### ISSUE TITLE
Some topic unable to be flagged for removal

### ISSUE THREAD

**Issue by WHATTHEDAN11** [Monika-After-Story/MonikaModDev#10182]
I've noticed that some topics can't be flagged for removal by pressing 'x',  for example:  "Natsuki's letter", "Natuski's death".  These topics can be bookmarked but cannot be removed for some reasons.

**Comment by Booplicate** [comment]
It doesn't make sense to derandom them.

**Comment by WHATTHEDAN11** [comment]
wdym?

**Comment by Booplicate** [comment]
Why would you derandom them.

**Comment by WHATTHEDAN11** [comment]
I just think its weird that these topics related to the other girls cant be derandomed. anyway, so basically those topics were intentionally made to not be able to derandom then?

**Comment by Booplicate** [comment]
It's not about them being about other girls. The topics should be derandomed automatically, what do you expect to happen when you press X on a topic that's disabled?

**Comment by WHATTHEDAN11** [comment]
I think u misunderstood what i meant, normally if u press X on a topic the top left will show "topic flagged for removal", but for topics such as "Natuski's death", when i pressed x, nothing happens

**Comment by Booplicate** [comment]
I understood you, so what do you expect to happen to the topics when you press X when they are already derandomed and cannot be rerandomed again?

**Comment by WHATTHEDAN11** [comment]
Okay, so based on what you said, those topics in the "repeat conversation" section that does nothing when pressing X,  are the topics that are already derandomed itself, even though they are within the "repeat conversation" section. Therefore nothing happens when trying to derandom them, correct?

**Comment by Booplicate** [comment]
The topics being under the "repeat conversation" section has nothing to do with not being able to derandom them again. Any topic that you marked with "X" will still be present in the section anyway, so you can bring it up yourself.

When you press "X" during a conversation, it marks the topic as blocked from random selection. The topics you're having issue with can only be seen once (Monika does not repeat them). When you press "X" during one of the topics, you're asking to derandom a topic that's already derandomed and cannot be rerandomed due to its nature (it's a PM var topic).

Which is why I'm asking what you're expecting to happen.

**Comment by WHATTHEDAN11** [comment]
ok. i just feel like it would be clearer if we would know that these topics cannot be derandomed since they naturally wont be mentioned by Monika again. Like before you telling me this i never knew PM var topics is a thing.  Perhaps maybe when trying to derandom those topics, a message like: "Monika won't talk about these" on the top left would appear, suggesting that these topics are the PM var topic)
