### ISSUE TITLE
Didn't gain any affections from bypass gifts

### ISSUE THREAD

**Issue by Kimura-stapen** [Monika-After-Story/MonikaModDev#10309]
[aff_log.log](https://github.com/user-attachments/files/17087892/aff_log.log)

So today is Monika's birthday. I decided to give most of the gifts to her today. I gave her the plushie, thermos, chocolate, hot chocolate, coffee, roses, and fudge. But as you can see from the log file, only fudge and roses is registered in the log - but they also resulting in 0 affection too?! what did I do wrong? they are all bypass gifts, right? the affection cap shouldn't even affect them. please, I need to know if this is a bug. I planned to give her the promise ring tonight, and I don't want to not get any affection from that...

**Comment by Booplicate** [comment]
Your log is truncated for some reason, but in short you did get affection, the log isn't a tool to track your progress.

**Comment by Justformas** [comment]
There's a good chance that people who ask questions like this read about affection in the all features wiki, which is outdated since about 2 years ago so understandably they could get confused over this. I think I have a pretty good understanding about the changes from then and could probably update it a fair amount. There's been several version releases since then. It could cut down on questions like this.

**Comment by Booplicate** [comment]
No thanks, it should either be removed or rewritten just to point out that it's not a progressbar of relationship.

**Comment by Justformas** [comment]
> No thanks, it should either be removed or rewritten just to point out that it's not a progressbar of relationship.

Progress bar vs progression system is what I want to clarify here first. It seems that a lot of things are still tied to affection, making it a progression system, but that doesn't make it a progress bar meant to be to be seen by the player. So it could be clarified that it's not meant to be seen by the player. But I also think it's accurate to say, as you said, that it's not the _full picture_ of your progress.

But the info that's already there, why remove it instead of correct it? Isn't the wiki meant to reveal (or spoil) such things? Even things not meant to be directly seen by the player are still part of the game and could be considered features. Gift names are another example of something you could say can't really be seen in-game, in that it's not obvious when a gift name is mentioned in game to someone who doesn't already know that it's a gift, and some gifts may not even be mentioned at all. But many of the things the affection section mentions can be seen in-game, such as the final farewell. That's certainly a feature. You're not saying things like that should be removed are you?

**Comment by Justformas** [comment]
I can probably generalize some things to discourage "abuse" of the system, like the soft daily cap doesn't need to have its range specified. Also the part that provides the specific values of 4 different action groups that affect affection is totally inaccurate now and can probably just be removed, unless you really think that it should provide the specifics on 8 groups now. Clarifying about the newer thing that can happen to bypasses also seems harmless and should reduce questions about it. There's a few other, very minor things that could be updated, along with clarifying about the intent of affection and the log.

Players who look at a page labeled "all features" and "spoilers" likely do have an interest in figuring out what can be done, unlocked, or worked towards and how. It may also encourage them to keep playing, rather than maybe stop playing quickly, such as if they think there's nothing more to the mod or to see.
