### ISSUE TITLE
[Suggestion] Bigender option

### ISSUE THREAD

**Issue by CinnamonGhostCrunch** [Monika-After-Story/MonikaModDev#10339]
As a bigender person it kind of sucks not being able to have that as an option lol. IDK if it'd be complicated to have Monika just randomly select what pronouns to use but it'd be a nice feature to have, just to make some more people comfy.

**Comment by dreamscached** [comment]
Unfortunately it's because of the same issue we face with a lot of other things where we can't just list everything, and adding a free input prompt for the user is not exactly desirable, as there's no way we can validate the input and let Monika have an appropriate reaction.

tl;dr *I assume* it wasn't added because there are just too many possible gender options and we can't possibly include everything

In the meantime, I think there are submods that can help you with it.

**Comment by Booplicate** [comment]
The whole thing is a mess. We changed it several times, but there were always people that didn't like it one way or another. Accounting for new genders and pronouns is impossible. The topic should be changed to just set the pronouns the user prefers with being able to add custom pronouns via submods (no free user input however).
Also see #6084
