### ISSUE TITLE
gifts

### ISSUE THREAD

**Issue by Rockyyyyyyyyyyyyyy** [Monika-After-Story/MonikaModDev#10338]
I can't seem to find where to find the gift IDs (example: hotchocolate.gift) and give them to monica... Is someone able to tell me what the gifts are? or where to find what gifts im able to give her?

**Comment by Justformas** [comment]
It was on the all features spoilers page but that seems to have been deleted. Would like to know why because that had a lot of helpful information, including piano notes for the songs and window reacts for websites that she reacted to. But we at least need another solution for gift names. Some exact gifts names like the thermos and the plushie aren't even mentioned in the game. 

If devs want to mention all gift names in the mod in the future and make it more obvious what is a gift, that's fine, but we need another solution in the meantime. I suggest that they be included on this page: https://github.com/Monika-After-Story/MonikaModDev/wiki/Gift-Giving-Guide or something similar.

**Comment by Booplicate** [comment]
Working on this

**Comment by Rockyyyyyyyyyyyyyy** [comment]
thank you!
