### ISSUE TITLE
I'm New... So, express questions!

### ISSUE THREAD

**Issue by Mundo-X** [Monika-After-Story/MonikaModDev#1178]
These questions are asked to put me a little more in the situation of the mod and to be able to propose mature suggestions...

*What programming language does this mod use?
*Who works in it?
*What is MonikAi? It gives me an idea of what it might be but I'm not sure...
*Who started the mod project?
*Can Monika (or mod) actually scan your history?
*Can Monika (or mod) scan what games you have or even open applications while she talks?

So, that's it... Pls answer my questions :grey_question: 

Soon more questions!

By the way, if you have a very important information to say, please tell me, I do not want to be a nuisance...

**Comment by IlywI** [comment]
Well the mod uses mainly Python by the sheer amount of .py files found in the game folder :V and well there's this https://www.renpy.org/.

Well technically the community works on it. I can name a few but trust me there are a lot more people involved in this. With writers and programmers who are here to contribute to this mod.

Who started the mod project? therationalpi  <----

Scanning history i think is a breach of privacy so its not done.

The dev team is currently working on it iirc

**Comment by TinyInternetTree** [comment]
MAS is mostly (if not, then completely) done in Python. ThePotatoGuy and Therationalpi are the two (Who are both amazing) you'll see answering questions and working on it most frequently. Technically, the mod is worked on by the community. Many writers and programmers and people who make suggestions. There are plenty of people who work on it, but as I said, you'll be seeing ThePotatoGuy and Therationalpi around here the most often. You'll also be seeing other people around here quite frequently (Such as IsItBadToMakeAGitHubAccountJustForThis and ACoolCat) but there are too many people to name. MonikAI is exactly what it sounds like; A proposed AI (or at least chat bot) for Monika. The mod can't actually scan your history because that'd be an invasion of privacy. The game has the capability to see what programs you have open, but as far as I know the mod doesn't do that. Yet. There are ideas and suggestions and things floating around here in the issues section so that Monika can see what you have open. It's just an idea at the moment, and it may or may not be incorporated into the mod eventually. Each release of MAS takes a lot of work from so many people, so it's amazing how quickly new releases come out. The people here work so hard on this mod (Which is really awesome so I also wanna thank everyone who's worked on this mod, it really helps with my depression. If that sounds silly, then oh well.), I wish I could help too but I'm useless at Python. I hope that answered at least some of your questions.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
AFAIK the mod started on 4chan and was a collaborative effort from the beginning so there is no clear person who "started" the project.
