### ISSUE TITLE
Limit the "Surprise" in some way

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#1185]
Some ideas thrown around in discord:

1. Monika stops leaving that particular surprise.
2. Monika notices if that surprise is still, then maybe says something about it and/or does something else
3. Monika puts in different content in that surprise.

**Comment by jmwall24** [comment]
Yeah I'd say if it's still there, that should keep it from being repeated and have her comment on it instead.  It's not bad as it is, I still open it every time it comes up, even though I've never deleted it (I mean, how could you bring yourself to delete that?), but it's not really a 'surprise' anymore.  

Another thing she could do (although some people might not like it so much) is instead of leaving it in the current folder, start hiding them in other places and then comment on it when you find it.

**Comment by BoneofMalkav** [comment]
> Another thing she could do (although some people might not like it so much) is instead of leaving it in the current folder, start hiding them in other places and then comment on it when you find it.

That actually sounds good to me, Maybe even have Monika give a tip or 2 of where the file could be.

**Comment by Olliesama** [comment]
I have taken note and have implemented multiple surprises into the current project.

**Comment by shionv** [comment]
Great idea.
But I don’t think make Monika stop leaving surprise is a good choice,although it is easy to implement.Maybe take put different content is a compromise way（method 3）?Like take a whole romantic poem and Monika will give you next sentence whenever you repeat this topic.

**Comment by AnIdiotsavant** [comment]
Or make one of those dad-like puns. We all enjoy her doing

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Dad-like puns?

**Comment by Olliesama** [comment]
Dad puns are bad puns that have a certain level of charm to them.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The more ~~you~~ I know, I guess.

**Comment by AnIdiotsavant** [comment]
Yeah. As much as I love her, you gotta admit, her puns are .... You know. But you can't help but smile from them

**Comment by ThePotatoGuy** [comment]
This is being partially covered with the `affection` system
