### ISSUE TITLE
Conversation topics ideas

### ISSUE THREAD

**Issue by Mundo-X** [Monika-After-Story/MonikaModDev#1201]
Um... No, I'm not giving conversation topics.
Specifically, I'm asking interesting conversation topics.
I've been learning a bit of Phyton and I wanted to help create at least 10 themes to help the mod to be more interactive.

My themes will have a lot of interactivity, how time, gender, battery, menu options, among others ...

I hope you give me ideas because I'm not very good at looking for topics and less giving the "voice" to Monika ('._.)

By the way, how can I comment on the Discord server? I wanted to publish the codes there...

**Comment by TinyInternetTree** [comment]
https://discord.gg/K2KuJeX 
Discord can be found in the contributing guide at the bottom, if anyone else wants to know. 

I've got a topic which could be interesting to write about: Dialogue for running MAS as an administrator. I actually made a separate [suggestion] issue about this, but since you're asking for topics you might be able to do something cool with the idea.

**Comment by kaido1224** [comment]
Check out #writing in the discord above for discussing writing topics.
