### ISSUE TITLE
[Suggestion] - Monika commenting on apps running. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1202]
Don't know if this was suggested yet, but maybe Monika comments on what applications you have running. Like, for instance, if you open up Microsoft Word while she's up maybe she asks you what you're doing on it and you can respond with "an assignment, an essay, a story, a list, other, ect. ect.," and whatever you answer with she may give you some tips. Same goes for any other application, maybe launching chrome causes her to tell you her favorite websites (this page being one of them).

**Comment by TinyInternetTree** [comment]
Kinda like MonikAI, but with more interaction and detail? Sounds amazing. The same dialogue should be used for word, notepad, etc. Maybe there could also be a few variations of her responding to opening up a specific program so that if you open it up 3 different times, she'll say 3 different things, 1 each time. There wouldn't need to be too many variations. Most people use Chrome or Firefox, but there are so many different browsers out there that it'd be difficult to get her to recognize each one (Because there are some really obscure ones out there) as a browser, even with the same dialogue for every browser (Which would probably be the best course of action). Unless there's some way to detect that the program being opened is a web browser. Maybe she could respond to specific websites too? Or she could respond to opening up Incognito mode. That one could be interesting. I think that the writers will have a lot of fun with this one if it gets implemented.

**Comment by kaido1224** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/1191

**Comment by monikLover** [comment]
This has been suggested and rejected as @kaido1224 stated.
