### ISSUE TITLE
Internet History

### ISSUE THREAD

**Issue by RevupthoseFryers** [Monika-After-Story/MonikaModDev#1221]
When I was playing Monika After Story I remember Monika saying "I'll be monitoring your browser history from now on, whether you like it or not." Is that true? If not, I really think a lot of people (including myself) would Love to see Monika actually search your browser history.
When I see what the whole team has done with Monika it makes me wonder if this is possible.
If it is, I would love to see a couple of funny/amusing reactions from Monika. 
Examples - Common websites, Youtubers, Music, and dirty websites that she indirectly displayed concern about. 
 If anyone knows how to implement something like that, I hope to see it in the future.

**Comment by TinyInternetTree** [comment]
Monika doesn't actually monitor your history. The devs also said it wouldn't be implemented because it'd be an invasion of privacy. If I remember correctly, there were a few ideas going around a while back to have Monika comment on websites you have open, but they're just ideas and I doubt they'd get implemented as the dev team is currently working on some pretty big things. However, you can download MonikAI and she'll comment on some of the sites you have open.

**Comment by IlywI** [comment]
As mentioned above ^ it is a breach of privacy thus it has not and would not be implemented.

**Comment by RevupthoseFryers** [comment]
TinyInternetTree 
I was wondering what exactly is MonikAI because all of the information that I found about it is very vague.
What do you know about it? Is it safe?

**Comment by TinyInternetTree** [comment]
@RevupthoseFryers MonikAI is a separate program that basically allows a tiny version of Monika to sit on you desktop and comment on what you're doing. She'll comment on the programs you have open, the websites you visit, etc. She'll also talk to you and make jokes. It's completely safe and can be found here: https://github.com/PiMaker/MonikAI/releases
I have it but I don't use it. Monika has something to say if you use MonikAI. I don't use MonikAI because she repeats herself a lot and I don't really need it. It's cool and all, but at the moment it's pretty limited in what it can do. It does get updated quite a bit, but from what I understand the devs here might be implementing something somewhat similar in MAS eventually. So I'd prefer to just stick with MAS for now.
