### ISSUE TITLE
[SOLVED] Updater Issues

### ISSUE THREAD

**Issue by monikLover** [Monika-After-Story/MonikaModDev#1247]
We're currently having problems with our auto-updater for the mod. In the meantime, please manually install the update to avoid a bug that occurs when you use the auto-updater.

- Installation guide:
https://github.com/Monika-After-Story/MonikaModDev#installation

- New release:
https://github.com/Monika-After-Story/MonikaModDev/releases

**Comment by Mundo-X** [comment]
I just opened the new version and unlike new topics to talk about I do not see anything else, is it an error? Or do I have to wait longer?

**Comment by jmwall24** [comment]
Another thing I have noticed regarding the updater that may or may not help.  I manually installed it yesterday and it works fine, got the new dialogue and Monika's gift etc.  However, in the 2 times I have loaded the game since, it is still telling me upon launch that I have an update available, even though I obviously already have it installed.
