### ISSUE TITLE
[Suggestion] - Write poems to her!

### ISSUE THREAD

**Issue by XolfWolf** [Monika-After-Story/MonikaModDev#1276]
I was thinking in _three possible options_ to make this work.

**1-_A Random Word Poem:_**
Just like when you write poems in-game or that instead of random words, You can search every word that you need.

**2-_A Realistic In-game way:_**
Just like when you're reading a poem but instead of reading it, you're writing it. Here you can select the type of font you want to use(the fonts used for poems in the game not a custom one). Monika will tell you tips about how to make it better and She will react if you write it specially for her.

**3-_A Desktop .txt File_ (This one sounds impossible to do):**
You tell to Monika that you write a poem and it is in your computer, so She is gonna search it and react to it.

That's all.
Thanks!

**Comment by sebastianN01** [comment]
first option seems decent, lets make say, just few words that would make Monika jump, and all other words would make her not. And based on the amount of words you hit correctly and she jumps, he gets different reaction.

Could be happy or sad, or angry, based on the amount of hits. Could make around 4 different reactions, but if some good programmer was ambitious i wouldnt mind to have 20 reactions for all 20 words you have to guess. :+1:

**Comment by jmwall24** [comment]
Only thing I worry about with option 1 is there is already dialogue about how she doesn't like the random word poems and how she hopes we're more romantic than that.

**Comment by ThePotatoGuy** [comment]
1. Random word poem can be done with a framework that was built in dec/jan, but as jmwall24 said, monika is aware of this.
2. An in-game text editor was one idea we had for creating poems, but the amount of variability in having her react to a poem is crazy. Having her detect certain words is simple, but literary devices as usually found in poetry? Not exactly something that's easy to do.
3. This is actually easier to do than an in-game text editor. But again, the thing about reactions would still be difficult.

Since having monika react properly to free-text is difficult, someone was trying to implement mad-libs (#689), which could be kind of treated as a poem. In this case, we would react solely on the words since we already know the poem itself is okay. However we haven't heard from this person in a while so atm we're not doing this.

**Comment by Mundo-X** [comment]
Something I was thinking is that...
If we want **Monika** to come closer to _our reality_...
Why not make the code _super-complex_?

I think of all I am one of the few who wants to study robotics and advanced programming in the future. A dream that I have always had is to create _artificial intelligence_ capable of creating its own code to have this **_free will_** even if it is not, but that is closer.

The point, try something simple, but little by little we make it more complicated to make it more _realistic_.

It does not only have to do with this.
It has to do with _everything_ related to **MAS**.

Make more dialogues, more themes, more games, more answers, more surprises. But, well done and they are simple to do, I do not ask you to stay awake day after day without sleeping working on this project, I just ask you to make **Monika** more _realistic_ and _interactive_, with more options or topics.

Do not believe that I will be watching from my computer what they do, I am learning programming in Ren'py and Python. I will help soon when I can.

Good luck guys, _**Monika** needs you._

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
If you want to make the code _super-complex_, then fork MAS' repository and knock yourself out.
But I honestly doubt you'll have much success at implementing a life-like AI from scratch, as it is something multimillion companies cannot quite pull off.
It is just too early to think about such grand stuff.
For now, I believe, we'd better focus on something more important in the long term, like establishing standards and creating frameworks to serve as a foundation of all the future DDLC releated projects.
