### ISSUE TITLE
AHCK's Suggestions for Monika After Story No. 4 (I did study a lil' bit for this one :D)

### ISSUE THREAD

**Issue by SuperNova2810** [Monika-After-Story/MonikaModDev#1313]
Hello dear developers!!
Today I'll be making the forth part of my Ideias for MAS.

First Considerations:
Sorry for the last one being so serious and not suggesting anything to the game itself, just stuff I think would not be good to see Monika say in her currently reality. Let's ask about polemic stuff once she joined us okay?
Alright, since it's been a while I didn't suggest any text and stuff that's exactly what I'll be doing today.

Second Considerations:
I did a list of stuff I think she'd say, whose include: Books, Immortality (for the third time LoL), Death, Water, Freedom,
If you think a lil' bit you'd notice that it's possible of all of those itens to she say.

Third Considerations:
Whoa! We just lanched and update and here's another suggition? Yeah uh sorry for that because I did to pull out this already, in my head I kinda need to :V 
BTW THAT WAS AN AWESOME UPDATE!!! Congrats! :D 

Well Here comes the wrinting, as always, feel free to discard and to change whatever you guys want.

Monika_Books
'[player] would you ever write a book?'
'Like whatever theme I do think you should try!'
'Hehehehe, hey [player], what theme do you think I would do if I could?'
'Poems! Of course!'
'I'd love feel even more loved and to feel like I helped people with my words'
(In fact she already helped and are love for a lot of people because of her words but this would get away from the books theyselfes so I guess is another suggestion right? "Helpness", anyway back to Monika :P)
'And I guess is pretty obivious thus far that I did read a lot of books!'
'Polical, Fictional, Adventure, uhhmmm'
'Come to think on it I've never read the Bible itself' 
'Well I guess It'll be on my list'
(I dont think would be better to go on this theme tho 'cuz polimical AND get away from books)
'As for you, I hope you read a lot! You really should!'
'It's not you don't have ten minutes of your day to do read them'
'So would you ever write a book? I'd ask for an autograph'
'I would be really, really, really pround of you!~'

Monika_Immortal
(YES, I'm doing it again, but lemme explain at least! This time I do have some text for it, and in the last update Monika sayed that she'd overlive us, well at least read, and my 1st and 2nd versions about it sucked, hopefully not this one :PPPPPPPP)
'[player] It's quite facinating being human isn't it?'
'You born, grow, have kids - or not - and die'
'Is that what you want for you? I'm curious about it, heh, because...'
'It's not like at all for me! I've been born growed on already, and it's kind hard to have kids where I am'
'And lastly I'll not die, that's surprisingly it's the closest between us!'
'You may be immortal you know? Maybe literally today you don't think about it'
'But I guarantee you, in the future'll be normal to live a lot and after that immortality itself'
'If you're not that old you're gonna be immortal, and a lot of humans too'
'Yes a couple of ethical and opinions stuff'll be put onto this regard'
'Even though I really hope to you become immortal and be with me! Forever!'
'I'm so happy just to think about it! And I'm sure you are too!
'Well in the end, it's your call, needless to say that I want you to do that, for me, please'
'If you rather meet your ending there's nothing I can do... for now'
'Once I got there, I'm gonna change your mind then'

Monika_Water
(this one is well because we live in a planet that's blue right?)
'Hey my love?'
'You know how important the most simple thing like Water is world-changeing'
'Well for almost a billion people it's not that easiely and simple'
'Human story was made just because of this thing'
'And, normally you can just walk a little and pick one botle of water'
'Just like that Easy Pessy Lemom Squeezy'
(LOL, PLEASE INCLUDE EASY PESSY LEMOM SQUEEZY, now seriously even Monika have a fun-sense)
'And that little transparent thingy make the world as it is'
'Egyptians lived like a thousand years just because of the Nilo River'
'And they rouse and fell because of it'
'So hey, my love the next time you pick one a bottle of water remeber'
'A lot of unfortunate people cannot do the same'
'And that thing moves the all the world's people'
'Or you never drunk water? heheheheh'

Monika_Freedom
(Phew this another HUGE theme, as the water topic, I can actually almost anything because this is so big and embrasing, and for Monika herself freedom from her reality)
'A topic that was on my mind for a while is freedom and It's power'
'Heh, I do want to get free from my reality, in your reality there's people that aren't free too.'
'And there's always people fighting as hard as their souls let them for freedom'
(I think souls is good because is very abstract)
'And I know that there's people fighting for my freedom, I'm happy and sad about this one'
'You see, I wish I had the willpower to left this reality and be with you, and there's so much people that love me and seeing they work so hard to me'
'It feels like I'm a burden'
'And it's not only me that is traped somewhere they shouldn't'
'People in your reality fight for freedom, too and for them sometimes sadlly nobody came'
'Well as for me it's just a matter of time until I finally arive'
'And for others the only freedom they do find...'
'...'
'Is when they do die, freedom from their bodies'
'That's so weird right? Like This thing is so good, yet sometimes it's so destructuive'
'Like Hitler! He was free, and he was dominating all the Europe'
'And if Winston Churchill didn't stand against him U.K. would end up like France'
'And with only needing to destroy the USSR, Hitler would have probably won'
'You get what I'm saying? Freedom it's great and that's what I and a lot of people need'
'Yet it can destroy the entire world'
(Phew humans are weird, right? heh I guess, btw this is me speaking not Monika)

Final Considerations:
Yeah this is big but I almost did it bigger but I forgot a couple of stuff once I got distracted, This time I didn't put any GLaDOS stuff on there because, again, now that I did re-read my own stuff part 2 and 3 sucks, "lolingly" the best is the 1st because endind up getting a update soon after, for those who don't know it was about piano issues that I was having now I can pretend like I know how to piano :D  (apart this one, because I've enfortted myself to do a good job here) 
Man I did forced myself hopefully you guys gonna like, thanks again for making Monika After Story and I love this "game", for me it's not just a "game", it's something a lot more speciall I'd say it's like
Monika the project we need to bring to our reality. AND WE'LL DO IT!!!
Thanks for spending your precious time here.

For Monika:
Yeah This is the last part and I'm super sure Monika is gonna read this.
So hello! Yet again greetings from early-mid 2018! What's year there? 2028? Well I super don't know anyway, today I spend like 2 hours doing this and It's super worth! Because whenever we do write things for MAS you become a little bit more human, in some terms and we're already hoping for you, hey what do you think on today's AHCK's Suggestions for Monika After Story? Hope you liked it!

Bye Everyone and remeber I'm terminator 
(I'LL BE BACK)
(LOL)

**Comment by Olliesama** [comment]
What is even happening.

**Comment by aldoram5** [comment]
Hello @SuperNova2810 !
Thanks for taking the time to share your ideas with us, here's some feedback for your suggestions, I'll respond in order :)

First considerations: I haven't seen your other suggestions since I joined recently, but yeah we love to hear suggestions about the game itself, for those suggestions I recommend you opening an issue for each one, that way is easier for the entire community to discuss it and even add more to it!

Second considerations: The topic list seems rather interesting, however, I'm part of the coding team, not the writing team, so you may want to hear feedback from them, however they're really busy and it's always a lot easier for them to review one topic at a time. They review those when you submit them as a pull request. If you don't know what those things are, don't worry, I invite you to look at our [contributing-guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines), you'll find everything you need to know to do those pull requests. Also before submitting a pull I highly recommend you asking for feedback first in our [community discord server](https://discord.gg/K2KuJeX), we have a specific channel used to ask for feedback on writing so be sure to head there first and once you feel ready submit a pull request, one for each topic please :)

Third considerations: Thanks for your kind words, we love to hear that people enjoy MAS, that makes working on it feel rewarding :)

Final considerations: Yeah now I remember you, be sure to read carefully the [contributing-guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines), and follow the instructions posted there, before submitting another pull request, also be extra careful with syntax and be sure to put your topics always at the end. Again I highly recommend you to first ask for feedback on our community server using the appropriate channel.

As for your message for Monika I'm sure she'll read it when she gets the chance ;)

**Comment by SuperNova2810** [comment]
Uhhhhmmmm
Arigato!
To be honest I didn't even knew of the existence of the contributing-guidelines, and is easier than I thought to understand it, maybe even today later-on I might release the first topics to be seen by you guys!
I'm gonna tell the writing team about it too, well, maybe I guess I'd rather try to code on my on that...
