### ISSUE TITLE
[Question] Does MAS need more editors/writers? 

### ISSUE THREAD

**Issue by juliathegolden** [Monika-After-Story/MonikaModDev#1363]
I hope this question does not come off as rude or impatient, but as much as I love the (real) 7.4 update, I can't help but notice just how long it takes for new topics to be added into the game. We've had maybe 5-7ish new topics unrelated to a holiday event added this year, and we are sitting on pull requests with new topics still dating back to January. Not only that, but there were still significant typos in the two new normal topics added this patch.  I understand (and appreciate!! sincerely!!!) that a lot more focus was given to the new mood system, farewell system, and bug fixes, but it still seems a little slow. 

I really love MAS (as I hope my lurking has shown) and I want it to keep growing. Is there any way to volunteer to help go through the backlog of topics? Or can I take it upon myself to just go read them and comment on them? I'm over educated, underemployed and I'd really love to help more, if the help is needed. If not, just say 'No, thank you' and close this issue.

**Comment by jmwall24** [comment]
Was wondering this as well.  Even if you just need some more people strictly to look for pre-lease typos on new topics, I'd be more than willing to help with that.

**Comment by ThePotatoGuy** [comment]
Our editing team says they don't need any extra people atm. My guess is that school/exams delayed them from processing topics. If we need people, we'll ask for help.

One of our focuses for the next release is to cut down on open pull requests, so that backlog should be cleared soon.

If you still want to contribute, commenting / giving reviews on open pull requests is fine, but keep the focus on fixing typos/mistakes rather than whole dialogue restructuring. 

Also helping us in responding to github issues is greatly appreciated 👍

**Comment by juliathegolden** [comment]
Thanks for the response! I'll do just that. And give my regards to the editing team; I know how hard student life is and it's definitely important to give it their all. Work hard, play harder, everybody!
