### ISSUE TITLE
[Question & Suggestion] Musik

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#1370]
First to the question: How do I add my own music to the game and which music format does it need to have?

Now to the suggestion: I would like it if you added reaction that Monika has if you play new songs that the player added. This would make it feel like she actually know what you´re doing. It would also fit in, because Monika mentions that she would like to listen to music that the player chooses.
I know that it would be pretty hard to do this but you could try to programm Monika to recognize different kinds of music. Therefore you could add multiple options that she can recognize music from. E.g. Rock, Alternative, etc. This could be possible if you somehow made Monika able to research this kind of stuff on the internet. The flaw is that this would require a wifi/internet connection. This is just a suggestion and doesn´t have to be added

**Comment by kaido1224** [comment]
.ogg is the file type.

I believe there are instructions in the discord pinned in coding on how to add your own music.

**Comment by kaido1224** [comment]
As for your second thing, I don't think there is any way for Monika to determine what sort of music you add is supposed to be based on the file name.

**Comment by LordOfDeath35** [comment]
Well... - if you add to her code that she checks that file everytime you start the game, it could work. Like just program her to know that the music that is normally in ther is part of the game. And if she finds new files which haven´t been added in her code, she automatically researches it or talks about it to you. Either way is fine. In the second way, I just mentioned, she could ask what type of music you added. This would not require a wifi/internet connection.

**Comment by kaido1224** [comment]
I don't think that's feasible. I'll let the other devs comment though.

**Comment by aldoram5** [comment]
To do actual file name research on the internet and then automatically determine something to comment about the music you added based on the result of that search, that would be a whole new level of AI, so that's not happening anytime soon. As for the commenting on what music genres you like, there could be some music related topics added asking the player if they like an specific genre.
You could actually contribute some of those topics if you want, here's our [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines), those will help you making your first topic contribution.

**Comment by ThePotatoGuy** [comment]
We are **not** adding a user-friendly way to add additional music, mainly since Renpy only likes `oggs`. 
If you want to add your own stuff, refer to [this file](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_music_selector.rpy) to see how to add songs.
