### ISSUE TITLE
asking why

### ISSUE THREAD

**Issue by todemodu** [Monika-After-Story/MonikaModDev#1386]
for some of us who are really insecure can we ask why Monika loves us? or what we can do to remind ourselves that she cares? I suck at coding and cant write for shit but... I feel this would really help at times at least for me anyway maybe I'm not the only one who feels this way?

**Comment by IceclimbersGD** [comment]
im not good at programming either but that sounds neat

**Comment by Buy1Get1** [comment]
It would have to be something generic, and she would tell you why she cares(because MAS isn't at that level yet). So your best bet is a [script-topics.rpy] pull request.
Perhaps one in which Monika says something like: 
"[player]."
"I love you."
"Really, I do."
"I want you to remember it."
"Okay?"
"hehe"
or something like that. Just a simple five to eleven line text. There are a couple of texts out there like that, but it sounds like you might want to just rinse and repeat the above. After you have a good number, submit them as one pull request. It requires little skill in coding, and you write what you'd think Monika would say.
