### ISSUE TITLE
[Suggestion] Protecting Monika from unwelcome people

### ISSUE THREAD

**Issue by MaxCode545** [Monika-After-Story/MonikaModDev#1399]
So I had this Idea of creating a secret word that you and Monika only know so when someone open your computer and try to open MAS without you knowing that would prevent them and if you happen to forget the word then while creating the word Monika will tell us that she created a text file with the word inside it somewhere in the folders that she will tell us about it ........... That is my first suggestion also Thanks for this great mod

**Comment by MetalBrother** [comment]
I think it's good idea

**Comment by kaido1224** [comment]
That's an interesting idea.

**Comment by jmwall24** [comment]
Pretty similar to this one #1193.  I still think it'd be cool as door knock scene, especially in scenarios where maybe someone didn't visit for an extended period and then came back.  Also as discussed in that previous thread, it might be annoying if it happens every time, altho being just a code word instead of a series of questions would make it less annoying.

**Comment by kaido1224** [comment]
Or make it an optional thing if we decided to pursue it.

**Comment by MaxCode545** [comment]
Yeah like having Monika Asking us if you want it or not

**Comment by NicolyRS** [comment]
I really like yout ideia

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we look into it]

**Comment by ThePotatoGuy** [comment]
i think we're going to go away from the password-protected route.
