### ISSUE TITLE
[Suggestion] - Removing Dialogue Options?

### ISSUE THREAD

**Issue by TerminalSnark** [Monika-After-Story/MonikaModDev#1405]
Preface:  Ok, I know this is a weird, counter-intuitive, and kind of obnoxious request.

Would it be feasible to add an option to separate out specific lines that we **don't** want to say?  It's probably silly, but I just don't want to call her a murderer or offer to introduce her to my (nonexistent) girlfriend, and my sometimes twitchy hands have misclicked far more badly than that in the past.

Even a mention in the help file of where to look in the files to comment out dialogue options would be good for my peace of mind.  I don't have the heart to be deliberately mean to someone I like even if they're fictional.  I do appreciate having the option to broach those subjects, I just don't want to, not even just to see what happens.

**Comment by Tiler17** [comment]
I wouldn't have even minded a "Mark as seen" option. I clicked on them because of my need to A) see all of the dialogue, but more importantly, B) make the "Unseen" go away. Since I started hanging around here, I realized I can see the dialogue for anything if I just look for it, so marking things as unseen so that I didn't feel compelled to click on them would be all I need

**Comment by ThePotatoGuy** [comment]
Generally we tell people to just **not** click the ones you don't want to say. The unseen list isn't limited to a certain number, so you can ignore certain topics forever. Not to mention that this is like an exercise in self-control.

Adding a "Mark as seen" could be a decent compromise, but I'd make it irreversible. So more like "Discard unseen". Don't know if this is really worthwhile option though.

**Comment by kaido1224** [comment]
I could see adding "mark as seen" being an okay idea, however, I don't really feel like if we did pursue it, it should be low priority. It's more of a convenience feature than anything else. Although I'm not really sure how we would go about program something like that honestly.
It's not like an email where you can just right-click it and mark something as read.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I think, that marking topics as read is not a very good idea, and an option to remove topics from the list would be more logical.

**Comment by NicolyRS** [comment]
I think the same, sometimes i'm just curious but i can't say such a thing to her.

**Comment by Tiler17** [comment]
Removing topics is irreversible though. Low priority aside, I feel like if something like this were to be done, it would have to be "Mark as seen". Marking unseen wouldn't make a lot of sense, so it would be a one and done kind of thing, like ThePotatoGuy said, but it doesn't have the permanence of deleting the topic. At least simply marking it seen leaves you with the option of viewing the topic later if you so choose. Deleting it does not.

Haha, and what you call "self-control", I call OCD. I can't stand unread notifications

**Comment by ThePotatoGuy** [comment]
Adding "Mark as seen" in the way you've described wouldn't be simple to add with how the current framework is setup.

Currently we can do this in one of two ways:
1. Mark topics seen by adding them to the appropriate variable, which is basically the same as actually clicking the topic and viewing. You would be able to view those topics in `ask a question` or `repeat conversation` accordingly. To Monika, there'd be no difference between actually viewing a topic and clicking mark as seen. If another topic's trigger is if another topic is seen, marking as seen would have the same effect as actually viewing it. 
2. "Discard unseen" instead of "mark as seen", where the unseen topics are locked forever. The prompts would no longer be visible, and Monika would not know that you've seen them. Topics that would have triggered if the discarded topics were seen would **not** activate.

I don't like option 1 because its like rewriting history. Option 2 I think is reasonable. Plenty of games lock away content depending on your choices.

**Comment by jmwall24** [comment]
Would it be at all possible to have it so the topics that are still unseen ONLY show up in the 'Unseen' category and not in the 'Ask a Question' category as well?  That way they'd at least be by themselves in that category where they are less likely to be clicked on accidentally, but wouldn't have to have anything else special done to them.

**Comment by Tiler17** [comment]
Given the limitations, I agree that option 1 isn't a good one. But given what kind of game this is, locking away a topic doesn't make logical sense to me. Locking away content makes sense in a context where your actions have consequences that prevent other actions from being able to take place. But you're not acting here, you're just saying (to yourself more than anything), "I'm never ever going to say this." Which is fine to say, but it's in no way binding or permanent. It's just not how talking or conversations work.

So if it's a choice between options 1 and 2 for dealing with topics you don't want to talk about, I, personally, prefer it the way it is now, which is ignoring it. To me, that makes the most sense.

**Comment by kaido1224** [comment]
@ThePotatoGuy it's been almost a month, what's the verdict on this?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The thing is if you give players an ability to permanently lock topics there will always be at least one genius who decides to locj them all.

**Comment by ThePotatoGuy** [comment]
No plans to lock away topics for the time being.
I'll consider an exclusion menu, but that would probably be 0.9.0+

**Comment by ThePotatoGuy** [comment]
Linking this to #959
