### ISSUE TITLE
[Suggestion] - Ask Monika about eating bugs?

### ISSUE THREAD

**Issue by Icep0wder** [Monika-After-Story/MonikaModDev#1414]
I'm curious of what her idea would be about it, since it shouldn't contrast with the reason why she choosed to be a vegetarian

**Comment by juliathegolden** [comment]
I think her opinion on it would be something like. "Logically, I know it's a good source of protein and it's interesting how in some cultures, it's no big deal...but I'm a product of my environment. I can't imagine myself doing it.  That's gross. I'm sorry."

**Comment by kaido1224** [comment]
If someone wants to write a topic about it, then go ahead. The instructions for contributing are below. It's more likely to be added to the game that way rather than waiting for one of the devs to get to it.

https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

It's really up to the editors to decide the suitability of the topic, so let's ask them what they think.

@Subzerosan or @monikLover is this topic suitable for MAS?
