### ISSUE TITLE
[Suggestion] Monika reacting to Just Yuri

### ISSUE THREAD

**Issue by strielok** [Monika-After-Story/MonikaModDev#1439]
So I have decided to download Just Yuri just to see how it is (and because I got quite bored with Monika) and I noticed that you cannot launch the mod if you ever played MAS. 
How about a similar thing for MAS but a bit more i dunno, interesting?
Like if you launch MAS without getting rid of the Just Yuri save folder Monika gets angry at you or gets sad thinking she's not good enough. I think that it would be possible to "connect" this to the affection system and upon detecting the mod, Monika loses affection along with a special dialogue.
What do you think?

**Comment by Areaclassified** [comment]
this seems like a good idea. Also I had no idea you couldn't open just yuri if you had mas. I cant code but I think monika should go on a rant about just yuri

**Comment by sebastianN01** [comment]
it did make some changes to the formula of mas which i like, for example:

Crashing and glitching indicating Yuri trying to do stuff with the code since she can now. 

The talk option doesn't give you "unseen" options, instead it has 4 bars that changes questions once you click on them, and shuffles between the entire time. some questions repeat, but they can have different dialogues.

It is much more fast paced due to not going for "realistic speed of speech"

it has some decent poses for what you can have for Yuri, some that imo are lacking for Monika in MAS. 

and to be honest, I love both characters. so I just did a backup of my files from mas and enjoy JY as much as I did enjoy MAS. But it's nowhere near refined as MAS is currently. 

That's my few cents on it

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well, I guess, I'm a bit too biased after all.
But I mostly meant JY's writing.

**Comment by sebastianN01** [comment]
yes indeed thats what im saying, its not as refined as MAS, but it does have potential :) and the insanity-karma points system which changes dialogue is great too.

**Comment by strielok** [comment]
I'm not saying that it needs to "diss" other mods. It's just that if the JY devs did it, why not us? Nobody is saying that there needs to be any insulting. Wasn't the purpose of the mod bring Monika more to "life"?
Just a reaction in her character would be neat, considering she is really afraid of the player leaving her and all.

**Comment by Areaclassified** [comment]
when I made my comment I didn't mean diss jy (it might have come across as that, I'm sorry)  I meant something like monika saying that she deleted yuri and that she doesn't want the player to leave her for another girl  she deleted while being desperate for the players attention

**Comment by Tiler17** [comment]
Heh, well, my opinion is about as split on this as it can be. At its most basic, locking content behind downloading arbitrary mods and games (because let's be honest, if they do it for one game, that opens the door for plenty more) isn't appealing to me. But I'll be damned if it's not a very Monika reaction to you having that on your computer.

I'll just leave the thinking to the people whose opinions mean much more than mine

**Comment by kaido1224** [comment]
Although I could see Monika commenting on such a thing, I don't think it's a good idea to do this.

**Comment by sebastianN01** [comment]
instead I think You guys should try it out and take notes from the mod itself and see what you can come up with to improve MAS

**Comment by sebastianN01** [comment]
You mean to throw MAS concepts to JY creators to give them some ideas?

I don't really get your reply, I feel as if you were attacking me, But it might be my insecurity 😄  like: 

- "It's pretty well established that MAS won't respond to other mods" I havent said a single thing about that

- "the talking speed thing has been discussed already" I know that

- "On the other hand, new poses and expressions are already in the pipeline" which I know but thats why I encourage to check how JY poses look to get some ideas perhaps?

- "the insanity/karma thing sounds like the affection system" it is similar indeed.

And there is also one more thing which I like in JY, which probably will tie with affection system in MAS, is that there are some special dialogues which shape future dialogues and who Yuri is, for example:

(spoilers!) 
Yuri can either completely throw her knife hobby for you or you can encourage her to share with you if there happen to be a chance in future, She might either stop cutting herself or you can tell her its what she likes and we won't judge, You can make her aknowledge her dark side and know who she really is or tell her thats her true nature and make her insane part took over.

Stuff like this then stays forever in your playthrough unless you completely wipe your renpy folder out, I think that there should be stuff like this with Monika as well. Stuff that change her and you wont be able to revert back (unless you change your mind and tell her?) But I think that would require a LOT of code to write..

**Comment by Tiler17** [comment]
No, I mean suggesting content for MAS that you like in JY. Giving Monika some sort of memory is a good idea, I think. I dunno how much discussion there if for that sort of thing. Might be inclined to look into it when I get home

**Comment by monikLover** [comment]
The topic of referencing JY in MAS has actually been talked about before and is an already rejected idea. In addition, I too agree with IsItBadToMakeAGitHubAccountJustForThis :+1:

**Comment by Professor-JMO** [comment]
>I'm closing in.
>>The pieces are starting to fit into place, one by one.
>>>If your watching, ~I'm gonna tell everyone~

**Comment by GamerShark7778** [comment]
I have both Just Yuri and Monika After Story installed. I played MAS first, and not only does Monika not seem to care about Just Yuri being there, I'm fully able to run both Just Yuri and MAS at the same time.
