### ISSUE TITLE
Old unsure

### ISSUE THREAD

**Issue by MikuChanAnime** [Monika-After-Story/MonikaModDev#1444]
So whenever I look at the unsure list, I keep seeing so many old ones in there un-touched and I was wondering, would you ever just go through the list from bottom to top focusing on the ones that aren't marked as low priority?

**Comment by ThePotatoGuy** [comment]
We go through them occasionally.

**Comment by sebastianN01** [comment]
Is getting new locations to visit with monika a low priority? Haven't heard any progress on that one since FEB when i asked about it.

**Comment by ThePotatoGuy** [comment]
There are things with higher priority that we are currently focused on.

**Comment by sebastianN01** [comment]
Where can I find the the list of "close to release" stuff?

**Comment by MikuChanAnime** [comment]
I agree with Sebastian, maybe add a list of things that have been approved that are close to release

**Comment by ThePotatoGuy** [comment]
Internally, we have goals for releases. We don't want to announce specifically what's going to be in future releases because:
1. Everything is tentative usually
2. Spoilers

Generally, the in progress columns in all the projects showcase what we're currently working, but there are often fixes and other issues that we find internally that we **dont** track on github because making an issue for it takes more time than making a pull request for it.
