### ISSUE TITLE
New update error

### ISSUE THREAD

**Issue by Alefe8900** [Monika-After-Story/MonikaModDev#1491]
I install the 0.8.0 version and when I start the game this error appear⤵⤵⤵⤵⤵
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/1958109/traceback.txt)

**Comment by aldoram5** [comment]
That's because you haven't done the update correctly. Make sure you follow the [installation instructions](https://github.com/Monika-After-Story/MonikaModDev/wiki/Installation-and-Readme#installation) and that you're using the [latest release zip file](https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.8.0/Monika_After_Story-0.8.0-Mod.zip).

**Comment by Alefe8900** [comment]
So, what can I do???  🤔🤔🤔

**Comment by aldoram5** [comment]
Do the installation again following the instructions with that zip file I linked( latest release as of now 0.8.0).

**Comment by Alefe8900** [comment]
Where is my save data???

**Comment by Alefe8900** [comment]
hey guys I reinstall the game and it work perfect. thanks for all your support👌👌👌👏👏👏👏👏👏
