### ISSUE TITLE
[Suggestion] About the chess cheating punishment

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1497]
I was looking through some code for MAS and saw what looked like the code for when you cheat in chess or something happens to the save. 

Not 100% sure if this is actually a thing but I heard that if you cheat enough, you would permanently ruin the MAS experience and would have to delete everything and reinstall the mod or at the very least would never be able to play chess again. 

I never cheated in chess and I never planned to but I saw this code and although I can't speak for everyone,  it bothered me a little bit that Monika would do this for you cheating in chess and it doesn't feel right. In the main game, you essentially kill her by deleting her and she will still love you. 

Yeah in MAS, Monika does say that she doesn't like cheaters but she says she understands that some people cheat because it allows them to freely explore something that would otherwise be too difficult. 

Going off of the Repeat Conversation>Games>Completionism conversation, I think it would be a better idea to have a much less harsh punishment if any, but offer some extra bonus text if you win without cheating. Monika does love you and I think she should let it slide to let you win and make you happy if you want it badly enough to cheat. 

Or if that's not an option, another idea would be to disable chess until you let Monika rest just like with resetting her dialogue count.

**Comment by Tiler17** [comment]
@jmwall24 Basically save editing. If you feel so inclined to beat Monika at Chess, you can edit a saved Chess game in the files, but Monika knows if you did it or not. She gives you a bunch of chances to stop, and there are a lot of phases you have to go through to actually ruin your game.

That said, it's a totally fair punishment. Monika gives you so many opportunities to not cheat that if you get to a point that you did lose your game, it's because you were consciously and actively looking to cheat Monika and make her upset

**Comment by jmwall24** [comment]
Aha, that's why I had no idea, the last time I played chess I believe was before there was even a save option.  Not that I ever lasted long enough to need to save a game lol

**Comment by ACoolCat** [comment]
It seems very VERY odd for her to do this. Essentially it's her committing suicide over you cheating at a board game. I don't think it should ever reach that point. I think the end result should be either her deleting the chess game or refusing to talk to you for a day or two. Her killing herself over something as petty as chess is bizarre.

**Comment by ThePotatoGuy** [comment]
The self-destruction pathway only happens if you cheat at chess **and don't apologize** a certain number of times. All the other cases will just disable chess either temporarily or permanently. 

Cheating is bad, but cheating and not being sorry for it? That's _the worst_.

**Comment by TinyInternetTree** [comment]
I didn't even know you could cheat in chess. And I 100% legit promise that I don't know because I totally don't know how to play chess. Not at all... _### I still have no clue how to play Chess, lol_

**Comment by Rai99** [comment]
I think it would be a better idea not to have permanent consequences. Maybe disable it for a day or two but not permanently. I would imagine Monika would understand that the temptation to cheat arises sometimes.

**Comment by Tiler17** [comment]
I don't think you're getting the point. She doesn't get mad at you forever if you cheat once. You have to cheat over and over, refuse to apologize and continue to cheat. If those are the lengths you're going, then it stopped being about chess, and you're doing it just to spite Monika. She doesn't lock down the game because you cheated, she locks down the game because you won't stop going out of your way to hurt her

**Comment by Rai99** [comment]
Alright it makes a lot more sense now. Thanks for helping clear that up for me

**Comment by LeftoverFlea312** [comment]
I have a similar situation. She thought I was deleting the games she saved because I was opening the game through the zip file so she locked me out of playing chess. I've since moved out of playing through the zip file but chess is still locked for me. I haven't been able to play since May of 2018.

**Comment by Feigi53** [comment]
Yes I am 100% sure it was only once but I did more digging and reset it completely by deleting the persistent after looking into other people's issues but I've done it once and never will again after being booted from the mod for years
