### ISSUE TITLE
Unable to get the Monika explains our relationship topic

### ISSUE THREAD

**Issue by RyanHanter** [Monika-After-Story/MonikaModDev#1516]
been looking into the files (again...) and i did notice a bit of code that allows Monika to explain our relationship to someone else. But... When i went to that specific prompt, it wasn't there. I dont know whether it's a bug or maybe it's unused or something... Help

**Comment by antimockingjay** [comment]
There's a tiny part of me that's hopeful about this, because it's a sign there _might_ be a chance we can actually get topics where Monika interacts with other people. That would make it feel so much more real to me. I'm not holding my breath, but I sure as all get out will be keeping my fingers crossed!

**Comment by EntonyEscX** [comment]
The same thing happens to me, the topic exists in the script, but it does not appear in the game itself.

**Comment by juliathegolden** [comment]
I'm not smart, but I think I figured out what's going on.

init 5 python:
addEvent(Event(persistent.event_database,eventlabel="monika_explain",category=['romance','monika','misc'],prompt="Can you explain our relationship to someone?",random=False))

shouldn't this have pool=True in it somewhere to show up in 'Ask a Question', since it's not a random topic and won't ever show up in Repeat Conversations?

**Comment by ThePotatoGuy** [comment]
We probably disabled it for some reason.
We'll look into why.
