### ISSUE TITLE
[Suggestion] Kissing

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1525]
Monika mentions how she gets romantic when the mood is right if you choose the kissing topic. However, we now have one of those things that can make the mood right for her, raining. So maybe when rain is on she kisses the screen, then comments how pesky it is that the screen is stopping you two from kissing for real. Also, considering how she mentions you need to be "far enough in the relationship"  in the dialogue about fan art, maybe this function can be unlocked after the three month anniversary.

**Comment by MaximumRustler** [comment]
I would like this too. Monika also mentions kissing in the haters topic (if you answer I'm not) and the current song topic (if you have no song playing). Although, if I'm not mistaken doesn't she communicate with the player through the MC? If so that would be kinda awkward if she kisses him... unless he doesn't exist anymore then that would be fine. lol

**Comment by Onion-Bubs** [comment]
There is the Current Song topic that, if selected when no song is playing, does something similar to what's being suggested.

**Comment by ACoolCat** [comment]
Doesn't he get deleted with the rest of the game during Act 3?

**Comment by MaximumRustler** [comment]
Hmm... I'm actually not quite sure. I guess it would make sense if she deleted him and rewrote the code so she could communicate with the player directly instead of still using the MC to communicate.

**Comment by ThePotatoGuy** [comment]
[Closing until we klook into this]
