### ISSUE TITLE
[Suggestion] Combination Options. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1532]
Maybe clicking on a specific topic before another could trigger a special conversation? Like, whenever I go to eat I tell her I'm hungry before saying goodbye. So maybe that could trigger her asking if you're going to go eat something.

**Comment by NoahDaggler** [comment]
And after you come back she'd greet you with 
"Welcome back player! Did you enjoy your meal/snack?" 
Yes: "I'm glad to hear that, eating a small snacks throughout the day can be good for your energy and just make you feel better in general.. sometimes it might be bad if you go overboard with them though.."
No: "Oh... Well, If I was there I'd try my best to make you something yummy! Would you do the same for me? Ehehe~"

**Comment by kaido1224** [comment]
That was sorta brought up previously but the devs wanted to limit the # of special interactions like that in the past, but since the greeting system was reworked it may be possible now. What you are suggesting would work similar to how you tell Monika you are sick and then try to come back after she closes the game on you. It's more likely to be added if a contributor adds it rather than waiting for the devs to add it though.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
