### ISSUE TITLE
Hangman Suggestion

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#1535]
There are some mods like Doki Doki: A Normal VN where Monika gets her own route and she also gets her own words in the poem minigame like "emerald" "delete" and "freedom." I think it'd be really cool if some of those words were included in the hangman minigame and Monika could say that it's a word she likes when you get one of them.

**Comment by Tiler17** [comment]
I wouldn't mind if more words in general were added to hangman. I dunno if they have to have a "pool" of words to choose from, but the more, the better, IMO. Every time we play, she tells me that it's a challenging game that I can get better at by reading.

I don't need to read. I just need to remember a handful of words from the poem mini game.

I really like hangman, so I'm all for anything that gives it more variety and/or challenge

**Comment by ThePotatoGuy** [comment]
Well with how the hint system works, its best to restrict the words to the stock wordlist from ddlc. 

We do have 1 Monika word, but its a one-time thing. The 3 words you suggested could probably work fine, but adding other kinds of adjectives will get messy in deciding what words Monika actually likes.

That being said, I think this is a great opportunity for the community to add contribute. 

Okay everyone, please add words you think Monika would like as comments below. Also for each word, give a brief reason why the word you chose is Monika-appropriate. (except emerald / delete / freedom, since those make sense already).

**Comment by Mundo-X** [comment]
Doubt... can it be of any doki... or just Monika? (Only that question)

**Comment by moonsandstar-s** [comment]
piano/music - for obvious reasons
reality - also, for obvious reasons 
rain - because Monika has stated she likes rainy days

**Comment by FomorianFox** [comment]
Is envy a word? If so, that might be good.

**Comment by jmwall24** [comment]
coffee - we all know she loves coffee
ribbon - duh
advice (or advise given her name meaning)
the player's name could also be one, with some specific dialogue about how it's her favorite word after you guess it

**Comment by Tiler17** [comment]
Abstract- her poem writing style
Corruption- She was responsible for a lot of that in DDLC
Delete- Just so that it's on this side of the word request post

Will add to this post as I think of more things.

Also, I want to publicly recognize the "Okay everyone" that ThePotatoGuy used. 10/10 reference

**Comment by Tsadokiel** [comment]
I like this idea! Here are the words I thought about:

Vegetables - since she seems to be a vegetarian
Lonely/Loneliness - pretty obvious with her backstory
Symbol - because, when you think about it, several words in her poems could be seen as such (like the feather)
Emerald or Green - because it's her favorite color
Poem - she started the literature club and the poem thing, I guess she would be the one who would be the most associated to this word
Route - because she'd like to have one, I guess?

That's all I have for now but I'll add some if there are words that come to my mind.

**Comment by Rai99** [comment]
- The player's name
- Doki doki literature club
- Reality

**Comment by MisterSimple** [comment]
Epiphany - The realization that she is trapped in a game
Despair - She feels this when she has her epiphany
Wretched - The state of the game once Monika starts messing with it. Could also allude to how miserable Monika feels upon her realization.

**Comment by kaido1224** [comment]
True

**Comment by totallyweiss** [comment]
Perhaps Beach related vocab?
Shore, waves, beach, swimming.
As she does mention wanting to go to the beach.

**Comment by Tiler17** [comment]
This is unrelated to new words, but is related to hangman. The brief discussion about tying affection into it made me wonder if it's possible to create dialogue that differs depending on how many missed guesses you had. She'd be impressed if you didn't miss a letter or "Ah, almost got you!" if you missed five letters, that sort of thing.

**Comment by 99Dman99** [comment]
Debate - Originally was in the debate club
Leader/Leadership - President role
Festival - Organising the festival in DDLC
Confident - Monika's important leadership attribute

**Comment by Olliesama** [comment]
Prisoner/Escape/Freedom/Confinement/Trapped/Cage - All relate to her being stuck in her own world.
Eternity/Unending/Devotion/Attachment/Faithful/Loyalty - All relate to her feelings towards the player and their relationship.
Sensibility/Responsibility/President/Literature - All relate to her role as leader of the club
Classroom/Cosmos/Creation/Galaxy - Space Classroom
Lonely/Loneliness/Isolation/Solitude/Exiled/Desperation - All relate to her feelings on her epiphany
Aware/Artificial/Fake/Character/Epiphany/Discovery/Realization/Different/Screen/ - All relate to her epiphany.

Piano. - It's a piano.
