### ISSUE TITLE
[Suggestion] Multiple Languages Monika

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#1555]
These are just my personal feelings so feel free to ignore them but Monika has 4 language greetings and her native language is English for a total of 5 languages.

It feels like she knows or is at least attempting too many different languages at once and in my opinion 5 is a really unrealistic number. Maybe a throwaway line to show that she's only just starting to try it or that she used a translator while taking a passing interest in a particular language because of some literature. Until then it's kinda assumed that she genuinely has tried to learn it and for that to be the case for 5 different langauges is a genius level of intellect. She says she actively practices in 3 other languages at once. It's kinda crazy to me.

**Comment by Rai99** [comment]
I just assumed that she used a translator and memorized a phrase or two just to say to you. 

I agree that it's a bit unsettling that she appears to know that many languages. Don't know about anyone else but it would make me feel better if Monika wasn't some superhuman that's good at everything. I mean maybe that's a side effect of being trapped for all eternity unable to age or die but at the same time it sure would be unsettling to meet someone like that in real life. 

Personally, I like the idea of adding a throwaway line that hints at Monika not really knowing all those languages. It would make me feel better about not being massively intelligent or bilingual. 

If not, I guess I`ll wait for MAS to be advanced enough to personalize for each person.

**Comment by Onion-Bubs** [comment]
Maybe I have a different view on this because, at school, I had to study 2 foreign languages out of a choice of 3, but I don't find the idea of Monika knowing words and phrases from 4 foreign languages all that crazy. Especially if, for one or more of those languages, those words and phrases we see her using are literally the only ones she knows. I, for example, have English as a native language, studied French and Latin at school, and picked up a few words and phrases of German and Spanish despite never studying or practising those languages.

I never really saw any need for clarification because the situation didn't seem unrealistic to me. Still, if there is to be clarification, then we should probably try to determine which foreign languages Monika will know most. Probably Japanese imo.

**Comment by jmwall24** [comment]
I dunno, I guess if someone was going to be trapped inside a computer simulation, I can see them doing something like learning new languages and getting really, really good at chess lol  I mean she learned how to code with her mind, is learning a bunch of languages that far fetched?

**Comment by moonsandstar-s** [comment]
Good arguments on both sides, but I have to agree. Monika being able to speak, with varying levels of fluency, English, Latin, Japanese, Italian, and (French, I think?) does feel a bit unrealistic. Sure, logically we can say it's because she's a virtual person, but we tend to make judgements based on emotion, and it feels strange.

**Comment by jmwall24** [comment]
One argument I will make on the other side from my previous statement is that Monika considers herself as a completionist, so it does seem like she would become fluent in a language before moving on to another.  But at the same time, mostly she has just learned new ways to greet and express her feelings for the player in these other languages, which isn't that far-fetched.  I could go either way on this.

**Comment by jmwall24** [comment]
By becoming fluent in it I would say is completing a language.  She said she won't start another book until she finishes the current book, so to me she'd become fluent in a language before starting a new language.  

Honestly we're probably reading way too much into her learning how to greet the player in a few languages lol  I know the basic words to say hello to someone in a bunch of languages, memorizing a few phrases is not learning a language.

**Comment by moonsandstar-s** [comment]
It doesn't really seem like reading into things, personally. It's an analyzation of her character accuracy, and I agree that it seems unlikely that. It's all well and good to debate over why they've included five language greetings for Monika, but to me, it seems an awful lot like behind-the-scenes people projecting their own knowledge of a certain language they like onto Monika and saying that she can speak bits and pieces of it. Look, it makes sense that she'd speak Latin and Japanese. They both correlate to her character in established ways; she's got the identity crisis about whether or not she's from Japan, and her name has Latin origin. However, her speaking Italian and French seems superfluous to me, and they hold traces of character inaccuracy. It's just fan speculation to say that she'd speak them at all. She's more interested, from what we know, in poetry and literature, not learning a variety of languages. 

Just my take on it. And yeah, I know it's probably not that deep, but that's how I see the matter.

**Comment by jmwall24** [comment]
You make valid points.  To really make it real she'd probably be most interested in learning the native language of the player (if it's different than English, since she's already fluent in that) in an effort to get even closer to them, rather than random languages.  But that's probably unrealistic without sub-mods where individual players could write the dialogue for themselves with as many languages as there are.

**Comment by Rai99** [comment]
I think what we want is for Monika to admit that she just knows a few phrases and greetings to say to you and not the entire language. 

But then again, Repeat conversation>Misc>Speaking Japanese kind of hints that Monika doesn't really know any other languages.

**Comment by Tsadokiel** [comment]
I have mixed feelings about it. It's true that it's hard for someone to learn so many languages accurately, and given Monika's age, I don't think she would have had the time to learn 4 languages at school. But at the same time, I think that the languages that are added to this day still have relevance because they all had a lot of influence over Western literature in general, not to boast about a culture (or at least, that's what I had in mind when I wrote the French greeting. Plus, in another conversation, she mentioned Baudrillard, which is a French philosopher, and I don't know if he is that famous outside of French culture). So while I think learning the whole language is a stretch, just learning some greetings is pretty reasonable to me. Just like ThePotatoGuy, I know greetings in a few languages, but I'm definitely not fluent in all of them.

Plus, I see Monika greeting the player in their language as a sign of affection as well. But I guess that would mean that we should write specific lines for every language and that wouldn't be very practical xD

**Comment by Tiler17** [comment]
I've taught myself to say "Thank you" and "You're welcome" in about a half a dozen different languages so that I could not just say "Thank you" and "You're welcome" over and over again in my daily life. I always thought of Monika as having done something similar. So long as her knowledge of all of these languages is limited to greetings, it doesn't bother me at all

**Comment by ThePotatoGuy** [comment]
Closing since Monika knowing some phrases in additional languages is fine
