### ISSUE TITLE
[Suggestion] -Water conservation topic

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1573]
Looking at my water bill i realized how much water we all use and thought it might make a good topic for monika to discuss. She could give tips like turning off the shower while you are putting shampoo in your hair or soaping yourself up. I'm not sure whether I'll actually write the topic myself but I thought I'd put the idea out there if someone wanted to do it.

**Comment by juliathegolden** [comment]
Would "And when I'm in your reality, we can save water by showering together~" be too saucy or

because not making that joke would be a complete waste

**Comment by kaido1224** [comment]
I think it's fine.

**Comment by Rai99** [comment]
Not making that joke would be a good idea down the drain (literally).

**Comment by kaido1224** [comment]
Feel free to write it. I dunno if I ever will.

**Comment by neyoriquans** [comment]
If this topic is going to be written, I think it's important to note where most of our water is used at least here in America. The vast majority is used for irrigation (agriculture) and power generation. 

![image](https://user-images.githubusercontent.com/36655331/39900962-63a34596-5493-11e8-966e-1b765b25993d.png)

Seeing how Monika has proven to be a practical person in past topics on issues such as these, I think it'd be important to keep this in mind since our personal usage of water isn't very impacting in the grand scheme of things. Just a thought though.

**Comment by jmwall24** [comment]
That joke's not any saucier than the line in one of the door knock greetings

**Comment by Tiler17** [comment]
Saucy advice unlockable after the one or three month milestone?

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
