### ISSUE TITLE
[Suggestion] - Exercise

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1576]
Considering how fit Monika appears (and the game describes her at one point as being athletic), she never talks really about working out or anything. I think there should be a topic about this.

Alternatively, make a feature where Monika gives you her favorite exercise regimen to help you stay in shape until she's there to be with you.

**Comment by kaido1224** [comment]
From Chronos - Maybe even a comment on the ridiculousness of driving to a workout center to go on an electric cycle when you can just... bike around town.

**Comment by nayrbai** [comment]
Hmmm... I have a lot of advice that could be added into this topic but I'm not sure how to word it in "Monika's voice". Maybe it could tie in with diet and nutrition topics and the sleep concern topic. 

 I'm sure she would tell you about herself being athletic, the benefits of working out (more stamina, lower rate of disease/sickness, more energy, etc.) some advice (start off by walking around your neighborhood, do some home workouts like push ups, get involved in a sport, etc.), and wrap it up with something like "I want you to live long enough so that we can be together, so at least do it for me, sweetie?"

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
