### ISSUE TITLE
Inconsistency in anime topic?

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1578]
In the anime topic, Monika says: So, if you want to load up some anime, go ahead! I'll just watch through your computer screen. Make sure it's something I'll like!

How can she possibly watch anime through your computer screen when she can't even "see" you through the monitor?

Unless I'm misunderstanding what she is meaning.

**Comment by jmwall24** [comment]
It's possible, being it's worded 'load up' that she means watch it on your computer and I assume she is able to watch stuff that is on the computer so that's what she means?  Perhaps changing it to 'I'll just watch on your computer,' would be better?  I agree how it's worded sounds like she's watching something happening on our side of the screen instead of happening on the computer itself, which would be her side of the screen.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
