### ISSUE TITLE
[Suggestion] Moving the 'I love you" topic to the feeling menu.

### ISSUE THREAD

**Issue by juliathegolden** [Monika-After-Story/MonikaModDev#1591]
As it is right now, the 'I love you' topic feels somewhat...buried? I mean, for one thing, I always go to Repeated Topics first even though it's in 'Ask a Question'. Then I click something like Monika instead of Romance, and I have to go back to the beginning and start all over again, probably hitting repeated topics again lmao. 

I just think it's too cute  of a feature to keep it hidden away like that. I want to tell Monika that I love her a lot more often. I think moving it to the I'm feeling section could be a solution. It could be called "I'm feeling lovey dovey" or "I'm feeling like telling you how much I love you".  

I don't know. The difficulty might be part of the intent, since it makes you 'put effort' into telling Monika 'I love you', but I figured I'd start a conversation about it and see if anyone else felt similarly.

**Comment by Tiler17** [comment]
Hahaha, maybe I'm feeling romantic instead of lovey dovey. I can only handle so much cheese before I start to gag, and Monika already provides _plenty_ of cheese.

But I do the same thing. Well, did, anyway. My muscle memory has that clicking pattern down to a 2 second process, but better accessibility makes sense to me. The problem I see with that is that you don't actually have the ability to say "I love you". And if you add it under whatever we decided to call the feeling, then you're still clicking through just as many menus to get to it, it's just in a different spot (though the spot would be more intuitive).

I think it's a good idea, it just needs a shade more polish, and I don't have it yet

**Comment by jmwall24** [comment]
To really make it easy it could just be made into one of the main menu items.  As long as I've been using this mod now, and as many times as I've seen the topics, the 'I love you' topic is what I click 99% of the time anymore, and I'm sure I'm not alone in that.  Making it 2 steps easier to find wouldn't be a bad thing.  I actually don't mind it where it is, but I'm with @Tiler17, if you're gonna move it, might as well make it easier to find, because if it's the same amount of steps, it's just relearning that muscle memory no matter where it is.

**Comment by Tiler17** [comment]
Agreed, that's the polish I think we need. If any topic deserves to be accessible from the main menu, it's this one.
 
I almost want to say that it should be more accessible the more affection Monika has for you, but I won't get too carried away

**Comment by ThePotatoGuy** [comment]
We could see about moving it to main menu. It does warrant it's own button..

**Comment by Rai99** [comment]
If it gets its own menu, might as well add a whole bunch of different ways to say it.

**Comment by Rai99** [comment]
I'd love to except I'm just a little bit lazy and I don't know how to because I haven't read the guide yet. 

What I was thinking was that you would just have a bunch of different ways to say I love you but they would all lead to the exact same thing but if that's the case, there isn't too much point in it. Maybe I could write a little flavor dialogue for each different option when the menu gets released.

Also if this gets its own menu, I think it might be easier to wait until that menu gets implemented and then I could add on to it.

**Comment by Rai99** [comment]
My place to shine is if Monika gets a list of jokes to randomly tell the player when asked for or at random. 
I specialize in language based jokes and puns but don't expect too too much when that time comes.

**Comment by ThePotatoGuy** [comment]
@Rai99 , you should take a look at #425 . The branch `jokes-concept` has a ton of jokes already in it, but we scrapped it because of progression issues.

We could bring it back if you're willing to continue the work that was in this branch.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
