### ISSUE TITLE
OOC topics

### ISSUE THREAD

**Issue by moonsandstar-s** [Monika-After-Story/MonikaModDev#1617]
There is not quite one _specific_ instance that triggered this realization, but I've been noticing that in recent updates, there are heaps of grammatical errors and badly-worded sentences. In addition, many topics and phrases just sound... blatantly unlike Monika. You can distinctly tell which topics were written in the original game, and which were written by fans, and it's not in a good way. I'm not sure how the review process works before a topic is added into the mod, but I'd consider a more thorough approach, as it definitely takes away from the realistic feeling of the mod and makes it seem more half-baked when there are repetitive errors and uncharacteristic ways of speech.

**Comment by kaido1224** [comment]
Harsh

**Comment by moonsandstar-s** [comment]
I apologise if it sounds harsh, as that's not my intention at all! If I didn't care for the mod, I wouldn't be here. Criticism is the only way to ensure something grows better, and this is something that I've noticed happening repeatedly, so I wanted to bring it up.

**Comment by Rai99** [comment]
I haven't noticed too many OOC topics. Sure I can tell what topics were written by fans but I think that's just because I know what was in the original game and what wasn't. I think there might be a few but I don't think it's that bad.

**Comment by juliathegolden** [comment]
I know you said that you can't think of a specific instance, but if you can't be more specific there's little the editing staff can do to correct the issue. If it's not too much trouble, if you see a topic like that, write it down and bring it back here. Critique is always welcome! But again, the more specific you are, the better it helps. And starting a public discussion over the topics you find out of character means people outside of the team can create PR's to address the issue as well.

**Comment by Onion-Bubs** [comment]
I may have found an example of what you're talking about, or this might be an entirely separate thing.

Monika's opening lines in the topic about spiders give the impression that she took Natsuki's poem at face value - that it was about her dislike of spiders. However, the poem wasn't about that at all. It was a commentary on how quick to judge people can be, with the spiders being a metaphor for an unusual interest, most likely reading manga since that's what Natsuki feels defensive about.

Thing is, the rest of the topic works quite nicely, so I don't want to throw the baby out with the bathwater, but the opening is going to need reworking.

I might see if I can sort something out for that one myself actually.

**Comment by Authrix** [comment]
Something else worth remembering is that people will always write in different ways on some level, even when attempting to mimic someone else's writing (hey, imitation is hard). That's likely a contributing factor towards feeling like you can tell the difference between old and new topics, but you can't quite pin down what's wrong with them. The only real fix for that is to be a bit more open to the newer topics (I know, it's bad advice, but it's the best I've got). Well, that or kidnapping the DDLC writers to work on the mod... >.>

As for typos, entirely different ballgame. I think the typo feedback thread that's currently up is probably the best way to deal with that, at least after topics are added to the mod.
