### ISSUE TITLE
[Suggestion] Rename "Ask a question." to "Say..."

### ISSUE THREAD

**Issue by arktomys** [Monika-After-Story/MonikaModDev#1659]
You're not always asking a question, but you're always saying something. For example:

>Talk
>Ask a question.
>"I love you."

That wasn't a question. That was saying something, hence why I think that string being worded differently would make more sense.

**Comment by Rai99** [comment]
I think renaming the menu to "Say..." would make it too broad. There are a few non-questions in there such as the "I love you" prompt and good morning/evening, but I think those are getting their own menu, most likely the "I love you" topic. 

Most of the topics in that menu are legitimate questions so I think it would be a better approach to fix the few that aren't instead of doing something to affect them all. 

I think it would be a good idea to have a new menu for statement type topics and possibly name that menu "Say..." I think the "I love you" topic is being moved to its own menu soon so that could be the new menu. 

I just think there has to be a better name for the menu than "Say..."

**Comment by ThePotatoGuy** [comment]
Yeah we could probably just move statements to a Say menu. We'll look into proper naming.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
