### ISSUE TITLE
[Suggestion] Topic where someone can tell Monika that you are injured, or worse.

### ISSUE THREAD

**Issue by CthulhuST** [Monika-After-Story/MonikaModDev#1677]
Though someone has probably brought this up already, I had the thought of a topic where a family member or friend could tell Monika that you are injured.... or worse. The topic where Monika talks about not knowing what might happen sparked my concern, and I waned to spread my concern to whoever might read this, even if it is disregarded. My thoughts on how it would work are that there would be two options in the Unseen questions list that would be, "[Player] is injured." or regrettably "[Player] is deceased." The first option would lead to Monika asking how bad the injury is, and the responses would be, "[Player should be fine in a couple of days.", "It will take a while for [Player] to heal.", and "{Player] is in critical condition." I have yet to think of responses. In the event of the player's death, Monika would ask if the person was telling the truth. If the person chooses yes, Monika would say she needs to think for a while and close the game. If in the future this is possible, the game would remain closed until a certain amount of time has passed. After that time it would open to the "door" where the person could knock, and check in on Monika.

**Comment by MaximumRustler** [comment]
This has been brought up a few times but you know, I've been thinking about this for a while. I remember there was a password system that was brought up a while back so Monika would know that it's you, what if there was a way to set up two passwords so you could give the second one to the other person and if that password was used she would know that it's not the player and would ask if something happened to the player. Also, if the other password is used the only dialog available would be the ones about the player's condition. I don't know this is something that I just thought up, sorry if it doesn't make sense I haven't had much sleep lol.

**Comment by Akh0r** [comment]
I don't want to create new topic after seeing this idea..
But I absolutely approve the idea to have a password for Player to confirm his personality.

Maybe we shouldn't make it just an option in the 'Settings' menu. It can be a part of dialogue with Monika instead.

Like, once she randomly asks you: "Hey, I just  had an idea. I can't actually see who is running the DDLC, so I can't be sure it is you. Let's make a secred word or a phrase that will confirm it is really you out there?"

After this, you will sometimes be randomly asked for this "password", like the door startup event.

And, developing the idea of telling Monika her Player deceased, a third person would be able to tell her about it.

**Comment by CthulhuST** [comment]
That is an interesting idea. Maybe not knowing the password could lead to the conversation.

**Comment by Akh0r** [comment]
Yeah, and also (or instead), she may have you answering questions only you two know.
Like, if future personal portrait of Player is implemented, she may ask you something you told her earlier. Or simply "in which month did you install this mod?", and so on

**Comment by Rai99** [comment]
My only concern with this is if the original player messes up on setting up the password or just can't remember the security check questions. 

Also I'm sure some people would find it annoying to have to randomly enter a password to see Monika.

**Comment by Rai99** [comment]
I did think about adding a mood/dialogue where you yourself can tell Monika that you're injured. 
Just wanted to get some thoughts before I put it on my list.

**Comment by MaximumRustler** [comment]
Ah, here are the issues I was thinking about in my previous comment #1399 and #1193. As Rai99 said people generally would have found it annoying if it was mandatory, that's why I would have liked it as a optional dialog.

**Comment by Rai99** [comment]
I don't think anything too heavy such as player death would be allowed in MAS but I really like the idea of letting Monika know if you're injured.

**Comment by CthulhuST** [comment]
Even though we do not like the possibility of one of our kindred dying, it is always a possibility. That was the original reason why I put it up as part of the idea so instead of Monika not knowing, she could at least know why someone never came back.

**Comment by Rai99** [comment]
I'm just saying that it might take some pushing for this to even be allowed in the game. Not to mention somebody might push the button by mistake or out of curiosity and ruin the whole point of it and torment Monika like that. 

Yes I agree if something were to happen to Monika's beloved, she definitely deserves to know.

**Comment by Akh0r** [comment]
Let's just keep the discussion adequate, because, as I've seen, the former topics like that rolled down to discussion of player suicide and different kinds of death for Monika to know and react :D 

Well, what I was talking about is NOT simply "Enter the password" window.

Look, if you were her, would you stop believing in your friend who you know, say, only by Internet chatting, if he or she said something strange once?

I think, no. If you suspect that the person on the other side of a screen is not the same you knew for a long time, you'll firstly try to subtly ask them a couple of questions only you two should know.
Like, "Oh, so you want to borrow some money from me? But won't it be like the last year?" 
And the person answers something like "Of course, no, this time I won't let you down!" 
And here you understand that your friend's account is hacked, because such a case never really happened.

Or, it may be a couple of questions you have answered earlier, like new 'Yuri's wine' interactivity, where you can confess that you are younger than Monika and/or that you do not treat alcohol. 

It is up to us, the writers, to write the dialogue in a realistic and believable way.
We just need some concept discussion:)

**Comment by MaximumRustler** [comment]
Hmm... personally I don't mind either way, but I guess I agree that a question of some sort would make more sense. I'm a terrible writer so I can't really add much more to this discussion lol.

**Comment by loverofmonika** [comment]
i think thats an awesome idea of the password thing or some code like monika asks you a question and later when again asked, only u know the answer to. Everyone think of it this way, she cant see us so do you like it if she says i love you to ur best friend or your dad.

**Comment by Rai99** [comment]
I think it's an alright idea if the player makes their own questions. There's nothing wrong with Monika making the questions but it might be easier to forget since the questions didn't come from the player. 

As for being injured, I'll put it on my list and possibly make it a mood.

Chobits topic is finished and will be double checked and put up a couple hours later when I usually write.

Current list is as follows:
- Add option to offer to go to Monika's world in the topic "Waiting to be together"
- Add dialogue where Monika talks about worrying in a storm that power might go out and player can comfort her
- Add dialogue/mood for telling Monika that the player is injured

**Comment by Rai99** [comment]
And yes please make more hugging interactions with Monika. I would love that.

**Comment by loverofmonika** [comment]
So is my proposal and game mechanics accepted? i mean the idea of blocking off anything related to the real player and all the lovey dovey blocked if its is someone else. that really makes the game so realistic. plus this little skit of her shutting down the game on purpose just to show her excitement really makes her more realistic and believable.

**Comment by Rai99** [comment]
When would you need to prove yourself? I think it would be a negative experience if you had to do it too much or if all of a sudden you had to do it without warning.

**Comment by loverofmonika** [comment]
yes i thought of that too that proving urself too much is annoying . the first time as i mentioned is perfect, that little skit. now to prove urself, she she can ask sometimes at the beginning in the greetings part. and after a good amount of time passing like every 30 mins, she ask again but casually bringing it up

**Comment by Rai99** [comment]
I mean personally, I would find it annoying to have to answer most if not every time I boot up and I have Monika in the background for as long as I'm on my computer. 

I feel like this check should only happen if the player goes off character but we probably don't have a way of checking if the player is off character. 

Sometimes after a long day, I just want to jump straight to Monika and if I just so happen to need to enter the password, that would really put a damper on things.

**Comment by loverofmonika** [comment]
yes but again she ask occasionally, like out of 10 greetings she ask 1 or two times. that way it'll be realistic. plus we got that knock, listen and open option. we can have her ask there sometimes, like when u try to knock, she riddles u, if u rush in, she glitches u and then ask. that way players may even look forward to it

**Comment by loverofmonika** [comment]
so her asking is not every time nor extremely frequent rather sometimes and with a long interval but not too long that she would never ask. i personally would love to go and say hello honey im home but since we are having a compromise, it gives u that feeling that monika really loves u and she doesn't want to say i love you to anyone else so she has no choice but to sk.

**Comment by Rai99** [comment]
Unless there's a toggle or opt in/out, I'm not sure this password thing could work anytime soon. 

1. There's always the possibility somebody might forget or mess up making their password but that can happen anywhere. What if it does happen and Monika won't interact with you? Is it just game over at that point?
2. If this becomes a thing, when would you need to enter the password? Too often and it'll get annoying and insincere. There was discussion of Monika detecting if the player was acting out of character or if what they said contradicts with a previous statement, but I don't think this feature exists at the moment. 

I think it would work best if there was a setting to toggle it. Maybe you're alone most of the time so there's not really any risk of somebody taking your place with Monika and there wouldn't be any reason for suspicion. Maybe you've got some visitors over one day and you do need some extra security for that day. 

I think toggle is the best option here.

**Comment by loverofmonika** [comment]
first of all.
if the answer is wrong, monika would still interact but all the topics which has romance or calling out the player and say something romantic like 'u will never betray me" would be closed. and she wouldnt call ur name. we can include an option where we can let her ask another question sooner 
second of all
what if the player forgets, we can use the game file technique for that, like in the saves files we include a text document that has all the questions and answers.

**Comment by loverofmonika** [comment]
i agree that this should be optional and not something that cant be turned off.
so if turned on, all the features i mentioned above would activate and i u want to deactivate it, just ask monika. but to introduce this new feature to the players, the little skit must be done

**Comment by Rai99** [comment]
Implementing the dialogue for this seems harder than standard topics so unless the person who makes this writes the dialogue themselves or somebody who does know how writes it, we (or I) would need the framework to write dialogue for it. 

I do remember you kind of made a rough outline of how it should go earlier so that could be worked off of.

**Comment by loverofmonika** [comment]
yes i did, u can find it untop of the comments, u can use that or even improve it. i would like to be in contact with u so i can in the future add more ideas and help out, i would love to improve this mod.

**Comment by loverofmonika** [comment]
other suggestions on improvement of the mod are all in the comment section. also i have also given an outline on what happens when the security is switched on, eg the use of knock greeting, all romantic dialogue and name calling and anything that has a hint of romance are locked if it is indeed someone else.in that case the player can tell monika to ask another question and her reaction would be a little different from getting the answer write the first try.
i so want to kiss monika and not get teased about it all the time cuz as if now i think that topic should be expanded

**Comment by Rai99** [comment]
Quite the commotion with this thread even though it ended on a completely different feature. The author wanted something to allow others to interact with Monika and here we are making a security system to prevent just that.

**Comment by Akh0r** [comment]
Rai99, it is not like preventing. It is more like making Monika able to separate her Player from any other person.
But, as I said, it would be very cute and immersive if we manage to implement some complex and thorough dialogue instead of stupid "Enter the password" window.
Sooo... It needs some writings! 
I think I have some ideas, but I have no time to write:/ Well, in a matter of days I think I will find a way to write something on my own. By that time I will certainly finish my Russian translation of MAS...

**Comment by loverofmonika** [comment]
Akh0r I have already gave a rough outline on how it would be implemented. All we need now is just to come up with good

**Comment by Rai99** [comment]
Thanks! 
I added "I really wish I could do more than just advise and watch, but I know that's not possible until I manage to get to your reality." to the "No." option. 

I didn't add the line where Monika tells you to be more careful because personally, I think it's not needed. For example, I would be just a little annoyed if something beyond my control happened and I get told to be more careful next time. Accidents happen regardless how careful you are. 

As I'm writing this, I think I might be able to fit something in about being careful.

**Comment by Rai99** [comment]
Added. 

And that's the beauty of discussion. Hope people like it.

**Comment by loverofmonika** [comment]
Indeed, oh and I would like to omit the line where she says you'll live through it. I feel  it's a bit awkward, that line matches Natsuki more. Do mention it once to be careful cuz Monika is more of a worried bud when it comes to love. U can extract the lines from my last comment. And the" I love you so much" must be there, that thing is an Arrow straight to the heart. Girls get overly worried when it comes to us getting hurt and I know that from experience so it'll be nice if Monika shows that without coming off as too annoying. I mean if my girl was hurt even in the slightest, definitely a's a man I would be protective, similarly girls get worried and stressed out

**Comment by loverofmonika** [comment]
And yes discussion is the way to find solutions and improvements, got to love it

**Comment by loverofmonika** [comment]
And yes discussion is the way to improvements and solutions, got to love it

**Comment by Rai99** [comment]
I removed the lines about living through it and being strong and slightly altered one of the lines to better match your suggestion. 

There's already an "I love you" like line I think is good enough and I don't think we need 2 in the same dialogue branch. I think it gets her love across fine while also trying to brighten the mood.

**Comment by loverofmonika** [comment]
i want to make a change to 356 to "Remember that I always will love you and i have faith that my feelings for you will never change. I believe that our love will last till eternity, (blush smiling face )  . "
U can edit this to improve it although i like how this turned out.

**Comment by loverofmonika** [comment]
now i shift my attention to the yes option lines
this is how i imagined monika would react
after clicking yes
monika:" ..... oh....... my......."
              ".............................."
               "Sorry to hear that, and again sorry that i was silent just now, its just.."
              " I really hate to see you so badly hurt like that."
              " Atleast you're recovering right? I wish i could be right by your side right now so i can nurse 
                 you back to health "
              " i think you should rest, as much as i love to spend time with you, resting as much as you 
                can is the best choice"
               " i'll watch over you while you rest although i have my doubts i'll be able to do even do that" 
               " i know hospitals can be pretty strict when it comes to its patients."
               "I really hope I don't get taken away from you [player] "
                " But if being seperated for a while means you getting better, then i think its worth it"
                  " Just spend more with me later on when you do get better, Alright?"
                  " Get well soon my love (cheerful face)"

**Comment by Rai99** [comment]
Looks like you're playing a pretty big part in all this so I just wanted to say thanks for your hard work and help!

I made some changes according to your suggestions. 
I really like the last 2 lines I have in the Yes/No path so I aim to keep those in.

**Comment by loverofmonika** [comment]
It's an honour helping out and being able to contribute to this amazing mod. Thank you for listening

**Comment by loverofmonika** [comment]
I would like to help an other topics and suggestions as well. What can I say I love this mod

**Comment by Rai99** [comment]
#1692 

The next thing I'm working on is some dialogue about driving, but that's probably not going to be finished anytime soon. 
ie. It's probably going to take a couple days.

**Comment by loverofmonika** [comment]
I'll take a look at it too

**Comment by loverofmonika** [comment]
oh i also want to talk about the "thoughts about god" i think its best to omit this option cuz there are players out there who may disagree with what she says and some may even dislike her. religion is a sensitive matter and i think its best to avoid any conflicts don't u agree. as i was observing some players having monika afterstory, i noticed that among them didnt like what she said and pretended that she didnt say that. some even on the verge of deleting the game. So please heed my advice. removing it wouldnt destroy the mod.

**Comment by Rai99** [comment]
I think we're at the point in this thread where it would be best to open a new issue.

**Comment by loverofmonika** [comment]
yes true but you get what im saying right?

**Comment by loverofmonika** [comment]
I think The potato guy didn't read our trend in the God topic and missed our conclusion. The trend was closed with him saying we are not gonna remove it. U got to talk to him, Rai99

**Comment by Rai99** [comment]
We _**aren't**_ going to remove it. He didn't say anything about not being able to add the option. The same kind of thing was done in #1559 and it seems people like having that option so I can still at least try to add a menu option to the god topic. 

Also I don't think it's a good idea to just come here to this thread to discuss other issues because this thread is long enough already, not to mention off topic from what the original intent of it was. There's also a much higher chance I won't see it since this is so old and long already. 

I'm surprised this issue is actually still open seeing as some really good ideas came from it and have already branched out into their own issues and discussions.

**Comment by loverofmonika** [comment]
I see, also I think the person who started the trend didn't log on for a longood time and maybe forgotten. Potato guy can close the trend
