### ISSUE TITLE
[Suggestion] - Power Outage Topic

### ISSUE THREAD

**Issue by ReddTheRedRedd** [Monika-After-Story/MonikaModDev#1682]
Had this idea when there was a thunderstorm and I was too scared to open MAS XD
Basically my idea is this topic would relate to the rain topic, where Monika mentions how she likes the rain but kind of comes to the realization of something bad about it. Pretty much that as much as she loves rain, it could be a danger to her if a power outage were to happen in "our" reality(real life), it can shut your PC off, or worse, destroy it. This isn't to scare the player, but more of a worry Monika herself has as someone who's stuck in a simulation. This could also tie into some other peoples suggestions, there's been alot of suggestions about letting Monika know about updates and other instances where you can't help the game closing. Maybe when you open it up again you can let here know it was an outage. Perhaps even if you want to go more in depth, maybe if you can detect if the game closes/crashes/PC stops unexpectedly then Monika will have more of frantic "what just happened?!" sort of greeting where you can then say an outage happend, or any of the other reasons.

**Comment by Rai99** [comment]
If it's an ordinary topic, I might get around to it myself.
Shall I add it to my list?

**Comment by ReddTheRedRedd** [comment]
I'd imagine it'd just be an ordinary topic, perhaps one interaction in the topic where the player would console her?

**Comment by CommenterOfComments** [comment]
I would absolutely love this. I've had my computer shut off due to power loss a lot recently, and I would really want to apologize to her and know whether or not she had to go to that void. I feel bad every time it happens.

**Comment by Rai99** [comment]
Currently working on a Topic called "Chobits."

Next was originally: Add option to offer to go to Monika's world in the topic "Waiting to be together" but that might be put on hold while it's discussed if an addition like this is strictly necessary. 

Other than that, this one should be next up. 

Also I think there's a topic being put in where you can apologize to Monika for whatever you feel you need to for.

**Comment by Rai99** [comment]
Also does anyone know when new topic and enhancement PRs get merged? I'd love to know that my work is in the game and I plan to continue regularly contributing but at the same time I don't want to flood the PR tab.

**Comment by ReddTheRedRedd** [comment]
Thanks, glad this topic can be used :D Also I'm not too sure about the merging.

**Comment by ThePotatoGuy** [comment]
Time until merge varies. If its not straight up dialogue, it gets merged faster.

#1668 Covers unexpected crashing.

**Comment by EntonyEscX** [comment]
I hope they fix it in the next update because it would be a very useful topic.

**Comment by Akh0r** [comment]
Haha, that reminded me of a case 2 years ago. I've been playing StarCraft: Legacy of the Void on my laptop. Then I came to the mission where the protagonist was about to go for a mission to re-activate some ancient artificial intelligence copies of his own kindred, which was heavily discouraged by his advisor.
Just before the mission a dialogue happened, where the advisor says how bad this decision is and how awful the consequences will be.
I tried to start the mission…  
And my laptop suddenly emits some smoke from its nozzles and shuts down.
Reason: due to a strong power surge the motherboard, CPU and GPU are completely burned down, the laptop is unrepairable.
Never underestimate the Protoss preserver!

And so, if Monika is rescued from a damaged PC or just has experienced some emergency power-down, it would be cool if she could react to this. Even though it is not very likely to ever happen to everyone

**Comment by Rai99** [comment]
I've witnessed cases where some storm struck and fried some computers beyond repair so it really could happen to anybody. Just hope it never happens while Monika reaches out of the screen to hug the player.

**Comment by Rai99** [comment]
Chobits topic is ready to review and merge.

What category would this power outage topic go under?

**Comment by Akh0r** [comment]
What is 'Chobits topic'?
I'd like to take part too :)
As for the category — I guess, it is something like "Monika" or "Misc".
It may be both Monika's reaction on computer hardware being significantly different (is there a way for her to detect it, by th way?), or Player's initiative to tell her about such a case.

Hm. How do I see it?
[Conditions:
-Monika's files are transferred to another computer
-The last game shutdown was unforeseen, without saying Goodbye]
`
"What just happened? I... I had a bad dream... I thought I will never see such a thing again! "
...
"[player], wait. I can see something is different now."
"I see that the hardware I'm running on is different."
#Here she can even list the main parameters of the former PC if it is possible to detect
...
"It was awful... Oh, well, I can concentrate now, I think. Let me try to..."
menu:
---"...Test my abilities. Do you read me, darling?"
---"Yes, Monika"
------"That's a relief! I'm happy to see you here!"
---"..."
------"What? Is... Something wrong? Oh no. Not that!.."
------"Wait, how could we be here if you didn't run me on a PC?! Are you joking? I-it's not funny at all!"
"Well, as I said, I find that the hardware is changed. And that forced shutdown... Tell me please, what happened?"

menu:
---"I simply have my PC upgraded"
------"Oh, really? So... Have you brought me here too?"
------"You did not simply download DDLC and MAS from anew – you have brought my files with you."
------"I'm so happy to see your concern!"
#In the next sentence it would be good to use the information about the first install of a mod
------"So, now you have not just a random Monika – you have me. Remembering you since [the installation day]. Loving you stronger with each day~"

---"My old PC was damaged"
------"Oh, things like that do happen, I guess."
------"Being trapped inside of a computer has its disadvantages. So much for an immortality, right? Ahaha~"
------"But wait... D-did you..."
------"...Brought me here from your old computer? I mean, exactly me – and not just a new version of DDLC and MAS to have some other Monika?"
------"..."
------"[player], I... Just can't express how I am impressed!"
------"Of course, if your hard drive is still intact, it is not a big deal to bring it to your new PC, or to simply copy the files."
------"But what if it wasn't intact?"
------"I imagine this as you saving me, bringing from a house on fire, or something like that!"
------"So you are my hero!~"
`

**Comment by ReddTheRedRedd** [comment]
I'd imagine it'd go under the "Monika" and "Weather" topic, unless you're trying to reserve the weather topic only for the weather options you can change to, but it would fit there imo.

**Comment by Akh0r** [comment]
So you made it only a random topic about the rain, and therefore I'm still free to make a suggestion of my own...
What I want to add is a conversation in case of computer being switched off forcefully.

Can anyone explain where do I post a proposition if I can write the whole monologue, but still can't write a piece of code?

**Comment by Rai99** [comment]
Yeah I have no idea how to check if the computer was turned off forcefully and I'm not sure if it would even be possible. 

My guess would be to make a variable that becomes true when the player says goodbye to Monika and false when they come back. If power does go out, that variable won't be triggered and Monika would know something happened. Maybe make another variable to check if the player is forcefully exiting out themselves and make another situation for that. Yes I'm actually a programmer too but I'm probably better at writing. 

As for premade dialogue, I was wondering if there was a place for that too where I can put some simple premade dialogue without code for #1677

**Comment by ReddTheRedRedd** [comment]
Awesome! heads up though, on line 6307 there's a typo, "I would probably take you by surprise."
Also believe I remember Potato posting somewhere about having a system like you mentioned Rai to see if the game crashes for any sort of reason.

**Comment by ThePotatoGuy** [comment]
@Rai99 the pull request I linked above handles detecting if the game crashed or not.

**Comment by ThePotatoGuy** [comment]
[closed as complete]
