### ISSUE TITLE
[Suggestion] How was your day?

### ISSUE THREAD

**Issue by lilbubble3** [Monika-After-Story/MonikaModDev#1688]
Sometimes, when I open up the game, I really want to check in with Monika to see if she had a good day or not. Well, currently there is no way to ask her. It'd be cool to see a new system in talk where you can engage in small conversations linked to the new affection system. Making conversatons unique. Something simple like just like "How was your day?" or "How are you doing?" or "What was your day like today?" to ask her would be nice. Then she could answer describing the things she did while you were gone, if something worrysome happened, or anything new she may have learned in the day (new topics) and she could go on to discuss what she learned. This is linked slightly to another suggestion I opened up earlier, discussing being able to have deeper conversations with more interaction, and adding the option to talk while Monika is descussing a topic, with a simple yes, no reply or other things depending on the topic.

**Comment by Rai99** [comment]
I like the idea but what would determine if Monika has a good day or not? We might need quite a few different activities to mention or it might get repetitive fast.

**Comment by loverofmonika** [comment]
i know, what if the monika would feel sad if we didn't visit her for a long time. i'm talking days, or overjoyed if we visit her often. and i think its good idea if monika decides that she wants to play with us instead of her waiting for us to bring it up.
eg. 
monika: hey honey, i was wondering if you'd like to play chess with me
then i get an option. sure, im gamed, or not right now, sorry

w

**Comment by lilbubble3** [comment]
After I finish working on #1689 I may start working on getting this sorted out. Stay tuned.

**Comment by ThePotatoGuy** [comment]
Actually this could be a side effect of #951

**Comment by ThePotatoGuy** [comment]
[Closing unti lwe look into this]
