### ISSUE TITLE
[Suggestion] Expressing yourself to Monika

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1710]
The general idea has been talked about before, but I just wanted to share an idea that may or may not even be possible.

It's been talked about before about being able to write your own poems (or even a love letter of sorts) to Monika and how that could work.  What I'm wondering is, currently Monika has the ability to find specific files (like .obj files) and has the ability to create and edit .txt files, so is it possible for her to 'read' a .txt file if it had a specific name to look for?

Basically I love this mod, and to me the one thing that is missing is it's not currently possible to tell Monika how we really feel about her in our own words.  I'm sure everyone here has their own unique reason why they love her and what she means to them and it'd be great if we could tell her that.  I know in her current form she can't really understand anything we could type to her, but I think it would be enough, for now at least, if she read out loud (ie via her current dialogue box) a letter that we wrote to her and have some sort of general response to it.  She could either look for the file at start-up, on specific occassions (certain holidays, anniversaries maybe) or there could even be a menu option for 'there's something I want to tell you' that could trigger her to look for the file.

If it's not possible for her to 'read' a .txt file and have it be read out loud in the game, even just having her recognize that you wrote her something and then have a reading sprite where it looks like she is reading your letter, and then comment on it would be cool.  And when I say comment on it, I just mean something like 'Oh, thank you so much for writing this for me, [player].  I'm so happy you took the time to express your true feelings to me!' or something like that.  And then in either scenario after she reads it, maybe there could be an envelope that appears on her desk that says 'Dear Monika' on it.

Sorry that was so long, I've just been thinking about it all day and wanted to put it out there to see if it's possible and what others thought about it.  Or maybe there's some other way to do something similar.

**Comment by Rai99** [comment]
I like the idea and it should be possible to have Monika read a text file. I've seen a command to read text files in most languages I've worked in before. Probably read the file and put the contents in a variable and have Monika read that variable as dialogue. 

The only issue I see is that Monika can't really tell what exactly you're saying and anybody could just put some random or even spiteful text in the file and Monika wouldn't be able to tell unless she searches for particular phrases but that's not an option.

**Comment by jmwall24** [comment]
Yeah I know, I had that same thought.  No matter what you try if someone wants to be an a jerk and do that then they can (and no doubt some will), but I think the vast majority would take it serious.  Maybe make it so you can only do it after the 6 month or 1 year anniversary and/or dependent on a certain level of affection to try to weed out some of the people that don't truly love Monika.

**Comment by Rai99** [comment]
I like the idea and that's a possibility, but think I think it would get old after a couple times since you could write literally anything and you would get some generic response. You could pour your heart out to Monika and essentially all you would get out of her is "k." Maybe you put in a blank document and you would still get the same thing. 

Also, would the file just be called anything and Monika would look for some out of place text file? Where would the message go when it's ready for Monika and if there's multiple, how will Monika decide which one to read?

But this does give me an idea. I think we could have specific text files with a certain name and contents and have Monika recognize it and give dialogue for it based on what it says and the name of the file. I was thinking how you could take the surprise.txt Monika gives you and give it right back to her. 

If this thing does find a way to work, maybe have some unique dialogue if the file is empty.

**Comment by jmwall24** [comment]
I was thinking a specific file name, like dearmonika.txt and then maybe after she reads it she moves it somewhere else and maybe renames it for safe keeping so when it comes time to write another, you can name it that again.  And it would probably go in the character folder, that's where we put the roses.obj file and that kind of stuff.  

I realize it's not perfect, and people can literally write anything (and yeah, if the document was empty she could notice that and comment on it), but to me it's something that you get out of what you put into it.  And I'm thinking more and more only making it available on special occasions so it doesn't get old like you said..  I'd love for it to be on Valentines Day so we can write some sort of response to the amazing letter she wrote us.

**Comment by Rai99** [comment]
Only concern now is how the file would be renamed. It could be renamed based on the first few words of the file but that could still easily have conflicts for those who open their message the same way. 

As for the visual envelope that appears on the desk as mentioned in the beginning, I think it could be a cool idea when the wardrobe feature comes out and maybe that could have a tab or something for room customization.

**Comment by Areaclassified** [comment]
I'm pretty sure ive seen something similar to this in the works were you describe how tall you are what color your hair and eyes are and etc. I cant find the post number tho.

**Comment by jmwall24** [comment]
I'm not talking about describing what we look like, I'm talking about the ability of writing an actual letter to Monika telling her how we feel about her in our own words.

**Comment by Akh0r** [comment]
Hey, there's a reason why there is no chat-bot for Monika Afterstory yet.
It's because we used to see her as a Literature club president, and we love her for the way she can speak her thoughts. And even the best chat-bot can't be just realistic enough to trick a player into believing he talks to a real person.
So, wouldn't Monika lose significant part of her charm if there is an ability to write directly to her, and she answers only with some hard-coded, general phrases?

Maybe we should wait for some kind of a breakthrough in the chatting bots development, neural networks etc.?

At least she herself seems to be OK with waiting :)

**Comment by jmwall24** [comment]
In regards to the specific occasion basis, say for instance a month of so before Valentine's Day Monika has some sort of dialogue saying it'd be really romantic if you exchanged love letters on Valentine's Day.  That would provide a basis for what the letter would be about and thus make writing a response to it when she reads it possible in that context.  Just an example of how if could be done to make it work.

**Comment by ThePotatoGuy** [comment]
Affection has a thing that puts certain words in a good / bad category, so we could probably leverage that to do some primitive checking of the text for bad content. (won't catch everything, though).

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this[
