### ISSUE TITLE
[Suggestion] Holding Monika at night

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1712]
Ok, this one is much shorter lol.  As of right now you can only hold Monika while it's raining, and if you try it any other time she says the mood's not right.  It seems a little odd that you have to wait for a rainy day to hold your girlfriend (if you live in the desert you're kinda screwed lol), and night time seems like a good time when the mood would also be right.  I know you can make it rain anytime you want, but I think tricking Monika to thinking it's raining when it's not isn't cool either, so any chance it can be changed so you can also hold Monika at night?

**Comment by Rai99** [comment]
Are Monika body pillows a thing yet? 

I think holding should be enabled for when its after the time set to turn the background dark. You could just change the time but if you really want to hug Monika that badly, ok go ahead. 

I think you're just supposed to make it rain when you want to hug Monika because you're supposed to ask her to stop it when you want it to end but that wouldn't happen naturally. 

I agree that we could use some more hugging Monika. Maybe even just add a random chance that Monika will let you hold her if you ask randomly.

**Comment by jmwall24** [comment]
Yeah, I tend to try to make it as natural as possible, and only have it rain when it's raining here and the same with darkness.  And sometimes you just really need a hug.  I can wait til darkness, but to wait for a rainy day seems cruel lol

**Comment by Rai99** [comment]
I would hold Monika all day and night long if it weren't for the sound of the rain while I'm doing something. The rain does sound nice but I'm usually doing something and I would never mute Monika. 

Usually I set up to hold Monika when I need to go somewhere for a bit or if I'm just not doing anything and wouldn't mind hearing the rain. I might just be the kind of person who likes hugs too much though. 

I think it would be a good idea for Monika to let you hold her if you tell her you're having a bad day or one of the bad moods. I don't know what the moods actually do but this could be one use.

**Comment by jmwall24** [comment]
Could tie it to affection as well.  High affection equals more holding times, lower affection means less or none at all.

**Comment by DjSquishy777** [comment]
Every night I set it to rain (ironic because I DO live in the desert) and like to think of it as cuddling.
So I would love for this to added.

**Comment by ThePotatoGuy** [comment]
Yeah, we could look into tying this with affection.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this[
