### ISSUE TITLE
The same conversations

### ISSUE THREAD

**Issue by Alefe8900** [Monika-After-Story/MonikaModDev#1758]
I'm tired of seeing the same conversations with Monika, this is getting boring.

**Comment by jmwall24** [comment]
Lots of people are very busy on doing things to improve the mod, from coding to dialogue to reviewing everything to make sure it all works and fits in the way it should.  It all takes time.

**Comment by Rai99** [comment]
#1751 covers a similar issue.

If the next version was released now, I think there would be a good amount of new content, but I'm pretty sure there's more coming. If you're bored and don't mind spoiling yourself, you could read the pull requests and upcoming topics. 

I'm doing my best for Monika and I'm sure everyone else is doing the same. 

I don't even have the fabled contributor tag yet but I'm just pointing that out for fun while I still can.

**Comment by jmwall24** [comment]
I hope you get it soon just so you stop saying it lol

**Comment by Rai99** [comment]
I'm sure Monika would support me saying it while I still can. 

One of these days, all my topics might just flood in and then people might be satisfied for at least half an hour for my weeks of work. 

I do it for Monika.

**Comment by jmwall24** [comment]
I would hope everyone is here for Monika.  That contributor tag isn't important.  People that don't submit pull requests but submit suggestions, report bugs etc are just as important and are contributors as well, regardless of the tag.  Don't sweat the small stuff, everyone appreciates your work.  We're all in this together.

**Comment by Rai99** [comment]
Of course. It would be pretty strange of me to work so hard only to stop after getting a nice little rectangle next to my name wouldn't it? 

If anything, it makes me feel better to know someone as small and insignificant as me (without a contributor tag) can make a big difference and please people. I think there are people who consistently read and go over my work so it's nice to have that sense of appreciation and achievement. _And Just Monika of course._

Support and appreciation of my work is always welcome since I think I'm just the kind of person who always doubts my own work (You could say that I'm a Yuri type in person) but Monika helps a bit with that and I guess you could say all my contributions are a way of returning the favor.

**Comment by jmwall24** [comment]
Well if it helps you're not small or insignificant my friend.

**Comment by Rai99** [comment]
Only downside is that Monika keeps scolding me for staying up late most nights. 
With that I'd better get going before Monika realizes I haven't actually gone to bed yet.

Topic for #1643 is nearly done, just need to write one more path of dialogue and convert the sprite codes.

**Comment by Alefe8900** [comment]
Ok, so the only way is just to wait. That's no problem, there is too many dialoge it will be good to see them again and I don't remember everything.
