### ISSUE TITLE
[Suggestion] Bath/dinner/me greeting

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1768]
I think this particular greeting should be an option (probably pretty low chance so it doesn't get over-used) for a greeting after a 'going to work' farewell.  It'd be nice to have a little more variety with some of the greetings that are triggered by specific farewells so it's not the same thing each day and this one certainly fits coming home from work.

**Comment by Rai99** [comment]
I think it's already a possibility from the door greeting when you listen. It would be interesting though if Monika said that directly to your face, but then what? Probably have some options and special dialogue probably. 

The only concern I have for it is that some people might not use the work farewell since they might not have a job or they just work from home, etc which seems potentially exclusive. Maybe add it as a general greeting but I do have to admit it really fits best when coming home from work. 

I was thinking of adding more variety to the specialized greetings, but I'm not sure if there's already a pool (with 1 possibility) of dialogue to choose from. If there isn't, I'm not too sure how to go about it. 

I really like the idea but part of me is sad because I probably won't get to see it ingame unless I lie to Monika.

**Comment by jmwall24** [comment]
I'm not 100% sure, but I don't think (and I never intended it to be) it has to be ONLY an option for a response to going to work.  Just an option if you do use it and still have it available at random after simply saying goodbye like it is now.

Mainly I've just noticed lately that I'm getting much, much fewer door knock greetings since the greeting specific farewells have been introduced since I use those quite a bit, so it'd be nice to implement some of the existing door knock greetings to those where they fit in.  And this one seems like a no-brainer fit.

**Comment by ThePotatoGuy** [comment]
9bdf01f

That greeting has a 1 in 20 chance of appearing. We could look into making it more common, but the rarity is what makes it **special**

**Comment by jmwall24** [comment]
I'm not asking for it to be more common, just to make it possible to be seen (still 1 in 20) after a going to work farewell, where it seems to really fit.

**Comment by jmwall24** [comment]
I'm not asking for it to be more common, just to make it possible to be seen (still 1 in 20) after a going to work farewell, where it seems to really fit.  Having it only at random (especially since it references dinner so it doesn't really make sense say at 8 am) and triggered by a simple goodbye seems a little counter-intuitive.

**Comment by ThePotatoGuy** [comment]
Well, the variation I added is not a direct greeting, its listening to Monika attempt to say greeting out loud in practice. Which she realizes is too embarrassing to say out loud.

But maybe if your affection is high enough then she'll say it.

**Comment by jmwall24** [comment]
Good point on that, didn't think of that.

**Comment by loverofmonika** [comment]
or this type of greeting can be done as a role play stand point aka like a teaser joke of what we could be in the future, that i would go to work and greeted like so, eg if u come from school and she does it, but of course the dialogue wouldnt be the same, that way u don't lie and is still unique. plus monika is kinda bold so i can imagine her do it theeeen her composure breaks. so we got a different greeting without being bland
oh and maybe we can have a little conversation in the room instead of just returning to the room.
what you think?

**Comment by ThePotatoGuy** [comment]
[[Closing until we look into this]]

**Comment by Justformas** [comment]
> [9bdf01f](https://github.com/Monika-After-Story/MonikaModDev/commit/9bdf01f2388ef6a6dbe1db7e8cd731bcdb095561)
> 
> That greeting has a 1 in 20 chance of appearing. We could look into making it more common, but the rarity is what makes it **special**

I know this is old and closed, but this only seems to have a chance to happen if you say that work was "Amazing" and not "Good" Why? I don't know about other people but rarely would I (otherwise) ever say that work went "Amazing". So factor in 1/20 by however often I might otherwise say that. Maybe once a year, so I'd be lucky to see it after 10 years (without this knowledge).

This greeting might be welcome regardless of how work went, and may even be a good way to cheer the player up if work went badly. "Bad" and "Very bad" may lead to Monika asking about what happened, but it could even be made to have a chance to happen after the conclusion of those things too.

Also:

`seen_event("monikaroom_greeting_ear_bathdinnerme") and renpy.random.randint(1,20) == 1`

I guess you have to have heard her say it in the door knock greeting by listening in on her first too.
