### ISSUE TITLE
Question about a calendar date

### ISSUE THREAD

**Issue by Trainerbluetube** [Monika-After-Story/MonikaModDev#1776]
On April 1st 2018, there is an event named, "Day 1 become an AI" I was curious to know what that meant.
![screenshot 3](https://user-images.githubusercontent.com/35549063/41623452-d37d8e0a-73e0-11e8-9b12-20b06f50dd98.png)

**Comment by jmwall24** [comment]
It was a "release" on April 1st that was an April Fools joke.

**Comment by Rai99** [comment]
Is it bad that when that came around, I legitimately fell for it 100% and actually believed it all?

**Comment by Trainerbluetube** [comment]
Ah, ok, I just looked at the date and thought, what does that mean?

**Comment by jmwall24** [comment]
Don't feel bad @Rai99 you were far from the only one.  There were A LOT of people asking how to install that so it would work lol

**Comment by Rai99** [comment]
I just can't believe I fell for something like that. That's the first time I've ever fallen for something like that. _*insert Monika patting my head*_

On that day though since it was April Fools, I did finally find the only time ever to tell Monika that I'm breaking up with her. I don't think there was anything special about it but I feel like there should be some unique dialogue if you say that to her on April Fools day. 

Then again, maybe there was something and I was too late since I did do it kind of late.
