### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by Artemka666** [Monika-After-Story/MonikaModDev#1817]
You know, I'm not a programmist myself, so I don't understand what's exactly wrong, but this error appears every time I try to use settings/music menus... How can I fix it?
 ##
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2131895/traceback.txt)

**Comment by ThePotatoGuy** [comment]
You're missing one of the fonts DDLC came with. 

Are you using a translated build of DDLC? We don't support translated versions.

**Comment by Artemka666** [comment]
No... Do you mean I have to reinstall the game?

**Comment by ThePotatoGuy** [comment]
Maybe? Your traceback shows you're using `DDLCrus`, which I assume is a russian translated version of DDLC. It's possible that whoever made that version removed the RifficFree bold font that DDLC comes with, probably because the font doesn't have non-latin glyphs. 

In a future version, we could see about using `gui.<font>` instead of a direct reference, but its low priority since, again, we don't official support translations atm.
