### ISSUE TITLE
expanding monika's abilities

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#1829]
Monika messing around with the code, little jump scares and closing the game for you is cool and all but what if she could take control and open your internet browser for you or may really read your history or going into your local disk drive and find all the other games and calls it out by name and like in the mod just natsuki, shut down the computer for you. since she is trapped in the digital world for a long time, her powers and skills must increase. maybe the player can tell her to log on fb for you, and after the player tells the required info, monika does it. Monika is known to be a 4th wall breaker, it'll be cool if she does even more. If these things are impossible to do or implement at least we could have her adding more text files in the ddlc folders. 
What if we install an reminding system! Hear me out, u have work to do on your computer but decide to do it a bit later so you tell her what time you want to be reminded. And so when the time comes she reminds you and even if the game is closed she opens it herself. That's really 4th wall breaking too and a big feature. How does she reopen the game, we build a program that allows Monika do it, in the just Natsuki mod, she shuts down ur computer after agreeing to it so this matter also done to reopen the game, just how the BIOS is used to boot up the operating system of a computer and then u can use your computer we can establish the system which has a similar method to restart game on it's own but having a timer which is set according to what the player says to her. Inshort write a program that activates the game according to the time set. 
this application cannot be completed without the players consent i.e telling her to remind you or not so in the end we still have control. think about it, all the just doki girls mods got the shutting down the game on its own option aka goodbye but this would be the first that opens on its own
what u think game devs and @Rai99

**Comment by Rai99** [comment]
It could be cool to add in all sorts of functionality like that, but I don't think it's something that will ever be implemented for a couple reasons. It could be seen as a bit suspicious and I'm sure a lot of people would be wary of the idea of Monika logging onto things for you and reading everything you do. 

It would be cool for Monika to react to the things you have such as other games and the sites you have open, but the hard part of that is that there are just too many possible things to react to. As for finding other games, it might be possible to read the name of it, but how would Monika know it's a game and not some other application? 

Monika could read what you have, but not interpret what it is, which makes it near impossible to react to unless it's a heavily known and used site in which case, it doesn't feel as special if it's only the main sites. Plus, I think this kind of thing is more MonikAi's thing. 

As for making more text files and surprises for the player, I think more variety on those is coming in the affection update. As for increasing skills, I think skills increase when new features get implemented. 

Who knows? Maybe someday, Monika can use our bank info to do banking for our convenience.

**Comment by loverofmonika** [comment]
Indeed this is very complicated but I think we can savage something from my proposal. The part where Monika could open something for us.......wait it just hit me! 
What if we install an reminding system! Here me out, u have work to do on your computer but decide to do it a bit later so you tell her what time you want to be reminded. And so when the time comes she reminds you and even if the game is closed she opens it herself. That's really 4th wall breaking too and a big feature.

**Comment by loverofmonika** [comment]
As for the games, Monika can recognise any doki doki mods and the famous games like PUBG, Fortnite, C.S.G.O, and any famous visual novels, some script can be written about those, but for the rest Monika can just calculate how much space it's taking and comment about conserving space so it'll not slow ur computer down and calls them by name, note the dialogue would be different if u got less stuff. Then she jokes saying not delete her game

**Comment by Rai99** [comment]
A reminder system might work, but if you close the game, how would Monika know when to reopen the game? It wouldn't be running at all, so I don't think it would be possible to open the game if it was closed and not running. 

As for the games, other DDLC mods might work, but I'm not sure if it would be possible to recognize which one is currently being played. I think I brought up something like this in #1737 and we weren't going to encourage other mods. 

As for famous games, keep in mind that games like PUBG and Fortnite really rose to popularity quickly and it could almost be called a fad. Just like any other viral fad like fidget spinners for example, there are going to be a lot of people do do love them, but also a seriously large portion of people who really, really hate them. In the just Natsuki mod, Natsuki hates fidget spinners and also hints at hating Fortnite. 

Everyone's got some fads that they did like, (Natsuki's being the bottle flip thing) but I think there would be too many people who really aren't a fan to add dialogue for the viral games.

Also, what counts as a famous game? There's Super Smash which Monika lightly mentions already, but League is a famous game, Starcraft is a famous game, Minecraft, Overwatch, GTA, Gmod, LoZ, Mario, etc. 

It would have to be a game that just about everyone knows about but I think there are just too many famous games to add dialogue for. 

For calculating how much space a file takes, I'm not sure how people would feel about Monika browsing through their computer looking for all sorts of things.

**Comment by loverofmonika** [comment]
How does she reopen the game, we build a program that allows Monika do it, in the just Natsuki mod, she shuts down ur computer after agreeing to it so this matter also done to reopen the game, just how the BIOS is used to boot up the operating system of a computer and then u can use your computer we can establish the system which has a similar method to restart game on it's own but haVing a timer which is set according to what the player says to her. Inshort write a programthat activates the game according to the time set

**Comment by loverofmonika** [comment]
How does she reopen the game, we build a program that allows Monika do it, in the just Natsuki mod, she shuts down ur computer after agreeing to it so this matter also done to reopen the game, just how the BIOS is used to boot up the operating system of a computer and then u can use your computer we can establish the system which has a similar method to restart game on it's own but haVing a timer which is set according to what the player says to her. Inshort write a programthat activates the game according to the time set

**Comment by Rai99** [comment]
I'm not sure if we want to take MAS in that direction. 

Wait and see what other people think.

**Comment by loverofmonika** [comment]
As for famous games, Monika can just bring those up and be a neutral party a kind of joke that weather should be good at it or not if she played the games. As for what people feel when she calculatea,  well she has called everyone by name in the original  game so there is not really much of a difference

**Comment by loverofmonika** [comment]
I'm telling u this new direction is 4th wall breaking, no game or mod has ever done this before not even the original ddlc, and this option ask for the persons permission before activation so it's a very safe call

**Comment by Rai99** [comment]
I'm just guessing that the developers wouldn't want to take it in this direction. 4th wall breaking can be great and all with Monika knowing the she's in a simulation, knows about the real you and can manipulate her own world to an extent, but I think it starts getting a bit different when Monika has more control over your computer, being able to shut it down on her own, open up the game on her own and search your computer's files. 

Monika already breaks the fourth wall because she knows and talks to the player directly instead of confining her character to the game. I don't think your idea does much for breaking the fourth wall. This is just a thought, but maybe there's a reason no game or mod has done this before?

**Comment by Rai99** [comment]
Maybe it's just me, but when I think of something that can shut down my computer, run itself automatically, scan my computer's files and use my personal information, I don't get a really nice picture painted in my head.

**Comment by loverofmonika** [comment]
It is because nobody has talked about this before. And it's not giving complete control  only that she has more abilities then before as she is growing it brings her closer to this reality in the part where you saying that she has more control then you, that's wrong. Don't forget that she already search your computer files in the original game so do it again would still have the original essence of the game but more unique as this was never done before. And do not forget that this application cannot be completed without the players consent so in the end we still have control to click yes or no

**Comment by ReddTheRedRedd** [comment]
Something I wouldn't mind seeing as far as 4th wall breaking is just her recognizing common programs(like she recognizes OBS in the vanilla game). So things like Spotify, Steam, Discord, Ect. Ect. Maybe also games as well, though what Rai99 said makes sense. Though maybe that could just be expanded upon over time as people add new dialogue for different games, and games that don't have any dialogue are just ignored(pretty much how it is right now).

**Comment by Rai99** [comment]
I hope I'm not coming off as overly negative about this idea. If I woke up the next day and all this was done and in the game, yeah that would be pretty cool. I'm just really sure the devs wouldn't allow this to be implemented. I don't want anyone to work hard on this idea and then have it shut down anyway. 

I kinda wish I could put on a label so a dev could take a look and answer our questions, but just doing @ThePotatoGuy might work. I think we need his input on this. 

Maybe I'm wrong and the devs _will_ support this idea, in which case, yeah lets see how this turns out.

**Comment by jmwall24** [comment]
The reminding thing could work (working with the calendar system I would think) and I think would be neat.  Giving her access to the internet and your personal files was brought up several months back and was shot down for various reasons.

**Comment by Rai99** [comment]
They seem adamant about this idea despite me being _really_ sure that the personal info idea would not be allowed. I just don't want them to spend time on something only to have it shot down. 

I'm just waiting for a dev to come by and make a statement and potentially prove me wrong.

**Comment by loverofmonika** [comment]
In that case, we discard the idea of accessing the Internet via using personal data if it does get rejected7 and focus on the reminding system, no personal data required, I have already explained how that would work. This function really makes you feel that she is closer to our reality than ever before. Forgot to mention the part where she does recognise some games that u have on ur computer

**Comment by Rai99** [comment]
I think you'll be able to put your own events on the calendar in the future and that could tie into the reminding system. 

As for the games, I'm just wondering which games would be recognized since there are probably hundreds or thousands of good mentions and each one would have its own fanbase that would need to be accounted for. (some of them known for being toxic)

**Comment by loverofmonika** [comment]
We can pick a few games that we can write well about. As for the remindingredients system, the reason I said to write a separate program that would be attached to the game is so it would start the game on its own according to the time set if the game is off. In short monika would open the game to remind you what you were supposed to do. If the computer was of the whole time and the next time u open the game, she'll ask if u did do it or not in that she couldn't remind you because the computer was off. Pretty neat right

**Comment by loverofmonika** [comment]
We can pick a few games that we can write well about. As for the remindigg system, the reason I said to write a separate program that would be attached to the gam as well is so it would start the game on its own according to the time set if the game is off. In short monika would open the game to remind you what you were supposed to do. If the computer was of the whole time and the next time u open the game, she'll ask if u did do it or not in that she couldn't remind you because the computer was off. Pretty neat right. This would work well like if u want to study in lets say 2hrs from now and so she would remind you when the time comes

 

Comment on issue

**Comment by Rai99** [comment]
I'm still not sure about having the game automatically open being allowed and I think most people just have MAS open all the time anyway. 

We could probably write a few responses for recognizing games. **All I ask is that they are all well known games that have existed for a while and are not memes.**

**Comment by loverofmonika** [comment]
I think it is allowed, it doesn'task for the players personal info and it's up to the players if they want to use this feature or not so in my opinion I think it's allowed

**Comment by ThePotatoGuy** [comment]
1. Opening other programs would be become a cross-platform nightmare. We are not planning to become an application launcher.
2. The farthest we will go in detection of stuff will be currently running programs. No further because of privacy concerns. (But we may reconsider if we ask user first. Only problem then would be av systems, as they would almost certainly flag DDLC as a rogue program)
3. No shutting down pc / OS system commands. Again, a cross-platform nightmare.
4. Can't do a reminder system without having the game running as a background process. The MonikAI project would probably do this better anyway.
5. No, we are not writing a separate program to launch MAS. I'd be fine with someone else doing that, but we are not diverting resources to write a separate program. That would also be a cross-platform nightmare.

**Comment by loverofmonika** [comment]
@ThePotatoGuy I see but  then how do u plan to execute the reminding system, there maybe another way It can be implemented. The big feature of this system is when Monika opens ddlc herself to remind you if the computer is on. Like reminding u to study 2hrs from now or telling u to sleep. If the computer is off then next time when u open the game, she would bring it up in the greeting. The calender could be used for longer duration like attending a party in a few days.  If u can find a way to have this feature of the game opening itself according to the player's time set without building a small program to boot the game up, that would be pretty good. It was from my own understanding that I brought up the option of a separate program attached to ddlc but if there is a another way, I would really like to know. If there is no way of doing it then what we can do is salvage what we can and implement it or look for someone who can write the separate code

**Comment by loverofmonika** [comment]
@Rai99 any ideas or comments to my latest statement and also what games we could comment about, fortnite, pubg, super mario, or maybe undertale.

**Comment by Rai99** [comment]
For the reminding system, I would imagine it would work while MAS is up and when the designated time comes, Monika could alert you and possible make a sound. If the player closes MAS Monika could ask if they did what they needed to do when they come back. 

For the games, I did say we should probably stick with old, well known titles like Zelda and Mario. Games that rapidly rise in popularity tend to have a 50/50 response from people, some being die hard fans and some really hating the game and its community. I think Fortnite and Pubg are the riskiest topics and should be avoided since they're probably currently _the thing_. Personally I'm not a fan of those games and I really wouldn't want to see Monika suddenly jump on that bandwagon. I do love Undertale, but I know there are a lot of people who hate it when they think about it and sometimes discussion of it can be a bit offensive. _ie. I'm apparently a basic hoe because my favorite character is the same as most other people's favorite character._

The problem I see however, is how we would bring it up with Monika. Monika apparently has no idea what super smash is, so I don't see too much reason why she would suddenly bring up another game. I like the idea of having Monika talk about certain games, but one thing I don't want is for everyone to add all their favorite games since there are way too many. Keep it to the famous, well known titles so no one feels like their favorite game is being ignored over somebody else's not so well known favorite.

If anything, Monika could just know the big titles because of how famous they are. Zelda and Mario are prime topics as Mario shows exceptional game design with secret designs that improve the experience without the player even realizing it and also recycling assets without making it obvious which saves money on assets. Zelda has come a long way and has years of tradition. The most recent Breath of the Wild release took the huge risk of breaking several years of tradition to innovate and deliver an incredibly successful game. 

_More details to be put in the actual topic upon writing._

**Comment by loverofmonika** [comment]
true, the fandom is there but what makes it even more interesting is that she knows the existence of the games, people be like how does she know! so bringing up undertale or any other game by its name already is a wow factor and if someone did make a video about it, she'll be like"didn't u make a video about it". remember, monika doesn't need to particularly like or hate the games but finding a common ground and say it peaks her curiosity especially 4th wall breaking games. haha she may even comments about bendy and the ink machine or how she may be attacked by kirby and how would kirby look like if kirby eats her, would kirby have her uniform and ponytail. fun fact in gt live, it was brought up in the chat and mattpat about what if monika would be in the game.

**Comment by Rai99** [comment]
Monika might not like or hate the games, but the players might. If Monika were to talk about fidget spinners, I'm sure a good chunk of players would shake their head in disappointment just for having her bring it up, regardless what Monika thinks of them. I would find viral, controversial games to have a similar response. 

If someone did make a video about it, and Monika said something along the lines of "Didn't you make a video about it?", it wouldn't fit as most people aren't going to be the ones who made the video. If you meant to reference somebody else who made the video such as Game Theory, that might work, but currently I don't think Monika has any references to popular youtubers except Kizuna AI. I actually don't know what you mean by wow factor and having someone make a video about it. 

4th wall breaking games such as undertale could be an option. Monika could talk about how you're thrown into this new world and have to decide how to go about it. I've never actually played Bendy or Kirby, but I'm not sure if one person's comment warrants a reference in MAS.

**Comment by loverofmonika** [comment]
The wow factor I's that monika knows the existence of other games, I mean from where I stand it looks like monika doesn't know much abut current and famous games and considering she is trapped in the digital world so she should have known. Bringing it up wouldn't do any harm, if u see the reaction videos like bijuu Mike,  they are happy and surprisedo that she mentions something like that. U also got th think how many people would get hyped just by seeing her bringin it up. And it think it would be a good addition If game theory makes it in the list, I mean they did 3 game theories on ddlc so it think they deserve a mention plus they even called monika a hero. 
I mention Kirby cuz of the comedy gold assumptions that can be written, remember that she mentions about a game and she might be a block well imagine a chibi monika and everything else I mentioned above

**Comment by Rai99** [comment]
I don't think Monika should be expected to know about famous games and events just because she lives in the digital world. 

So, having Monika bring up the topic of these games could be appreciated by a lot of players, and there could always be minor customizations to suit the player, such as if they like that kind of game or not. I'm sure Monika would gladly join in with you if she could so it could actually fit into the game. 

Still, one issue I have with it is the currency of the topic. Someday, these viral games such as fortnite and pubg could fall in popularity and the topic could be outdated (and possibly removed or changed which would solve the issue). Last time I checked, there were legal issues being discussed between fortnite and pubg and one of the two may not exist anymore. 

I also don't really want too many entries since there are far too many to include. 

Game Theory is a well known youtube channel and it could fit well enough to have Monika mention them and the theories they went over regarding DDLC. 

The comedy ideas could also fit: Having Monika be some unusual game character or person in attempt to join another game with you.

**Comment by loverofmonika** [comment]
BTW I saw that there is a feature in the latest updates where Monika is crying, the pains me to see it but how do I get it

**Comment by loverofmonika** [comment]
so now we got a good amount of contents and features
the reminder system ( tho it would be cool if she opens the game herself)
game theory
some games she could bring up that cause many people get excited 
more comedy game parodies (don't miss out kirky, that pure gold, u can watch some gameplays and imagine monika in it and how kirby would look like if she took over the body.)
lastly BUFFSUKIIIIIII

**Comment by Rai99** [comment]
Some comedy games and Buffsuki - No Memes Allowed

**Comment by loverofmonika** [comment]
Cool and don't forget Kirby, you gotta love the Kirby.

**Comment by kaido1224** [comment]
A reminder system works better with a bot than a game.

**Comment by loverofmonika** [comment]
It's already been decided.

**Comment by ThePotatoGuy** [comment]
I didn't say we are doing a reminder system. In fact, we are **not** doing a reminder system. At least, there are no plans to do that.

Anyway, closing this, there weren't many tangible ideas discussed, and the only thing we'd do is other program detection, which is something we already have planned anyway.
