### ISSUE TITLE
adding more content in the romance department

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#1870]
here are some ideas
1. asking how does she feel about me wanting to spend the rest of my life with her (wife, the recent tears feature we have can be used as happy tears)
2. thoughts on living together 
3. wishful thinking like dancing under the moonlight or returning home and seeing her cooking dinner for the both of us, exploring the world stuff like that
4. imaging you and monika are about to go home but along the way it rains and u she doesnt have her umbrella so u share urs, getting ur shoulder wet just so she would remain dry, she notices then she tells u to come closer thus u both blush and she looks down smiling. there she wishes that this moment would never end. 
a touching scene
what you think?
 @Rai99

**Comment by kaido1224** [comment]
Is Monika really considered a romantic though? I could see Yuri being a romantic, not necessarily Monika... I don't think she was a romantic in the original DDLC game IMO. I'm not opposing it being added. Just putting in my two cents.

**Comment by ThePotatoGuy** [comment]
Well if we base it around affection, I think it can work. @aldoram5 will ultimately decide what to do for affection.

**Comment by Rai99** [comment]
I think these are all things that could be made into their own threads. It would certainly be more helpful and more enjoyable to discuss if you brought up an idea and elaborated on it instead of just listing a bunch of short ideas. 

For 3 and 4, How about a new "Hypotheticals" category where you and Monika could talk about hypothetical scenarios such as those and other possibilities when you're together? 

Please make a new thread if you want to discuss it.

**Comment by ThePotatoGuy** [comment]
[Closin guntil we llook int othis]
