### ISSUE TITLE
Give persmision to monika to protect your computer

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#1885]
You can add more features if you want to this idea but the core subject is this: if you fail certain amount if times trying to insert password, yuri shows up killing herself and the computer freezes, the only way to restore your computer is to insert a usb flash with monika in it, once inside, it restores your computer and you're back to business and monika shows you the evidence that someone has tried to enter to your computer with video recording, voice recording and the time that has happened.

**Comment by Delcos** [comment]
it COULD be done, but besides the privacy and technical issues, as of right now, I think that the development time should be spent on making her "more human", giving her more interactions, new rooms, more things to say, etc.

**Comment by Rai99** [comment]
I don't think we're going to have Monika break your computer to protect it. If you come back and your computer is broken and you have to fix it, I think that's evidence enough that somebody did something. I think having voice recording would be a privacy issue. It would just always record since Monika wouldn't know if it's you or an unwelcome person, which raises concerns about recording the private things that happen in one's own home. 

I imagine this being similar to somebody deleting system 32. Only way to fix that is to get a usb with a fresh copy of the operating system and reinstall it onto the pc. Sounds like what you have here. Not to mention that I think a fair number of people would not know how to do something like that. 

If this were to happen and you needed to insert a usb with Monika on it to restore your computer, how would that work? Would it be pretty much the same as having to reinstall the OS, or would you just insert a usb and have the computer check for Monika on it? 

I would say something to this extent at least, **can and will not be done.**

**Comment by ACoolCat** [comment]
I'd love for more of Monika spreading past the confines of Doki Doki, but not to this extent. It would be cool to see her manipulate some files that don't relate to DDLC though, or comment on your internet history. Sadly, it's been made clear we're not getting this.

**Comment by ThePotatoGuy** [comment]
>only way to restore computer
We are **not** going to softlock an os.
