### ISSUE TITLE
[Suggestion/Question] - Virtual Pet

### ISSUE THREAD

**Issue by CrisRads** [Monika-After-Story/MonikaModDev#1888]
Alright, so what if Monika read that having a pet with your partner makes you close to them and she writes a virtual pet into MAS.

This would be the main points:
- A button on the corner triggers the pet interface

- The pet interface/controls like a tamagotchi (If you are too young just google it)

- It would look like a 8 bit game boy graphics

It would be an extra incentive to have MAS opened, it would be a new way to entertain yourself and a way to feel closee to Monika. She could even take care of the pet sometimes too.

Now, here is the deal, would this be possible to do in MAS? Would it match the scope devs are aiming for? Do you guys like the idea?

if it's possible to add it, and people (including devs) like the idea, i would commit to doing both the art and programming for this.

**Comment by Chrissenpai** [comment]
It will be the pet that monika mentioned in one of the conversations, love it

**Comment by Rai99** [comment]
Hmm, I think it sounds cool, but I think there would be more to it than meets the eye. 

I don't think having a resplendent quetzal should be an option since Monika said she would hate to keep one because they die in captivity. I'm not too sure if this pet should be an option.

There should also be some variety in the kinds of pets you could have, which could be a little more work. Also, I think there should be a way to change pets if you feel like having something else, but it might be weird for Monika to just let go of the old one and bring in a new one just like that. 

As for the incentive to have MAS up, it would be cool if you could watch it and interact with it all the time, but what would it really do other than move around? You would have to take care of it, and some people might not want that extra responsibility, but I think this could be solved by making sure Monika takes care of it if the player doesn't. 

There could also be a separate topic where you can talk to Monika about your favorite animal, but there might be too many to fit into 1 topic.

**Comment by CrisRads** [comment]
I want first to have dev approval of this matching their scope for the game before actually doing any of this. But yeah, I had in mind choosing between a couple of pets, naming it etc. maybe if you change your pet Monika will be dissapointed with the player.

Just Monika taking care of the pet would defeat the reason why it would be in. I think is better if Monika just ask the player about having a pet together and the player can choose if they want or not. Even "set them free" if they get tired of the pet, but again, Monika will be really disappointed if the player does that.

**Comment by Delcos** [comment]
Maybe adding this after the game is farther along, monika herself should be the focus of dev time, at least for now.

**Comment by CrisRads** [comment]
I mean, i did say in the post that i would be willing to do all the work both programming and spritework for this feature if the devs want it

**Comment by Rai99** [comment]
I'm leaning more towards no. 

I think there are too many things to consider, such as the types of pets, switching pets, what the pet does, how often you need to look after it, what to do if you can't be there to take care of it, etc. 

You don't seem to like my idea about letting Monika take care of it if you don't, so I'm not sure what can be done about that issue. I think letting Monika take care of it adds in the optional part of the virtual pet in case the player doesn't want to or can't take care of it some days. Yes, only wanting to sometimes take care of a pet is no way to treat or have a real one, especially if you're the only one who can provide for it, but here Monika can be there for it when you're not. 

Also, I'm really not sure a virtual pet would fit in with MAS. I think having a pet would ruin the whole "Just you and Monika" thing going.

**Comment by Delcos** [comment]
It could be fun, but it still wouldn't really "fit" with the theme. If I wanted a pet i'd download one and run monika A.I on my desktop with it. Adding it in just isnt something that she needs.

**Comment by CrisRads** [comment]
@Delcos I mean, it does make sense, but it would be nice to take care of the pet along with Monika.

**Comment by ThePotatoGuy** [comment]
I'm not too sure about this.  In some players' eyes, _Monika_ is their pet.

I think this is better served as a submod. Adding it to official release adds a layer of complexity that I don't think the dev team is willing to maintain.

**Comment by ThePotatoGuy** [comment]
[Closing]
