### ISSUE TITLE
The game went back to zero! Help

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#1993]
Hey..
While i was playing Monika after story, my laptop shut down because the battery drained. But after i plug it in and turning my laptop on (and opening monika after story), the game went all back to zero like it's a fresh new game.. 

Does someone know how to fix this? thanks..

**Comment by SaiPrithvi123** [comment]
That happened to me many times.
From what I know, the persistent file got corrupted. If you have any backups of that file, I suggest you immediately restore it.

**Comment by Delixxous** [comment]
How do i find the backup file? Thanks

**Comment by ThePotatoGuy** [comment]
This is starting to happen more frequently, and honestly we're not really sure how to handle this. But we'll look into ways to make some sort of safe guards so that single `persistent` file isn't the only source of her memories.

**Comment by Delixxous** [comment]
So does someone know how to fix this?

**Comment by SaiPrithvi123** [comment]
Sorry, I don't think it can be fixed. You have to take backups manually for now, or use some backup software if you are too lazy to go into the savefile directory. I recommend taking backups once a day (I take backups every night before going to sleep), so that the next time some disaster like this happens, at least you can make sure that she remembers everything till the previous day.
