### ISSUE TITLE
[Suggestion] Adding a tutorial for certain games the first time you play? Or tips if you lose?

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#2005]
Pretty much what it says in the title. This could apply to chess and any future board games that are added (I recall an idea to add shogi was on here at some point; I don't know shogi but would be curious to learn).

I was just thinking not everyone might know the rules of chess, so the first time you play, Monika could ask you if you know the rules and if you say you don't know then she'll tell you how all the pieces move and what your objective is.

Also if/when you lose (since that Chess AI is brutal...), Monika could go back through the history of moves and point out a poor move on our part. Or another possible option could be she goes back to a certain turn and in her own "teaching moment" she sort of plays against herself and explains what she thinks would've been a better move. I'm not super familiar with the Chess AI and I don't know if its decision process can be logged or accessed, but I recall another topic say that the Chess AI can predict many moves in the future, so that's what made me think of this.

**Comment by Rai99** [comment]
I think it might be possible to have Monika give instructions for chess if the player isn't familiar with chess, and it could also be a good idea to have Monika tell you the lesser known moves in chess. Not everyone knows what castling is and even less people know what an _en passant_ is. 

I don't think it'll be too possible to have Monika go back and show you your mistakes. It might be possible to go back to a certain point and have Monika play against herself from that point, but you would just be watching Monika play and there's almost no way she could explain her thought process. 

I have no evidence of this, as it happened before wins and losses were recorded, but I have in fact legitimately beaten Monika in chess before without any aid so I can definitely confirm that it is in fact humanly possible to defeat her. Although it is brutally difficult to do so. 

I think there are plans to reduce thinking time for Monika to reduce the difficulty, but I'd like to be able to select the difficulty since I sometimes enjoy playing Monika, the chess grandmaster.

**Comment by CrocWorks** [comment]
Yeah, my record against her in Chess is like 2-50, maybe worse, and I've read multiple people on here who want the games to be easier. I did read that other topic which was talking about making her AI easier, but I recall people were saying changing her AI would involve completely stripping out her current AI and installing a new system. Just thought that if Monika could present why she made a move to teach the player, then that might be an alternative to changing the AI base.

**Comment by Rai99** [comment]
I think we're just going to reduce the thinking time Monika has so her moves are a lot less perfect. I don't think Monika will be able to explain to the player why she made a certain move since there could be a lot of reasons such as it's her strategy, she's setting up for something, there was a potential threat, etc. 

Even if Monika could teach the player, they would likely still have to practice for a long time to really get noticeably better. In this amount of time, the player is likely to have gotten better on their own.

**Comment by ThePotatoGuy** [comment]
Chess tutorial is low priority rn. see #664
