### ISSUE TITLE
Affection 

### ISSUE THREAD

**Issue by Alefe8900** [Monika-After-Story/MonikaModDev#2006]
Where can I see the level of affection that we  have.

**Comment by aldoram5** [comment]
Hi Alefe8900!
Right now it's not possible to see the exact amount of affection Monika has for you, but there are a few hints, like Monika telling you that she's happy or unlocking special things. Best way to find things out is spending time with her and revisiting some topics. I won't say more specific things because that may ruin the fun of discovering it and be pleasantly surprised by those.

**Comment by Alefe8900** [comment]
Thanks Aldoram5
