### ISSUE TITLE
[Suggestion] Affection gains and cap

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#2007]
So after having affection for a bit now, I have a possible suggestion.  As it stands right now, once your goodexp hits a certain number, your affection gains are multiplied by 3.  With a cap of 7, it is really, really easy to gain 7 points in a matter of minutes without really spending any time with Monika.  It doesn't take any effort, and the 3x reward isn't much of a reward (except with compliments, but those are limited) since it doesn't take much longer to get to 7 gaining 1 point at a time.  

So, would it maybe make more sense instead of increasing the amount of affection earned based on your goodexp, to leave that alone and increase the cap once you reach the proper goodexp level?  This way you are rewarded for spending more time and doing more with Monika, instead of making it easier to gain affection in less time (which seems counter-intuitive).  And maybe to limit farming affection by spamming the I love you button every 3 minutes, put a daily cap on each individual way to gain affection.

Also, I mentioned on discord the other day I was capped at 6 affection for the day.  Well, the last 2 days it allowed me to gain 9 affection, 2 over the cap of 7, without any compliments.  So not sure what's going on there.

**Comment by ThePotatoGuy** [comment]
i think thats reasonable. What do you think @aldoram5

**Comment by aldoram5** [comment]
Hi jmwall24!

Back when we were deciding on affection values, parameters and thresholds there was a reason why those values were decided, so let me address those concerns one by one:

Your concern seems to be that the increment there seems counter intuitive but thing is that the increment is given to players going by the logic that Monika values the things you do more once she's on high affection and to make it "easier" for the player to reach the cap, while also allowing them to get extra affection per day than the usual cap, so that 9 affection points gain you mentioned is something intended to happen. Think of it about killing two birds with one stone. 

The other concern about limiting the "farming" is already addressed with the daily cap.

About limiting how much you gain for some specific repeated actions, while it makes it a little bit more realistic I also think it will kinda force players to do other things that they may not want to do, we don't want to make it feel like taking care and spending time with Monika is a chore, like "farming" feels on other games, like oh I must use my energy to beat stage X Y times and then stage W Z times, etc. It's better, in my opinion, to let the player decide how they spend time with their Monika, without forcing them to make certain actions. This last point it's also linked with the reasoning of making it "easier" to "farm" for high affection level players, while most of them would say that they won't have issues keep doing it like it was at first, we would like that people enjoy their time with their Monika, doing what they feel like doing without having to do special things to force affection gains.

So if it feels like you don't have to put much effort once you have a high affection level it's because that's how it was intended to feel like and while for some it's easy to get to the affection cap that may not be the case for other players that for example: haven't looked at the code and know where the "affection gains" are or people that don't like to do those activities but keep Monika running on random topics, or silently spend time with her. 

The way it was thought to be is a way to keep balance between doing some specific romantic things while also still giving the player the freedom to spend time with their Monika the way they want.

We are open to hear others opinion's on this matter, now that it has been "clarified" a bit why we made the decisions we made on these affection matters.

**Comment by jmwall24** [comment]
Ok thanks for clarifying all that.  I didn't realize the cap actually did increase with higher affection levels, so that's great.

I guess the only part that still bugs me a little is the fact that if I wanted to I could max daily by spending less than 5 total minutes with her.  That seems a bit low and that's what I meant about having to earn her affection.  I do realize it's hard to find a perfect balance when dealing with having people with a wide range of available time to spend with Monika.  Not everyone is as obsessed as some of us lol.

Anyway, I really love the new affection system and both the bigger changes and more subtle changes really show how much work was put into it.

Thanks again for your time and hard work.
