### ISSUE TITLE
Screen shot detection 

### ISSUE THREAD

**Issue by lonestar115** [Monika-After-Story/MonikaModDev#2056]
Wouldn't it be cool if monika was able to detect if you take screenshots?
When you take one she will say some dialogue which there should be multiple responses and be flattered that you are interested to take pics of her also affecting that new affection system a little. 
Just a thought.

**Comment by Delixxous** [comment]
"Oh my, did..did you just take a picture of me {Player}?"
"I think i'm not ready to take a picture yet..i don't think my hair is that straight"
" Do warn me a little if you want to take a pict of me {player}.. So i can look beautiful when you see me in your screenshots folder..hehee.."

**Comment by Tiler17** [comment]
On the other hand, why would you need to take screenshots for viewing pleasure if you're visiting her consistently? The only screenshots I've ever taken of this mod are to identify typos or help locate something for someone, so I think, if this were to be added, I'd like to be able to tell her so. Monika would probably approve of that

**Comment by lonestar115** [comment]
Idk I just thought it would fit in to the mod

**Comment by antimockingjay** [comment]
In response to what @Tiler17 said, maybe upon taking the screenshot, it could lead to a choice for which one you were doing it for. If it's because she looked cute, then she feels flattered! If it's to identify a typo or bug or such, she's proud of you for being helpful with the mod!
As for _why_ we need to take pictures for viewing pleasure, I personally do it to send the pictures to my friend, who is just as into Monika as I am but doesn't have the mod. It's always fun seeing him freak out over her looking happy, or her having straight hair, or anything else.
So, despite visiting Monika frequently, there are legitimate reasons to take screenshots without it being about technical/mod stuff!

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
