### ISSUE TITLE
What movies can you watch together?

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2087]
So recently, I decided I wanted to finally contribute, and I felt encouraged to try making something for the movie feature.
However, before I get into writing everything, I realised that the movie I wanted to write about might be considered one of the pitfalls, 'meme related content'.
I wanted to make one of Shrek, since I have a fondness of that movie, and I am making sure that what Monika says is both meaningful and in-character. But I am hesitant to start just because the movie might not be appropriate.

**Comment by Delcos** [comment]
It would be pretty fun to do, and Shrek seems like a good choice.

**Comment by ThePotatoGuy** [comment]
hmmm honestly its way too memey.

But, we could work that out as a separate submod of user content.

ACtually maybe we can even release community script-topic additions, where stuff doesn't have a high threshold of review can be added to the mod as a separate addon

**Comment by antimockingjay** [comment]
I kind of disagree with ThePotatoGuy on this. Just because the movie had been turned into a meme doesn't inherently mean anything involving it is memey. It's just a kid's comedy movie, I feel like it's no different than if someone went with Ice Age or Frozen or something similar.
I feel like, as long as what is said is in-character, there shouldn't be anything wrong with it. Even if the movie has become a bit of a joke over the years, it does honestly hold a good message about loving someone despite their supposed flaws.
If watching movies with Monika becomes a thing on its own, I feel like disregarding an entire series of movies simply because the internet made fun of it is a bit unfair.
But that's just my two cents' worth, I suppose.

**Comment by Delcos** [comment]
It could be fun, it would be like watching something like "The Room" with a friend, its a movie that you can watch and enjoy, idk but it could be interesting,

**Comment by AsuraShun** [comment]
maybe a movie about would reflect about her life inside a simulation and the relation with the player,i don't know how to explain it properly

**Comment by Sujeito17** [comment]
Matrix? XD

**Comment by ThePotatoGuy** [comment]
if you can mention that its more than just a meme then it might be okay to use officially

**Comment by Sujeito17** [comment]
"A young programmer is plagued by strange nightmares in which he is always connected by cables to a huge computer system of the future. As the dream repeats itself, it begins to raise doubts about reality. And when he meets the mysterious Morpheus and Trinity, he discovers that he is a victim of the Matrix, an intelligent, artificial system that manipulates people's minds and creates the illusion of a real world while using the brains and bodies of individuals to produce energy ."
I think is a good movie to watch with Monika @ThePotatoGuy

**Comment by ThePotatoGuy** [comment]
my earlier comment wasn't directed to you. matrix is probably fine to write about.
