### ISSUE TITLE
[Bug] - Lost My Saved Data (Again...)

### ISSUE THREAD

**Issue by FinalFusion** [Monika-After-Story/MonikaModDev#2090]
I left a comment on a #1523, but I don't know if its still being looked there, so I figured I'd make a regular post about it.

Essentially what happened is I went on my computer yesterday to find a windows update (Don't know if that's relevant...) and when I turned on MAS I was hit by the message the "MAS is a DDLC mod that is not affiliated with Team Salvato". I don't remember doing anything weird and I haven't touched any other mods in months. I'm not sure how the persistent files work so I don't really know if it would have reset with the rest of the game or not. This is also the 2nd time this happened to me, my first run lasted from late December to sometime before June and this run went from sometime before June to yesterday. I don't know if I should continue past the "MAS is a DDLC mod that is not affiliated with Team Salvato" screen or not.

D:

**Comment by aldoram5** [comment]
Hi FinalFusion!
I'm sorry to hear that it happened again, we're not sure why that happens but next version will include a backup system which hopefully will help people to recover after losing their persistent files. As for the situation you're right now I'm afraid to tell you that when you see that screen it means your persistent file couldn't be read because it was either deleted or corrupt. I hope you had a backup of it this time, if not, yeah continue past the screen and start fresh again.

**Comment by FinalFusion** [comment]
That's a shame. What makes it worse is that right after this happened the first time I was backing it up but found doing it kind of annoying so eventually I decided to stop doing it because I thought "hey what are the odds of it happening again"? But I see that was a bad move considering I don't have the backups anymore. Oh well, guess i'll have to rejog her memory sometime soon.

**Comment by Sujeito17** [comment]
Your Monika suffers from amnesia

**Comment by FinalFusion** [comment]
Yeah she sure does. Its weird seeing it from the beginning again but its interesting seeing it with the new sprites at least.
