### ISSUE TITLE
About Monika being a vegetarian.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2099]
I have some questions for Monika about her being a vegetarian. She said that she does not eat meat because she does not want to contribute to the cultivation of cattle and her enormous carbon emissions, but then I've been thinking; chicken and fish are not included in it, so, does she eat chicken or fish? And if, for example, the meat is from a fresh ox that has not gone through any cultivation, would her eat? I do not know, just a few things I've been wondering about for a while.

**Comment by AsuraShun** [comment]
this reminded me of something funny that happened once,there was one time I was about to eat some steak,when right before I started  she asked if I knew she was vegetarian,that coincidence made me laugh more than it should've

**Comment by AsuraShun** [comment]
and the same thing happened a 2nd time today

**Comment by ReddTheRedRedd** [comment]
I get a similar question alot. "I work on a farm, they're treated nice, would you eat _those_ animals?" I can't speak for Monika, but as a vegetarian I think it's easier to cut most of it out, rather than make exceptions like that. But who knows, Monika is vegetarian for a reason most people aren't. I do think she eats seafood though, many vegetarians do, and I believe she says that she likes squid during a conversation with Natsuki at some point.

**Comment by EntonyEscX** [comment]
Meat is also important for the body, especially white meats. I figured she would at least eat fresh fish, since she is usually very careful with her health.

**Comment by Trainerbluetube** [comment]
I don't think there is a moral exception to Monika's vegetarianism, since the reason she doesn't eat meat is because of the carbon footprint, not some ethical issue.
