### ISSUE TITLE
"Mommy" Monika nicknames

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2119]
![324353](https://user-images.githubusercontent.com/42453997/44420771-bd923600-a576-11e8-8664-5c07567e41db.png)
This dialogue just feels out of place for this mod, since it's both lewd and meme-related.

**Comment by ReddTheRedRedd** [comment]
..Is this a response to if you make her nickname mommy? xD

**Comment by DiggyDog2** [comment]
Yep, don't know how it got in.

**Comment by antimockingjay** [comment]
I mean... I feel like the solution is simple. Just don't nickname her that. This is kinda like buying chocolates that clearly have almonds in them, and then saying, "Why would these have almonds in them?! I'm allergic to almonds!! This is unfair to anyone with allergies!!"

Like, it's two lines that _slightly_ push the boundaries. You literally have to _actively search_ to get this dialogue, and yet you're complaining that you had to see it. Also, how on Earth is it meme-related?

With the amount of effort needed to find this, I kind of feel almost like you're just looking for something in the mod to be upset about. You have to actively seek this dialogue out, which you _chose to do,_ only to complain about it once you found it. I find that a bit odd, honestly.

I may be reading too far into it, but either way, I think you're being a bit unfair by actively seeking something out, only to say it's wrong for it to be in the mod. It'd be like complaining because there's a gender-neutral option simply because _you_ don't feel a need for it, which clearly means no one does, right?

If you don't like the dialogue, that's fine, you're entitled to that opinion. Just don't give her that nickname. It's honestly that simple. But don't seek out the dialogue then try to complain to get it removed

**Comment by ReddTheRedRedd** [comment]
^ He has a point. You most likely aren't going to name Monika "Mommy" unless you yourself are memeing, why get mad at the mod for joking back? And about it being lewd, there are already lewdish topics in the mod, so..

**Comment by DiggyDog2** [comment]
Eh, just felt it was out of character to me, if nothing else, but I'll bite.
Nothing wrong with addressing it.

**Comment by ACoolCat** [comment]
I think that it is a bit memey, but she should still respond to it since immersion is key with this mod, at least in my opinion. There's a simple solution that satisfies both sides, just make her a bit more tongue and cheek in her response. Make her say something along the lines of "Well if it'd make you happy you could call me that" before that line then give an "Ahaha~" At the end

**Comment by ThePotatoGuy** [comment]
Users who name her mom-related terms are most likely referencing the meme. We're keeping it as a callback to them.
