### ISSUE TITLE
[Suggestion] Monika helps you study effectively!

### ISSUE THREAD

**Issue by MeatbagNPC** [Monika-After-Story/MonikaModDev#2120]
Is it possible to add a feature where Monika reads you a txt file? Let me explain: I'd like to save Chemistrybook.txt to Monika's directory, and she should be able to repeat it through the game. While doing so, she should be observing a large book between her hands. Occasionally, she could stop reading and look at you for a few seconds, or make a thinking face, or make a joke, or make a grammar mistake as her face becomes red, or anything else you could think about

**Comment by Sujeito17** [comment]
That is interesting, if you study can be useful (for me isn't useful XD)
I don't know if that is can be possible but...
I think is a little empty thing to add, however is a realistic thing.
Maybe grammar mistakes can be impossible. The other things I think may be possible

**Comment by Tiler17** [comment]
I would imagine doing that would make studying significantly more difficult, especially if she's occasionally making jokes or being otherwise distracting. You'd have to read at Monika's relatively slow text speed in small chunks, and going back to look at something stops being an option after so much text has gone by. I do get it, studying with a partner makes studying a lot more bearable, but if you really are trying to focus on studying, then I don't think copying the text into Monika's dialogue is the way to do it

**Comment by ThePotatoGuy** [comment]
I like the concept of studying with monika. We can just make the text display instantly during study mode so text speed wont matter.

But I think something more like a quiz or test-style would be better, monika would ask you questions, you have to pick an answer, and you can add these things via txt / jsons.

or even flash cards could be possible, hmm

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into this[
