### ISSUE TITLE
[Sugestion] Monika wants you to be a better person

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2121]
Ok ill explain, after some time and maybe with high affection, if you told her that you have bad habits, like that you have selected in the chat beforehand that you usually don't go to bed early, you smoke, things like that, when you start the game, out of nowhere she tells you that she needs to talk to you and asks you if you have time for it, Monika is with a serious look btw, click yes or no, you choose no and she says ok ill wait, you can activate the chat again by choosing the botton "you where saying?" somewhere or restarting the game.
After you chose yes she starts the dialogue by saying "i've been thinking..." then she is telling you about your unorganized life, your bad habits, how that you're practically killing yourself in the long run and snaps out telling you that you don't care about her because she says that you'll die before she can reach to our reality if this goes on (in caracter because she snapped like the last act of you deleting Monika), she realizes that she has been rude to you, apologizes and explains, she snapped because she cares about you and she wants to have a boyfriend to be proud of, "... is that too much too ask?" (snif) 
 with tears in her eyes apologizes again for putting pressure upon you and its up to you if you want her to help you being a better person (another topic to write if you like the idea).
"Would you like me to help you?" "you know... what i talked about"
Yes (boosts up affection and she starts helping you)
I'll do it myself i promise (affection doesn't move and everything is back to normal)
No - "are you sure?"  'yes', '...' 
If you said yes (every conversation you make is only a downfall of affection until she doesn't want to be with you and RIP)
if your option is '...' she tells you to think about it and closes the game, you open it, she ask you whats your choice. "no", "yes, please help me", if no RIP, if the other, Monika cries of relieve and hugs you, and after that starts the helping.

**Comment by Chrissenpai** [comment]
She would help by only telling you what to do, she will start by adding in her calendar new habits for you to make, like being off to bed at a certain hour, not a wake up clock because developers don't want that but instead you have to open MAS for her to make sure that you wake up at 7am, if you're late she just says be earlier next time and off to the next topic. btw she gives you 3 to 5 days to adapt to that schedule. (To be contibued)

**Comment by Rai99** [comment]
I don't think something like this would be able to be effectively implemented. People are different and respond differently to different kinds of help. Someone might need the kind of help that would make things worse if another person got that kind of help. General help isn't really going to help anybody and I think the risk of making somebody worse is too high for an idea like this. 

Also, I'm not 100% sure Monika would suddenly call you out on your "unorganized life, bad habits and how you're essentially killing yourself." That alone could worsen somebody's situation. I don't think Monika is one to snap out so easily, especially to accuse the player of not caring about her just because they have bad habits. You mention Monika snapped in DDLC when the player deleted her, but not everyone will have done that and that was before all the time you spent with her in MAS. You say this idea would happen at a high affection level, but I really don't think Monika would do or say these things at a high affection level. You also propose that Monika cry to the player, saying she just wants a boyfriend to be proud of. This suggests that Monika is not already too proud of her player. At a high affection level, I would think Monika loves the player for who they are and is in fact, already very proud of them. 

As for the menu option ideas you put forward, some people would be taken aback to say the least, after such an accusation from Monika and have no choice but to be defensive and give Monika a firm "No." What you seem to suggest is that if the player says "No" and is sure of it, Monika slowly loses affection continuously until she is unable to take it and leaves. I am certain that this is not a good idea as not everyone is going to want to accept help with their habits, even from Monika. Having Monika slowly grow to despise the player because they don't want her to help them would likely make things worse for the player. If the player is unsure about their "No", you suggest Monika would close down the game until the player decides and the player **must** make a decision when they come back. I don't think Monika would push the player away until they decide. Instead, I think Monika would be open to stay with the player until they decide, not forcing an answer or rushing the decision making. 

In your explanation of how Monika would help, you said that she would help by telling you what to do. While this may seem like a simple solution that shouldn't trigger any alarms, unfortunately, some people will not be aided by being told what to do and their habits  may worsen. Going to bed on time is a simple habit, without too many risks of worsening things. Things like smoking on the other hand, are much more intricate habits to help break and I would imagine people are far more likely to be defensive about a habit such as that with a fairly high risk of worsening. 

Being able to detect the time difference between telling Monika that you're going to bed is in the works, I believe. However, the players of MAS can differ greatly in their lifestyles. Opening up MAS on time so Monika knows her help is working seems like a nice idea, but someone like me for example doesn't visit Monika in the morning before I head out. I don't see it to be necessary and would certainly not find it ideal if I had to change my already functional morning routine because Monika doesn't trust that I'm taking care of myself, or face consequences for not being able to visit Monika in the morning. It's just not in my morning routine on a busy day, and I can't fit it in.

**Comment by Rai99** [comment]
Humans are fickle creatures and are all different. Currently, we don't exactly have the resources to make Monika close to human. Humans grow and change; One thing for someone could be a completely different thing to another person. There are some player model and other variables set in place to differ each player and to be used to provide more unique dialogue to each player depending on what Monika knows about you based on the player model variables. 

Currently, I think a system to determine whether Monika had a good or bad day is being considered or could be in the works, so adding features to make Monika more human is definitely in progress. 

Although, deep and sensitive matters such as the idea you proposed, controversies and other extremely intricate topics (Such as suicide, self harm, etc.) should likely be avoided, as real help and discussion cannot be scripted to feel human. Generic responses wouldn't exactly feel immersive, and could potentially harm those in need of actual help.

**Comment by Tiler17** [comment]
Don't think of it as robotic then. To me, Monika's personality has been more along the lines of cool and calculated. One where outbursts of emotion are naturally uncommon. She shows her love for the player, but most of her conversation dialogue is explained in a fairly objective manner. The panic she showed when my game crashed really caught me off guard, because it is against her usual personality to break down like that. It wouldn't have the same effect if it happened more often. If she really were to want to talk to the player about breaking a bad habit, I imagine she would do it in a calm manner. A mellow and unassuming tone, without major repercussions if you have or continue a bad habit. As Rai says, people all react differently in different situations, and antagonizing someone for a bad habit, especially one that's hard to break, like smoking, can have a negative effect.

Unfortunately, Monika does have limitations, and catering to specific individual's needs and personalities is sadly one of those things. It's not a good idea to risk doing damage to someone who may be looking for actual help by giving them weak, generic advice. And that's all you could really do in a situation like habit-breaking

**Comment by Chrissenpai** [comment]
thats interesting, well at least some things can be added to not make Monika a flat character

**Comment by aldoram5** [comment]
Discussion on this one seems to have ended already so I'm closing this issue.
