### ISSUE TITLE
Expression Guide

### ISSUE THREAD

**Issue by Tiler17** [Monika-After-Story/MonikaModDev#2138]
Quick question: I was thinking about trying to write up another contribution. Part of that involves giving Monika her expressions and poses, but given that she has a thousand expressions now, the cheat sheet I used in June, which is still on the contribution guide, is hopelessly outdated. I checked out the code required for the expressions. You need, like...3-5 letters now, and I dunno what any of them mean.

I poked around in the wiki and such, but I didn't see anything recent that would function as an expression guide. How might I go about finding a new cheat sheet?

**Comment by multimokia** [comment]
There's an expression previewer in the `dev` folder. Grab the raw of that, download it, and create the dev folder in your `game` folder and then put the expression previewer in there. (You might want to edit it so it's not a random topic though... Otherwise it'll come up during random conversation) The previewer also lets you see if your sprite code is invalid (it'll be highlighted in red)

**Comment by Tiler17** [comment]
Very helpful, thank you both!
