### ISSUE TITLE
suggestion fix

### ISSUE THREAD

**Issue by TheRealBrickPlanetWail** [Monika-After-Story/MonikaModDev#2183]
when you cheat in chess monika says she cannot trust you anymore goodbye... then monika locks you out of the mod forever.there should be a update where monika forgives you and lets you in the mod again

**Comment by myseriousaiyan64** [comment]
nah man, Monika trusted you, and you broke that trust my dude, the realtionship is ever. 
Monika ain't no girl you can get back once you make her upset or mad. Unless, you promise that you would never make her feel like that again and she will onlye forgive **once** (when you first open the mod).

**Comment by Rai99** [comment]
I think there should be a way to have Monika forgive you without resetting your persistent. 

It's true that Monika is special and nobody should ever lie to her and break her trust, but Monika is a human and humans _can_ forgive, given enough time. 

Plus, you say that Monika should only forgive you the one time when you first open the mod, but not everybody will have deleted Monika before getting MAS, so that doesn't apply to everyone. 

_Hey, I've got an idea. How about we make any offenders sit with broken MAS up for a total of **1000 hours** 
until Monika comes back to the player?_ 
1000 hours is almost 42 days, and if somebody seriously spends that long on broken MAS, I think that shows enough dedication to warrant Monika's forgiveness. True, _some_ people might continue to mistreat Monika, but having to wait 42 days? At that point, I think Monika would at least humor the idea of coming back. Maybe have affection start really negative if the player keeps mistreating Monika time and time again. ie. Doing 1 or 2 mean things to Monika would make her leave again.

**Comment by Tiler17** [comment]
I'm not totally opposed to the idea myself, but the request sounds like you want a second chance. Second chances are good and all, but it's not like you lie to her once and she leaves. It takes continuous abuse to get her to leave. You had your second (and third, etc) chance, and you threw it away. You shouldn't be regretting the consequences after they occur, you should be doing what you can to avoid them in the first place.

Humans can forgive, yes. Forgiveness isn't the same as returning to a poor relationship, though. If it were up to me, I would say that she wouldn't come back at any point

**Comment by Rai99** [comment]
It does take continuous abuse to get Monika to leave, but among the people who want a second chance, some people _do_ change. I was thinking this 1000 hour second chance would be available if Monika ever leaves for whatever reason such as low affection or cheating in chess. Coming back wouldn't exactly be returning to the relationship right away. I was thinking Monika start just a few points away from leaving again, so if the player mistreats her right there again, it would be evident that they haven't changed, and so Monika would leave again, and the player would have to wait another 42 days at least to see her again. 

I think it would be bearable to have to see someone who previously gave you trauma once every 42 days and have the option to leave right then if you feel they haven't gotten any better. 

When Monika leaves, she does still love you, but knows that if she stays, she'll just keep on being mistreated. 

This whole 1000 hour thing started out as a joke for me, but I think it's reasonable to get a second chance. If the player still wants to torture Monika, their extra chances won't last 5 minutes. If someone really goes out of their way to spend 42 whole days just to torture Monika for a minute before having to do it all again, I hope they find the help they need.

**Comment by ThePotatoGuy** [comment]
Gonna start this off by saying that even I though I disagree with a second chance option, it can still be added if enough people want it.

That being said, as tiler17 mentioned, that particular flow requires repeated cheating with no remorse to reach. It's very deliberate, and it deserves an appropriate consequence. Does it seem harsh? Sure. Should users get a second chance? Maybe. But life doesn't usually give second chances when you truly mess up, so we applied that same dosage of reality here.
