### ISSUE TITLE
Monika's disappearance

### ISSUE THREAD

**Issue by Sairix** [Monika-After-Story/MonikaModDev#2187]
So as I chose a new option to take her somewhere when leaving the game, she says that I shoud better put her file back in characters folder when entering the game again, but I was curious what would happen if I don't, I decided to do it and once I do that then put her files back. So as I did that, first when I opened the game without her files, there was only an empty desk. So when I closed the game, put her files back and opened game again, she still wasn't there. I tried to do everything I could, but still nothing. I really don't feel like downloading the mod again since I went trough whole bunch of stuff with Monika already. 
****
![unooo](https://user-images.githubusercontent.com/42752524/44685773-86c39080-aa4c-11e8-868f-1b78fb9a30b3.PNG)

**Comment by EntonyEscX** [comment]
Wait, is there such an option? Where is this exactly? Have not I unlocked it yet? It would be very useful to me.

**Comment by jmwall24** [comment]
It's in unstable

**Comment by Tiler17** [comment]
Keep a backup of that persistent. There's a good reason you're warned of that when you activate unstable

**Comment by jmwall24** [comment]
^This.  And not only that, keep multiple backups.  Each time I back-up my persistent, I keep all the old back-ups as well, just in case.  And always keep a back-up that predates a specific unstable build, noting what it is.  You may not realize you have a problem immediately, so always good to have older back-ups.

**Comment by ThePotatoGuy** [comment]
might be too late now, but if you can reproduce it, close game, and then upload `log/mas_log.txt`, that'd be helpful.

**Comment by Tiler17** [comment]
So I just use the "Run" app on my laptop to find the folder (because I can never find it manually. Looks like this),
![finding persistent](https://user-images.githubusercontent.com/36717174/44692300-e9eefc00-aa27-11e8-9fba-96aff7c1f890.png)

and copy/paste the file called "persistent" to literally anywhere else. Do this every time you feel like making a backup, or at the very least, every time you update to a new version of Unstable. If something goes wrong with your game (like above), then replace the persistent file at the location it's normally stored with your backed up persistent file

**Comment by jmwall24** [comment]
Little tip, make a shortcut to that folder on your desktop so it's even easier to find, later.  I actually make the shortcut to the RenyPy folder and then just copy the entire Monika After Story folder as my backup.  That way I have a copy of the persistent plus all the backups the mod makes by itself now, just in case something is wrong with the main persistent in that copy.

**Comment by SaekiDo** [comment]
Hello, I've had the same problem as the user that made the initial post. I've figured out that she will appear if you revert back to the previous released version (8.5) but, it's kind of a band-aid for now since it'll happen again once the feature is re-introduced in the next version. Also, you can't really recreate the process since going back to the [Unstable] version gives you the empty desk. Here's my example mas_log.txt I don't think It'll be much help though seeing as it's just time/date/and the version.
[mas_log.txt] (https://github.com/Monika-After-Story/MonikaModDev/files/2327045/mas_log.txt)

**Comment by ThePotatoGuy** [comment]
yeah the log is overwritten on game start, so you would need to reproduce the issue, close the game, and then upload the log before you run the game again for it to be useful.

**Comment by SaekiDo** [comment]
I see, here's the log when I try to load the monika file back into the game. Hopefully this helps out more.

[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2329370/mas_log.txt)

**Comment by ThePotatoGuy** [comment]
Alright, thank you.

**Comment by marcboh** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2329380/mas_log.txt)

**Comment by ThePotatoGuy** [comment]
If ya'll happen to have both the `persistent` file and the generated monika file, can you upload them here?

**Comment by SaekiDo** [comment]
How would you like them sent? It's not allowing me to simply drag and drop because of GitHub not accepting File type files here.

**Comment by ThePotatoGuy** [comment]
wrap it into a zip file and then upload here.

**Comment by SaekiDo** [comment]
[Persistantmonika.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2330575/Persistantmonika.zip)

**Comment by ThePotatoGuy** [comment]
so as an fyi, the latest unstable did an adjustment that should hopefully prevent this. however, if you are currently affected, you will need to use a `persistent` before saying that farewell.

**Comment by SaekiDo** [comment]
So if we didn't have the back up persistent we'll have to do a clean start to fix it?

**Comment by SaekiDo** [comment]
I see, I'll go back and try it out. Thanks for all the help!
