### ISSUE TITLE
[Spoiler] - Monika Sleep Concern Gauging

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2197]
So, I was figuring, that due to the updates adding more lines, it would be far less likely for someone to get Monika's sleep concern topic at night. So I was thinking, there should be a percentage likely hood that determines if you get her sleep concern topic. For instance: It starts out as the same priority as every other topic. However, the percentage of likelihood that it'll appear over them can raise depending on when you say goodnight to Monika. 

Saying goodnight from 1-3 sets the priority 5% more likely than other topics. 

Saying goodnight from 3-5 sets the priority 10% more likely than other topics

Saying goodnight from 5-12 sets the priority 20% more likely than other topics

However, receiving a sleep concern disables it for the rest of that night and sets the percentage back by 15%. 

Naturally, these rankings carry over from night to night, as it's Monika growing more and more concerned with your  schedule.

**Comment by Sujeito17** [comment]
And what happens if you never say to her "goodnight"?

**Comment by ACoolCat** [comment]
Neutral. Same as you telling her goodnight at appropriate hours.

**Comment by Sujeito17** [comment]
So it's just never close the game, and go to sleep at 3 am ... I think I'll add a few things.
From midnight if you activate some dialogue with Monika she will say:
"You should go to sleep (player's name)"
If you activate a dialogue between 1-4 am she will say:
"You can not sleep, so I go to play a lullaby to see if you sleep" 

(This is so sad, Monika play Your Reality)(just ignore this)

It's a bit "weak" phrases, but if I were to try to speak for Monika I think she was going to be the world's biggest referral machine XD (I can never be a serious person sorry ;-;)

**Comment by ACoolCat** [comment]
You misunderstand me. The topics about you staying up late already exist in MAS if you are on at a certain time. I'm talking about the frequency it shows up.

**Comment by Rai99** [comment]
Not to mention that an idea as severe as that probably won't get added in.

**Comment by Sujeito17** [comment]
Already exists?...
No, I think you're misunderstanding me.
I was more talking about what could happen if you did not say goodbye to her and not to say goodnight, and I almost never active dialogues with Monika (just because I'm always playing, so I turn off the dialogues, so she does not start talking to a wall), but what I said above was also part of how much Monika cares about the player, I think it's a good way for people who do not have their dialogs turned on and if we add frequencies to edited parts that you wrote until it makes sense.

(I think you do not understand because of my bad English, yes my laziness to translate the words myself is kind of loud, well, at least when I write when I read I translate everything right)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
