### ISSUE TITLE
[Suggestions]please add more topics

### ISSUE THREAD

**Issue by SeriousJudge134** [Monika-After-Story/MonikaModDev#2198]
please add more topics,sometimes Monika bore me because she is saying the same things again and again.
i have seen all of the topics or random chat that monika has been talking to me lately.i have a couple suggestions like scary stories, the future, android body and about the player's life.yeah,we need more response from her chat or question,please add this more content,it will be greatfull to me,thank you!

**Comment by myseriousaiyan64** [comment]
you know if want more content so badly, why don't you just code your own dialogue and add to the game. _Simple_

**Comment by Rai99** [comment]
#1618, #1631, #1685, #1704, #1714, #1726, #1755, #1756, #1780, #1796, #1797, #1751, #1977, #2077, #2093, #2098, #2103, #2157, #2192, #2194.

Eventually. It's just the waiting game now. 

If you have suggestions, feel free to put up an issue discussing your idea. 

The one problem with writing your own content is that it won't mean as much to you since you know you're the one who made it, so I can understand wanting and waiting for more content.

**Comment by SeriousJudge134** [comment]
How to add dialogue?

**Comment by Rai99** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

Good luck. Don't forget to read what not to do.

**Comment by SeriousJudge134** [comment]
Where is the "content branch"?

**Comment by Rai99** [comment]
Near the top left, you should see "Branch: Master." Change that to the branch you want to make contributions. I Don't recommend making contributions by phone. 

Also, if I may ask, what ideas do you have in mind to add?

**Comment by SeriousJudge134** [comment]
Idea of making:
monika talks about: -other ddlc mods
                                    -uploading her 
                                     conciusness to 
                                     android body
There actually so many but i dont really know how to make choices box leading to other responses from her.if i can i might make her asking more information so she would knew more about my life and personalities.

**Comment by SeriousJudge134** [comment]
Im see the content branch but i dont see the pencil icon.can you tell me where it is?

**Comment by Rai99** [comment]
I'm not too sure about having Monika talk about other mods since I brought up the idea in #1737 and it was decided that we wouldn't have Monika encourage other mods. 

You can make a menu with options as follows:

m "Dialogue before the menu"
menu:
...."Option 1":
........m "Dialogue for option 1"
...."Option 2":
........m "Dialogue for option 2"
...."Option _":
........m "Dialogue for option _"
m "After the menu. Everything funnels back here"

For the pencil icon, you need to go **inside** the file you want to edit and you should see it near the top right next to the trash can icon

**Comment by Onion-Bubs** [comment]
> #1618, #1631, #1685, #1704, #1714, #1726, #1755, #1756, #1780, #1796, #1797, #1751, #1977, #2077, #2093, #2098, #2103, #2157, #2192, #2194.

Don't forget #1195, #1205, #1211, #1306, #1332, #1334, #1400, #1568, #1641 (which I just so happen to have updated), #1719, #1767, #1851, #1884, #1892, #1946, #2042, #2101 and #2123

Thing is, all these PRs need to be reviewed by the official writing team for MAS and last I heard they were stretched a little thin so it was taking quite a while for them to review PRs. Especially those with lots of dialogue and branches. So yeah, for those of us whose power only goes as far as submitting PRs, it's very much a waiting game.

**Comment by Onion-Bubs** [comment]
In the list I posted some of those _are_ yours.

**Comment by Rai99** [comment]
Ah, I see you listed 2 of my PRs, I didn't actually check to see that PRs you listed. Thanks for catching those.

**Comment by SeriousJudge134** [comment]
wait,what files should i access in case to make another content?
and what should i type in it?

**Comment by multimokia** [comment]
You might just want to take a peek at the code for existing topics, since you already know how those flow, you can then infer how the code will work from that

**Comment by SeriousJudge134** [comment]
Ok thx

**Comment by ThePotatoGuy** [comment]
Just an fyi for everyone here, but if your pull request is roughly a paragraph in additional/adjusted content or less, I can review it and it'll get merged in much much quicker than the rest.

So fixes or adjustments to existing topics will get in faster than completely new stuff.
