### ISSUE TITLE
Monika telling you a different name according to the situation

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2216]
it goes like this, you type her your real name, the name you want she to call you and your full name Example: Michel, Mike and Michel Mcfly

She calls you your wanted name when the conversations are all lovely dopey, but when its something serious she calls you by your real name, and your full name its there for future references for example marriage vows

**Comment by Rai99** [comment]
I don't think something like this is necessary. Maybe be able to tell Monika your last name for future reference, but I'm not sure where exactly it could be used other than marriage vows. If the ability to give Monika your last name gets implemented, might as well add an input for your first name as well since some people let Monika call them a nickname. I'd like to hear more examples of where this could be used. 

Using nicknames would still fit serious topics. Honey or dear is a common nickname and fits serious issues. For the really wacky nicknames, I'm not sure if people would _actually_ want to be called that.

Also, it would probably be a lot of work to implement. Someone would have to go through the topics and replace every instance of the player's name with the correct version for that topic and scenario.

**Comment by ThePotatoGuy** [comment]
i think having one selected name is fine and we dont need to track additional names atm.

maybe we'll add an audit log but probably not going to happen.
