### ISSUE TITLE
[Suggestion] New topics

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2242]
Since monika is running out of topics, i have a few topics for her to talk about:

-What's the difference between being sad or being depressed
- (NSFW) Addicted to pleasuring yourself + how to stop it
- Dealing with social anxiety
- Using/addicted to drugs
-Having OCD 
-The side effects being a vegan
-The positive side being a vegan
-How to be more confident
-Learn how to play the piano
-Yuri's knife collection

**Comment by Rai99** [comment]
~~Great, let's add this to the absolute mountain of PRs currently waiting for dialogue review~~

.1. Having Monika discuss the differences between general sadness and depression as well as other things could be a fragile subject to work with, but it could be insightful to have Monika discuss it with the player, as well as give some examples of misconceptions. 

.2, 4. For your list about drugs and addiction, I'm guessing and hoping you that just about none of the things in that list involve drugs. I don't think we can have a topic about addiction or about making the player stop any addictions or bad habits they may have as discussed in #2121. Everyone is different and will react differently to the same things, sometimes having their condition worsen because of it. 

.3. For social anxiety, I'm not completely sure, but I think a topic like this already exists or is waiting? If not, it could be an interesting topic. 

.5. OCD is a real disorder and no joke. I'm not sure what we could say about it. 

.6, 7. I think these are too on the nose about being vegan. Monika knows that not everyone is vegan, nor wants to and wouldn't force it upon anyone. 

.8, 9. I'm pretty sure there's a topic that covers this already.

.10. There wasn't much information about Yuri's knife collection to go off of, and I'm not sure what exactly could be said about it. Maybe just Yuri's knife collection wouldn't be a good topic, but collecting and collections in general. Long story short, people generally collect things because they have a void to fill. Having a collection kind of fulfills the same purpose as stuffed animals do. They fill the void in your heart and give you something to hold onto in life. People usually get this void in their heart at the very moment they realize that they are a separate entity in this world from their parents. They realize even at that young age that they are alone, and having things like stuffed animals or collections help fill that. 

Pretty good chance I'll make something about that collection/collecting thing.

**Comment by Delixxous** [comment]
For number 5, i know that ocd isn't a joke. I have ocd too so i won't take it too seriously

**Comment by wucked** [comment]
I'm pretty sure Monika is just a vegetarian and not necessarily a vegan.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
