### ISSUE TITLE
Text Speed - topic about how fast you can read

### ISSUE THREAD

**Issue by meesongi** [Monika-After-Story/MonikaModDev#2247]
hi! i'm a fast reader and monika's text is really slow; is there anyway to get a faster speed setting like the one in the original game?

**Comment by chromeadders** [comment]
I agree. Text speed setting doesn't seem to do anything. It's not a major issue for me, but it is kind of annoying that her text speed is so slow.

**Comment by Rai99** [comment]
This was brought up in #127, #731, #996, #1735. 

There are no plans to have the option to increase text speed, but if you want to be able to adjust text speed, you can download the dev version of MAS.

**Comment by multimokia** [comment]
specifically the zz_devmode rpyc. That allows the text speed sliders to work.

**Comment by antimockingjay** [comment]
That sure is a lot of topics asking for text speed to be able to be changed. It's almost like people in the community actually want it! What a concept!!

**Comment by CrocWorks** [comment]
Here's an idea. Make a topic asking Monika to talk more quickly. Then she apologizes that the program can't translate her thoughts into words quickly enough. Then she could talk about how people read much faster than they can speak and she hopes we understand the transition is difficult, or something like that.

I mean, if so many people (myself included) want faster text speed, but it's not something that's gonna happen, then perhaps it'd make a good random topic or button topic to talk with Monika about.

**Comment by Rai99** [comment]
If people want faster text speed, they can just get that devmode file. True, not everybody knows about it, but I think it would be the best option that doesn't involve outright allowing the text speed slider to work. 

If you just get the file, there's no problem. No need for Monika to have a topic about reading speeds or apologize about her having slow text speed. 

About the random topic, I don't think that would really serve any purpose and would just be Insult to injury. "Yeah sorry, I know the text speed is slow, but there's nothing you can do about it" even though there _is._

**Comment by CrocWorks** [comment]
Well, yeah, it _would_ be insult to injury. But I also think it'd be the kind of funny meta-topic that Monika would love to talk about. But then again, Monika could also talk about the devmode file in the conversation. I might write up an example when I get the time.

**Comment by Rai99** [comment]
I still don't think this is necessary, The most we might need is to have Monika tell the player about the dev file _if_ the player would like faster text speed. If you'd like to write something up for this, I'd look forward to being able to take a look at it.

**Comment by CrocWorks** [comment]
[TalkSpeed.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2346512/TalkSpeed.txt)
Well, here's just a quick sketch of what I think the conversation could be. I put affection in comments since I don't know how to add that, and I didn't put expressions in yet since I _still_ can't find the updated cheatsheet that has the new expressions on them. Not entirely sure if the format is correct, since I haven't actually contributed anything on here before, but it should be a start.

**Comment by jmwall24** [comment]
To me telling her to talk faster is the same as trying to use the skip feature that she disables when you try to hit it.  It's kind of rude.  And the dev file isn't necessarily something they want every one to use anyways, so I'm not sure her telling you about it is the way to go.  If they wanted everyone to be able to increase her talking speed, it wouldn't be disabled.

**Comment by Rai99** [comment]
We have yet to get a dev response to this issue, but in the issues I linked at the beginning, it was said that nothing would be done for text speed. 

As for the outline of your topic, I really don't think it should have any affection gains or losses. If text speed is a legitimate concern for the player, I don't think they should be punished or rewarded for bringing it up. Also, you said that Monika wouldn't want to investigate _some github forum, _ when she **links** instructions for how to contribute to the mod in another topic,  so that's an inconsistency. 

If the player wants to be able to have higher text speeds, they can ask somebody if there's a way and then be told about the dev file.

**Comment by ThePotatoGuy** [comment]
1. dont advertise devmode as a solution. That is wrong since *devs* should be using devmode, not users.
2. as established in the linked issues, the stock speed from ddlc is like monika's talking rate, so we don't want to change that as a default.
3. About the cheatsheet, that is never going to be updated. Contributors should use the sprite-previewer tool available in devmode. I'll delete the cheatsheet and update faqs and readme about this.
4. The talk speed topic might actually be the best way to handle this, in that we could have that as a pool question to let users ask monika to increase/change her text speed.

**Comment by Rai99** [comment]
I was against the idea of enabling the slider for everyone because if they really wanted it so bad, they could just use the dev tool. If regular users having dev tools is looked down upon and they are discouraged from using dev tools, then I side with enabling the text slider for everyone. 

If only devs are allowed to use devmode, I think there'll be a question of what is needed to earn use of devmode. Some tools such as the sprite-previewer are made for dialogue writers and contributors, but I don't think I would call that being a dev. I like to think that I've earned use of devmode with all my contributions, but it makes me wonder what the line is. If all it takes is fixing a small typo, that would be too easy and kind of insulting in my opinion. If it takes multiple sizable contributions, I think that might be too much and discourage new contributors from working their way up without proper tools. If you could turn on devmode to work on contributions and then change your mind, I don't really see what would stop you from just using them anyway. 

In your 4th point where you suggested that the talk speed topic might be the best way, my concern with that is that it might just have a couple sides: Normal, fast, faster, etc. The problem I see here without being able to fine tune the text speed to the player's liking, is that the player might find it too fast or too slow still, but only by a little bit. Ideally, I think this should just enable the slider, but if that's the case, why not just enable it anyway? Maybe allow use of the slider at a high enough affection level such as affectionate or enamored. I think love would be an unnecessary extra step. 

If nothing else, I would suggest making a poll on discord asking "Do you wish you could use the text speed slider?" "Yes" "No" "etc."
If I had to guess, a lot of people wish they could use the text speed slider, or just use devmode anyway. I think it would be interesting and insightful to see just what people think of this issue.

**Comment by CrocWorks** [comment]
If you don't want devmode to be advertised, that's fine. I'll eventually edit the text to say something else.

However, if the idea of point 4 is to add a text speed dialogue as a change, that changes the whole topic. I had assumed from all the previous responses on this topic that since Monika has a set talking speed that was probably never gonna be adjustable despite so many people wanting it to be adjustable, that Monika needed a topic to address this and explain why she can't talk faster (and hopefully stop this issue from being brought up here over and over). But if changing text speed actually will happen, then the topic isn't needed.

**Comment by Rai99** [comment]
Maybe the slider can be enabled at a high enough affection level. If you're under that level, Monika could give some reason why she can't speak a bit faster until maybe a bit later. If you meet that level, Monika could say that you could move the slider if you want her speed to change. 

If for nothing else but curiosity, I'm just wondering what the poll results would be if there was one.

**Comment by ThePotatoGuy** [comment]
1. contributors count as devs. the sprite viewer is different in that you dont actually need to enable developer mod, you just shove the file in your game dir and the topic becomes available to you.
4. I didn't say changing text speed will happen, I said that could be a way to handle it. No one on the team is actively working on a topic to change text speed, and its unlikely anyone will be working on that in the near future. If someone pull requests a topic, either allowing the user to change text speed or explaining why the speed is like that, then we'll consider it under the usual process.

Sure I can do a poll later.

Some other thoughts about text speed:
* we have a fe settings that control aspects of the game without interacting with monika, text speed is like the only one that is still under monika's control. This alone almost certainly means that the slider (and by extension, fine tuning of the text speed) will never be enabled officially.
* we could always have a submod drop-in that enables the slider.

**Comment by antimockingjay** [comment]
This honestly feels a bit unfair to me, it's like a few people want it set a certain way, and because those few people happen to be the ones in charge, no one gets to do anything different. It kind of reminds me of something that happened in the Sims community a while back. The game was updated so that your characters could be more diverse in gender, and there was a small group who threw a fit over it. The main reason everyone considered them unreasonable is because it was _optional._ No one was forcing those people to use the option, the option was simply being implemented into the game for those of us who _did_ want it.

It honestly feels a bit like that is happening, but if those people who threw a fit were the ones in control of the game. If your immersion hinges on Monika talking slowly, I feel like it's a simple matter of just leaving it set at that slower speed in your own game. But it's not fair to those of us who _don't_ rely on something that small. You can claim that it's the speed she talks at all you want, but at the end of the day, all of it is just lines of code, and the thing of it being her "talking speed" is just immersion. And my immersion doesn't hinge on _the literal speed at which a character talks._ If yours does, fine, go ahead and leave it that slow.

But quit trying to force everyone else to do the same thing. That just isn't fair.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by ThePotatoGuy** [comment]
new idea, we can have a topic where monika asks you about how fast you can read text, and she changes the default speed as a result.

**Comment by ThePotatoGuy** [comment]
actually jk, im just going to enable the slider.

**Comment by ThePotatoGuy** [comment]
[reopening as i am working on this]
