### ISSUE TITLE
"Thank you for always being with me" disappeared from the 'I want to tell you something' topics

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#2262]
I was able to say it to Monika after the first time she showed me the islands, and once I left the game and came back in, I was no longer able to find it.

**Comment by Rai99** [comment]
That's a one time only thing, Say it once and regardless what you say in that menu option, it's gone.

**Comment by aldoram5** [comment]
Hi RutTutPut!
This was intentional, it was supposed to be a special one time thing, but it has been decided that it will be like the other options, but after you reach a higher level of affection. It still hasn't been implemented as of now, but will be in a future update. We'll use this issue as a way to track the progress of that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
