### ISSUE TITLE
a way to reuse the old talking menu (the typing one)

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2281]
the way you cold reuse the  old talking menu is basically having monika react to your searches on the internet by copy and pasting the url of your search into the menu and depending on the search she will have different reactions for example a search of lewds of one of the other dokis and she would scold you because you dating her and lewds of her would be very similar to her asking you if you've been looking at lewds pictures of her

**Comment by Rai99** [comment]
That sounds like a cool idea, Since I don't think there are any plans to do something like this currently, someone should work up a revised schedule and cost estimate so that you can decide whether you want to do it now or later. 

~~In other words, no, I don't think we can do something like this.~~

**Comment by CrocWorks** [comment]
I had already brought up the idea of using that old talking menu for a search engine for the menus instead (see #1985 ). But what you're suggesting seems closer to actual AI. I don't think that will be very easy to do.

**Comment by ThePotatoGuy** [comment]
#1985 is more likely to happen than what you're suggesting.
