### ISSUE TITLE
[Suggestion] Choosing multiple complements for a single topic

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2306]
It's completely possible for a player to be:-
-Wanting to better themselves for Monika
-Proud of Monika
-Feeling stupid because of Monika
All at the same time.

So it would be unfair if the player wants to be honest about the last one, and loses affection. 

In the system I propose, instead of adding the affection points of each option, the affection gained will not go over the affection given by the best option the player cannot get more affection than the option which gives the most affection, but options which give negative affection will stack up (IDK if there are multiple options in a topic which reduce affection). This will make sure that the player is not able to get more than the intended maximum amount of affection.

And for the lore (IDK what to call it):-

-If you said something really nice, and then said something less nice, she wouldn't like you more because the you because you already said the best thing she could hear (it won't make sense in some cases, but its the best I can think of in my sleep deprived state).

-She would like you a little bit more if you said something nice and then said something eve nicer.

-She would like you a bit less if you said something nice and then something bad.

-She would like you even less if you repeatedly say bad things.

**Comment by Tiler17** [comment]
Well, since as far as I've been able to tell, you can only pick these options once. Once you've picked, it's stored in her memory and she won't have you choose again. So it's not like you can abuse the compliments for affection points or anything. The last half of your post just sort of seems like you're adding the affection points you'd get together, which is how I think it already works. But you're asking to change it, so I kind of feel like I have no idea what you're trying to get at

**Comment by multimokia** [comment]
DDLC/MAS menus work as single select. I.e. their code is structured as follows:


```menu:
          "Option one:"
                    "Result one"

          "Option two:"
                    "Result two"```

And so on. As such, you can only pick one option and get a single result, unless you have menus inside those menus which just make it needlessly complex

**Comment by SaiPrithvi123** [comment]
Nevermind the last part
