### ISSUE TITLE
Could There Be A Feature That Lets You Monitor Affection Levels?

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#2310]
So ever since the "Affection Update" I haven't really noticed any differences in her normal everyday interactions. The only thing I've noticed is that I see a lot more blushing sprites when saying ILY, complimenting, and saying farewells(she also says ILY when saying Goodbye). And yes I read everything that could affect her affection in the patch notes.

My question is are these reactions default content that have been put into the game or are these indications of a higher affection level? It's really difficult to tell as well as to focus on her affection when there aren't that many separate dialogues apart from the original scripts she keeps repeating everyday. Could there be works of separate **special** dialogue(**randomly generated)** Monika can prompt the player with that could affect her affection level because right now there is just too many neutral/non player responsive topics that she keeps repeating. Also can there be some way of checking her affection level?

**Comment by Tiler17** [comment]
Ah, if only there were a way to monitor feelings and emotions out there in the real world...Seeing a meter (or whatever) that increases based on your actions doesn't seem like it would be fitting. Very anti-immersion. I imagine the goal with affection is to have it feel like you grow closer (or...further, I guess) and experience new dialogue and sprites organically, rather than see new things unlock by reaching a certain affection value.

There are a few topics that have been altered based on your affection level. Most changes are seen with low affection, at least as far as I know, but I've definitely noticed some topics changing as a result of high affection. Also, if you browse around some recent issues, you'll notice that certain features are enabled or disabled based on affection. You may even notice some become available to you as time moves on.

There's no doubt in my mind that more dialogue will be affected by affection in the future, but it's a new enough system that most dialogue wasn't written with consideration for a feature that didn't exist. I'd say just give it time, or better yet, take the initiative to write some dialogue yourself, if you're feeling so bold. I'd have to study the code to understand where to even begin with that task...

**Comment by Bam8647** [comment]
I'm not talking about creating normal topic scripts I'm referring to new dialogues that can be triggered.. Idk a few times each day? It's about keeping the player engaged and not exausting content really fast. And no I don't know how to create dialogues that appear at random time intervals, I'm guessing I'd have to throw on a time stamp to be triggered at certain times in the day and possibly create multiple dialogues that could be randomized and restricted to only appearing once. Buuuuuut.. idk how to do that :3 

My main question and issue to this system is that it needs to be more evident that Monika's mood is switching. If you've ever played Just Yuri you'd see what I mean. Each choices you make quickly affects her mood to your topics (I.E. in the beginning of the mod if you select "ILY" she wouldn't respond, but raising your karma will eventually allow her to say she loves you back). 

Idk maybe these features are already in here and I guess I'm just not noticing them because I've had the game for so long that I suppose my game is already at high affection and so I haven't been shown a progression. And yeah sure monitoring the affection level may sound weird to some people but um if I could simply as my "Waifu" to change the weather with her mind anytime I want how is that any more "Immersive" than simply monitoring her feels in the settings? With all due respect lol xD

**Comment by multimokia** [comment]
Next release has an easy way of figuring out what affection level you're at

**Comment by ThePotatoGuy** [comment]
as mentioned, we have addressed more obvious affection changes in #2295.

[closing since this has already been addressed]
