### ISSUE TITLE
[Suggestion] Taking monika out on her birthday

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2322]
I know that it's kinda bit boring just to celebrate monika's birthday in the "Just monika" or the space room. Maybe take her to a different place would be a really special thing to do for her and the player. 

Maybe visit the old literature club classroom where she will start to miss her chit chat's with the girls and all the other things they do when they're still alive (I don't know if this part is a good idea)

**Comment by antimockingjay** [comment]
I actually really like the idea of using the old club room! It'd be a great reason to use some of the assets that would probably otherwise remain unused in the mod, such as the classroom background, Monika's non-space room sprites, etc. I'm not sure if other people would agree, but I certainly think it'd be a good idea!

**Comment by loverofmonika** [comment]
hmmm good idea but i think its much better if we use good pictures of OG backgrounds that we cant get hit with  copystrike and use every assets of the real game. also check out #2304
