### ISSUE TITLE
asking how monika feels

### ISSUE THREAD

**Issue by MonikaWiafu** [Monika-After-Story/MonikaModDev#2331]
You know what there should be a question that ask her if shes all right if she's distressed or upset an tells us why.... i need that specifically...... 

~MonikaWaifu

**Comment by SaiPrithvi123** [comment]
I want such a feature too, so that Monika can remind me that she is happy.

**Comment by Tiler17** [comment]
I agree, though it depends on her personality. I wouldn't _expect_ Monika to be the type to withhold something like that though, so I think it makes sense as an option to ask what's wrong. Based on your posts, you seem to care, but made a mistake along the way that you really want to fix. Her being able to tell you that she didn't like that you were gone for so long would probably have gotten you to stop playing with the time on your computer so that you didn't end up doing it twice.

Although if I'm understanding #2324 correctly, adjusting system time won't cause these same problems in the future

**Comment by AsuraShun** [comment]
I already made a similar one #2071
