### ISSUE TITLE
Won't Detect Song Playing

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#2340]
For whatever reason, even when I follow the guides on playing Your Reality, Monika still can only get the first line. Occasionally, she'll start the second line, but then she quits suddenly halfway through it. I don't know what I'm doing wrong, because I'm being sure to hit it exactly every single time.

**Comment by ThePotatoGuy** [comment]
theres a bit of filler notes between some of the lines that are optional to play. the problem is the start of these filler phrases are the same as the next line, so piano thinks you're trying to play the filler notes when you're not. 

we'll fix this eventually, but its certainly lower priority. try learning the filler notes, they really make the song play smoothly.

**Comment by antimockingjay** [comment]
That's... Only so helpful, I'll admit. I've never played piano, I would have no idea how to learn that. I've literally been going off of the guides online that say what buttons to press, similarly to how one might read sheet music while playing. I don't know how to play piano/read sheet music, I'm just trying to play based on what the guides online tell me.

**Comment by ThePotatoGuy** [comment]
`opo opo ] ] op p[ [ o`
