### ISSUE TITLE
[Art] The Monika's Birthday Cake.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2372]
***Update: I adjusted the viewing angle of the cake to be more realistic (thanks for the tip, @Chrissenpai).**

Well, I do not know what the plans are for the 22nd, so I just decided to help with the "party" making the cake; I think this is my biggest contribution so far.

![birthday cake sprite day](https://user-images.githubusercontent.com/38970166/45567173-6870d980-b82f-11e8-9050-4682dc539ac2.png)
![birthday cake candles sprite day](https://user-images.githubusercontent.com/38970166/45567181-70c91480-b82f-11e8-8ce2-322e0870d94e.png)
![birthday cake candles on sprite day](https://user-images.githubusercontent.com/38970166/45568656-98ba7700-b833-11e8-80a4-276fed618261.png)
![birthday cake candles off sprite day](https://user-images.githubusercontent.com/38970166/45567198-7aeb1300-b82f-11e8-885e-ee7b5337cbb6.png)

![birthday cake sprite night](https://user-images.githubusercontent.com/38970166/45567209-82122100-b82f-11e8-8987-6733e3d64cd9.png)
![birthday cake candles sprite night](https://user-images.githubusercontent.com/38970166/45567215-85a5a800-b82f-11e8-9af9-b1b8a3d4701e.png)
![birthday cake candles on sprite night](https://user-images.githubusercontent.com/38970166/45568642-8cceb500-b833-11e8-9dba-b3c8a45ea536.png)
![birthday cake candles off sprite night](https://user-images.githubusercontent.com/38970166/45567228-8e967980-b82f-11e8-9798-a05407b670ce.png)

![birthcake candles sprites](https://user-images.githubusercontent.com/38970166/45568747-d1f2e700-b833-11e8-988b-bce46cefbade.png)

![birthcake monika example day - cake no candles](https://user-images.githubusercontent.com/38970166/45567414-25fbcc80-b830-11e8-8a53-371fcd82ede8.png)
![birthcake monika example day - cake candles on](https://user-images.githubusercontent.com/38970166/45568707-b4be1880-b833-11e8-81b1-8e12498844fb.png)
![birthcake monika example night - cake no candles](https://user-images.githubusercontent.com/38970166/45567470-4deb3000-b830-11e8-8411-b4574ad428d2.png)
![birthcake monika example night - cake candles on](https://user-images.githubusercontent.com/38970166/45568728-c56e8e80-b833-11e8-8473-b69339c1bfe9.png)

I know it's not the most colorful cake in the world, but I did what I got. I do not know if you already have a cake art ready, but if you do not have it, here's the homemade birthday cake I made for Monika.

**Comment by Chrissenpai** [comment]
I like the cake but fix it, it looks like half of the cake is lifting and half is still on the plate, and don't put the name, what if (you) have changed her name to a different one? sorry for my rambling lol

**Comment by EntonyEscX** [comment]
Well, theoretically the "change name" is to put a moniker on Monika, but Monika is still Monika.
And how so "lifting"? Could you explain better? I depend on Google Translate to understand English and apparently I did not quite understand.

**Comment by EntonyEscX** [comment]
Not necessarily. Anyway, I understand you said half the cake is "floating" (or something), I imagine you're talking about the top half. Well, if that's the case; it is a large cake in height, and has a layer of white whipped cream between the top and bottom halves of the cake, so it would be kind of impossible to make the top half stay on the plate.

**Comment by EntonyEscX** [comment]
I never had much contact with the Spanish language, so I think it would still be better if I kept the English. Besides, we're not the only ones here.

**Comment by Chrissenpai** [comment]
Ok then.
It might be a large cake but it´s still deformed, look it´s not a sin to look for references, just google it and make sure it´s SHAPE form is right.

**Comment by EntonyEscX** [comment]
Ah, now I understand! I'll fix it as soon as I can.

**Comment by EntonyEscX** [comment]
@Chrissenpai You probably have a angle sense better than mine, so do you think that's good?
![image](https://user-images.githubusercontent.com/38970166/45525585-05892f00-b7aa-11e8-9099-03a544a4c6bd.png)

**Comment by antimockingjay** [comment]
@Chrissenpai "It's not a sin to..." seems to be your catchphrase, since you used it here and in #2366 

Buddy, just because someone doesn't want to do what you say doesn't mean they think it's a bad thing to do. It'd be one thing if you were just offering your opinion, and saying that you personally would like it better if done differently, but you seem to think that your opinion is fact.

For some reason none of the people in charge here are calling it out when you're being rude to artists, so I'll do it. Both in this one and the one I just mentioned, you've been rude to the artists, barely stopping yourself from straight-up saying the art sucks. If you hate the lines on the pose or the shape of the cake so much, change it yourself.

Like you said, it's not a sin to do it, right? Since apparently, according to you in the other thread, it's as easy as tracing things. So go do it. No one is stopping you. Change it to be the way you want it, then post it here and if the people making the mod possible like your version, they'll use it. But there's no need to boss people around and be rude about it just because it doesn't perfectly line up with your tastes.

@EntonyEscX I think the cake looks amazing in both versions, and while I do agree that the second one looks better, I think both are great. You did a great job!

**Comment by Chrissenpai** [comment]
Nice work @EntonyEscX you did a good job... and someone got edgy *sigh* look i would LOVE to do the art myself @antimockingjay but the thing is that i have no job now and i need to survive first, (good thing theres monika to confort me) and when i'm stable, i could show you how good i am, also that catchphrase is not meant to be rude, if it sounded like that then i'm sorry, but the reason i'm this strict it's because breaks immersion and immersion, believe it or not, it's important. Also it brings a smirk in my face to see an artist improve like @EntonyEscX Who WANTS to be better for the sake of Monika and i find it ADORABLE, so if i sounded rude i'm sorry but i just want artists to improve, is that a bad thing?

**Comment by AsuraShun** [comment]
freaking wonderfully majestic!

**Comment by GirlwithaWhiteMask** [comment]
Primeiramente ~fora temer~ que bom saber que não sou a unica Br aqui :P 
2 Awww que fofo ♥ 
Você fez os glaces em Verde Menta owo que adorável <3

**Comment by EntonyEscX** [comment]
***Update: I adjusted the viewing angle of the cake to be more realistic (thanks for the tip, @Chrissenpai).**

**Comment by Sujeito17** [comment]
I feel bad for not knowing how to draw now (Não sou a única pessoa que sabe falar português neste mundo tô feliz agora vai facilitar muito meu trabalho)

**Comment by AgentZephyr** [comment]
Disregarding the edgelord from earlier.  The cake looks good! Shadows and the glow look like they line up to me!

**Comment by Delixxous** [comment]
Maybe you could draw a slice/Piece of cake? Or a half sliced monika's birthday cake?
It would be so sweet if Monika shares her piece of cake to The player!

**Comment by moniking** [comment]
@EntonyEscX
I think you're cake looks great my man! I'm sure monbon Would love it.

**Comment by ThePotatoGuy** [comment]
we had our own cake, so we decided not to use. thanks anyway!
