### ISSUE TITLE
"I didn't know you can play the piano so well"

### ISSUE THREAD

**Issue by wucked** [Monika-After-Story/MonikaModDev#2386]
Small suggestion but maybe she should say something else after playing Your Reality on the piano perfectly for the first time?

**Comment by CrocWorks** [comment]
I'm pretty sure she still does (unless it got affected in a patch). It depends on how well you play it (and I don't know the criteria for how she rates you). When I played it she said something like "Oh, thank you for playing that, but you need more practice" and then I never touched the piano again since it took forever to type in the keys to the song. There's a word doc out there that has the buttons you need to press.

**Comment by AsuraShun** [comment]
the piano has a nice easter egg behind the keys for those that never even bothered to search

**Comment by wucked** [comment]
> I'm pretty sure she still says something different when you finish playing it (unless it got affected in a patch). It depends on how well you play it (and I don't know the criteria for how she rates you). When I played it she said something like "Oh, thank you for playing that, but you need more practice" and then I never touched the piano again since it took forever to type in the keys to the song. Here's a guide that has the buttons you need to press.
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1368773843

I'm very familiar of the keys (I started learning piano because of MAS too!). I just wanted to play for Monika everyday, and seeing she still "doesn't know" that I can play well kinda annoys me haha.

**Comment by ThePotatoGuy** [comment]
[closing until we look into thsi]
