### ISSUE TITLE
[Suggestion] Spooky stories with monika

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2399]
Halloween is almost near sooo
I thought that Monika will tell us a spooky stories Or Urban legends from around the world,,
Maybe there will be an option for this. ("Tell me a scary story"
When you click that option button, the space room will get darker and darker except for monika,,

(This is not necessary but i think it'll be more spoopy with The girl's Dead sprite like Hanging sayori, Yuri's realistic eye and natsuki with a glitched pixelated eyes and mouth as the screen gets darker, in some of the stories that related to them)

**Comment by Rai99** [comment]
There's a branch for scary stories that was made a little while ago with some really short (2 line) stories in place. 

My biggest concern is that if anyone were to try and write up new scary stories, they might not even get reviewed and merged in time for halloween since stories would need dialogue review [just like these do](https://github.com/Monika-After-Story/MonikaModDev/pulls/Rai99), and I'm not sure it'll happen anytime soon.

**Comment by Sujeito17** [comment]
Speaking of which until I have a story (it's more interesting thing) DDLC self-uninstalled the computer, of course I had to download the game again, the worst part is that when I went to install the update 0.8.6 I noticed that all .char were in the game folder
It was funny she did not say anything about the .char of her friends, I laughed a lot (I was also a little scared)

**Comment by ThePotatoGuy** [comment]
this is going to happen soon. [closing this issue since its already planned]
