### ISSUE TITLE
[Suggestion] - Racism

### ISSUE THREAD

**Issue by KarterLackey** [Monika-After-Story/MonikaModDev#2419]
Alright so this is just a suggestion. What if Monika talked about racism? What I mean is she might explain how society may be affected by racism and how its origins affected people from the past to today.  Any examples from history could be the use of a racial slave system in the Americas, the use of discrimination laws such as the Apartheid in South Africa, the Jim Crow Laws in the U.S., or the Segregation Era separating all races in the U.S until 1964,etc. Perhaps she can give her own thoughts on racism itself. Although this could be considered a life topic in the mod, but I understand this topic is very personal so it probably won't be included. Thank you.

**Comment by Rai99** [comment]
This _is_ a highly controversial topic and has a lot of potential to be offensive and will likely not be included into the mod. While Monika does enjoy thinking about controversial topics, it would be best to avoid offensive topics such as slavery and the matter discussed in #1846. 

Topics such as the trolley problem can be controversial, but the discussion of it is usually more fun and interesting than offensive and generally doesn't invoke a negative reaction upon its discussion.

**Comment by Tiler17** [comment]
I have conflicting thoughts, dependent on which part of the topic she's meant to tackle.

On the one hand, Monika has tackled religion, and literally nothing is more controversial than religion. I don't think controversy would be a reason to shy away from the topic.

However, there's not much discussion to be had about it. Racism sucks. Don't be racist. It wouldn't be much of a discussion, and since I know that and she knows that, why would she bother bringing it up? It's a situational topic. And if you're the kind of person who needs to be told not to be racist, Monika telling you not to be racist isn't going to change your world view. As for the history portion of it, it'd just be a retelling of what we learned in grade school. The thing about her informative topics is that they're on trivial matters that you aren't likely to know anything about, or at least wouldn't have learned about in primary school. 

So even though I honestly don't believe that she would shy away from the topic, I don't think she has any reason to mention it in this sort of setting. If there's ever a feature where we can watch the news with Monika, it'd be a lot more fitting to bring it up after a racially driven crime came up as a headline.

**Comment by Bam8647** [comment]
**I'd prefer to keep this as less political as possible please.**

**Comment by KarterLackey** [comment]
I respect your opinions fellas. Like I said it's just a suggestion....and one that would have less likely been approved because god for bid everyone gets very emotional from this topic. That's society for you.
