### ISSUE TITLE
Listening

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2426]
It is touched on somewhat when Monika tells us that we are a good listener but she often mentions that she feels like she is rambling so I believe it would be nice to tell her that we like to listen to her.

**Comment by AsuraShun** [comment]
definitely,after all,this mod was made for her happiness,and there's still not enough ways to achieve it

**Comment by CrocWorks** [comment]
I always thought this mod was to make Monika more human, not about her happiness. Happiness is certainly a part of being human, but you can't really have happiness without unhappiness to compare it to.

Whether or not the player likes listening to Monika's rambling should be the player's choice (though I imagine almost everyone would say they don't mind it). Perhaps one option could be that Monika's rambling feels more like a limitation of the mod since there are very limited ways in which the player can provide inputs to Monika and Monika waits for the day when she can interact more freely with the player.

**Comment by SaiPrithvi123** [comment]
This is a fan mod made to extend Monika.

**Comment by AsuraShun** [comment]
I would add a lenny face here but i'm too lazy

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
