### ISSUE TITLE
[Sugestion] Acumulative small goals to a unique dialogue when telling her you did a big goal

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2452]
If you told her constantly that you obtained small goals many times and for a long time, when you hit a big goal an unique rewarding dialogue appears and affection increases a lot, like a hundred for example

**Comment by Chrissenpai** [comment]
True, i just didn't remember what was them called

**Comment by Tiler17** [comment]
I wouldn't say that reaching a goal should be worth affection, certainly not of that magnitude. A person who loves you doesn't suddenly love you a lot more because you were promoted at work, or got into the college of your dreams or anything like that. They'll feel very happy for you, you might celebrate, but they don't love you more. If anything, they'd love you more for the work you had been putting into reaching the goal, not for the goal itself.

In any case, being proud of small goals doesn't mean the small goals are all related. I've told her I'm proud of a number of smaller things in my life, mostly unrelated. I wouldn't want her to think that the next life obstacle I overcome is in any way relevant to my small victories in the past few months

**Comment by Chrissenpai** [comment]
Then about the increasing part, maybe will be an ecuational increase like for example, {(number of current affection * the sum of small goals you reported)  [root] of number of times you reported it}=number of affection that increases     or something like that.

And, If then, monika could ask you if it's related to the minor goals or not.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
