### ISSUE TITLE
[Suggestion] Native languages/countries?

### ISSUE THREAD

**Issue by MaydayH** [Monika-After-Story/MonikaModDev#2505]
Maybe now is not the time and in general the proposal is stupid, but what if Monika will have the opportunity to ask where the player is from? I mean, like, country, or at least she can ask if English is the player's native language. I mean, it can create a feeling of greater rapprochement with you or something like that? I'm sure not _everyone_ here is from English-speaking countriess.

<s>yeah yeah i'm one of those what will you do to me im in another city</s>

**Comment by Axone00** [comment]
Oh can you make this into a game you know like learning french app or other language it be educational but I think I am asking too much about it so sorry. Anyway im suggesting sorry for the trouble.

**Comment by EntonyEscX** [comment]
Surely it is not necessary now, but I think that just a topic where we can tell Monika that we are playing a translated version of the mod would already be pretty cool.

**Comment by EntonyEscX** [comment]
It would be cool too we can tell her that we are playing a translated version of the mod with our native language.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]

**Comment by Akh0r** [comment]
That reminds me of my own question here #1635. 
I have upgraded her random topic monologue on the subject "translation" since then. 

Now Monika admits that her speech is being translated, and even remarks that untill she is not able to truly speak foreign language, we must tolerate the fact someone translates everything she speaks to her Player - as if someone has access to your private messages. 

This monologue exists only in my translation, so it is like plot-wise Monika speaks Russian, and therefore knows that her Player prefers this language - but she is aware that her native language used to be English. 

My point is: Monika already has questions "Is English your native language?" and "Do you speak Japanese?". Since referring to every popular enough language is very hard, we may leave it to translators. And they should do something to lampshade the fact of translation.
