### ISSUE TITLE
sensitive mode

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#2569]
#2566 

a mode that disables sensitive content.

probably would need:
- [x] new event property to define sensitive events
- [x] flag for sensitive mode
- [x] setting for sensitive mode
- [x] art adjustment for sensitive mode
- [x] modify topics that should be adjusted for sensitive mode
- [x] set sensitive property for topics that cannot be modified for sensitive mode
- [x] clean hangman so its appropriate for sensitive mode
- [x] adjust music menu for sensitive mode
- [x] remove easter eggs that were inappropriate for sensitive mode

**Comment by Rai99** [comment]
I actually like the dark humor, so I might not be the very best judge. 

- monika_sayori
  - That hanging pun
- monika_high_school
  - If there's an issue regarding whether or not Monika considers the other dokis _real_
- monika_lastpoem
  - Maybe not tasteless, but it does reference Yuri's suicide
- monika_yuri
  - Making fun of Yuri for being a yandere
  - The last line about asking Yuri
- monika_impression
  - Probably self explanitory
- monika_natsuki
  - Line about not feeling guilty
  - May cause inconsistencies if altered
  - Derandomed, so might not be as urgent
- monika_othergames
  - same as monika_natsuki

**Comment by PC57** [comment]
I don't think it has to go so far as changing the name of the hangman game - that actually comes off as a little spiteful if I'm being honest - or even getting rid of the Sayori and Natsuki player name Easter eggs since you have to intentionally go out of your way to see them.

Some of the topics could be altered a bit if the player started mas  after act4 but that's more of a character consistency issue than sensitivity. Monika already asks if you're comfortable hearing about Sayori dying and that's really the only, for lack of a better word, triggering topic.

Honestly the only thing I would want would be a way to opt out of having dead Sayoris hanging from Christmas trees or party balloons and other decorations. I get that they're jokes but once you notice them it's impossible to unsee them and kinda sours the mood of what's supposed to be happy events with Monika.

**Comment by ThePotatoGuy** [comment]
>changing the name of hangman

Hangman was added solely because it references sayori. this mode basically gets rid of all hanging references.

>sayori / natsuki / yuri player name easter eggs

all of these are pretty disturbing or can trigger people, disabling them is the safest option for this mode.


And I think you're misunderstanding, we're not taking all of these things out of the mod, we're only adding a opt-in mode that disables this content.

**Comment by ThePotatoGuy** [comment]
closed as R  E M  O  V  E  D!!!
