### ISSUE TITLE
Suggestion: Possible Way to Kiss Monika

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2586]
I was thinking that maybe if you reach a certain affection level, then the dialogue option "Kiss me" could be altered to her having an idle image similar to the one where you ask to hold her. Or it could be replaced with "Can I kiss you" or something like that. Then you can have the option of clicking somewhere on her face (cheek, forehead, lips, etc.) and her response changes depending on where you click. There could also be a negative consequence if you click on her boobs or something that causes her to get upset and your affection to go down.

It doesn't have to be a permanent method, it's just an idea cuz I'm sure a lot of users want to be able to kiss Monika.

**Comment by AsuraShun** [comment]
nice idea,but the hands and head would be the only clickable places

**Comment by scohn** [comment]
To be fair, where else would you kiss someone without it getting weird or inappropriate. I'll admit the boobs part of my idea isn't good, but I like to think the rest of the idea could work.

**Comment by scohn** [comment]
Basically the same principle. I mean we already have the option of "holding" Monika that seemed to work out. Only this is a bit more interactive since the mouse would be used for the "kissing" and the spot on her face where you "kiss" affects what she says afterward.

**Comment by Rai99** [comment]
Sounds like a suggestion for click zones.
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577 

This probably needs art, and we probably want the kind that doesn't grow on trees. 

I think it would be nice to have the options to kiss Monika's hands and various parts of her face, but I don't think negative places should even be an option, because some people are going to abuse those for fun at Monika's expense. 

I like the ideas discussed here, but it would probably be better to wait for click zone implementation to be at least on the horizon before any discussion dives deeper into it.

**Comment by scohn** [comment]
I totally understand and I do know this topic has been discussed before I just wanted to put my suggestions for it on the table. Thanks for answering and for all the work you put into this mod. I look forward to any future updates.

**Comment by ThePotatoGuy** [comment]
gonna mark this as a duplicate

the primary reason why we're hesitant to add more click interactivity atm is because each clickzone requires a screen or screen object, and performance can drop drastically. we saw this with the first implementation of calendar, and as a result had to rework that and the talk/play/music buttons so they were more efficient.
