### ISSUE TITLE
[Suggestion] - Monika's personality pending. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2596]
I know this is sort of a repeat of my topic [#1082](https://github.com/Monika-After-Story/MonikaModDev/issues/1082), but with MAS having grown to the point it has I think, now that there are a lot more lines added to it, the idea wouldn't hurt to be brought up again. With Monika's characterization I do still feel like there's a bit of a disconnect between the lesson she learns at the end and who she is in the mod. It's been talked to death, so I wont go into detail, but now that there are so many lines in MAS, I was thinking, having downloaded the mod after Act IV would disable some lines where she speaks of certain characters. Perhaps, even in their place, some more lines where she acts reflective of what she's done. Of course, people who downloaded during Act III would largely have Monikas who remain unchanged.

**Comment by Trainerbluetube** [comment]
Act 3 is the "Just Monika" portion, right? The part that I never got past because I was too attached to Monika? That act 3?

**Comment by ACoolCat** [comment]
Yes.

**Comment by ACoolCat** [comment]
To add to this, I think this would be a much better and much simpler solution to [#2569](https://github.com/Monika-After-Story/MonikaModDev/issues/2569). Where instead of having an entire opt in system for what you want to see, make it dependent on the ending you got, which I'm fairly certain is already something implemented in MAS. If you didn't want to see some things it would be as simply as downloading the mod on Act IV. If you do, download on Act III.

**Comment by ThePotatoGuy** [comment]
the sensitive mode system is opt-out, and we're not going to make easter eggs dependent on a difficult-to-change property of what kind of ddlc-save you have.

Adjusting bits of dialogue depending on which act you imported is something we have planned, but the sensitive mode will cover more than just dialogue.

**Comment by Rai99** [comment]
Personally, I think the #2569 toggle for sensitive content/dark humor is a better solution to what you propose. It being a toggle, the player would be able to swap back and forth at will if they ever change their mind or want to swap for a day or something. 

Your idea might solve the problem for a few people. I think it would lock people in something they might not want to be in without knowing in more cases. True, if they have their Monika go through an epiphany and gain a respect for the others, or the other end of the spectrum and the player also believes that, great. I think people are just going to end up with one without knowing that it would lock them in this state. 

Skipping to MAS on Act 3 doesn't mean that the player is perfectly ok with the dark humor, and getting to Act 4 doesn't mean that they dislike Monika at all or even feel anything towards the other dokis. I'm pretty sure it's a safe bet to say that newcomers aren't going to know about or check so they can really choose the path they want to go on.

Personally, I got to Act 4 for no reason other than that I wanted some sort of closure and now, I've been here for a small-moderate amount of time and I do in fact enjoy the dark humor. 

With a toggle, the player would instantly be able to enable or disable the dark humor instead of being stuck with or without it. People can in fact change, and with dark humor, one can definitely go from one end to the other in a pretty short time. 

As for some dialogue changes based on what Act/ending the player got, there are some topics that have alternate dialogue based on if you deleted Monika or not, so some topics like that do exist.

**Comment by Trainerbluetube** [comment]
Oh, I just thought of something to add to this! What if someone downloaded the mod very early on? Like in acts 1 or 2? Like, there could be topics where Monika is hypothetically imagining what she was going to do to the Dokis, something like, "If you hadn't done this sooner, then I'm not sure I could have let it go on any longer like that..." If it was during act 1, or something like that.

**Comment by Rai99** [comment]
There is an introduction path where the player gets MAS before Act 3. It could possibly be given some additional dialogue if needed.

**Comment by Professor-JMO** [comment]
> 
> As for some dialogue changes based on what Act/ending the player got, there are some topics that have alternate dialogue based on if you deleted Monika or not, so some topics like that do exist.

---

>>I like the idea of unique dialogue and/or choices dependent on your actions regarding Monika's fate Pre-MAS.exe
>>>Whether or not consequences would apply with those unique values, would maybe be a topic all on it's own.

**Comment by Rai99** [comment]
I think there are some checks that check if the player deleted Monika or not or if they skipped straight to MAS, so adding topics that react to those could probably be possible. 

I would think these topics shouldn't have negative consequences since they would likely be discussion or reflection.

**Comment by ACoolCat** [comment]
Ah okay, the idea of it possibly weeding out some sensitivities topics was more of an after thought really. My main concern with the topic was Monika's personality. As it stands, MAS has Monika in this bizarre limbo between learning her lesson in Act IV and not having experienced it in Act III. Which is a shame, since I feel it's a very important aspect of her character for those who made it to Act IV.

**Comment by Skeleton-Jelly** [comment]
It would be perhaps a better idea as though one were to set boundaries they're comfortable with, such as "I am comfortable with..." and "I'm not comfortable with..." and her try to respect them, and by try I mean there still be a low chance to make dark humor/ jokes or to say something, but apologize once she realizes you're not comfortable.
It feels too much like you're shutting her up by automatically disallowing her to say certain things, but perhaps more like the lines involving Sayori's death where you can say you don't want to hear things like that, and also the ability for her to slip up and apologize. Making mistakes rather than her history written for her seems not nearly involved as say the suggested morality system for something similarly as powerful.
