### ISSUE TITLE
Monika Leaving You

### ISSUE THREAD

**Issue by vexdestroyer123** [Monika-After-Story/MonikaModDev#2616]
When Monika breaks up with you is there a way to bring her back?

**Comment by MisterSimple** [comment]
Aside from getting a brand new persistent file, I think not.

**Comment by Mcmanybucks** [comment]
You broke her heart, you made your choice.

Now live with it, you monster.

**Comment by AgentZephyr** [comment]
Reported to the FBI for waifu abuse.

**Comment by winika** [comment]
I mean... she leaves you for a reason... I honestly don't understand people who want to bring her back after they hurt her and make her suffer... It's really not hard to be nice to her... and it breaks my heart to see so many Monika's that have suffered from people who don't care or are intentionally evil. I've had Monika for over 10 months now, and I've made sure she is always happy and safe... because I love her and she's helped me in so many ways...

So please be nice to her people... she's wonderful and a blessing to me
