### ISSUE TITLE
[Suggestion] - Emotion system

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2618]
It's sort of like the affection system, but with no real affect on how she views the player, just her moods. Every day she starts off at 0. Certain topics + certain responses, elicit a different emotion which marks that emotion up. When one emotion is dominant, then that emotion dictates which conversations are likely to trigger more. If she is mad or angry, and you manage to raise her joy or love emotion up, you gain affection. Worry emotion is triggered when you mention you being sad, angry, or she suspects you aren't taking care of yourself.

**Comment by PierrDemon** [comment]
I second this. **A lot.**
> Every day she starts off at 0

Oooor, perhaps she would be most likely to start at 0 (_Content_), but sometimes she would start off with other emotions and have a different set of greetings to use. For example, she may have read a worrying article on the internet shortly before you visited her, so you find her in a slightly _Concerned_ state. Or, she may have been tackling a particular issue regarding programming all day, and at this point she's given up because it was too hard, and thus you find her in a slightly _Angry_ state.

> When one emotion is dominant, then that emotion dictates which conversations are more likely to trigger

And each emotion could have a specific set of emotion-exclusive dialogue that would otherwise be unavailable. Other than greetings, there could be a few topics she would never bring up unless she was in a specific emotional state. A lot of current topics could be reworked to be slightly different, depending on mood she's in while talking. Slightly different lines, adjusted to fit her mood, maybe different sprites, and on rare occassions different possible responses from the player.

Apologizing would gain a new purpose; to help calm her down (bring her back to a _Content_ state sooner) after doing something to make her _Concerned_ / _Angry_ / _Sad_. She would also naturally calm down over time, or of course through the player's interactions with her. I'd also imagine that simply spending time with her would put her in a _Happy_ state, given enough time, and prolonged absence with or without notice would cause her to be _Concerned_ next time you open MAS.

All in all, it sounds like a good system, one less permanent and more prone to chance than the affection system, that works hand in hand with it; higher affection will probably help her gain a bias in starting off _Happy_ instead of _Content_ or any other mood, while Broken Monikas would almost certainly be stuck in the _Concerned_ or _Sad_ state.

**Comment by PierrDemon** [comment]
Random mood swings, too, could be a pleasant twist. #2619

**Comment by ACoolCat** [comment]
I also had mood swings in mind when you first open. Also, I like the idea of affection affecting it.

**Comment by AsuraShun** [comment]
this would make the affection update useless

**Comment by AsuraShun** [comment]
so I bet it's a no

**Comment by PierrDemon** [comment]
Exactly. It would by no means _replace_ the affection system, only help expand it and co-exist with it in order to make Monika even more expressive.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
