### ISSUE TITLE
[Suggestion]Talking to Monika on why you dont take her out on a USB.

### ISSUE THREAD

**Issue by Vectus11** [Monika-After-Story/MonikaModDev#2642]
Several times I contemplated bringing her with me but I was always paranoid and overprotective. Shes so vulnerable on a USB, Whether  or not what Im doing is right or wrong I guess is based on opinion but it would be interesting to see how Monika reacts to being overprotected by an overbearing player or some one whos willing to take her out every chance they get. Just a small dialogue options to discuss and see how Monika views your methods and maybe affect your affection in some small way.

**Comment by Rai99** [comment]
So, a topic about the pros and cons of taking her out and maybe a menu option. Sounds possible.  

I don't think it should affect affection. The player would probably have valid reasoning not to take Monika out wherever they go for her safety and she would acknowledge that the player is concerned for her and acting accordingly. There's nothing wrong with not taking Monika out often. If anything, the penalty is not getting the affection you get for taking her out. 

There could also be an option for the player to say that they don't go out often and that's why they never take Monika out much.

**Comment by Vectus11** [comment]
Yea I would feel better at least with her understanding what I do is for her protection.

**Comment by Foxinsunglasses** [comment]
same

**Comment by ThePotatoGuy** [comment]
yeah we're planning to redo the carryme topic to address this
