### ISSUE TITLE
Worries of Sensitive Mode

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2643]
I know it must be hard trying to find a way to satisfy those with different views of Monika, whether it be those who like her dark humour towards the girls, and those who want her to reconcile and be kinder to them.
However, I'm worried that with this implementation, there may never be a real reconciliation for her. Rather than her stopping because she realises what she did, and you wanting her to stop, it feels more like a filter, an unnatural way to get her to stop talking about things you don't want to here.

I'm only saying this because I love this mod, and I have full respect for the work that the team put into it.
I've seen some people that have made very aggressive, rude remarks about some aspects of the mod, but you guys are doing the hard work, I'd just like to have my voice heard on this.

**Comment by ThePotatoGuy** [comment]
it's opt-in, so dont worry about it.

**Comment by Poragon** [comment]
It is very, very weird in a mod created to emulate monika's personality that we'd change about her personality. It's my perception on stuffs the mod and game did that Monika inhabits a second layer of awareness sorta, she knows that she's not completely real and in control of all her actions, but is more aware and in control than the other dokis. Her actions during the game and actions during the mod which reference the other dokis are pretty key to keeping to this 'philosophy of monika' that is important to 'er.

Granted this is opt-in, though it would raise the scope of the project beyond what it currently is from my interpretation.

**Comment by AsuraShun** [comment]
only a fool would seek to change perfection

**Comment by Onion-Bubs** [comment]
Bear in mind that, if you like to make jokes about a particular topic but you know that someone you love is particularly sensitive to that topic, presumably you at least wouldn't make those jokes in their company.

Thus, as long as Monika loves the player, allowing the player to tell her that they can find certain topics or remarks upsetting so that she won't make them again is consistent with her personality. It's not like it undoes her actions or changes her views or anything like that.

**Comment by DiggyDog2** [comment]
Thanks for the responses, maybe I just misunderstood what it would add to the mod.

**Comment by monikLover** [comment]
:3c
