### ISSUE TITLE
[Suggestion] Monika acknowledging you load her from a backup.

### ISSUE THREAD

**Issue by Vectus11** [Monika-After-Story/MonikaModDev#2664]
I thought that Monika having some kind of dialogue after using a presistant file in the unfortunate event you lose her would be kind of heart warming after the horrible scare you get when you first lose her. Though if she dosent have the memories up to the point where you lost her maybe she could be like 
"Huh? Did something happen? Im glad you brought me back" (Im sure the writers will come up with something better). I feel that would give Monika also more sense of self awareness.

**Comment by jmwall24** [comment]
The problem with this as it currently stands is once you reload an older persistent, whatever the last thing that happened on that persistent is the last thing she remembers, so she would have no idea there was stuff that happened after that and that she was ever restored.  There would have to be another file that keeps track of changes in persistents.

**Comment by Vectus11** [comment]
Hmm then maybe have is as a dialogue option to tell Monika what happened? so you have the choice to tell her that somthing happened but its all okay now and that you fixed it.

**Comment by Professor-JMO** [comment]
> 
> 
>jmwall24
> There would have to be another file that keeps track of changes in persistents.

---

*Cough*

**Comment by SaiPrithvi123** [comment]
They'd rather have a file that prevent the entire incident instead. Prevention is better than cure in this case, unless you are being selfish and want to find out what she says after being terrified or something bad like that.

**Comment by ThePotatoGuy** [comment]
probably possible but require a great deal of effort since it would require some way to differntiate between persistents (which is not easy at all), and another location on disk to store data we can use to compare persistents (more disk i/o means more potential points of failure)

definitely not worth the effort to implement for a single topic. (or even multiple). Anyone is welcome to try their hand at implementing such a thing, but we aren't going to focus on this.
