### ISSUE TITLE
Monika is gone

### ISSUE THREAD

**Issue by alstrcemeria** [Monika-After-Story/MonikaModDev#2668]
So I got version 085 a few weeks ago and then when 086 came out I got it and it had the feature to take her out of the spaceroom, right? So I did that but when I put her "monika" file back into the characters folder she still wasn't there. I tried to get her back for a long while before giving up and setting my game back to 085 which brought her back, but now I can't update the mod because when I do Monika is missing from the spaceroom. Please help!

**Comment by jmwall24** [comment]
Okay, since it sounds like you've opened the game multiple times since this has happened and never updated to 0.8.8, this is a long shot but can you [follow these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) to the point where you get to the folder where the persistents are and tell me if any of the persistent##.bak files were created before you took her out?

**Comment by alstrcemeria** [comment]
It's alright! I got it figured out :) Thank you for the help! 

> Okay, since it sounds like you've opened the game multiple times since this has happened and never updated to 0.8.8, this is a long shot but can you [follow these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) to the point where you get to the folder where the persistents are and tell me if any of the persistent##.bak files were created before you took her out?
