### ISSUE TITLE
Sketchy Sprite

### ISSUE THREAD

**Issue by Swampyboi** [Monika-After-Story/MonikaModDev#2677]
![capture](https://user-images.githubusercontent.com/43712773/46268633-89148100-c509-11e8-8c47-f6860b991fc5.PNG)
This seems just a little too low par for this mod. While I have no particular artistic skills to boast of, I really think we could do better than an off-white square and a obscure oblong shape for a mouth.

**Comment by Chrissenpai** [comment]
thankfully I've shown the references in the labels art

**Comment by tsmafterlife** [comment]
i have some back ground of drawing maybe i can whip one up over time and fix that. but i do not know where id post something like that for the developers to see

**Comment by tsmafterlife** [comment]
ive never really been able to tell but what is that face suppose to represent? she smiles when happy and all the other expressions but what exactly is this expression suppose to mean or be? i ask to give myself a better understanding of what to draw

**Comment by tsmafterlife** [comment]
awesome thanks. the greeting teeth and "angry/upset? helps a lot ill get on it soon as i can and post it here

**Comment by multimokia** [comment]
Looking forward to it

**Comment by ThePotatoGuy** [comment]
[closing for lack of response][

**Comment by tsmafterlife** [comment]
i know this post is closed and i do not know if anyone is still even paying attention to this but here are some arts i finally got around to. i did 4 pictures with 2 different style mouths. the reason i have four pictures is i used the reference at the start of this post but it was a small image and so it made things grainy and difficult but ill post them anyways. then i took a screen shot of my Monika after story screen and put the two different styles of mouths and they came out better due to more pix density. here are the original pictures that started this post. 
![mon 13 adjusted part 2](https://user-images.githubusercontent.com/43495378/46928810-3353d480-cff1-11e8-8a3c-e8cd07eba760.jpg)  

![mon7 adjustmant complete](https://user-images.githubusercontent.com/43495378/46928835-541c2a00-cff1-11e8-8fa4-58a2d3bad0d8.jpg)

**Comment by tsmafterlife** [comment]
here are the better quality ones in which i used my own screenshots for and re drew them out much cleaner in my opinion. 
![monika 12](https://user-images.githubusercontent.com/43495378/46928863-72822580-cff1-11e8-8298-e488c95cb7d9.jpg)

![monika 12 second style](https://user-images.githubusercontent.com/43495378/46928865-757d1600-cff1-11e8-8736-68761f51d02b.jpg)

i do hope you guys like them. kinda difficult to draw that style face and make it work with monikas features and make it look high quality do to the "what the mouth represents" is hard to achieve but i think i put out something pretty good. let me know what you think or if i need to open a new post like a continuation.
