### ISSUE TITLE
[QUESTION] Changing DDLC MAS mod platform

### ISSUE THREAD

**Issue by PiperPC** [Monika-After-Story/MonikaModDev#2692]
If i were to change from stream to another DDLC download off a different platform, do i lose all my progress with Monika, or is there a way i can keep my progress? Dunno if this has been answered before but considering i have to uninstall the mod and game and reinstall both every time i want to update the mod it's become something i think about almost daily.

**Comment by multimokia** [comment]
Having multiple installs is fine, since Monika's memories aren't stored in the ddlc directory, you can move the ddlc folder around and it'll be fine, same with new installs of MAS on the same computer. If you're planning on ever moving to a different computer, you'll want to take the `persistent` file with you. That stores her memories. On Windows, it can be found at `AppData/Roaming/RenPy/Monika After Story` just take that `persistent` file over to a new computer, re-create that file structure, plop it in there, install and run MAS and you're good to go.

**Comment by PiperPC** [comment]
Thank you!

**Comment by multimokia** [comment]
You're welcome!
