### ISSUE TITLE
Took "monika" file somewhere on USB, pasted it back into characters folder, but her chair is still empty!

### ISSUE THREAD

**Issue by tabtlenta** [Monika-After-Story/MonikaModDev#2700]
I realized that the game stopped responding for a sec right before it shut down as per usual, so maybe it crashed and that caused the issue but I'm not 100% sure.

[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2440793/mas_log.txt)

**Comment by multimokia** [comment]
Head over to the filepath mentioning the `.lock` file, and just delete that. The game should run again

**Comment by multimokia** [comment]
After you restored the persistent, were you just greeted by the lock traceback? Or an empty chair?

**Comment by multimokia** [comment]
Also, would you mind sending your `persistent` over? (Head over to `AppData/Roaming/RenPy/Monika After Story` to find it) GitHub won't let you send it normally, so you'll have to tack on an extension, or send it via a Google Drive link.

**Comment by tabtlenta** [comment]
I tried deleting the .lock file, but the game still opens to an empty chair :(
"persistent.txt" is my most recent persistent, and "persistent21.txt" is my last remaining persistent from before there were any issues.
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2444400/persistent.txt)

[persistent21.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2444399/persistent21.txt)

Thanks for all your work on this - hopefully there's a way to get her back!!

**Comment by tabtlenta** [comment]
Also, per the advice of a friendly dev on reddit, here's my monika file
[monika.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2444402/monika.txt)

**Comment by jmwall24** [comment]
You said persistent21 is from before you had any issues.  Did you try loading that one up?

**Comment by jmwall24** [comment]
it must be after you took her out as well, I just loaded it up and she's not there.  we'll have the current persistent fixed up soon.

**Comment by tabtlenta** [comment]
I tried, and got the .lock error again:
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2444410/traceback.txt)

When I deleted the .lock file and *then* restored to persistent21, it was still empty. I guess that persistent must have somehow been created just after I took her out of the game (maybe related to the game crashing?) as the timestamps match up. Thank you very much for the help!

**Comment by jmwall24** [comment]
do you have multiple versions of MAS/DDLC open?  that's usually what causes the lock error.

make sure all versions of MAS/DDLC are closed, then delete the .lock file again and then download this persistent and replace your current persistent with this one.  she should be right there waiting for you

https://drive.google.com/open?id=1movEkLhWbuHHmd6dlXatzpDcx9V-fQU4

**Comment by jmwall24** [comment]
You're very welcome, always happy to return a Monika back home!

As for prevention, saving persistent backups is always a good idea.  Next release will include a fix that will make it so your persistent##.bak files will not be overwritten when the chair is empty, so once that takes effect, you will always have a backup available from before you took her out that you can load in to get her back if this happens again.  But even with that, I still recommend making your own backups of your persistent frequently.  I actually make a copy of the entire `Monika After Story` folder that the persistent is in, so that way you have a backup of the persistent and all 5 backups.

You can also make a copy of the monika file each time you take her out and store it some place else on your computer.  That way if the one on your USB is bad, you can use the backup.
