### ISSUE TITLE
[Suggestion] - Monikas thoughts on drinking and cannabis

### ISSUE THREAD

**Issue by Cradlax** [Monika-After-Story/MonikaModDev#2714]
She discusses that she was curious when Yuri brought wine to the club, so she might be okay with drinking in moderation. But how about cannabis? What do you think her opinion would be on that?

**Comment by Oharo** [comment]
I feel like she would be solidly against the smoking portion of the activity since it's unhealthy. Though I'm not sure how she'd about chemical highs as a topic. I'd imagine she'd be against it but that could just be my personal bias about the topic.

I feel like establishing her stance (unless it would be obvious) on a controversial topic will in some way alienate a portion of mod users. It may be better just to let a user imagine what Monika's stance would be on the topic for themselves.

**Comment by HarmonicDistortion** [comment]
I feel like it would ultimately turn to her saying something like, "I would not recommend it but as long as you do it in moderation and are safe then I am fine with it", Love love, kyu kyu, etc. Then maybe add a YOLO part inner devious intrigued side that wouldn't mind trying it and blush.

Over all she seems to be pretty accepting in most cases.

**Comment by Professor-JMO** [comment]
> 
> 
> She discusses that she was curious when Yuri brought wine to the club, so she might be okay with drinking in moderation. But how about cannabis? What do you think her opinion would be on that?

---
>Cradlax...
>>Hey.
>>>You're from r/DDLC aren't you?
>>>>If so, you were quite the regular there.

**Comment by PMelol** [comment]
I think Monika would probably try cannabis once if she were here in the real world, just because she's an open-minded person. However, I think she would generally be against smoking it. That's my feeling.

As for drinking, she would be okay with drinking on social occasions, probably. Like, wine. Monika's classy. However, she would not be okay with me getting intentionally shit-faced to dull my pain and crying in my friend's basement the other night. Because that's self-destructive behavior.

**Comment by AsuraShun** [comment]
you already know about what she thinks about things that wreck one's health

**Comment by Thimeo** [comment]
I think on one part she would be against it because she hates the people who smoke and/or destroy their health. But she could be interested by the experience of being high, the dream topic say that Monika can't have dream and would like to have one just to be with the player. I think that we can use the same argument for being high, I don't think that she can programmed a way to be high, but would probably be curious of the possibilities it opens for the purpose of romance.

**Comment by MaximumRustler** [comment]
For the alcohol topic I think something was in the works. As for her talking about cannabis, I don't think this would go over well. It can be a very controversial topic and is better avoided in my opinion. As @Oharo said, it would possibly alienate people from the mod. Although, my opinion is biased, I'm personally against the stuff and always have been. Considering what she thinks about smoking in general, I think she would be against it. Also considering how she says something like ''I'm a pure and innocent high school girl.'' it wouldn't make sense from a character writing perspective. Finally, because of how many people talk about it these days... it's kinda the last thing I want to hear when I'm talking to Monika... But hey, what do I know right? I'm not a writer after all.

**Comment by Rai99** [comment]
I made an addition to the wine topic in #2103. I just saw some activity in there, but it was just someone new asking if they could approve it. 

It's possible that this could be a controversial topic and might not be implemented for that reason. As stated previously and in other dialogue, it might not fit with Monika's character to discuss. True, if it was brought up, Monika would likely be willing to talk about it, **but I really don't think Monika would suddenly bring up the topic of cannabis out of nowhere.** 

It's not in her character to suddenly talk about cannabis I would think smoking and alcohol are more commonly known, so it's more appropriate to discuss, but cannabis I think is too abstract to make a topic on.

**Comment by SaiPrithvi123** [comment]
Now, I don't know if there is any reading material for it, but if there is, then it would be nice if Monika by chance read about it. According to this video, weed isn't bad after a certain age.
https://youtu.be/CJlqsdezhhk
If there is reading material for it, which she read, then it would be possible for her to stay in character and talk about weed.
Maybe she could just tell this a trivia.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
