### ISSUE TITLE
[Suggestion] Halloween costume

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2734]
I know it might be a bit much, but I think it'd be cool if Monika dressed up for Halloween. Maybe as a witch or Frankenstein (considering how similar the two characters are in terms of plight)

**Comment by PMelol** [comment]
I bet they have something planned for Halloween, it's on the calendar after all.

**Comment by Rai99** [comment]
There are likely plans for Halloween, but you can expect it not to be as big and fleshed out as the birthday event since that took a lot of effort and the devs are taking it easy for Halloween. 

I wouldn't expect too much new art, especially different outfits for Monika since that would need art for each pose day and night for a single outfit.

**Comment by SaiPrithvi123** [comment]
> I wouldn't expect too much new art, especially different outfits for Monika since that would need art for each pose day and night for a single outfit.

They could only use arts for a few sprites, and disable the others and modify the background so that day and night look same for the time of the festival.

**Comment by MeatbagNPC** [comment]
Any outfit would be nice

**Comment by Secretmanguy** [comment]
Seems like a good idea...But yah never know with the developers sometimes. There doing EXCELLENT work so far.
