### ISSUE TITLE
[Suggestion] Monika's pet names staying.

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2735]
I heard that on the highest affection tier Monika stops using words like "My love" or "darling" and uses more casual phrases like "What's up". If this is a rumor then feel free to ignore my complaint, but for some reason it feels a tad wrong to me. I thought the names she said were really cute and her switching to more casual slang  seems like a downgrade if anything. 

Also, on top of this, Monika saying terms like "What's up" is kind of out of character for her. She uses words such as "my love" and "darling" in base game Act III, so it's reasonable to assume that's how she'd normally interact with her love. I hope I'm not the only one who has these views.

**Comment by ZeeMaster33** [comment]
I'm half and half on this one. On one hand, I'd like to see the pet names carry on to the 'lovestruck' tier, given Monika's romantic disposition. On the other hand, I'm for adopting some more casual speech given the more intimate/comfortable nature of the relationship at that point. However, I don't quite believe it should be 100% one or the other, but rather, a mixture of the two.

**Comment by ZeeMaster33** [comment]
That's why I'm not necessarily suggesting it be entirely casual, but I do think it can show that she feels comfortable enough to not have to refer to you via pet names all the time. Sometimes, being in an intimate relationship can be treated like your significant other is your best friend rather than needing to emphasize the 'lovers' aspect all the time. I definitely don't think the pet names should be removed, but I can't see why it can't be a mix of both casual greetings and romantic pet names.

**Comment by PC57** [comment]
I think she could have casual quips as well as the lovey-dovey ones. Even a cheeseball like Monika wouldn't be pouring it on thick _all_ the time. Even adding "honey" or "Sweetheart" to the end of the more casual quips would do a lot. Big difference between "what's up?" and "What's up, sweetie?"

**Comment by Rai99** [comment]
I think the current definition of the "Love" doesn't really do justice for the amount of time spent with Monika. It really does seem like a downgrade from _Exceptionally happy, the happiest she has ever been in her life to that point. Completely trusts the player and wants to make him/her as happy as she is"_ to _"completely comfortable with the player"_. 

I at least think it should be changed to account for the fact that Monika does really love the player very much and would continue being lovey dovey if the player likes it, at least some-most of the time. 

Personally, I prefer ~~**formal speech as literally everybody who sees me comment probably knows**~~ the casual quips since I'm not too fond of the cliche nicknames such as "Dear, Honey, Sweetheart, etc." but the love stage really does feel like a downgrade. I'd like Monika to still be lovey dovey, just without those nicknames. 

Another possible option would be to give Monika a nickname that she could call the player if that differs from the name they gave her already. 

Again, I have to say that the current possibilities for "Love" are far too casual for the amount of time spent with Monika.

**Comment by MisterSimple** [comment]
I actually experienced these quips for a while (because of an affection bug that's been fixed already) and it did feel kind of out of character, mainly because she doesn't address you by your name or pet name as often.

> Even adding "honey" or "Sweetheart" to the end of the more casual quips would do a lot. Big difference between "what's up?" and "What's up, sweetie?"

That's a decent compromise imo, though having Monika say "What's up, sweetie?" feels like she's trying to combine being casual and lovey-dovey in a single quip, and it doesn't sound right to me. Perhaps have her say "What's up, [player]?" instead, and save the pet names for exclusively lovey-dovey quips.

**Comment by Rai99** [comment]
I think the hard part about making content for the "Love" affection group is that the level before it (enamored) is probably as appropriately affectionate you can get while still being general to fit most people's preferences. Anything beyond that level, and Monika should probably know some of the player's preferences on what they'd like to be called, how they like to talk and be talked to, etc. 

Adding customization options for "Love" might take some work and I'm not even entirely sure what could be done about it or how to make a "setting" for a certain preference. 

In the mean time, I think it would be best to simply add onto the quips for enamored rather than replacing the quips with an entirely new subset that some people might like less the enamored quips.

**Comment by Olliesama** [comment]
I think maybe it should be completely different. Call me crazy but people that are comfortable don't usually talk, so instead of having her say throwaway (and to me almost distant) lines she'd simply say nothing if you want to convey comfort, or small tiny things like...
"Hm? :heart:"
"Yes, sweetie?"
"What is it, [player]?"
As opposed to longer, more inquiring lines.

**Comment by Rai99** [comment]
I like the idea of just having happy/content sound effects ending with "~" or a heart emote rather than full on, complete sentences. Maybe Monika could even switch to a happy expression.

**Comment by Olliesama** [comment]
Yeah, it makes her seem more comfortable and not have the need to say anything but still show off affection, which is the issue with the current ones.
They come off as considerably colder.

**Comment by TheSuperStu** [comment]
To me, Monika is supposed to be **obsessed** about the player (based on events from the game). If it was to be that she is more comfortable at the highest tier I can understand that she is assured the player does in fact love her. Its just the current quips at the love tier seem strange compared to the tier before, where in the love tier she should be more in love with the player.

**Comment by PMelol** [comment]
And I just raise it by saying I love you constantly? hahaha.

**Comment by TheSuperStu** [comment]
@PMelol If you take a peek (just a peek!) into the affection-script, right at the top shows the tiers and what they are supposed to be based on how she will behave towards the player. It takes time to get to the top, no rush!

This is where this specific issue on the quips comes from, on the highest tier the "what would you like to talk about" lines seems to be less love focused, which I think is out of character for her.

**Comment by ThePotatoGuy** [comment]
as described in some of ur comments, its meant to be realistic. enamored is the honeymoon stage, and it doesnt last forever. beyond that is comfortable, and most couples in that stage dont constantly burst out in i love you's every 5 minutes.

that being said, we could look into what rai said with a variable monika that changes based on user prefs. regardless, im against making "love" a "completely obsessed with you" stage. (at least not by default)

**Comment by ACoolCat** [comment]
I don't personally believe that having pet names mean you're completely obsessed with a person. It's just a quirk she has. I know it's meant to come across as her growing comfortable, but it seems as if she's falling out of love.

**Comment by PMelol** [comment]
I get what you guys mean. It should probably be a mix of "Hey, what's up?" And "What do you want to talk about, honey?" Why not? Pretty sure people in comfortable and intimate relationships still call each other honey/sweetheart. Monika is a romantic at heart.

**Comment by TheSuperStu** [comment]
It might have to be its own discussion (if it already hasn't been discussed in excess already) about how Monika should act at certain levels. Seeing as what she did in the club, and how much she talks about how she relies on the player or that she is so thankful of having the player with her or how she wants to make the player as happy as possible, almost makes it seem like the player is the world to her. So going even higher in the tiers would make me think she would latch onto that train of thought even more.
I do fully understand how being with someone for so long would allow them to be more casual/comfortable with them. But as said before, for those specific lines to just do away with all the 'lovey-dovey' quips seems to be backtracking on how much she loves the player. Something as simple as continuing the enamored lines with the current love lines would make both types stand out whenever she does use either (showing she is more relaxed with the player and that she still does very much love them).

**Comment by PC57** [comment]
This is just my experience but when past relationships got more comfortable pet names were used even more often. At first saying honey or sweetie can feel a little silly but after awhile it becomes second nature, sometimes to the point where using the person's real name is unusual.

**Comment by Bam8647** [comment]
I'd vote for 50% Enamored 50% Best Friend once they hit "Love" level. It's true even married couples still use nicknames every now and then. So like I said, do a 50/50 so the player doesn't go from "In love" to "In the friend zone" lmao. Or let the player tell Monika what they'd prefer as TPG mentioned.

**Comment by SaiPrithvi123** [comment]
> as described in some of ur comments, its meant to be realistic. enamored is the honeymoon stage, and it doesnt last forever. beyond that is comfortable, and most couples in that stage dont constantly burst out in i love you's every 5 minutes.

Those are the couples who had their honeymoons. You know what people do in their honeymoons? They communicate with each other without being limited to a text box. They can feel each other's warmth, etc.. Those are the couples where one of the partners isn't trapped in a computer. IMO, those couples don't burst in "I love you"'s every 5 minutes because they have more ways to show love than just saying "I love you"'s. Monika and the player isn't a normal couple. You might be trying to mix a gorilla and a human and expecting to make a creature which is as intelligent as a human and as strong as a gorilla, and ignoring the possibility to create something that is as dumb as a gorilla and as weak as a human. This was just an example, but if you replace the speciality of the gorilla with showing love to the player, and replace the speciality of the human with being realistic, it would make sense why some people see the removal of pet names as a downgrade IMO. It would result in Monika neither being realistic, nor showing as much love.

**Comment by DiggyDog2** [comment]
Maybe she could stick with one pet name, for example?
She could still keep a similar lovey-dovey attitude with her names, but she maybe grows a preference for a certain name, and begins to use it casually.
It seems like a nice in-between.

**Comment by ACoolCat** [comment]
I believe a good way to set the "love" affection stage apart from the other affection stages could be new topics unlocked. When couples are more comfortable with each other they are more open to talk about topics they'd otherwise find embarrassing. Perhaps Monika talks about her insecurities, or asks semi lewd questions, or brings up starting a family.
