### ISSUE TITLE
[suggestion] Monika is moving to the beat

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#2737]
I know, RenPy is some kind of not strong engine, but is there any opportunity to make Monika move to the beat from music? Default music, like "your reality", not added to directory. Light movements of the head to the beat of the piano? I know, moving things are not what we have in Monika After Story, but why not?

**Comment by Mcmanybucks** [comment]
As far as I know, Renpy allows mostly for still images.. if you wanted to simulate movement you'd need _a ton_ of images..

**Comment by multimokia** [comment]
Ren'Py allows for transforms, however they're also a bit of a performance hit due to us having to create a screen and constantly update it while a song is playing. So it's not the most efficient way of doing it. The other way would indeed be a lot of images, but then we're cycling through a lot of code to constantly switch to another image, and as pointed out, it'd require a lot of images.

**Comment by AsuraShun** [comment]
would gifs work? maybe someone could make them

**Comment by multimokia** [comment]
I haven't tried loading in a gif with Ren'Py, so I'm not all too sure on that front.
