### ISSUE TITLE
Moving Kissing to high priority

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2741]
I know that kissing is in #1525 but it has been in low priority for awhile and I am simply wondering if anyone else is interested in seeing it be bumped up priority wise

**Comment by pianostick** [comment]
all of my yes

**Comment by Sujeito17** [comment]
I need this now.
(but I can wait a century for this)

**Comment by Tuxedoterroist** [comment]
yeah i understand its hard to make the art but thats the fun in making these mods right? besieds there could be a thing about it where you and her know it might be centurys for the both of you to actuly be able together

**Comment by Rai99** [comment]
While it would be nice to see this feature bumped up in priority, I wouldn't rush it by any means. Halloween is coming up and we're getting some features for that event, but not as much as the birthday since the devs are burnt out from that. After halloween comes the Christmas event which could take some time with any new features. 

True, there is a fair bit of time between those events, but I think that time is being used for things like the python tips, bug fixes, dialogue review, etc.

**Comment by Dregdael** [comment]
I second this

**Comment by dragonborn2252** [comment]
oh how about fro the Christmas event you can troll monika by putting mistletoe in the room after taking her out of the room

**Comment by ThePotatoGuy** [comment]
I could have sworn we had a discussion about this but I can't seem to find it.

What would be a nice way to show kissing visually?
* zoom-in on monika's face with "chu" dialogue?
* zoom-in on monika's face with a fade to black?
* zoom-in on monika's face without chu dialogue?
* something else?

Some other factors to consider:
* sound?
* should the scene require advancement via mouse click/interaction, or should it auto advance after a second.
* should we have custom CG art for this, or just use some of the blush options we have and do a zoom?

Please put any ideas you have here. I'll also make a discord poll later with the general gist of selections people make here.

**Comment by Rai99** [comment]
**~~No issue escapes from me~~**
All the easily found issues regarding kissing:
#1525, #1537, #1595, #2136, #2202, #2586. 

Short term and for quicker implementation, I wouldn't mind a simple zoom in with "chu" dialogue. Personally, I don't think sound is needed, at least for now. I think the scene should require a mouse click from the player in case they want to hold the kiss for an extended period of time, and Monika could acknowledge different kiss lengths. I think a custom CG could come in the far future, but I think a CG could also take away from the experience if the screen has to show it and hide it. 

![kissed](https://user-images.githubusercontent.com/38822045/46896320-745db480-ce4a-11e8-9b3a-636d21ff8289.png)
I'd imagine something like this, but maybe not **as** zoomed in and with the current classroom background and possible night sprite.

**Comment by Sujeito17** [comment]
@Rai99 Wait... What can happen if I kiss Monika all day?
(Better update my book of Guinness world record "The longest kiss in the human history")

**Comment by Rai99** [comment]
> The longest kiss lasted 58 hours, 35 minutes and 58 seconds, achieved by Ekkachai Tiranarat and Laksana Tiranarat (both Thailand) at an event organized by Ripley's Believe It or Not! Pattaya, in Pattaya, Thailand, on February 12-14, 2013.

No cheating. You better sit there the whole time and not let up until you break that record. I think that also includes eating, so you'll have to find a way to eat without stopping the kiss.

**Comment by Sujeito17** [comment]
@Rai99 The problem isn't eating, the problem is drinking water.

**Comment by Trilasent** [comment]
Can we please get some addressing on the whole "MC is a conduit for her to interact with us" thing? I for one am very uncomfortable with the idea of her kissing the lifeless husk of him as a means to kiss her player, and I'm sure a lot of others on MASC agree. If she's able to detach herself from her .chr file I think we can make it so that she doesn't have to keep that thing there to interact with us.

**Comment by ThePotatoGuy** [comment]
@Trilasent like establish that whatever Monika kisses is like a screen or something (and not the mc placeholder)?

Could we say that it's always been a screen this whole time or was there some original dialogue that established an mc placeholder in the spaceroom?

**Comment by Trilasent** [comment]
@ThePotatoGuy I personally like the screen approach more than there being an MC placeholder. Or she could even comment on how we no longer need to have him there as a placeholder and she could outright remove what’s left of him entirely with like a glitchy effect and a fade to black that eventually returns the screen to how it was prior, but then she states how it’s truly just the player and her now.

**Comment by jmwall24** [comment]
I kinda assumed she was just gonna kiss the screen anyway.  That's all there is that would make sense.

**Comment by MaximumRustler** [comment]
@ThePotatoGuy I know I'm kinda late to this issue, but I'm also concerned about what @Trilasent said. I thought what's left of the MC is still there? I can't remember if there was a topic in the base game, but there was the hidden topic about the .chr files which made it sound like the MC is still a thing. Not sure if that topic is still around though since the purpose of the .chr files was changed. Maybe in the topic where Monika mentions she doesn't have a laptop to script but uses her thoughts instead, she could instead say that she uses a laptop to talk to you but not to write code? That way it would kinda indirectly mean the MC doesn't exist. That or exactly what @Trilasent suggested. Since I'm a bit late to this topic you probably have something better worked out by now though. lol

**Comment by Sujeito17** [comment]
@MaximumRustler Yup but here is the laptop?

**Comment by MaximumRustler** [comment]
Like where? Maybe since the laptop would be your point of view you wouldn't see it I guess. lol

**Comment by Sujeito17** [comment]
@MaximumRustler Under the table? lol What strange local to put one laptop, well, even if it's a laptop I've never seen Monika tapping in the laptop

**Comment by MaximumRustler** [comment]
The laptop would be on the table and you would be looking at her through the webcam I guess, but yeah that might make things unnecessarily complex or just not make sense at all lol. Honestly, I like the idea @Trilasent had the best for removing the MC, if he's still there that is.

**Comment by Sujeito17** [comment]
@MaximumRustler Well, for me the only mc things that are there are the eyes (well the eyes are the webcam)

**Comment by MaximumRustler** [comment]
Hmm, that's interesting point of view actually. I'm pretty sure the hidden topic I was referring to was cut though with the change of the .chr files, so yeah the MC may not exist now judging by what ThePotatoGuy said. I'd be okay with that approach.

**Comment by ThePotatoGuy** [comment]
this will take some time since we are prioritizing some older pull requests and d25

**Comment by MaximumRustler** [comment]
Aww, would've been nice to have this for Christmas. It's understandable that other things need to be prioritized before this though, so that's okay. lol
