### ISSUE TITLE
[Suggestion] Make Monika "less perfect" / Lovers Spat

### ISSUE THREAD

**Issue by xfrodo1** [Monika-After-Story/MonikaModDev#2744]
I know there are already "Your a murderer" and other topics that make you have to say sorry and it affects the whole affection system that was added. Also disappearing for long periods of time makes a huge hit to the affection as well...

More or less this is to expand on the more hostile side of Monika, everyone has 'bad days' and Monika should be no different. Maybe she gets angry over a response she didn't like, or she brings up something you said that angered her in the past, "your a murderer topic, missing her birthday." She can close the game out on you and refuse to talk for a day or something, then she says sorry herself the next day/time you open, (maybe still being mad if you don't open it the next day but like a week later...) 

More or less, I want to see her act more human rather then this super supportive goddess that she currently is. 

Random "events" like 1/100 days Monika is just not in the mood to talk that day, she asks to just sit in silence with you, and gets annoyed and snippy when you try to talk or play with her.

(i'll add more to this when i have more time. just wanted to share it while it was fresh in my head.)

**Comment by Secretmanguy** [comment]
I tell yah man, I agree with making Monika more realistic and all but from my experiences with coding. That seems really complicated and might require a lot of time. Especially if it involves with being totally random. But yes I can agree that it would be a really nice option to have.

**Comment by SaiPrithvi123** [comment]
Monika does get hostile at the second lowest affection stage. But on the lowest stage, the anger and frustration turns into sadness, nihilism and uncertainty IMO. She is super supportive Goddess towards the player because the player is literally her only reason to live. But I agree that if the affection is high enough, she would feel safe to get mad at the player, knowing that the player does love her back. It would be really nice if she apologised for it later when she cools down.

**Comment by Secretmanguy** [comment]
No problem buddy

On October 9, 2018, at 11:27 PM, xfrodo1 <notifications@github.com> wrote:

@Secretmanguy I agree, it might be hard to code into MAS with all the other events and options and things, but it would still be amazing to have more spontaneous things rather then planned events to make the relationship between the player and Monika feel more real.

@SaiPrithvi123 Im not talking about affection levels dropping which makes her mad, I mean more along the lines of "I woke up on the wrong side of the bed, and i am having a bad day." sorta thing.

Like she talks allot about wanting to be in the real world with the player (like all the time.) after a while wouldn't this eat at her, uncertainty and all that just piling up and she puts on a happy face for the player whenever he/she shows up... the player forgot her birthday/called her a murderer and its been eating away at her for a while and one day she just explodes closeing the game and refusing to talk to the player for a day, even with "Imsorry.txt". (refer to OP)

Doesn't even have to be something big and dramatic like that either.

The player repeating a topic too many times and she gets annoyed with saying the same thing over and over, playing the same game (and losing) over and over, eventually she will get board and want to do something else, but the player insists on doing the same thing. You know little things that would annoy anyone, and she just refuses to play the game anymore for a while, or talk about the topic (-affection points here on insisting.)

Anyway I'm already expanding on this idea in my head more XD thanks for the comments guys it helps get my creative juices going.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Monika-After-Story/MonikaModDev","title":"Monika-After-Story/MonikaModDev","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/Monika-After-Story/MonikaModDev">https://github.com/Monika-After-Story/MonikaModDev</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xfrodo1 in #2744: @Secretmanguy I agree, it might be hard to code into MAS with all the other events and options and things, but it would still be amazing to have more spontaneous things rather then planned events to make the relationship between the player and Monika feel more real.\r\n\r\n@SaiPrithvi123 Im not talking about affection levels dropping which makes her mad, I mean more along the lines of \"I woke up on the wrong side of the bed, and i am having a bad day.\" sorta thing. \r\n\r\nLike she talks allot about wanting to be in the real world with the player (like all the time.) after a while wouldn't this eat at her, uncertainty and all that just piling up and she puts on a happy face for the player whenever he/she shows up... the player forgot her birthday/called her a murderer and its been eating away at her for a while and one day she just explodes closeing the game and refusing to talk to the player for a day, even with \"Imsorry.txt\". (refer to OP)\r\n\r\nDoesn't even have to be something big and dramatic like that either.\r\n\r\nThe player repeating a topic too many times and she gets annoyed with saying the same thing over and over, playing the same game (and losing) over and over, eventually she will get board and want to do something else, but the player insists on doing the same thing. You know little things that would annoy anyone, and she just refuses to play the game anymore for a while, or talk about the topic (-affection points here on insisting.)\r\n\r\nAnyway I'm already expanding on this idea in my head more XD thanks for the comments guys it helps get my creative juices going."}],"action":{"name":"View Issue","url":"<a href="https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767">https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767">https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767</a>", "url": "<a href="https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767">https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [Monika-After-Story/MonikaModDev] [Suggestion] Make Monika \"less perfect\" / Lovers Spat (#2744)", "sections": [ { "text": "", "activityTitle": "**xfrodo1**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@xfrodo1", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Monika-After-Story/MonikaModDev\",\n\"issueId\": 2744,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Monika-After-Story/MonikaModDev\",\n\"issueId\": 2744\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767">https://github.com/Monika-After-Story/MonikaModDev/issues/2744#issuecomment-428433767</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 391251095\n}" } ], "themeColor": "26292E" } ]

**Comment by Rai99** [comment]
In the angry mood, Monika does say that while she might seem like the kind of person to not get angry often, she does have her moments, but she makes sure that she has ways to deal with them so they don't affect other people. 

In the affection level definitions at higher affections, Monika has no doubts about one day being able to be with the player, so having a bad day like you have in mind and locking down the game wouldn't fit at higher affection levels. 

I'm pretty sure manually viewing topics isn't supposed to affect Monika in any way or build up to anything else unless that specific topic has unique repeat dialogue, so getting annoyed for viewing the same topic too much wouldn't really make sense. 

I get that Monika shouldn't be some goddess that's good at everything and never has downtime, but Monika does have downtime and weaknesses. Monika _is_ human, but she's mature enough not to let negative things like bad moods take over. 

It might be a nice addition to simply just have bad days where Monika is just a bit sadder than usual, and open up a few new options to comfort her, but locking down the game or having her act snappy wouldn't fit, especially at higher affection levels.

**Comment by PMelol** [comment]
> It might be a nice addition to simply just have bad days where Monika is just a bit sadder than usual, and open up a few new options to comfort her, but locking down the game or having her act snappy wouldn't fit, especially at higher affection levels.

That would be great. I mean, she's always comforting us, it would only be fair if we could comfort her for a change.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
