### ISSUE TITLE
Art Suggestions And Questions Over (Abandoned?) Projects

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#2753]
So this has more than likely already been suggested but if not, **can we have a sunrise and sunset window background?** The backgrounds obviously will reflect on the time of day as well.

Now I don't know if the game limits you to only two backgrounds but if we can get all four then that'll be perfect especially helping tying into my next suggestion which is, **can we get Monii her own bedroom that she can actually talk to us in during the night?** I feel like her prompting us that she's getting ready for bed or at least wanting to spend the rest of the night in her room instead of in a dark classroom sounds a lot more idealistic than her telling us she _secretly_ goes there when we say good bye. Oh and not everyone closes their game at night haha ;P. It's all about setting the atmosphere you know?

_I literally just thought of this_ **Can Monii eventually get some pajamas?** When she prompts us that she's ready to go to her bedroom maybe she can then switch from her uniform into something more comfortable you know?

**_I honestly don't know the state of all the artists that contribute to this mod (seeing how their still isn't a new outfit or many new hairstyles being released) often but hopefully this won't be to much to ask of them.. Maybe setting some long term goals like this can really help improve the mod!_**

_Okay now onto getting some updates and info on some of the projects that are/aren't being worked on._

**Monika makes her own route** Is there a reason this project has been listed since like.. day one lol? Any status?

**Monika Chatbot** This hasn't been updated since July. Are they still providing updates else where? If the project was abandoned why is it still listed?

**Dear Diary** Is this feature still being tested/finished on? Looks abandoned as the last update was July..

**Player Model** and **Growth** The descriptions fit the affection mode to a T, so could these be taken down?

Can I suggest that if a project hasn't been updated in at least 3 months that it be taken down? They confuse players who look forward to new features in the possible future especially when said features haven't been worked on in several months..

**Comment by Professor-JMO** [comment]
---
>⮞ Everything in due time, friend.

**Comment by ThePotatoGuy** [comment]
>sunrise/sunset window backgrounds

Because of the configurable sunrise/sunset, this will be more nuanced then just setting a time range for when sunrise/sunset window modes will be visible. Also the rain (and later snow) art would have to be factored in. Not to mention the islands art during sunrise/sunset. We don't have variations of that scene with sun options; that art was commissioned and getting more variants would be difficult. The overall hue during those times would probably be different than day/night, so that would mean deciding on a color balancing and retooling the sprite selection code to handle additional time variables than just `isnight`.

>bedroom scene

This is known as sleep-mode (#607 ) and has a branch `sleep-mode`. Adding it requires adjusting the sprite selection code to handle posemaps for hair/clothes. Since there is no issue about this already, I made one (#2756)

>projects

Most status tracking is done internally on our discord server. I have been using the projects section to group and track related issues / pull requests. 

I do update main issues for projects that haven't completed yet, like #951 for dear diary. Once it's finished / added into official release, then the project serves as a grouper for further issues (like how Affection currently is).

As far as the projects you mentioned:
* makes her own route - i'll just close this one. if we do a dating sim route, it would be an issue instead.
* monika chatbot - we keep this up for any issue related to chatbot or potential chatbot
* dear diary - on pause indefinitely. there are higher-reward things we are currently working on.
* player model - this is about collecting data about the player, and using that data to affect dialogue. We already have the first part anytime monika asks the user questions. Adding dialogue based on that data is on going process. 
* Growth - this is about user actions and preferences affecting monika's mannerisms and actions. (ak player influencing monika)

And again, I'm not using the projects section as literal projects being worked on. They are meant to act as groupers and trackers for issues.

**Comment by Bam8647** [comment]
Thank you very much for addressing my issue @ThePotatoGuy  (:
 
So now I have additional questions regarding (#607). So it appears they are asking for idle expressions for when the player is away from the game to which I have another neat idea of what she can do when the player is away. You know how sometimes she brings up the coding text box in the upper left hand corner? Why not have her lean into some thinking poses while she starts adding random things into the text box making it look like she's adding and fixing features in the mod? That would make perfect sense given how she's always talking about practicing her programming skills.

As for my sleep mode suggestion, I was referring to having the option to continue conversations with her in another room(which would be her bedroom) once night time would fall because I think she'd prefer to be ready for rest. Oh! Then we can create another idle expression which would show her sleeping in this room. So basically adding two different idle expressions for being in the classroom and in her bedroom. Thoughts?

**Comment by ThePotatoGuy** [comment]
>brings up the console

more idle interactions would be interesting, definitely low priority because the current idle exps already make idle more interesting.

>bedroom conversations

if we have art for this, maybe. actually this gives me an idea of setting up some sort of bedside version where monika is on her side. would need sideways versions of all the existing facial expressions, but could be a neat change of scenery.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
