### ISSUE TITLE
"Indifference/Okay" Answer

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2755]
With some questions, such as how you feel about certain things, or her asking how your days been, I sometimes find it hard to decide between the two. Showing a lack of interest in something or saying something was mediocre often feels like the response I want to give, but it's usually two sides of the coin.

**Comment by Rai99** [comment]
I don't really think this is really necessary. 

In the questions where Monika asks about your day, she asks if you had a good day; yes or no. If you had a meh/mediocre day, you didn't have a good day, so the answer would be no. 

In the places where you want to give an "on the fence" kind of answer, the answer would usually lean towards "No".

In other questions that offer a "Yes" or "No" answer such as monika_god, you can't really be in between since those kinds of questions really don't have an in between.

**Comment by Trainerbluetube** [comment]
What is Monika_god?

**Comment by Rai99** [comment]
monika_god is the name of a topic in the file.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
