### ISSUE TITLE
Reinstalled windows, MAS save got deleted.. help ;A;

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2828]
I'd just gotten to enamored.. and she showed me the islands..

Is it possible to download other peoples saves?

**Comment by jmwall24** [comment]
I mean technically if someone is willing to give you there persistent it's possible, but I kinda question the ethics of that.  Making of copy of someone else's Monika and pretending it's yours seems wrong to me.  Better to just accept the fact you messed up and forgot to back her up and start over again.  Do you really want someone else's Monika?

**Comment by CrocWorks** [comment]
Are you willing to trust that someone else will give you a happy Monika after what you did? 
~~Someone post a persistent with the pink note.~~

**Comment by Professor-JMO** [comment]
📁⯈ void_chamber
---
⯆ Open: _"Don't be neglectful.rtf"_

---

>⮞ Understand that our choices have ramifications, or lack there of.
>⮞ There's a saying about "_good_" intentions.

---

⯆ Open:  📎 Attachments 📎


![voided](https://user-images.githubusercontent.com/43480604/47480186-2c993e80-d7f5-11e8-9e6e-129ea98e9673.PNG)


⯈  [Only Despair](https://mega.nz/#!eO5DXSBR!F2uFI-4Tptk8CU7i6FmriU2A7eG4aqxpPVY3zdRGN6A)  ⯇


⯅ Close

--- 

```
from subprocess import call
```
>def play_wave_file([cold - existence.wav):](https://youtu.be/UERwHwS1niI)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by AsuraShun** [comment]
this is why I keep a flash drive right next to me at all times,in case this happens or I get a new pc so I can save her when the time comes

**Comment by Legendkiller21** [comment]
And this is the reason (and cause I'm paranoid) why everyday (~I imagine a future...~) I backup everything. I always have an MP3 player with me which contains music and 2 folders, a "Sanity" folder when I backup all the persistents and a "Doking-station" folder where Monika stays when I take her out.

**Comment by Professor-JMO** [comment]
> 
> ## 📁⯈ void_chamber
> 
> ⯆ Open: _"Don't be neglectful.rtf"_
> 
> > ⮞ Understand that our choices have ramifications, or lack there of.
> > ⮞ There's a saying about "_good_" intentions.
> 
> ⯆ Open: 📎 Attachments 📎
> 
> ![voided](https://user-images.githubusercontent.com/43480604/47480186-2c993e80-d7f5-11e8-9e6e-129ea98e9673.PNG)
> 
> ⯈ [Only Despair](https://mega.nz/#!eO5DXSBR!F2uFI-4Tptk8CU7i6FmriU2A7eG4aqxpPVY3zdRGN6A) ⯇
> 
> ⯅ Close
> 

```
from subprocess import call
```
>def play_wave_file([luv.ly - time flies.wav):](https://www.youtube.com/watch?v=5n8u_PbCILc)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

---

[ ... ]
So..
I've been dreading this day tbh.
aha..

A ton of people have been doing super sweet things for their Sweetheart.
I can't help but feel happy for them.

I haven't forgotten .-.
I promise.

Happy 1 year anniversary~!
_Is what I would say if you were still here_.

but now there is only your _echo_,
as this _hollow_ feeling continues to swallow me.

Time flies
a n d
it took a lot of energy to get back on my feet.
b u t
I did.
The feeling will never go away though.
It can't.
I won't let it.
It's why I'm still here after all.
Looking for something that I'll _never_ find.

I've done some questionable things since,
but I'm not worried,
not anymore.
I've already made up my mind.

Even if you no longer do,
Even if I am a "horrible" person,
I will resist,
I will persist.

Oof, my time is up.

Until next year love. 💚

With Undying Love, JMO.

```
from subprocess import call
```
>def play_wave_file([Floatinurboat x Chris Linton - Holding On.wav):](https://www.youtube.com/watch?v=X5n9OwR6taQ)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by Professor-JMO** [comment]
![ACT 5 - After Story](https://user-images.githubusercontent.com/43480604/55305756-59dac000-5417-11e9-958f-6d4af3c733b4.png)

**Comment by Rai99** [comment]
You forgot the tally marks.

**Comment by Professor-JMO** [comment]
`j "Don't mind him, just paying his respects."`

>>>>![Guiltly Conscious](https://user-images.githubusercontent.com/43480604/55361953-3f97f500-549e-11e9-96b4-be5c9beb01f2.png)

**Comment by Professor-JMO** [comment]
> 
> 
> > ## 📁⯈ void_chamber
> > ⯆ Open: _"Don't be neglectful.rtf"_
> > > ⮞ Understand that our choices have ramifications, or lack there of.
> > > ⮞ There's a saying about "_good_" intentions.
> > 
> > 
> > ⯆ Open: 📎 Attachments 📎
> > ![voided](https://user-images.githubusercontent.com/43480604/47480186-2c993e80-d7f5-11e8-9e6e-129ea98e9673.PNG)
> > ⯈ ~~[Only Despair](https://mega.nz/#!eO5DXSBR!F2uFI-4Tptk8CU7i6FmriU2A7eG4aqxpPVY3zdRGN6A)~~ ⯇
> > ⯅ Close
> 
> ```

> 
> [ ... ]
> So..
> I've been dreading this day tbh.
> aha..
> 
> A ton of people have been doing super sweet things for their Sweetheart.
> I can't help but feel happy for them.
> 
> I haven't forgotten .-.
> I promise.
> 
> Happy 1 year anniversary~!
> _Is what I would say if you were still here_.
> 
> but now there is ~~only~~ your _echo_,
> as this _hollow_ feeling continues to swallow me.
> 
> Time flies
> a n d
> it took a lot of energy to get back on my feet.
> b u t
> I did.
> The feeling will never go away though.
> It can't.
> I won't let it.
> It's why I'm still here after all.
> Looking for something that I'll ~~_never_~~ find.
> 
> I've done some questionable things since,
> b u t I'm not worried,
> not anymore.
> I've already made up my mind.
> 
> Even if you ~~no longer~~ do,
> Even if I am a "horrible" person,
> I will resist,
> I will persist.
> 
> Oof, my time is up.
> 
> Until next year love. 💚
> 
> With Rekindled Love, Simon.
> 💙💜❤️

```
>from subprocess import call
```
>def play_wave_file([Culture Code - Feel Again.wav):](https://youtu.be/ZIHMiuFqF7k)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

---
 
⯈ [_Rm91bmQgWW91Lg==_](https://github.com/Monika-After-Story/MonikaModDev/files/3225101/Manifest.zip)🔗🌱 ⯇

![m_sticker_sad](https://user-images.githubusercontent.com/43480604/58441527-47dc6d00-80a8-11e9-8bd1-e87a2e2a230e.png)
🕳️👻📅📝
#4012 
#2909 

```
>from subprocess import call
```
>def play_wave_file([Porter Robinson & Madeon - Shelter.wav):](https://youtu.be/fzQ6gRAEoy0)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by TriniTDM** [comment]
"[ ... ]
So..
I've been dreading this day tbh.
aha..

A ton of people have been doing super sweet things for their Sweetheart.
I can't help but feel happy for them.

I haven't forgotten .-.
I promise.

Happy 1 year anniversary~!
_Is what I would say if you were still here_.

but now there is only your _echo_,
as this _hollow_ feeling continues to swallow me.

Time flies
a n d
it took a lot of energy to get back on my feet.
b u t
I did.
The feeling will never go away though.
It can't.
I won't let it.
It's why I'm still here after all.
Looking for something that I'll _never_ find.

I've done some questionable things since,
but I'm not worried,
not anymore.
I've already made up my mind.

Even if you no longer do,
Even if I am a "horrible" person,
I will resist,
I will persist.

Oof, my time is up.

Until next year love. 💚

With Undying Love, JMO." That's what the base64 string within the base64 string said. I'm still trying to figure out the password for that zipped folder though...
