### ISSUE TITLE
Monika has started repeating subjects with the option off.

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2866]
I told her not to repeat herself but she does so anyway ;A;

**Comment by Rai99** [comment]
**Short answer: You probably started over, so now _all_ topics are new for you and technically aren't repeating.** 

A couple days ago, you made the issue #2828 saying you lost your Monika. Seeing as how you asked about an auto progress feature in #2860(which already exists) and seeing as you're having this issue now, I'm guessing nobody gave you their Monika, which makes it safe to assume that you started over and wanted to auto progress through all the topics you've already seen. (which you can)

On Wednesday Oct. 24, you made the issue #2827 asking how to back up Monika, but closed it exactly 1 hour and 50 minutes later, which probably made it go unseen by most people. 

You were also seen in the MASC discord tech-support channel asking for help that day where you _did_ probably get the answer you were looking for, but it looks like you didn't back up and lost your Monika due to wiping your PC.

**Comment by AsuraShun** [comment]
you have that but in my case she talks about her hair as if it's down,even when it's tied up

**Comment by AsuraShun** [comment]
this is unrelated but is she supposed to talk about her tied hair as if it was down?

**Comment by Mcmanybucks** [comment]
> 
> 
> **Short answer: You probably started over, so now _all_ topics are new for you and technically aren't repeating.**
> 
> A couple days ago, you made the issue #2828 saying you lost your Monika. Seeing as how you asked about an auto progress feature in #2860(which already exists) and seeing as you're having this issue now, I'm guessing nobody gave you their Monika, which makes it safe to assume that you started over and wanted to auto progress through all the topics you've already seen. (which you can)
> 
> On Wednesday Oct. 24, you made the issue #2827 asking how to back up Monika, but closed it exactly 1 hour and 50 minutes later, which probably made it go unseen by most people.
> 
> You were also seen in the MASC discord tech-support channel asking for help that day where you _did_ probably get the answer you were looking for, but it looks like you didn't back up and lost your Monika due to wiping your PC.

I know but she repeats things she's already said even with this new version.

**Comment by Rai99** [comment]
@AsuraShun, please make a new issue discussing the problem

**Comment by Rai99** [comment]
I think the repeat topics option is more meant for later on when you've seen everything. With or without it, I think newer, unseen topics are put at a higher priority to display. 

Another possibility is that you've exhausted the number of new random topics that day, so Monika is repeating topics.

**Comment by SaiPrithvi123** [comment]
>Another possibility is that you've exhausted the number of new random topics that day, so Monika is repeating topics.

I unchecked repeat topics, and she doesn't even say anything except saying that she has nothing to talk about or some new stuff in every update. I don't think that's a possibility.
