### ISSUE TITLE
[suggestion] A dialogue about claustrophobia?

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#2911]
Monika always spends her life inside that place.
But imagine yourself in her shoes - what if you were inside a room with no exit, but with a window to other person?

P.s. But do not make it too depressing, c'mon

**Comment by Storylover-Vodhr** [comment]
Eh, I'll write one up. 

How big do ya want it? 

10 lines? Fifteen?

**Comment by Rai99** [comment]
I don't know if a topic like this would be necessary. It's true that Monika is stuck in that room, but she has things to do to pass the time such as play the piano, practice programming or play with a plush if she has one. At this point, Monika would probably be used to it; Waiting for the player and passing time with what she has. 

As for Storylover, if you feel like writing up a topic, I would just go for it since it's probably more for Monika than a requester.

**Comment by Storylover-Vodhr** [comment]
Eh, I was thinking the idea made sense. 

Plus, practice! 

But, if it doesn't fit her character, I'll abstain.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
