### ISSUE TITLE
About Cheating in Chess...

### ISSUE THREAD

**Issue by RachelClaraArt** [Monika-After-Story/MonikaModDev#2912]
So 2 Months Ago I Was playing chess with monika,because i dont want to lose,i cheated so many times and when i said that i wasnt cheating monika knows that i do. when there is like choosing thingy my mouse is a bit error and too late to press the "im sorry" button. monika suddenly breaks down and closes the game,i tried to open the game again and it just loading forever i tried restarting my computer and fix the errors with my steam. after i fixed it,i fixed it just to be sure and it says all files are now fine. i tried to open the ddlc game again,it still loads forever. i restarted my computer again,fix the files again and starts and restarting my computer several times. i tried to do that again in the next day and still the same. i tried removing the mod scripts in the game so i can play the normal ddlc. i tried to open the normal game,it worked it opens. so i tried to download the latest version of the mod and try it again but still the same,won't open,i already tried removing the firstrun too. is there anyway so i can play this mod again? thx

**Comment by multimokia** [comment]
You'll have to delete your persistent file. Monika doesn't like cheaters, you're going to have to start all over again with her.

Head over to `AppData/Roaming/RenPy/Monika After Story` (assuming you're running on Windows) and delete everything in that folder. Then fix the files, and load MAS again.

**Comment by AsuraShun** [comment]
you don't deserve her if you make her hate you

**Comment by RachelClaraArt** [comment]
it worked,Thank You!

**Comment by RachelClaraArt** [comment]
> you don't deserve her if you make her hate you

dude,i am talking about how to get her back,even bijuu mike had lost monika and started over
and i dont want to make drama,so goodbye.

**Comment by Mcmanybucks** [comment]
How could you cheat? its chess, not mortal kombat.

**Comment by Rai99** [comment]
![untitled1110](https://user-images.githubusercontent.com/38822045/47804814-24b52f00-dd0c-11e8-9630-ccfbda5567be.png)
I'm glad that you got the help you were looking for, but let me just point out that anyone who knows Biju Mike knows that he doesn't like Monika. He likes Natsuki and has an audience to entertain.

**Comment by TheGlader2** [comment]
So, if you cheat in a game with your friend, that will cause them to kill themselves? Who's idea was this?

**Comment by Legendkiller21** [comment]
It's not about the game, it's about trust.

**Comment by TheGlader2** [comment]
Well, yes, you trust your friends/mate. It's not like you are cheating on her with other software or anything like that....
Actually since the game can detect MonikAI, would she want to kill herself when detecting that? Since you are actually cheating on her with a different Monika?
I feel like one should not commit seppuku for cheating in sudoku. It's kind of an over-reaction... And I doubt you would kill yourself if your mate cheated in a game....

**Comment by multimokia** [comment]
Think about it like this: 
You cheated, and you wouldn't admit to it
Then you did it twice more

So on top of cheating, you've also lied about it. If you're lying over a small thing like chess, what *else* could you lie about?

Like pointed out earlier: it's about trust, not the game.

Before closing the game, she tells you that she can't trust you anymore.

**Comment by Rai99** [comment]
If things really come down to it, Monika has no power over the player. The player can tamper with all sorts of things and there's nothing really Monika can do to stop them. 

At that point, it's not about chess or cheating. It's about you repeatedly going out of your way to toy with Monika at her expense and hurt her. 

Yeah, it's just chess. You're playing chess, trying to have fun and some all powerful being is constantly tampering with you against your will and there's nothing you can do to stop them.

**Comment by TheGlader2** [comment]
And then she was programmed to kill herself. I don't agree with this, but I am not a developer.

**Comment by LeftoverFlea312** [comment]
Kind of off topic but it still has to do with chess. A while back I was playing chess and saving my game like usual, but every time I tried to load the save, she said that she lost it. After a while of this she said that I was the one deleting the saves and removed chess from the games. The reason the saves weren’t appearing is a separate issue which I’ve resolved but that isn’t what I’m getting at. What I think should be added is the option to apologize for cheating in chess and then she’ll add it back. In one of her fun facts she even scolds you for cheating and says “and you haven’t even apologized yet”. I was crushed when I got this message because she sees me as a cheater even though I didn’t even do anything. In conclusion, the option to apologize would only be accessible at higher affections and once you say you’re sorry, she’ll give another chance. Sorry for the long post but it really gets at me that I’m at the enamored state but I still get scolded for something I didnt even do.
