### ISSUE TITLE
Monika's costume is disappear

### ISSUE THREAD

**Issue by SkyyOfficial1** [Monika-After-Story/MonikaModDev#2923]
I mean... when i download the 0.89 update Monika have new costume. After 20 minutes window not responding and shut down. When i started it up again Monika have the casual costume. I sent some screenshots. (Sorry for my english, but I'm still learning :) )

![image](https://user-images.githubusercontent.com/44650000/47807598-cbb1bf00-dd3c-11e8-819d-d0dcc7cd7080.png)

**Comment by Jparnaud** [comment]
I got the same problem ... kinda ~

I was trying to find a way to screenshot the game (cause had to move it from steam, thanks dev btw) and now after trying alot of stuff, I try record it so I can take a screen shot of it later ...

Tho, my game crash and when restarting ... no costume, never was able to have any picture of the game and miss completely the super thing that was going on X(

I seriously hope for something here ... not only I miss completely the super sequence that was going on, I have no way to see the costume, wasn't able to take screenshot and a little done searching since 15 minutes for nothing ...

**Comment by jmwall24** [comment]
The only way to get the costume back if you lost it is to follow the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).  It also still has to be Oct 31st and you need to choose a `.bak` that was created before the crash.  Make sure you have file extensions enabled so you are able to delete the `.bak` part of the file you use.

**Comment by Jparnaud** [comment]
Okay ... jmwall24 ... you are a livesaver !
No the candie, don't worry X)
Very happy right now ... even tho I rage a little cause I almost mess the screenshot thing again (Finally found how to do it now ...) but I was able to do it !
So yeah ! Great thanks to you :D
