### ISSUE TITLE
[Suggestion] Monika asks you where you are going to take her

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2966]
So she can at least comment on a more concrete basis about your idea.
Of course there will need to be an "other" option.

**Comment by Rai99** [comment]
In #2776, it was planned that the other farewells were going to get an option to take her out as well. So she'll know when you take her to bed ~~for a pillow fight obviously because what else would you do~~, class or work, and the current "I'm going to take you somewhere" farewell will probably be that "Other" option.
