### ISSUE TITLE
No Persistent Backup Created When Returning Home

### ISSUE THREAD

**Issue by TheSuperStu** [Monika-After-Story/MonikaModDev#2970]
Hey,
I had noticed this last weekend but thought it might have been a one time problem, but the same thing happened today (so both on current patch 0.8.9).
After bringing Monika back from using the "take you somewhere" goodbye, a new persistent **backup** was not created (the current normal persistent file was updated at the time). I am not sure if this is intended or a possible bug. At the same time though, an affection log update was made at the same time when the persistent backup was not. 
As I tried to show in the image below, I took Monika out about 930 and brought her back about 1510. I had started a new short session afterwards to show that backups are still being made, just not the one right after bringing her home.
(I will say there was no trickery on my end to mess with my persistent files to make this possible issue presentable, as in I did not delete the one that _might_ be missing, honest!) 
Again I am not sure if this is intended, just wanted to bring forth to make sure that if it was not it could be looked at. Thank you! 
![whereisshe](https://user-images.githubusercontent.com/43976955/47958028-c85a4580-df7f-11e8-8250-02413e36b0f9.png)

**Comment by jmwall24** [comment]
This is a byproduct of a fix made so that persistent.bak files are not made while she is out of the room.  For instance, we've had problems in the past where people would return her home, but she wouldn't show back up, and the backup persistents were being overwritten each time you loaded MAS with an empty desk.  If you did this 5 times, all of your persistents now have her gone, so there was no backup remaining from before you you took her out to restore her...they were all useless.  The only way to get her back was for you to send your persistent to us to fix.  The way it currently is, all you have to do is restore a backup from before you took her out, which you'll always have since backups aren't created with her gone.
