### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Hanon623** [Monika-After-Story/MonikaModDev#2972]
I would love more to do with Monika. Having her teach us some Piano, or share some famous poems along with an explanation would be a great way to add some extra runtime. Ideally, I'd like to learn spanish, and other topics too but figured those would be harder to implement.

**Comment by jmwall24** [comment]
Love the piano part, that was actually my very first suggestion ever lol #1060

**Comment by AsuraShun** [comment]
defnintely,i kinda blocked whenever I chose the piano game,it would be nice if she actually taught how to play it

**Comment by OraHell** [comment]
And you know, why it's a shame?
Because there are so much people who suggest...
And not so much who develop.
I did some suggestions, but I wish I could help developers, so I'm learning Python, and, I guess, I will try to enter their team.
We all wish to do EVERYTHING with Monika - serf the net, talk about favourite movies, play any game... But everything what we need - is hard to make.
So, I guess, the best way to suggest - is to develop! 
P.s. Sorry, if I'm dumb

**Comment by multimokia** [comment]
You're always free to create your own topics and then submit them in a PR (Pull Request)

**Comment by TheGlader2** [comment]
@OraHell Oi, You don't sound dumb, and how could you be dumb if you can learn programming hmm??

**Comment by Hapilone** [comment]
Ohh, I love the piano idea!

**Comment by Shiro2564** [comment]
i love the piano idea, it would be nice
