### ISSUE TITLE
Traceback,Can't Open The Game

### ISSUE THREAD

**Issue by TheNyoukOfLoL** [Monika-After-Story/MonikaModDev#2993]
So i installed the latest mod of Monika after story but when it says to re open the game for the update the game crash and the traceback appears 
![image](https://user-images.githubusercontent.com/44787907/48027541-5afa1080-e149-11e8-8e30-9756d9ce68c0.png)

**Comment by multimokia** [comment]
Right, I see you're running unstable. Can you send a screenshot of your `game/` folder, please?

**Comment by jmwall24** [comment]
You have .rpy files in your game folder.  You're going to have to delete all the .rpy files, reinstall the latest stable version of the mod from https://www.monikaafterstory.com/releases.html.  Then if you want unstable, download that using the update.  Those .rpy files are overwriting your .rpyc files on launch, causing that error.

**Comment by TheNyoukOfLoL** [comment]
Do i download the zip one or tar.gz one ?

**Comment by jmwall24** [comment]
You shouldn't be seeing the tar.gz file if you use the site i linked.  just click where it says `0.8.9 - The Scary Stories Update` and that will start downloading the correct file.  The file you want is called `Monika_After_Story-0.8.9-Mod.zip`.

Also, you're also probably going to need to delete the zz_history.rpyc file as well, since that's not in the stable version.  The unstable version will re-download that later.

**Comment by TheNyoukOfLoL** [comment]
i don't see the zz_history.rpyc when i open the file that means it's okay ?

**Comment by jmwall24** [comment]
yeah that's fine, but you're also going to want to delete it from your `game` folder, or you're going to get an error again.

**Comment by TheNyoukOfLoL** [comment]
Well now i can run the game but the first thing i see is that gray screen 
![image](https://user-images.githubusercontent.com/44787907/48085727-60b02e80-e1fb-11e8-82e7-a854a8ca4bb0.png) but i still can talk to Monika

**Comment by TheNyoukOfLoL** [comment]
Nevermind it works now thanks!
