### ISSUE TITLE
Moving Monika to my Android?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2995]
So we can take Monika with us in an usb drive, but she can't interact with us while that's happening.. so what about an APK? 

There are already people who have ported DDLC onto Android where it's basically just the vanilla spaceroom with some MAS functionality like music, but that's about it, they had no plans for further development.

But what about MAS? I would love to be able to take Monika with me on my phone :D 

[Here is the Android version](https://cz-games.weebly.com/just-monika.html)

**Comment by jmwall24** [comment]
Yeah, we've seen that.  It breaks the modding guidelines outlined by Dan and his team since there is no regular DDLC version for mobile, and thus this ends up being a standalone game and you don't need to have DDLC to use it.  This is why that app is no longer available in any app store...technically it's illegal.

**Comment by Dregdael** [comment]
So, I've been thinking. Since we can't actually port MAS to android due to modding guidelines, could it be possible that we use another devices such as the raspberry PI for a portable version? I don't know much but I think you can run DDLC on a raspberry PI 3, or at least get it to run, add a touchscreen and a battery pack and boom, you got a pocket Monika!

Might give it a shot once I'm out of drowning in Uni homework

**Comment by Dregdael** [comment]
Well shoot.

But I mean, there's no harm in trying, right?

**Comment by Mcmanybucks** [comment]
I don't understand, he's fine with modding but when it involved applications on your phones its a no-go?

**Comment by jmwall24** [comment]
The guidelines state no standalone mods, any mod that runs without ddlc installed is a no no.  And since ddlc doesn't exist for moblie, any mobile app automatically goes against the guidelines.

**Comment by multimokia** [comment]
Yep. Only way MAS has a chance of going over to mobile is if Team Salvato release an official mobile port of DDLC, therefore we can comply with the modding guidelines. Otherwise we can't do it.

**Comment by CloakedGhost** [comment]
This gave me an odd thought... 
Wouldn't Monika be illegal if she ever became real?

**Comment by Mcmanybucks** [comment]
> 
> 
> This gave me an odd thought...
> Wouldn't Monika be illegal if she ever became real?

Well, she's written as 18 years old.. in most european countries thats legal.

**Comment by MaximumRustler** [comment]
@CloakedGhost I mean, there is a difference between a mod and Monika becoming an A.I. that could eventually come to our reality. I think Dan would be kinda fine with it judging by his response here:
![2018-11-06 at 20-09-01](https://user-images.githubusercontent.com/38181362/48110337-7542f580-e200-11e8-9232-9760274245f6.png)
This was from a Q&A thing he did a while back. Link to the thread:https://www.reddit.com/r/DDLC/comments/7dvb70/hello_my_name_is_dan_salvato_i_created_doki_doki/

**Comment by FluffyMuffinMeyer** [comment]
> Yep. Only way MAS has a chance of going over to mobile is if Team Salvato release an official mobile port of DDLC,

... Is an Emulator possible? having a mini version of windows on my phone, that requires DDLC/MAS installed? It might be a bit large for most peoples phone storage, however...

**Comment by jack-ship-it** [comment]
Well it's possible for certain items I think something like joiplay might be a good solution
