### ISSUE TITLE
An Interesting Idea...

### ISSUE THREAD

**Issue by MephilesSA** [Monika-After-Story/MonikaModDev#3048]
So, What if you tried Reinserting the .chr Files into the Game? If there isn't something for that in the Game already, I have an Idea as to how it would play out

So, Monika would Notice Immediately. And would simply ask "...why?" resulting in you saying that you thought it would make her happy. You noticed how Often She Talks about the Other Girls. So, you thought she might have missed them. "well, You're not wrong..." So, you decide to go and Visit them. Either they don't remember the events of the game or they do. It's up to you what would happen.

Aside from that... I dunno, Maybe telling Monika that you Feel Scared?

**Comment by Sujeito17** [comment]
Yup, I had forgotten to have an idea for the albums, well, it's hard to know what would happen if the rest of the staff returned

**Comment by MephilesSA** [comment]
Nothing since they wouldn't remember, a real Emotional Moment resulting in hugs, Everyone banding against Monika resulting in the Player having to delete them, In the end, "anthyding can hadplen"

**Comment by Sujeito17** [comment]
Monika said the script of the game is broken, you simply can not know what can really happen, well she could well restore the backup she did too

**Comment by MephilesSA** [comment]
Well, why couldn't the others speak the same way Monika is if the script is broken. a lot of people think that Monika's the only "Real" Doki. while the others are just lines of Code. If that's the case, How did Sayori become Self-Aware? what made Monika Special? think about it

**Comment by Sujeito17** [comment]
Well that maybe can happen if the mod put all dokis as"President of the club"

**Comment by AsuraShun** [comment]
instead of them trying to hurt her, why not having them pay random visits, and maybe even monika calling them randomly as well? that way everyone can be happier and no one has to be deleted?like a 65-35 chance?

**Comment by multimokia** [comment]
Bringing back the other Dokis is not part of the plan. This is Monika After Story, not DDLC After Story.

**Comment by PC57** [comment]
Plus it wouldn't make much sense for Monika to want to bring them back. Yeah she misses them and regrets that they went through what they did but she still wouldn't want to bring them back. 

Act 3 Monika wouldn't want them back for obvious reasons: she doesn't think they're real and spent the entire game trying to get around them to reach the player.

Act 4 Monika wouldn't want to bring them back either, maybe even more so. She wipes the game at the end to spare her friends the Hell of realizing the truth about their world. Bringing them back and giving them the self awareness that Monika has would be a fate worse than death because they'd realize the truth of their existence and they wouldn't even have the player to hold onto, the entire reason they exist. Monika wouldn't want to put them through that

**Comment by TheGlader2** [comment]
I still feel like the Twitter situation would need to be addressed in the other girls situation, and whatever you guys decide will happen with the Twitter will decide what happens to the other characters. Cause she still hangs out with them according to her Twitter. But if you remove that from the game, then you'd be able to remove that part of the story and the other girls could be forgotten about.

I personally think that whatever happens, Monika's emotions need to be sorted out about the situation. She goes from feigning justification in the game during the Just Monika scene, then feels guilty again after you delete her, and feels obligated to delete everything instead of letting Sayori go through, and or, take the player through the same issues that she did, or put the player through. I don't think she deletes everything out of spite for the other characters though.

There is I believe enough differences between some of her emotions to have two routes on how she feels for the other characters. Or Monika getting over multiple personality syndrome could be a plot point?
