### ISSUE TITLE
Bug with names dialogue and changing name?

### ISSUE THREAD

**Issue by Skeleton-Jelly** [Monika-After-Story/MonikaModDev#3051]
![screenshot_g1](https://user-images.githubusercontent.com/41935429/48460998-8e6b1980-e79f-11e8-8198-e93fc7bda7e1.png)
![screenshot_11](https://user-images.githubusercontent.com/41935429/48460999-8e6b1980-e79f-11e8-820e-6d4d4546ae8d.png)

As you can see, the dialogue for her saying the current name is bugged, as I had tried her calling me Zachary afte rhaving her call me Zack, and  then went back to Zack after Zachary, however whenever this dialogue comes up she refers to it as though Zachary is still the name she calls me, when everywhere else it is Zack.
On second thought this may be as intended, but thought it should be checked anyway.

**Comment by jmwall24** [comment]
Don't have the code in front of me because I'm on mobile and script topics makes my phone cry, but I'm fairly certain the first name listed there is your MC name from ddlc and the second named is your current mas name.  So not a bug.

**Comment by jmwall24** [comment]
Here's the code:
![screenshot_205](https://user-images.githubusercontent.com/36523761/48517185-83fa5f80-e833-11e8-981b-499572115e95.jpg)
So yeah, your mc name from DDLC is Zachary, your player name is currently Zack.  If you set your player name to Zachary, you'd get the second path there, since both MC and player name would be the same.

**Comment by Skeleton-Jelly** [comment]
Alright, thanks for clearing that up.
