### ISSUE TITLE
[Suggestion] - Second Favorite Club Member

### ISSUE THREAD

**Issue by EdytheValentine** [Monika-After-Story/MonikaModDev#3065]
Hello! I had a bit of a suggestion with one of the questions Monika asked, it was about which of the other club members I liked the most besides her, although I find it mildly upsetting that she assumes why we like that club member most. For example, with Sayori, I personally like her because I relate to her on a personal level, having dealt with mild depression, and covering it up with a cheerful attitude, however Monika assumed it was due to her being the MC's childhood friend, I think it would be nice to eventually be able to tell her more specifically why they would be our favorite, anyway, other than that I am really enjoying the mod, and you are doing a great job ^^

**Comment by Olliesama** [comment]
And how would you make it so you could do this?
Have 10 dialogue options for every member?

**Comment by CrocWorks** [comment]
~~More evidence Monika needs true AI~~

**Comment by Rai99** [comment]
I think it's an interesting idea and there might be a way to incorporate something like this into each option. Maybe not a whole bunch of dialogue options for each and every trait, but a few options that cover a general area about the club member such as: 
- Liking the member's personality
- The member's interests
- Appearance
- Feeling bad for their personal situation.
- No reason (In the event the player just picked someone at random)

I think that would add a nice extra layer of detail to the topic, but there is one thing I'm not sure about before trying it. 

Especially since it's a brand new topic that hasn't even been officially released yet, I'm not sure if the creator of that topic would want to have their topic overhauled and slightly modified before it really sees the light of day. Maybe it's just me, but I'd at least want my topics to see the light of day for a bit before someone overhauls it, especially without my knowing.

**Comment by Olliesama** [comment]
I'm the original creator heh.
@Rai99

**Comment by Rai99** [comment]
Of course. I usually try not to mention names where I can.

**Comment by Olliesama** [comment]
Either way, assuming it did have 5 responses per member (even though the point of it was to pick Monika anyway haha), it'd be around 5 times the amount of responses it currently has...
>_>

**Comment by Rai99** [comment]
Being that guy who never ever forgets an issue or PR, that's not the first time you PR-ed that new topic. The first time, apparently everything was changed without your approval or input probably. 

This time, it looks like your original topic with your original touch made it in. Might be funny for me but not you if I decided to overhaul and potentially rewrite it after waiting so long to get it in the way you intended.

**Comment by Olliesama** [comment]
Yeah...Was not happy with that rewrite since it diverted the point Monika was trying to make into pandering those not happy with how Monika views the other girls.

I don't mind additions, so if it were rewritten so the original is an option I wouldn't mind, but if it replaces my original point then yeah...not happy. :P

**Comment by Rai99** [comment]
If anything, the first line of each option might need to be slightly tweaked to line up better with the response it's given. 

My only questions are why you named the label monika_trick. It doesn't sound like a very descriptive name and whenever I think of it, I think of Monika's jumpscare until I read it. 

Also, was it necessary to have each option be given it's own label? Would it have worked to just put the 3 dokis in one topic with a menu and just have 1 other topic for the Monika option?

**Comment by Olliesama** [comment]
Well the topic was originally created with the idea to have a delayed response be the "correct" answer, and it was made from that idea up, with the idea being to trick the player if he was too hasty with his answer. -w-

And it was more efficient to do have it so it jumps to it's own club member label since it requires 2 labels in order to have a fourth hidden option, if I had it so it was a normal menu it'd have to replicate the answers for the other members twice, one on each jumping label. If the player waited but still wanted to select Natsuki for instance I'd need Monika's response written in both labels wouldn't I?
Having the same response twice is inefficient.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
