### ISSUE TITLE
[Suggestion] Interactive music

### ISSUE THREAD

**Issue by ViruSSofTer** [Monika-After-Story/MonikaModDev#3103]
Here are some suggestions for the musical part of the game.

1. Monika remembers some of users`s most often played in-game tracks, let`s say, three most preferred ones, and all that forms a small rating list.

2. Monika may sometimes make a comment on the chosen music. The comment may be exclusive for the base tracks and general for customs.

3. If the same track plays for too long/nothing is played for too long then Monika suggests to switch/turn on the music. If user agrees - she turns on the track from the preferred ones from suggestion 1. The chance depends on the rating list.

4. Custom music recognition. This is VERY optional and low-priority but may be interesting. Monika may recognize custom tracks from the name by checking some keywords and comment on that too.

**Comment by SaiPrithvi123** [comment]
>Monika may sometimes make a comment on the chosen music. The comment may be exclusive for the base tracks and general for customs.

There used to be a time where Monika did comment on currently playing music, before they added custom music. I wonder why they removed that feature.

>Custom music recognition. This is VERY optional and low-priority but may be interesting. Monika may recognize custom tracks from the name by checking some keywords and comment on that too

The player would easily be able to fool Monika by renaming the song into a different one. Besides there are a lot of songs you'll have to dig through the internet to find.

**Comment by multimokia** [comment]
Feature was removed because when custom music was added, there was no dialogue for it. The dialogue for that isn't too easy to write because of how open ended it is for custom music, since there's no way to really tell what genre a song belongs to (without reading tags, but then not all songs have tags on them)

**Comment by multimokia** [comment]
Problem is, she thought custom music was silence. And said the silence dialogue instead, so it needed a bit of reworking. Was also low priority, so I figure they just took it out in the meantime

**Comment by SaiPrithvi123** [comment]
Then it might've been worth it. Sometimes the simplest changes are really complex under the hood.

**Comment by ThePotatoGuy** [comment]
1. as far as i know, there's no way to get notified if a song repeats, so we'd only be able to add counts on startup/song switch
2. yeah theres that one topic that had it, as discussed in the comments, would need handling for custom music
3. I actually mentioned redoing #3093 so it will change music, so that could cover this maybe
4. maybe.

Anything regarding music is low priority since the current system works well and is reliable.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
