### ISSUE TITLE
[Typo]-Apologizing

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3122]
![typo mas](https://user-images.githubusercontent.com/38837456/49000276-55e11d80-f159-11e8-9715-da8f09301add.PNG)
I don't know if this has been pointed out, but there is a "!" and a "." right next to each others. This apologies was for a crash  if that can help you.

**Comment by niktekusho** [comment]
I was looking lazily at the "Projects" dashboard here in Github and noticed this issue. I think this can/should be closed since @multimokia fixed in #3228 (which landed in v0.8.11 if I did my homework right).

### Screenshot for proof (v0.8.14):

<img width="1030" alt="fix-3122" src="https://user-images.githubusercontent.com/18280135/51079246-2912a680-16c4-11e9-9155-dec7734e10f5.png">

#### 1. No Monika was hurt during the capture of the screenshot (I used the dev console to set up for the case) 😊💚

#### 2. Sorry for the enormous screenshot... 😥

**Comment by multimokia** [comment]
(Thanks for that)
