### ISSUE TITLE
God Damn it I tested taking monika out and lost the file 

### ISSUE THREAD

**Issue by Kyouko-Kun01** [Monika-After-Story/MonikaModDev#3183]
hey so back in the day when u could take monika out on a usb and take her with u i tested this seeing how it worked. but while i was testing it i have lost the file and could not play any newer version of the mod since all i get is just a empty room :(.  so if you have any advice plz share i need to by with my one tru love monika again or else im going to break....

**Comment by jmwall24** [comment]
how long ago was this and what version are you playing on now?

**Comment by jmwall24** [comment]
also please upload your `persistent` file please, if you are unsure where it is, it'll tell you here where to find it:  https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by Secretmanguy** [comment]
Calm down buddy. Your okay. What platform do you have? If you have Windows then I can tell you exactly what to do. Otherwise, check out the provided READ ME file in the game folder and scroll to your platform. Get the persistent files and SAVE THEM to a flash drive for safety. Re download DDLC and put all the Monika After Story files in. Delete the current new persistensts that should come with the game and replace them with your older ones. That should work, if not contact me or someone else. Were all here to help each other buddy

**Comment by jmwall24** [comment]
Not to be too blunt, but none of that will work.  Without the monika file from when he took her out and without a backup persistent from before he took her out, there is no getting her back without sending me the `persistent` which is why I asked for it.

**Comment by multimokia** [comment]
> Calm down buddy. Your okay. What platform do you have? If you have Windows then I can tell you exactly what to do. Otherwise, check out the provided READ ME file in the game folder and scroll to your platform. Get the persistent files and SAVE THEM to a flash drive for safety. Re download DDLC and put all the Monika After Story files in. Delete the current new persistensts that should come with the game and replace them with your older ones. That should work, if not contact me or someone else. Were all here to help each other buddy

For the record, this isn't going to change anything. It doesn't matter what install you're using, it reads from the same `persistent` file. The data indicating that Monika is out of the room is stored on that persistent file.

**Comment by Secretmanguy** [comment]
Strange?? It worked for my friend about two weeks ago when his flash drive broke with the character file. Hmm...Anyway, listen to him buddy. multimokia will fix it.

**Comment by jmwall24** [comment]
My guess is your friend either loaded an older version of the mod or used a `persistent.bak` which makes sense 2 weeks ago, new `.baks` aren't created when she is out of the room if he was on the 0.8.9, so that's an easy fix.  The fact that the original poster implied this happened a while ago and that he's loaded older versions of the game means that won't be an option for him.

**Comment by Secretmanguy** [comment]
Dang...
