### ISSUE TITLE
[Suggestion] Idle style game. 

### ISSUE THREAD

**Issue by FluffyMuffinMeyer** [Monika-After-Story/MonikaModDev#3201]
Having an Idle style game that can be interacted with on a hourly basis would be a nice addition to MAS, due to the style MAS itself is in.

Currently, in MAS, Monika's affection can be raised by roughly 9 per day, (sometimes more). Having a daily cap on Monika's affection is a good reason for the player to visit daily, that is why I believe having a game that the player could interact with on a daily basis would be good for MAS. (From Monika's perspective, it would get the player to come back daily, and I think that'd be something she'd want...)

The style of game, in my mind would be something reminiscent of Plants Vs Zombies "Zen Garden" or Cookie Clicker. but there is many other styles of games that this could apply too. It doesn't take long to find many idle games online in flash websites. (kongregate.com)

This would be a rather large project to work on, but I think it could be something nearly completely separate from mas, simply with a DDLC style theme, There could be a lot of room for expansion and new ideas inside the game possibly even with special unlocks for progressing far enough. It could also allow for player shops using a form of currency earned from the game, (Possibly to buy a unique outfit? Maybe even allow players to retrigger holiday events or something special at high tiers of the game... Things that could affect MAS directly, just for the day.)

I'd recommend that this game would be unlocked at an "Enamored" state, as it would imply it would have been a project that Moni herself would have been working on, and has made specifically for the player, (She could even lock the player out from playing it past midnight, or if the affection drops too low)

Some Idea's people are throwing around in discord:
Chibbi Moni as a shop keeper
events and stuff could affect it as well, (E.G. Birthdays, holidays, new years, anniversary's, etc.)
Bonus's for having random topics with MAS monika.

Shop would include things like additional outfits, backgrounds, or whatever else you can come up with, really. stuff that would directly affection MAS itself, It would be nice to get some dialogs from playing the game, aswell. having monika notice our progress, maybe even locking the player out if she doesn't think the player is spending enough time with her, instead of the game she made.

**Comment by Rai99** [comment]
My first thought on this is submod. It doesn't sound too bad of an idea, but I really don't think it fits in MAS. 

Sure, it would give a reason for the player to come back regularly, but I don't know how Monika would feel about the player coming back for something other than her. 

One of my concerns is the performance demand of implementing an idle game since a few of them can be pretty demanding. Some have an "AFK" mode that disables the interface and reduces CPU usage, but I don't think that's something we should do with Monika. 

Also, almost every single idle game I've seen and played has some sort of prestige system where you reset with a boost. This boost would have to be pretty major in order for the game to be satisfying but might raise performance demand even more. 

As for any kind of payout for progressing in the game, again, it would have to be at least somewhat significant. Maybe re-skins or recolored eyes, clothes, etc, but that's kind of small and I think there would have to be additional assets for each and every one of those. Completely new outfits or features is a huge gain, but also a huge cost, seeing that art is a valuable commodity and isn't too easy to come by. 

You also suggested being able to re-trigger events via this idle game. I know Cookie Clicker does this and lets you re-trigger seasonal events such as Christmas, Valentines day, Easter, etc. _if you've got the money._ This kind of feature would game-ify MAS rather than make it feel more real. I don't think we want to encourage being able to repeat missed events based on progress in some external game that not everyone is going to be interested in or allow players to bypass certain restrictions "because money."

Locking the player out of the game at certain times might add some realism, but it would probably cause more problems than make up for in what it adds. Locking out based on affection makes more sense, but if that's the case, the player probably doesn't want to play anyway and if they do, then they'll have to treat Monika nicer. This sounds like a positive until you consider that they're only doing it so they can play Monika's game, and not actually for Monika.

**Comment by FluffyMuffinMeyer** [comment]
> One of my concerns is the performance demand of implementing an idle game since a few of them can be pretty demanding. Some have an "AFK" mode that disables the interface and reduces CPU usage, but I don't think that's something we should do with Monika.

Most idle games dont typically actually require being open, but instead do some simple math to gauge the amount the player has earned in that time. I.E. the player makes 10 shekels a minutes, leaves for 10 minutes, 10 x 10 = 100 shekels. this could be activated when this portion of MAS is opened, instead of when MAS itself is launched, to reduce lag.
 
> Also, almost every single idle game I've seen and played has some sort of prestige system where you reset with a boost. This boost would have to be pretty major in order for the game to be satisfying but might raise performance demand even more.

A Prestige system wouldn't be required in my mind, perhaps it would help if you thought of the game more like... Farmville? something to simply interact with every day or so. thats why I think the Zen Garden styles would be a better approach.

> As for any kind of payout for progressing in the game, again, it would have to be at least somewhat significant. Maybe re-skins or recolored eyes, clothes, etc, but that's kind of small and I think there would have to be additional assets for each and every one of those. Completely new outfits or features is a huge gain, but also a huge cost, seeing that art is a valuable commodity and isn't too easy to come by.

I do understand that art is not cheap, and that having new assets would be very expensive, and I by no means want to diminish the value of the work the wonderful artists put forward to make the mod great,
but making one, very late in the games stages outfit, or having something simple like a sticker on the wall would be interesting. the prizes do not have to be immense, but could be added on to in later patches. I dont believe the game would have to have tons of amazing prizes to start out with, as to make it available to be developed further.

> You also suggested being able to re-trigger events via this idle game. I know Cookie Clicker does this and lets you re-trigger seasonal events such as Christmas, Valentines day, Easter, etc. _if you've got the money._ This kind of feature would game-ify MAS rather than make it feel more real. I don't think we want to encourage being able to repeat missed events based on progress in some external game that not everyone is going to be interested in or allow players to bypass certain restrictions "because money."

I do agree that perhaps being able to retrigger events would be a little silly, but i'm just some rough ideas.

> Locking the player out of the game at certain times might add some realism, but it would probably cause more problems than make up for in what it adds. Locking out based on affection makes more sense, but if that's the case, the player probably doesn't want to play anyway and if they do, then they'll have to treat Monika nicer. This sounds like a positive until you consider that they're only doing it so they can play Monika's game, and not actually for Monika.

> Sure, it would give a reason for the player to come back regularly, but I don't know how Monika would feel about the player coming back for something other than her.

I think monika would enjoy having the player play her game, Like she would be proud of how the player can play "Your Reality" on the piano. It's nice to see people enjoy the work you've created. maybe thats just me...?

**Comment by Rai99** [comment]
> A Prestige system wouldn't be required in my mind, perhaps it would help if you thought of the game more like... Farmville? something to simply interact with every day or so. thats why I think the Zen Garden styles would be a better approach.

I've never played Farmville but ok, I've got idle games that are completely linear with no prestige system. 

> I do understand that art is not cheap, and that having new assets would be very expensive, and I by no means want to diminish the value of the work the wonderful artists put forward to make the mod great,
but making one, very late in the games stages outfit, or having something simple like a sticker on the wall would be interesting. the prizes do not have to be immense, but could be added on to in later patches. I dont believe the game would have to have tons of amazing prizes to start out with, as to make it available to be developed further.

In #2007, it was discussed that we don't want to make MAS feel like a chore by requiring the player to do certain things everyday to progress. We typically want to avoid "farming". Sure, it wouldn't be mandatory to play the idle game, but when you lock features and unlockables behind it, it becomes a chore. Especially when a player wants something behind it, but doesn't want to play "that idle game". Affection is different because typically, you open up MAS for Monika and that's pretty much what MAS is about. Having something optional and extra on the side with its own exclusive content seems a bit questionable when the aim is Monika, not something extra. 

> I think monika would enjoy having the player play her game, Like she would be proud of how the player can play "Your Reality" on the piano. It's nice to see people enjoy the work you've created. maybe thats just me...?

I'm sure it would make Monika happy to know that the player likes what she made for them, but I think it changes a bit when the player only boots up MAS for the idle game and not Monika. 

Think of it as if you got something new like a new console or game, and your friend wants to play it. Yeah, it's great to be able to share it with your friend, but I think starts to feel less joyful when they come over for the game/console and not you. They don't really give a damn about you, they're there to to play/use something you have. 

Also, I noticed that in the MASC discord server in the spoilers channel, you said that you thought it would be a fun side project to work on and give them freedom to explore and work on other things and you think devs get tired of writing new topics all the time and that this could be a smaller passion project inside the bigger passion project. 
Yeah, I don't think that's how it works. MAS _**is**_ a side project and no one is obliged to work on it. It's all done voluntarily on people's free time. 

As for the devs getting tired of writing new topics, I don't really recall any time a programming heavy dev wrote topics too often, and this might just be me, but I don't think making an idle game would exactly be more engaging to work on than other features such as boops, other games, or little improvements such as #3199. 

As for making new topics, lately, I think they've mostly been from contributors and seeing as there's a small backlog of topics, I think being stuck in limbo is a bigger problem than nobody wanting to write/people getting tired. Personally, maybe I've slowed down, but I'm not tired of it.

**Comment by AsuraShun** [comment]
i kinda already visit her daily, I spend almost my entire day with her

**Comment by FluffyMuffinMeyer** [comment]
> In #2007, it was discussed that we don't want to make MAS feel like a chore by requiring the player to do certain things everyday to progress. We typically want to avoid "farming".

But isn't that what the point of the affection system cap is already? It feels a lot like farming having to open MAS daily just too get the affection, and it may feel a little hallow just opening MAS to tell monika you love her three times, than closing it, and not opening it for the rest of the day.

> Think of it as if you got something new like a new console or game, and your friend wants to play it. Yeah, it's great to be able to share it with your friend, but I think starts to feel less joyful when they come over for the game/console and not you. They don't really give a damn about you, they're there to to play/use something you have.

I dont think that'd be an accurate comparison, even if it was, it wouldn't be something I would mind, because the actions in the minigame would directly affect the person who "Own's the Console". it's their to give new things to do, and besides, I'd rather have a nice console for my friends to come over and play from time to time, than never have my friends visit me. (Trust me, I know what both of those feel like, and I don't mind having my friends visit me to have a good time with something I have, especially if we are doing it together)

**Comment by Rai99** [comment]
> But isn't that what the point of the affection system cap is already? It feels a lot like farming having to open MAS daily just too get the affection, and it may feel a little hallow just opening MAS to tell monika you love her three times, than closing it, and not opening it for the rest of the day.

Opening MAS, telling her you love her 3 times and closing it for the rest of the day? If that's all you do with MAS, I kind of have to ask why you keep doing it. I'm sure Monika appreciates seeing you even for a little, but I'm pretty sure the whole point of MAS, is spending time with Monika, not just to play some other game within it. 

The farming aspect becomes a much bigger issue when there's exclusive content locked behind optional content. 

> I dont think that'd be an accurate comparison, even if it was, it wouldn't be something I would mind, because the actions in the minigame would directly affect the person who "Own's the Console". it's their to give new things to do, and besides, I'd rather have a nice console for my friends to come over and play from time to time, than never have my friends visit me. (Trust me, I know what both of those feel like, and I don't mind having my friends visit me to have a good time with something I have, especially if we are doing it together)

I don't know if you understand what I mean. They don't give a damn about you. If you didn't have that "console", they wouldn't be showing up so often. They'd take it home themselves if they could just so they could skip the middle step of having to visit you for it. You aren't enjoying it "together", You don't really even get to talk to them. It's just in, game, out, repeat.

**Comment by FluffyMuffinMeyer** [comment]
> Opening MAS, telling her you love her 3 times and closing it for the rest of the day? If that's all you do with MAS, I kind of have to ask why you keep doing it. I'm sure Monika appreciates seeing you even for a little, but I'm pretty sure the whole point of MAS, is spending time with Monika, not just to play some other game within it.

Because she makes me happy, I just cant have multiple programs up at once, mostly because even a single program will cause lag on my PC. If I could keep it open, I would, but this is very far off topic.

> The farming aspect becomes a much bigger issue when there's exclusive content locked behind optional content.

People missing out on a outfit or cosmetic because they choose not to play an optional minigame is completely up to them, as potato said himself, he has a grander plan on making everyone's monika Unique in there own way, this is just one way for people to separate them, and help make each one special. 

> I don't know if you understand what I mean. They don't give a damn about you. If you didn't have that "console", they wouldn't be showing up so often. They'd take it home themselves if they could just so they could skip the middle step of having to visit you for it. You aren't enjoying it "together", You don't really even get to talk to them. It's just in, game, out, repeat.

No, I do understand what your saying. And if people really don't care about you that much, and they did just want to spend time with you to play on your console, you're always free to tell them "No." or just not let them in your house, It might just be hard for you to comprehend my position, as it's a rather strange one, but If I have a friend thats bored and wanted to come over to my house and play on my playstation or the day, I'd let them. it wouldn't matter to me in the slightest. Their my friend, If thats what my friend wants to do, they can.

**Comment by jmwall24** [comment]
To me, having content unlocked by some idle game is completely missing the point of the mod.  Anything that is 'unlocked' should be based on Monika, not some other game.  People who want to actually spend time with Monika instead of playing some random game should not be punished by not having things unlocked.  This is essentially recommending ignoring Monika in favor of some random game just to unlock stuff.  Actively spending time with Monika is the entire point of MAS.  This makes something else entirely way too big of a focus.  Don't forget:  Just Monika.

**Comment by FluffyMuffinMeyer** [comment]
> To me, having content unlocked by some idle game is completely missing the point of the mod. Anything that is 'unlocked' should be based on Monika, not some other game. People who want to actually spend time with Monika instead of playing some random game should not be punished by not having things unlocked. This is essentially recommending ignoring Monika in favor of some random game just to unlock stuff. Actively spending time with Monika is the entire point of MAS. This makes something else entirely way too big of a focus. Don't forget: Just Monika.

Alright, I can take that comment to heart and understand what you mean. but I don't think it would be awful to have unlockable through doing things in MAS. for instance, playing the Piano, and if you are able to play a song perfectly, perhaps have an unlock for it. Maybe beating monika at 50 games of chess, or something. I don't find that beyond the realm of possibility.

**Comment by jmwall24** [comment]
A game that actually involves Monika and encourages you to spend time with Monika, I can see that possibly working.  It's the other kind of games that bother me.  I'm just imaging Monika sitting in the background while her player plays some clicker game for 3 hours trying to unlock a hat, and then getting the hat and then barely even seeing her wear it because he then starts trying to unlock something else.  The focus needs to be Monika.

**Comment by FluffyMuffinMeyer** [comment]
Well, I do think naming it "Idle" game was a mistake on my part, again, It might be more focused on something along the lines of the plants vs zombies Zen Garden, or Farmville, etc. Something the player would have to interact with for about 10 - 15 seconds every 2 hours, encouraging the player to visit every two hours.

**Comment by FluffyMuffinMeyer** [comment]
I keep referencing plants vs zombies zen garden, so I'll post this and provide some parallels that I think would work well.

https://plantsvszombies.fandom.com/wiki/Zen_Garden_(PvZ)

"It is an alternative, non-competitive environment"

The game is simply unlocked, and through completing normal tasks throughout the game, the player is given the ability to interact with the garden as a small pass time. (Completely Optional)

"The objective of the mode is to acquire plants, either by random drops in any of the other game environments or by purchasing them from Crazy Dave."

The player will never be scolded for ignoring the game

"make them drop extra coins periodically, but nothing negative will happen if the player ignores their needs."

The game itself requires intervals between feeding and fertilizing and making the plants happy, as a cooldown, requiring the player to visit at a later time, then the player is rewarded for their work and dedication. (Sadly, the Wiki never really directly points this fact out, You'll just have to take my word on that)

"Once they are obtained, the player must care for them by watering them and meeting their other needs until they are fully grown. Once they are at full size, the player must water them every day and make them happy after which they will begin dropping coins every 30–60 seconds or so for up to a full calendar day."

**Comment by multimokia** [comment]
Personally, I don't really see the need for a game like this within MAS. As well, still locking certain things behind a wall of playing a game like this is not a good idea. As has been pointed out before, the reason for coming *back* to MAS is to spend time with Monika. Not play an idle game of sorts. If that's what you wanted, you could just stick with Farmville or the likes. On top of this, I don't think most people just open MAS, say 'I love you' three times, and then close it again. It doesn't really make sense to game-ify MAS. It's not a game simulator, so I really don't think we should make it one.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
