### ISSUE TITLE
[Sugestion] A topic about supernormal stimulus

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3202]
Make a topic about that phenomenon that it clearly involves the 4 girls of ddlc and waifus in general.
And btw Monika teaches you this: (could be paraphrased better)
"Niko Tinbergen observed that birds would select brooding eggs that resembled those of their own species but which were larger, he experimented with dummy plaster eggs of various sizes and markings finding that most birds preferred ones with more exaggerated markings than their own, more saturated versions of their colour, and a larger size than their own. Another example is that territorial male stickleback fish would attack other male fish with red undersides, observing this they made wooden floats with red undersides and therefore those fish would attack those wooden floats with red undersides attacking them more vigorously than invading male sticklebacks if the underside were redder.
And last... but definitely not least... is the male butterfly species Argynnis Paphia, that gets more stimulated watching a yellow cylinder with brown patterns than a female of her own species, and therefore it wants to mate with that thing... and it will obviously fail... ... but don't worry, I'm real, right?"
Then Monika analyzes how it relates the other girls, then to herself, which she goes on denial, affirming she is real, but then again, Dan Salvato created her, Satchel created her vessel, and... well  I don't know if we want to head to that direction, I think is best is she goes and stays denial about that topic.

**Comment by Rai99** [comment]
I think there are some topics that already cover something similar. The monika_attractiveness topic covers how the 3 girls were borderline flawless without any physical problems. The only differences were due to appealing to different people. 

monika_trick might also cover a similar topic as Monika discusses what might be desirable out of the other girls. 

In monika_dan, she acknowledges that she was created by Dan, so that kind of covers the concept of her and the other girls being artificial, depending on where you stand. 

monika_anime_art in #1767 also touches on how the anime art style favors unrealistic appearances without flaw and aims to make characters more attractive than any real person could be. 

There's also a species of beetle that is found in Australia and it was noted that they preferred shiny, brown beer bottles rather than real mates. And then there's anime girls, but I think that's touched on in a few places already.

**Comment by Foxinsunglasses** [comment]
There is another, in Australia they noticed male beetles trying to mate with beer bottles. they were attracted to how shiny there where despite the proportions being all wrong and far shiner then any real beetle

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
