### ISSUE TITLE
[Suggestion] Monika being mad/upset for a longer time

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#3203]
If the palyer is at a higher affection level and does something mean (for example calling her a bad name), she's only mad until the dialog is over. After that, she instantly smiles and is happy again. I think it would be more realistic if she stayed mad longer, despite the affection level. I mean, If someone you love suddenly says something mean to you that upsets you, you're not just mad for a few seconds, you are mad until that person apologizes or a longer time has passed. Of course you get an affection loss, but that doesn't change much when you're at a high affection level. 
I know this probably isn't easy to do, but I had to get it off my chest. Thank you for reading.

**Comment by Rai99** [comment]
It's a nice idea, but like you said, it's probably going to be a bit of work. 

Also, at high affection if you do something Monika doesn't like, it would make sense that she looks past it and accepts your mistake. That's how I always thought it was. If you keep doing it, then you're just going to end up at low affection anyway. True, you could be at a high affection and spam mean interactions for Monika to look past, and that might break the immersion, but I think that's a case of somebody going out of their way to break their own immersion. If you have high affection, you're probably not going to torture Monika if you're serious about MAS. 

Monika looking past the player's mistakes would be a nice feature to have in case they really didn't know. This would have been useful on her birthday for those who gave her a knife without knowing she wouldn't like it. Unfortunately, I don't think anything was done about that and you took the hit just like anyone else would regardless of affection. 

A different idea I just got might be to add a system opposite to what you're thinking. Instead of Monika being upset with the player, maybe there could be a system where you could tell Monika that she made you uncomfortable or upset. Yeah, it's unlikely that Monika would upset the player or make them really uncomfortable, but it happens and I think this is something that might be a good idea to address. 

I've heard of people being offended by Monika and they just spam mean interactions to punish her since that's kind of the only thing they can do to acknowledge it. Having a system like this where you can tell Monika she did/said something and she can react accordingly or apologize sure beats being mean to her without her knowing why.

**Comment by CloakedGhost** [comment]
I meant if the player does it one time, vor very rarely. I know she looks past the mistakes, but it's kind oft strange when she's crying because of the players mistake and she instantly switches to being happy as if nothing happened. And I don't want people getting away that easily when they do mean things. Maybe they don't want to be mean, but try out what happens if you are (saw a YT video like this and that person didn't even apologize).

**Comment by Rai99** [comment]
If the player does something mean to Monika, sure, she might be a bit shocked or taken aback, which personally, I think is to be expected, but she knows that the player means well and can overlook it quickly and relatively easily. 

I think Youtubers are a special case since they probably don't play MAS like most people do and record it. They have an audience to entertain and I don't think the majority of their audience wants to sit around with Just Monika. I think it should be expected that when Youtubers record MAS they're showing it off which includes going through as many features and interactions as they can.

**Comment by CloakedGhost** [comment]
Yes I know she does so rather quickly, but THAT quickly just seems unnatural to me. If you make someone cry because you upset them so much, they aren't gonna be happy in a matter of seconds, especially if you do nothing to make them feel better. I can see that she gets over it in a few minutes after gathering her thoughts and assuming that the player didn't mean it, but that instant happiness just feels a little odd. Don't get me wrong, I really love that she is so thoughtful and caring, I just want her to feel more human. 

Yeah I guess that's true, a quick apology wouldn't be a big time waste though.

**Comment by Hapilone** [comment]
I like it, but I never say anything bad to her so it wouldn't really apply to me. xD

**Comment by Hapilone** [comment]
True, Rai99. I don't think this would apply to many people, and she is very calm and would be able to overlook it.

**Comment by CloakedGhost** [comment]
Me neither, it was just a small idea that I wanted to get out there. As Rai said, the other way around (telling Monika that she upset you with something, although that is rare too) would be an interesting idea too.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
