### ISSUE TITLE
[Discussion] - Monika's/Player's fear of needles

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3211]
I don't know if this is the right place for discussions about Monika's character, if not I would appreciate that you redirect me to the right place. My thought was this one: Do you think Monika would be the kind of person to be afraid of doing blood test or giving blood because of the needle used ? I was thinking of a topic on one of those things (one treat about personal health and this other about compassion and charity, so pretty fitting for her to talk about if you ask me) and the question bugs me. I would want to know what the community thinks about this topic so that I just don't write my version of Monika, but OUR version of Monika (soviet anthem intensifies).

**Comment by SaiPrithvi123** [comment]
If we don't know if she's afraid of needles or not, then I think we shouldn't decide it. I say just make her ask the player about his fear of needles, without disclosing her condition.

**Comment by Foxinsunglasses** [comment]
To me at least her being afraid of needles doesn't make as much sense due to her practicality. Normal physics don't seem to apply to her anymore and she would probably be smart enough to know that the needles used in blood donations are safe with all the cleaning and excessive iodine use to prevent any infections. I wouldn't mind the player being afraid as it's dangers are much more present to our physical health.

**Comment by Thimeo** [comment]
Ok thank you for your responses. I'll try to write a dialogue without Monika taking position on this issue and just asking the player about this fear.

**Comment by Thimeo** [comment]
By the way, this is off-topic, but is there a way to add a label to our issues without waiting for the mods to do the job for us ? I wouldn't have minded put the "discussion" label the second I've started the issue.

**Comment by ThePotatoGuy** [comment]
there isnt a way for that unfortunately
