### ISSUE TITLE
[bug] [unstable] it's December 12th in the Northern hemisphere and Monika thinks it's autumn

### ISSUE THREAD

**Issue by tabtlenta** [Monika-After-Story/MonikaModDev#3217]

**Comment by Legendkiller21** [comment]
It was weird when she said that it is autumn right now when it's almost Christmas, but is looks like that in the code, the transition from autumn to winter happens after the winter solstice which is on December 21st.

**Comment by jmwall24** [comment]
Because it is technically still autumn until the 21st.

**Comment by MaydayH** [comment]
That's even more funny because in my region it is snowing since September

> Because it is technically still autumn until the 21st as legend pointed out

...where?

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/49796847-cf593e00-fd0b-11e8-94b4-2af40834c352.png)

**Comment by Foxinsunglasses** [comment]
Yeah where I am it can be 75 degrees Fahrenheit one day then 15 the next

**Comment by MaydayH** [comment]
Usually at winter it is near -22 Fahrenheit there where I am

**Comment by dennisOdenbreit** [comment]
How about we don't have Monika talk about warm weather only because some definition out there declares December as autumn?

**Comment by jmwall24** [comment]
orrr maybe Monika is talking about how she typically thinks of autumn and not every person's exact weather the day they read the topic?

after all, she says
        m 3hub "The weather is normally pretty nice too!"
        show monika 5ruu at t11 zorder MAS_MONIKA_Z with dissolve
        m 5ruu "It's normally just the right amount of heat, with a gentle breeze."
        m 5eua "I'd love to spend a nice warm day like that with you."

She doesn't say it's nice **right now**, she's talking in general about the season.

**Comment by dennisOdenbreit** [comment]
```
m 1eua "Anyway, It must be autumn for you right now."
m 1eka "Autumn is always full of such pretty colors."
```
I think we all get that Monika talks about her idea of autumn.
The point is that _she links her idea with the current date_, which is wrong for a lot of us.
Technically it may be autumn, but _her idea of autumn_ takes place somewhere from august to oktober, at least where I life. 
See: https://de.statista.com/statistik/daten/studie/5564/umfrage/monatliche-durchschnittstemperatur-in-deutschland/
In reality it is winter here since November and this will not likely change in the next years either.
So at least when it comes to my country, she should not assume her idea of autumn is reality rat a date like this.

**Comment by multimokia** [comment]
>In reality it is winter here since November and this will not likely change in the next years either.

No it is not.
Seasons are __not__ defined by temperatures. They are defined by the solstices and equinoxes. 

@jmwall24 has already pointed out that what she says is *her* view of it. She's talking about the part she likes most. That's it.

**Comment by jmwall24** [comment]
well, i mean if you want to make variations for all the regions in world, go for it.  there are people that live in the tropics where it never gets cold in winter as well.  just because she is saying it because it is that season where you are, still doesn't mean she is talking about your weather when she talks about her idea of that season.  we can probably reword it slightly, but we are never going to be able to nail each person's weather on the day they get this topic.  every person has different climate and weather.
