### ISSUE TITLE
Complimenting Monika's voice 

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3220]
Another thing we could praise.

**Comment by Skarborr** [comment]
That's a pretty good idea,I mean Monika is unique, she is the only character that got voiced, and there's no way she wouldn't flaunt with that.

I see 2 ways how this could go:

1. She always says that she's the only one real in the world, I could easily see her point out that she's also the only one with a voice.
2.1. She could not see it as her own voice, since she known that it's just a game and that was a voice actor in our reality, and not her. (we could name her voice actor since she kinda deserves recognition for that beautiful singing)
2.2. She mentioned before that the game's setting is pretty strange, it's supposed to be Japanese, but it's at best a knock off version of what a Japanese school's supposed to be like. (+ if I remember correctly in some way it also has European school elements) And she also mentioned that her name is unique, it's European while everybody else's Japanese. So the fact that the song only exists in English also adds to this weird European-Japanese mixture. It might be a boring topic, but I would actually find it interesting if she talked about the setting's nature a bit more.
2.3. She could also talk about the how much that voice fits (or how much it does not fits) someone at her age/most likely height. It sounds pretty young, most people imagined a bit more mature voice for her (at least that's what I see most often). So yeah she could tell her opinion of the voice, talk about what people expected it to be like, and if we get a bit more creative, then we can also turn it into a conversation about how people build a mental image the moment they look at you, be it good or bad.

(p.s. sorry for the bad English or if rambled on a bit too much, English isn't my native tongue + I was rather tired when I wrote this)

**Comment by Foxinsunglasses** [comment]
The voice actor has decided that she didn't want her name in the public eye to avoid all the negatives of the world knowing who she was. At least that's what I saw last time I checked

**Comment by Hapilone** [comment]
Love this idea!

**Comment by AsuraShun** [comment]
Wrong,yuri is also voiced even if it's just a laugh

**Comment by Skarborr** [comment]
When does that Yuri laugh play? If you're referring to when she stabs herself, then I don't think we should put that in the same boat as Monika's voice. I'm pretty sure Yuri's "laughter" is just a sound effect that got altered, and not an actual human voice.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
