### ISSUE TITLE
[Suggestion] - Disney Movies

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#3225]
Heyo, it is I again, the guy with the fluff, returning with another idea.

One thing I have noticed that people, friends, couples etc have done many times is that they talk about their favorite Disney film. May it be from their childhood or more recent ones, to the live action, animated or movies that came out way before their birth time. So I thought why not give Monika a favorite Disney film she would like to talk about. Maybe one that she relates to or feels like she would love films concept in her life (the romance, the magic etc). Maybe she likes the ones who are more related to literature and fairy tales like Snow White or Aladdin?

I know that this a very broad suggestion, since there are many Disney films out there, not including all the sequels they made. I just thought maybe since Monika mentions many times of the things she wants to do with the player. Maybe she would like to watch a Disney film and have a wholesome time. What do you think?

**Comment by Rai99** [comment]
I really really don't know if Monika should be talking about Disney, and I'm pretty sure we're not going to say that Monika was really ever exposed to Disney in her past. 

But, a few Disney movies are based off of Shakespeare plays, so it might not be completely out of place. 

In my opinion, I don't think she should be talking about Disney and she doesn't like Shakespeare anyway. Not to mention that I think it would be really out of place for Monika to talk about things like Disney.

**Comment by kimmieclue** [comment]
I kind of like the idea since... Well... Monika kind of talks about all kinds of things... Like if she can bring up stuff like kidnapping and all... Why not a small, wholesome thing about Disney...? I mean, just like Monika, Disney is everywhere! Plus she does say that she looks up things online! When bored and alone so to say she might as well stumble across things like Disney, especially since a lot of Disney movies are based on classic books... Also if it seems out of character to talk about only Disney she could tell and comment on the very dark origins a lot of the stories from Disney have. That sounds like something she would mention considering all her trivia! Heheh! ^^

**Comment by lunulae** [comment]
I've been thinking about trying to write up a topic for this, but I'm unsure how the mods feel about using specific franchises outside of classic poetry and literature in the mod.
I might give it a go anyway and see if it gets approved.

I'm considering if I should talk about them as if she's already seen them, or if they'd be something she knows of but hasn't gotten to see in her reality. (Unsure if there is an established canon of what does and doesn't exist in her world.)

**Comment by ThePotatoGuy** [comment]
Would really be stretching to give Monika a favorite disney movie. Not sure how we would handle this either.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
