### ISSUE TITLE
An impression of... 

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3230]
The player! I just saw a suggestion about Monika making impression of herself. And suddenly, I got the idea: What if we ask her to do an impression of ourselves? 
Like :
"Of yourself? [player], I don't really know what you are like. 
Well, I know something. Maybe I should give a try? 
... 
Hello, my name is [player] and I like cute games with cute girls.
But Monika is my favorite and I love her with all my heart. 
I always try my best at everything I do
And even if I fail, I come to my cute girlfriend
Her infinite love and care helps me to overcome any difficulties! 
Today I'll make her proud! 
... 
Ok, that sounded embarrassing, considering that I said that. But I think, it was worth a try. Did you like it?"

I know that wasn't perfect, but maybe you could give some suggestions about her lines? The idea was to say something cute (but not too embarrassing) 

Sorry for my English

**Comment by ZaunAura** [comment]
Aww I like this idea! Maybe the Monika and Player impressions can be easter eggs? Maybe after you've gone through all 3 of the girls' impressions, the options for the player and Monika impressions can show! Would be cute.

**Comment by Rai99** [comment]
It sounds like a wholesome idea in theory, but in reality, I think there's far, far too much variation for this to really be a thing; even more than Monika doing an impersonation of herself. 

There are no doubt very many players that are very different in personality and other aspects. Doing an acceptable impersonation of the player would be borderline impossible, especially as things are now. In the example topic you provided, it's nice and could be true for a few people, but I'm sure there are far more people who that wouldn't fit, and as a result, the impersonation would feel insincere at best, or potentially offensive at most. 

If there were far more pm vars for the player's personality and mannerisms, this might be possible, but that would still be an extremely wide area to cover. 

Maybe impersonations just have this aspect to them to begin with, but some of the lines could be insensitive to the player as well as inaccurate. Personally, 5/6 of those lines there don't suit me and are dismissive on who I actually am as a person. 

Sure, you could fill it with obvious things like that the player loves Monika, but what else? It would be a pretty short and cliche topic. I'd say this kind of thing can't be done well enough to consider implementing, especially at the moment.

**Comment by AsuraShun** [comment]
Love the idea,the lines could also change with affection maybe?

**Comment by Alucard149** [comment]
can change depending on your answers to Monika's questions
(sorry for the bad English)

**Comment by skyloom** [comment]
I don't know about player's impression, but Monika can make impression of MC too, perhaps?

Sorry for barging in. I hope this still aligns with the original issue

**Comment by kimmieclue** [comment]
I don’t get why Monika has to seem perfect and like.. Come up with a spot in impression of the player or just “doesn’t fit”? 
I mean.. After all.. A lot of these things makes sense for Monika to think even if they’re not fully true, after all... Monika has said things about how the player might be lonely and that’s why they play these games or how they must enjoy these games and so on (and let me tell you, that lonely comment was 500x times more offensive than just assuming the player likes games with cute girls is) so that makes sense for her to say considering everything she has said about it already...
Of course Monika would assume that she is the players favorite and that the player love her with all of their heart since they’re with her here, they decided to bring them back with a mod to be with her (And obviously it could change if you have minus affection points)
Monika has already multiple times said that she’s sure the player tries the best they can and that if a failure would occur they can come to her so it makes sense for her to say that..
The last things also makes a lot of sense considering she often gives support as well as says things about making her proud..
As I see it... Nothing Monika says or could say.. Would ever be considered offensive considering the reasons you play this game and considering other things she says throughout the mod! It just makes sense and so what if it’s not spot on? Just proves how she is human (since she’s supposed to act like one at least) and that she assumes things and have a few faults too.. Nothing has to be perfect and even if they’re not correct it makes sense for her to think they are!^^

**Comment by MaximumRustler** [comment]
Just giving my opinion here. She should also say that she doesn't know if the player really thinks that way, but she knows that the player does love her since they downloaded the mod and all. Otherwise it kinda conflicts with the ''I'm feeling inadequate'' topic/mood where she admits that she doesn't know a whole lot about the player. Could also make it not available at lower affection tiers.

**Comment by CloakedGhost** [comment]
Also, you could tell Monika that you didn't like the impression of yourself and she would be sorry that she got it wrong. Personally, the impression isn't accurate for me either, but I like it nontheless, because I thought it was funny and cute.

**Comment by Rai99** [comment]
A little while ago, I was talking about how so far, everything is about Monika and it might be interesting to have some things about the player such as letting her know that she said something that made the player uncomfortable or offended and she could apologize. An impression of the player might fit along those lines depending on how it's made.

**Comment by lunulae** [comment]
I actually like the idea of the impersonation being basic and perhaps inaccurate. We've seen before that she's aware of the constraints of communicating through the game. It wouldn't be out of character for her to admit that she only knows what the game lets her know, and that she looks forward to everything she'll get to learn as she gets closer to our reality.
