### ISSUE TITLE
Why doesn't Monika ask me if I'm a vegetarian?

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3232]
Monika talked about being vegetarian and I was waiting for her to ask me if I was one. (I am vegan in fact.) But she never asked and i felt left out! Seems like an easy thing to add!

**Comment by PiperPC** [comment]
Yeah, Honestly I wonder if when someone says they're not vegan or vegetarian what she would say, for instance;
"Well [Player] as long as you're eating healthy, I don't mind what you eat!" Or
"As long as you take care of yourself [Player], I'm happy." Or maybe even like,
"Oh, ok [Player]. I guess as long as you are eating a balanced diet I can't complain!"

I mean they all portray the same message kind of, but with a bit of a different tone shift depending on her opinion on the matter. I feel like any of these could be her response considering throughout MAS she's been emphasising we look after ourselves to live as long as possible.

**Comment by PiperPC** [comment]
In addition when you say you are one of the two - Vegan or Vegetarian - She'd say something wholesome surrounding making a salad and eating healthy together.
(I'm not a vegan or vegetarian myself btw)

**Comment by MaximumRustler** [comment]
I'm not vegan or vegetarian, but I also think this would be a nice option to have. Actually the current dialog kinda fits if you said that you aren't, maybe add what PiperPC said before the last current line.

**Comment by ZaunAura** [comment]
If you haven't noticed yet devs, I'm down for MAS to be as interactive as possible. I feel like Monika spends a lot of time explaining stuff but some more interactions would be nice.

**Comment by dennisOdenbreit** [comment]
That's what I've been asking myself at least three times now since a month.

**Comment by dennisOdenbreit** [comment]
There are times where Monika actively asks you and other times where she just lazily assumes your answer instead of actually asking you.
While this may work sometimes, it would be nice to have her really ask you this question here.
Whenever the player has opinions that matter to him, Monika should actively listen to him.
I'd appreciate to get as far away from Monika's third act monologue as possible.

**Comment by PiperPC** [comment]
Going slightly off topic, I myself can't really eat most meats properly anymore. I went to a doctor about it and he said my body doesn't digest meat well (I usually bloat, throw up, and started losing muscle when the problems started showing up) and suggested I get on a vegetarian diet and instead take vitamins to remedy the issue, but also didn't want to recommend it too strongly. I'm also intolerant to the A1 milk.

Either way if I become a vegetarian, may it be on my own accord or to remedy my health issues, I would want to tell Monika about it so that she doesn't assume otherwise about me.

I guess that was a little TMI but I could relate a little and wanted to input a little more. XD

**Comment by ZaunAura** [comment]
@JumpinJehoshaphat and @dennisOdenbreit glad we're on the same page! sounds like u guys know what's best for monika; and if there were more persistent variables in the game that would be great. As I've said I have a bunch of free time to help code if need be.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
