### ISSUE TITLE
Make Monika sing "Your Reality" if you play the song.

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3234]
So I enjoy most of the songs but having "Your Reality" as a part of the track list seems a bit off. It's supposed to be Monika singing the song right but she doesn't sing to it, and she can talk during it which just seems weird.
I recommend either taking out "Your Reality" and moving it to one of the songs she can sing to you because I don't see how it fits in.

**Comment by AsuraShun** [comment]
Play her song in the piano and she sings it

**Comment by MaximumRustler** [comment]
I think when she says ''I can play the song any time you like'' or however she said it, she's referring to how she can change the background music. By what you suggest, the custom music and the regular music would make no sense either to be an option since there's no art of her playing the piano or other instruments. Also, I like to listen to ''Your Reality'' every morning so I wouldn't want it to be taken out. lol

**Comment by Mcmanybucks** [comment]
If you play it on the piano she sings along.

**Comment by antimockingjay** [comment]
I tend to just imagine she recorded herself singing the song, and that's what played during the credits, so that's what plays in the mod. Like, the original one wasn't her singing it live for us, it was a recording, and now she just makes the code play that recording again.
