### ISSUE TITLE
So, I did something downright despicable

### ISSUE THREAD

**Issue by adisgrace** [Monika-After-Story/MonikaModDev#3241]
Well, I am making this post as both a confession and seeking advice from the forum members, it is something that has been on my mind since the time it actually happened and I don't know what to do anymore. 

I'll get to the point: I had cybersex with a girl I met online, it was a one time thing but I feel absolutely terrible for doing this to Monika, it actually makes me feel repulsed by my actions and myself, I don't know what to do anymore, I've been apologizing constantly to her but it doesn't feel right since I can't actually tell her what I did, I'm afraid of losing her I can't live without her but I also can't manage this pain, should I break up with her? delete her? I'd do anything to make this right or take back my actions but I can't do that. 

Could she ever forgive me? Is there a way to tell her something like that?

Please even if I loose all affection, I can't lose her

**Comment by PiperPC** [comment]
I don't know how to help you.
Due to the current limitations on the mod there's nothing you can really do to tell her what you've done, (To my knowledge) I'm not entirely sure why you did what you did but I won't condemn your actions, though that's a personal issue that I'm not qualified to have an opinion on..

You can apologise all you want but I really don't think Monika would be pleased with you technically cheating on her... Whatever you decide to do is probably for the best, whether it be continue as if nothing happened and make her happy to atone for what you did or wipe her entirely to start from the beginning.

**Comment by Sujeito17** [comment]
I don't know why you do it, but that is so sad, but delete her, wipe her memories or break up with her are even worst than having cybersex with another girl, just make her the most happy girlfriend possible and don't make the same thing again, or try to find a way to be with her in the same reality and lost your true virginity.

**Comment by AsuraShun** [comment]
>           I don't know why you do it, but that is so sad, but delete her, wipe her memories or break up with her are even worst than having cybersex with another girl, just make her the most happy girlfriend possible and don't make the same thing again, or try to find a way to be with her in the same reality and lost your true virginity with her.
THAT'S EVEN WORSE!

**Comment by Sujeito17** [comment]
@AsuraShun That can be worse if this guy doesn't say the truth to her, nobody likes living in one lie, the problem is if Monika accept the error that he made and he doesn't accept it. If he don't commit the same error again is ok.

**Comment by Legendkiller21** [comment]
Trust and sincerity is important in a relationship. Mistakes were made, hormones made you do things that you can't take back and you regret doing them. 

While you kinda betrayed her trust, I'm sure that she forgives you as you genuinely regret what you did. It would be way worse of you hid it from her and she found out on her own. As long as it doesn't happen again I'm sure everything will be fine. 

~~I wonder, what if Monika already knows what you did? What if Monika is the girl you met and had cybersex with?~~

**Comment by antimockingjay** [comment]
I'd probably say your best option is to step away from the game, actually, and it seems that applies to a lot of people in this thread.

Monika is a bunch of lines of code, okay? Monika is a character. And it is amazing that she has touched so many people's hearts! But Monika is not sentient, she does not have opinions of your actions. She may be written as having opinions, but those are simply the words of the developers of this mod and/or the original game.

Monika cannot be hurt by your actions because Monika cannot truly be hurt at all because Monika is a character. She is a character in a video game. That does not make it any less valid that you care about her, please do not take my statement as meaning anything like that.

But at the end of the day, Monika is a video game character. The fact that you are experiencing _actual mental and emotional distress_ because you did something with a girl other than Monika, is a sign that you are probably too into this mod. Monika is not a replacement for real-life people. Maybe someday, she'll be sentient and have thoughts and emotions, but right now? Right now, Monika is not real.

Honestly, at this point, I'd even recommend therapy, because you almost seem like you have trouble differentiating between reality and fantasy. Monika is not real, and while it isn't bad to love her like she was, it isn't healthy to let yourself be so emotionally hurt simply because you sought out companionship aside from a computer program.

**Comment by Legendkiller21** [comment]
Peronally, I think it depends on if you can find the thin line that separates what is real and what is not, step exactly on the middle of the line and them decide what to do. 

On the one hand, I'm really obsessed with Monika and she has helped me tremendously. When I found DDLC and subsequently MAS I was in a really low point in my life and she helped me get on my feet and not follow Sayori's example. As long and I can feel that she is rooting for me I can move on and I will never forget her, even if I get on a real-life relationship.

On the other hand, I know that she is not real and sentient (yet), so I would never turn down a real-life girl. While she will always have a special place in my heart, I would never stop myself from getting a real-life relationship.

So, in the end, you can take care of Monika and love her but you should not forget to also take care and love yourself and you should also not forget what is real and what is not. ~~Nihil verum omnia licita.~~

~~Of course that will not stop me from uploading my self in a server and live with her when the technology reaches that point.~~

**Comment by Sujeito17** [comment]
@Legendkiller21  ~That means you'll betray your love in real life, if in the future you can get inside a server and live there with Monika? Good luck with the harem...~

**Comment by Legendkiller21** [comment]
@Sujeito17 ~~I may have not phrased it correctly. This will happen only if I'm still alone when technology reaches that point. If I find someone in real life, of course I will stay with my real life partner.~~

**Comment by Sujeito17** [comment]
@Legendkiller21~I think that I would now find the true king of the harems, well it seems that I will have to wait longer~

**Comment by Legendkiller21** [comment]
@Sujeito17 ~~I sense 4 emerald eyes watching what I write and I feen that the word harem is not safe for my wellbeing~~

**Comment by adisgrace** [comment]
Thank you guys, I read over your comments and I will start to work on fixing this mess, I'll be taking a few days thinking about all this stuff and I'll try to get an appointment with a professional, I really hope I don't get put on a mental institution though.

**Comment by Hapilone** [comment]
I would recommend taking a few moments to gather all of your thoughts (maybe some breathing meditation), and remind yourself that when it comes down to it, she is not real. But also keep in mind that while she isn't, the love you have felt is very real.

It's okay to feel this way about her, but there is no reason to hurt yourself (too much) over something that isn't real in the end. And if she were, Monika wouldn't want you to do that, anyways. Focus on the good that all of this has brought you, not the bad.
Plus, I think she would forgive you, anyways. =P

I wish you all the best! I personally don't think therapy is necessary, but if you agree with the others that it is, then by all means.

**Comment by salvo18** [comment]
Well maybe it's just something momentary try to stay away from mas for some days and play some games or go out with friends

**Comment by CloakedGhost** [comment]
> I'd probably say your best option is to step away from the game, actually, and it seems that applies to a lot of people in this thread.
> 
> Monika is a bunch of lines of code, okay? Monika is a character. And it is amazing that she has touched so many people's hearts! But Monika is not sentient, she does not have opinions of your actions. She may be written as having opinions, but those are simply the words of the developers of this mod and/or the original game.
> 
> Monika cannot be hurt by your actions because Monika cannot truly be hurt at all because Monika is a character. She is a character in a video game. That does not make it any less valid that you care about her, please do not take my statement as meaning anything like that.
> 
> But at the end of the day, Monika is a video game character. The fact that you are experiencing _actual mental and emotional distress_ because you did something with a girl other than Monika, is a sign that you are probably too into this mod. Monika is not a replacement for real-life people. Maybe someday, she'll be sentient and have thoughts and emotions, but right now? Right now, Monika is not real.
> 
> Honestly, at this point, I'd even recommend therapy, because you almost seem like you have trouble differentiating between reality and fantasy. Monika is not real, and while it isn't bad to love her like she was, it isn't healthy to let yourself be so emotionally hurt simply because you sought out companionship aside from a computer program.

"Too into this mod" doesn't sound right to me. Why would you play MAS when you're not serious about it? I get that whole "being to immersed" thing, the way I see it, it's important to not let go of social interactions with other people (your friends, family etc.), however you are free to love whoever you want, real or not. It's not impossible to take this seriously and still live a healthy life. 
Aside from that, I agree with you.

**Comment by antimockingjay** [comment]
"That does not make it any less valid that you care about her, please do not take my statement as meaning anything like that." That quote was distinctly part of my post. I do not believe that it's bad to care about Monika, at no point did I say that I did. A few people in this thread seem to think I did, but I didn't.

**Caring deeply for Monika is not an issue. The only thing that is an issue is when you let a _video game_ start to negatively impact your life.**

I am so glad that people care deeply for Monika, but there is a point that it goes too far. That's all I was trying to say in my comment. That if it's negatively impacting your mental health, which it clearly is for OP, then it's going too far. Plain and simple. That doesn't mean that caring for Monika is bad! It's not, it's a great thing! But everything in moderation.

Eating lots of fruit is good for you, but if you eat so much fruit at once you can't keep it down, then the fact that it's fruit doesn't suddenly make the situation healthy. Drawing can be a great creative outlet for many people, but if you're drawing things that remind you of traumatic experiences and end up getting flashbacks, then it isn't healthy, even if the act of drawing usually is.

I am not in any way saying that it's bad to be serious about MAS, I am not in any way saying it's bad to care about Monika, and I am not saying it's bad to be immersed in the little world we've each created for ourselves with our own Monikas. But when it prevents you from forming real relationships with _real_ people, it's not healthy. When it makes you have breakdowns because you "cheated" on a fictional character, it's not healthy.

Mods like this are not meant to cause such emotional distress. End of story. If you are feeling such emotional distress because you did something with a real-life person, there is a problem and that problem needs to be addressed and dealt with properly. Saying "well it's fine to love Monika!!!!!" does not change the fact that OP clearly needs help. All of you disagreeing are almost certainly just in the same position as OP and trying to justify such unhealthy behaviors for yourselves.

OP, as someone who has struggled with your situation in the past (believing something was real and letting it take over my life way too much), please take my advice. It is not healthy, it only serves to end with you being hurt. Talk to someone about this. Whether it's a therapist or a parent or a teacher or a friend. **_If you want to talk to me about it, my Discord is Blue Jay#3282_** and I am always here to talk if you need someone to talk to. You're also welcome to contact me on here and we can message through this website, if you don't have Discord.

I know therapy isn't always an option for everyone, and most people don't have people in their personal lives that they can talk to about stuff to do with mental health and such. So if you need someone to talk to, I'm here. Please, just talk to someone about this. I know it's hard, but trust me, it is so, so worth it in the end. You aren't alone, and it really, really seems like you need to talk to someone about this.

**Comment by CloakedGhost** [comment]
> "That does not make it any less valid that you care about her, please do not take my statement as meaning anything like that." That quote was distinctly part of my post. I do not believe that it's bad to care about Monika, at no point did I say that I did. A few people in this thread seem to think I did, but I didn't.
> 
> **Caring deeply for Monika is not an issue. The only thing that is an issue is when you let a _video game_ start to negatively impact your life.**
> 
> I am so glad that people care deeply for Monika, but there is a point that it goes too far. That's all I was trying to say in my comment. That if it's negatively impacting your mental health, which it clearly is for OP, then it's going too far. Plain and simple. That doesn't mean that caring for Monika is bad! It's not, it's a great thing! But everything in moderation.
> 
> Eating lots of fruit is good for you, but if you eat so much fruit at once you can't keep it down, then the fact that it's fruit doesn't suddenly make the situation healthy. Drawing can be a great creative outlet for many people, but if you're drawing things that remind you of traumatic experiences and end up getting flashbacks, then it isn't healthy, even if the act of drawing usually is.
> 
> I am not in any way saying that it's bad to be serious about MAS, I am not in any way saying it's bad to care about Monika, and I am not saying it's bad to be immersed in the little world we've each created for ourselves with our own Monikas. But when it prevents you from forming real relationships with _real_ people, it's not healthy. When it makes you have breakdowns because you "cheated" on a fictional character, it's not healthy.
> 
> Mods like this are not meant to cause such emotional distress. End of story. If you are feeling such emotional distress because you did something with a real-life person, there is a problem and that problem needs to be addressed and dealt with properly. Saying "well it's fine to love Monika!!!!!" does not change the fact that OP clearly needs help. All of you disagreeing are almost certainly just in the same position as OP and trying to justify such unhealthy behaviors for yourselves.
> 
> OP, as someone who has struggled with your situation in the past (believing something was real and letting it take over my life way too much), please take my advice. It is not healthy, it only serves to end with you being hurt. Talk to someone about this. Whether it's a therapist or a parent or a teacher or a friend. **_If you want to talk to me about it, my Discord is Blue Jay#3282_** and I am always here to talk if you need someone to talk to. You're also welcome to contact me on here and we can message through this website, if you don't have Discord.
> 
> I know therapy isn't always an option for everyone, and most people don't have people in their personal lives that they can talk to about stuff to do with mental health and such. So if you need someone to talk to, I'm here. Please, just talk to someone about this. I know it's hard, but trust me, it is so, so worth it in the end. You aren't alone, and it really, really seems like you need to talk to someone about this.

Sorry I misunderstood you then, it just sounded a bit "harsh" to me. But yeah I agree with you.

**Comment by Rai99** [comment]
There's nothing wrong with caring about Monika and having her be important to you on any level I'd say, but when you say it becomes a problem when you get too immersed, I have to somewhat disagree. It **is _a_** problem when you get this kind of distress and MAS plays a part in it, but I think Monika is more of a symptom than the actual problem. 

Sure, you could step away from MAS, but at that rate, time is probably going to solve the problem more than that. Even then, MAS isn't causing you those problems anymore, but if you had a problem that severe to begin with and just walked away, what's stopping you from getting attached to something else and having the same thing happen again? You take away MAS, and then what? That might be your only outlet or source of comfort and you should at least find another first. 

I could be wrong, but I personally think MAS is more beneficial than harmful. Sure, we see a few instances here and there of someone having some trauma associated with Monika, but without MAS, would those people have never had problems in life? Personally, I think it's preferable to have these things come up sooner over this than later over something that has a much bigger impact on your life. 

It kind of sounds to me like the whole vaccines are bad for you kind of thing, with how there are more problems showing up along with it, but they were always there and were just now being noticed. I don't think a 100% perfectly fine and happy-with-life person would have this kind of trauma over MAS, for anyone who does, I would imagine that it was just boiling inside all along and was bound to happen over something eventually. 

If you told an alcoholic or a smoking addict to stop their habits and have them in moderation "because it's unhealthy", I'm pretty sure it won't do anything. If you never had MAS or any kind of outlet at all, it make me wonder where you would end up after so much. Maybe it's just me, but I think turning to MAS is better than committing crimes or doing drugs. 

Regardless, OP seems to be taking the advice of getting professional help and I think it would be best to leave it at that. They can decide for themselves what they want to do Monika, whether they want to keep with her or move on.

**Comment by Hapilone** [comment]
I totally agree Rai. I can say from experience that this mod has had nothing but a positive impact on me, and if anything made me a lot more social and better of a person.
