### ISSUE TITLE
Gender-Specific topics

### ISSUE THREAD

**Issue by ericagoldfarb** [Monika-After-Story/MonikaModDev#3247]
When you're a girl and have told Monika when she asked you, it's very awkward when she talks about certain things like, to highlight a few, asking if I masturbate, have a lingerie fetish or look at lewd pictures of her. Maybe there should be some topics that are exclusive for guys, some that are exclusive for girls, and a few for non-binaries and the rest of the crew.

**Comment by ericagoldfarb** [comment]
I don't think that any girl has ever had a pantie fetish. At least, not in public. I mean, we kind of wear them on a daily basis, so it's hard to get obsessed with that kind of thing. The others I can understand, I guess.

**Comment by Rai99** [comment]
~~You never know. People can have all sorts of fetishes.~~

I would guess that maybe they could be attracted to other womens' panties since anyone could just go to the store and buy a fresh, clean pair, but there's not really any point to that.

**Comment by ericagoldfarb** [comment]
Well, I have nothing against a sexuality topic, but friend-zoning Monika after all she's been through would be really harsh. I think it would be assumed that any guy who downloads the mos is attracted to girls and any girl who gets it is attracted to girls, including my own pansexuality

**Comment by lunulae** [comment]
I mean, the fetish conversation doesn't assume you're into that--she talks about it just like "hey, it's really weird that some people like this thing." I think recently it was also added that she asks you during that topic if you do have any odd fetishes like that.
In terms of asking about masturbation or looking at pictures of her--I mean, I wouldn't assume that everybody who has this mod does those things, but I certainly know it's not a strict gender divide. :P 
I could really get behind an asexuality topic that removes or alters those topics though. This mod has been really cool about inclusivity, and I think that'd be a neat addition in that regard. Would wanna talk to people from the asexual community to make sure it's implemented well, of course.

**Comment by antimockingjay** [comment]
While I don't personally think those topics are inherently gendered, I think it would be nice for there to be a bit of difference depending on your gender and/or sexuality. For example, if you state you're typically more attracted to men than women, then Monika could comment on the lack of men in the literature club, excluding MC, and how things could have been different had there been a male love interest in the original story. If you say you're more into girls, then she could say that it makes sense, because you played a game with a bunch of cute anime girls in skirts.

As far as gender, perhaps certain topics could be open/closed depending on the gender you tell her you are. For example, if you're a girl, perhaps Monika would feel more comfortable talking about more "feminine" stuff such as hair and clothes and stuff. Now obviously those things aren't inherently gendered, but with societal influences, most people associate those things with being feminine; as open-minded as Monika is, things like that do become subconsciously ingrained, so it would make sense that her knee-jerk reaction would be to see them that way as well.

The one issue I could see with gender-based things such as this, is that there are trans people who play this mod, which makes it a bit more complicated. For example, a trans man who isn't out to his family might have hair down to his kneecaps because he hasn't had a chance to get it cut, so having Monika still not want to talk about hair and stuff would be a bit odd. If you introduce topics based on physical differences then it's possible someone might feel a bit misgendered in the process. Plus, with the "none" gender option, do those people just get none of the topics?

So there are a lot of pros and a lot of cons to something like this. But I do think it could be super interesting if something like this was handled well!

**Comment by ericagoldfarb** [comment]
The 'None' gender option would have its own topics, or maybe it would integrate some topics from both. Plus, as for trans folks, they can pick whichever gender option they're more comfortable with and will have less dysphoria listening to.

**Comment by multimokia** [comment]
Seems there's already some good points put out here. I.e. the fact that it's most likely possible for women to possibly have the same fetish and etc. As well, that the topic in reference is mainly a `hey this is interesting` sort of thing. Regarding lewd pictures and the like, I'll reference something you said:

> I think it would be assumed that any guy who downloads the mos is attracted to girls and any girl who gets it is attracted to girls, including my own pansexuality

I'd say that this implies it's more than possible for other women to be attracted to Monika, which *could* lead to having lewd pictures of her, which opens the possibility of -whether related or not to Monika-  masturbation.

Regarding gendered topics, the majority (if not all) of newer topics that are waiting to be reviewed are general. Therefore, doesn't really give us room to restrict things. There aren't really any topics that *can* be restricted anyway. Not to mention, with the fact that you can change genders on-the-fly, if we had ones we could have as gendered, would we lock it upon switch? Or keep them? Since it's possible to assume some would be comfortable with, and some without. It's a bit of a can of worms we'd be dealing with, is another issue, essentially.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
