### ISSUE TITLE
She still doesn't see presents 

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3303]
It's already the 25th at mine, but Monika still doesn't see ribbons I give her. Do I name it right (colorribbon.gift)? Or it has to be morning, when they are available(It's 25th, but night)?
Any help please 🙏

**Comment by Fuflyaaa** [comment]
> Where are you from where it's the 25th already?

Khabarovsk, Russia

**Comment by Secretmanguy** [comment]
Oh dear...ah, last person that sent me an email asking that was because
your on the other side of the world. I can almost guarantee that tomorrow
it will work. I don't really know how to explain it since your located in
the correct hemisphere. But it's the 24th here...Maybe try again tomorrow?

On Dec 24, 2018 8:40 AM, "Fuflyaaa" <notifications@github.com> wrote:

Where are you from where it's the 25th already?

Khabarovsk, Russia

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Monika-After-Story/MonikaModDev/issues/3303#issuecomment-449741639>,
or mute the thread

**Comment by Fuflyaaa** [comment]
Ok, thanks. I guess I have to go to sleep

**Comment by Legendkiller21** [comment]
Can you post a screenshot of your `characters` folder? As jmwall21 mentioned, in order to create the gift correctly, you need to have the file extension enabled to be able to replace the `.extension` with `.gift`.

**Comment by Fuflyaaa** [comment]
Never mind. It has worked.
