### ISSUE TITLE
[Suggestion] If Monika's difficulty for Pong and Chess is decreased, can she still be made to remember if you beat her on "hard mode?"

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#3309]
What it says in the title.

I've noticed a lot of people want Monika's Pong and Chess AI to be made much easier, and I'm fine with that. However, for those of us who have beaten her in those games on the difficult AI, I'd like it if Monika could remember that we beat her before her nerf, and then have her comment on it somewhere (perhaps add it to the "You're really good at Pong/Chess" compliment? She already knows that you have beaten her in there). It'd be a sort of "badge of accomplishment" that I think those of us who achieved this would appreciate.

Also, if a gradual difficulty for these games is implemented, I think it'd be nice if Monika would also have a similar "achievement" quote if the player works their way back up to Monika's old AI difficulty and beats her. This would be something for those who haven't been able to beat her yet could work toward. ~~or if we have beaten her, she can tease us if we are struggling to earn our way back to the old difficulty despite beating her before~~

**Comment by shades-of-teal** [comment]
I really like this, as well as the idea I've seen about Monika teaching users how to play chess. I'm teaching myself by playing with her, since I'm pretty bad at chess no matter who I play against. It would also be neat if there was a way for her to tell when we are giving up really early (like if you've only lost 3 pieces and quit because you know you can't win). If she notices us giving up a certain amount of times, maybe she asks if she should go easier on us? Or she just encourages us to keep trying?

If there is a not so difficult way for her to respond to our previous wins or repetitive loses, that would be really cool to see!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
