### ISSUE TITLE
[Likely Bug]

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#3311]
Hi everybody, how are your holidays going? I hope are well! So, Monika is not recognizing the gifts (The ribbons specifically)that i put in the "game" folder (and nor does she mention about them, as she usually does with those she can not read),any suggestions to solve this?

**Comment by tsmafterlife** [comment]
are they .gift?

**Comment by Kazuito-from-somewhere** [comment]
Yes they are

**Comment by jmwall24** [comment]
If you tried to give them to her on Christmas but had loaded the session up before Christmas, they won't work.  Have to have started the session up on Christmas for them to work.  Any ribbon you didn't try should still work provided you loaded the session up after Christmas began.  Sorry for the inconvenience, 3 ribbons are going to be made available next update that you can give any day as a make-up for the people that couldn't give her ribbons on Christmas due to this.

**Comment by OkiDokiABrazilian** [comment]
> Se você tentasse dar a ela no Natal, mas tivesse carregado a sessão antes do Natal, eles não funcionariam. Ter que começar a sessão no Natal para eles trabalharem. Qualquer fita que você não tenha experimentado ainda deve funcionar, desde que você tenha carregado a sessão após o início do Natal. Desculpe pelo inconveniente, 3 fitas serão disponibilizadas na próxima atualização que você pode dar a qualquer dia como uma maquiagem para as pessoas que não puderam dar fitas no Natal por conta disso.

No problems! Monika recognized a ribbon after i seeing some things in #3317! Thanks for the information and Merry Christmas!
