### ISSUE TITLE
Concern over word choice in hangman

### ISSUE THREAD

**Issue by HowlOrca** [Monika-After-Story/MonikaModDev#3350]
While playing hard mode, one of the words Monika chose was “retarded”
First off, I understand that its a word that has description which could be why it appeared. However, as a psych minor, this word is not as commonly used now because it carries derogatory undertones. 
I believe it is out of character for Monika to use a word like that, as well as potentially insulting to players because it comes without warning or buildup. It does not appear to make sense in the context of the game. 
I understand that this is a minor issue, and that there are more serious bugs to be addressed, but I would be thankful if this word was erased from the potential vocabulary for hangman

**Comment by Illra** [comment]
![image](https://user-images.githubusercontent.com/38264221/50461694-010f0d80-0978-11e9-9de0-11806bed5196.png)
There was an option to turn off sensitive mode if you don't like the word or offended by it.
It was probably intentional for people who has sensitive mode one.

**Comment by Mcmanybucks** [comment]
>this word is not as commonly used now because it carries derogatory undertones.


Only because we chose that. 

In the late 1800s and the early 1900s, individuals with a developmental disability were often called "feeble-minded". Based on perceived ability, they would also be categorized as "high grades" or "low grades". By the mid-1900s, the term "mentally retarded" was used and individuals were labelled "educable", "trainable" or "custodial".

People with increasingly severe developmental disabilities were classified as "morons", "imbeciles", and "idiots". The word "idiot" referred to people with the most severe intellectual impairments. 

The definition of Retard is "to delay or hold back in terms of progress or development."

    "his progress was retarded by his limp"

The word really is only that.. and I'm sure in 50 years time, the word will mean nothing as the developmentally impaired community will find a new word they're comfortable with until they become offended by it.

**Comment by TheSuperStu** [comment]
Hmm, even if "retarded" is used properly in context, I agree that it is out of character for Monika to use it. Something about her wanting people to be happy and see the best out of people, using a word that _sometimes_ is used for talking down others seems out of place, as said in the original post, out of nowhere. I understand this might lead to an issue of where to draw the line on what is okay to be said, but I believe Monika would be smart enough to know "retard" is used often as an insult. 

Even with a source listed on the code, it looks like it was just a bunch (1000) random words, so I doubt it was put in with intent. I don't know if the hangman list does reference words while on sensitive mode, because scrolling through glancing at the words, I did not see any other "controversial" words. 

If anything it probably is an easy fix to just remove one word, if it were to be removed. Because again it does not seem like a word Monika would use.

**Comment by ThePotatoGuy** [comment]
hard mode uses the thousand word corpus from [doki docs](http://dokidocs.net/). if you have a problem with the word, contact the guy who made it.

**Comment by TheSuperStu** [comment]
Fortunately, I'm not someone who gets upset or triggered by words and seeing your response, I can assume you are not too, at least this one. This just happens to be an interesting subject, because of whether or not Monika would use the word in her speech. Being literate she probably would know of its uses for her vocabulary, but again having knowledge of the use of the word being a common insult.

But I also think that response is kinda weird. Just saying "hey go here and complain" doesn't really work or address the issue. Since for starters there is not really a spot on the site to just complain since there is not any info about a source (unless tracking down the specified reddit user only found on the file is what you mean). I'm assuming if that person changed their list it wouldn't have any effect on the mod without action from the mod's end. But also it can't really be THAT hard to replace one single line/word on the code, it even says on the file "Feel free to modify to your own accord", if that might be a concern. Granted it does save as a txt file, so I don't know how the coding would work on that end, if changing the line on github would work and replace for downloads or if a new 16kb txt file would have to be put in place. 

Again I am just curious to see how it would be handled for whether or not Monika would actually use it. Might get into a problem of what words are okay and what are not, but this one almost should be a no brainer.  Again, probably a super simple fix.

And to save some precious time, here is a possible replacement that is not found on either list:
mischievous,1,3,2,4
