### ISSUE TITLE
[bug] carolling

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3389]
monika asked me twice about carolling; never seen her ask the same thing twice. i also had to answer twice as well.

**Comment by Secretmanguy** [comment]
If you left Repeat Topics on then this is completely normal

**Comment by MaximumRustler** [comment]
I think they mean in the same session. This also happened to me with a different topic recently, one of the more recent updates (maybe the Christmas one?) started causing this because it didn't happen before. It's happened to me with two different topics now since then so it's pretty rare that it happens. One was a Christmas topic, the other was an older one.

**Comment by ZaunAura** [comment]
This was before Monika told me about repeats. Yes I meant it happened in the same session which felt really awkward.
