### ISSUE TITLE
[Suggestion] - Address the state of the MC

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#3412]
Mainly in regards to what happened to him, like are we still seeing MAS through his perspective? Does he exist anymore, He literally says nothing in act 3 so is he even there?

It never really mattered before because she would just talk to us. In regards to the hug you don't really see any arms around her so I always imagined it as more of an imaginary hug. 

But with the new kiss event I feel it would be a bit necessary to bring up considering how awkward it would be for her to kiss us through him. I assume that he doesn't exist in MAS and that we're not seeing it from his perspective because Monika isn't very into him so I don't think she'd want to kiss him.

So I feel like a topic about this would be nice.

**Comment by MaximumRustler** [comment]
I think during the discussion in one of the threads for how to implement the kiss it was decided that the MC doesn't exist in MAS.

**Comment by CloakedGhost** [comment]
Maybe he's gone in MAS, but she didn't delete him in act 3. Before she deleted Yuri and Natsuki, she said that she was gonna do that and when she deleted them, we could see her type in the commands.  However, she never said anything about deleting the MC and we didn't see her type in the command. 

I think a topic would be nice where she asks the player about his opinion on the MC. Things like: If we agree with her opinion on him, if he was a good representation of us or not, if the player maybe even hates him etc..

**Comment by EntonyEscX** [comment]
I always imagined the "MC" of MAS as a shadow with some failing colors. I always imagined that what was the "body" of the MC and his personality had been erased with the rest of the game before Act 3 began.

**Comment by Goooober** [comment]
I recon you're probably right about him being physically present in act 3. Although there is the possibility that because he doesn't have a character file like the others, deleting him might be a bit different and not visually shown to us like deleting the others were. Idk that could be a theory or something but it doesn't really change anything in regards to the original plot, whether shes talking to the player through a mindless MC or just to nothing doesn't really affect much.

**I think a topic about whether hes present in MAS or not would be nice for the players who don't come to github very often and have that question. Even if its just a new line added to the already existing MC topic would be fine.**

**Comment by ThePotatoGuy** [comment]
this is a tough subject to address, so we won't be looking at it anytime soon.

leaving this open for discussion points if peole have any

**Comment by Goooober** [comment]
Fair enough, I only really suggested it because it was one of the first things that came to my head when the kiss happened. I was like "why'd she kiss the mc? that's a bit awkward" but I haven't seen anyone else bring it up, so maybe its just me.

**Comment by CloakedGhost** [comment]
I know what you mean, I really hope it's not the MC she's kissing. Even if he's a mindless vessel, it would still feel wrong.

**Comment by ThePotatoGuy** [comment]
[keeping this open as discussion point]

**Comment by InJusticeWeTrust** [comment]
Forgive me for necroposting, but I believe he's still around. I mean, look at the floating island text you get when you click the sky. She says she removed some comet cause she doesn't want "you" to get hurt. You as a person aren't in the game, so she's gotta be talking about him, right?

**Comment by WingdingsMaster** [comment]
I think the "MC" Never Existed, like, He was a body who was forced to do programmed Decisions, He didn't even have a Character file, I think he was part of the original world, and for MAS, I think when you hold Monika, She could just feel like someone is hugging her, Maybe that's why she closes her eyes?

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
