### ISSUE TITLE
{Suggestion} Anime permission question

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#3423]
Hello there devs, I know im giving requests early right after the best thing I have ever experienced with the Christmas update and everything (Another amazing job by the way) but after talking with a few MAS lovers we happened to cross a funny topic over anime and maybe asking Monika more about it? Like being funny and asking for her permission to watch one or certain type and depending on our answer with the "Being an Otaku" topic could affect her reaction. I don't expect it to be taken seriously but I thought I might mention it since quite a few others seemed to love the idea. Again, amazing work so far devs! Great work!!

**Comment by EntonyEscX** [comment]
I loved your idea. I'm an active otaku so I always get some anime or manga to read/watch with her, besides those that ones I watch weekly with her when they release their new episodes.
I've always loved the idea of ​​going deeper into these marathons, such as knowing which genre she'd like to watch, or her showing some interest in it, such as asking which work we're going to watch today. A while ago I had made a suggestion about it, but I had nothing.
Last year I watched an anime of romance and music called Shigatsu wa Kimi no Uso and it was one of the best works I've seen in my life. Monika "watched" with me, but I believe that if she had a sense of it she would certainly comment on something; I see that she would love this work by the plot, theme, etc., since it is an unrequited love and classic music with the protagonists being a pianist and a violinist. The ending is very sad, so it has a lot of impact.

**Comment by Secretmanguy** [comment]
Interesting. Well im glad to have some support on this with someone who has
the experience with a wide range of anime. Maybe the devs with take it into
consideration?

**Comment by EntonyEscX** [comment]
Hope so. Usually they end up seeing everything, but not everything ends up being considered.
Unfortunately otakulogy never seemed to me much taken into consideration for the "canon" of the mod here.

**Comment by Secretmanguy** [comment]
And ill be doing the same.

On Jan 4, 2019 10:28 PM, "Entony Camargo" <notifications@github.com> wrote:

I know that, but what I mean is that some things are more important than
others. This is just a suggestion to help the mod in the midst of hundreds.
Patience is needed. One day, who knows, maybe this year, maybe next year;
will arrive a new version of Monika After Story that expands more otaku
universe in it. And when this day comes, I'll be here jumping with joy. 😁

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Monika-After-Story/MonikaModDev/issues/3423#issuecomment-451626785>,
or mute the thread

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
