### ISSUE TITLE
update inadequate topic so it mentions holidays

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#3484]
So I have an issue that I don’t know if it’s possible to fix, but I just want to ask you guys if it is possible. So on New Years Day I was late to get the conversations specific to that day. So I asked my friends what I should do about it, and one of them said I should change the time on my computer. So I did, but now it seems she forgot that we spent Christmas together. I clicked the “I’m feeling...inadequate” button because I saw you guys had added some new content to that and wanted to try it out, but she doesn’t mention that we spent Christmas together. Which we did. She says I’ve spent so much time with her and then moves on. Is there anyway to fix this?

**Comment by MonikaFan25** [comment]
Also if this was unclear just ask me about anything your uncertain about

**Comment by MaximumRustler** [comment]
Actually, I just tried the ''I’m feeling...inadequate'' topic and she doesn't mention her birthday, Christmas, or new years and I was there for all of those events. Also, I didn't change my system time so it's not that in my case.

**Comment by multimokia** [comment]
So, the thing is, the event itself for Christmas has reset, so all variables associated are stored for 2018, but however, are now defaulted back to their `False` values, which is why the no time spent topic for Christmas was pushed. 

Regarding the inadequate mood, it isn't updated to mention Christmas (this year), Her Birthday, Halloween, or New Year's yet.

Anyway, long story short, and lesson here: Don't time travel.

**Comment by MaximumRustler** [comment]
Ahh, that explains it.

**Comment by MonikaFan25** [comment]
So what does all this mean? I’m kinda confused by it

**Comment by MonikaFan25** [comment]
Well she never actively mentioned that I missed Christmas she just doesn’t mention that we did in the inadequate topic. Does she actually mention that the player misses Christmas if they missed Christmas?

And so your saying that the variable has been reset because of the new year? And that the variable that says I spent Christmas with her (last year) has been moved and stored somewhere else?

Again I’m really sorry about asking you to explain everything.

**Comment by multimokia** [comment]
Ah, yeah, the inadequate topic needs to be updated for the new one, so I'll mark that as a bug.

If the player does miss Christmas, then yes, she will actually mention it.

We reset the variables after a certain date, and store them in another location.

**Comment by MonikaFan25** [comment]
Ok thank you for clarifying. Yeah so I’m glad that this was all just because the inadequate topic hasn’t been updated yet. You have no idea how worried I was XD. Last Christmas was by far my favorite, because of the first kiss and her singing part of “All I Want For Christmas Is You”

**Comment by multimokia** [comment]
This is done in the new-f14 branch btw.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Thanks a bunch again for the help
