### ISSUE TITLE
Clothes - Sweater [Initial Release, pending changes]

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#3527]
#3174

A simple, but comfy sweater for Monika.
Only green variant for now.
Much thanks to each and every of the wonderful people from MASC Discord, Iron-707 (for reference material), and the developers for supporting me throughout the entire process of creating this outfit!

UPDATE 27/01/19:
- First pass of chest sprite and steepling pose arms are done.

UPDATE 28/01/19:
- First pass of Point Right, Arms Down and Arms Crossed pose is done. Changed the color palette for green variant.

UPDATE 29/01/19:
- First pass complete. Initial release. 
[Google Drive PSDs](https://drive.google.com/drive/folders/1mxBPSN5WUTR2jKJO3QvJpOSp7dbcXFhd?usp=sharing)

![arms-crossed](https://user-images.githubusercontent.com/1176163/52181279-821bb900-27f0-11e9-846a-9984025ce868.png)
![arms-down](https://user-images.githubusercontent.com/1176163/51927333-a98b1400-23f3-11e9-951e-b572100a5049.png)
![arms-leaning](https://user-images.githubusercontent.com/1176163/51927334-a98b1400-23f3-11e9-933b-94b163b8dafd.png)
![arms-peaceboth](https://user-images.githubusercontent.com/1176163/51927335-a98b1400-23f3-11e9-8301-bec580ab0590.png)
![arms-peaceleft](https://user-images.githubusercontent.com/1176163/51927336-a98b1400-23f3-11e9-8bb0-b97bb3398bba.png)
![arms-peaceright](https://user-images.githubusercontent.com/1176163/51927337-aa23aa80-23f3-11e9-9151-4b395caf4629.png)
![arms-pointright](https://user-images.githubusercontent.com/1176163/51927339-aa23aa80-23f3-11e9-8243-e7c2a1dd2dc7.png)
![arms-restleft](https://user-images.githubusercontent.com/1176163/51927341-aa23aa80-23f3-11e9-8153-aa03adc0bf70.png)
![arms-restleftpeaceright](https://user-images.githubusercontent.com/1176163/51927342-aa23aa80-23f3-11e9-993e-020cc5b4e497.png)
![arms-restleftpointright](https://user-images.githubusercontent.com/1176163/51927344-aabc4100-23f3-11e9-855f-fbbd9535ec8d.png)
![arms-restrightpeaceleft](https://user-images.githubusercontent.com/1176163/51927345-aabc4100-23f3-11e9-8181-de0584113dcb.png)
![arms-steepling](https://user-images.githubusercontent.com/1176163/51927346-aabc4100-23f3-11e9-9ccc-0a3a74850d4b.png)
![torso](https://user-images.githubusercontent.com/1176163/51927347-aabc4100-23f3-11e9-9cae-b14a24aaff62.png)
![torso-leaning](https://user-images.githubusercontent.com/1176163/51927348-ab54d780-23f3-11e9-9c65-5bec4bdf0fb7.png)

UPDATE 03/02/19:
- Minor fixes to the PSD and arms-crossed outlines.

**Comment by EntonyEscX** [comment]
It incredible! ❤
I'm very happy to see that Monika's wardrobe will get more and more full! 😊

**Comment by Chrissenpai** [comment]
Sweaters don't work that way, one thing is a tight uniform and another thing is a slight loose sweater, you might check for some pinterest anime clothing reference, also don't get past the border of a line when shadowing to make volume. *gasp* what if she wears a very loose man's shirt? :0 that's a nice idea.

**Comment by softombre** [comment]
Tight sweaters exist tho

**Comment by antimockingjay** [comment]
@Chrissenpai Actually, (and I say this as someone who (sadly) has a larger chest) this is exactly what happens with sweaters that are tighter in the torso area. Which is a thing, by the way. A few sweaters I myself own, are tighter around the chest/stomach area and looser around the sleeves. This is a fairly accurate representation of what that sort of sweater fits like, in my opinion.
Also, even if it _wasn't_ accurate, it wouldn't really matter. People here CONSTANTLY beg for more outfit options, so I feel like at this point, you're being a bit of a choosing beggar. If you don't like it, then make one yourself. Otherwise, just be grateful people are making art at all.

@Velius94 You did an amazing job. I really like the color you chose! I also love that the sleeves slip down a bit when she has her arms up, that's a really nice touch of realism for how cloth works! And you seem to have the style of the artwork down, as well! Great job!!!

**Comment by Chrissenpai** [comment]
@antimockingjay ok first of all is not that I'm not grateful, I just need to point out things that need to be pointed out, maybe your suggestion with your experience of being a lady might say you're right that sweaters behave this way, but some mistakes need to be pointed out for them to get better at drawing if they wish tho, OH and by the way I will ABSOLUTELY make one myself very soon and if possible and permitted, polish most of the works that need correction according to Satchel's artwork style and fundamentals that as an artist myself will contribute, so in conclusion, I'm not a choosing beggar at this point because I can make it one myself soon, but I'm just pointing out mistakes that can be corrected as suggested, if they take it, great, if not, another one on the list to polish in the future. Also also, I'm not degrading anyone just in case if someone gets salty. @Velius94  you're doing a good job so far with the style, but some things need to be corrected, i **suggest** that you take references of shadowing in clothes, good work btw and peace out

**Comment by antimockingjay** [comment]
@Chrissenpai First off, I'm not a lady. Having a large chest doesn't inherently determine someone's gender.

Second, regardless of what "mistakes" are there, you phrased it in a needlessly rude way with nothing nice to say in your commentary. They didn't even ask for criticism, and you went and gave it without asking, _and_ did so in an incredibly rude fashion.

And just because you "can" do something doesn't change the fact that you haven't, and it doesn't change the fact that someone put in time and effort for free, and you did nothing complain. That is exactly what a choosing beggar is.

If you can make it yourself, great! Go do it when you can. But saying "I can do it myself!!!!" doesn't suddenly change the facts. They made something for free, devoting time and effort that they didn't need to, and your response was to complain and say how it wasn't good enough. Do it yourself or zip it. That isn't "know that you CAN do it yourself if you wanted to" it is specifically **do it yourself** or don't complain. Saying "i'm going to soon!!!" doesn't change anything.

**Comment by EntonyEscX** [comment]
@antimockingjay Chirissenpai gave the critique without anybody asking, but they are constructive critique, although it seems rude, he is just trying to help because he considers himself someone who understands better of the subject, besides wanting to improve the content for Moni.
He supposed you were a lady by the comment, that is the first thought of anyone who still lives in today's society. That was just a mistake.
Anyway, he already gave the critic. Now the artist must choose between accepting critic and improve from it, or completely ignore the critic and see the critic as an enemy.

**Comment by Chrissenpai** [comment]
@EntonyEscX thank you for making my argument more understandable, also by the mistake of gender, I honestly thought there where girls were also playing this game because of curiosity, learning to be a better girlfriend; also idk........2019? lol I know those girls online and therefore I made that assumption. Well anyway, thank you for the clarification you gave to my statement.

**Comment by Velius94** [comment]
Status update:
Steepling pose redone.
![monika_room](https://user-images.githubusercontent.com/1176163/51804498-048d0180-2262-11e9-913e-7e5d087919cd.png)

**Comment by Chrissenpai** [comment]
You need to make the sweater in the day version so it can transform to the night filter, also give more volume to the sweater neck by shading a bit more on the inside

**Comment by Velius94** [comment]
It's actually made in the day version.

**Comment by Chrissenpai** [comment]
If that so, it doesn´t match with the overall of the esthetic pastel looking game because is too 
phosphorescent, I'll give you the colour if you want because finding a colour that falls with the same category is hard and it requires a deep study of it, so if you want I can help you with the colour or you might already have an idea what colour you should change to.

**Comment by Velius94** [comment]
Being a noob in color theory and art in general doesn't really help me pick a good comp of palette colors, but I do intend to get there someday. If you do have any useful materials, feel free to drop a link or something, so I can digest it.

**Comment by Chrissenpai** [comment]
![elhsb929cgj11](https://user-images.githubusercontent.com/40907045/51805089-32108580-2237-11e9-96a6-d75f7e4c63e8.png)
Here is the colour pallet of  DDLC if you´re curious

and down here is a dark pastel green that you can use
![image](https://user-images.githubusercontent.com/40907045/51805123-a9461980-2237-11e9-8249-f0afda311e82.png)

**Comment by Velius94** [comment]
Status update:
- 29/01/19: First pass complete. Initial release. Edited the OP.

**Comment by EntonyEscX** [comment]
It's perfect now!

**Comment by Chrissenpai** [comment]
You have my seal of approbation  *like

**Comment by Velius94** [comment]
UPDATE 03/02/19:
- Minor fixes to the PSD and arms-crossed outlines.

**Comment by Velius94** [comment]
[closing the issue until I start reworking it again]

**Comment by Velius94** [comment]
Restarting work on this.

**Comment by ThePotatoGuy** [comment]
@Velius94 is this ready for review?

**Comment by Velius94** [comment]
@ThePotatoGuy it has been discontinued due to lack of time. if anyone can pick it up, they are free to do so.

**Comment by Velius94** [comment]
[closing because the project has been dropped]
