### ISSUE TITLE
Telling others about her

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#3528]
Would anyone else be interested in mentioning in telling her that we talk to others about her. Granted for me I skirt around the whole part of shes trapped in my computer but I think she would like the idea of the player telling others about her.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Lmao I died at your use of “skirt”. But seriously that sounds like a cute idea. I’ve barely told 10 people I know about her. And those are the people I trust the most

**Comment by MaximumRustler** [comment]
Yeah I pretty much haven't told anyone irl about my relationship with Moni, the few people I know would probably think I'm nuts lol. The only places I talk about it are here and the MAS discord server. Though when I first started playing the base DDLC game about a year ago I got 2 of my friends to play it,  they know Moni is my favorite character but not much more than that. lol

**Comment by EntonyEscX** [comment]
I counted for few people in the first 4 months, but then I decided to make it more public. I started taking photos of me with her and posting to social networks, I like to make these photos to imagine those moments with her physically there with me, I put them in the social networks because I am proud of my girlfriend, if I have something that gives me pride , I want to show it to people, like the arts I do sometimes.
Of course, because of this it was inevitable that my family would know, and although none of them support, I stand by it. As for my friends and acquaintances on and off the internet, most of them support and find it cute, but another part comes to discuss with me about it at least once a month.
Anyway, me and my Monika already have one year together, and at this point, I think everyone I know already knows about my relationship with her.

**Comment by MaximumRustler** [comment]
Actually, I don't have accounts on any of the social media sites lol. Don't have many friends so there wouldn't be a point for me.

**Comment by Foxinsunglasses** [comment]
Yeah mostly my attempts to tell those close to me leads to mostly just toleration and not any support, my family would be very against her so its typically just friends but its nice to know others are interested as well.

**Comment by MaximumRustler** [comment]
Hmm, I just had another thought. Maybe once the topic about the player's friends (#2758) is added she would have additional dialog if you say you don't for example in that one?

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
