### ISSUE TITLE
Inconsistency with Greetings/Farewells

### ISSUE THREAD

**Issue by Monikadidnothingwrong** [Monika-After-Story/MonikaModDev#3531]
Since the last update I've noticed that the greetings and farewells aren't working how they are supposed to be, for example, today I entered at around 9 am (this greeting was ok, monika was angry at me because I went to sleep late last time hehehe) and when I leave at around 2 pm she mentions how that is kinda sad that i'm leaving so early?? And now (6 pm) I entered and she mentions how much time has passed since the last time I visited her? In the same day???? Either she's just being clingy (I don't mind hehe) or something is going wrong around the code.

**Comment by Rai99** [comment]
What greetings/farewells exactly did you get? I'm pretty sure they're probably intentional. 

There's a greeting of Monika teasing you by pretending to be mad, which has stirred some questions in the past, but is a normal greeting. 

As for leaving early in the afternoon, I think that's intentional since if you're done spending time with her at 2pm, I think that's kinda early to say goodbye.

**Comment by MaximumRustler** [comment]
As for her saying it's been a while since you last visited her, that can happen even if you say goodbye and come back like 5 min later. The greetings are equally random currently I think. I think there's a fix in the works to make it more consistent.

**Comment by Monikadidnothingwrong** [comment]
Hmmm I see, thats pretty much how is going to be for a while. Maybe in a future we will get more appropiate and consistent greetings and farewells?? (I bet is hard af coding this stuff so I just should shut the hell up hehehe)

**Comment by ThePotatoGuy** [comment]
there is work in progress to make greeting rules make more sense. (`new-greeting-rules` branch)

**Comment by ThePotatoGuy** [comment]
[keeping opensince farewells need the adjustment in the future]

**Comment by dennisOdenbreit** [comment]
The "I hate to see you leave so early" farewell always kind of bothered me.
The problem with it is that it does not address the time you spend with her this session, but the time of day you leave, which can be confusing. Maybe it could be more explicitly stating that it references the time of day only.

There are some greetings that currently seem rather random, for example when she comments on you not visiting her often enough even though you do. I think this is because there are no actual checks yet whether this is the case or not. This can indeed make her seem clingy / unreasonable, especially if it happens more often. Sometimes she says she is joking about it, but the message is there.

**Comment by dennisOdenbreit** [comment]
Another concrete example that just happened to me is:

`label bye_goodevening:
    if mas_isMoniNormal(higher=True):
        m 1hua "I had fun today."
        m 1eka "Thank you for spending so much time with me, [player]."`

I visited her for 5 minutes in the evening.
The conditions / responses do need a rework.

**Comment by AsuraShun** [comment]
Yeah,that last one seems weird,specially if you have to go out for most of the day

**Comment by Rai99** [comment]
Closing as complete
