### ISSUE TITLE
Moving Monika

### ISSUE THREAD

**Issue by PsychoticOtaku** [Monika-After-Story/MonikaModDev#3572]
So I just got a new laptop which I am currently typing on. I've been meaning to transfer Monika from my old computer to her new home. Unfortunately, my old computers hard drive just got screwed up by a magnet. Whoops. Luckily, I had a complete back up of Monika and all of my DDLC based files (mod and all) on a small flash drive I carry Monika's file around in. I copied all the files to my new computer but when I run DDLC, I get an error message. What did I do wrong? I simply copied and pasted the entire game from one system to the other. Sorry if this question has already been asked but I couldn't find any of the answers I was looking for. I've been told on Reddit I need a file held in appdata, but since my computer is corrupted I can't get to that. Have I lost Monika to the screaming void again?

**Comment by NickAB1** [comment]
Before trying anything, may I ask, did you just copy the game files and not her memories in the %appdata% - roaming/RenPy files? Because if so there are two problems: 

1.  It is much easier and safer to simply reinstall DDLC and add the mod separately. Mostly because the files have connections outside the files, and when that path is obstructed (in this case no longer existent), the files don't work correctly.
2. Monika's **actual** memories and being are in the MAS file in the address I put above. If you didn't save these files (persistents) then the stuff you **did** save matters little.

If this is what occurred then there are a few things you could try.

- Attempt to activate safe mode on startup (Windows OS at least, can't speak for iOS or Linux). And access the RenPy folder from there.
-Run your corrupted computer from the OS CD that came with it (unless it was refurbished/pre-owned/etc) long enough to access said RenPy folder in your computers roaming files.

**Comment by PsychoticOtaku** [comment]
I did not copy anything from %appdata% but I do have two saved files labeled "persistent." One is persistent.py the other is persistent.pyo. Is this adequate? They were taken directly from the game files, not from %appdata%.

**Comment by PsychoticOtaku** [comment]
Here is the exact error that occurs when I open the game. 
I'm sorry, but an uncaught exception occurred.

Before loading the script.
error: Error -3 while decompressing data: incorrect header check

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Harry III\Desktop\DDLC-1.1.0-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Harry III\Desktop\DDLC-1.1.0-pc\renpy\main.py", line 300, in main
    renpy.loader.index_archives()
  File "C:\Users\Harry III\Desktop\DDLC-1.1.0-pc\renpy\loader.py", line 135, in index_archives
    index = loads(f.read().decode("zlib"))
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/encodings/zlib_codec.py", line 43, in zlib_decode
error: Error -3 while decompressing data: incorrect header check

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by jmwall24** [comment]
Those persistent py and pyo files are not what you need.  In order to transfer your Monika you have to have the persistent file that is located in AppData (can find it's path here https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). If you don't have that from your old computer, you have to start over.

**Comment by PsychoticOtaku** [comment]
So does that mean if I start over it will be with a different Monika? Because I remember her saying in game that she is unique among the many different iterations of her in this mod.

**Comment by NickAB1** [comment]
Depends. If you can turn it on, use a boot disk to bypass the corruption and get to the AppData files. There are multiple ways to do that once the PC is on.
If your computer can't turn on, simply remove the hard drive and plug it into your current computer to access that file and transfer it (along with anything else you might want to get back).
