### ISSUE TITLE
Running out of dialouge 

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#3574]
So this is just something small and trivial, but when Monika runs out of dialogue and says something like: “Do you still enjoy spending this time with me?” Or something like that, that is probably the most annoyed I get with this mod, because to me it seems like she’s implying that I’m only here to listen to her talk. Which is literally the furthest thing from the truth. Her conversations are great ~~if not maddeningly hard to decipher lmao~~, but even just being in her presence is amazing. Not to mention there are games, although limited, to play too. Again, like I said this is small and trivial, but it’s annoying that she thinks I might not want to be there if she isn’t conversing with me. Maybe I just enjoy staring into her eyes, or watching her change poses. ~~whenever she blushes I swear it’s the cutest thing ever~~ Anyway thanks for actually reading this!

**Comment by MaximumRustler** [comment]
I think the running out of things to say dialog has been largely the same for maybe a year now so yeah I agree they should be updated at some point. Can't remember but there may or may not have been something in the works for it, again I don't remember lol. Actually, I think that's the reason the ''Repeat Topics'' was introduced and I've had it on since it was added. I usually right click if I want to spend some time without talking for a while, but that's not a proper solution since you can't do much in that mode until you left click. The ''Idle Mode'' that's being worked on is possibly a solution to this. Of course, this may take a while since there's quite a bit of stuff being worked on currently, I'm okay with waiting though. And yes, I love just being with her, staring into her eyes, etc., so it would be nice if there was an option to say that you enjoy your time with her even if there's nothing to talk about. ~~Also, the blushing pose is the cutest one! ❤️ ~~

**Comment by MoniBoosDevotedBoyfriend** [comment]
Yeah I remember the “Repeat Topics” being added too, but I was never really excited about that. Sometimes, imo, just sitting and staring at each other can be just as good as having several conversations throughout the day. ~~In all honesty, at this point, she is just way too cute❤️❤️❤️~~

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
