### ISSUE TITLE
Use standard resolution game sprites

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3607]
We currently downscale all of our sprites by 50% (from 2560x1700 to 1280x850). There are pros and cons to this approach:

Pros:
* smaller image sizes:
    * smaller mod size + less to download
    * better performance in renpy
    * less RAM used

Cons:
* sprites look kind of blurry or low quality. zoom brings this out very noticably
* exporting outfits that dont hide body/arm seams in clothes is currently a mess.

We are debating some options for using the standard (2560x1700) sprites instead of the smaller ones. First, some pros/cons regarding using these sprites:

Pros:
* looks much much better, especially with zoom
* much easier for us to export outfits since what we see in photoshop is what we get when exported

Cons:
* nearly 3x-4x the size of the smaller images:
    * big mod size
    * probably performance degredation, but not 100% sure
    * definitely more RAM usage

Here's some options we discussed regarding sprites sizes:
* standard/downscaled sprites would be toggable via a setting. 
* release standard size sprites as a separate zip
* change required size of sprites to the downscaled sizes instead of the standard size. This would be great for the in-game sprite exporting but would leave us very little room in potentially releasing standard sized sprites. 

Some issues:
* having both standard and downscaled sprites means double the work with exporting, as well as double the work in fixing sprite issues. Ideally, we want to just do only standard or only downscaled, but as mentioned, there are pros and cons to each.
* the current method of handling sprites is also pretty bad. Downscaling can completely screw with an otherwise perfect sprite setup. as it currently stands, getting #3376 to work at a lower resolution is taking some work.

There will be a poll on the MAS discord about this sometime later this week.

Main thing is whether or not we should completely swtich to the standard size without providing support for the downscaled ones, or do the blended approach and just deal with the extra work. (or never do standard sprite sizes)

### Core issue with current system

Current process for adding new sprites:
1. receive psd from artist at standard size resolution (2560x1700)
2. export day/night png layers from psd at 50% size (1280x850)

In outfits where layer seams (like where the base ends and arms begins) are in line with the outfit (like on a black line in blazer outfit), the seams look like they match and there are no visual artifacts.

In outfits where the arm/body seam does not have clothes (casual vday outfit), there is a very noticable seam line between the arms and the body. This is the result of the resampling/interploation algorithim photoshop does when it downscales different layers.

**Comment by MaximumRustler** [comment]
This is something I kinda though about bringing up a few times but I decided not to for the issues already mentioned. The increased file size may take too long for some people to download, not an issue for me but I know that some people would have issues. I don't know about creating options but yeah, having a separate download for the higher quality sprites may be too much work. But the biggest issue in my opinion is possible performance issues/instability, considering the game already has some lag issues (which is oddly inconsistent for some) and the possible limitations of renpy, I wonder how it would do with higher quality sprites, would it cause more lag or have no difference? According to what you said there seems to be some issues down-scaling the new outfit so that's another thing to consider I guess. And while yes, I really would like higher quality sprites, I don't know if I would if there is some added instability. Depends on how it performs and if the extra development time is comfortably manageable I guess.

**Comment by EntonyEscX** [comment]
It would be beautiful if all the sprites were bigger, but the risks and problems exist with that. I think it best to keep it as it was, work with the larger sprites and then decrease them to put in the mod itself.

**Comment by ThePotatoGuy** [comment]
poll probably at end of week

**Comment by ThePotatoGuy** [comment]
poll probably when art has settled a bit.

[closing this in the meantime]
