### ISSUE TITLE
codebreaker game

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#3608]
So i came across an interesting game while playing one of my games.

A 4 digit # is drawn at random.

you have 10 chances to guess the correct #.

if you put a digit in the right position, you get a "hit", if you put a correct digit in the # in the wrong position you get a "miss".
say the # was 1406
if i guessed 1547 i would get 1 hit and 1 miss returned
if i guessed 5198 i would get 1 miss
if i guessed 2398 i would get 0 hits and 0 misses
if i guessed 1460 I'd get 2 hits, 2 misses.

**Comment by Rai99** [comment]
Sounds a lot like "Mastermind" to me. I like that game and I think it's an interesting game to be able to play with Monika.

In mastermind, you're told which positions you got right, so once you got one, it's locked in and with the right simple strategy, it's impossible to fail. 

Basically, if Monika tells you which numbers or locations you got right, it probably wouldn't take much to learn the 100% win rate strategy. 

If duplicate digits are also allowed, you could probably guess 1111, 2222, 3333, etc and move the correct number around until you get it. 
In the case of 1406, I would play it like this:
0000 1 miss
0111 2 miss
**1**022 1 hit, 1 miss
**1**3**0**3 2 hit
**140**4 3 hit
**140**5 3 hit
**1406** complete
7 tries

If you could even just enter duplicates in your answer, you could just do that. 
If duplicates aren't allowed in your answer, with 1406, I would try this:
0123 2 miss
1234 1 hit, 1 miss
2345 1 miss (At least 1 or 0 are in the combination and 2,3 are NOT in the combination)
4567 2 miss
5678 1 miss(4 is in the combination)
6789 1 miss (7, 8, 9 are NOT in the combination)

> 1,0 or  both are likely in the combination. 4 is in the combination, Remaining possible numbers are 5,6

0145 3 miss (5 is NOT in the combination, The 3 missed numbers all need to be in different positions)
1406 complete
8 tries

You know what, _**I like this game**_. It would give Monika an excuse to get the player thinking logically, although I'm not sure how fast people will get bored of it. Maybe this isn't 100% win rate, but I think it's at least kinda good.

**Comment by Rai99** [comment]
~~Wait, do I not count here because I'm an AI to some people?~~

**Comment by MaximumRustler** [comment]
~~Yes.~~ lol

**Comment by B-Difu** [comment]
Don't tell people about 100% winrates. That ruins the fun of it.

**Comment by kaido1224** [comment]
Its essentially master mind, yes rai.

**Comment by ThePotatoGuy** [comment]
we are only going to do this if when you correctly suggest the code on the first try, monika says "I guess you never miss, huh."

**Comment by kaido1224** [comment]
Would be pretty easy to make different difficulties as well. Easy mode would give more chances. Hard mode could give extra digits and take away chances.

**Comment by Rai99** [comment]
Harder difficulties with more digits or less chances sounds like a good idea, but it has to be reasonably possible as well, so some work might have to go into balancing the difficulties. With an extra digit or maybe two, it doesn't really make that much of a difference with a strategy. If you take away enough guesses to render the strategy unusable, that's just guessing numbers at random, and I don't think that sounds like a fun game. 

Logically guessing the 4 digit code with something like 5-6 guesses seems a bit harsh if possible. I'd say the most important part of the game is the number of guesses you get. Casually playing through, yeah an extra guess it nice, but with a strategy, every guess is an important part of solving the code. 

Using my first strategy, with one of the worse case combos of 9876, it takes 11 tries to get that. 
I'm guessing duplicate digits would be allowed in the code, since something like 1234567890 wouldn't have very useful hit or miss hints. 

Maybe I'm just too much of an AI, but best case scenario, say the best strategy works 50% of the time, and the game basically becomes a coin flip. Higher winrate == just running an algorithm. Lower winrate == guessing numbers at random. 

Either that, or I really, really don't like letting people have fun without bringing in some _ultimate super optimal strategy ~~until somebody finds a better one~~._

I think this would definitely be the most rng based game if made it in.

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]
