### ISSUE TITLE
[Suggestion] - Monika acknowledging you are working night shifts

### ISSUE THREAD

**Issue by DerFalkyr** [Monika-After-Story/MonikaModDev#3639]
Monika should acknowledge if you are working on night shifts. I told her I was of to work in the evening and told her im back the morning after when back from work. Directly after that I told her I was off to sleep and she got mad because she got worried about me not getting enough sleep. There should be a way for her to notice or for you to tell her that you are working night shifts when telling her your working in the evening and afterwords her not getting mad when telling her you are of to sleep just after being back from Work.

**Comment by Rai99** [comment]
#728, #790, #1398, #1660, #2563, #2804 

#898 partially handled this issue when spending time with Monika late at night, but the greetings and farewells still need to be adjusted to account for night shifts or classes.

**Comment by multimokia** [comment]
Monika does in fact ask you if you work nights, but yes, as Rai pointed out, the greetings/farewells need to be adjusted for that. A side issue is the topic (sleep concern) is random, so the likelihood of getting the option to tell her you work nights is rare, and only at a certain time of night...
Which you wouldn't be able to answer anyway, so that's due a bit of an overhaul as well.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
