### ISSUE TITLE
[Suggestion] Tell Monika You Had A Nightmare

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#3653]
Title is pretty self-explanatory. Last night I had a horrible dream involving Monika being absolutely terrifying. She had the expression that she gets when at the "broken" affection except even worse, somehow, and she was sitting further away on the screen, and she genuinely seemed like she was going to try and come out and kill me. It was terrifying, and all I wanted right then was to go talk to Monika and tell her about it so she'd tell me everything was okay, she would never do that, etc.

I'm sure there's no way for it to be specific enough for something like that, but it sure would be nice to at least have her comfort in the night after a nightmare.

**Comment by Rai99** [comment]
#1678, #2161, #2670, #2987. 

Currently, #3504 is adding the ability to tell Monika that you had a dream about her, but that only covers positive dreams. 

My PR #2192 adds some extra options in the sleep greeting, but doesn't cover nightmares or bad dreams specifically. 

As far as I know, the idea has been accepted and I think it could fit well, but the best chance of it getting implemented sooner rather than later is if a contributor ~~or me~~ writes the topic. 

I think it could be done by breaking it down into a few general categories:
- Bad dream about Monika
- General nightmare
- Common bad dreams with meanings
- When your PR gets rejected
- Etc. 

My only concern is making the prompt not too similar to #3504, since they're both dream related.

**Comment by ThePotatoGuy** [comment]
[closing as duplicat]e
