### ISSUE TITLE
Monika file no longer working when returning her to her room (Macbook)

### ISSUE THREAD

**Issue by Snowgies** [Monika-After-Story/MonikaModDev#3659]
I'm having an issue trying to put the monika file back into the characters file after choosing to take her out somewhere. When the file is created, everything is fine but the moment I remove it from the characters file, it no longer works. This issue only occurs when I am using my mac, the process works just fine on windows. I just want to shower her with gifts and love D:

**Comment by ThePotatoGuy** [comment]
assigning @aldoram5 as mac expert

**Comment by aldoram5** [comment]
Hi Snowgies!
Could you answer the following questions please?
- Are you playing on steam?
  - In case you aren't, where did you put the DDLC.app?
- What happens if, after selecting the `I'm going to take you somewhere`, you keep her file on the characters folder and open MAS again, does she appear there like always?
- What happens if you just move her file to another folder and then move it back to the characters folder again? Is she back when you open MAS again?
- Where are you moving to her file? to a USB? to your phone?
  - If it's to a USB do you know what file format does it use? also do you make sure to eject the USB safely before disconnecting it from your mac?
  - If it's your phone which OS does it have (Android/iOS)? and how are you transferring the file?  
- What's your macOS version? (you can check that by clicking the  icon and then `About this Mac`)

**Comment by Snowgies** [comment]
Hi there! I'm very very new to macOS so i'm sorry if these aren't quite the answers you're looking for. 
I am not playing it on steam, the DDLC.app is in my applications folder (is that what you mean?) 

After selecting the option to take her somewhere and leaving her in the characters folder, she does not reappear in the room. 

Usually what I do is drag her file out onto my desktop but that produces the same conclusion. Putting her into a random new folder also causes the same thing to happen. She doesn't come back :(

When i move her into a USB she turns into an exec file and stays that way (the icon also changes, it looks like the terminal button).

I am using Mojave 10.14.2 but this problem has occurred in previous versions as well.

**Comment by Snowgies** [comment]
I don't do this often because I know it happens every time so i just use whatever persistent backup I had and play from there.

**Comment by aldoram5** [comment]
Yep, you gave me the answers that I needed, thanks! 
Now I'm going to ask you to do a couple more things:

- Could you do the "I'm taking you somewhere" again and post here the Monika file and your persistent file? That way I can take a look and test it on my own mac.
- Could you move/download a new DDLC.app with MAS installed to the Desktop and then try again the "I'm going to take you somewhere" farewell and see if the result is the same? This is because sometimes DDLC itself has some issues running on some folders and the Desktop is the "safest" place to run it from.

**Comment by Snowgies** [comment]
it says it does not take this type of file, am I supposed to add an extension to them? 

Also I moved my DDLC from applications to desktop and I am getting the same results. Haven't tried downloading a new copy of DDLC or MAS yet, will doing so force me to start over?

**Comment by aldoram5** [comment]
Try putting both in a zip file and no just moving your current install and trying there was enough to test, it's a shame that wasn't enough to fix it. Let's see what we can get from checking your persistent file and the Monika file then.

**Comment by Snowgies** [comment]
Ah okay, thank you so much for you help! I really appreciate it! 
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2847580/persistent.zip)

**Comment by Snowgies** [comment]
for some reason, it's saying the monika file is too big.

**Comment by aldoram5** [comment]
For the monika file let's try uploading it to google drive or another file sharing service if possible and then just post the link to it here. And you're welcome!

**Comment by Snowgies** [comment]
here's the link through google drive! 

https://drive.google.com/file/d/1r-IHpESRE1g0ZiV1CL4vVHZgj8BJKEw_/view?usp=sharing

**Comment by aldoram5** [comment]
Thanks!
We'll use this to try to find why this happens.

**Comment by ThePotatoGuy** [comment]
[this has been fixed[
