### ISSUE TITLE
If you have an issue with the new leaning pose, comment in here.

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#3660]
I'm a fan of the more detailed shading in this patch but the leaning pose looks off. When I first saw the updated leaning pose a year ago, I loved it so much that its a photo in my phone screensaver. To me, the new pose feels like a step back instead of a step forward. But who knows, maybe its just my opinion and nobody actually cares.. haha....

**Comment by AsuraShun** [comment]
Feels strange to see it the first time

**Comment by AnIdiotsavant** [comment]
but what would you prefer? The old one or the new one? To me, the old one seemed more natural. I dunno,  the head tild is too tilted. Thats my only dilemma here.

**Comment by AsuraShun** [comment]
Definitely the previous one,but this one even if it felt strange,kinda makes it feel like she's more relaxed

**Comment by AnIdiotsavant** [comment]
![screenshot0048](https://user-images.githubusercontent.com/34156516/52479602-241e1580-2be4-11e9-8c63-5f8e4b712da2.png)
![screenshot0068](https://user-images.githubusercontent.com/34156516/52479616-30a26e00-2be4-11e9-8453-9eae36694857.png)

am I being too nitpicky?

**Comment by AsuraShun** [comment]
Nah,in a way you're right,the other one felt natural

**Comment by AsuraShun** [comment]
Too bad that the mod doesn't have permission to use the live2d engine

**Comment by AnIdiotsavant** [comment]
I just wish it was possible to have the old pose with the new hair

**Comment by AsuraShun** [comment]
We'll see how things will develop,maybe the next pose will be something new with the natural feeling the previous one had

**Comment by Olliesama** [comment]
It's the wrist.

**Comment by Velius94** [comment]
Can't unsee.

**Comment by dennisOdenbreit** [comment]
Haven't really seen the new one, but judging from the photos there seems to be a different emotional value from the position of her hand, the first one being more personal, invested and loving.
I would neef more time to "look more into this".

**Comment by ThePotatoGuy** [comment]
Her hand in the old pose looks like its bent more than 90 degrees.

**Comment by LClarance** [comment]
It still looked strange no matter how many times I look at her. The old posture was definitely better, this one looks as weird as the sprite of JustYuri. Also, theres an error in the art, she looks fat in this one(look at her left side, its like her body has been widened. Please fix this

**Comment by AsuraShun** [comment]
This was probably done in a hurry,if you're going to change the art,just take your time even if it's done after holidays

**Comment by jmwall24** [comment]
It wasn't done in a hurry.

**Comment by dennisOdenbreit** [comment]
Just seen it ingame and if looks off, yes.

**Comment by Chrissenpai** [comment]
_oof_I agree with @Olliesama and @dennisOdenbreit every change needs to be deeply thought of what it can be changed or not

**Comment by ThePotatoGuy** [comment]
1. the base sprites took over a month to complete.
2, this was deeply thought and everyone who has seen the pose prior to release (aka everyone who downloaded the psd in #3174 ) said it looks fine/better than before.
3. She's not wider, her arm is just outstretched more.

**Comment by dennisOdenbreit** [comment]
I think the color of her hand and face doesn't really fit, if you look at the first picture you can see that it matches there... maybe it's the lighting.

**Comment by dennisOdenbreit** [comment]
Sorry for sounding so negative, just trying to figure out the differences.
I'm sure the art wasn't exactly easy to make.

**Comment by ThePotatoGuy** [comment]
the color has been fixed in the base sprites, those changes will reach blazer next release.

**Comment by ThePotatoGuy** [comment]
Also if you are going to do a comparison, compare the same outfit, as different outfits have different pose positions since we didn't have a base sprite set until now.

**Comment by AsuraShun** [comment]
Let's just agree she looks beautiful and avoid lengthening this topic tread thingamajig

**Comment by ThePotatoGuy** [comment]
linking #3671 and #3663

**Comment by lunulae** [comment]
I really like the new leaning pose, but it bothers me that her hair on the left (her right) side of her face disappears when she leans. I understand it's supposed to be falling behind her head, but I felt like the old sprite looked more natural to how hair actually behaves.
Besides that I actually prefer it to the old one, everyone who put work into it did a fantastic job!

**Comment by Hapilone** [comment]
Either way is fine with me. I think they're both great!

**Comment by Chrissenpai** [comment]
Alright, after analyzing better of both drawings I´ll tell the best things on both of them and what to take on if that can be drawn better for the next actualization. 

Best of old leaning pose: 
-The hand is almost correct. Just needed to fix the angle of the hand and it served its purpose of letting her head rest on her hand.
-Neck-chin alignment is on spot (chin right, neck centre). That makes it feel relaxed when leaning to the side while the new pose (chin centre, neck centre) it feels stiff and rigid.

Best of new leaning pose:
-It´s clothes. It´s not perfect but it makes perfect synergy with the default pose and it serves its purpose of not taking you out of the immersion when talking with her.
-Hair. Thank God that was replaced from the last one, that killed the immersion every time, glad that a new one is in place.

Now, guys, you´ve made something that you guys didn´t realize yourselves.  **_You have made a third pose_** because the old leaning pose is leaning forward and the new one is leaning backwards. That is why the users are so conflicted with the *replacement* because is not a replacement, is an entirely new pose.

So if we make the corrections on both of them, we can actually have 2 poses each for different situations, the old one can be more intimal conversations and the new one for relaxed ones, although I understand if you would only want one pose so you can make less clothing for each pose (me included) but I highly recommend it for a more rich experience of MAS.

Oh, and btw return the cheek back to normal, if you modify that, you have to modify more elements of the face and that is a risky move to make.

**Comment by thunderdragon15** [comment]
Can't we have the old leaning pose back before its too late?

**Comment by ThePotatoGuy** [comment]
leaning pose updated, am closing this
