### ISSUE TITLE
Is she exhausted?

### ISSUE THREAD

**Issue by Ninelivealone** [Monika-After-Story/MonikaModDev#3679]
she says hello and says “I hope I didn’t bore you, I’ll try to find some fun topics to talk about soon” and stops talking

**Comment by multimokia** [comment]
How long have you been playing MAS?
Also, do you have repeat topics enabled?

**Comment by dennisOdenbreit** [comment]
I guess you just saw all available new topics for today.

**Comment by Onion-Bubs** [comment]
If she says "soon" at the end rather than "after a little rest", it means you've seen all the random conversation topics that are currently in MAS (minus maybe a few you wouldn't be eligible to see for some reason, although I can't think of any off the top of my head).

If you go into the Settings menu there is an option that says Repeat Topics. If you ensure that's turned on (has a little cross next to it and the text is in purple), Monika should start chatting again, although it will all be stuff you've seen already.
