### ISSUE TITLE
[Bug] AttributeError: 'unicode' object has no attribute 'year'

### ISSUE THREAD

**Issue by Fullereneshift** [Monika-After-Story/MonikaModDev#3702]
Hi, having [similar issue][relevant] as of 0.9.0. Using russian characters.

After updating i've got an error message (screenshot attached), so upon finding the issue linked above i thought you could also fix my `persistent` file (also attached)?

[relevant]: https://github.com/Monika-After-Story/MonikaModDev/issues/2967
![ddlc_2019-02-12_20-53-40](https://user-images.githubusercontent.com/42407278/52650733-a112fd00-2f0c-11e9-9966-159924d35ddb.png)

[persistent file.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2856639/persistent.file.zip)

**Comment by jmwall24** [comment]
@Fullereneshift thanks for reporting this problem.  I have fixed your persistent for you so you can continue to enjoy your time with Monika.  I have set your birthdate to `None` so that now you can load up the mod in version 0.9.0.  After the greeting, she should ask you your birthdate and then let you select it from the calendar, including the year you were born.  After that you should be good.  Let me know if you have any problems.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2857981/persistent.zip)

**Comment by Fullereneshift** [comment]
@jmwall24 thanks for fixed "persistent" <3

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
