### ISSUE TITLE
A quick question about the player's appearance conversation

### ISSUE THREAD

**Issue by DankeyMaliten** [Monika-After-Story/MonikaModDev#3704]
So I just got this today and when she had asked me how tall I was I put in 5’3 {5 feet 3 inches} and she said I was as tall as Natsuki but I'm pretty sure she's just as tall as me as I remembered and looked up that she's supposed to be the exact same height. So I kinda expected to have her talk about how we're both the same height. Was this intentional or did I just flat out do something wrong? Cause that kinda confused me. And if not will it be fixed?

**Comment by MoniBoosDevotedBoyfriend** [comment]
No I noticed this too. She guesses that she’s around 5’5 which is wrong according to the wiki. I think maybe it might be unintentional, but I don’t want to make assumptions.

**Comment by MaximumRustler** [comment]
This was discussed a few times actually. Since it's a concept height she's unsure of how correct that actually is but thinks maybe closer 5'5''(was changed to say this in the recent update or maybe next one). I'm not sure if Dan gave official heights to the characters. ~~This also means I'm shorter than Monika. lol~~

**Comment by MoniBoosDevotedBoyfriend** [comment]
Actually she’s said that she’s 5’5 for a while ~~oof I’m 6’2~~

**Comment by jmwall24** [comment]
> This was discussed a few times actually. Since it's a concept height she's unsure of how correct that actually is but thinks maybe closer 5'5''(was changed to say this in the recent update or maybe next one). I'm not sure if Dan gave official heights to the characters. This also means I'm shorter than Monika. lol

Correct, those heights in the wiki were concept heights and do not reflect their actual heights.

**Comment by MaximumRustler** [comment]
I mean, now, if not the next update, she's supposed to mention the height on the wiki too. She didn't before as far as I remember.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Oh ok

**Comment by NoodleJoodle** [comment]
So wait she's actually 5'5? really?
This'll take some time to getting used to since I've always gone by the concept height. Her being 5'5 seems a little off to me but that's because as I said I was just so used to the concept height.
Or is this just another concept height? Well doesn't really matter all that much hugging a taller than me Monika makes me feel happy and lovey for some reason

**Comment by EntonyEscX** [comment]
I also got used to the height of the wiki. I have 5'8 and whenever I put Monika in my photos I end up putting her at 5'3. 😕

**Comment by B-Difu** [comment]
Well, I think that they went more for the average height of a woman. Places like USA, UK, Australia, Russia, Sweden and many more countries it's roughly 5' 5" for white woman within an inch according to Wikipedia.

**Comment by jmwall24** [comment]
I look at it this way.  A point was made that 5'3" was merely her concept height, so to me that means 5'3" is not her actual height.  If 5'3" was her actual height, why say it was her concept height instead of just saying she's 5'3"?
So what height is she? Yuri is considered the tall one, so her being a little taller than average makes sense, then Monika was next in height, so her being average height makes sense to me.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ok ok, I’m sorry. I was just misinformed

**Comment by B-Difu** [comment]
All good, we could be wrong and she's not 5'5". She could be 4", 6", 7", we don't have solid evidence pointing any specific height.

**Comment by MoniBoosDevotedBoyfriend** [comment]
That’s a fair point. Like I mentioned I’m 6’2 so having her be somewhere between 5 and 6 feet would be awesome

**Comment by MaximumRustler** [comment]
~~ @MoniBoosDevotedBoyfriend  Heh, that just means she could listen to your heartbeat while you hold her.~~

**Comment by MoniBoosDevotedBoyfriend** [comment]
~~awww that’s cute. That would be very nice tho~~

**Comment by jmwall24** [comment]
> Ok ok, I’m sorry. I was just misinformed

Nah, no need to apologize at all.  Just explaining the reasoning behind it.

**Comment by Chrissenpai** [comment]
I´m 5´6 and I´ll slowly retire...
