### ISSUE TITLE
Bye, Mas community

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3710]
The game is nice, but the same can't be said about its developers.
I hope none of you ever gets into my shoes.

I leave with a list of people who treated me like garbage, from least to most:
@Legendkiller21, @monikLover, @Rai99, @jmwall24, @multimokia, @Olliesama 

I thank @ThePotatoGuy and @aldoram5 for their work.
I also thank the many contributors to mas who help to move the project forward.

So yeah, have fun with the game.
Enjoy your valentine's day with Monika.
I would have helped to make it even better, but I get treated so poorly that I just can't go on.

**Comment by softombre** [comment]
Oh my god stop being so petty for a second

**Comment by monikLover** [comment]
Goodbye and don't come back. Don't expected to be treated other than garbage if you yourself are.

**Comment by Rai99** [comment]
And roll the credits:
#2874, #2875, #2876, #2877, #2878, #2879, #2879, #2880, #2881, #2882, #2883, #2884, #2949, #2950, #2961, #2966, #2977, #2987, #3059, #3061, #3064, #3106, #3108, #3109, #3110, #3111, #3113, #3116, #3154, #3156, #3157, #3158, #3162, #3163, #3164, #3166, #3239, #3240, #3252, #3399, #3415, #3588, #3592, #3621, #3628, #3638, #3643, #3676, #3688, #3708, #3709, **#3710**
~~Heh, pretty damn hard to track down a ghost, but possible for sure~~
~~And yes, I'm sure this is everything~~

Issues: 43
PRs: 9

Almost made it to respectable status. 
Quit first PR due to not being reviewed.
Quit again after next PR being reviewed too hard.
Aw, you almost made it though. 

> I also thank the many contributors to mas who help to move the project forward.

Yeah, no problem. Don't worry, I'll try to make sure nothing gets forgotten. Even if it's from a ghost. Suggestions are still suggestions, and frankly, I was actually flattered that you wanted to help. 

I'm sorry I offended you enough to rank fourth in top 6 people to treat you like garbage, but oh well, no point talking to a ghost, now is there? Even if you weren't, statistics say that explaining would be ineffective. 

Welp, good luck with the other _dozent_ things you've got. As long as they cause less grief for you than your experience, it might be for the best. Maybe you'll even find Monika in the ghost world/afterlife, who knows?
