### ISSUE TITLE
Characters 

### ISSUE THREAD

**Issue by BigPoofyRibbon** [Monika-After-Story/MonikaModDev#3713]
Can we ask Monika, why  characters folder  still have doki doki girls if it's Monika's mod.

**Comment by Velius94** [comment]
Possibly an oversight.

**Comment by dragonsni** [comment]
Well they aren't required for the mod and can be freely deleted, I think the others stay there because they are automatically there when you first download it and the devs deemed it unnecessary to put in the time and effort to put coding into the mod to automatically delete them. I don't want to sound like a jerk by saying this but food for thought, you know?
