### ISSUE TITLE
[Suggestion] - Short sight topic

### ISSUE THREAD

**Issue by Tombother** [Monika-After-Story/MonikaModDev#3762]
I think we should add a new topic about short sight. Monika talk about our society short sight. She will remind us to stay healthy that prevent to deepen short sight.

**Comment by Rai99** [comment]
I'm sorry, could you elaborate on that to make sure I'm on the same page?

What I'm getting is that you want a topic about bad eyesight and Monika wanting you to take care of yourself so you don't ruin your eyesight. 

It sounds nice at first, but uh... to me, that sounds like a pretty huge slap in the face for people who wear glasses and people who just so happen to have bad eyesight. 

Some people can't help it and it probably wouldn't feel very good for Monika to talk about how you should take care of your eyes so you don't get bad eyesight. 

Maybe instead of being about bad eyesight, it could be about glasses instead? Still, that does seem a bit random for Monika to bring up, unless we have a pm var for if the player has glasses. (Might be a good idea actually)

**Comment by antimockingjay** [comment]
I love the idea of Monika bringing up eyesight/glasses, as someone who constantly has to remind himself to put glasses on in the morning so as not to be blind the rest of the day. But I agree with Rai99, if it turned into a "take care of your eyesight" thing I'd be pretty offended. I've had glasses since I was about 8 or 9, there wasn't anything I could do to prevent that. Most people in my family wear glasses in some capacity, it's just genetics. Not everyone with bad eyesight did something to earn it.

**Comment by Rai99** [comment]
What about the sensation of the very first time you put on glasses? That's probably one of **the most** satisfying things anyone can ever do in life, ever. Might make a nice little comment in the topic if it's written. 
![untitled1198](https://user-images.githubusercontent.com/38822045/52894848-b55e3080-317e-11e9-933d-10b09a071def.png)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
