### ISSUE TITLE
[Question] - What's the mod's weakest link?

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3784]
As the title imply, I was wondering what's the thing(s) that is(are) slowing down this mod the most. I do not mean it in a criticizing way (even less in an insulting one), I'm just curious to know what it is that you would want more resources to deal with.  Would you need more coders? more artists? more dialogues writers? or something else? Someone who's hesitating to contribute could be happy to know that his/her job is really needed.

**Comment by jmwall24** [comment]
imo it's art, but I feel that's soon to change and is in fact already changing.

**Comment by Thimeo** [comment]
Because of new artists jumping on the project or of previous ones becoming more productive?

**Comment by ThePotatoGuy** [comment]
art isn't really a problem anymore (except for bedroom mode), right now there's just an issue of getting a stable base sprite set so we don't have to keep going back and changing existing art over and over again.

dialogue review is the bigger issue, we only have 2 people actively doing reviews on reasonable timelines. We have 3 additional people who review dialogue but on very intermittent schedules.

**Comment by Thimeo** [comment]
And what would be the qualifications needed to be a dialogue reviewer? I don't remember seeing the procedure detailed anywhere.

**Comment by Rai99** [comment]
You'd probably have to have a good grasp on Monika's character, have written some of your own topics or helped others, but I think one of the more important aspects is not being a total stranger in the community.  

Also, it would probably help if any topics you've written didn't need a massive rewrite and don't have too many errors. 

You could come in fresh claiming to have experience and skills, but if nobody knows you or has seen you before, that probably doesn't look too good. 

The two active reviewers are I think @jmwall24 and @multimokia. I think they started out as helpers in the discord, became trusted, became the go-to tech support lads, and then I think they were brought onto the team. As for me, I've been laying low for a long time, but along with a bit of A.I. meme status, I've risen up at least a little. Sorry, I'm probably one of the bigger reasons reviewers are in demand since well...  [check my PR list.](https://github.com/Monika-After-Story/MonikaModDev/pulls/Rai99)

I don't know if I count as one of the reviewers on very intermittent schedules, but I usually aim to tackle dialogue contributions from non-OG members (I don't want to bother the OGs like Finale) and I don't know if I was supposed to, but I also left all the old PRs alone. 

Anyway, with the big events like Monika's birthday, o31, d25, nye, vday out of the way, I think review might speed up a bit.

**Comment by kaido1224** [comment]
We appreciate your help Rai.
