### ISSUE TITLE
Monika being 'busy'?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3793]
Like, we open the game to spend some time but she's teaching herself new code or another subject?

She's her own person, so despite all her love for us it's only reasonable that she has her own stuff going on.

**Comment by AsuraShun** [comment]
I don't think this would work since she said she'd always be there for the player

**Comment by Onion-Bubs** [comment]
You get a bit of this sometimes when you open the game and there's a black screen and you're given the option to either open the door, knock or listen. Select listen and you get some idea of what Monika's up to.

**Comment by AsuraShun** [comment]
Did you get one where she is practicing the ''dinner, bath or me'' thing? That one got me good

**Comment by AsuraShun** [comment]
There's also the greeting where she's playing with the code, you'll see a messed up yuri sprite

**Comment by CrocWorks** [comment]
It would be nice to walk in on Monika doing some sort of hobby (besides the singing one I guess). If she's coding, perhaps we could see her moving a bunch of text/numbers around and the room doesn't look like the normal room or something? And since she loves literature, perhaps we walk in on her reading a book? (a book seems like an appropriate gift to give her at some point)

~~Now if only art of this stuff was easy to come by~~

**Comment by ThePotatoGuy** [comment]
I like this. [closing until we look into it]
