### ISSUE TITLE
[Suggestion] Eating/Drinking

### ISSUE THREAD

**Issue by Ulvsblakk** [Monika-After-Story/MonikaModDev#3795]
What if we had an "I'm Eating" Or "I'm drinking" menu where we could tell Monika what we're having and she'd comment about it? We could add multiple dialogues for different foods, so they don't get stale too quickly. 
Just an idea. Let me know what y'all think

**Comment by Rai99** [comment]
Eating with Monika: #1789, #1934, #2164, #3210

As a topic, could be done, as a feature/mechanic, definitely been suggested before and might take some time. 

Can I just say that's a whole lot of possibilities to cover? How many different foods do you plan to include and how do you plan to compress them down into a reasonable selection? 

I see on MASC, you said that you were working on it, and I'm looking forward to seeing how it turns out.

**Comment by Ulvsblakk** [comment]
I've already got the outline for everything functioning. I'm going to open a new issue if that's alright with you, and have an open forum of sorts of what people want included on the list.
