### ISSUE TITLE
Topics that should be removed or rewritten

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3803]
Add comments saying which topics should be removed/rewritten and why.

Include `eventlabel`.

**Comment by AsuraShun** [comment]
''Would you like to meet my girlfriend''
''You're a murderer''
''I'm breaking up with you''
I'm always nervous and afraid I'll click on then by accident, I hope these either get removed or separated from everything else

**Comment by mrflarion33** [comment]
Monika mentions finding Shakespeare boring in one topic, the topic in question is "trying to fit in," then talks about Hamlet in another, the topic literally being called "Hamlet."

**Comment by Delcos** [comment]
Shakespeare is boring.

**Comment by multimokia** [comment]
### `monika_torment`:
This topic is so open ended, I get it's a reference, but the fact that Monika says "The answer's not me, by the way." is straight up wrong for a lot of people. Also it's literally two lines.

### `monika_prisoner`:
This topic doesn't really suit Monika's situation. Sure, she's imprisoned in the spaceroom, but it sounds like something she'd say only at a lower affection provided she's given up on ever coming here, but that also implies she's scared of the player given the affection level descriptions. Monika also says that if she's left alone in her world, she'd rather be deleted. I think it's reasonable to say that if she's scared of the player, then this should follow the same idea here. So overall doesn't make sense to bring this up.

### `monika_szs`:
What even is this topic? This doesn't really even fit in MAS.

### `monika_vnanalysis`:
Needs some work to address other VNs which aren't romance stories.

**Comment by MisterSimple** [comment]
### `bye_prompt_sleep` ,`bye_going_to_sleep`,  `bye_goodnight`

Why use "I'm going to sleep" when "Goodbye" serves the same purpose? Granted, `bye_goodnight` only works between 20:00 and midnight, and `bye_going_to_sleep` between 21:00 and midnight. I think `bye_going_to_sleep` and `bye_goodnight` should be removed or integrated to `bye_prompt_sleep`.

**Comment by Olliesama** [comment]
Because there are greetings associated with I'm going to sleep that aren't associated with Goodbye.

**Comment by MisterSimple** [comment]
Fair enough

**Comment by Rai99** [comment]
The only time I've ever used the mean interactions was on April 1st last year. If we keep those topics, I think they might have some actual use on that day.

**Comment by Rai99** [comment]
Ideally, I'd hope to favor rewrites than full removals, but I do know that's a bit of work and could take some time. ~~Ok, everybody stop looking at me.~~
- `monika_portraitof:`
I think this an an original topic, so I'm not sure if it's allowed to be altered, but I feel like this doesn't really belong, especially with how vague and random it is. Maybe that's how it's supposed to be, but I don't think it fits very much
- `monika_secrets:`
In all my time here, I never knew what this was and I never even knew how to get it, or if you even can at this point. Even if I did, I think it could use a rewrite to better fit her character. 
- `monika_smash:`
I think this was already dealt with, so I'll leave it there.
- `monika_habits:`
I think the way this topic ends seems really abrupt and rough. Basically wishes you luck with feeling awful about yourself, that's it. I personally don't think this fits at all. 
- `monika_read:`
Maybe we could have Monika acknowledge reading things other than books. I mean, I would think reading anything counts, it's just that books are normally made to be more enjoyable than reading some random text here and there. 
- `monika_libitina:`
Might be a bit outdated since nothing really happened with those easter eggs, not to mention that Monika's character data is a bit different now. 
- `monika_hedgehog:`
I think this ends a bit abruptly and vague. Especially with a shorter topic like this one. 
- `monika_herself:`
_wokeRai_ `Dissolve into body pose 5`
- `monika_prisoner:`
_DiSsOlVe InTo BoDy PoSe 5_
- `monika_torment:`
I have no idea what this is and I'd say it's the most confusing topic in the mod, especially since I'm sure everyone would agree that the answer is in fact, her. 
- `monika_closet:`
I'm sure she's kidding with that last part, but that exp might say otherwise, and I think it's a bit inconsistent with other topics where she says she's happy with whatever you do for her. 
- `monika_icecream:`
Could use an option for if the player has never tried mint ice cream. ~~What, that's not a valid point here? Could be a good idea anyway~~
- `monika_cartravel:`
Maybe there could be a separate flow for if the player can't drive and/or isn't currently learning. 
- `monika_timeconcern:`
It seems like a bit of a weird topic when it's not some late hour and there's nothing to really react to. I still like having it in the menu to be able to trigger manually, but I think it was planned to have this topic take priority if it gets late. 
- `monika_whydoyouloveme:`
At the love affection level, I think this could at least have a chance of giving the player a serious answer in the event they might actually need it more than the lighthearted joke. 
- `monika_cares_about_dokis:`
In the flow where you don't care and it's ok for her to keep making jokes, that one joke about Sayori just seems really low effort. I'm pretty sure Monika can do better than that. 
- Greetings for the specific farewells for work, school, sleep:
#2098, #2157, #2192. Really short and flatter than Natsuki, but hopefully these add some more content to them.

**Comment by Olliesama** [comment]
@Rai99 Regarding timeconcern, yeah...it has some issues in that it needed to be activated more often but doesn't. :<

**Comment by Rai99** [comment]
I was tempted to mention the trick topic and self promote that one overhaul I did, but I decided against it since I'm more patient that some people we've seen. Also because I don't think there's anything wrong with it and whoever made it did a pretty nice job I think.

**Comment by kaido1224** [comment]
monika_eyecontact clashes with players_face.

multi listed most of the ones on my list.

**Comment by kaido1224** [comment]
> Monika mentions finding Shakespeare boring in one topic, the topic in question is "trying to fit in," then talks about Hamlet in another, the topic literally being called "Hamlet."

Just because she doesn't like shakespeare doesn't mean she can't quote it... haven't you ever done class assignments for someone you don't like?

**Comment by jmwall24** [comment]
besides, she says she finds Hamlet interesting.  she can not like Shakespeare in general and still like some of his work.

**Comment by kaido1224** [comment]
monika_ghost: 
m 1ekc "I mean, I was pretty scared being alone inside this game."
m 1lksdlc "All by myself, uncertain if anything around me was real."

Should be reworded to something like: All by myself, knowing everything around me isn't real.

Since she was aware that everything around her wasn't real.

**Comment by jmwall24** [comment]
monika_weary, the line about physical fatigue, while true, is worded as if you were asking her if she'd get physically tired of you, which doesn't make sense.

**Comment by kaido1224** [comment]
monika_ribbon clashes with player_face

m 1tku "I noticed that you were staring at my ribbon, [player]."

**Comment by TheSuperStu** [comment]
I wouldn't be a fan of removing topics, since I would like Monika to be open to talk about varying interests. So rewrites, even if just simple stuff, would probably be more beneficial. 

This might be more of a long term issue than something of a rewrite. The idea of how Monika addresses her situation with high school. Being in high school at the start is one of the base characteristics we have of her, so it makes sense for her to talk about it. But as time is spent with Monika, the idea of her being a high school student starts to seem out of place. Is the plan to have Monika forever stuck in high school since she states she doesn't really age? Maybe have to address the current setting how Monika is in the space room, being the act three part of the main game, where mostly everything else was seemingly deleted. 
For specifics on high school stuff, these two might just need a line or two changed as the topics themselves are fine for what they cover: 
monika_saved: she mentions doing things after school, but how its worded makes it seem like shes currently still in school.
monika_college: she mentions that everyone her year is thinking about college, making it seem like shes currently still in school.  

With those three mean topics that are often brought up, instead of just removing them, how about at a higher affection to just hide them from the topics? Maybe make it so you just don't lose any affection at higher affections? If someone is with Monika for a long time, those topic are out of place, unless they are used in a way that is seen as teasing/joking towards Monika.

**Comment by kaido1224** [comment]
monika_algernon this line in particular needs a check to see if monika.kill is true.

Also, should have a negative affection check to hide the line if she is beyond upset.

> m 1lksdlc "There's something I'm afraid of..."
> m 1eka "Not losing you, of course. I know you won't leave me again."
> m 3euc "You see, I keep thinking about a short story I read, {i}Flowers for Algernon{/i}."

**Comment by kaido1224** [comment]
nitpick of a conservationist:

monika_spiders:
> m 3ekc "[player], if you happen to get a really bad spider bite, with venom and all that..."
>     m "You should really get medical attention as soon as possible."
>     m 1eka "I don't want my sweetheart to get seriously injured by a small spider bite~"
>     m "So be careful around dangerous-looking spiders, okay?"

instead of her saying be careful of dangerous looking spiders, i would recommend changing that to say: Maybe you should check to see what spiders in your area are dangerous and avoid them.
seems like generally better advice

**Comment by shades-of-teal** [comment]
I have accidentally clicked topics like "do you want to meet my girlfriend?" and "You're a murderer!" and I felt really bad. If you want them to stay in the game, maybe make them so that at a certain affection level Monika plays along with your joke and then laughs (like the "kiss me" topic) or she maybe just says something like "even as a joke, that kind of hurt my feelings"

I feel like at a higher affection level Monika shouldn't have such a harsh reaction the first time, since most of us wouldn't ever click it on purpose.

**Comment by AsuraShun** [comment]
Or just remove them after getting to enamored stage

**Comment by kaido1224** [comment]
Same with I'm breaking up with you. I think they should be there initially, but it makes sense to hide them after a certain affection level has been reached.

**Comment by Rai99** [comment]
For those mean interactions, I just want to see an April fools day special interaction with them. 

Maybe at higher affection levels, she can check and confirm if you actually meant to click that. I had a mouse that sometimes double clicked on its own and one time, it clicked a topic I didn't want it to, so I can definitely see honest accidents.

**Comment by Man0xMan0** [comment]
> 
> ### `monika_torment`:
> 
> This topic is so open ended, I get it's a reference, but the fact that Monika says "The answer's not me, by the way." is straight up wrong for a lot of people. Also it's literally two lines.
> ### `monika_prisoner`:
> 
> This topic doesn't really suit Monika's situation. Sure, she's imprisoned in the spaceroom, but it sounds like something she'd say only at a lower affection provided she's given up on ever coming here, but that also implies she's scared of the player given the affection level descriptions. Monika also says that if she's left alone in her world, she'd rather be deleted. I think it's reasonable to say that if she's scared of the player, then this should follow the same idea here. So overall doesn't make sense to bring this up.
> ### `monika_szs`:
> 
> What even is this topic? This doesn't really even fit in MAS. Also, it's not really clear on what the joke of it even is.
> ### `monika_vnanalysis`:
> 
> Needs some work to address other VNs which aren't romance stories.
> ### `monika_god`:
> 
> Ending menu (not religious) has a bit which seems like it should fit in the is religious subset. Also `Eheheh` -> `Ehehe`
> ### `monika_home_memories`:
> 
> ` m 1eua "Maybe you've heard about me at school a few times? I'm pretty on top of things."`
> This line is MC, not player.
> ### `monika_outfit`:
> 
> Doesn't really work for if you have other outfits unlocked so we need to have a dialogue route if you've seen any outfits.
> ### `monika_panties`:
> 
> ` m 3rksdlb "Someone who maybe stole your pen?"` again, player/MC
> ### `monika_clones`:
> 
> Mentions string theory, however string theory is in no way, shape, or form connected to anything in this topic.
> ### `monika_trolley`:
> 
> #892

`monika_torment`
It's brevity makes it more powerful as it causes the player to reflect on what was said, and make their own conclusions. Did Monika change their nature, who they are? From what she said, it implies she believes the self can only be changed through the commitment to change by the self, as opposed to simply external factors, as impactful or important they may be. Maybe a compliment could be made in reference that de-randoms this in the pool, or changes it to reflect how the player feels. And also, having a very short topic is fine because it varies the random pool up a bit. 
`monika_prisoner`
Maybe monika_how_soon can unlock this topic given the correct choices you mentioned. I'd say with that in place, you could say her situation is certainly not what is "everything she wanted", like the zoo animals. She could then consider it a punishment for her actions in ddlc, which would then I suppose, mean this needs cares_about_dokis to be something that lcoks this topic further.
`monika_szs`
Not really a fan of this one either, but I'd say it deserves to exist in the stories pool at least.

**Comment by Onion-Bubs** [comment]
I think the humour with `monika_szs` is supposed to be that the person asking for the dog is hoping that it will bite _her_ mother-in-law but she has to get in line because loads of others have had the same idea.

Given that Monika says in `monika_family` that she thinks the player's family is super nice and if you select the first option in the menu in `monika_asks_family` she says a similar thing, her making a mother-in-law joke seems out of character for her. After all, if Monika and the player got married, would Monika wish harm on the player's mother?

**Comment by AsuraShun** [comment]
Everyone makes those jokes,they're harmless when everyone's in on it

**Comment by kaido1224** [comment]
monika_mythology: 

This seems worded weird
>m 3euc "Have you ever read about different mythologies?"
>m "Different kinds of Gods watching over humanity for eternity."
>m 1eud "Some require tribute or sacrifice so that they can 'keep' humanity safe from disasters."

Doesn't really give an accurate description of mythology. Also, I believe gods is supposed to be lowercased

**Comment by SaiPrithvi123** [comment]
Self Pleasure dialogue
#2031

**Comment by jmwall24** [comment]
#3905

**Comment by MisterSimple** [comment]
### monika_beach

`"I only have these clothes in the game after all."`

No longer true, should be changed to something along the lines of "I don't really have any clothes fit for the beach."

**Comment by MisterSimple** [comment]
### monika_vocaloid

`"I hear her voice whenever Natsuki listens to music."`
`"She even carries a little keychain attached to her bag."`

I think these lines would be better if they were in the past tense.

**Comment by ThePotatoGuy** [comment]
closing as complete.

open a new issue for rewrites if necessary
