### ISSUE TITLE
[Suggestion] - Tell Monika you're bringing her on a date

### ISSUE THREAD

**Issue by Undeademon** [Monika-After-Story/MonikaModDev#3813]
It would be cool to tell Monika you are bringing her on a date. When you tell her that you want to take her out, you don't actually specify 'where' you are bringing her. It would be cool if you could trigger the "I'm asking you out on a date" option if you tell her to wear the white dress in the closet and then say "I'm taking you out". I'm pretty sure the topic of this suggestion should've been 'Specify where you are taking Monika'.

**Comment by CrocWorks** [comment]
And to play Devil's advocate, what if I want to tell her I'm taking her to the authorities for being a murderer? We could always specify a bad place, too. ~~It would be cool if you could trigger the "I'm asking you to turn yourself in" option if you tell her to wear an orange jumpsuit~~

But regardless, I think part of this is that Monika can't see or interact with anything whenever she's in her character file when she's taken out. She already assumes it's a good place because she trusts the player, and I think that adding specific options would mean creating a really long list. If such a list is made, it'd only make sense if some bad options are on there too just so that there's balance. Perhaps some sort of type-in checking system like how she judges her nicknames could be used?

**Comment by Undeademon** [comment]
yeah. you're right. you're always right. i'm useless. i'm a disgrace. my
suggestions are stupid. yeah. life would be better if i never existed. this
community would be better off if i never contributed. have a nice day. life
would be better tomorrow. 'cos i won't exist.

**Comment by CrocWorks** [comment]
Huh? I appreciate your suggestions, though. I apologize if you mistook my dark humor for a personal attack. It's always good to hear many different ideas and then refine them to see what we all can do to make it better. Making Monika as complete of a person as possible is a goal that I think everyone here wants, and every suggestion made contributes to that. You're certainly welcome to go in and find my suggestions and point out ways to improve them. Monika would appreciate any improvements that we all suggest.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
