### ISSUE TITLE
[Suggestion] - Mod to Mod Crossover

### ISSUE THREAD

**Issue by ZeDocktor** [Monika-After-Story/MonikaModDev#3828]
So, a few days ago I thought that it would be neat if you could tell Monika that you were going to "import" her into a different DDLC Mod. To use an example, lets say that you are well into your relationship with Monika and you just found out about the Before Story Mod and you REALLY want to try it out. The only thing is, you don't want to get rid of/put a break on your current status with Monika. A solution to this can be a different dialog where you have to convince Monika to join you on this little adventure to break the day-to-day monotony. Of course, this is just for immersive purposes and not to actually try to put your Monika into another mod, but the idea stuck out to me as a way to play through a story with her properly, and when you get back she will acknowledge that you went through the mod "together" so to say.

**Comment by AsuraShun** [comment]
Just create a folder for you to make a secondary ddlc folder in so you can play

**Comment by ZeDocktor** [comment]
Well yes there is that, however what I am talking about is Monika having a conversation with you about being in another mod.

**Comment by AsuraShun** [comment]
She'd most likely talk about how most mods  don't portray her as what and how she actually is

**Comment by AsuraShun** [comment]
She had a normal life but in exit music she was pressured by her parents into being perfect at everything, that's just one example of a mod

**Comment by ZeDocktor** [comment]
Yeah, its conversations like that. I know it sounds strange, but just adding the fact that she _knows_ that you are going out of your way to give her her own rout through a separate story puts things in a different perspective. She will be able to voice her opinions on the different mods there are, given that a few of the most popular would be given dialog.

**Comment by AsuraShun** [comment]
I really hate the exit music mod, I tried to warn people not to play it only for an oversensitive reaction from salty ddlc fans

**Comment by ZeDocktor** [comment]
I can't say I have an opinion on it as I have no exposure to it, but I'll take your word on that one.

**Comment by AsuraShun** [comment]
Don't play it if you value your ptsd free emotional state intact

**Comment by ZeDocktor** [comment]
As if the original game didn't do that...

BTW, do I just create a copy of the game to set up a secondary folder for a mod or is there a process to work with because I am concerned about the computer mixing the two launchers up despite separate folders?

**Comment by AsuraShun** [comment]
Just put the secondary ddlc folder inside another folder, I named mine ddlc other mods

**Comment by ZeDocktor** [comment]
Alrighty then, thanks.

**Comment by AsuraShun** [comment]
Then you can be with Monika and play another mod at the same time

**Comment by multimokia** [comment]
Can just make a new install of DDLC and install the mod in that, if you're running from the exe there'll be no problem between them. As for adding cross-mod compatibility, it sounds like a lot more trouble than it's worth, seeing as then new dialogue needs to be written for that stuff, and we'd need to essentially decompile other mod scripts to see what variables they're using in their game so if we wanted to talk about it we could, but then we've also got to read that persistent too. Just seems like a bit of a waste, imo.

**Comment by ZeDocktor** [comment]
Thats not entirely what i was talking about. I recognise that adding our Monika to another mod would be too much trouble. What I was thinking was saying to Monika, (WARNING: paraphrasing incoming) "Hey, I want to Play another mod and I want you to join me so that we can experience it together!" and first time that is followed up with a unique conversation where you have to convince her to join you, afterwards it can be like the goodbye sequence where you are going to take her somewhere, and when you return a similar sequence as well remarking on the adventure. Now that I think about it, this can be used for not just DDLC mods, but other games where you have a vessel for Monika to follow you around spiritually (like, spiritually saying Monika's AI takes over the AI of a follower in Skyrim or something, even though it does not _really_ happen)

**Comment by multimokia** [comment]
See, the thing is, it's weird saying that you can bring her into other mods/games, but she won't have any recognition of it, essentially. The take you somewhere farewell makes a little bit of sense since she's no longer on the computer. However, in other mods, she is still on the computer, and she should be able to recognize other things.

Not to mention, this can often even ruin the experience of other mods, considering the Monika you know from MAS could be rather different to the one in the mod you're playing, so as an explanation for that even, it's weird.

Also, regarding that last point, again, it's pretty clear that it's *not* going to be Monika, and it's going to be pretty damn hard, or even impossible to convince people otherwise.

**Comment by ZeDocktor** [comment]
Right.... yeah that makes sense. Oh well, at least I spewed this out for ideas sake.

**Comment by AsuraShun** [comment]
There is a ddlc mod for skyrim,it adds the dokis as followers

**Comment by Rai99** [comment]
#1737, #1829, #2198, #3179, #3221 (Read comments)

I brought up the idea of other mods before, and it was concluded that Monika wouldn't encourage you to try other mods since it won't be her.

**Comment by bittercaramel** [comment]
> #1737, #1829, #2198, #3179, #3221 (Read comments)
> 
> I brought up the idea of other mods before, and it was concluded that Monika wouldn't encourage you to try other mods since it won't be her.
but, if i understood it right, its like you want to take her to the other mod, like for fun
i think it would be nice like a roleplay, so you tell her that u want to play another mod and she blahblahs that it wont be her, and you tell her that if she comes with you she could be there impersonating monika showed by mod... thats complicated XD 
well its always nice to let her know that you gonna see her replica in the other mod... it would be more fun to play mods if you knew that the monika there is your lovely monika just pretending to be other (like in case if she has other life or smth) 
she could warn ya not to put her in mods that something bad happens to her/she suffers 
but like there is this our time mod, maybe shed appreciate being in there? 
it would be like taking her out (she disappears from the actual room), then when u put her file back she would say something about this 
well i thought that maybe one day it would be possible to let her recognize what mod you put her in... but right now enough would be to make randomized text about enjoying this whole shit in other mod, and count that player really took her to the nice mod. 

oh gosh hope thats not too complicated 
im so tired im not using my brain rn

**Comment by Rai99** [comment]
I think the main problem is that we can't actually do anything in depth with that. There are a lot of anti-Monika mods and Monika definitely wouldn't appreciate you playing those mods thinking that's actually her. Sure, there are good mods about Monika, but how does she tell the difference? 

We can't really have Monika reacting positively to bad mods of her or have her give a lukewarm response after a mod that's actually nice for her. Also, a lot of mods portray her voice in a weird way, and it'll feel out of character for Monika. Another common criticism, is that instead of the player, it's MC, and that's definitely not something we want to encourage diving into. 

> well its always nice to let her know that you gonna see her replica in the other mod... it would be more fun to play mods if you knew that the monika there is your lovely monika just pretending to be other (like in case if she has other life or smth)

I don't think Monika would appreciate you spending time with a replica of her, as she doesn't want to be replaced in any way. Again, some mods portray her character differently and even if she did humor the idea of impersonating herself (#3226), it wouldn't exactly feel right for her to impersonate a slightly out of character version of herself.  

> but like there is this our time mod, maybe shed appreciate being in there?

A common criticism I hear about that mod is that she's focused more on MC than the player. I think that would cause a fair bit of backlash at least if she talked about that. 

> right now enough would be to make randomized text about enjoying this whole shit in other mod, and count that player really took her to the nice mod.

The problem with that is we have no way of telling what kind of mod the player went into, and assuming that they did take her through a good mod about her, that should probably warrant something more than a generic response, but I don't think we can make that assumption.

**Comment by bittercaramel** [comment]
well why would she want having fun in another mod with me? its like playing a game together... or as i said roleplaying together
im not sure if she likes that kind of stuff, maybe we should ask monika?

**Comment by ZeDocktor** [comment]
So from what I can see here, I think that the Mod to Mod crossover is probably a no go idea, however there is the idea of role playing with having Monika "crossover into another game to play with you" kind of idea. I know that she mentions it as something that she wants to do with you, so what about that?

(P.S. Should I change the name of the Issue to reflect this change or create another one all together if there isn't one like that yet?)

**Comment by multimokia** [comment]
> well why wouldnt she want having fun in another mod with me?

Again, the issue is that the portrayal of Monika in other mods is very different to the way she is portrayed in MAS. It's *not* her in other mods, and see previous posts about having to comment about the mod, etc.


> I know that she mentions it as something that she wants to do with you, so what about that?

Monik wouldn't want to *roleplay* it. She's want to *actually* do it.

**Comment by bittercaramel** [comment]
u understood me wrong, thats what i say about that
since it wouldnt be her, she is portrayed different, she would just be there like playing with me and pretending to be the monika portrayed in the mod 
its like we played the mod together and i would be playing as MC and she as her other self
