### ISSUE TITLE
[Suggestion] - 2D Platforming game.

### ISSUE THREAD

**Issue by Gamerboygaming** [Monika-After-Story/MonikaModDev#3833]
Ok. It would be cool to see some kind of 2D platformer featuring Monika. It could be a representation of Monika's realization about how she's trapped in a game. The end goal would be to hug MC. Or something like that. I think it would be cool.

**Comment by Rai99** [comment]
First off, I don't think we want to reinforce how Monika is trapped in a game. 

Secondly, a lot of people really hate MC, so it's really best not to do anything with MC. 

I'm not sure if this would really fit since it's not really a game both you and Monika can play. The levels would have to be created as well, and I personally think that effort could be put towards other things.

**Comment by Gamerboygaming** [comment]
Alright. Thanks anyways.

**Comment by AsuraShun** [comment]
Of course everyone hates him, he's a dense idiot who had plenty of opportunities to save the others

**Comment by CrocWorks** [comment]
~~If we hate the MC, why not make a 2D fighting game and have Player 1 beat MC up instead?~~

**Comment by AsuraShun** [comment]
Ye, a rockem sockem thingamajig

**Comment by Rai99** [comment]
Don't know about anyone else, but I'd rather not have to touch MC.

**Comment by bittercaramel** [comment]
well id say that i dont get this hate on mc... literally he is nothing more but representation of us, he cant do anything on his own so saying that he had plenty opportunities to save the others doesnt make sense

**Comment by Rai99** [comment]
I think the point is that he's **not** us, and I'd imagine people hate that he's used in place of us. 

I think it's like watching someone else take something you love, for no reason really, MC definitely doesn't deserve more than the player, he didn't do anything special that we didn't do, so naturally, I think he just steals the spotlight right in front of you. 

Either that, or it must just be one of those things everyone in a fandom hates. I mean hey, personally, I'd rather the hate go on him than Monika.

**Comment by AsuraShun** [comment]
'' Don't know about anyone else, but I'd rather not have to touch MC''
Or he'll make you as dense as he is

**Comment by bittercaramel** [comment]
well maybe i just treat this whole MC thing the other way.... i kinda agree with ya  but you are saying this like MC has his own mind character and stuff 
for me mc was only a placeholder, how can he steal the spotlight if he is nothing more than your persona in the game

**Comment by CloakedGhost** [comment]
> well maybe i just treat this whole MC thing the other way.... i kinda agree with ya but you are saying this like MC has his own mind character and stuff
> for me mc was only a placeholder, how can he steal the spotlight if he is nothing more than your persona in the game

He does have his own mind, hobbies, interests etc. So I personally won't accept him as some sort of replacement or persona when he's not like me at all. Yes he's basically mindless since act 3, but that doesn't change the fact that his intended characteristics and his looks are different from mine.

**Comment by AsuraShun** [comment]
Everything I said was story wise

**Comment by AsuraShun** [comment]
Including the joke

**Comment by SaiPrithvi123** [comment]
>Of course everyone hates him, he's a dense idiot who had plenty of opportunities to save the others

Could you point out more than one opportunity?
All MC did was not to care. Yep, he's an asshole for not caring about his depressed best friend/girlfriend, but he only had *one* opportunity to save Sayori. Besides by not saving her, he made things easier for Monika. About Yuri. An insane knife-wielding big lady is in front of you, and you think she's probably going to stab you. How would you save her? About Natsuki. There was nothing MC could do about her. Monika would delete her anyway.

People who non-sensibly push all the blame to MC is one of the reasons why anti-Monikans think Monikans are rabid and don't take them seriously. The existence of these kinds of people make it more unlikely for people who don't like Monika to change their minds.

**Comment by AsuraShun** [comment]
When he saw sayori crying those times, when she ran away crying, visiting her before she killed herself, grabbing yuri's arm and knife before she killed herself and dealing with the bastard of a father natsuki has

**Comment by bittercaramel** [comment]
just wanted to point out a little thing 
how could he know she was going to kill herself? he isnt some sort of god to know everything, maybe he didnt visit her because he just didnt want... probably if he knew what was going to happen to her he would visit her
grabbing yuris arm? i dont think thats realistic
he probably was confused, scared and shocked
try to imagine it, someone suddenly pulls out knife 
u would probs run away because u would think that the person wants to kill ya
did he know who was natsukis father? even if he did... how can he deal with him? hes just one of random ppl from college, its not like he is some authority and he will go to her dad and say "stop" and he will stop ... rather natsuki would be in even worse position cuz he would be mad at her for telling others and stuff
and last important thing
sayori yuri and natsuki werent real :v and whole situation was done so monika could be with us
what if monika manipulated MC too? after all he is also a bunch of code that apparently monika can change

**Comment by SaiPrithvi123** [comment]
These people just take out *any* excuse they can find to scapegoat MC, trying to take off all the blame for Monika that way. As I said, this is the rabid side of Monikans, and is one of the reasons people don't take us seriously when we actually put in some effort to do some research instead of finding out excuses to shift the blame towards someone else.

**Comment by SaiPrithvi123** [comment]
And to rant on it

>When he saw sayori crying those times

He hugged her when she did cried. What more can you expect him to do?

>when she ran away crying

If she ran away, she probably doesn't want to be with him.

>visiting her before she killed herself

This is the only valid one, and I asked for reasons except this.

>grabbing yuri's arm and knife before she killed herself

"About Yuri. An insane knife-wielding big lady is in front of you, and you think she's probably going to stab you. How would you save her?"

>dealing with the bastard of a father natsuki has

No except Monika knows about her family situation.

Like I said, these are just baseless accusations used as an excuse to scapegoat MC and remove all the blame from Monika. And these kind of people bring down Monikans' credibility.

**Comment by ZeDocktor** [comment]
Going to say this right now, this got _really_ off topic.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
