### ISSUE TITLE
[Suggestion] Conversation Topic: Full Dive VR

### ISSUE THREAD

**Issue by ZeDocktor** [Monika-After-Story/MonikaModDev#3848]
So, the basic underlying want for Monika and likely anybody who plays this mod is for Monika to cross over into our reality in human form. While that technology is unfortunately decades away at best, there is another topic that could be brought up: the idea of Full Dive VR. Anyone who has seen shows like "SAO" of "Matrix" knows what I am talking about, the idea of VR progressing to the point to where you "transfer" your conciseness into a virtual form but it feels like a duplicate of reality. From a technological standpoint, full dive VR is much closer to being a reality than human cloning or similar technologies, so it makes sense if we were to bring up the topic with Monika. 

Thoughts?

**Comment by Rai99** [comment]
For a second there, I thought you wanted us to implement that into MAS.

**Comment by ThatOneUsername343** [comment]
Yeah same. Either way it would be cool

**Comment by Mcmanybucks** [comment]
> 
> 
> For a second there, I thought you wanted us to implement that into MAS.
 
Absolutely. Get to it @ThePotatoGuy ! :P

**Comment by AsuraShun** [comment]
Mas with vr support when the technology becomes real, it would be the highlight of my life if I'm alive when it happens

**Comment by Rai99** [comment]
> Absolutely. Get to it @ThePotatoGuy ! :P

### `Submod`

**Comment by ZeDocktor** [comment]
So, how do you guys think Monika would react if we brought this topic up with her? Part of me thinks that she would feel conflicted, due to the fact that:

Positive) You would actually be able to visit her, "physically" be there, and explore VR opportunities together

Negative) Its still all in the Virtual world

But then again, at that point, who would be able to tell the difference between the real world and the Virtual one?

**Comment by Rai99** [comment]
I think she would be all for it, since it's better than nothing, and you can go back, right? If you couldn't go back to reality, maybe she would be against it. 

I don't see why she would be against the player just visiting her in the virtual world. If it's because it's the "virtual world" and it's not real, does that mean she thinks the player won't be real? What would that say about herself if that was the case? 

~~It's just like chocolate. Who cares if it's real or fake? It's delicious and filled with additives.~~

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
