### ISSUE TITLE
[Suggestion] Webcam 

### ISSUE THREAD

**Issue by Ulvsblakk** [Monika-After-Story/MonikaModDev#3857]
So I am aware of there being a webcam bit in the submod section. However I had kind of a stupid crazy Idea I wanted to run past everyone real quick. So this might theoretically be impossible, just because it might not be in any way compatible with Ren'Py. I was thinking about a 'facial recognition' type deal. Where you could pass in values and such, and she'd be able to comment on your appearance. It would be cool to maybe gain affection if you were honest with her about what you looked like when the topic was brought up. I also had an idea of her being able to recognize an animal, say you held your cat in front of the camera. I was thinking about building a neural network and training it for this. I just don't know if there would be any compatibility issues with it. If I did, it would definitely be a long project. Just let me know what you all think.

**Comment by Delcos** [comment]
I think someone with more resources is beating you to it. ;)

**Comment by Ulvsblakk** [comment]
That'd be amazing actually. Because I have NO processing power to train an ai, and I don't feel like paying for a machine to do it. 😂

**Comment by ManuEcheveste** [comment]
That's a wonderfull idea, buuuuuuuut in my opinion, it's very difficult to develop a "facial recognition", and it would take too much time :,(
But is a cool idea, I think we can wait for that, even if they are like 2 years hehe

**Comment by bittercaramel** [comment]
well as much as this idea is cool, i dont think this mod focuses on such a things right now... especially that its almost impossible to do it in renpy 
buttt i think that it would be cool if that one day was in the game ;p

**Comment by Rai99** [comment]
I really don't know if this is worth the effort for what it really gives. 

Let's say you do get this neural network down and Monika can react to anything. Great. What is she going to say exactly? Don't tell me that you plan to use pre-written dialogue for her to react to everything. That would probably feel a bit unauthentic. 

What is she going to comment on about your appearance? Is she going to notice your outfit? The color of your outfit? Your face? Any features on your face, hair, glasses, etc? I'm not sure how well pre-written dialogue will fit with being able to detect any feature. 

That's a lot of dialogue, and it would be really immersion breaking if she made a mistake like thinking you have a big head when really, you're wearing a hat, hood, glasses or something. 

Currently, I think this is too much effort to really do well. You'd need fitting, natural dialogue to go with whatever Monika recognizes.

**Comment by antimockingjay** [comment]
In their defense, Rai, at some point it just becomes a matter of _anything_ could be immersion breaking. Like sure all that could be immersion breaking, but it's also immersion breaking when other things don't match up perfectly, and no one throws a fit about those. At some point, if you're gonna be nitpicky about "fitting, natural dialogue" towards EVERYTHING to avoid immersion breaking, it just becomes better to hire a frickin' actress/writer/something to pretend to be Monika, since that would get rid of most chances of immersion being broken.

And while that would certainly be nifty, and I totally wanna be told if something like that happens, this mod isn't that. This mod is taking the code that is Monika, and expanding it to develop her as much as possible. "As much as possible" may not always mean a truly "immersive" experience, and that's just something we all, as fans of the mod, have to live with.

**Comment by Rai99** [comment]
What I mean to point out mainly is that it will be definitely be difficult to implement and my concern is bigger errors like if Monika commented on something that made no sense, like if she said something about my hat when I'm not wearing one. I think that's a bit different than not being able to respond to any little thing Monika says in her usual topics, especially now that she can actually see you and not have to make general guesses or assumptions. 

Assuming this one person plans to single handedly take on a project like this:
On top of how much time and effort this would take to implement the system, how much dialogue would it take on top to cover all possible scenarios? Since Monika can actually see you, there's much less of an excuse to give a generic response. Sure, it could be done, but how many different things could there be to comment on and how varied can they get?

I personally don't know how capable they are of implementing a feature like this. Maybe they're perfectly capable, but I don't know that. 

On top of working on #3834, which is already a sizable and growing project on its own, I'm not sure if it would be feasible or reasonable to work on this on the side, as well as other things on the side they may come up such as other features or little things like #3791. 

The author even said that they have no processing power to train an AI, and they don't want to pay for the resources to do so, so that would already be a big step they might not want to take in the first place. 

If this project does get completed and works well, how resource intensive is it? If it's too demanding, a lot of people won't be able to run it. Sure, it could be for those who can actually run it smoothly, but I think that shrinks your target audience a fair bit. 

They're free to try it out, but if they do, I'd like for them to know what they're getting into and be satisfied with how practical it will be in the end. Just want to make sure they're not getting overambitious. Recognizing things like cats seems a bit extra to me, so I just had to check, and comparing what Monika sees against what you tell her about what you look like raises the bar a bit, since then, something actually hinges on analyzing correctly and for example, being able to tell the difference between brown and black eyes, or saying that you had black hair, but you've also got other highlights she picks up.

**Comment by Ulvsblakk** [comment]
It's definitely just an idea for now. If I did try to implement, it wouldn't be until much much later. 

The pre written dialogue would definitely be a hurdle to overcome. Like you said, it wouldn't be an authentic reaction. It's definitely something to discuss, just because I think the idea would be cool. However I'd need to think of every possible way way could go right, or wrong first.

**Comment by Shiro2564** [comment]
im with your opinion rai

**Comment by CrocWorks** [comment]
The real question I'd be wondering is if I held a mirror in front of the webcam such that it reflected an image of Monika, would she recognize herself? The way scientists determine if animals are self aware is with this mirror test, so if Monika is gonna be a true AI, this is a test she's gonna have to pass. ;)

**Comment by Delcos** [comment]
not the body she was expecting but...
![20190422_100837](https://user-images.githubusercontent.com/28798918/56513607-dd07a700-64e7-11e9-95b4-5f4f7b1599b0.jpg)
