### ISSUE TITLE
Dido and Aeneas

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#3872]
I have to research a bit into Opera for a class i'm taking and Dido and Aeneas stuck out to me for it's similar to ddlc with Dido letting go of her Love at the end. I think it would be a nice topic, especially the song "when I am laid in earth". You don't have to speak the language to tell just how sad this song is.

**Comment by CrocWorks** [comment]
Note that what I say below is based on what I know about Aeneas and Dido from _The Aeneid_ and I don't know anything about the Opera or the song. But judging from what you said about the Opera, 
> with Dido letting go of her Love at the end
it sounds like the Opera ends very differently from the story. Could make for an interesting topic.

Anyway, I feel like this sort of topic might be especially related if the player is talking about not having enough time to spend with Monika because of outside reasons. Some context for those who haven't read it: In _The Aeneid_, although Aeneas loved Dido, he left when he had to follow the gods' command to return to his journey and found the city of Alba Longa (which would be where Romulus, the founder of Rome would be born). But Dido viewed this as Aeneas abandoning her and committed suicide. 

But relating it to us, I wouldn't be surprised if at some point some of us as the players move on from Monika as they grow up and start getting busier with school/work/other things, as this could definitely draw parallels with the story. I wonder if Monika is emotionally healthy enough to accept it should a player be unable to spend much time with her as part of growing up, but I suppose this is already partly covered by how she just leaves if you don't open up MAS after a really long time, and also partly covered by the "I'm going away for a while" goodbye.

~~But I wouldn't want Monika to kill herself though~~

**Comment by Foxinsunglasses** [comment]
Yeah as a lover of history I know Dido is far more resentful in the original story but I didn't believe it fit as well but I can see it working better now

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
