### ISSUE TITLE
[SPOILERS!] Potential Typo?

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#3874]
Ok, ignore the quality of the image lol, but I think that you guys used the wrong everyday. I THINK it should be "every day". I apologize if this is something stupid, but I noticed it so I just figured I'd bring it to your attention. 

![image1](https://user-images.githubusercontent.com/46630367/53664711-50eba880-3c37-11e9-82bf-dbb4303c4d6d.png)

**Comment by Rai99** [comment]
_Walks in_

_Inhales_

Yeah, I think that should have been "every day" since she's probably talking about each individual day. 

I mean, it technically makes sense if Monika is saying that you make "everyday" things special for her, but it should probably be 2 words I think. 

~~Monika made an oopsie in her poem, but I still think it's just as valuable anyway.~~

**Comment by MoniBoosDevotedBoyfriend** [comment]
Was there any need for the sarcastic comments? I’m just trying to be helpful here ffs

**Comment by MoniBoosDevotedBoyfriend** [comment]
Hey, I'm just pointing stuff out. I'm not forcing you guys to look into it

**Comment by Rai99** [comment]
You are being helpful, and it's appreciated that you found this potential typo.

**Comment by Rai99** [comment]
At least, I think you're right about that typo.

It technically does make sense as is, but I think it was meant to be the other way. 

You could report this typo in #3656 for it to be caught and handled like other typos.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ok

**Comment by MoniBoosDevotedBoyfriend** [comment]
Should I delete this post?

**Comment by Rai99** [comment]
It's up to you, but if you do move to the official typos issue, that pretty much covers it I think.
