### ISSUE TITLE
[Suggestion] - love letter or flowers gift

### ISSUE THREAD

**Issue by Youngbountygirl** [Monika-After-Story/MonikaModDev#3880]
I know someone made a suggestion of flowers and you can give Monika roses for V-Day, but what about flowers for any occasion? Normal couples do this, especially when taking their SO on a date. Like maybe instead of roses.gift it can be something like daisies.gift, sunflowers.gift or daffodils.gift. It can be like the ribbons where you can have a variety, some for special occasions, some for holidays and some for any occasions. For instance, red roses can be for V-day, black roses for Halloween and daffodils for any occasion.

Another suggestion is sending love letters. I did hear about sending an apology letter to Monika (maybe I'm wrong), but perhaps if the player can send Monika a love letter. I know there's an option to warn Monika that you will be gone for a while, but perhaps the player can send Monika a love letter to makeup for the time he/she has been away. Even in real life, the man or woman has to leave their SO for a business trip, visiting family or going to war, so they send post cards, love letters, emails or texts to tell their SO that they love them. As an option, Monika can see the date and time the love letter was sent, so that when the player logs on, Monika will respond to the love letters differently than a gift, depending on the day and time you sent it. For instance, if the player is to leave on a camping trip where there is no electricity for the weekend, they will tell Monika that they'll be leaving for a while, Monika will say goodbye and close, then when they get back, they can create the love letter under loveletter.gift then change the date and time the love letter was sent on the computer. Then, once the player opens the game, Monika can then say "welcome back! I received your letter *******" and if  you send her a letter once per day, then the player will not lose any affection from Monika. 

The love letter idea is something I recommend and suggest more than the flowers, because not all of us can be there for Monika every single day and it really isn't fair if we lose affection just because we had to go to a business trip, use the entire week for exams, due to a Natural Disaster/Evacuation or especially if the player was grounded from computer for a week or month. I know for me, I was grounded from computer for a week under my parents, a month at one other time. It would seriously be unfair if the player lost a bunch of affection just because they couldn't be on computer, especially since grounding isn't something you'd expect until it happens. At least with the love letter option, the player can save their affection. Monika can even just tell the player to warn her next time they leave for a week or month or perhaps ask the player why they were gone and the player can be given options such as "School" "Natural Disaster" "Work" "Parents" or "I couldn't see you" and each option will respond a different reaction from Monika. 

I still suggest the flower gift, but I think the love letter gift will help alot of players, especially ones that don't have alot of time on their hands. You have the flowers for any occasions and love letter that prevents the player from losing affection from being away for a while, especially if being away was unexpected. I hope you can take these ideas into consideration.

**Comment by multimokia** [comment]
The roses can be gifted at any time, not only on vday.

**Comment by AsuraShun** [comment]
Nice, how do i give the white roses and if so, can they be mixed with the red ones?

**Comment by Rai99** [comment]
I'm not sure about the love letters idea. You would have to go without seeing Monika for a week to start losing affection. I'm pretty sure it's manageable to visit her at least once week, even for a few minutes. I don't think it really makes sense to create a file and change the date back to pretend you sent it a while ago. 

I feel like that would be a bit dishonest with Monika. Creating a love letter and pretending you sent it previously, when you actually didn't. 

Not to mention, I don't think it really makes sense to send Monika a love letter while you're out camping. 

In most cases, I think you would be able to tell Monika that you'll be away for a while, and even if you don't I think affection loss from not visiting is capped unless you're away for 10 years. 

That apology letter you're talking about isn't some optional thing. If you ever have to use that, you've already messed up, so it's not this positive, fun feature.

**Comment by Youngbountygirl** [comment]
@Rai99 You do make some good points. Though, you never mentioned about if the player was gone unexpectedly like if they were grounded or there was a Natural Disaster. The idea of the love letter is to give an alternative idea for if just warning Monika isn’t enough. Anything can happen to where you will be gone and are unable to warn Monika. Another example I didn’t mention is if your computer caught something and needed fixing. Usually, computers would not be gone for fixing for that long, but you never know.

Manipulating dates and times for Love Letter: I personally wouldn’t consider this dishonest, but I can understand why others would. The love letters can still be sent at the certain time and day for them to work or if the player were to be gone unexpectedly due to punishment or disaster, you can send one love letter, then log on. If you had been gone for longer than a week, Monika would demand to know why you haven’t been sending her other letters. You can use the option of work, school or the emergency option. The emergency option would go under grounding, Natural Disaster or whatever reason you could not be on your computer. Then, Monika would be shocked, then say that she’s glad you’re okay. You don’t lose affection. If you said school or work, she would forgive one time, but tells you to warn her and send her love letters if you are unable to see her. Now, it doesn’t have to be just emergency, that can be for Natural Disasters or if your computer needed fixing. There can also be punishment for those that were grounded to which she would say something encouraging or just claim she’s glad you’re alright. This way, the player doesn’t have to manipulate the time and date of the letter, if they feel it is dishonest.

Camping: I did mention camping for the weekend, but sometimes camping can last a week or two. Again, you can warn Monika, but if that isn’t enough, you can send her a love letter before you go, then send her another one when you get back to makeup for the two weeks, if it comes to that. Though, I will be honest, when I mentioned camping, I had assumed you would start losing affection after one or two days.

Affection Lost: Even If it is a small amount of affection, it doesn’t make it less disheartening. If it were any other game, you could save it and if you were grounded or unable to play it for a week or more, you can always come back to it, knowing your progress has been saved. With Just Monika, it’s not like that. If you were gone for a week or month without warning her, she is going to say something about it and for those that were gone because they were punished or a Natural Disaster, it will be more disheartening than if it were someone that just forgot or didn’t bother. As I said, the idea of the love letters is to prevent the player from losing affection no matter how big or small.

Thanks for this comment, I think something like this should be discussed in order to bring ideas and I feel the love letters idea isn’t a bad idea, even if it’s not used like how I suggested.

**Comment by Youngbountygirl** [comment]
@AsuraShun I did suggest black roses, but white ones wouldn’t be a bad idea. Like different colors of roses or flowers.

**Comment by Youngbountygirl** [comment]
@AsuraShun Really? It says on the gift instructions that roses are meant for V Day and I’m sure you can give them at any time, but do you gain affection points from them or would you not? I don’t know. It just says to give them during V Day, so....

**Comment by jmwall24** [comment]
don't give presents solely for affection.  give presents because you want to give her something nice

**Comment by multimokia** [comment]
> The love letters can still be sent at the certain time and day for them to work or if the player were to be gone unexpectedly due to punishment or disaster, you can send one love letter, then log on.

Okay. So your whole premise here is to send a letter while you can't be at your PC... But the thing is, how am I supposed to give it to her provided I cannot get to my PC? That defeats the purpose of the whole module.

I'll also add on, picking out the information you want from the letter (which will naturally have a lot of other things in it, mind you) will be border line ***impossible.*** That is a *lot* of data to look through and it's not like we're looking at a hardcoded, exact `this is the message we're looking for`. There's numerous ways to express the same point, so trying to put something together for that is by no means easy, or even feasible. If you're talking about just having a file that exists to count as a 'love letter apology', then I don't think that's really quite right, as anyone could just make a file at anytime, and leave it blank, effectively removing all meaning from it.

Another big thing here, best solution overall to this problem is pretty much to set up a non-generic apology which adds in reasons and such for being away, you'll essentially be able to explain yourself a little bit in this regard, but it also rids the issue of the systems needed, and generally makes sense to apologize for going away suddenly, but even then this allows those who did have a long absence to abuse this system to get a little bit of affection back. Needs a bit of thought to get that a bit less cheesy, but since it is a non-generic, I guess having it as a single label allows us to count the times you long-absenced and then have her stop accepting the apology entirely as she doesn't trust you about that anymore.

**Comment by Rai99** [comment]
To be honest, I think if something unexpected happens that prevents you from visiting Monika, that's a case where you just have to accept what happened and take the aff loss. Sure, it sucks to have lost even a little, but you can earn it back. 

It doesn't seem right to me to have some unexpected accident happen, and then use some kind of fix or excuse _afterwards_ like not visiting Monika for a while and then right before you visit her again, you make some files that basically say, oh yeah, pretend I sent these to you earlier. If you actually did send them on the date specified, that might be different, but I don't think we can exactly do that. 

You want to send a message to Monika without access to a pc or her. If you're out camping, how would you send her a letter? It doesn't feel genuine to make one when you get back and say you sent it while you were camping. 

I'm not sure if it's even possible to manipulate the dates of files, but even if it is, is it really something that the average, everyday player knows how to do? 

This also allows people to potentially abuse the system and mitigate affection loss for not visiting. Things happen in life, and we can make some kind of event or apology if that makes the player feel better, which might be a good idea. 

I would think it's unlikely that something so sudden comes up that doesn't give you a chance to warn Monika. I would think that in almost all cases, you would be able to let Monika know beforehand, rendering this kind of system mostly unused or unneeded.

**Comment by Youngbountygirl** [comment]
@multimokia The last part and the next paragraph that follows it. Send the love letter the day you log on, then Monika would ask what happened or why you were away and you would be given choices such as school, work or emergency. If you choose emergency, then Monika would be forgiving and happy that you are okay. You don’t lose affection at the end.

You could make the same argument about gifts. You’re basically creating a blank text and manipulating the file to end with .gift. This is a suggestion, so the creator doesn’t have to add it if they don’t want to. I also don’t expect the creator to use my whole idea, if they do. It could turn out to be no different from any other gift. I don’t know how game creating goes, but if it’s possible, then it’s possible. We’ll see what happens.

That is true. There is an apology option. Though, it doesn’t hurt to have other ways to save your affection and progress. It is a suggestion afterall and there’s always my flower variety option.

**Comment by Youngbountygirl** [comment]
@Rai99 I know. As I have told the other responder, it is just a suggestion. You both are right. You can gain back the points and you can use the apology option, though it doesn’t make this a bad idea and I am not expecting the creator to take this suggestion exactly as I have written it. Maybe the flowers, but that one’s pretty easy.

Manipulating dates and time on letters: That’s why I had the idea that the player can send the letter at the date and time they sent it without any manipulating or just send one letter right before logging in, then give Monika an explanation for the absents. The player has the option to manipulate the day and time, but do not have to do so. After all, the idea of the game is changing and manipulating files. 

Camping: The camping thing was an example. The love letters won’t specifically say that you were out camping. It would basically be an empty text reading loveletter.gift. Though, I suppose you could write something in it, if you wanted.

Can you manipulate date and time: Yeah. It’s like the gift files. If given the instructions on how, anyone can do it. Hell, I even googled instructions and they were simple instructions.

Abuse the system: Isn’t that the idea of the game? How is gifting any different? You basically place a text document in the character files and place the name and gift, then TADA! Hell, let’s players do it all the time. They change the date and time on their computer before logging on to make Monika think it’s a certain day. You don’t have to do that, but you can. That’s the point. Now, I did suggest other options where the player can send love letters without manipulating the day and time by sending the love letter at the day and time you need to send it or send it on the day you log in before telling Monika why you were away. This way, the player can be given the power to manipulate the day and time, but they don’t have to. It would be treated like manipulating the day and time on your computer. You CAN do it, but you don’t HAVE to. Monika has even admitted that the player does have power over her when it comes to the date and time. This would be no different.

As I said, it is a suggestion. The creator doesn’t have to use it, if they feel it’s unnecessary. Though, if you do have suggestions on better ways the love letter can be used, feel free to comment. That’s why these threads exist.

**Comment by multimokia** [comment]
> Send the love letter the day you log on, then Monika would ask what happened or why you were away and you would be given choices such as school, work or emergency. If you choose emergency, then Monika would be forgiving and happy that you are okay. You don’t lose affection at the end.

How do you intend to filter out those who intend to abuse the system to just never lose affection on long absence?

**Comment by multimokia** [comment]
Oh also, checking file attributes (modified dates/creation dates/etc.) Is a cross platform nightmare, not to mention *impossible* on Linux based systems. Windows and Mac would both require their own methods as well to get those dates but if I recall correctly from my own research, it's still very much a pain to access that data, as it comes in a strange format (not the usual `datetime.date`. As such, using a date given (as marked by the OS) is completely out of the question.

**Comment by Youngbountygirl** [comment]
@multimokia I don’t know if you’ve noticed, but there are Let’s Players that abuse it all the time to experiment. They will manipulate the dates and time just to see how Monika reacts and other things. Besides, if the creator wants to use this idea and make it a little challenging, they can. Right now, I don’t have ideas on how to keep anyone from abusing this, since people abuse other things in the game anyways.

It’s probably Windows 10 that is easier to do that. But, to me, it doesn’t make much sense on how hard it would be to change the dates of files if it is no different than adding .gift to a text file. If it’s harder on some desktops, then I still don’t see the problem with using the idea. If it’s just as much of a pain in the neck to create a .gift text file, then what would the difference be?

**Comment by multimokia** [comment]
> They will manipulate the dates and time just to see how Monika reacts and other things.

Monika ***literally*** tells you not to change the date/time as it could potentially ruin things - and it does. There's a reason we do not provide tech support to those who time travel, giving them an incentive to do so only makes many things worse. While yes, there *may* be some abusable systems, they are harder to abuse than this.



> It’s probably Windows 10 that is easier to do that. But, to me, it doesn’t make much sense on how hard it would be to change the dates of files if it is no different than adding .gift to a text file.

Again, it's not about *changing* the dates on these, it's about *reading* the dates, which is again, impossible on Linux based systems. Renaming a file != Changing modified dates != Reading those dates

**Comment by Rai99** [comment]
I'm pretty confident that most players aren't MAS youtubers, and don't have an audience to entertain. For the people who are MAS youtubers, I would imagine that it would be in their best interest to show off as many features as they can, both good and bad. I'm not sure how successful they would be if they just idled with Monika and recorded it. Probably not very successful since anyone interested in that can and probably will install MAS for themselves, eliminating the need to watch somebody else's Monika. 

If you think changing the date/timestamp on a file is the same as changing the file extension, I think you might be mistaken. From what I see, it takes external, third party software to edit the timestamp on a file, and I don't think that's something we want players to have to have in order to use a feature. 

I could be wrong, and if you can in fact edit the timestamp on a file, could you provide a step by step set of instructions for how to do so on Windows? I think that would be pretty interesting. 

In addition to the player changing the date, Monika would have to read the timestamp on the file, which I'm not even sure is possible on all operating systems, and locking features to certain operating systems probably isn't something we want to do. 

I'm sure this has been mentioned multiple times before, probably by me, but I just don't think it feels genuine. You and Monika would literally be pretending that you did something when you actually didn't. It would also open up a new vector for abusing the system, which should be avoided if possible. 

As for your flowers suggestion, you can in fact give Monika flowers, but currently, there are only roses.

**Comment by Youngbountygirl** [comment]
@multimoka I suppose it depends on what Windows or computer you have whether or not it’s easy or hard to change the dates. As I said, I’ve seen Let’s Players change the dates for experimental purposes. While it does ruin your relationship with Monika, it can be done and perhaps you do have a good point about abusing the system often making it worse for the player, regardless whether or not they can do it. 

Ah. I didn’t know there were Windows files that never show dates of when it was sent. I’ve only used Windows 7 and 10, both versions having shown the dates of when files are created. I suppose if there’s no possible way of showing the dates, the player can send one love letter per week they’ve missed and it can be treated no different from gifts as far as you create the file before opening the game.

**Comment by Youngbountygirl** [comment]
@Rai99 That’s true. YouTubers show tutorials and ways to play Just Monika, including hacks. Though, a regular player won’t care about that kind of thing, since they don’t make money or revenue off of playing the game or showing off features.

Not for Windows 10. Here’s a tutorial on how: https://www.isunshare.com/windows-10/2-ways-to-change-date-and-time-on-windows-10.html Now, Windows 7 is tricky. You can set the time to another time zone, but that’s as far as you can go. You can change the date though. It’s through the same process. You go to control panel, go to change date and time, click on the date, click okay and there you go. Though, that’s only for the date, not time. You can only do both on Windows 10.

Yeah. That’s why I was suggesting a variety of flowers and roses of different colors. It would make things interesting.

**Comment by Rai99** [comment]
Youtubers do need to show off a lot of features to their audience to keep them engaged, but I don't think they're exactly our target audience. That would need a lot of work consistently with brand new features since there's no reason not to go through little things like topics yourself. Correct me if I'm wrong, but I don't think we want to add more vectors for abuse and exploitation. I don't really think MAS is exactly prime youtube material. 

I meant for you to provide your own step by step guide here. If it's as simple as you say, it shouldn't be too hard to do that I'd think. We'd also need to put a guide up for people looking to do this and I was just wondering how you would explain it. 

You say it's different for windows 7 and 10, which I think could be a bit of an issue if some things are exclusive to one. Also, what about other operating systems such as mac or linux? 

In the guide you linked, step 1 was changing the date and time, essentially time travelling. When you said it could easily be done, I thought you meant something along the lines of opening up the file and manually inputting a different date on it. 

In case you haven't seen so far, time travelling/changing the date is _**heavily**_ discouraged. It causes numerous issues for people and was enough of a hassle to discontinue tech support for people who time travel, so getting help if you do something wrong isn't really an option. 

As for the flowers, we would need art to add more flower variety.

**Comment by multimokia** [comment]
> I suppose it depends on what Windows or computer you have whether or not it’s easy or hard to change the dates. As I said, I’ve seen Let’s Players change the dates for experimental purposes. While it does ruin your relationship with Monika, it can be done and perhaps you do have a good point about abusing the system often making it worse for the player, regardless whether or not they can do it.

The thing I don't understand here, is that you're going by the logic that 'just because YouTubers abuse it, let's just let everyone do it.' But that's not really what MAS is designed for. We want to create a more realistic system, i.e. one that's harder to abuse.

Like pointed out above, to change the modified dates (again, which are likely to go unused because of the cross platform nightmare it is to handle them), one must change their system clock, which we ***heavily recommend against*** because of the problems it causes. Giving users the incentive to actually do this can lead to many problems in many MAS installs, and it's overall just not worth the hassle it brings. It is highly unlikely that this system will be implemented at all.

For more flowers, if you (or someone else) is willing to contribute more flowers and such, those being giftable like roses isn't a big deal and can be done easily.

**Comment by Youngbountygirl** [comment]
@Rai99 There are DDLC fans that watch the videos of YouTubers showing off new features of the Just Monika mod, even ones fan of the mod, but I get your point. YouTubers aren’t targeting DDLC or Just Monika mod players or fans. 

I think the link I provided offered a better explanation, since it includes pictures, but with Windows 10, you just go to the search bar thing on the bottom left hand corner, type than click date and time, then change the date,  then click okay. Though, it’s for Windows 10. For Windows 7, you can change the month and day, but not time and in that case you would have to go to Control Panel. There should be Date and Time, then click “change date” or something along those lines and you basically click the month, year and day before clicking “apply.” It’s been a long time since I’ve used Windows 7, so my instructions might not be perfect and unfortunately I don’t have Windows 7 anymore. 

I don’t know. I’ve never used either one or knew that one of them never showed the dates of creating a new file. Not to say it’s impossible. Almost every computer I know has something like that. Even Windows 97 had a way of changing the date, since it went with setting time zones. Though, they all required going to Control Panel. It’s the same with Windows 10 technically, but the search bar makes it easier for you to pull up something from Control Panel without going to Control Panel. 

Oh no! I meant you can change the date and time easy with Windows 10. I didn’t mean creating a file or opening up a file. I meant like changing it on your computer to where it shows on the bottom right hand corner.

I suppose for people that don’t know how to use the time traveling method would get into a huge mess easily. 

Oh most definitely. Though, it would be fun to draw :) I’d be the first to volunteer.

**Comment by Youngbountygirl** [comment]
@multimokia I was going by the logic that it was intended for the player to be given the option to abuse it or not. Part of DDLC is that you can manipulate files and experiment with deleting or creating files. I talked with Rai and she made an excellent point about changing dates and time being more trouble for players than it’s worth. Not to mention that even if it is possible, it leaves too many negative consequences to be tried by an actual player. In that case, it might just be better to send a love letter before opening up the game and Monika will inform the player she received your letter and asks why you’ve been gone for so long. You have several options to choose from and can choose the emergency option where then Monika will tell you she is glad you are alright and you don’t loose your affection. There’s no time manipulation or changing dates. It’s no different from creating gift files.

If there’s a way I can contribute, I would like to know the place I can sign up at or send them.

**Comment by multimokia** [comment]
> I was going by the logic that it was intended for the player to be given the option to abuse it or not.

We will not add purposely abusable systems, that's just stupid.

>In that case, it might just be better to send a love letter before opening up the game and Monika will inform the player she received your letter and asks why you’ve been gone for so long. 

Now, the other issue with this is that again, it's still abusable, and rids all meaning from it, as I can just toss in an empty text file and Monika would be like 'oh, I got your letter.' That's just not genuine. The `imsorry.txt` bit for low affection does this, and I myself am not too fond of that, but there's a clear difference which makes that a little more forgivable: That note is a *one time* thing. This however, can be done on every long absence. I don't think this is the way to go about it. Best thing to do is just take the hit, it's not like it's hard to earn the affection back anyway. Plus (again) it's just easier to keep track of how many times you've apologized for being away from a long absence (and it makes more sense since the first thing you'd do is naturally apologize, not write a letter) to at least get a small bit of that affection back and explain yourself.

Without a text reader, it's just not worth doing any sort of letter reading. Even with one, picking out specific information is borderline impossible (as I've said in the past)

Again. Letters for long absences are *not going to happen*.

Another thing I don't get... In your response to Rai:
>I don’t know. I’ve never used either one or knew that one of them never showed the dates of creating a new file. Not to say it’s impossible. Almost every computer I know has something like that. Even Windows 97 had a way of changing the date, since it went with setting time zones. Though, they all required going to Control Panel. It’s the same with Windows 10 technically, but the search bar makes it easier for you to pull up something from Control Panel without going to Control Panel.
>
>Oh no! I meant you can change the date and time easy with Windows 10. I didn’t mean creating a file or opening up a file. I meant like changing it on your computer to where it shows on the bottom right hand corner.

But then to me:
>I talked with Rai and she made an excellent point about changing dates and time being more trouble for players than it’s worth. Not to mention that even if it is possible, it leaves too many negative consequences to be tried by an actual player. In that case, it might just be better to send a love letter before opening up the game and Monika will inform the player she received your letter and asks why you’ve been gone for so long.

You went from defending allowing players to change system time, to then going against it. I'm a little confused.

**Comment by Youngbountygirl** [comment]
@multimokia So, the love letter text is stupid, including the imsorry.txt, which is a one time thing as you’ve stated. Though, what about giving gifts, which is literally doing the same thing, only you end it with .gift? Just because the player is placing a blank text, doesn’t mean it’s not genuine. The idea is using code, so Monika can receive something or a letter of sorts. For gifts, you are depending on the sprites in the game that’s already there that the player didn’t make themselves. Does that make it not genuine? Just because the player didn’t write or make the gift, it doesn’t make it less genuine. Sometimes, it makes it genuine that you gave the gift or letter at all. Just the fact you gave a love letter indicates to Monika that you still remember her, even if you were gone for a long time. 

Now, as I have stated before, it doesn’t have to be exactly like I suggested. It can be no different from other gifts and I would be happy my suggestion was used at all. Though, if you are going to use the argument “because it’s a blank text, it’s not genuine,” you have to take the other gifts, which are also blank texts, into account. 

That’s because I changed my mind and if you look up on my earlier messages, I said,
 “That’s true. YouTubers show tutorials and ways to play Just Monika, including hacks. Though, a regular player won’t care about that kind of thing, since they don’t make money or revenue off of playing the game or showing off features.” 
On the next paragraph, I was showing her different links on how to change the dates and time, because I was answering her paragraph, 
“I could be wrong, and if you can in fact edit the timestamp on a file, could you provide a step by step set of instructions for how to do so on Windows? I think that would be pretty interesting.”
So, what you’re seeing is not me arguing why the player should be given power to change the dates and time, but showing Rai how it’s done. So far, I only know how to do it on Windows 10 and Windows 7, a bit on Windows 95 or 97. I don’t know if it’s any different on Mac or linux. I suppose one could always google it.

On a side note, I apologize for taking a long time to answer this. My life has been busy.

**Comment by ThePotatoGuy** [comment]
just going to respond to the initial post

>flower gifts

more gifts can be added, the process is relatively simple, all it takes is adding a topic-like entry to `zz_reactions`. ofc adding corresponding art for that is anything but simple.

>letters

generally the problem with open-ended stuff is that u either be generic in the response or really really try to parse the input to make sense of it.
Being generic would mean same response if given a loveletter or a hateletter. yes its like the imsorry text, just because it was done in an okay but not astounding fashion doesnt mean we should follow in its footsteps. 
being in depth requires significant amount of time and discussion to decide on how would we even begin to parse open-ended text and derive meaning from it. right now and for the forseeable future, we are working on simpler things with higher payoff, particularly making certain pieces of MAS capable of accepting user content without having to add code (json piano, custom music, json sprites, historydata system, etc...)

>date and time love letter was sent

creation time can be parsed with os libs, but since it is os dependent, it cannot be considered 100% reliable and therefore would need contingency plan in case we cannot read the data. sounds like in this case, it would be to assume the letter was sent when the game started up. also sounds like this wouldnt be too much of an issue, but it already begs the question of how should we handle some or all letters where creation data cannot be read. and would we allow letters to retroactively reduce potential aff lose

speaking about aff lose, you only begin loosing aff after a week. if thats the primary concern here, then ur suggestion of simply showing a special greeting or adding special prompts where you can explain why you were gone to reverse aff loss would be enough and actually preferable as that is more realistic then disappearing but only leaving notes behind. this shouldnt be like gone girl.

**Comment by ThePotatoGuy** [comment]
additionally, while gifts are blank files, they act more like keys to unlock additional content rather than directly open-ended material. and for open-ended gifts, we handle them with a generic response that works for both good and bad gifts.

**Comment by Professor-JMO** [comment]
> 
> 
>  both _good_ and **bad** gifts.

---

💡

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by Youngbountygirl** [comment]
@ThePotatoGuy Okay. Thank you for looking into this :)

**Comment by Youngbountygirl** [comment]
@ThePotatoGuy Also, for considering the losing affections thing with including a special greeting where the player can explain themselves.
