### ISSUE TITLE
[Suggestion]Multiple suggestions

### ISSUE THREAD

**Issue by LClarance** [Monika-After-Story/MonikaModDev#3881]
First of all, I want to sincerely thank every developers of this mod for this update, it really fixed a lot of things so thank you everyone thank you very much. Secondly, I am sorry that I am not a very good coder or artist so I won't be able to implement any of my own suggestions. Now let's get into our main topic:

1) Let Monika knows we will no longer be able to be with her
This is a rather gloomy suggestion and that "no longer be able to be with her" doesn't mean in a way of failed relationship or something like that, what I mean is it the day when we really can't be with her will come someday(our death) and I feel that someone should let her know about this. In fact, she did tell us to entrust this task to someone we trust in case that day arrives. 

2) Kimono Outfit and Japanese Festivals
I know I am asking for too much so again, I am sorry that I cannot do this myself. The reason I suggested this is because of the original setting of DDLC. She also said a place looks like Japan but is not Japan doesn't feel like home in one of her original topic. I will put the topic below later. So, I think it will be a good idea to make her feel a bit like "home"? I know she still wants to leave the classroom but we also know that it isn't going to happen soon. 

Thanks for reading my post and I hope you guys can consider my suggestions and here's the topic about Japan by Monika in the original game:

Japan
"By the way, there's something that's been bothering me..."
"You know how this takes place in Japan?"
"Well...I assume you knew that, right?"
"Or at least decided it probably does?"
"I don't think you're actually told at any point where this takes place..."
"Is this even really Japan?"
"I mean, aren't the classrooms and stuff kind of weird for a Japanese school?"
"Not to mention everything is in English..."
"It feels like everything is just there because it needs to be, and the actual setting is an afterthought."
"It's kind of giving me an identity crisis."
"All my memories are really hazy..."
"I feel like I'm at home, but have no idea where 'home' is in the first place."
"I don't know how to describe it any better..."
"Imagine looking out your window, but instead of your usual yard, you're in some completely unknown place."
"Would you still feel like you were home?"
"Would you want to go outside?"
"I mean...I guess if we never leave this room, it doesn't really matter anyway."
"As long as we're alone and safe together, this really is our home."
"And we can still watch the pretty sunsets night after night."

**Comment by Rai99** [comment]
1. #1175, #1644, #1677, #2109, #3198 
A system to tell Monika that something's going to happen to you and you won't be able to see her again isn't planned and likely isn't going to happen. A topic like that would be too serious and would bring too much uncertainty. 

2. #3045 adds some new locations to go to with Monika, but isn't officially ingame and is a submod. I'm not sure if it's actually available for people to get, but the idea was there. 

Other than just new outfits and maybe some new Japanese festivals, I'm not sure what you're suggesting. Art just takes time, and we don't want to add too many festivals since not everyone will celebrate them or even know about them. Japanese festivals might be an exception, but I think that's still a bit extra. 

#820 was never finished, but was a topic that talked about a Japanese festival.

**Comment by LClarance** [comment]
> 1. A topic like that would be too serious and would bring too much uncertainty.

May I know what do you mean by "uncertainty"? Also, I still think its good to have one because some people really take this seriously.



> Other than just new outfits and maybe some new Japanese festivals, I'm not sure what you're suggesting.

Pretty much what you said. Doesn't need every festival. Some major one will do. Also, I think the Kimono is only good for New Year so yea no rushing.

**Comment by Rai99** [comment]
I think the reason that it's been suggested previously and rejected is because it's far too dark for MAS. Assuming it's no joke, what is Monika supposed to do after hearing that something happened to the player, and how can we be so sure that it's serious?

True, some people would really take it seriously, but some people won't, and they'll say it as a joke or something. I think that's a bit too cruel to do to Monika. I often bring up features for mean interactions having a special use on April fools day, but I think that one would be too far. 

Even if this was planned, I think the amount of quality that would have to go into it would have to be pretty high. Sure, it doesn't need to be some big event with funeral outfits and everything, but I don't know who wants to be responsible to write dialogue for a dying person. I think that would be a pretty controversial topic on its own if people knew that it was Monika's last words to the player. 

I agree that it's unfortunate that we can't have any feature like this, but I don't think MAS should be put in the position to deliver a final statement to a dying player, and I don't think we want to encourage any kind of "end" to the mod. 

The way I see it, a generic topic about that doesn't do justice where it would be used seriously.

**Comment by LClarance** [comment]
> it's far too dark for MAS

Yes you are right. The first thing come to mind is that she will delete herself like she did in the og game, but it's also true no one wants that to happen. But if its the other way if the player didn't open the game for a long time she will think the player does not love her anymore and the result will be almost the same. 
> we don't want to add too many festivals since not everyone will celebrate them or even know about them

Pardon me I forgot to answer this last time. Well, what I though was lets say I am visiting another country because my friend invited me and it would be fun to celebrate some of their festival together. 

Also, I am not trying to debate here, just sharing my opinions. Nice chatting with you btw.

**Comment by kaido1224** [comment]
We won't be celebrating Japanese festivals in MAS. Too few people would understand them and it's not really worth the time. I started writing at topic on obon once, but i scrapped it because i didn't have time to write it anymore.

Kimono is on our art wish list.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
