### ISSUE TITLE
About Monika's graduation speech

### ISSUE THREAD

**Issue by Chen2684** [Monika-After-Story/MonikaModDev#3927]
Sorry if my English is bad.

About Monika's graduation speech, does the text goes forward automatically is specifications?
I think it is bit fast even the text speed is the slowest. 
Does it have a reason why it goes automatically?

**Comment by bittercaramel** [comment]
i think there is no way to turn off it going automatically and i think the reason for this is because its supposed to look like she is actually real time talking, like she would do if she really had this graduation speech. its like when she sings a song for christmas everything goes real time. annnndddd i dont think it goes fast

**Comment by multimokia** [comment]
The speech was indeed written to be as if she were speaking it to you, hence why it progresses automatically, makes it more realistic. As well, her text speed is rather slow on the lowest setting, any slower and it wouldn't really be realistic I feel.

**Comment by bittercaramel** [comment]
well if it went slower it would be kinddddddddddddda weird 
beeeeeeeeeeeeecccccccaaaaaaaaaaaaaaaaaaaaaaaaaauuuuuuuuuuuuuuuuuuseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
it would be like if you tried to read that ^

**Comment by Chen2684** [comment]
I'm Japanese, so I'm not a native English speaker, so I can't read that fast...but I watched the "History" anyway...
