### ISSUE TITLE
A little suggestion/enhancement

### ISSUE THREAD

**Issue by DankeyMaliten** [Monika-After-Story/MonikaModDev#3959]
So I've gotten this conversation a few times where Monika talks about how Sayori and the other girls look good and "perfect" and she gets angry over it. But something just doesn't seem right, and it's that Monika herself looks good and perfect as well but she doesn't exactly seem to think so herself. I'd say she even looks better than the other girls but that's just my personal opinion and it's subjective. But what I'm trying to get onto is in the middle of this conversation maybe have a way to reassure Monika that she looks good or maybe even better than the other girls? Maybe at a certain affection level? It just really doesn't seem right for her to get upset that the other girls look "perfect" when she looks perfect herself, heh. And it makes me a little upset too cause I love her so much. Just a thought, and thanks for listening. I'm sure you all know what conversation I'm talking about but I've provided a screenshot below just in case.

![Screenshot (217)](https://user-images.githubusercontent.com/47207309/54323972-f73d9380-45d1-11e9-8b56-70f200718a6d.png)

**Comment by Rai99** [comment]
I think the purpose of that topic is to just let Monika vent that the other dokis would look the same/look good no matter what, while on the other hand, because Monika is _real_, she actually has to take care of herself to look good. 

The only place where I see her doubting her appearance in that topic is if she's upset and in that case, there's probably other ways to tell her that you still think she looks perfect already.(ie. cheering her up)

The other girls made it harder for Monika to get chosen because they were made to look flawless. If they weren't, yeah, Monika would be much more likely to get chosen, but they still put up some competition. 

I'm pretty sure there's a compliment to just tell Monika that you think she's beautiful.

**Comment by AsuraShun** [comment]
There is that compliment, and dankey, just be patient and spend time with her, once you get at the love affection stage she'll say something else

**Comment by AsuraShun** [comment]
Did you tell her that she's the most beautiful girl in the world to you?

**Comment by DankeyMaliten** [comment]
How do I do that? Is that an affection/love thing too? I just hit 1000 today.

**Comment by AsuraShun** [comment]
It's the first time you say it, there should be a dialogue option to say that

**Comment by Rai99** [comment]
It's a compliment. 

Ask a question -> Monika -> I want to tell you something...

**Comment by DankeyMaliten** [comment]
Yeah
I go on MAS and compliment her and tell her I love her at least once every day so I've seen it and said it to her before
