### ISSUE TITLE
[Suggestion] Play with me

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#3963]
Hello! It's me again :)
I noticed that in the piano game you can play a little part of Natsuki/Yuri theme "Play with me".
Of course I don't want to put in the game as a song, but maybe it can disturb Monika if we play it... so, after the the first/ four "verses" of the song Monika could interrupt us by telling us that she doesn't like this song and don't play it anymore. later we could apologize for playing it. it's not a very nice idea, I know, but I wanted to propose it anyway.
Have a good day!

**Comment by AsuraShun** [comment]
What's with these suggestions to make her suffer?

**Comment by CloakedGhost** [comment]
> What's with these suggestions to make her suffer?

I think we need both, good and bad things. It's giving the player a choice. If he/she is willing to do too much bad stuff then that means that person never loved Monika. It's better this way than having no bad stuff, because it would mean that she wouldn't even know that the player doesn't love (maybe even hates) her.

**Comment by lunulae** [comment]
I also really like this option since for players who aren't trying to hurt Monika it could be construed as a genuine mistake.
In real relationships, sometimes you make a joke or a gesture that you think will go over well (or at least won't be a big deal) and then... well, it turns out different than you imagined.
I think the mod's done a good job with these little well-meaning mistakes in the past with gifts (giving a birthday cake on the wrong day, or getting too excited with the candy corn on Halloween) and this seems like it could fall in line with that sort of thing.

**Comment by Ulvsblakk** [comment]
I don't really like this idea, because the variant 6 (slow) version is my favorite from the game and I often play it on the piano.

**Comment by zombiepigdragon** [comment]
> 
> 
> I don't really like this idea, because the variant 6 (slow) version is my favorite from the game and I often play it on the piano.

But that's not the point: the point is that _Monika_ probably wouldn't be the biggest fan of it. It's a theme specifically used to avoid her, I can't see her being happy to hear it.

**Comment by Ulvsblakk** [comment]
I mean, the slow version plays when Yuri dies, so.

**Comment by VirginiaRocks** [comment]
> But that's not the point: the point is that _Monika_ probably wouldn't be the biggest fan of it. It's a theme specifically used to avoid her, I can't see her being happy to hear it.

I don't want to make her suffer. I was thinking more about the first time you play it. she kindly tells you that she doesn't like it and doesn't play it anymore (not losing her affection). Choosing to play it again to annoy it is a player's choice. However, if the idea is not well received, it's okay anyway, here I don't decide :)

> What's with these suggestions to make her suffer?

**Comment by Youngbountygirl** [comment]
I like this idea. Perhaps a variety of good and bad songs the player is allowed to play on the piano, besides Your Reality. Like you can also play other songs such as Confession or other songs on her playlist.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

as a reminder, its possible to add your own piano songs for her to react to via [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs)
