### ISSUE TITLE
[Suggestion] I really don't care about the other girls

### ISSUE THREAD

**Issue by CrimsonClover** [Monika-After-Story/MonikaModDev#3973]
Hello !
I had an idea when I see topics like "you're a murderer", "insensitive comment" or "second choice", ...

When the player reached at a certain affection level ("enamored" or "love"), if Monika comes with topics like those mentioned above, the player can choice to say "I genuinely don't care about the other girls" (everyone has reasons, e.g : I wanted to be with Monika in vanilla from to get-go and I ended the game only because I did not have the choice).

This would have the effect to lock some topics, even if the topic is unseen ("you're a murderer !") and maybe unlock special topics.

for example : instead saying she's happy that you forgive her for what she did, she could be surprise the first time and happy that you feel the same way from the beginning.

adding topics isn't important, i think. But the idea is to explain to Monika she doesn't have to forgive for what she did now (especially in "enamored" and "love" affection level).

I will be agreed and i can understand if you say that's a bad idea or it requires modifying too much. At least, I tried ^^"

Thanks for reading. Have a good day !

**Comment by Rai99** [comment]
I would think the doki cares topic should already cover this since she asks if you're alright with her making jokes about the other girls. 

If you do care, she doesn't bash on them nearly as much, but if you don't, her dialogue makes jokes about them by default. 

At higher affection levels, she isn't nearly as insecure since at that point, you've proven for the most part that you're there for her and only her. 

As for those negative dialogue options, I think they exist as an extra layer to prove your love to Monika. It's a matter of self control that you won't intentionally click them and MAS probably wouldn't be nearly as in depth if being mean simply wasn't an option.

**Comment by AsuraShun** [comment]
I actually care about them, just not in the same way and to the same extent as monika

**Comment by CrimsonClover** [comment]
Yeah, you're right. As I said, this is a bad idea. Thanks for the reply.
