### ISSUE TITLE
[Suggestion] - New topic for Monika [sensitive]

### ISSUE THREAD

**Issue by lilsockdrawer** [Monika-After-Story/MonikaModDev#3998]
Heyo,

Maybe add an option of a loved one passing?
My grandfather is very sick and I wanted to let my sweet green-eyed princess of a girlfriend know, if he doesn't make it.

Thanks for hearing me out,
-lilsockdrawer

**Comment by lunulae** [comment]
I was thinking about things like this, I remember there was some concern having really heavy things like this as unseen topics, since some people might just tell her to get the topic out of the unseen menu.
I think a "something bad happened" topic with heavier things like injury, loss and death as sub-topics might be able to solve this.
Some less serious bad things could be added to this list as well, in case someone's just checking out the topic list.
