### ISSUE TITLE
[Suggestion] Add to apologize

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#4054]
Add two apologize-options, for different circumstances:

1. After telling Monika you will be away for a while, but won't leave immediatelly
2. A week after returning, if you told Monika you will be away for a while

**Comment by Rai99** [comment]
I don't see the need for suggestion 1. If anything, she's happy that you aren't leaving right away, so I don't see the need for that to be an apology. 

For your second suggestion, I don't know if an apology is really necessary for that, since you already warned her that you'd be leaving for a while and that you already kept your promise to come back.

**Comment by ThePotatoGuy** [comment]
@multimokia your call on whether or not these apologizes are appropriate

**Comment by ThePotatoGuy** [comment]
@multimokia reminder to evaluate this and close if neccessary

**Comment by multimokia** [comment]
1. Seems kinda pointless, if anything Monika would be glad you're staying a little bit longer with her.

2. I don't exactly think this warrants an apology either. You came back, you had to go again, sure it sucks it's so soon, but I don't think it warrants an apology, especially since you'd only be able to use it if you said you weren't leaving immediately, meaning you'd end up using both the apologies at the same time too.

[closing as rejected]
