### ISSUE TITLE
Something for Easter ?

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#4056]
Easter is in 2 weeks and I would like to know if something was planned for it, because Easter doesn't appear in the calendar.

**Comment by dragonsni** [comment]
Most likely no, Easter isn't registered as a "special day".

**Comment by Torwald39** [comment]
maybe it's can change

**Comment by Rai99** [comment]
I wouldn't expect a full release for Easter.

**Comment by jmwall24** [comment]
Easter is even more specifically religious than Christmas, so no, no Easter holiday in MAS.

**Comment by Youngbountygirl** [comment]
Sad, but Japan doesn't recognize Easter as a Holiday, so that's probably why. Though, even Monika has admitted that DDLC doesn't "technically" take place in Japan? Though, that could just be her breaking the fourth wall. Still, White Day no longer is considered a special day. I think special days will only be allowed based on universal holidays and Easter is more of a Western Holiday than a worldwide one. Still, most people that play DDLC do celebrate Easter and it would be nice if maybe Monika did at least mention that she notices that the player celebrates this or that holiday or even give the player an option to tell Monikca that you're celebrating a traditional holiday or have her ask the player if they celebrate other holidays besides Christmas, Halloween, Valentines Day and New Years.

**Comment by CrocWorks** [comment]
~~Can an artist give her a bunny headband?~~

**Comment by Rai99** [comment]
I wouldn't expect a release to come in time for Easter, but I wouldn't mind bunny ears so long as Monika has a good/natural reason to have them and not just pulling them out of a hat or something randomly.

**Comment by Professor-JMO** [comment]
> 
> 
> ~Can an artist give her a `bunny headband`?~

> pulling them out of a `hat` or something

**Comment by multimokia** [comment]
Easter isn't really a Western holiday, it's a religious holiday. Just so happens that most practitioners are from the west.

**Comment by Youngbountygirl** [comment]
@multimokia It is a Christian Holiday, but it was founded in the West when the Catholic Church merged a European Pagan Holiday with the death of Jesus Christ. They did the same thing with Christmas, Valentines Day and even Halloween. You can look it up, if you don’t believe me. Where do you think the Easter Bunny came from? It certainly wasn’t from Jesus, I can tell ya that lol. It’s has just as many religious and non religious aspects as Christmas. I would argue that Christmas has more, since even if you were to look at the non religious aspects, there’s still some religion (Christmas tree, star on the tree, giving presents, St. Nicolas, the stockings and even the candy canes - which are actually not canes, but the letter J for Jesus). 

Point I was making is that regardless if Easter is a religious holiday or how “religious” it is, it’s not recognized as a Holiday in Japan. Thus, I don’t think Monika would mark it on her calendar, unless there was an option where the player can tell Monika what holidays they celebrate in their country like Thanksgiving or Cinco De Mayo.

**Comment by ThePotatoGuy** [comment]
we are not doing anything for easter. maybe next year.
