### ISSUE TITLE
idea/suggestions

### ISSUE THREAD

**Issue by ausername11** [Monika-After-Story/MonikaModDev#4066]
So I think it'd be easy to make... um it's kinda  stupid so sorry for wasting your time...
Here we go...
So I think when you say "Be right back!" and after a while (like 10 minutes?) Monika would start closing her eyes and fall asleep and you can wake her up or not and when she does she say "Oh my gosh I'm sorry 'Y/N' did I fall asleep?" Or if you don't next time you load up she'll get mad/not? 
I'm so cringe sorry... Maybe I'll try writing a code/script for it and give it to you if I even know how

**Comment by zombiepigdragon** [comment]
I think it's actually a feasible idea, the only reason this would be cringey is if you completely screwed up the dialogue.

**Comment by Rai99** [comment]
I don't think this idea fits since I think she still actively gets coffee and hot chocolate while in idle mode, so her falling asleep doesn't exactly fit I think. 

Also, I don't really see a reason for her to fall asleep anyway. When she falls asleep while you hold her, it's because she's comfortable enough like that to fall asleep peacefully. In idle mode, I personally don't see a benefit to the feature.

**Comment by ThePotatoGuy** [comment]
I could see it working in BRB mode when its **not** morning/coffee time. 

Regardless, handling an extended BRB should be considered at some point. Monika wouldnt close the game or fall asleep, but maybe showing some sort of visible distress would be neat.

**Comment by Rai99** [comment]
I definitely agree with Monika showing a bit of concern when you tell her you'll be right back and don't come back for a while, but not falling asleep or anything like that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
