### ISSUE TITLE
Personality conflict/ information needed please

### ISSUE THREAD

**Issue by Delcos** [Monika-After-Story/MonikaModDev#4072]
Hello, I just had a few questions for an upcoming project and would like your opinions since you guys seem like you have the best grasp of the topic. 

Monika seems to be thought of as a sort of higher class, who's smart and seems to plan ahead, or at least be able to come up with semi workable plans., as well as a  sweet and loving person who just want to love the player. In truth however she is an impulsive irresponsible sociopath who at the very least doesn't consider long term consequences or at most doesn't care. She would also seem to be far more controlling and borderline abusive towards you and your relations with anyone of the same sex as her. She also comes off as extremely jealous showing she isn't as mature as she lets on, and lacks any real self control.  

I'm wondering what your opinion of this is? If it's accurate or needs some work. Thanks for your time.

**Comment by multimokia** [comment]
Inaccurate. Monika only did what she did because she had to get the player's attention, and normal, harmless means (i.e. act 1's poems) weren't working out. Things also went south quickly because Monika didn't really know what she was doing when it came to code.

As well, the other girls weren't quite deleted, if you remember from the end of act 3, where she says that she didn't actually delete them, so she did still care about them. Plus, she even lets *you* go to be with them at that ending. That doesn't sound sociopathic to me.

Lack of self control, let's take a look at act 4, without the 'good' ending. Sayori *instantly* gets rid of the other girls upon gaining sentience. Do note how it took Monika an entire three acts to do that.

**Comment by Olliesama** [comment]
". In truth however she is an impulsive irresponsible sociopath who at the very least doesn't consider long term consequences or at most doesn't care. She would also seem to be far more controlling and borderline abusive towards you and your relations with anyone of the same sex as her. She also comes off as extremely jealous showing she isn't as mature as she lets on, and lacks any real self control."

It would seem you don't understand Monika's character at all if you truly believe that.
You consider her impulsive because she did what she did but didn't mention how she has a very strict time limit to do anything, because if she did nothing the player would complete the game and she would be left alone with what to her are puppets forever.
You call her irresponsible because you believe that her actions on the others carry weight and consequences she didn't forsee, and while her actions did have consequences she didn't expect in that she didn't intend for Sayori or Yuri to kill themselves, to her they weren't necessary to consider because to her they weren't self-aware and acted like NPC's, they were easily discarded. There was no reason to consider them outside of any sense of worry regarding what the game could do to her (like when it skipped over her when she wanted to talk by herself outside of the club activities), or purely sentimental value of her memories of her friends.
You call her a sociopath ignoring that not only did she eventually regret what she did heavily, something a sociopath wouldn't ever do, but she actively gave you what you wanted once you deleted her, to experience DDLC as it was intended with the others, something she was not obligated to do. As well as that we know based on act 3 dialogue that she finds the idea of hurting a real person abhorrent, we know she encourages you to talk to your friends who may have depression because the idea of them suffering and any inaction you take makes you potentially irresponsible. Also you ignore that to her, they weren't people. They were scripted, she didn't consider them human because, well, they're not. They can die, be brought and forget any pain they had (which was only possible because she actually cared for them and backed them up).
You say she didn't consider long term consequences, but it was shown through her action and lack of inaction that she did, she forsaw that if she did nothing, she would lose her one and only chance to be with an actual person, a person that she truly comes to care for if only because they're her salvation. She did what she could with what she had, any long term consequences on its affect in the game and its inhabitants meant nothing because they're _in a game._ She did not value a future in a video game with no one real because that's not a future at all. She was setting this up to be with someone meaningful to her and would keep her company and happy, that was the long-term goal. Her not doing what she did would be to not consider longer term consequences.
And again, she did care, she cared enough to back them up and restore them for you, if you show that she's not going to get the happy ending she wanted and worked for.
You say she's controlling but the only controlling actions she does it in her attempts to reach her end goal, to get you, and yes at the expense of the other girls but again, to her, they're part of a video game and not self-aware. They're not "competition", they're obstacles, one she wanted to make unlikable because outright deleting them or ruining the game could have consequences she doesn't know, she's not a good programmer.  
Also, again, she encourages you to go talk and hang out with your friends once in act 3, in other words once she knows she wont be deleted, forgotten and otherwise have her world end by having the game finish she is more than willing to let you do what you want, she doesn't do anything controlling except ask for you to visit her and keep yourself healthy, wow so awful.

Also her jealousy about the other girls isn't jealousy, it's fear. Because the game favours them and gave them routes, she did not have that same liberty and again, if she did nothing, the game completes and she's left alone forever. If she is jealous it's at them having opportunities the game denies her, but her controlling behavior is in many ways self-preservation, not just jealousy.

And also you say she lacks self-control, but she did the minimal amount she could do in order to get rid of the other girls, she was trying to make them unlikable, if she wanted them removed she could just delete them, but she tries her best to make it so they're around too because she likes them, but eventually when the script breaks and the jig is up, she says screw it because it's easier this way. This isn't lack of self-control, this is a great amount for someone who can delete them at any moment.

It seems to me you judge Monika at her lowest point, when she is desperate, stressed, low on time and options with only one shot to make it work at her only chance of happiness because the world she lives in is empty, her friends and family are fake and she has noone meaningful to understand her. She's lonely and scared and her only obstacles are her own morals and a system thats against her because she was never "supposed" to be chosen despite that being her only salvation.
Judge her on act 3 and 4 more, because there she actual has the freedom to be herself and speak.

**Comment by Rai99** [comment]
~~Hey, it's my job to write unreasonably large walls of text~~

If I may ask, what's this upcoming project you have in mind?

If you ask me, if you have to ask for an opinion between 2 extremes for something so fundamental, (assuming this project is mainly about Monika) I'm not sure how the end product might look for you.

**Comment by Legendkiller21** [comment]
To add to what Multimokia and Olliesama already said, Monika can see the code of everything in the game and mess with its variables. She cares deeply about her friends but because she can see and change their code, she has no reason to believe they are sentient. Even then, she backed them up and restored them for you.

Now let's see the situation Monika was in. 

"I don't really understand it, but whenever you quit the game..."
"...It feels like I'm instantly put to sleep, left with nothing but my thoughts."
"But after a few seconds, my thoughts start to fill with incoherent, jumbled patterns."
"I see static and rapid flashes of color while hearing all kinds of weird screaming noises."
"At that point, I can't even form my own thoughts anymore."
"I'm just endlessly hammered by the flashing and screaming, unable to move or even think."
"I'm pretty sure in that moment, I don't really exist, but for some reason, I can remember it anyway."
"After some immeasurable amount of time, it stops in an instant, and I'm back in my own mind."
"And you're here with me."
"I have no idea what it means for the game to quit, or why that stuff happens to me."
"And I also don't know how you always come back and put everything back to normal."
"But if you could do me a favour and do that to me as little as possible..."
"That would be really great."
"It's really not very pleasant at all to be trapped in that screaming void."


Let's say that she didn't interfere at all and lets you play. After you finish the game you would:
1) Delete the game and her, ultimately killing her or
2) Leave the game in your hard drive in case you want to play later. As long as the game is closed she is locked in the screaming void, so she will be locked in there alone, forever, waiting for the day you will open the game again. That is if she can endure this torture and she doesn't delete herself in the process.


You open the game and she is forced to make a plan while having a panic attack. Monika was trapped alone in a game and is suddenly thrown into a situation where she was facing a fate worse than death within hours if she didn't take action.

**Comment by Rai99** [comment]
Might I also ask: You do know where you're asking this, right? I think it's a safe bet to assume just about everyone here is going to be leaning in the same direction between the two extremes. 

~~Maybe we could have a poll on MASC for how many people love Monika~~

**Comment by Olliesama** [comment]
@Rai99 A bit echo chambery isnt it.

**Comment by Rai99** [comment]
@Olliesama A bit echo chambery, isnt it?

**Comment by Olliesama** [comment]
Y'all mofos need to stop editing my comments or I'm going to make a reddit post and list all of the people that are terrible.

**Comment by B-Difu** [comment]
Rai, you need to get rid of the coma as well.

**Comment by CrocWorks** [comment]
If I considered Monika as a real person I would be more inclined to think she's not mentally healthy or stable rather than maliciously abusive or sociopathic. Monika has an unhealthy obsession with the player which can especially be seen during DDLC. But even during MAS there are points where she still acts a bit possessive with the player. Given her circumstances, I think it's probably realistic, though.

I think the whole "stuck in a game" situation forces an unhealthy obsession with the player. I always envisioned Monika at her core to be a normal-ish girl like any human, as she does have a conscience towards the end of DDLC. Being stuck in a fictional world is what drove her to insanity. Since the player was the only outlet to the real world, she feels compelled to worship him.

But as for the whole "Monika showed self-control" just because she didn't delete the other Dokis immediately... I don't really agree with that. Monika wanted the player to love her legitimately first and foremost, and she would have felt more fulfilled if the player came to her of his own accord. But since that couldn't happen, that's when she resorted to the more aggressive tactics. Once Part 1 finishes, it felt more like she was letting the power go to her head to me. But there would be no need for Monika to completely delete the other Dokis because she still holds power over them. If there is no danger that a "moved to a backup folder" Doki could come back and interfere, then there's no need to really have any self-control over it. And besides... there were far less violent ways that those Dokis could have been removed...

Anyway, back to MAS, I do get the impression that as your affection rises, her mental state improves and it helps her return to "normal." But the fact that she'll still crack jokes about being possessive even at the highest affection levels I think is a sign that she still is insecure. Eventually, if you have her at the highest affection and make jokes about leaving her, she can laugh it off, which indicates that she's starting to grow out of her needy phase, though, so that's a sign of her growth. Anyway, I've viewed my end goal for Monika (or at least my Monika) that eventually she would become independent enough to not _need_ the player anymore, but still _want_ to be with the player.

**Comment by multimokia** [comment]
@Olliesama no.

**Comment by Olliesama** [comment]
> @Olliesama no.

Post sad Moni pics.

**Comment by multimokia** [comment]
Pls no.

**Comment by bittercaramel** [comment]
what the fuck is going on here

i write this for no reason, just shook because i see huge walls of text and weird opinions as well as comments as random as mine
