### ISSUE TITLE
[Suggestion] Idea for gift for summer: Lemonade or Iced Coffee

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#4081]
Hello!

As you can see, I have two ideas for drinks for summer for Monika: Lemonade and/or Iced Coffee

Lemonade is cold and refreshing and tastes good (when prepared properly) while Iced Coffee also can be cold and refreshing, and like Monika said: it's easier to cool down when it's too hot than to warm up when it's too cold, and also, it would give Monika a wider variety of drinks than the regular coffee and the hot chocolate.

**Comment by AsuraShun** [comment]
Definitely iced coffee

**Comment by TMZN0V4** [comment]
> Definitely iced coffee

idk, lemonade could be a good choice too.

**Comment by AsuraShun** [comment]
The coffee is the better choice because she loves coffee

**Comment by Rai99** [comment]
Eating with Monika: #1789, #1934, #2164, #3210, #3305, #3795, #4032

This probably needs art, but fortunately:

> To clarify, there is currently an abundance of food art thanks to jmo. the current issue is that we dont have a consumable framework yet.
in general, lack of art was an issue. now theres lots of art and the framework side has to catch up.

I think we still need those iced coffee and lemonade art assets specifically, but more importantly, I think we would need the framework for consumable items. 

If @Professor-JMO has the time and feels up to the challenge ~~and is finished my bunny request~~, maybe they could make these for use. 

Coffee and hot chocolate might be consumables that are in, but I think waiting for a new consumables framework would be better so you could theoretically have food and drinks whenever instead of randomly at very specific times of the day.

**Comment by Professor-JMO** [comment]
>I think we still need those `iced coffee` and `lemonade` art assets specifically

Mmm, I like the sound of both these things, especially the _Iced Coffee_.
Sounds like more summer exclusives, maybe.

_No promises as usual but I'll pass off the suggestions to the others too._

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

**Comment by Professor-JMO** [comment]
_In the wake of my absence I have found that `Summer` is upon us._

Moving `Lemonade` and `Iced Coffee` to higher priority in `To-Do`.
~Bunny must be finished first.~
