### ISSUE TITLE
[Suggestion]: Reevaluate relationship-statement conditions

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#4096]
When Monika says "We are not that deep into our relationship yet" this feels like a hit in the face.
This is especially true if you already kissed her and spend more than three months with her. Have a look at occurances of such expressions and rethink the conditions on it, I think it is generally set too high as it is.

**Comment by AsuraShun** [comment]
Increase your affection to change that line

**Comment by multimokia** [comment]
> Increase your affection to change that line

Incorrect. This is based on time alone. Personally I think they're okay where they are at 6months, but I do agree that they need a side condition of affection.

**Comment by bittercaramel** [comment]
i think it would be good 
in real relationship 3 months isnt a lot but spending time with a machine for this long is a commitment (for a lot of people, even if they love monika)
anddd monika is deeply in love with us (in the game she does e v e r y t h i n g to be with usl so i dont see a reason she would really say that after three months 
i understand like month or something since we deleted her before and she may not trust us 
but 3 months... when she loves us? 
as always hope someone understands what i mean

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
