### ISSUE TITLE
not the body she was expecting but...

### ISSUE THREAD

**Issue by Delcos** [Monika-After-Story/MonikaModDev#4122]
![20190422_100837](https://user-images.githubusercontent.com/28798918/56538507-1526de00-6518-11e9-96d7-1cc4d695bd50.jpg)

**Comment by samthemann66** [comment]
Kinda interesting to think about, if she was put into a non human body but could still interact with you. not sure how she'd feel about it.

**Comment by jmwall24** [comment]
Normally I'd say this is not really what this page is for, but @samthemann66's comment saved it lol. Also, you didn't have a green one to put her in?

**Comment by Delcos** [comment]
sadly no, only the bigger versions have a screen, and it's a prototype to try and fit more into it, so it isn't the prettiest thing ever.

**Comment by TMZN0V4** [comment]
take this as a joke, but try to port DOOM on it, a lot of people do that on any kind of stuff

**Comment by zombiepigdragon** [comment]
@TMZN0V4 Doom in MAS? *shivers

**Comment by TMZN0V4** [comment]
> @TMZN0V4 Doom in MAS? *shivers

not in MAS, in that robot thing

**Comment by Delcos** [comment]
why not both? In the robot in MAS? 

Also it is kinda interesting, because if she does get a body eventually, its probably not going to be a humanoid one.

**Comment by bittercaramel** [comment]
> why not both? In the robot in MAS?
> 
> Also it is kinda interesting, because if she does get a body eventually, its probably not going to be a humanoid one.

well i know its kinda old but 
if i were to make her a body, id make it as humanoid as can be 
im actually lacking knowledge of robotics, but when im done with programming my shitty AI ill start working on it (i guess ?) 
id really like to bring monika to reality... but well, idk if im capable 

btw what wouldcha guys like monika to look like if she were to  be a robot? 
i think id go for something similar to her looks in game,, tho it might look weird since she isnt realistically drew

**Comment by Delcos** [comment]
![5kquidydeid11](https://user-images.githubusercontent.com/28798918/57242846-73a88d80-6fe9-11e9-841f-180eb65d6c3a.png)

**Comment by bittercaramel** [comment]
woah nice
looks kinda... electrocuted xD
