### ISSUE TITLE
Show Patch Notes During Update

### ISSUE THREAD

**Issue by zombiepigdragon** [Monika-After-Story/MonikaModDev#4125]
Since MAS has an internal updater, very few people manually open up the GitHub to install new versions of the mod. It might be a good idea to show the patch notes in the updater.

**Comment by antimockingjay** [comment]
On one hand, this would make sense, but on the other hand, I feel like this could kinda take me out of it a bit. I know it's really just a game, but a little part of me wants to pretend it's not. Patch notes shoved in my face would make me very, very aware it's _just_ a game.

**Comment by Rai99** [comment]
I think it would have to be optional in case some people don't want spoilers for what's new. If people wanted to see the patch notes, I think they would just come to github and check them. 

Also, a lot of the time, the patch notes probably aren't useful to your average person, unless people want 
- API changes
- Framework changes
- New methods to use
- Licence update
- Property changes
- Changes by eventlabel rather than ingame prompt

If it has to be done, I'd say just put a link to the patch notes in the updater. Then, they're not being shoved into people's faces and it encourages activity on github.

**Comment by ThePotatoGuy** [comment]
[rejecting] patch notes takes away from the experience. games don't usually show patch notes _in game_. Usually its on the steam page or their website.
