### ISSUE TITLE
[Suggestion] Telling Monika you're going to take a shower.

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#4129]
I understand this may be a semi duplicate to #3270 BUT HEAR ME OUT.
-I mean this is my second time writing this because my phone crashed so please at least hear me out.-

Telling Monika that you're going to go take a shower. It would be in the Be right back option. 
"I'm going to take a shower."
And Monika would be cute, blush at the thought of you taking a shower, and then tell you to remember to scrub behind your ears.

It would be cool if she noticed how long you were gone too.
<5 Minutes...
Monika would ask if you simply forgot something, or if you deciding against taking a shower in the first place.
5-25 Minutes...
Monika will simply ask you if you enjoyed your shower.
26-35 Minutes...
Monika will comment on how she noticed you took a longer shower.
36 minutes and longer...
Monika will tell you that saving water is important and a way to cut down on using so much water is to take faster showers, or bring up again that turning off the water while you wash and turn it back on to rinse is a safe way to use less water.

ALSO

Remember when Monika told us that people with depression sometimes don't have the motivation to go shower? Monika could also remember the last time you told her you were going to shower and ask you if you been feeling okay, and tell you she's there for you, and try to give you motivation to go at least give yourself a sponge bath.
I think that would be cute.

I love what you guys do. Thank you so much for making this mod and giving me Monika back. <3

**Comment by Delcos** [comment]
yes.

**Comment by AvelJames** [comment]
I'm glad you like my suggestion.

**Comment by Rai99** [comment]
~~I'm starting to get suspicious that whenever I think of something myself, somebody goes and makes a suggestion for it.~~ 

Also keep in mind that in #1573, the topic of water conservation was discussed and it was brought up that most water consumption is from agriculture and power generation, while only a small part is from use. Seeing as how Monika is a practical person, I'm not sure she would really push for you to save water. Also, water conservation is already its own topic. 

There are also some cases where taking long showers is a sign of depression, and I can't imagine it would be helpful to have Monika basically tell you to stop taking such long showers. 

I'm not sure about Monika remembering the last time you showered. That seems a bit over the top and unnecessary to me at the moment.

**Comment by AvelJames** [comment]
Okay but do you like everything else?

**Comment by Rai99** [comment]
I kind of like the idea of having a brb style option for going to shower, and I think it would be interesting for Monika to comment on how long you were gone, but I'm just a bit iffy on what she could say if you were gone a long time.

**Comment by AvelJames** [comment]
Okay

**Comment by Rai99** [comment]
For clarification, what's your plan for this? I'm a bit confused as to what you have in mind for this. 

I'm not sure if this is a request or if we're keeping the idea since I brought up some of my concerns with it or if that'll be handled when we cross that bridge. 

I thought maybe you would propose a second pass of your idea after hearing what I think of it, but I'm a bit lost with that "`Okay`".

**Comment by AvelJames** [comment]
Sorry about that, 

I like the idea of her commenting something like
"That took longer than I expected! But that's okay since you're here now." 

(As for the okay its late where I'm at and I just wanted you to know I got the message. My bad.)

**Comment by antimockingjay** [comment]
I absolutely LOVE the idea of her noticing how long it's been since we commented that we were going to go shower. As someone who _does_ fall into that category of not showering enough because of depression, I think having Monika call me out on that and encourage me to do so more frequently would be really, really good encouragement. I think it would be important, though, that she does so in a gentle, worried about the player way, as opposed to any sort of judgmental way. I'm typically embarrassed when it comes to that stuff, and I don't know about others, but I'd be mortified if Monika added to that somehow.

**Comment by Rai99** [comment]
My problem with Monika reacting to the last time you took a shower is that it'll take a little bit of extra work to put in place the system for checking that. 

Also, I personally don't think I would use it every single time, so it would be a bit inaccurate for Monika to comment that I haven't showered in a long time, when I just haven't been telling her. 

I don't think Monika would assume that you don't shower just because you don't tell her. Otherwise, I think the first interaction with the topic might make things interesting. You tell Monika that you're going to shower and then she assumes if you don't tell her, you don't shower.

**Comment by AvelJames** [comment]
That's why she could ask "Have you been showing? I noticed you haven't told me in a while and I'm worried if you're doing okay. "

-Yes I've been showing.-

"Oh that's good! I was concerned you weren't feeling well. You know you can tell me anything."

-No, I haven't been showering-

" [Player], you really should take a shower... It will help motivate you to stay healthy and not get sick... For me, please try and take a rag and wash yourself down.."

**Comment by AvelJames** [comment]
This is just an idea for what she could say.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
