### ISSUE TITLE
A note on file extensions

### ISSUE THREAD

**Issue by sarielv** [Monika-After-Story/MonikaModDev#4142]
I was watching some *cough* on youtube play your mod, and he had a problem with getting Monika to accept an apology. When he said he had to take off the extension to make it work, it hit me what the problem really was.

By default, file extensions are hidden on most modern versions of Windows. When you go to create a text file, it will automatically fill in the .txt extension, every time. However, if you have extensions hidden, then this automatic one is filled in unseen to the user. In fact, it remains unseen when you look at in the file browser, so the problem is invisible and it looks like your screwup, not theirs.

I see from your patch notes that you have fixed this bug, but I don't see an issue for it to see if you fixed it _correctly_. Basically, if you're looking for files input from the user, be sure to look for filename.ext and filename.ext.ext       This may help in the future.
-SV

**Comment by sarielv** [comment]
In fact, if the user has to start from a text file and specify a different extension, it might be good to look for filename.ext, filename.ext.ext and filename.ext.txt

**Comment by jmwall24** [comment]
We look solely for the filename here, not the extension, which is what caused the issue before.  Since they were naming it, as you said, `imsorry.ext.ext` which, to the mod, made the filename `imsorry.txt` so it couldn't find it. As you can see below, we are now looking for a filename of `imsorry.txt` or `imsorry`, which cover `imsorry.txt.txt` and `imsorry.txt` respectively.

![Screenshot_752](https://user-images.githubusercontent.com/36523761/56870574-916d6580-69df-11e9-9d44-2293d8c4114c.png)

**Comment by ThePotatoGuy** [comment]
yeah this is already handled. Whoever you were watching was probably using an older version.  The extension is no longer needed and i believe the in-game text has been updated to reflect that as well.
