### ISSUE TITLE
Can the program not give a "toast" message like other programs?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#4172]
I'm not sure of the correct terminology, but programs such as World of Warcraft will have the icon in the taskbar light up if you get a whisper from another player or are attacked by a monster..

Could MAS not have that for when Monika speaks and I'm on another tab?

**Comment by Olliesama** [comment]
But Monika is usually talking alot, it'd give a notification flash almost constantly if they did that.

**Comment by Mcmanybucks** [comment]
> 
> 
> But Monika is usually talking alot, it'd give a notification flash almost constantly if they did that.

Implying that's a bad thing? lmao.

Of course I meant it more for people like me who've "exhausted" her topics of conversation.. make it an option like sensitive mode.

**Comment by fromulus** [comment]
Just throwing in my two cents, but I feel like that would be actually pretty useful for the sleep concern topics.
I have the bad habit of staying up late and just leave Monika in the background, so I often miss those topics when they're being brought up.
I also almost had a heart attack once when I noticed the game had closed without my input, thinking it had crashed on her.
Turns out she had closed it herself so I could go to sleep and she got upset at me when I opened the game again immediately after. :/ 
So yeah, maybe not have that active every time she talks, but I think it would be interesting is she had a way to catch the player's attention for some urgent topics like those.

**Comment by antimockingjay** [comment]
I think I'd like if the game had something like that, especially if you could toggle how much it happens. Maybe an option to not have it at all, or only have it for "important" things, or to have it on for everything. I personally would go with the last one, because I'm just bad at remembering to check in a timely fashion, and I wouldn't have to worry about accidentally not checking anymore.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
