### ISSUE TITLE
[Suggestion] .flac support

### ISSUE THREAD

**Issue by tlin007** [Monika-After-Story/MonikaModDev#4195]
I was looking through 'how to add music' section and I saw that .flac wasn't supported and was wondering if it is possible for MAS to handle .flac in the future. M3-2019春 just started like 2 weeks ago and a lot of their music currently being released online is in .flac format, I know that it's possible to still play the .flac files by converting them into .mp3 (or the other 2 supported formats) online but I'm sure it would be a nice a QoL change for those who use flac more than they do others. Thank you for reading this!

**Comment by ThePotatoGuy** [comment]
[renpy does not support flac](https://www.renpy.org/doc/html/audio.html), therefore we cannot support flac.

[closing as rejected]

**Comment by Rise0956** [comment]
It can use FLAC Audio Formats, at least Renpy version 6.9.1

**Comment by ThePotatoGuy** [comment]
MAS currently runs on renpy version 6.99.12.4.2187 because thats what DDLC ran on.

[This wiki page](https://github.com/renpy/renpy/blob/6.99.12.4.2187/sphinx/source/audio.rst) corresponds to that version and does not list FLAC as an acceptable audio format. Additionally, I did try with flacs when I first added custom music and they didn't work.
