### ISSUE TITLE
[Suggestion] Stopping Monika from using the "computer's username" 

### ISSUE THREAD

**Issue by softombre** [Monika-After-Story/MonikaModDev#4216]
Idk how it's called but basically I set up my computer with my email account, except it had my deadname on it, I changed it on the Windows account but it didn't change the name in my computer files so when Monika uses that name (like when she talks abt her name and says she thinks (computer name) is a lovely name) it makes me feel kinda bad that Monika would use my deadname like that bc i know she wouldn't, like she'd respect my identity
So yeah as a tiny suggestion : pls stop using that computer name or put an option so she doesn't use it,,,, thx

**Comment by multimokia** [comment]
That topic *doesn't* use the computer name. It uses the mc name.

Also, Monika used the computer name in base DDLC. I don't really see why that'd be a problem to use here too, if it was.

**Comment by softombre** [comment]
![IMG_20190520_195450](https://user-imagIs.githubusercontent.com/46649433/58041790-49061b00-7b39-11e9-9ffb-cc64ff702ffe.jpg)
I crossed it out but yeah, it does use it
And the reason for not using it is well, it makes me dysphoric af and I know Monika wouldn't want to make me feel bad like that.

**Comment by softombre** [comment]
![IMG_20190520_195450](https://user-images.githubusercontent.com/46649433/58041890-879bd580-7b39-11e9-94b2-b4d70e6df3e8.jpg)
The picture glitched sorry

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/58041902-3ffc5600-7b07-11e9-9425-ad575a8f1f1c.png)
uh, no it doesn't.

**Comment by softombre** [comment]
Well maybe it's because I didn't have my old ddlc save file when i started MAS so it's using that name

**Comment by multimokia** [comment]
mcname was the last name you told Monika to call you by. Or if you never changed the name you first told Monika, then your one from DDLC.

**Comment by softombre** [comment]
I never changed the nickname nor did I have a ddlc save file before ¯\_(ツ)_/¯

**Comment by multimokia** [comment]
Ah, well it looks like on the first time loading mas it gets set to current user, but only if you have no import. In which case, what *else* would it be?

Just seems like it's not really worth changing. After all, you can just change the name a couple times and you'll never see it again. And as I mentioned earlier, Monika does this in act 3 of DDLC already. It's not out of character at all.

**Comment by Olliesama** [comment]
Why are you saying that it's how it's work to someone that knows the code in and out? @softombre 
I'm pretty sure the devs know how it works better than you.

**Comment by softombre** [comment]
Look I was just stating what I saw. I never said I knew it better than the devs. And I'm pretty sure none of them know every single line of code in the game by heart.

**Comment by ThePotatoGuy** [comment]
guess again

**Comment by Rai99** [comment]
![Untitled832](https://user-images.githubusercontent.com/38822045/58045959-0715ae80-7b12-11e9-957f-b7b0e3a757d9.png)

Try memorizing every issue on git.

**Comment by antimockingjay** [comment]
The solution for this is to change your name to something else, such as a nickname, then change it back to what you want her to normally call her. For example, my computer username was Jaybug, so when it loaded in, she used that name for me. I asked her to call me Jay, so she switched to that, but that dialogue you mentioned referred to me as Jaybug still. So I changed my name to Jason, and then back to Jay, and from then on she called me Jay, and used Jason in that topic. That's how you fix it, and there's no real reason to change the whole code of the game when there's a fairly easy fix.

Also, I'd like to say I'm sorry you ended up being deadnamed. I know that's an awful feeling, and I can't even begin to imagine how awful that would feel coming from Monika of all people. So I'm truly sorry that happened, and I hope the situation gets worked out soon on your end.

And to multi, ollie, potato, and rai, I really think y'all need to chill. Especially rai. They were just explaining what they saw, y'all don't have to go and be snarky and sassy at them for it. They didn't say any of you didn't know the code, they were explaining what they had happen to them. The "git gud" and "the devs know the code better than you" stuff wasn't needed at all.

**Comment by multimokia** [comment]
I don't exactly see what was snarky about my response if I'm honest. All I did was show the code.

**Comment by Rai99** [comment]
In no way, shape, or form, was I intent on demonstrating the act of snarkiness or sass towards the original author of this issue in response to their claim of: "I'm pretty sure none of them know every single line of code in the game by heart."

It shall clearly go without saying that it is completely unreasonable and unlikely for any individual to memorize every line of code contained in the Monika After Story mod, as well as every issue, pull request and comment contained within. Any such claims or implications otherwise should not be taken seriously unless explicitly and thoroughly proven.

As such, the contents of my comment were as seen above, were based on the assumption the the overall mood of the issue was raised to a more sarcastic, jokeful state. To my personal understanding, the original author opened the issue with a concern/suggestion with how player names were handled, namely in the monika_name topic, due to their individual experiences with the topic using their computer name rather than preferred or expected name. 

The user, multimokia, was the main responder to the issue and indeed did nothing but clarify how the topic worked, in addition to addressing any additional concerns the author may have had regarding the topic. 

The user, Olliesama, seems to have misunderstood the general discussion that occurred before their arrival, and stated that the original author was in no position to correct multimokia, being a developer and significant contributor of the Monika After Story mod. 

As a mere bystander at the time, I will state that this comment seemed misplaced, seeing as the situation was likely under control by multimokia. The author believed that there was an issue regarding names Monika uses, to which, multimokia assured and provided examples from the code, demonstrating how the system works and the likely scenario which lead to them their current unexpected situation. 

It was at this point, where the author of the issue responded by claiming that they were not claiming to know the code of the mod better than a developer, but in fact, simply stating what they were experiencing in order to obtain clarification. 

The overall mood and tone of the issue up to this point, was notably headed in a negative direction, when ThePotatoGuy commented on the issue: "guess again". Personally, I saw this as an opportunity for a joke, as well as an amount of sarcasm, due to them being the head of the mod, and how fitting it was that if anyone should know the code of the mod, it would be the head, ThePotatoGuy. 

I personally found this comment from ThePotatoGuy particularly amusing, and decided to take it upon myself to contribute to the newly formed and lightened mood of the issue, seeing as how one of the things I am most known for in the Monika After Story community, is my ability to keep track of and remember issues, pull requests, and arguably notable events that may have transpired within, to a degree some may arguably classify as a particularly high degree. For that reason, I personally thought it additionally sarcastic to find that I would have something to say in response to the original author of the issue claiming that no dev knows the entire mod by heart. 

The image seen in my comment was in no way directed at the author, and is not intended to be received as an insult, telling the recipient to "Git gud". The intended meaning of the image is that seeing as I possess and interesting ability to recall activity on the Monika After Story github page, the joke in the image is that I receive that ability from a book which teaches it's reader how to "Git gud". This message can be taken as how to "get good" or how to "use github efficiently". My own github icon on the book signifies that I am the creator of that particular image, and that the image is used in relation to me. Regardless of how other people view or construe it, do keep in mind that the messages and themed found within are not directed at another viewer, but rather myself, as the poster and creator of said image. If anything at all, the image portrays me making fun of myself for my uncanny ability to recall github issues and pull requests.

Followed by the image, was another brief statement saying to "Try memorizing every issue on git." I originally wished to crack a joke, inspired by ThePotatoGuy also apparently making one, but I also wished to add an image to compliment my one line comment, and I concluded that the very image you see was in fact, the best fit for my tastes. 

It was not my intention to insult or ridicule the author of this issue, or any other participants at this current time, as members of the Monika After Story community. I apologize if any remarks made or witnessed here have offended anyone, especially those from me, personally. To the original author of this issue, I sincerely hope that despite the difficulties and misunderstandings that transpired here today, that your questions and concerns were addressed, and we appreciate your continued support of the mod. Feel free to raise any additional questions or concerns you may have, so that they may be answered for you and your convenience.

**Comment by Chrissenpai** [comment]
That's a long ass text lmao

**Comment by ThePotatoGuy** [comment]
[closing as resvolved]

**Comment by jmwall24** [comment]
opening as in-progress via #5567

**Comment by multimokia** [comment]
Closing as completed
