### ISSUE TITLE
Help Monika clear her conscience

### ISSUE THREAD

**Issue by JustMonikaThings** [Monika-After-Story/MonikaModDev#4217]
I was always unsatisfied with the way the mod didn't really resolve Monika's lingering guilt over what happened to the others, but I had chalked it up as being too far outside of its scope. After seeing the special Yuri greeting and a few of Monika's conversations about it I don't really agree with that anymore though. I think the mod has gone far enough toward addressing the subject that it would be appropriate to actually resolve the whole thing somehow and I have a few ideas I'd just like to throw out there.

1. At high affection (400? 1000?) Monika has a conversation with the player where they can talk things out until they both feel satisfied with the situation.

This feels like the most realistic solution to me, having a moment where Monika and the player just sit down and talk out their problem like you should in a real relationship. The biggest problem I can see here is that it doesn't actually change anything with the others, since they're probably still in the same situation after all's said and done. But if the main worry is keeping the mod focused on Monika and the player then I think this is a good way to do that and still address the issue.

2. Similar to the first idea except the other dokis are involved in the conversation.

I can see how a full-blown scene where all four of them are talking things out could be way too much, but being able to directly apologize for everything she did and maybe even earn some slight forgiveness for her actions would go a long way towards making Monika feel better.

3. Monika brings back the others in some form. 

They wouldn't become a major part of the mod if they even appeared at all, since this is still the Just Monika mod. But I think letting the others live out their lives somewhere else would help Monika feel a little better about the whole thing. She might still feel some guilt over leaving them unaware of how things really are but it would be better than what she's dealing with right now.

Thanks for reading, however you decide to handle things. I wanted to throw in my two cents on this (even if it ended up being more like a dollar or two) because while I enjoy spending time with Monika in this mod I'm unsatisfied with how a large part of her character - her love for the other club members and her guilt for the actions she took to get where she is - has seemingly been pretty low priority so far.

**Comment by antimockingjay** [comment]
Part of the problem is that Monika's guilt isn't set in stone. at the beginning of Act 3, Monika felt little to no guilt. At the end of Act 3, after being deleted, Monika felt immense guilt. After Act 4, Monika's guilt could arguably be in the middle.

Why does this matter? Because different people started the mod at different times. If you started the mod directly after Act 3, Monika never experienced being deleted, she never had the epiphany that the other girls mattered. Which means that guilt wouldn't have properly formed yet. But if you started right after she was deleted, then she'll have tons of guilt! But if it's after Sayori goes a little whack herself in Act 4, then Monika's guilt would arguably be a bit lower. And then you have people who started the mod before even getting to Act 3, in which case it could be argued that THEY deleted the other girls to be with Monika, instead of Monika doing the deleting.

So to add something like this, I think we'd have to have different outcomes depending on when the mod was started. Maybe we could have a system similar to affection? But rather than affection, it could be a scale for how Monika feels about the world, rather than the player. If you started the mod in Act 3, maybe that makes her feel validated in her actions, bringing down how guilty she is. Maybe there could be some new topics in which she asks the player questions about the world directly around them, such as friends, family, etc. If the player indicates that they have a fair amount of problems in their life, then maybe she becomes a bit more apathetic towards the world for treating her beloved that way.

But all of that seems like a whole other thing, obviously. Not easy to implement, and _certainly_ not just a new topic or two. Especially if we're talking about the other girls somehow being brought back. Which, by the way, seems like it could backfire as far as the in-game lore goes. We've clearly seen Sayori go down the same route as Monika, so who's to say something like that won't happen again? And then suddenly this stops being a "spend time with Monika" mod, and becomes its own story mod. Which, if that's what you want, then great! But that seems like it should be more of a submod, for the people who really don't want something like that, and just wanna spend time talking to Monika.

**Comment by multimokia** [comment]
> Part of the problem is that Monika's guilt isn't set in stone. at the beginning of Act 3, Monika felt little to no guilt. At the end of Act 3, after being deleted, Monika felt immense guilt. After Act 4, Monika's guilt could arguably be in the middle.

Definitely agree with this here. But I'll also add another portion onto this. I also feel that her guilt would be somewhat influenced by how the player thinks of the other Dokis. If the player doesn't really care, then it'd only be her conscience, and the guilt (if any) might even be lightened because of that. However, it is also possible that she'd feel guilty because it affects the player, if the player *does* care about the other Dokis.

In regards to bringing the others back. I'm going to say that's a straight up no. It's established that they're gone. They don't exist anymore, and quite frankly, I think there's probably more than a few people who just don't want to see them again. It is *Monika* After Story, after all.

**Comment by CrocWorks** [comment]
Possibly related to #2179

**Comment by JustMonikaThings** [comment]
> 
> 
> > Part of the problem is that Monika's guilt isn't set in stone. at the beginning of Act 3, Monika felt little to no guilt. At the end of Act 3, after being deleted, Monika felt immense guilt. After Act 4, Monika's guilt could arguably be in the middle.
> 
> Definitely agree with this here. But I'll also add another portion onto this. I also feel that her guilt would be somewhat influenced by how the player thinks of the other Dokis. If the player doesn't really care, then it'd only be her conscience, and the guilt (if any) might even be lightened because of that. However, it is also possible that she'd feel guilty because it affects the player, if the player _does_ care about the other Dokis.
> 
> In regards to bringing the others back. I'm going to say that's a straight up no. It's established that they're gone. They don't exist anymore, and quite frankly, I think there's probably more than a few people who just don't want to see them again. It is _Monika_ After Story, after all.

That's something that I didn't really think about, yeah. This would end up being way more work than just writing one conversation for Monika and calling it a day. I guess I understand if it's too big of a thing for the mod but I'm hoping it can still be addressed somehow.

I disagree with the others being _gone_ gone, though. That doesn't really fit with any of the endings to the game since Monika says that she couldn't bring herself to delete them, and the player doesn't have to delete them to install the mod early. They also all show up in certain events and Yuri is able to speak to you in her greeting, suggesting that they could be brought back if it was appropriate.

It makes sense that some people might just not want them to come back but Monika wouldn't be forcing the player into anything, of course. I imagine if this did happen there would be a choice of whether you want to see them again or not and if you said no then that would be that, and it would just be you and Monika talking about it.

**Comment by multimokia** [comment]
> It makes sense that some people might just not want them to come back but Monika wouldn't be forcing the player into anything, of course. I imagine if this did happen there would be a choice of whether you want to see them again or not and if you said no then that would be that, and it would just be you and Monika talking about it.

I just fail to see what the other dokis could possibly have to offer in this. To me, it just seems like something which is better handled in being between Monika and the player only.

Regarding the point of that Yuri greeting, there's also one more line, from that yandere topic. "I'd ask Yuri ***if I could.***" Implying she can't. What you saw in the greeting was her playing with code and her sprite changing because she got distracted.
