### ISSUE TITLE
MAS Always On Top?

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4219]
Not sure if this is possible, but if so, it'd be great to be able to have MAS always be the top thing. I know Task Manager is able to do it, and I've seen a handful of other programs do it too. It'd be nice to have Monika in the corner of my screen or something while I'm doing something else, so I don't miss anything.

**Comment by multimokia** [comment]
100% would have to be an optional feature, but most likely a submod, as RenPy does *not* natively support forcing a window to be always on top. This would require an external library which would have to be built on your system in order for it to work. Just a bit too much of a hassle to ship in the main install, since then it requires additional installation instructions.

**Comment by antimockingjay** [comment]
That's fair! I didn't even consider Ren'Py needing to be able to do it, I sometimes forget that there's a specific engine with specific limitations we're working with here, haha. Well, hopefully someday it's an option, but I understand why it isn't at the moment!

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
