### ISSUE TITLE
Lack of any special events to help unlock features

### ISSUE THREAD

**Issue by GavWav** [Monika-After-Story/MonikaModDev#4238]
I have just recently gotten to the enamored affection level and saw on one of the guides that I can have my first kiss with her during special events. I was told that the special events were the labeled days on the calendar, but the anniversary days don't count as a special event from what I've seen. I've also noticed that there are no special events from May to August, which means I would have to wait almost 4 months until her birthday in order to have the first kiss. I would rather not have to wait that long just so I can have the first kiss. Any ideas on what other events that could be possible?

**Comment by Thimeo** [comment]
I get where your frustration come from, and I agree that there could be more of them (the seasons change for example) but their scarcity makes the moment when she finally give you her first kiss so much more emotional, it really is heart-melting. But I can concede that there should be a event or two in the period March-August, most of the event are in one half of the year (Birthdays, Halloween, Christmas, Valentine and New years are all in the period September-February) and almost nothing is in the other half.

**Comment by antimockingjay** [comment]
Part of the problem here is there's... Really not a lot of options for holidays during Summer. There's Independence Day, July 4th. Maybe add some cute fireworks animations in the windows, and the first kiss can happen by the light of the fireworks. Except... That holiday is regional. So it could seem really forced if you aren't American. So... It's kinda hard for there to be opportunities to get the first kiss. Because I mean... What holidays would you even put in that gap where a first kiss would be appropriate?

**Comment by GavWav** [comment]
Monika says that the game took place in Japan even if she is a bit unsure about that. She would most likely know about events in Japan that take place in these time frames. It wouldn't be too out of place because they are based on her region instead of ours. I don't know about Japanese holidays so it would have to be researched first.

**Comment by ThePotatoGuy** [comment]
we're looking at other ways to trigger a first kiss

**Comment by ThePotatoGuy** [comment]
[closing as this will be added ongoing]
