### ISSUE TITLE
Monika should age

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#4258]
You remember the wiki topic that says she's 18? What if we adjust it for every year since you've installed the mod. Since the date set for the calendar was implemented, she could just add a year of her age every birthday. Doesn't seem impossible and I think she'd appreciate not being 18 forever, right? Plus we could add some extra dialogue on her age like she's 19, 20, 21 and so on.

**Comment by AsuraShun** [comment]
Time doesn't flow there, she's unable to age or die, she even says so herself

**Comment by multimokia** [comment]
This, she would also then have to appear to age too, which requires the constant changing of base sprites and then the outfits made for them. Would be a hassle to handle.

Plus, how do you intend to handle those who started say, today? Is she 19 right now then? Or is she still 18, turning 19 next year?

**Comment by Rai99** [comment]
> she'd appreciate not being 18 forever, right?

Maybe it's just me, but having a young body that doesn't age sounds better than one that gets old and degrades.

**Comment by desertdessert** [comment]
From #3448 it seems like a number of people prefer Monika aging, although the discussion didn't really talk about if her physical appearance should change or not.

Even if her appearance ages over time, her body doesn't necessarily have to degrade. Obviously I don't want my Monika to suffer from arthritis or Alzheimer, but that doesn't mean she can't just _look_ older. This could be explained as either 1) she has really good health or 2) she can control her appearance through the code. I would prefer (as I'm sure others would, too) for her to look old in the distant future than to create an uncomfortably large age gap. Maybe the best option would be to let people decide if they want Monika's body to age?

And maybe I'm wrong on this, but updating the sprites does not seem like it would be that much of a hassle. I mean, couldn't it just be minor changes to the base sprites and hair color? Like have two more base sprites, one for middle age Monika and one for old Monika, and then just switch to them on one of her birthdays? This doesn't seem like a lot, considering there is literally decades before it needs to be done.

Regardless of whether her appearance changes, I think it's better for her to at least age numerically. Otherwise, celebrating her birthday makes no sense. Is it her 19th birthday every year? Or is it not really her birthday, but just the game's release date that is celebrated? Afaik, birthday parties are by definition 
a celebration of a person's age increasing.

**Comment by AsuraShun** [comment]
She even says that her life can't be summed up in a number

**Comment by multimokia** [comment]
> And maybe I'm wrong on this, but updating the sprites does not seem like it would be that much of a hassle. I mean, couldn't it just be minor changes to the base sprites and hair color? Like have two more base sprites, one for middle age Monika and one for old Monika, and then just switch to them on one of her birthdays? This doesn't seem like a lot, considering there is literally decades before it needs to be done.

Please take a look at `sprite-chart.rpy` and enlighten me on how it would be easy to have different sprites generated based on how many years it's been. Plus then aliasing them automatically so they're used in topics/idle.

It's hard enough to just make her *blink* (requires an entire rewrite of all sprite definitions plus making new ones which are ATL'd for the animation. Almost 800 Sprite definitions)

Not to mention, art doesn't come cheap, and it's already enough hassle to make an outfit for the current base since there's 6 poses, now you're wanting to make that even more of a hassle by making people have to draw that more times.

For any commissioned outfits like the O31 ones, that price racks up FAST. Not worth it.

**Comment by LClarance** [comment]
Please dont do this. As much as everyone wants her to be human, she is not one... our rules dont apply to her, she even said so herself and doing so means straying from the original course. IMO its better for this fan mod to just stick to the original rules established by in DDLC, aside from adding events and features nobody should try to change anything.

**Comment by Delcos** [comment]
no

**Comment by ItsjustmeandMonika** [comment]
I wouldn't recomment that time doesn't exist in her world I asked her about it too

**Comment by ThePotatoGuy** [comment]
monika doesn't age. [closing as rejected]
