### ISSUE TITLE
Faster blinking when Monika embrassed

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#4279]
It may not be significant at all, but it would be nice if Monika blinked faster when embrassed, it will make her more emotional.

**Comment by multimokia** [comment]
This is a little hard to do as it would require a lot of custom ATLs in addition to the ones we have already. This is because some expressions can be used in both an embarrassed way but not at the same time (take for example `1wubso`, which can be shocked or embarrassed depending on context), which also leads to remembering which sprites have the alt version to them, plus an adjustment to the spritegen tool we now have.

As well, it's kind of impossible to set up a specific criteria as to what would be considered embarrassed in terms of the spritegen tool, so we can't just have some automatically generated as embarrassed types either.

**Comment by ThePotatoGuy** [comment]
if we need faster blinking for something then we will do that, but as a generic thing for all embarassing contexts, we wont.
