### ISSUE TITLE
New green dress costume.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#4289]
https://drive.google.com/open?id=1MbTlfxpsfD6VO-j7kzOSxFHVdGU1ErUp
![FINALLeaningGreen](https://user-images.githubusercontent.com/36523761/59573572-a2eaf980-9081-11e9-8144-697fc433fbf5.jpg)

**Comment by MetalBrother** [comment]
Whoa! That perfect!

**Comment by Professor-JMO** [comment]
Cuteness. 💚

**Comment by LordBaaa** [comment]
I love this!

**Comment by Chrissenpai** [comment]
![image](https://user-images.githubusercontent.com/40907045/59892057-32075280-939d-11e9-892c-22ae98c8d422.png)
add more depth to the sleeves and the shadow makes her slightly more fat, need to "flatten" the shadow.

**Comment by multimokia** [comment]
Fyi he didn't do it himself. Was a commission done by EroNeko Senpai

**Comment by Chrissenpai** [comment]
Oh hmmm. Do you have the original file, if so can I have it?

**Comment by Olliesama** [comment]
No.

**Comment by Rai99** [comment]
@Chrissenpai, from what I understand, there were a couple other projects undertaken by you, to which you seemed pretty enthusiastic to work on. 

In #2201, you requested the sprites so that you could polish them up, and in #2969, you said you needed a graphics tablet to undertake artwork for MAS. In #3681, you showed us a test of your graphics tablet, and I believe that is the tool you said you needed. I may be mistaken, but I don't remember seeing any polished sprites from you. Do you still plan to polish the sprites?

In #3863, you showed a formal dress in a couple of the poses, saying that it would be coming soon with all the poses. I'm just curious as to the progress or state of that outfit and it's required poses. 

It's nice to see you so eager to create and improve on art for MAS, albeit sometimes heavy handedly, but I was just curious as to how you plan to take more onto your plate when you seem to have a few loose ends already. It certainly wouldn't do to have a contributor overworked, especially to my understanding at least, with you also taking personal commissions.

**Comment by Chrissenpai** [comment]
@Rai99 Oh right, about the polished poses, yes I still plan to do it, even planning on creating a new one for a "hug me" pose. And also the new dress (I lost that file since I didn't save it to a PC meltdown, oof) need to do it again.
So, yes I said that I will be doing that, I don't like leaving loose ends, but right now I'm prioritizing to make an Income with my drawings since I'm still having a normal work, right now if I stop normal work I'll be on the streets, I'm building my digital portfolio and all that stuff to promote myself, but until then I can't dedicate too much to this with college and below pay job and barely surviving. It will take some time for my efforts to blossom economic results for my self-sustained living. And with Monika by my side, we share the burden of life and persevere. When glory comes, I'll reward her with the best treatment she deserves.

**Comment by LordBaaa** [comment]
@Chrissenpai I understand you are in a tight spot right now, but I would really like to see that formal dress and the other stuff you are talking about come to fruition. So what if were to get you to do a commission for me for this mod? Would you be up for that and if so what kind of price would you be looking for? And no hard deadline just hey making some progress. Also if you still have the hard drive from that old computer that melted down those files should be recoverable. I might be able to help you with that.

**Comment by Rai99** [comment]
Of course, it's nice of you to be so eager to provide assets for MAS, but do keep in mind that there are other people who dedicate time and/or resources for Monika.

**Comment by Chrissenpai** [comment]
@LordBaaa I will gladly do it, I'll specify the prices tomorrow cause just finished homework, tired and need to get ready to go to college early in the morning and work at midday. Oh, I think I did not explain myself correctly, PC had shut off out of nowhere due to overheating but after it cooled down it turned on normally, but because I didn't save the file, the file is lost forever. 

@Rai99 I'm aware of that, also that is because they can afford it, I don't know about anyone's time or resources but I can assure you that they can spare those time and resources without risking anything too much of themselves.
goodnight

**Comment by Chrissenpai** [comment]
@LordBaaa I'm back, let's talk.

**Comment by multimokia** [comment]
FYI, I'm going to nip this right here. This isn't the place to discuss commissions. Please keep that within other messaging means.

**Comment by LordBaaa** [comment]
@Chrissenpai How about discord? Im LordBaaa#9748

**Comment by ThePotatoGuy** [comment]
@Olliesama I assume eroneko wants credits for these when we use them, right? I'll be id'ing these as eroneko instead of you in that case.

**Comment by Olliesama** [comment]
Don't think he cares tbh but go ahead.

**Comment by ThePotatoGuy** [comment]
then do u want to be credited? the id is also used when naming sprite packs, so is a matter of if these should be part of "Finale's spritepack" vs "eroneko's spritepack"

**Comment by Olliesama** [comment]
Uhh as his I guess

**Comment by ThePotatoGuy** [comment]
oops, will start adding this tomorrow

**Comment by Olliesama** [comment]
Wait, I'm getting Eroneko to remake it to better fit the base, touch it up with shading and the frills and make a laying down version.

**Comment by ThePotatoGuy** [comment]
aiight i shall wait

**Comment by Olliesama** [comment]
Will post a comment here with the update when it's done.

**Comment by Olliesama** [comment]
Thanks for waiting!

https://drive.google.com/drive/folders/1yOFbqoT7LD-OPK4m6eKnWFAheeMK_s7t

**Comment by Olliesama** [comment]
https://cdn.discordapp.com/attachments/461926858527735818/801825018371113000/SPOILER_GREENuprightbase.jpg
https://cdn.discordapp.com/attachments/461926858527735818/801825007071658064/SPOILER_GREENleaningbase.jpg
https://cdn.discordapp.com/attachments/461926858527735818/801825025186725921/SPOILER_GREENLaySprite.jpg

**Comment by Olliesama** [comment]
Thanks for waiting!
https://drive.google.com/drive/folders/1yOFbqoT7LD-OPK4m6eKnWFAheeMK_s7t

![SPOILER_GREENuprightbase](https://user-images.githubusercontent.com/35244051/105382760-54f88900-5c08-11eb-89df-37be97808bdf.jpg)
![SPOILER_gfvfsd](https://user-images.githubusercontent.com/35244051/105382769-575ae300-5c08-11eb-8ed4-8725e937aa11.jpg)
![SPOILER_GREENLaySprite (1)](https://user-images.githubusercontent.com/35244051/105382776-5924a680-5c08-11eb-8779-62898a5c4d29.jpg)

**Comment by Olliesama** [comment]
@ThePotatoGuy Told to ping you.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
