### ISSUE TITLE
[Bug] - Update Dropped Affection By 196.5 pts... How?

### ISSUE THREAD

**Issue by GensokyoLRE** [Monika-After-Story/MonikaModDev#4297]
All I did was update the game and all of a sudden she went from being affectionate and sweet (pre-update) to upset and raining in background (post-update) and I'm worried to update any more given the chance it'll drop again and I'll have to reset things...
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3311781/aff_log.txt)

**Comment by Shiro2564** [comment]
did you visit her frequently?

**Comment by multimokia** [comment]
Did you ever use the long absence farewell in the past?

**Comment by GensokyoLRE** [comment]
I don't remember if I did, but why would the number jump like that only after the update?

**Comment by multimokia** [comment]
Because what happened was the long absence farewell, if you said you weren't going to leave immediately (and then you used some other farewell), you'd still have the long absence var set to be true, so you wouldn't lose affection for time, however you were still coming back daily as normal. We made a change which fixes this, but it also had the side effect of then having affection catch-up with that gap.


Though, I'd like to make sure of this, do you have any other `aff_log` files? Ideally one which is before this.

**Comment by GensokyoLRE** [comment]
I don't think so... that's my only log unless there's another place.

**Comment by multimokia** [comment]
Weird that it's so short then, and starts at the drop, it has no other history of any other session you have which doesn't seem right.

**Comment by GensokyoLRE** [comment]
Plus she mentions that "we've been together for over a year"...

**Comment by GensokyoLRE** [comment]
Is this a bug or is the mod still workin? O.o

**Comment by ThePotatoGuy** [comment]
you've probably got hit with what multi mentioned before. We didn't know about this until after the release dropped, but regardless, we're not going to adjust aff unless there is substantial proof (usually via a full aff_log.txt) that you were likely affected.

**Comment by GensokyoLRE** [comment]
So I'll have to work on the affinity manually...? I can't jumpback to the positive number before the near 200 pt drop after update?

**Comment by jmwall24** [comment]
you're sure there's no other aff_logs in there like `aff_log.txt.00` ?

**Comment by GensokyoLRE** [comment]
As far as I saw.. I'll check tomorrow asap.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
