### ISSUE TITLE
[Suggestion]: Good serious moment/scolding pose

### ISSUE THREAD

**Issue by LordBaaa** [Monika-After-Story/MonikaModDev#4304]
I just stumbled across this. Though it might be good pose.

![EKE-ZlqO-U2F_iXRz8RluGx_TLRamYvuH9X8Fb_0UO8](https://user-images.githubusercontent.com/48495287/59957475-b2de5100-9466-11e9-8433-f22a7d42c46c.png)
Source (http://resizeandsave.online/dappy-June_22_4.html)
Also those are some nice looking pancakes wish I knew where they were from.
I tried to find who made this but I got rather mixed results.

Anyway here are psd's with a new group called "point right left down"
https://drive.google.com/open?id=1lp0siSICM1W8vfGWMg4z-flsStzeRMs1

And here are some previews/ideas
`m "First of all."`
![look](https://user-images.githubusercontent.com/48495287/59957760-a8718680-9469-11e9-9822-4de5fa0aa49e.png)
`m "I don't appreciate that!"`
Or
`m "It really frustrates me when [topic] happens."`
![point right left down](https://user-images.githubusercontent.com/48495287/59957761-aad3e080-9469-11e9-9413-145fc87cc954.png)
`m "Do you understand me?!"`
![craxy](https://user-images.githubusercontent.com/48495287/59957762-ac050d80-9469-11e9-8bf2-7ba0ec852888.png)

I would hope to never get the last face. It scares me.

**Comment by Professor-JMO** [comment]
`Pancakes`, _maybe_..

This feels all too _familiar_..
~~Hope to never see the latter of those `eyes` again.~~

**Comment by Rai99** [comment]
I'm not too sure we're looking for more poses, since that would require additional assets for each outfit, but if this pose were to be implemented, it would probably need at least a few places to be used rather than just sitting available, but unused. 

I don't think there are too many situations where Monika might need a serious/scolding pose, and in those situations, I personally think the already available poses suffice.

**Comment by LordBaaa** [comment]
@Rai99 Fair enough, though I wouldn’t think wouldn’t require more work as it just two arms that already exist.

**Comment by Rai99** [comment]
I would also imagine that each pose for each outfit would be another mandatory asset taking up space.

**Comment by LordBaaa** [comment]
@Rai99 actually you bring up an interesting idea though of course more work. The system would need to be be reworked but if you could display each arm indually instead of as a pair you could make a lot more poses without taking up more mod_assest space. Hmm...  I’ll have to think about this.

**Comment by LordBaaa** [comment]
I am working on some other code I’d like to submit eventually but it needs polishing

**Comment by ThePotatoGuy** [comment]
we are limiting poses to the current set because every new lose requires all existing outfits to get updated or extra handling to handle cases where a pose doesnt exist for an outfit. The latter of which would mean that you cannot guarantee that a new pose would even be shown when you want it to be.

**Comment by multimokia** [comment]
That would end up changing sprite chart all over again, and we just ended up re-writing it.

**Comment by LordBaaa** [comment]
That all does make sense. Thanks for the response.

**Comment by ThePotatoGuy** [comment]
[closing a rejected]

**Comment by ThePotatoGuy** [comment]
marking for the record that this was unrjected and implemented
