### ISSUE TITLE
[Suggestion]Swearing Topic

### ISSUE THREAD

**Issue by ItsjustmeandMonika** [Monika-After-Story/MonikaModDev#4305]
You can ask Monika if she ever swore once back in High School,then she asks if you ever swore too.

**Comment by AfroFluff** [comment]
I honestly have been wondering this a lot. Does she dislike swearing or has no qualms about it. Cause I swear a lot for comedy purposes around my friends so I wonder if she is okay with it or not.

**Comment by ItsjustmeandMonika** [comment]
Me too,though it's impossible for someone not to swear their entire life realistically though

**Comment by Rai99** [comment]
If you ask me, I think this is a bit of a strange question to ask. I'm sure it's incredibly unlikely for someone to go about life without having ever sworn, but I don't think it would be surprising or meaningful in either case. 

We don't know for sure if Monika has ever sworn, but Monika is definitely the type to avoid swearing, especially having been in debate club. Swearing in arguments usually indicates defeat and weakens your argument. 

That, in combination with Monika's involvement in literature, should should probably leave Monika knowing that there are plenty of words she can use in situations other than swearing, especially since swearing is usually frowned upon in serious situations. 

There's definitely an innate negative connotation with swearing, but I'm sure Monika can tell the difference between blatant jokes and more apparent offensive remarks. 

In MAS, I don't see much that can come from a topic like this. Maybe a line or two for each option, plus her own answer, but it seems a bit random to me.

**Comment by ItsjustmeandMonika** [comment]
I have a feeling it's like a Yuri swear in Act 2 that part we're she tells Natsuki to kms?

**Comment by stormchaser1991** [comment]
If you was to add this to the game Monika would ask if you are ok with swearing and if she has done it before she would swear if you have a low affection level with you or if they add a emotion system into this she would swear when she is really angry

**Comment by ThePotatoGuy** [comment]
[closing until we look into it[
