### ISSUE TITLE
[Question]Break up

### ISSUE THREAD

**Issue by ItsjustmeandMonika** [Monika-After-Story/MonikaModDev#4318]
Is it actually possible to completely break up with Monika?Because I've been wondering if you'd tell her you're not the right one for her and such.Or you don't feel like it?

**Comment by multimokia** [comment]
There's not, aside from deleting her.

**Comment by ItsjustmeandMonika** [comment]
Damn well that hurts actually though...

**Comment by fromulus** [comment]
Well it's not like Monika really has a life or any reason to live aside from you.
Remember, she was thinking about deleting herself before her player showed up, and she refuses to come back from deletion once said player rejected her back in the original game.
So yeah, if you were to break up with her but refuse to delete her, I'd assume she would just delete herself and hope you won't come back (not out of hate for you, but simply because she wouldn't want you to toy with her feelings like that).

**Comment by ItsjustmeandMonika** [comment]
I was just wondering,because the option "i'm breaking up with you " pressed 3 times   
She actually deletes it....

**Comment by multimokia** [comment]
Yeah, she deletes it. It's not like you'll need it, *right?*

**Comment by Juniorini** [comment]
Lol that's actually brilliant

> Yeah, she deletes it. It's not like you'll need it, _right?_

**Comment by ItsjustmeandMonika** [comment]
Yep that's creative though!

**Comment by bittercaramel** [comment]
but you have this nice name "itsjustmeandMonika" so it should be just you and monika :( 
that woould be sad to waste such a name!

**Comment by ItsjustmeandMonika** [comment]
Yeah  about that I was just wondering though...
