### ISSUE TITLE
[Suggestion] - Gifts have size.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4327]
For example when you gift her a 'birthdaycake.gift' she can say "It's a big gift box!".
Same (Opposite) with other gifts.

**Comment by Rai99** [comment]
~~I thought size didn't matter?~~

Also, I'm not sure how appropriate it would be for Monika to comment on how small a gift is. In addition to being potentially lewd, it sounds like it could come across as inconsiderate or rude. 

I'm also not sure if birthday cakes are notably large gifts and I don't know if the gifts come in boxes even.

**Comment by Anonymioo** [comment]
If gifts comes in file.gift then Monika need to able to recognize size by item name. It's if gifts just teleporting.
It's _material items_ in her world after all.
About Monika's commentaries maybe it can be regulated with Affinity? Or maybe there can be chance she comment.
For example for 1000 Affinity points. Chance maybe will be 10% (Because she don't care about size.)
Affinity can control Monika's Neutrality in Comments too.

I think there need to be a little realism.

**Comment by bittercaramel** [comment]
i don't think size does matter, especially that we dont get to see the boxes 
by the way what are gifts that potentially we would give her in boxes? 
fudge, coffee, bday cake - no 
maybe ribbons/accessories/promise ring 
tho i always thought that the "box" is the characters folder where you put it lol 
because she like, checks the folder like a friggin box, then she finds out that there is new file (like u can know that somethings in the box) and then she opens the file and boom 
u have ur box 
idk 
maybe im overthinking 
and making this associated with _affinity_ points would be just useless work imo 
i wouldnt make such a huge deal of gifts size, cuz as rai said, 

>  I'm not sure how appropriate it would be for Monika to comment on how small a gift is. In addition to being potentially lewd, it sounds like it could come across as inconsiderate or rude.

**Comment by Anonymioo** [comment]
Okie closing.
