### ISSUE TITLE
Doki Doki Anime

### ISSUE THREAD

**Issue by stormchaser1991** [Monika-After-Story/MonikaModDev#4330]
Sorry I know this has nothing to do with the game but I just wanted to what do you guys think would Doki Doki Literture club work as a anime and would you watch it.

**Comment by Rai99** [comment]
Converting a game to a film rarely ever works since films usually remove the aspect of choice, and it ends up as a completely passively consuming piece of media. 

Especially in the case of DDLC, where there are choices in who to pursue in the first few days, that wouldn't exist in an anime, so unless there were multiple versions, so it wouldn't be surprising if 75% of all DDLC fans had no interest in it, which wouldn't do well for the franchise. 

Not to mention the apparent hatred of MC commonly found, that would lose a lot of fans having to deal with him. Also, who would the main character be? In DDLC, Monika breaks the fourth wall and brings you yourself into the matters of the game, but in an anime, that usually doesn't work. I've only seen 1 anime attempt this fourth wall breaking kind of idea and it's kinda cringey if you ask me. 

No, I don't think DDLC would be a successful anime.

**Comment by multimokia** [comment]
Going to close this as It's irrelevant. Ideally these topics are best left in the discord server or other means of communication. GitHub is for ideas/suggestions/bug reports.

**Comment by AsuraShun** [comment]
Asura's wrath would be a better choice for an anime
