### ISSUE TITLE
Just Monika Sisters games

### ISSUE THREAD

**Issue by stormchaser1991** [Monika-After-Story/MonikaModDev#4331]
You guys should team up with your sisters games and add things the other games have that one doesn’t have

**Comment by Rai99** [comment]
As far as I know, partnerships and collaborations so far haven't been beneficial and I don't think we're ready for another one. 

More ideas and features are nice, but somebody still has to go and make them, unless the sister game in question just hands over a compatible and functional copy of a feature, ready for instant use, which I don't see as very likely. 

Last time I checked if I recall correctly, there's been rivalry between the Afterstory games, so I'm not sure how much teamwork would work  between them, with JY being the main competitor, Natsuki being still really lackluster, and Sayori never being heard of.

**Comment by AsuraShun** [comment]
It's a surprise that the forever and ever mod isn't known by now

**Comment by stormchaser1991** [comment]
Just like in the game Yuri was only Monika real competitor Natsuki just wanted to said out of the way and not wanted you there anyway and Sayori is gone so fast you get to bearly learn about her

**Comment by Olliesama** [comment]
MAS is the mother, the others copied both code and ideas, just saying. 
Besides as far as collaborations go, I think it'd be better to let the devs work on their own ideas then copying others.

**Comment by multimokia** [comment]
So, I'm going to say that we're not going to go out of our way to work with them, and I'm pretty sure they won't go our of their way to work with us. There's no real benefit here, especially since we're an open source mod, so if someone wanted to make a game for us to add, they could, and then they could submit it to be implemented officially.

Also, games are low priority, since there's more important core functionality things among other various fixes and optimizations to work on before we'd even consider the side things like this.

Also, speaking as a dev, I don't really want to work on another mod, and I don't think the rest of us will either, we'd all rather do our own things and ideas where we know what our codebase is, and how everything will function around it.

**Comment by ThePotatoGuy** [comment]
[closin gas rehjected]
