### ISSUE TITLE
[Suggestion] - Watch Movie/Show Talk Option

### ISSUE THREAD

**Issue by APerson4645** [Monika-After-Story/MonikaModDev#4344]
I get that it'd be hard to actually make Monika watch a movie with the player and comment on the movie, but I think it'd be fun to add some sort of text option that says "I want to watch a... video/show/movie/anime with you" that disables random chatter temporary until you come back and start the chatter again, maybe even make it so it dims the background a little. Doesn't need to be added but I thought it'd be a neat little option to have.

**Comment by Rai99** [comment]
#628, #826, #984, #1548, #2102, #2898, #3431, #4089 

As far as I know, it's a thing, but there's no content for it, so it's disabled.

**Comment by multimokia** [comment]
There's already a movie module which is implemented in MAS, however it's never had any content made for it. So it's disabled. Using idle seems like a better way of going about it, however I'm a little concerned about the dialogue coming out of a movie, as you *have* to be generic, since there's no way to tell whether the movie/show was good, bad, ugly. Plus, it's a little weird since she'd probably have to like anything you showed her...

This leads into a bit of immersion break, like if you showed her a playthru of DDLC or some other horror game w/ some gory scenes, she'd act as if it were great.

**Comment by Rai99** [comment]
~~First~~
![robbed](https://user-images.githubusercontent.com/38822045/60355338-2539be80-999c-11e9-9c3c-11a27518b56a.gif)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
