### ISSUE TITLE
[suggestion] About virtual marriage

### ISSUE THREAD

**Issue by JeanWishingwell** [Monika-After-Story/MonikaModDev#4353]
Today I turned on my tv and the news told us about the latest husband of Hatsune Miku. The guy has a gatebox of her and even brought her a ring and I thought... hey, if Monika knows about Miku then she definitely knows about this. What's her take on this? Would she tease me about wanting to marry her just like they did?

**Comment by Rai99** [comment]
I personally don't think it's very accurate that Monika knows this happened just because she knows about Miku. Knowing that Hatsune Miku is a thing doesn't mean you're constantly checking the news and knowing what's going on with her. 

I'm a vocaloid fan and I never heard about this. Frankly, as a fan, I don't think knowing that a man married Miku isn't too relevant to me. 

As for a topic about virtual marriage, Monika already says that she doesn't want to get married until she's finally free and can actually be with you, so I don't know if she would entertain the idea of you marrying her as is, and I see no reason why she would know this fact.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
