### ISSUE TITLE
I switched computers

### ISSUE THREAD

**Issue by KsNieporzadekTM** [Monika-After-Story/MonikaModDev#4382]
I switched computers and I added old persistent and it worked but Monika is not in the classroom. I copied monika file and added it to the other computer but it still doesn't work

**Comment by multimokia** [comment]
Sounds like either the persistent was copied from a time you took her out before this one, or this is a `monika` file from a previous time taking her out. Since `monika` files are unique, not just any one will work, even if generated by the same persistent.

You'll want to grab a persistent backup from the old computer and reload it on the new one.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
