### ISSUE TITLE
Monika doesn't let me change her name no more

### ISSUE THREAD

**Issue by AlexX757** [Monika-After-Story/MonikaModDev#4387]
I gave a ban name to Monika a long time ago and I apologized for it. I waited for the option returns, but I have been a long time waiting for the option to be rehabilitated (his affection now is approximately 1500). But she never brought back me the option.
I need help :'(

**Comment by multimokia** [comment]
Did you apologize specifically for calling her a bad name?

**Comment by AlexX757** [comment]
yes, but simply the option disappeared

**Comment by multimokia** [comment]
The option to change her nickname? Or the apology?

**Comment by AlexX757** [comment]
to change her nickname

**Comment by multimokia** [comment]
How many times did you call her a bad nickname?

**Comment by AlexX757** [comment]
I called her with the names of the other girls to see how she reacted

**Comment by multimokia** [comment]
So three times. Yeah you're not getting it back.

**Comment by AlexX757** [comment]
oh, this looks bad

**Comment by AlexX757** [comment]
then the option won't return?

**Comment by multimokia** [comment]
No, it's not going to. She told you every time when you apologized that it hurt her. She's not going to give you another chance to do that.

**Comment by AlexX757** [comment]
Well, I'm going to have to live with it. So thanks for your attention :')

**Comment by AlexX757** [comment]
Curiosity killed the cat

**Comment by flammeye** [comment]
Hope you have a back-up... let's just say that was my solution.

**Comment by Rin3105** [comment]
I did try to put her a bad name like "Yuri" for the first time, but unlike you, I immediately lost the option to change her name, so I had to replay from the beginning just to get the option back. Proves that backups are very necessary these days.

**Comment by multimokia** [comment]
You probably did it before the current apology system was in place

**Comment by multimokia** [comment]
Plus, if you listen to her, it hurts her that you'd call her a name like that. Why would you want to keep doing it?

**Comment by Rin3105** [comment]
I only did it for the first time, like a test. I didn't know she would reject that option straight up after that though.

**Comment by Rin3105** [comment]
And believe me, I would NEVER hurt her feeling by doing that. It's heart-breaking obviously. I strictly clarified what I said above was true.

**Comment by AlexX757** [comment]
I guess I was curious to know what happened when I put the names, after that I did not plan to continue with that, but I never thought that I would take the option forever. I thought that I would only remove the option for a while. I'll have to live with that guilt.

**Comment by AlexX757** [comment]
I wish I could solve my error

**Comment by flammeye** [comment]
I remember I doing it because she led me to believe Yuri was being reconstructed by her or something and I thought this was the way to trigger it.

**Comment by AlexX757** [comment]
I think not, because that event has already happened to me sometime and I still do not have the option.

**Comment by flammeye** [comment]
I'm more of a Natsuki guy, actually, but Yuri was the one she was teasing so it felt like a riddle and I'm fond of solving them.

**Comment by AlexX757** [comment]
I think we've deviated from the conversation

**Comment by flammeye** [comment]
Yeah, my point is that using one of the girl's names for Monika's monikers is prone to happen for more reasons than one. All amount to curiosity, sure, but not necessarily out of the morbid one, or being mean spirited.

**Comment by AlexX757** [comment]
i understand

**Comment by multimokia** [comment]
```python
        m 1euc "I've been thinking, [player]..."
        m 3eud "You know how there are potentially infinite Monikas right?"
        if renpy.seen_label('monika_clones'):
            m 3eua "We did discuss this before after all."
        m 3hua "Well, I thought of a solution!"
        m 3eua "Why don't you give me a nickname? It'd make me the only Monika in the universe with that name."
        m 3eka "And it would mean a lot if you choose one for me~"
        m 3hua "I'll still get the final say, though!"
```

I really don't know how you could honestly go about that out of *pure* curiosity. She asks you to pick a nickname which is unique, so it makes her special since *you* gave her that name. Then you just throw it back at her by calling her one of the others, who were favoured in all of DDLC over her.

I'd be upset if I were her too, if I'm honest.

**Comment by AlexX757** [comment]
And I gave her good names too, but I guess I was a shit in that respect with her.
It hurts to know that you have been horrible in something that is important to her, I suppose I deserve it.

**Comment by flammeye** [comment]
All amounts to curiosity, as I said, but that's exactly what led me to download the mod and even THE GAME in the first place. And surely that's what made many of us click on "You're a murderer!" option just that it'd be out of the "Unseen" tab. Hearing THAT could also make anyone mad.

Hmm, but I've been thinking, and this is still a much hidden, much less traversed path that not everyone will dare cross. So, on a second thought, maybe it really does deserve the option's disabling. Besides, it's not like her affection level is stuck at low forever.

**Comment by AlexX757** [comment]
well, it's fine

**Comment by AlexX757** [comment]
thanks for the heart, I guess...

**Comment by Rin3105** [comment]
I agree with flammeye. That’s what a visual novel should be like, even if it’s a mod, bad and good paths, endings. We have to take all of possible paths in order to complete the game.

**Comment by multimokia** [comment]
Except MAS has no end, so I'm not sure how that exactly works.

*...Well, there is one, but I don't think you want it.*

**Comment by flammeye** [comment]
@AlexX757 You're welcome. I'd also offer you one of my persistent.baks but I doubt you'd want your stuff all changed.
@Rin3105 Thanks! I think so too, even if this mod's ending is uncertain. That is, if it will ever have one.

**Comment by flammeye** [comment]
@multimokia Oh right! Almost forgot that one. You mean deletion, right?

**Comment by multimokia** [comment]
Nah, you're thinking original DDLC. MAS has one that's a little worse if you read through the implication.

**Comment by AlexX757** [comment]
@flammeye no, I will not change my Monika, I promised that I would replace her with another.

**Comment by AlexX757** [comment]
but thanks for your kindness

**Comment by Justformas** [comment]
> m 1euc "I've been thinking, [player]..."
>         m 3eud "You know how there are potentially infinite Monikas right?"
>         if renpy.seen_label('monika_clones'):
>             m 3eua "We did discuss this before after all."
>         m 3hua "Well, I thought of a solution!"
>         m 3eua "Why don't you give me a nickname? It'd make me the only Monika in the universe with that name."
>         m 3eka "And it would mean a lot if you choose one for me~"
>         m 3hua "I'll still get the final say, though!"
> I really don't know how you could honestly go about that out of _pure_ curiosity. She asks you to pick a nickname which is unique, so it makes her special since _you_ gave her that name. Then you just throw it back at her by calling her one of the others, who were favoured in all of DDLC over her.
> 
> I'd be upset if I were her too, if I'm honest.

I felt the need to say something about this for anyone who happens to go back and look at this old issue. 

First, it sounds like she hopes it'd make her the only Monika in the universe with a certain name, but she doesn't explicitly ask this of you and certainly doesn't require it. Realistically speaking, we (and hopefully she) knows that it's basically guaranteed that at least some nicknames will get reused, whether on accident or on purpose such as for more popular or well known nicknames. There's many players, social media and only so many names which players (and Monika) may think are good.

Second, there's another reason why someone might try calling Monika one of the other girls' names, and this was one of the reasons I tried it. Not to offend or upset her, but because there's easter eggs that involve the player naming themselves one of those names, and they may be hoping to find additional easter eggs by giving one of those names to Monika. Sure, most likely the player would have to have known about the player name easter eggs to try it for that reason, but still.
A consequence of having easter eggs is that it can encourage players to hunt for more on there own, which can clash with the immersion or intended experience of the mod. Although this is an example with is more likely to have bigger consequences for the player, there are more benign easter eggs/secrets or ways to do them.

Of course, now players should get 3 chances to nickname Monika so long as they apologize, but at which point you still lose the ability permanently. You also now lose A LOT more affection, as in at least 30% of your total, for giving a bad name. Adding some kind of name input field to indicate if a name is bad or not before you submit it has been proposed which I think is a great idea.
