### ISSUE TITLE
Vampire Monika

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4406]
Hey there!! My name is Briar. I've been playing your mod every day for a week, now, hah! (Just unlocked Monika with her hair down, YES!)
  ANYWHOO

  Since day 1, I noticed that you were having people draw outfits for Monika :0 I'm an artist myself, but I doubt I could do an outfit that would look enough like the art style for this game qwq
HOWEVER
What I can do, though, is that I can give Monika's expressions fangs and red eyes! ^w^ 

Is this open?

**Comment by kkrosie123** [comment]
![face-eyes-crazy-red](https://user-images.githubusercontent.com/52429850/60751435-391b8c80-9f69-11e9-80f4-7d866af42d5e.png)
![face-mouth-big-fangs](https://user-images.githubusercontent.com/52429850/60751486-88ae8800-9f6a-11e9-9feb-b1cf0dbfe7bf.png)

ALSO HERE IS AN EXAMPLE OF BOTH UWU

The fangs are a little rushed - I don't have access to my usual editing tools at the moment, but I will tomorrow and I can provide a better example uwu

**Comment by Chrissenpai** [comment]
Hi, there @kkrosie123 , I'm one of the people that made an outfit for Monika, there will soon be coding for an outfit I made.
I'm the most experienced artist here on the extent of what I know of the contributors of the community until now. I'm not here too often, just checking once in a while because I have my own life to maintain. There is someone that commissions my service for MAS which I'm very grateful. With that said, you can tell me your art wishlist and in due time there will be a new creation or polished art no matter how big or small.

PS: I'll have more time next week because of college summer break, then I'll only work instead of work and study

**Comment by kkrosie123** [comment]
I see! Thank you for telling me! ^w^

**Comment by kkrosie123** [comment]
Hec I need to reference the issue

#3174 

So ayye

I'm working on this uwu

**Comment by ThePotatoGuy** [comment]
seeing that fangs would be like an accessory, I'm not too sure of how this can be used. Not to mention the amount of overhaul needed to make acs vary between facial expressions. Can't say this will be used, but we'll look into it

**Comment by kkrosie123** [comment]
Closing until a feature like this is looked into further. :)
