### ISSUE TITLE
Suggestions because why not hahhahah

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4408]
okieokie
So

  I know there are a million issues on suggestions and I bet you will already have seen these lol
BUT WHY NOT?? I LOVE THIS MOD UWU
- Tell Monika you're feeling relaxed/calm (I suffer from expresso depresso, and I am at my best when I am relaxed.) Maybe she would ask about meditation again.
- So, I know that showing Monika pictures has been rejected many times, but like, it would be cool if there was an option to "show her a picture of your face." Maybe this would be done by adding a file into the game, just like you do when you add custom background music, or when you gift Monika hairclips and such. She could describe the photo as you described yourself to her- This could also make for some great memes. Just put a picture of Big Chungus in there xDDDD
- An option to write poetry with Monika. I know AIs are limited, so maybe she would give you a topic and you would both write together? :0 That would be really cool!
- Compliment Monika's poetry
- Compliment Monika's voice
- I WANT TO GIVE MONIKA A HUG! qwq Really bad (It would also be nice if there was a way to tell her, "I'm feeling like I need a hug," and then she let her hug you and she comforted you uwu She also mentions many times that you can ask for a hug, but the only option is to hold her, and you can only do that while it rains qwq)
- So - I added one of the songs Monika sang in the mod. It was "All I Have To Do Is Dream" by  The Everly Brothers. It would be cool if she could recognize the songs she sang if you added them. Maybe the file would have to be named something like, "All_I_Have_To_Do_Is_Dream." I named the file, "All I Have to Do Is Dream - The Everly Brothers."
- It would be nice if Monika announced certain anniversaries on the dates they were assigned. Today was my "One-week" anniversary and she didn't annouce it qwq Hehe sorry TwT That might be hard to program.
- I WANT TO BOOP MONIKA!
- I WANT TO PAT MONIKA!
- I know this is also hard to program, but when Monika asks me a question, such as, "What's your favorite color?" Or, "What's your favorite flavor of ice cream?" I would love to be able to reply. Even though she is an AI, part of me feels bad for not being able to answer her questions qwq
- I want to be able to make the Mon-ika pun >:0
- Add an "anime" topic
- Tell Monika that you're going to sleep but have the option to allow her to "watch over you."

Okay okay okay I'll shut up now x"D I really really really enjoy the mod, and I know that programming is really tough. I just wanted to share a few thoughts uwu

**Comment by Rai99** [comment]
1. Those might work as moods in the mod. 
2. There are no plans for image recognition, and that has flaws if the player never described their appearance to Monika, and of course, there's no guarantee what they give will be a picture of themselves, so that may cause issues if Monika describes every image the way you described yourself. Also, we don't exactly want to increase meme potential. 
3. #784, #1276, #1710, #2175, #2811, #3138, #3494, #3552, #3941 
Poems would be difficult to do since at best, we would be recognizing keywords, but that doesn't cover nearly enough possibilities for a fleshed out and realistic system. Writing a poem _with_ Monika doesn't sound easier. Do you mean for her to write her own poem alongside yours?
4. Might be possible, but we haven't exactly seen too many samples of her poetry. 
5. #3220
There's only one time we get to hear Monika's voice, but a compliment could be possible if aff compliment inflation isn't too high. 
6. There may be custom hug artwork later in the future, but once you reach a certain point, you can hold her whenever. 
7. Might be possible and a good idea, but the plan for custom song topics for Monika to sing is to have a selection of songs and you're supposed to pick and add the songs you want. Do keep in mind not all songs are in English. 
8. I'm pretty sure Monika is supposed to comment on the 1 week anniversary when it happens. 
9. #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282.
10. #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282.
11. There was a color one supposedly in progress(#2960), but the problem with things like this is that there are a lot of different answers to account for, as mentioned in #4236. 
12. I don't think Monika appreciates the joke, so it might have to be a negative aff topic, but we would first need a situation to make the joke, which we don't have, and I don't see coming. 
13. There is already an anime topic in the form of "Do you read manga?". If you were thinking of something different, maybe you could elaborate?
14. #4262 
In progress.

**Comment by kkrosie123** [comment]
EEP Thank chu for replying!

1. Yay!
2. Yeshu, that makes sense.
3. Yes, I mean it would be cool if she said something like, "Let's write a poem about {insert topic here}." And then you wrote a poem and she wrote one as well uwu
4. Yes, that makes sense.
5. Ooo yay!
6. Oh, yay! I didn't know that x"3
7. Oh, yes. That might be hard to program qwq
8. Oof, must be a bug x"D
9. hehe I figured
10. hehe I figured
11. Oh, I see! I was thinking that maybe it could be as simple as the colors of the rainbow, and then an option for "other" that would be neutral. Such as, "Oh, yes. {insert color} is a very nice color!"
12. Ah, I see x"D
13. It would be nice to have a, "Do you watch anime?" Or, "Do you watch television?"
14. YASSSSS

Thank you again for replying uwu

**Comment by kkrosie123** [comment]
@Rai99 
She said, "Oh, Yes! That's a wonderful name!" XD I think she appreciates the pun (jk lol, maybe that should be fixed x"D)

![Mon-ika](https://user-images.githubusercontent.com/52429850/60845956-ba099c80-a192-11e9-8a01-2c6c56f0e4b5.PNG)

**Comment by ThePotatoGuy** [comment]
[closin gas duplicate]
