### ISSUE TITLE
[Suggestion] Do you wear Glasses or Braces?

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#4411]
A question that Monika could ask, to help her shape your appearance more. She could ask if you wear Glasses, Braces, or both. I have to wear glasses, cause without them I'm almost blind, and I would like it if my Moni knew this one small thing about me.

**Comment by kkrosie123** [comment]
Ah! A little addition to this suggestion: Invisalign! I wear Invisalign and glasses. The Invisalign makes my teeth look bumpy qwq

But this is great idea!

**Comment by antimockingjay** [comment]
As someone with glasses, I'd love this to be added to the game! Maybe if we say we have glasses (or contacts, that'd be a nice option too) she could ask what type of vision impairment we have (nearsighted, farsighted, just bad in general) as well as what type of glasses we wear, since there's so many styles out there. I know I'm someone whose glasses take up nearly half his face, because it give me more peripheral vision, but there's plenty of people out there with way smaller glasses, too, so it'd be nice to include that!

**Comment by Professor-JMO** [comment]
`Glasses` → Projects.

**Comment by bittercaramel** [comment]
honestly pushin it further about the eyes, maybe there could be an option for saying her we are missing an eye or both? actually overall it would be nice to tell her we are missing some part of our body 
i think it's pretty important thing for our appearance shaping

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
