### ISSUE TITLE
[Question + Possible Suggestion] Deemo

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#4423]
Heyo everybody, how is your summer going? I am steaming over here, its unbearable!
While I was chilling in my room with the fan on I was playing the game "Deemo" on my ipad and I thought to myself that Monika would really enjoy it.

What you guys think? Do you think that Monika would like a game like Deemo? Since especially there is some really good music in it and its supposed to make you feel like you are playing the piano. As well as emotional story hidden in it. I am excited to hear your opinions.

Now to the suggestion part. I don't know how much the mod is allowed to delve into other games. As in how much can a game be mentioned by name or gameplay but if it is possible, maybe Moni can talk about Deemo and give her own opinion about it? Hopefully this thread might help finding out creating a script for it (I have no idea to be honest). If that is not possible its fine!

Have a nice day everyone!

**Comment by multimokia** [comment]
Would help to know what Deemo is

**Comment by kkrosie123** [comment]
Are you talking about this..? https://en.wikipedia.org/wiki/Deemo

**Comment by multimokia** [comment]
Regarding delving into other games, it's a little out of character for Monika to go into those topics, since Monika herself says she doesn't really play games. If she knew some games (other than her own, of course) Then it'd probably have to be the games which pretty much made history, like the first Mario game or something. Otherwise she probably wouldn't really know any other games.

**Comment by AfroFluff** [comment]
> Would help to know what Deemo is

Yeah sorry about that. Deemo is a mobile music rhythm game, where you can pick different songs that are piano based and choose a difficulty. There are bars that come from the screen down and you must click on them in time when they reach the line at the bottom of the screen. As @kkrosie123 shown there is also a psvita version and as well as a Switch version now. But as you mentioned it probably would be out of character if she would go deep into games when she rarely plays some. I thought this was a good, lets say, exception cause it is piano based.

**Comment by kkrosie123** [comment]
The description of this game sort of reminds me of Piano Tiles. I play that game, and it has really improved my hand-eye coordination. I don't think a game like that would suit Monika, however. I think she would prefer to play the real piano. :)

**Comment by ThePotatoGuy** [comment]
since this would be a niche topic, it is recommend to make one yourself so we have a feel for what you'd expect monika to say. See [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) for instructions on how to dothis.

Otherwise, closing this until we look into it
