### ISSUE TITLE
[suggestion] "im feeling hungry" improvement

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#4449]
Sometimes when you say "I'm feeling hungry" Monika responds "Hi Hungry, I'm Monika" and nothing else.

**Comment by multimokia** [comment]
Shouldn't it be `"Hi feeling hungry, I'm Monika.`"?

**Comment by Rai99** [comment]
Yeah, somebody should fix that. Thanks for bringing that up.

**Comment by Rai99** [comment]
Wait, I read this wrong. I thought you meant this was already in and you thought it was a bug. 

As an actual suggestion, I'm not actually too sure, since it sounds a bit out of character to me. I don't see Monika making that kind of dad joke, especially if it's not an easter egg that requires a specific setup. 

Maybe if the player names themselves "feeling hungry", it could work.

**Comment by ThePotatoGuy** [comment]
yeah I'm not sure of the setup. seems kind of out of nowhere for her to make the joke. 

[closing until we look into it]
