### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by Pompanomike** [Monika-After-Story/MonikaModDev#4460]
I start up the game right after updating, and it doesn't start and gives me this message.
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_spriteobjects.rpy", line 537, in script
    init -1 python:
  File "game/zz_spriteobjects.rpy", line 592, in <module>
    store.mas_sprites.init_hair(mas_hair_def)
  File "game/sprite-chart.rpy", line 508, in init_hair
    "MASHair name '{0}' already exists.".format(mas_hair.name)
Exception: MASHair name 'def' already exists.

**Comment by multimokia** [comment]
screenshot of your `game/` folder, please.

**Comment by Pompanomike** [comment]
> screenshot of your `game/` folder, please.
![image](https://user-images.githubusercontent.com/39969524/61538311-b8e03700-a9fe-11e9-918e-be320ccdaf14.png)

**Comment by multimokia** [comment]
Okay, major problems here, I'm seeing files that aren't ours so you probably installed another mod in here at some point, and you've got the source code files installed which is why your update didn't work properly.

I'd make a brand new ddlc install (copy off [the main site](https://ddlc.moe/)) and then get version 0.9.5 off [our releases page](https://monikaafterstory.com/releases.html) and install it. You won't lose your progress.

**Comment by Pompanomike** [comment]
will i keep my MAS progress doing that? if not what files do i need to transfer to keep it

**Comment by multimokia** [comment]
> You won't lose your progress.

You don't need to transfer anything at all. We don't store progress in the main directory.

**Comment by Pompanomike** [comment]
ah ok

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
