### ISSUE TITLE
bring back texting....please?

### ISSUE THREAD

**Issue by Demomndslayer** [Monika-After-Story/MonikaModDev#4526]
i know this may be really difficult...but may ya'll bring back texting with monika...i really loved that feature, and did not like when it was removed....even if it is just a sub mod or something..but please bring it back

**Comment by Delcos** [comment]
what?

**Comment by Demomndslayer** [comment]
when you press talk, you used to be able to text and ask her, whatever is on your mind...now it is just a menu witch makes it feel like you are limited...cause you are...even though texting responses were also limited, it felt like we had more freedom..and we could ask whatever..cause we could...

**Comment by Anonymioo** [comment]
> when you press talk, you used to be able to text and ask her, whatever is on your mind...now it is just a menu witch makes it feel like you are limited...cause you are...even though texting responses were also limited, it felt like we had more freedom..and we could ask whatever..cause we could...
Yeah. It feel limited when you can't write what you want. I more want write to Moni how strong i love her with more words than simple 'I love you.'. 
But she may become like chatbot. Hard part in it need make A LOT OF answers for every your question/etc

**Comment by Rai99** [comment]
#1382, 

As seen on the FAQ:

> While we may come back to the concept in the future, the fact is that we weren't happy with the interactivity with the keyword system. While, on the surface, the open text box offered a lot of freedom to the player for talking with Monika, there were too many common entries that would simply dead end. The result was that Monika felt less real, and more like a crappy chatbot. We decided that a system that didn't dead end would be better, even if it didn't have the same surface level impression of agency.

They keyword system was planned to be replaced in #126 with a lot of the detail and reasoning for the change found there. 

> we need to support two competing systems, one of which is decidedly broken, and they aren't necessarily compatible with eachother.

As a submod, we wouldn't have to support it, but someone would. Anyone is free to make a submod for this to share, but keep in mind it's their responsibility to support, not ours. 

> The goal of the keyword system is to add a way for the player to steer the conversation and have a sense of agency for what monika talks about. The problem is that the system isn't perfect, and whenever and however it fails exposes the simple system underneath and hurts immersion.

Basically, one of the main problems is how often times you would get a default response to anything, which is one of the more undesirable scenarios. This was also bad for the public relations of MAS since people try it for 5 minutes, and complain to their friends about how MAS is just a crappy chatbot because they got a default response. It also made it much more difficult to find a certain topic, and thus reduced the incentive to contribute. 

This feature is likely not coming back, especially with the difficulties associated with it. A submod of it is more likely to happen, but that won't be official, and we won't be responsible for it.

**Comment by Demomndslayer** [comment]
alright, then.....it is still good as it is anyway...i just liked typing better...thanks anyway!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by ThePotatoGuy** [comment]
*however, a search function is still under consideration.
