### ISSUE TITLE
[Suggestion] - Megane/study

### ISSUE THREAD

**Issue by Irres** [Monika-After-Story/MonikaModDev#4528]
I think that it will be a great idea to have a reading time, There should be an option like
in the menu I'm feeling ... Like studying/Reading, and she will read her own book, (with glasses as an option) and maybe make glimpse/ look back at you for a few secs each x minutes. Kind of a study buddy.

**Comment by Rai99** [comment]
#1598 

Or, it could be expanded beyond a brb/idle style topic: #2311, #3896 

A reading/study mode had been brought up before, but we would need art of her reading. I think glasses should come from acs beforehand if the player chooses to have that, and not specifically for reading, since Monika probably doesn't need reading glasses.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
