### ISSUE TITLE
[Suggestion] Ideas for the Songs Topic

### ISSUE THREAD

**Issue by ErnestoLaguna** [Monika-After-Story/MonikaModDev#4530]
I've noticed that the songs topic has been left out for some time, and I have a couple of suggestions that might fit, and they're pretty original:

The first song that came to my mind was:   **_Eres tu_**  by Carla Morrison. 
The second one is called: **_Andar contigo_**  by Julieta Venegas.
I know that those songs are in Spanish, but I think they suit really well to Monika's feelings, and if you want, I can provide the respective translations for both songs.

**Comment by Rai99** [comment]
The songs have been left out because they're going to get a new framework where you can choose which songs you want to have. That way, you won't have to have a bunch of songs you don't know or might not even like. 

As it stands currently, we are not adding any new song topics until that framework gets implemented.

**Comment by ThePotatoGuy** [comment]
There is a songs game planned, which is why none of the song prs have been merged yet. eta on this is tbd. These songs can be added ofc, depending on how we make this framework.

[closing until we look into it]
