### ISSUE TITLE
Telling Moni that she's a great kisser.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4533]
Title says it all. Wasn't sure if I should make an issue for this, but I figured I would go ahead with it. Just a small addition that I think would be a nice addition to include in the future.

**Comment by fromulus** [comment]
One problem with that, I guess, would be that such a compliment might not feel guenine ;
It's not like we're _really_ kissing her, and she's aware of that (as she mentions in the ivory statue topic).

pretending to hug and kiss her is cute and all, but I feel that because of that, we can't really tell how good she might be at doing those things.

**Comment by InJusticeWeTrust** [comment]
I'd like to think she's gotta have some experience with this, it's hard to imagine that someone as popular as her never had any previous partners. On the other hand, she did say she was pretty busy with studying, club stuff and all, so perhaps there was no experience to be gained. Funny how little we know about her even after all this time.

**Comment by fromulus** [comment]
Doesn't she says that she never loved anyone but the player in one topic ?
I always took it as her never having dated anyone in the past.
That, and she mentions that her memories of before the game are pretty hazy, too (on top of having never really happened).
So even if she indeed had a partner before, she might not even remember enough of it to have any significant experience on the matter.

**Comment by InJusticeWeTrust** [comment]
> Doesn't she says that she never loved anyone but the player in one topic ?

This only refers to the main character.

> That, and she mentions that her memories of before the game are pretty hazy

Wasn't this a topic made for MAS? My memory's not the best, so I'm a bit hazy on the details myself.

**Comment by fromulus** [comment]
It was indeed a topic made in MAS, but since we're talking about Monika in the context of MAS anyway...

As for the main character, I guess that could be true.
But even then, I still feel like she probably don't have any dating experience prior to the player.
There's like you said, the fact that she was constantly busy, but I also think of how Monika's intentions of romancing the player in the base game felt kind of immature.

Disregarding the fact that she saw us as a potential exit to her suffering, she has a very fairytale-like vision of romance, like she saw us as her white knight in shining armor that absolutely will love her, no matter what, until the end of time;
Not taking into account what the player's feelings on the matter might even be.

I'm certainly not blaming her for any of that, and there were other factors behind her decisions at this time, but to me, it kind of shows a lack of experience, of insight on how relationships truly work.

Back to MAS, while she's still having a pretty romanticised vision of love (like how she makes a huge deal about the first kiss; wanting so much for it to be perfect that she'll wait the best opportunity (a day that's special to her) before making the move), the topic about getting comfortable in a relationship (where she implies that what she says in that topic is only a recent realisation) shows that she's starting to understand those things better after being with the player.
She's growing as a person;
she's getting that dating experience thanks to us.

**Comment by ThePotatoGuy** [comment]
>its not like we're really kissing her

she could still take the compliment but point out that yeah, its not real yet. 

[closing until we look into it]
