### ISSUE TITLE
Monika gives her player a nickname.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4535]
She only refers to her player as their requested name. A pen name isn't really the same as a nickname, so I was thinking what if we could ask her to call us something as a nickname, and she refers to her player at certain times, or depending on the dialogue she's saying?

**Comment by MetalBrother** [comment]
Also, it can depend on affection level. I think that a great idea.

**Comment by Rai99** [comment]
#1941, #2216, #3008, #3068. 

It's been brought up before, and decided that we probably don't need to track more player names.

**Comment by Trilasent** [comment]
> 
> 
> #1941, #2216, #3008, #3068.
> 
> It's been brought up before, and decided that we probably don't need to track more player names.

Tracking one more name doesn't seem that difficult. It could end up being one of those "small comforts that only a partner can have" that she talks about sometimes, which could make the relationship between her and her player more intimate and personal since that nickname is only something that that version of Monika and her player would have, unlike nicknames we give her which can be the same as what others choose to refer to theirs as.

**Comment by Rai99** [comment]
#2216 stated by TPG: 
> i think having one selected name is fine and we dont need to track additional names atm.
> 
> maybe we'll add an audit log but probably not going to happen.

> unlike nicknames we give her which can be the same as what others choose to refer to theirs as.

I think this problem still exists, since most of the nicknames I've seen are a generic lovey dovey term. This could still happen the other way around too. 

If we implemented player nicknames, where would use use them? There should be a place for both the regular name, and the nickname, where appropriate, and I personally don't see too much merit in having both and balancing them between topics. 

Personally, I would think that you could just ask Monika to call you something else if you wanted a nickname.
