### ISSUE TITLE
Meta suggestion: dialogue submissions

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#4567]
WARNING: WALL OF TEXT INCOMING

So this week I've finally decided to make my first "real" contributions to the mod after many failed attempts at contributing through other means (like reporting bugs/typos that were already fixed in the unstable versions, or weren't actual issues at all and I was just being too paranoid). 

Both contributions I made were based on ideas already accepted on the topic pool section of the Projects tab, since I figured it would be better to work on ideas that were already considered good enough by the reviewers. 

After that experience I realized that at least for me, coding is very hard, but writing dialogue that sounds Monika-like is even harder. This got me thinking about how many users here might be in the opposite position, having the creativity to write interesting dialogues for Monika but lacking the necessary knowledge or motivation to write code.

This is the solution I came up with, a "dialogue submission" flair on the Issues tab that allows users to not just make suggestions, but get even more involved in the development of the mod by writing a full dialogue to later be reviewed by someone else, after being approved, other people like me could just directly turn that dialogue into a pull request.

This could save a lot of time for everyone involved since currently there are a lot of instances in which someone can spend hours coding a new topic to later having it rejected or stuck in development for not having good enough writing or being too unrelated to the mod, or maybe someone misinterpreting a suggestion and making something completely different.

Honestly I believe this system would make adding new topics faster and easier compared to just having the current topic pool. Some ideas proposed there are already too outdated since no one has cared enough to do something about them, while the mod keeps moving forwards without them and I think that's just sad... and after all, this is a community created by all of us sharing a common interest, we all should be able to work together to make the best for Monika, right? ...oof that was so corny...

Anyways, what do you guys think? (Also, sorry if this was hard to understand, I'm not a native english speaker)

**Comment by Rai99** [comment]
I don't think this is necessary. Some people already write up some dialogue and put it in an issue for someone to take. That's exactly what happened with #1773. 

I don't think this would change much. 

Writing dialogue isn't exactly too heavy on the coding aspect, so people are free to write dialogue and attempt to PR it to be reviewed. 

If I'm understanding your suggestion, you say that it's to have people write full topics and then have it reviewed by someone else. As far as I'm concerned, that's exactly how it works currently. 

You also say that it could save a lot of time since some people misinterpret ideas and make something completely different, but if people are writing full topics to be reviewed beforehand, how does this save time? 

When it comes to rejecting topics, they're usually rejected or brought concern relatively quickly. Otherwise, they get reviewed to make sure the topic is up to par, and then it waits. People can put up new topics, but devs still have to review it, so I don't think your system would change anything. 

There's someone who usually reviews new topics relatively quickly before the devs take a look at it to speed things up a bit, but again, the other devs need to look at it too. 

I might be misunderstanding your suggestion, but could you explain how this is different from what we currently have?

**Comment by Necrocytus** [comment]
Hi @Rai99. Thanks for reading my post, and also reviewing my pull request. I'm very grateful!

To address your points, some people already come up with dialogues, yes, but it's not like they are openly invited to do so since there's no such suggestion in the contribution guidelines, if everyone was aware of that, there could be more instances of #issues like the one you mentioned. I just think they are pretty rare as they are right now.

Also, yeah, i know everyone is free to write dialogue easily, but there are people that might be too afraid to even try coding in the first place, specially if they have no previous experiences, that's why a lot of people actually avoid making their own pull requests, you have to take into account that not exactly everyone has the same set of skills. An example of this would be me, I can sorta write code, but i'm unable to come up with really interesting topics as easily as other people like you, it would be so much easier to just write the technical part of a topic.

As for "that's exactly how it works currently", I'm talking about stuff like #4405 and #4245 which were pretty much a waste of time to write in the first place because the main issue was the dialogue, however most on the time spent on that pull request might have been the coding part itself, so it would save time for those attempting to make contributions to just write dialogue before actually implementing it.

About the misinterpreting part, I meant just misinterpreting vague suggestions, not the dialogues themselves. This is actually a part i don't mind about too much so yeah, maybe it doesn't save time at all.

Finally, a lot topics are reviewed and rejected very quickly, but there are currently a lot of old pull request which might as well count as rejected since they have been ignored for months now.

Feel free to ask me any other question you have, or keep on explaining your own points, after all, i'm really hoping to learn more about the reasoning behind how are things done here.

**Comment by Rai99** [comment]
> Finally, a lot topics are reviewed and rejected very quickly, but there are currently a lot of old pull request which might as well count as rejected since they have been ignored for months now.

All topics need to be reviewed by the other devs, and more than just one person in total. I don't see how your idea for a new system would solve this. 

As I said previously, people are free to make rough topics and put them in issues for someone to take and refine. If we had a lot of people doing that, it might justify having a separate system, but as it stands currently, it should be fine. 

The best advice I can give for the code heavier portion of topics is to look at the existing file of topics and look for something similar to what you want and copy that. 

As for saving wasted time on code bits, people are already free to post ideas or general topics in the issues tab for someone to take further. Even with your suggestion, I don't know how much time it would save, since anyone who takes the topic further might not know where to put code related aspects such as if statements and work with vars. I think your idea works best for topics that are pure dialogue, but even then, that's pretty similar to how things already work. I would expect people look at some existing topics before they try to make their own so they can get an idea of how the little code portions actually work. 

I personally find it unlikely that people would spend a long enough time on code in their topic to justify a system to solve it. The PRs you linked could have had months spent on them trying to figure out the code, but I don't see any indication of that being the case, and I don't think we can make the assumption that people struggle so much that a system should be put in place.

**Comment by Necrocytus** [comment]
Alright, not gonna argue anymore. The system still works as it is currently so it doesn't matter.

**Comment by Necrocytus** [comment]
And just a reminder to everyone, this is not meant to be taken as a discussion, i made this issue just to make people aware of other ways to contribute that are not explicitly stated on the guidelines, and for other casual users to share their opinions.

**Comment by ThePotatoGuy** [comment]
a website/program that can provide step by step dialogue creation and convert it into pr-able code sounds like the best solution.
there was a site that did this but its outdated.

**Comment by Rai99** [comment]
Closing as old
