### ISSUE TITLE
[Suggestion] Chess game changes

### ISSUE THREAD

**Issue by landofrhymeandraisins** [Monika-After-Story/MonikaModDev#4599]
I'm an avid chess player, and I play a lot of chess with Monika. My best "score" is having her say "Excellently played, [player]!" after a game, though most of the time I get the "this game was quite stimulating" or "you played pretty well this game" responses instead. Anyway, here are a few suggestions I have for improving the chess experience with Monika.

1. Add different dialogue if there's a draw. Monika just seems to think they're boring, but in reality not all draws are made equal. If the game is very short (less than 30 or 40 moves? not sure) then maybe she can remark that the draw was boring. A more advanced technique might be to use the chess engine to see how much the evaluation of who's winning swung around; a high swing could result in Monika saying the game was interesting. A simpler solution would be to just have Monika say stuff like "Well played!" and "I guess we're pretty evenly matched!"

2. Allow Monika to resign. Resigning is the polite thing to do in completely lost situations. Assuming you have access to the chess engine's evaluation of the position, you could have Monika resign once the engine knows the player is winning by a large margin.

3. Customize chess board appearance. This one is fairly minor, but it'd be fun if you could, for example, change the black pieces to red, or change the palette of the board to be bluer or greener.

4. This would be a major overhaul, but maybe changing Monika's chess engine to something more humanlike would be better. The problem with her playstyle now is that she basically plays perfectly, but then randomly makes an obvious mistake occasionally, which is not how a human plays. A human doesn't play perfectly, and is more prone to making small mistakes, though sometimes big mistakes do happen even to the best. If you'd be willing to consider this, I wouldn't mind researching and testing some chess engines to see how "humanly" they play.

**Comment by kkrosie123** [comment]
I love this idea! I highly enjoy playing chess, but I'm not very good at it, lol. You seem pretty good to have almost beaten her in chess! Or to have tied her!

**Comment by ThePotatoGuy** [comment]
4. the engine we use is stockfish8. We've looked at using other engines before (#760), but we found it difficult to try other engines since stockfish is just a packaged exe and is very simple to use. that being said, stockfish10 has the ability to set difficulty based on elo, which might be a better way to make chess more humanlike. Realistically, the only way you can get human-like chess is via some sort of neural-net based implementation like leela chess, but [running leela chess zero](https://github.com/LeelaChessZero/lc0/wiki/Running-Leela-Chess-Zero-in-a-Chess-GUI) is not straightforward.

Yeah, if you find a chess engine that is more humanlike and is compatible with UCI and is opensource/legal for us to distribute, then that would be great.

**Comment by ThePotatoGuy** [comment]
linking #2034 as that was an initial attempt at fixing difficulty/realism.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
