### ISSUE TITLE
About the new art

### ISSUE THREAD

**Issue by LClarance** [Monika-After-Story/MonikaModDev#4620]
First of all, I want to clarify that I am not here to start an argument and that I just want you guys to know about my opinions for this new update, I know that the devs of this mod are working hard to create free contents for Monika and always hearing out people's opinions and I am very grateful for this. 

Now lets get into the main topic. I just wanna point out a problem with the new fixed art. Her arm/hand/palm or whatever you call it looks chubby of her leaning pose in this new update to me or maybe its always been like this I just didn't notice it but I visit Monika very often so minor details like this might "irritate" my eyes a little. Please correct me if I am wrong about this.

![Monika](https://user-images.githubusercontent.com/47456818/64489110-cfc63b80-d281-11e9-9edd-2e95ec83e8a4.PNG)

Second, this is not really a big problem but I just wanna say IMHO her new wrinkles looks very thicccc its like she's another anime character lol.

![Monika 2](https://user-images.githubusercontent.com/47456818/64489111-cfc63b80-d281-11e9-823f-0fcf879c17b5.PNG)

Other than that, the new update is very cool and I like it very much but I gonna be very honest here so my words might hurt a little, every time she got her art updated, I am worried that she would look more like a Disney princess(Disney's Artsyle), so whatever you guys do, please don't stray too far from the artsyle of the original game is my wish. 

Lastly, thank you guys for looking at my opinions.

**Comment by lxnavarro23** [comment]
Whoa! I didn’t even notice that wrist! It does look a little weird. 

But ya I love the new update. It makes me look forward to what the future has in store...or at least, I hope so

**Comment by kkrosie123** [comment]
Haha! I know you said it looked a little weird on Discord, but I never got a chance to see it! Yes, I agree, the wrist should be a bit curvier.

**Comment by Starryknight007** [comment]
I kinda agree she's starting to look more and more Disney Princess-ish.

Also it looks like no amount of artstyle revamping can keep her left eye from clipping over her hair.

**Comment by Orcaramelo** [comment]
> I kinda agree she's starting to look more and more Disney Princess-ish.
> 
> Also it looks like no amount of artstyle revamping can keep her left eye from clipping over her hair.

it was intentional to keep it tho "please don't stray too far from the artsyle of the original game is my wish." this is what we go by

**Comment by Starryknight007** [comment]
So it's straying too far to fix a clipping error but not to make her look like a Disney Princess?

**Comment by Orcaramelo** [comment]
> So it's straying too far to fix a clipping error but not to make her look like a Disney Princess?

what do you mean by disney princess tho
her eye coloring is just repainted Act 3 eyes
all her new face features are just act 3 but repainted for better quality, not even positioning has changed is 99% of repainted stuff

**Comment by LClarance** [comment]
I think by Disney Princess, I mean her new coloring. Compared to Japanese animes, Western cartoons always have brighter color some to the point you can feel like its illuminating while Japanese animes tend to have a more balanced/darker/plain(not sure how to descibe it properly lol) coloring. Just compare the new art and the original Monika by Team Salvato and I think you will find the difference somehow. 

There is another thing that is bothering me that I forgot to point out. Its that her left arm in Blazer feels bigger too. 
![monika](https://user-images.githubusercontent.com/47456818/64510413-bb7f4e80-d314-11e9-9823-c4e8f036c348.PNG)

Again, sorry for complaining and I don't do art so I cant describe some of the situation properly.

**Comment by LClarance** [comment]
First of all, I do not understand why there's a need of going offensive. My statement might be a little impolite, I apologize on that but I was merely encouraging LordBaaa about making a submod just in case something I worried would happen, I mean everyone needs motivation to do something right?

Second, @multimokia and @jmwall24 might be mistaking me with someone else as all I asked for Monika's arm and wrist to be fixed not her eyes(I already thanked Orcalamelo in the other thread made by another guy), I did talk about her eyes but that is not the main topic of my post and I can still accept the coloring of her new eyes so please read again. 

Thirdly, I do not understand why jmwall got so triggered when someone else have different opinion? You got triggered in Chrissenpai's thread too. Sure I dont pay you anything but why use words like "accuse" and "vocal minority" to describe me when all I did was just giving my opinions and I didn't even force you guys lol? If you don't like me giving opinion in GitHub then I apologize for not speaking up in discord and I will get it next week. Also, may I suggest instead of always fixing something that is not broken(her sprite) why don't you guys go with things like new room features(example: tic tac toe that were planned) or fixing the pixelated area of the island?

Finally, @ThePotatoGuy  well you are not entirely wrong about me mixing my own preference when speaking but I am only bothered by Monika's thicc arms of her new leaning pose because her other sprites and official arts aren't that thicc. 

That's all I wanna say and I am sorry for being rude on this one, I hope we are cool now since Monika's birthday is coming soon, I don't really want to set the mood for the coming week. Hope we can have good discussion in discord soon after her birthday. See you guys there

**Comment by LClarance** [comment]
And thank you @Velius94 and @ThePotatoGuy for issuing the fix.

**Comment by ThePotatoGuy** [comment]
> Also, may I suggest instead of always fixing something that is not broken(her sprite) why don't you guys go with things like new room features(example: tic tac toe that were planned) or fixing the pixelated area of the island?

The pre 0.10.0 sprite system was terrible in its current state for handling the vast number of outfits planned. The past 2 months were spent re-thinking how this system could be improved to avoid an issue where a change to a base sprite would require changes to everything. During this period, the artists decided to redo parts of the base, which was a great time to do so since the system was changing anyway. In their task to redo, they solicited feedback from the community discord and we ran polls, and the general consensus was that the changes looked better. 

The rest of team each had something to do (dark mode/bg swapping framework/making gifts selectable/better generic gift responses/updated split-base sprite system). In almost every update, the majority of changes are framework, updating systems to be better prepared for a time when no one is working on the mod anymore. And we can't do that by focusing on only new features and writing a bad codebase in the process.

**Comment by LClarance** [comment]
@ThePotatoGuy thanks for filling me in on these, I appreciate the things you guys have done for us its just sometimes I feel like talking about my own thoughts so sorry about that.

**Comment by LordBaaa** [comment]
@LClarance I had mentioned my preference of the older/original sprites as well as not feeling quite right about the new eyes in discord and well like I said here I plan to make a sub-mod that addresses it for myself and anyone else who would like to download it. I am aware that I am in the minority of users who prefer the older eyes but that is what I prefer. 

@ThePotatoGuy If could make a suggestion, why not just make her new/old expressions as a sprite pack? Could even make each aspect (eyes, mouth, eyebrows) separate bit in the sprite pack. That is what I plan to do in my sub-mod is allow the user to mix and match between the new/old styles. And yes I know its more coding, mainly because I am working on that coding right now. But at the most basic all you **need** is this is a simple override like this. 
``` 
init -4 python in mas_sprites:
 F_T_MAIN = F_T_MAIN + "0.9/" # Folder name for alternative expression version
```
No hard current code changing, just existing stuff modified or stuff added non destructively.
All you'd need after that is the night time mode 0.9 sprites which I am currently exporting and would be more then happy to provide when I am finished. Anyway point is, it really wouldn't be hard to continue to support the original eyes as well as the new. Personally I believe supporting the original expressions as default would be the best because it preservers Monika's original style for new and old users and allows users to change it if they want or if Monika suggests it. Could even put both versions in and have Monika say like she had a new version of her sprite and if you missed the older version she could go back for you. Basically same as any other sprite pack, you get to choose the new outfits/hair/acs you want. The Pink Shirt is not in the official game so why take her eyes that have been used for almost 2 years and change with no option to go back, yah know? Seems unreasonable.
I personally don't like being forced to use new, well anything much less expressions. I'd much rather be given the choice to `opt-out`. I do like your new expressions as they are well done and I'm sure it took a lot of time and effort to make them. But in the context of Monika, her original art style and my interest in maintaining the original style I prefer the old/original 0.9 sprites. 

On a final note the new system is looking awesome! I had wanted to be able to split the arms for quite a while but hadn't gotten around to making an option for it. I was digging around in mas_drawmonika looking to update some of my personal mods and saw the split code.

**Comment by multimokia** [comment]
> Monika say like she had a new version of her sprite and if you missed the older version she could go back for you. 

That has got to be the most immersion breaking bit of dialogue I've ever read.
When does anyone ask anyone, let alone their girlfriend `"Can you change your mouth?"`, `"Can you change your nose?"`, `"Can you change your eyes?"`

Spritepacks are different because they're *articles of clothing*. And clothing is meant to be changed.

Overall, it's too much work and too many things to render out/ship (heavily bloating up the mod size) to have the old sprites on the side. If you want to make a submod, that's cool. But we will not be doing this officially.

Again, the majority of people like the new assets, it's a very, very, very small amount of people who wish to go back, it's just not worth supporting officially.

**Comment by ThePotatoGuy** [comment]
> mix/match styles

I am not opposed to making this configurable. However, there are lots of nuances to consider with doing this, as explained below.

> why not just make her new/old expressions a sprite pack

> support the original eyes as well as the new

All of these things become problems if we decide to add new facial expressions. Therefore this would have to be custom spritepacks (aka we will not release them with the main spritepacks) because they would need to be updated by someone who would want to make "classic" versions of any new expression.

> night time mode 0.9

Spritepacks would then need to have an export with your (or whoever's) custom night filter. Maybe we could only load spritepacks that have a compatible filter. Regardless, being willing to apply your night filter to everyones spritepacks everytime a spritepack is released (and getting permission from the spritepack creator to do so, as well), is a significant amount of work that we don't want to encourage by making it possible to do so.

> Seems unreasonable

There was one user who colored Monika sprites in their ideal artstyle, and to install this you would replace existing sprites, which is basically submod territory. Style mix/matching, core sprite changing would easily be handled via submods rather than spritepacks. As multi mentioned, spritepacks are like giftable DLCs that simplify adding new content, not replacing existing content.

**Comment by LordBaaa** [comment]
@multimokia  
`heavily bloating up the mod size`
the 0.9 folder size is only 2.29 MB

@ThePotatoGuy (Excuse me cause I dont know the formatting for the reply style you guys use)

`they would need to be updated by someone who would want to make "classic" versions of any new expression.`
Well firstly in these sprite packs I suggest they would need a `.rpy` file or to just to override variables/functions so yes that is a bit more submod territory. But I would be up for this for the classic mode. I am not an artist but I do commissions with @Chrissenpai so we could help a bit for new "classic" stuff. But even without that, when `_ms_face` is called you can check the variable of the bits that go though it to `_ms_eyes, _ms_eyebrows` etc. All you'd need to do is put a basic if statement.
if the the name of the expression bit we are dealing with is in the list of expressions that exist then send the expression bit variable to the function. else send a default expression bit. Like if new eyes existed in 0.10 sprites but not in 0.9 it would simply use another 0.9 sprite as a replacement.

`Spritepacks would then need to have an export with your (or whoever's) custom night filter.`
I dont understand  this one. Why would you need to export everyones pack if its just expressions? Do you mean if other ppl made expression packs? And if that is the case, I simply meant that the stuff you have now you release and maintain that (possibly with out help), not for everyone to realease them, though of course they could 

```There was one user who colored Monika sprites in their ideal artstyle, and to install this you would replace existing sprites, which is basically submod territory.```
```As multi mentioned, spritepacks are like giftable DLCs that simplify adding new content, not replacing existing content.```

I do agree that submods are an easy way to deal with this, and if that is the case maybe just link the submod as an official download or at least mention the possibility. I will say that with what I am proposing for the submod/spritepack it would not be designed to change replace content. Simply override it, aka if you deleted the one rpy file it would go away. 

Finally I must say I really appreciate you actually considering what I said.

**Comment by LordBaaa** [comment]
oh and @multimokia Yes I agree that is immersive breaking but that its just an example. Just to clarify idea is if you were a sprite pack is that you simply extract it and then it would be changed. You wouldn't have to be in the game and break immersion. And besides at least you'd know it would change. Having her whole face change on a reload after an update with no warning especially if you hadn't read MAS releases page or had been in the discord (aka used auto-updater) is also quite immersive breaking isn't it? Suddenly she is just different.

**Comment by ThePotatoGuy** [comment]
> I don't understand this one

I'm talking about your thing about 0.9 night filter. Thats a filter applied to a sprite, then exported. It's not a layer over everything. Trying to make night filters configurable means an entire set of images for that night filter. Then add spritepacks to that mix and now you have a enormous amount of image exports to do. Which I guess if you have all the time in the world, you can do it, but that's not something we're going to do.

> submods are an easy way to deal with this

Yes, and that's the way we're going forward with your suggestions. Facial expressions/base sprites/base clothing/base hair are core sprites and replacing core sprites is a submod, even if its adding swappable core sprites. Spritepack clothes/hair/acs do not fit in this category because they do not replace core sprites.

> basic if statement

Each branch incurs a penalty in rendering, and with performance at an all time low, we're not going to add more if statements in the sprite system. We're already putting a focus on removing/replacing the legacy outfits (witch/neko) as they cause an extra if statement in `_ms_sitting`.

**Comment by LordBaaa** [comment]
`I'm talking about your thing about 0.9 night filter. ` 

I am talking about use 0.10 night time filter for 0.9 sprites. I wouldn't mind 0.9 night time as well but atm I am talking about using 0.10 night time.

`Yes, and that's the way we're going forward with your suggestions. `

So are you saying you be interested in supporting a sub-mod I make for this purpose if it has up to date expressions (any new ones added in 0.10 converted to 0.9) so it doesn't need an if statement? Or am I reading to much into that?

**Comment by ThePotatoGuy** [comment]
we'll link it in the submods general but thats it.

**Comment by LordBaaa** [comment]
Okay well thanks for at least hearing me out.

**Comment by jmwall24** [comment]
@LClarance just so you know, I was not addressing you with my comments. I was addressing the comments about the eyes, and since that's not what your main concern was, it wasn't about you. Your suggestion about the hand/wrist was spot on and has been fixed.

If I seem a little `triggered` it's because this is not just confined to this thread. It's been in other threads here and on discord. We are very busy working on other important stuff for the mod and it's my preference to not have to keep addressing this matter. 

Also, not sure how using the phrase 'vocal minority' means I'm triggered. It's the truth. You always hear from the people who don't like something more than people that do. Just the way it goes. I just tend not to like it when the few people who don't like something automatically think they are correct in everything they say and that everyone should bend to their will. 

As for my comments in the chrissenpai thread, there's a good reason for it that I won't get into here, but if you've read some past threads you'd understand.

That aside, as I and others have said in a few places, these changes were not a quick process. We were very public in our changes and encouraged and received lots of feedback. We made many changes along the way due to this feedback, so it's kind of frustrating to have all this come out after release, especially when all of these changes were available in our unstable update a week before release. I highly encourage anyone who wants to have their opinions on the mod heard to join our discord server and ask for access to unstable.

I also feel that a lot of this with the eyes and facial expressions is just a knee-jerk reaction of 'change = bad.'  If people actually put aside their preconceived notions and actually look at what was done by our wonderful artists, they'll see just how much improvement has been made. The improvement in the quality of the art in this update is incredible.

**Comment by LordBaaa** [comment]
` join our discord server and ask for access to unstable.`
@jmwall24 so to be clear is there a hidden unstable chat?
Cause I was unaware of this. Had I know I would have asked for it much sooner. I though you guys only meant unstable build not channel as well. I just read the member roles and I see it. I believe in the past I read the rules but I don't recall reading the staff-and-rolls cause well honeslty I was though to myself well I'm not staff so ye doesn't help me. Well if that is the case I would have spoken up in that before hand so I am very sorry about that for this sort of thing coming out after the fact. However hopefully from my position of really not even knowing that exists it until you said something you can also understand why I am reacting the way I did. And once again I want to reiterate I do think your new expressions have a lot more quality. I just feel that the style is off not the quality. If for example the new green hue wasn't so bright and kept more of the original color that would be good in my opinion.

**Comment by LClarance** [comment]
> Also, not sure how using the phrase 'vocal minority' means I'm triggered
@jmwall24 you know kind of people are commonly described by these right? 
But let's forget bout this for now. No offense, but there are many video games that still have bugs even after going through strict alpha and beta testing despite being handled by top tier developers in the video games industry so I think it's quite normal for people to point out mistakes after a patch has been released. Btw, as you can see, the discord server isn't really efficient and sometimes I wonder what are they doing when more than 300 people voted but nobody noticed her swollen wrist and it was the same with Monika's second leaning pose(forgot which version but its the pose before this one till it got fixed when people brought it up in GitHub), I didn't expect things like this will happen again. Nevertheless, thank you guys for the hard work.

> would be more then happy to provide when I am finished
@LordBaaa thank you for this too

**Comment by multimokia** [comment]
>  you know kind of people are commonly described by these right?

Commonly described or not, it's a fact given the poll results and given how many people say they love the new art vs the old and how few people are complaining.

> Btw, as you can see, the discord server isn't really efficient 

Actually it's more efficient than GitHub since more people visit there vs here. Not to mention that more people understand how to use discord over github.

>  I wonder what are they doing when more than 300 people voted but nobody noticed her swollen wrist

Actually, there was a session in #artistry where one of the artists was getting feedback directly for the leaning arms and working with people in the channel in real time getting feedback and incorporating it.

> it was the same with Monika's second leaning pose(forgot which version but its the pose before this one till it got fixed when people brought it up in GitHub)

Actually, what we did here was better than that. The leaning before this iteration wasn't even polled aside from the community artists and devs. This set of changes was completely made open with polls after each round of changes to see what people liked. It was actually a very involved process with the community.

> I didn't expect things like this will happen again.

They didn't, see above point.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
leaning is changing again because of popular vote

**Comment by LClarance** [comment]
@ThePotatoGuy may I know where to find the poll? I missed it lol. Just want to have a look and Im a newbie on discord so it still looks messy for me

**Comment by LClarance** [comment]
@LordBaaa oic. Thanks for the info. Its not really their fault, Im kinda busy recently so I dont check discord often. Havent install the mobile app
