### ISSUE TITLE
[Suggestion] Anime + Monika = Fun

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4684]
I've seen suggestions from Monika watching anime with us, but I also read that it would be complicated. This can take away the excitement, but why don't they make this easier? We tell Monika "Let's see some anime" and that a series of options that show the anime that we will see will be shown on the screen, for example: "The Seven Deadly Sins" and that Monika asks us what chapter, for example: "Chapter 1 "And when we finish the chapter, we click on the screen and let Monika give us her opinion. It comes out much easier than detecting search engine pages. Also if you can give more detail, that is how the hug we give Monika, if we do not click the screen, she can fall asleep, and if we click in a few minutes she will tell us that it was fine, that it be the same with the anime, if We clicked the screen before the duration of the episode, that Monika tells us why we put a pause, and if we do it after the duration, that he gives us his opinion about what he saw, how I said it takes away the emotion, but it is better than nothing. Thank you for reading :)

**Comment by Rai99** [comment]
How many anime series would we have to account for if we list them all, provide separate options for each chapter/episode, know the duration of said episode and have unique dialogue about each episode, _and_ for coming back before the duration is up? 

That still sounds like a whole lot, possibly more than what was originally intended. Also, if I recall, the idea of the feature was cancelled entirely because it would be far too much.

**Comment by RavenPLAYER** [comment]
@Rai99 I had no idea it was canceled.

I wish I could help... i would happily take the time to do that, alone if is necessary, but I still couldn't, anyway, since the only series I've seen anime is "The Seven Deadly Sins". Anyway, thanks.

**Comment by Rai99** [comment]
You say something about a list of anime to pick from, which would already be just about impossible to do, since there's so many already and we probably wouldn't be able to release content for new anime soon enough to really be relevant. 

Adding a list of episodes to each anime with unique dialogue would also be much, much more work, especially with pause dialogue in the middle. 

It's nice that you're willing, but remember what Monika says about starting small.

**Comment by RavenPLAYER** [comment]
I can't argue anything about that logic. 
Haha, you make me see how an idiot xd

**Comment by RavenPLAYER** [comment]
@Rai99 Another thing they could do is put a list of the 5 most famous anime, like "Dragoon Ball", "Naruto", "The Seven Deadly Sins" And so on, and not put everything at once, for example, as I only know The Seven Deadly Sins will only give examples with him: Put the first season first, and later (much later, like weeks or a month, I guess) they put the other season, the same with the others. And it is not necessary to do it at the same time at all, but I see that they have to deal with other things, but this is another option after all. I know it sounds unfair to people who haven't seen those anime, but what are the chances of it? (Now that I realize, it's quite unfair, but I just said). Thanks again for reading.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]

This would be like the movies module, where we would leave it open for people to add their contributions via a framework or something. And so I think it would end up like the movies module, where no one wants to add to it so it just doesn't help anybody.
