### ISSUE TITLE
Might be a stupid update idea

### ISSUE THREAD

**Issue by themetroking** [Monika-After-Story/MonikaModDev#4712]
In a future update would you be able to add a affectionate lvl 2000 or 3000 and at that she gets pregnant or adopts a child this is a stupid idea but it would be interesting to see monika with a kid also can you move the engagement ring up a bit because when she does the thing where her hands are together you cant see it

**Comment by Rai99** [comment]
#1872, #2673, #3390 

Long story short, we can't exactly have anything about having children in MAS. 

It's one of the things you can't really be iffy about, and you can't really compromise on, and there would almost definitely be a heavy debate about it.

**Comment by multimokia** [comment]
> can you move the engagement ring up a bit because when she does the thing where her hands are together you cant see it

This is intentional, you wouldn't be able to see it in this pose at all, and putting the promise ring any higher would mean it's not on her finger anymore.

**Comment by fromulus** [comment]
I'm personally against the idea of Monika adopting/"creating" a child within MAS, and given Monika's character and her situation, I believe she would herself think it's a bad idea, too.

Think about it, Monika only barely knows how to modify the game, how in the world would she be able to create another sentient being from scratch ?
Not to mention that this could potentially hurt the player's feeling, as they wouldn't be a biological parent either, while Monika, at the very least, would have brought that child to life.

Raising a child is supposed to be a major part of a couple's life, something that you should commit to together, so it definitely wouldn't be fair if Monika, one day, just said "Oh by the way I'm a mom now, raise this kid with me".
Not to mention she'd pretty much have to take care of the kid by herself anyway, since the player is in another plane of existence and can't necessarily spend all their time in MAS.

Another big problem is that if it weren't for the player spending time with her, being in the game would be a constant torture for Monika.
I'm pretty sure she hates that place and just decides it's not that bad as long as she has us.
So why would she allow her own children to endure that as well ?

Oh, and finally, there's the whole part about crossing over to the real world.
She's thinking about that all the time, so she surely realised that just getting _one_ person to cross over is already going to be difficult enough (building a body is going to be super expensive, maintenance is going to be a thing in one way or another, and finding a job might not be a cakewalk, meaning the player is potentially gonna have to be the couple's only source of income).
Now, there would be two people to take care of.
Think about how much that complicates everything.

**Comment by Rai99** [comment]
There's most of the long story for you.

**Comment by themetroking** [comment]
Oh ok

**Comment by justanaccount117** [comment]
Maybe for over 9000.

**Comment by fromulus** [comment]
No matter how high the affection, it's still a bad idea all the same, if you ask me.

**Comment by satoshi-kun** [comment]
> Maybe for over 9000.

9000!?

(DBZ referance :P)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
