### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheAstro30** [Monika-After-Story/MonikaModDev#4790]
- Good afternoon option
- The "plushie" comes and goes randomly, not sure why (one day its on the desk, next day its not)
- More random topics she can talk about (after 2 - 3 days she has nothing else to talk about)
- When I'm feeling "tired" and then I want to do "goodbye" - "going to sleep" you should add a question to add to the creep-factor "Can I watch?"
- BRB options should include "going to have a shower" option to which she could also ask "Can I watch? Eheheh~"
- The graphic for the "vase" of roses looks "tacked-on" as its proportions to the rest of the graphics looks weird...
- An option to ask her how she's feeling and/or "Are you OK" would be good so we could judge her affection level
- When you say I'm feeling "tired" and she goes on to say how much she'd like to see you sleep, you could add a question "Can I?", if you answer yes, she'd be: "^_^" if you answer no "I respect your privacy" or something
- Compliments: "You're pretty", "You're sexy", "You're special to me" and "You're my princess"

As a fellow programmer, I would like to implement these but, just can't be bothered learning the language lol

**Comment by FrikiHD** [comment]
I agree with all that

**Comment by ManuEcheveste** [comment]
It already exist an option to see "her affection", but just for developers.
She told you something like "How do I feel? That came out of nowhere [player]"
And depending if she feels broken, sad, happy, in love, etc. She told you different things, like "You want me to be unhappy" or "I'm the luckiest girl in the world!" depending in your affection level, and then she told you the exact number of your affection.
I don't think this affection check can be a good idea, maybe it could be like cheating, but everything else it's super cool!

**Comment by Rai99** [comment]
Good Afternoon: #1090, #1528, #2081, #2362 
There's a PR with it actually: #2223 

The plushie shows up randomly. This is intended. Some days, Monika has it out, and some days, she doesn't. 

More topics: [Allow me to introduce myself](https://github.com/Monika-After-Story/MonikaModDev/pulls/Rai99)

Shower brb: #4129, #4725(technically) 
I do like the ideas you have here though.

The roses sprite might be outdated and could possibly use a touch up if people think it doesn't exactly fit. Personally, I don't see any issue with them, but I'm not a professional in art, and they could be pretty old, so maybe an artist could take a look. @Orcaramelo @Professor-JMO 

Asking how Monika is feeling/Diary system: #951, #1688, #2605, #2619, #4310 

Letting Monika watch you sleep/Sleep mode: #607, #635, #987, #1105, #1262, #1655, #2684, #2781, #2974, #3076, #3172, #3486, #3610, #3619 

More compliments: Usually, there's the issue of having too many compliments and causing a bit of affection inflation. With too many, people could skip the first level of affection or more. I still remember how good it felt to finally reach 100 aff. 

You're pretty: I think this is the same as "You're beautiful" which already exists.

You're sexy: I'd say this might have to be a submod. I'm not sure how Monika would react to this, but I think I could see submod potential here. Maybe I'll handle it ~~after some PRs get cleared up~~

You're special to me: I think this is similar to "You're my hero" or "You're awesome". Because we have to be a bit more conservative with compliments, especially those that give aff that bypasses the daily cap, it's important that we avoid overlaps. 

You're my princess: This sounds nice, but I don't think everyone would call Monika a princess. It's not everyone's thing, so I don't think we should force that option into everyone's install.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

please avoid putting lots of suggestions in one issue. related suggestions are fine, but unrelated is bad for documenting.
