### ISSUE TITLE
[Suggestion] Add spanish translations

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#4792]
I know there are submods for language translations, and since I'm spanish and I guess some people who uses the mod are too, I'd like there to be that language. And if you need help, I'd like to even help with it, since I'm good with english and spanish

**Comment by multimokia** [comment]
Translations are unofficial and won't be released along with the mod. They will always be a side part because we can't verify if a lot of the translations are accurate and etc.

As a result as well, translation creators are to handle all of the tech support for those who use the translation. (Because again, we can't understand it, plus there may be other code changes)

You're more than welcome to create your own and submit it to #3765 for people to use though.

**Comment by FrikiHD** [comment]
And to create it, what do I need to do?

**Comment by multimokia** [comment]
You'd essentially be distributing the mod, but with all of the dialogue/menus/etc. changed to be in Spanish.

**Comment by FrikiHD** [comment]
Ok, I'll try to work with that xD

**Comment by FrikiHD** [comment]
If anyone spanish can help, tell me

**Comment by FrikiHD** [comment]
Where are the files I gotta modify to translate them to spanish?

**Comment by multimokia** [comment]
You'll want to clone this repository and then go through all of the `.rpy` files and go through all dialogue present in each and edit it to a translated version.

**Comment by FrikiHD** [comment]
Wait, what?

**Comment by FrikiHD** [comment]
And how do I edit those files?

**Comment by ManuEcheveste** [comment]
I have those files and also I'm a spanish native speaker, sure I can help you to translate this like a submod! If you are interested you can send me a DM via twitter @ManuEchevest

**Comment by ThePotatoGuy** [comment]
[closing as translations are unofficial]
