### ISSUE TITLE
[Suggestion] Take Monika somewhere in the game

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4822]
As in the title, it would be great if there was an option like "Let's go somewhere..." and that Monika gives you some options to choose, such as "Park" and that when selected, that Monika make the fund be the selected place and have a good time together. I think I saw this somewhere, but I don't remember where... anyway, thanks for reading :)

**Comment by Rai99** [comment]
New Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023 

We would need art, and unfortunately, fitting art isn't easy to come by. Someday, it might happen though.

**Comment by Mcmanybucks** [comment]
> 
> 
> New Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023
> 
> We would need art, and unfortunately, fitting art isn't easy to come by. Someday, it might happen though.

What about the locations already in the game? like the street, the classroom, etc.

**Comment by RavenPLAYER** [comment]
![forest](https://user-images.githubusercontent.com/55263957/66084776-d3c64000-e545-11e9-915f-949ce5dadd8a.png)

And those that already exist? I think it would be necessary to ask for rights and stuff, right?

**Comment by RavenPLAYER** [comment]
![Monikapaseo7](https://user-images.githubusercontent.com/55263957/66084851-007a5780-e546-11e9-9d35-0d6c20440cd4.jpg)
And this...

**Comment by RavenPLAYER** [comment]
![PaseoY](https://user-images.githubusercontent.com/55263957/66084878-15ef8180-e546-11e9-8718-97a1c946b635.jpg)
And... this

**Comment by RavenPLAYER** [comment]
![mcama](https://user-images.githubusercontent.com/55263957/66084915-2c95d880-e546-11e9-9739-d016a5aa8a27.png)
And this ( ͡° ͜ʖ ͡°)

**Comment by multimokia** [comment]
1. If these aren't royalty free, no we can't use it.
2. Need day/night assets at minimum
3. Good luck getting a desk scenario working in this
4. Outdoor ones will probably need alt weather variants

**Comment by RavenPLAYER** [comment]
@Mcmanybucks I think that walking alone on the street would not be so special, but it would not stop being with Monika, and that would make it special, but walking with beautiful landscapes would be much more indicated and romantic for the situation

**Comment by RavenPLAYER** [comment]
@multimokia I don't mean sitting there with her, I mean a real walk, I upload a photo in a few minutes ...

**Comment by RavenPLAYER** [comment]
![screenshot0001](https://user-images.githubusercontent.com/55263957/66085607-18eb7180-e548-11e9-806a-6d07f3534de5.png)
Here is

**Comment by RavenPLAYER** [comment]
@multimokia This is the real idea

**Comment by multimokia** [comment]
So, we don't really have any intent on bringing back standing sprites.

Why?

1. Outfits, hair, and accessories. This would end up resetting outfits and hair every time we took her out because she'd be in her uniform. This is already decently annoying because of the constant need to reset clothes back to what you had every time you return. Standing sprites were also such a niche use that having our artists make these is pretty much worthless.

2. Blinking wouldn't happen anymore as eye positions don't line up properly. (Hence why its disabled during opendoor greet)

3. Existing sprite system (due to blinking) modified things such that 70% of sprites don't exist in the standing variant, and figuring out which ones do exist is a pain. (And they only pretty much do because of the opendoor greet)

4. Standing sprites aren't *nearly* as expressive as what we have now. There's only a small amount of combinations.

**Comment by RavenPLAYER** [comment]
Hmmm... well, maybe someday it will be possible

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
