### ISSUE TITLE
Hair Strand Color adjustment/fix.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4839]
In game it's fairly noticeable that Monika's left hair strand (her left) changes color around the mid section:

![acc67ddd80fae76bf1de4de4bb68730c](https://user-images.githubusercontent.com/36512990/66277488-cb7f4500-e864-11e9-9550-a07b581be376.png)

Here's a comparison between the adjustment I've been trying to make and the current version/how it looks in game:

Current: 
![tweak off](https://user-images.githubusercontent.com/36512990/66277500-08e3d280-e865-11e9-95c8-68ed8709fe6d.png)

Adjustment:
![tweak on](https://user-images.githubusercontent.com/36512990/66277507-1e58fc80-e865-11e9-9b5a-628a49db6524.png)

**Comment by ThePotatoGuy** [comment]
couple of things:
1. the difference in color is incredibly minuscule, I dont think most people notice it
2. a change like this would require the hair spritepack to be retrofitted with the changes as well as rexported, neither of which is something I want to do or have the spritepack artist do because of point 1.
3. I'm done with changing base sprites. thats basically most of what I've been doing since january and I'd like to write code + dialogue again.

**Comment by Trilasent** [comment]
> the difference in color is incredibly minuscule, I don't think most people notice it
Well you can't really know what most people think unless you ask them, right?

> a change like this would require the hair spritepack to be retrofitted with the changes as well as rexported, neither of which is something I want to do or have the spritepack artist do because of point 1.

It's literally one change that I or the creator of the spritepack can do themselves, we can make our own night time versions since the filter comes in the base psd, so all you're doing is replacing the file in the mod itself.
> I'm done with changing base sprites. thats basically most of what I've been doing since january and I'd like to write code + dialogue again.
Again, you're doing nothing more than replacing the file while the artists do the  work making the day/night versions, and resizing them to work with the resolution you have set for the mod.

**Comment by ThePotatoGuy** [comment]
>others without the problem would be able to see it more easily

If that was the case, then someone else with better visual acuity would have brought this up sooner.
These hair strands have been out for several months now.

>can do themselves

well not quite since someone has to verify that the images look fine, have no artifacts and are exported with the correct interpolation settings. And since these are base images, they have to be added to the base psd.

You're free to submod these if you'd like.

**Comment by Trilasent** [comment]
> If that was the case, then someone else with better visual acuity would have brought this up sooner.
These hair strands have been out for several months now.

The majority of MAS users most likely don't even have a GitHub account to comment on problems they notice, or have Discord/access to the MAS Discord server, so they'd just have to put up with it for all we know. If more than 100k people have downloaded MAS, then certainly a good portion of them aren't on the MAS Discord server.

>well not quite since someone has to verify that the images look fine, have no artifacts and are exported with the correct interpolation settings. And since these are base images, they have to be added to the base psd.

> I don't see this as much of a problem that can't be resolved with a simple addition to the **PSD section** of the art guidelines here: https://github.com/Monika-After-Story/MonikaModDev/issues/3174. Giving more specific requirements for how the images should be exported could only reduce the amount of work you yourself have to do.

**Comment by ThePotatoGuy** [comment]
I already do mention the export steps, but there's no reason to just blindly accept that people will export the sprites correctly. Everything has to be reviewed, especially if its something that would be added to the base psds.

**Comment by Trilasent** [comment]
> 
> 
> I already do mention the export steps, but there's no reason to just blindly accept that people will export the sprites correctly. Everything has to be reviewed, especially if its something that would be added to the base psds.

Okay, so what does this reviewing process involve? Also you already mentioned the exact specifications for exporting art properly?

**Comment by ThePotatoGuy** [comment]
>reviewing process involve

I mentioned checking artifacts, there's also ensuring the sprites fit in the correct render order, and general quality review. Base sprites get reviewed with more scrutiny, I look for transparency holes, linework issues, color issues, and more.

>mentioned the exact specifictations

go to the psd issue and scroll down past the revision history.

>reduce amount of work

While yes it would save me work by just letting others export the sprites and putting them in, I want to ensure the sprites being added to base/spritepacks (and effectively being promoted by us) are of good quality.



Finally, to reiterate, the primary reason why I'm not looking to add these changes is because dev team and I have agreed that the proposed changes are unnecessary and not needed. We don't see an issue with the current hair strands.

**Comment by ThePotatoGuy** [comment]
if you want to submod this, make a new issue.
