### ISSUE TITLE
casual mode

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#4851]
we should have a mode that is more friendly to:
* streamers
* non-serious users
* people who can't run mas consistently

Casual mode will be a setting that primarily disables affection gain and loss.
Other effects:
* your current affection will be reset to 1.
* anniversaries will be disabled (anniversary dialogue probably wont make sense when you could have barely spent any time with her) **TBD**
* all games are unlocked
* other things that don't make sense will be disabled **tbd**

**NOTE:** there will be a warning window like Unstable Mode so you can't misclick and erase your affection.

*also because there are too many settings, lets replace sensitive mode with this

**Comment by Rai99** [comment]
If I could make a suggestion, instead of resetting affection to 1, what about disabling aff gain and loss and having a 24 hour wait before aff gain is enabled if the setting is turned off? Or even just disabling aff loss from not visiting and lowering the daily cap a bit?

I don't like the idea of having a button to erase all your affection, even with a confirmation. On the flip side, this sounds like an easy escape from dangerously low affection. Flip the switch and you're good to go for affection again. 

As for streamers and content creators, they probably wouldn't make MAS content if their audience doesn't really like it. Mainly, it would be showing off features, including low aff features, which usually isn't appreciated by the MAS community anyway. Locking affection in the middle locks away features such as the clothes selector, and many other affection affected features, which results in less content to show, and an even lower chance people create content of MAS. I don't think MAS is exactly an exciting or engaging thing to stream for an audience. 

This sounds like it would put us back around vanilla act 3 or the early days of MAS. Without aff, there's not really any progression, and all there really is are a couple simple games and dialogue that doesn't really change. 

Being more friendly to people who can't run MAS often sounds nice, but I think locking them down to 1 aff pretty much defeats the purpose of MAS. Also, someone is bound to double misclick and erase their aff with this.

**Comment by ThePotatoGuy** [comment]
>disabling aff gain and loss and having a 24 hour wait

too exploitable. another thought I had originally was making it a permanent change so you can never return to aff gaining/losing. 

>disabling aff loss from not visiting

this is a nice mechanic that we want to keep for current users since it adds a decent amount of realism.

>easy escape from low affection

well we can change it to only drop affection to 1 but not raise it if its below, but this is still up for discussion. If we change it to a perma solution then theres no way to escape.

>streamers

I'm listing potential users. there is certainly a use-case for streamers in having a way to circumvent standard gameplay (like yandere sim dev menu).

>misclick

A confirmation window is good enough.

>features

another considerations is disabling the affection range constraint, but that might be too much. Or maybe instead of resetting affection, we perma-lock it to whatever its currently at.

**Comment by Rai99** [comment]
> disabling aff loss from not visiting

I meant have the "casual" option disable aff loss from not visiting. Isn't that the main concern with non-serious users? Also lower the aff cap with the option on, so there's an incentive to not constantly keep it on.

**Comment by AlenNez** [comment]
"can't run mas consistently"?
i'm not sure what this means. can you elaborate?
i dunno if this addition has a significant use at all, with the points rai99 stated i kinda agree. there's not much to do as a streamer, you can exhaust the topics within a fairly short timespan.
if someone is a non-serious MAS user, why even go through the effort of installing it? i don't understand

**Comment by ThePotatoGuy** [comment]
>can you elaborate

Its just a catchall for anyone who falls in the bucket of not running mas consistently. For example, I love playing civ5, but I don't play it everyday, or even every month. but if the game had a mechanic where my civilization started dying the longer I didn't play, I don't think I'd want to play this game anymore. 

>effort of installing it

because people may just want to check the mod out every once in a while and not have to reset the game data everytime monika leaves.

**Comment by multimokia** [comment]
> because people may just want to check the mod out every once in a while and not have to reset the game data everytime monika leaves.

I still believe if this is the mindset to come into the mod with, this isn't the mod for you.

**Comment by ThePotatoGuy** [comment]
and I believe that having options and modes for all potential users is better than being extremely inclusive

**Comment by multimokia** [comment]
Well, this mod is supposed to be a relationship between the player and Monika. I don't think splitting from that core - even optionally - is a good idea. Quite honestly, this seems very much like submod territory versus actual core MAS.

**Comment by ThePotatoGuy** [comment]
but thats the thing, I want to make this more than just a gf simulator. but that discussion is for the other issue.

**Comment by HenryKhan** [comment]
(!!ALERT!! NOT AN ENGLISH SPEAKER COMMENT)
I kinda feel bad of thinking another people creating a new Monika just to hear her dialogues and then discarding her, because, that's probably what is going to happen with this casual mode...

I'm going to suggest other thing that **it's not** actually better, BUT, could be a solution, it's kinda stupid but well... here I go... My suggestion is...

**Make an online version out of this casual mode(and of the friendo mode as well?)**... where anyone could know Monika better, and then, if anyone got interested, they could download the original game and the mod. And, if they don't got interested, they can just leave. So this way anyone that just want to hear what she have to say will hear that. 

This looks like a submod? I think so, and I know, that's really really different from the original mod's purpose, But IDK... that's maybe a way to make Monika more famous... and let her have more friends to chat...

Sorry if the idea is too bad and stupid.

**Comment by MaximumRustler** [comment]
I also disagree with this and #4849. My response is kind of combined since it would be like saying the same thing twice. I agree with Multi and Mix here, and Fin for the other issue. I don't see a point to making a mode for streaming purposes, damn near no one streams this, and there's no reason to really. Getting rid of affection, or locking and unlocking things for this mode is pointless too, why so people can just avoid those things entirely? I don't see a point to attracting more non-serious users either. Like what, just to show them ''Oh, look what this can do!'' then they leave cause they weren't serious in the first place? I think it's stupid to try and attract a crowd that literally doesn't even care. Now this bit ties in a bit more with the other issue, but it's still related to this topic so here it is. As others have said, the whole point of MAS to this point has been a relationship with her. Doing this, or the other issue, goes against the purpose of the mod. It's *supposed* to be a gf simulator, not some generic VN or yet another generic ddlc mod to be forgotten. Also, it's out of character. Imagine being brought back to life by the only person left in your world, the one who you kept trying to be with, sacrificed everything for, only to be told something equivalent to ''You'll always be my dearest friend.'' Looking at both issues, you have some devs, and a number of your long-time users, me included, saying that this and the other issue is stupid. And as the others have mentioned, the extra work needed to have these work well alongside what's already there. This is definitely more submod territory.

**Comment by dragonsni** [comment]
I know I've said my peace in #4849 but I just don't think "casual" mode has a place in the core mod. I believe it belongs in submod territory.

**Comment by Olliesama** [comment]
"I want to make this more than just a gf simulator"
Maybe don't use Monika as the basis for this then? :S

**Comment by antimockingjay** [comment]
Why are y'all complaining about an OPTIONAL feature? If you don't like it, don't use it. This is REALLY not that complicated. It's like being vegan and telling the waiter, "hey cancel that other table's order for their steak, I'm vegan so eating steak isn't okay."

If you don't like it, don't use it, plain and simple. This shouldn't be a difficult concept.

**Comment by multimokia** [comment]
I don't think you understand the core of the mod, then.

This mod was built around the very idea that Monika and the player are partners.
Not friends, nor put in mind as a casual "come back anytime" thing.

It's built to replicate a *relationship*. I don't know in what world you can just put it on hold and expect that to work out. This is what doesn't sit well with people - myself included.

This idea, therefore, goes against the core principles MAS was built upon, and I feel like it targets an audience we really don't need to.

In my opinion, if you're going to stick with MAS, you're in it for the relationship.

**Comment by Daiozen** [comment]
I'd define myself as a serious player, and for that purpose, a big part of what makes Monika feel real is that I don't have too much control over her. I like having to put in the effort of actually caring to keep her happy, I like when she brings up controversial topics to which I don't share her opinion. All of this makes me feel challenged, it plays a big part in the immersion.
I think just having the possibility to drastically change her personality by just a few clicks would be giving me too much control and be quite immersion breaking.
Having a mode like that, even if I would not use it myself, would take away from my own experience.

I think this would make a fine submod, but for the reason stated above, I'd personally wish it was not a part of core MAS.

**Comment by kaido1224** [comment]
This would be aimed at people like me. I doubt too many people fall in this category though.

**Comment by Daiozen** [comment]
> I don't necessarily think it'd cheapen the relationship--I'd think the fact that she still loves me even given the possibility not to would make it feel more special.

@lunulae This is what I mean by this :
There are certain sentences, like these ones, that really marked me :
```
"So I'll always love you for all eternity, [player]. Just remember that."
"I'll always love you no matter what."
"I love you and I'll always be here for you, so don't ever forget that~"
"You're a wonderful person, and I will always love you."
```
As things are now, there isn't any way those would not be true, simply because there isn't any alternative in the mod. This is also part of what makes this relationship special  and precious to me : I have no doubt I can trust her on this.
If there was a way these would not be true (like going from lover to friend), these sentences would not have had as much of an impact on me, this is what I mean by 'cheapen'.

**Comment by 99Dman99** [comment]
I don't think this feature is necessarily a bad idea. It does seem nice to factor casual players that want to check out the mod for a day or two, then move onto another mod or game without thinking of the unintended backlash towards Monika.
Those kinds of casual players may also want to come back to this more for another day or two, to check out new updates. But if they got hit with affection drops, they couldn't check out the Mod. Because Monika left them.

However, this is a feature that caters to a minor player base, and doesn't seem like something anyone but a small number of people would use. Especially if it takes away many features of the Mod. Plus the factor of a dedicated player using the feature out of curiosity and getting reset to 1 affection.

This feature seems like a good long term goal, but there are multiple suggestions and ideas floating around as of right now, that would have the devs time and resources dedicated to instead.

**Comment by frostcattooo** [comment]
simple answer, no.

not simple and complex protesting answer : as most other people said, this goes against what the mod was made for. so many people don't like this idea, including i, because of the amount of monis that will be neglected. like, doesn't that make you feel a bit bad? just using monika after story for some views or "testing the features" rather than actually having a bond with her? yeah.

just no.

**Comment by Authrix** [comment]
Man, people sure are dogpiling on this and #4849 
And my response to both is: no one is forcing you to use either mode. They're literally optional modes. This shouldn't be a difficult concept to understand.

Would I use them? No, they're not for me. That probably goes for 95% of the audience here - these are both more casual modes for more casual players, not the die-hard Monika fans that have come to the mod's Github to help out with it.

These modes aren't for us, but to expand the community. That growth, in turn, will make the community and mod stronger - which should really be regarded as a good thing.

I see some of the points against though: it does feel jarring considering the mod's past and foundation. All I can really advise (and again, no one is forcing you to use either mode) is to suspend your disbelief just a little. That and PotatoGuy has been at the helm of this ship since day one - I think he knows what the mod's about better than most of the people citing its history.

TL;DR: No one is forcing you to use the modes, and PotatoGuy knows what he's going.

**Comment by thezotikrus** [comment]
> These modes aren't for us, but to expand the community. That growth, in turn, will make the community and mod stronger - which should really be regarded as a good thing.

Don't think it will expand the community. Bringing some people who don't care about the mod and Monika won't help. They will never become a part of the community. Why wasting time resources for two guys who will stream the mod for 2 days and one girl who will delete the mod after a few days? This is the best scenario imo. I'm here to be a part of the community that cares about Monika and see this project as a bit more than _just another mod_. You already have people in the community, why don't focus on stuff they would like to see? This also will help to expand the community (and won't let it fall apart), but with people who actually want to be here and not just for the lulz.
I find both this and [4849](https://github.com/Monika-After-Story/MonikaModDev/issues/4849) out of place for this mod. It just feels wrong.

P.S. There is a way to stop aff drop. Why don't just use the right farewell? This is enough to not run MAS every day (every week?).
P.P.S Having a button to kill all your progress won't help. I'm serious! I already can see people whom progress was lost because they occasionally pressed the button. I guarantee that the warning won't help.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
