### ISSUE TITLE
Hangman Suggestion

### ISSUE THREAD

**Issue by PaperPlate1** [Monika-After-Story/MonikaModDev#4859]
While playing hangman with Monika, I came across the word "Ubuntu". Having had no idea what that was, I looked it up and read a little bit about the Linux distributor. But it got me thinking: It'd be kind of neat if after a word is revealed (whether successfully guessed or not), you could click on it to open a short dialogue with Monika about it.

Lot's of word puzzle games on mobile apps have this feature, where after guessing or unscrambling a word, you can tap on it to read its definition. This could be similar, but with a little more Monika flair. She could relate different words to DDLC, or the player's relationship with her, or to other general topics, etc. It'd definitely make the experience of playing round after round of hangman with Monika a little more interesting.

Now, this is coming from someone with absolutely no coding background, so I'm definitely not trying to be that guy imposing his idea on the people who actually put in the work to make this mod as content rich as it already is. I'm curious to know the difficulty behind pulling something like this off. I realize there are a LOT of words this would have to be applied to. I have friends who are into coding, so I can empathize with how tedious the process can be.

I'd love to get your opinions on this. Whether it's a good idea or not, I'd still be curious to know how laborious this would be from a modder's perspective. I have a growing interest in Python thanks to the work you guys have put into this mod.

Thanks!

**Comment by multimokia** [comment]
There's over 1000 words to write for in that case. Doesn't seem all that feasible

**Comment by PaperPlate1** [comment]
Jesus... I figured there were a lot, but given how many repeated words I get I would have never thought there to be over 1,000 of them. That does seem a bit too labor intensive (even excluding character dialogue).

**Comment by HenryKhan** [comment]
Well... We could start with the more "meaningful" words. Like the ones that are related to Monika/[Player]/DDLC content, or something like that.

**Comment by PaperPlate1** [comment]
@HenryKhan That's true. Every word would definitely be a hassle, but only a handful of the more "meaningful" ones like you had mentioned would probably be enough to break any monotony between rounds.

**Comment by multimokia** [comment]
This probably wouldn't be something high enough on the priority list to do ourselves, but if someone out there wants to do it, they can feel free to go for it and when its ready, make a pull request adding them.

**Comment by ThePotatoGuy** [comment]
if its done for specific words, it doesnt seem too bad. 

In terms of changes needed:
* need to decide how to introduce the option to learn more about the word. this could be a button shown after the word is guessed (which should definitely **not** be a standard menu because that would be an extra click for people who just want to play)
* need to decide where to store the extra dialogue. the text file seems like a good candidate, but those are meant to be replacable, aka users can swap these out for a longer wordlist as long as it has the appropriate values set. Storing dialogue in the text file means thinking about how to store that data and dealing with parsing issues and stuff. Hardcoding the dialogue in renpy code is also a bad choice since that's a lot of extra simple labels.

and neither of the above issues are trivial to deal with.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
