### ISSUE TITLE
[Suggestion] make changing clothes more natural

### ISSUE THREAD

**Issue by NCRaouf** [Monika-After-Story/MonikaModDev#4903]
As the title says, I think that when you choose the clothes that monika should wear, she would tell you "I'll be right back" or something like that and go for 5 seconds and come back with her clothes on.

**Comment by RavenPLAYER** [comment]
I always thought about writing this suggestion :P. Good idea, don't you think?

**Comment by ThePotatoGuy** [comment]
because of the previewing nature of the selector system, this isn't really viable. You can either have the system as it is, where you can view the options before confirming, or not be able to preview and have to confirm every time.

I guess we could make it so that instead of an instant preview, monika takes 5 seconds/some amount of time to put on the clothes when clicking a selector item, but now that introduces long delays when previewing clothes and results in a poor user experience.

[marking as rejected, leaving open in case of discussion]

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
