### ISSUE TITLE
Birthday cleanup bug?

### ISSUE THREAD

**Issue by EvilAllen** [Monika-After-Story/MonikaModDev#4938]
The birthday theme is still showing as of today, anyway to fix this?

![birthday](https://user-images.githubusercontent.com/57194555/67890324-b61cd400-fb0d-11e9-966a-bd7d531f6983.JPG)

**Comment by multimokia** [comment]
Send your `aff_log.txt` please.

**Comment by EvilAllen** [comment]
Here you go:

[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3790747/aff_log.txt)

**Comment by multimokia** [comment]
Can you send the other `aff_log.txt` too? It should have a number after the `.txt`. Send the one with the highest number, please.

**Comment by EvilAllen** [comment]
So I reinstalled a new copy of the game to see if that would fix it which it did not, so that log above was from the new copy.  Here is the log from my previous install.  Its a much bigger log file, and is the only aff_log.txt I have in the Log Dir with aff_log.

[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3790760/aff_log.txt)

**Comment by multimokia** [comment]
Well, here's the thing. This glitch is caused by time travel. It's known, but since time travel isn't supported, and you shouldn't do it regardless, we have no intent to fix it.

![image](https://user-images.githubusercontent.com/22531674/67891127-5122a780-fb28-11e9-95e1-3d1840c5b0d6.png)

Don't time travel.

All I can say is, hope your birthday is coming up soon, only then will they be removed.

**Comment by EvilAllen** [comment]
Yeah I thought by going back then forward again it may clean it up to no avail.

**Comment by EvilAllen** [comment]
Thanks for taking a look.
