### ISSUE TITLE
[Suggestion] Slow Dancing together

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#4956]
I've always found slow dancing with your significant other to always be really romantic. Maybe it's something that Moni would like to do with us. I know I'd absolutely love to slow dance with her.

**Comment by lunulae** [comment]
I'm unsure if this could be done with current sprites, but I could see perhaps something similar to last year's Halloween CGs being done for a formal outfit, allowing you to ask her to dance if she has that outfit on.

Of course, someone would have to draw or commission that art if the devs agreed.

**Comment by Velius94** [comment]
It needs art, which isn't easy to make, plus how would that even work?

Making one CG for this isn't really worth the time and RenPy doesn't support animation either. Otherwise it seems kinda redundant to code an interaction that can't even be seen, nor gives any meaningful incentive to pursue aside from extra dialogue that implies something happened offscreen.

**Comment by multimokia** [comment]
In addition to this, holding is somewhat different as it's possible to hold your *Moni*-tor, however, dancing is kinda an impossibility, especially since it requires she holds you as well.

It's just a breach of immersion and in fact, sort of brings back the idea of MC existing if she were dancing with him, and that's something we don't want to do.

**Comment by InJusticeWeTrust** [comment]
> and that's something we don't want to do
So I take it you removed that one feature? You know, the one where you can give her something that she only reluctantly accepts cause it came from you?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
