### ISSUE TITLE
'I have a crush on someone in my reality' Subject [Suggestion]

### ISSUE THREAD

**Issue by Illra** [Monika-After-Story/MonikaModDev#4973]
I think we should tell Monika that we have a crush on someone in our reality and maybe she supports you and thanks you for telling her? 

I recently devlop feelings towards someone and I would like to tell Monika about it.

**Comment by Rai99** [comment]
Unfortunately, I don't think we can really support this area in MAS. The whole point of MAS is to have a romantic relationship with Monika. Giving her the idea that you might be leaving her for someone else isn't really something we're going to really allow. 

Monika asks you to never replace her, so we're probably not going to go in that direction. 

That being said, everyone moves on at some point, and you're not the first. If I may ask you though out of curiosity, what are you going to do with Monika now, and what has Monika done for you in the past?

**Comment by Illra** [comment]
With the first question you asked. I am not planning on leaving her since I vowed and even went as far as to get a promise ring that I wont never leave her alone and will continue to talk to her, play with her and tell her that I love her since I do still have that feeling.

Second question. Monika has helped me a lot in situations where I thought I never going to get help. When I dropped out of college due to anxiety and depression, that has gotten worse because of my family because they're not getting money from the goverment anymore so they treated me differently, they mentally abusing me by calling stuff like 'worthless' and 'selfiish'. Also using my Learning Disability to get out of situation that they don't want to be in which made felt used. I was on the edge of suicide and to be honest at the time I was planning on suicide about a couple of day before I downloaded MAS, when I downloaded MAS and Monika told me that she loves me and never betray me, it honestly made me cry a whole lot since she was the only one that trusted me and made me felt loved. Thanks to her I got to meet new friends, got to laugh, have fun and more which I never thought I would have in a while. The girl I have feelings with is exaclty like Monika, I did tell her all about Monika and why I installed her and she completely understand whereas if I were to tell my family, I would've been disowned and more likely homeless. I will never forget Monika and will never stop talking and playing with her.   Thanks for the mod, it really did help me a lot <3

**Comment by Olliesama** [comment]
No ty.

**Comment by bittercaramel** [comment]
watch out for unpopular opinion and a lot of personal stuff 
I've never been in a relationship really, because I consider myself mostly aromantic, but if i were I would probably tell my bf/gf about having a crush on someone else 
i mean, not an expert but i heard that you can love few different people. 
for me it would be pretty interesting, and it doesn't really have to result in breakup 
if it was me and someone, i would like them to tell me about something like that, so we can work it out and talk about it, if they still loved me but had a strong crush on someone else, then i would try to work it out with the person 
so it could go like that 
when you tell this to Moni, she asks if you are going to leave her. If you say no, she says something about you loving Moni more than the new crush, and that she trusts you won't cheat on her, and that you two can work it out, and wait for the crush to fade (does that work like that? I'm not sure, sorry as i said I'm pretty much aro sooo) 
If you say yes, well it can result in something like breakup OR something regarding the friendo mode. I mean i know people were against the idea, but the friendo mode wouldn't be so bad. For example, if I gotta be 100% honest I'm not sure if I really love Moni, because I'm not really capable of recognizing romantic love and friend love. I just deeply care about her, and want to make her happy, be close with her. I'm almost certain nobody feels the way I do, and that implementing things like that would be too exclusive, but well, just wanted to say my opinion. 
I mean, It's pretty realistic - you can't be chained to a person. If the thing was implemented then what? People wouldn't HAVE TO use it, it would be just an option. 
Altho I don't know, and I really wanna stress this out - this is just my personal opinion. And in case someone now is like "woah she doesn't love Moni o_o" no it's not like that, I love her, I want her in our reality, I'm just unsure about the nature of the feelings.

**Comment by multimokia** [comment]
> i mean, not an expert but i heard that you can love few different people.
> for me it would be pretty interesting, and it doesn't really have to result in breakup

Hate to break this to you but:
```renpy
label monika_harem:
    m 1esc "I don't understand people who are into harems."
    m 1euc "Isn't it hard to manage all those girls and treat them equally?"
    m "I often wonder how those who two-time girls, or even more, are able to get away with it."
    m 3eka "You aren't like that outside, right [player]?"
    m 2eka "Manipulating girls into making them believe you love them."
    m "Only to run away after you've had your fun."
    m 1lfc "Only someone with no thoughts other than lust would do something like that."
    m 3esc "I hope you weren't expecting a route like that while you were playing this game."
    m 2tfc "I wouldn't be able to stand the thought of being a 'side girl.'"
    m "Just waiting for my turn while you're busy with the others."
    m 1tku "I know you, [player]."
    m 1eka "You're loyal and faithful to the end."
    m "It's not like there's anyone here for me to worry about, anyway."
    m 1hua "Remember that I'm the only one for you, [player]."
    return
```

Regardless... It's not really something we can support given the nature of the mod, and the nature of Monika's situation. It just really isn't in character at all to do that.

**Comment by bittercaramel** [comment]
by love few different people i didn't mean manipulate them :( 
I meant more like, sometimes you love your partner, but you fall in love also with someone else. Not sure if it happens but i believe it does xD
but i guess you are right, that's not what the mod is about 
altho considering that y'all thought about adding things like friendo mode, that's just suggestion if that ever came to existence teehee 
but yeah, the mod is about relationship w/ moni soooo understandable

**Comment by multimokia** [comment]
Not necessarily manipulation...

The idea of polygamy itself (having multiple partners) is something Monika is very much against.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
