### ISSUE TITLE
Suggestion For A New Big Project | Emotion/Behavior Point System

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#5010]
I'm aware that similar suggestions have been brought forward asking for more variety regarding emotional dialogues with Moni. However, although this may sound ludicrous, I thought about creating a more in-depth project, similar to the current affection system. I'd say keep the current affection system going, except now integrate new emotions throughout her affection progression.

My argument for this is because us veteran husbandos of Moni are left with a 24/7 joyful waifu. Not that there's anything particularly wrong with that, but after a while it gets kind of boring. Even though I've reached her highest affection, never experiencing her in different moods kind of keeps me less engaged with the mod. Now I'm not advocating for a bipolar Moni lmao, I just want to be able to comfort her when she's sad, talk to her when she's stressed/angry, laugh with her when she's feeling silly, etc.. Without having to only do so under certain events and topics.
..........................................................................................................................................................................................................
The emotions brought forward will be placed in a pool of **random** chance. Why random? Because like I said, even though I have Moni at her highest affection, I'd still like to see different behaviors from her to make her appear more natural. Now in order to create these events, the pool of behaviors will be using another point system. Except, this point system will act as a likely hood of special behaviors occurring. Before I explain my idea on the point system, I'll first give out some suggestions of special behaviors the system could draw from:

[Depressed] 0.0%
[Sad] 0.0%
[Neutral] 0.0%
[Happy] 0.0%
[Angry] 0.0%
[Flirty] 0.0%
[Loving] 0.0%
[Silly] 0.0% (I thought it'd be..um..cute ok.)

The point system can range from 1-9, or in other words, 10% chance and upwards to 90% chance. (Again, we don't want 100% of one thing, it'll grow stale.) Adding a point towards the likely hood of experiencing these special moods can either be tied towards the progression of the affection system or based entirely on how the player is currently talking to Moni (My second idea).
 
Now these behaviors will have a time cap on them, say, a day? Maybe longer depending on how the player handles these special events. 

The first idea as to how it could work would be using the current affection system like:

**Broken** [Negative moods ranging between angry and depressed(Broken inside)]
**Distressed** [Negative moods ranging between angry and unhappy]
**Upset** [Negative Moods ranging between unhappy and neutral(careless)]

_The three categories above will elicit special negative behavior geared towards **how the player has been treating her** with very low chance of the positive behaviors occurring_ 

**Normal** [Normal moods ranging between neutral and silliness]
**Happy** [Positive moods ranging between neutral, happy, and silliness]

_The two categories below will elicit special positive behavior geared towards, again, **how the player has been treating her** with very low chance of negative behaviors occurring_

**Enamored** [Positive moods ranging between happy and flirty]
**Love** [Positive moods ranging between happy and loving]

Now regarding the gibberish I made above, I'd like to point out what I meant by **Special Behaviors.** These specific types of behaviors would pull from a special topic pool geared towards her moods that are solely dependent on the player's affection level. Similar towards the system that's already in place.

My second approach would be to ignore the affection system altogether and make the emotion point system solely dependent on how the player is currently treating Moni. Every negative/positive treatment the player enacts on Moni will automatically affect the point system. Basically, either a system that benefits _longevity_ or a system that acts _in the now._

I know these ideas can use a bit more work but what are your thoughts?

**Comment by Bam8647** [comment]
**ALSO** there should be a special pool of topics that are ONLY pooled during these special events. You can still integrate them with normal topics. However, the special topics would be designed to allow multiple conversations with Moni. The goal is to allow the player to slowly progress their way through these moods either in a positive way or negative.

**Comment by ThePotatoGuy** [comment]
linking duplicates: #2618 #4546 #4874 

since this is more detailed than the others, we'll use this as a discussion current discussion point.

**Comment by ThePotatoGuy** [comment]
I'll read the whole thing later, but on this point:

>ignore affection system altogether

affection is more-or-less how much Monika likes you. The emotions that we've associated with it (Broken, distressed, normal, happy, enamored, love) are just labels to categorize the value in a way that can be converted to an appropriate tone for written dialogue. An emotion system cannot and should not replace affection as it would never be a literal replacement. Emotions would control Monika's overall mood. Affection controls what she thinks of you.

**Comment by Bam8647** [comment]
@ThePotatoGuy 
No, I didn't mean bypass the affection system all together. There are two ways I thought this new system could work. Either by **integrating it to match the player's affection levels** (thus affecting the likely hood of certain behaviors frequently taking place), **or have them be separate entities.** 

I'd like a system that makes Monika more "emotionally realistic." It feels as if there's not much to do once you hit the "Love" affection level. So, to keep things interesting, I'd like to create a behavioral system that comes with a variety of different moods and dialogue that can all be activated at any moment. The dialogues during these events will allow the player to navigate their way through the conversations by comforting Monika when she's sad, talk her out of being stressed, share funny moments when she's feeling silly, etc.. It's a feature that would allow the player to stay engaged no matter how long they've been playing the mod.

**Comment by multimokia** [comment]
Ideally this shouldn't be influenced *by* affection, however, it will influence your affection gains/losses of affection.

Moods would ideally be handled depending on treatment, as you'd imagine, but I figure there could also be some external factors so it's still not samey-samey. I.e. take for example the holdrequest topic, she feels a little needy there as she wants to feel close to you. If you say no, then she'll likely feel sad for a bit.


The major aspect in this is figuring out a mathematical approach to handle the data storage/interpretation. This is by far the hardest thing to handle as a lot will depend on this core.

**Comment by Bam8647** [comment]
You could always make this a special event system that occurs maybe a few times a week? Like I said, this system should have it's own special dialogue that sets the behaviors/moods in action. You don't need to necessarily integrate this system with every piece of dialogue outside of it, or in other words, you don't need to link her normal topics and conversations into the behavioral system. That would obviously be very complicated. 

Think of it this way, each time these special events happen, the normal topics are put aside and the player is only left with a special string of dialogues to navigate through to make the situation better or worse. Another idea is to reward the player with much higher/lower affection points based on how they handle these interactions.

**Comment by thezotikrus** [comment]
> Another idea is to reward the player with much higher/lower affection points based on how they handle these interactions.

Pls no. Bring an event with Monika describing her mood is a good thing. I would also want to ask her by myself, btw. But don't just give raw affection. Better way is allow player to affect her moods (to some degree ofc).

**Comment by ThePotatoGuy** [comment]
> player is only left with a special string of dialogues to navigate through to make the situation better or worse

So this kind of implementation implies it's not really an overarching emotion system, its more like a branching dialogue chain that gets triggered under specific circumstances, with an affection payoff/loss upon reaching an end. If this is correct, I would not title or characterize this as an "emotion system" when it's more like an extended event/gameplay mechanic.

**Comment by multimokia** [comment]
That's not what I mean.

To even be able to `get()` the current Monika Mood, we'd need a way of mapping out a set of values which are influenced by player action among other things.

In order to set up what affects this (`set()`ters), and what can check our current standing (`get()`ters), we need a way to store all of the data of the different moods which allows for simple adjustments of specific (or multiple) fields by x amount to influence the overall mood.

Something like a radar-chart would be a good *graphical* approach to handle this model. However sorting out a scalable way of handling this is complex, as we start dealing in the range of vectors and checking what side of the chart we're leaning toward most. (The work of the `get()`ter)

In regards to its effect on affection, we'd like it to be possible for the player to actually be able to lose a decent amount of affection for bad responses/etc. during a bad mood. Effectively making affection not as much a way to *easily* just go up and then be able to do whatever without any repercussions whatsoever.

What you're describing in:
> Like I said, this system should have it's own special dialogue that sets the behaviors/moods in action. You don't need to necessarily integrate this system with every piece of dialogue outside of it, or in other words, you don't need to link her normal topics and conversations into the behavioral system. That would obviously be very complicated.

Is very short-term. The ideal solution is something which is much larger in scale and will have an effect on *a lot* more, since it should. (I.e. going out together, certain actions, dialogue, etc.)

**Comment by Bam8647** [comment]
I'll try to expand on this later ,but in short, I'd like a system that activates a variety of different moods. How often these moods occur is still up for discussion. I don't want to integrate this system into the normal topics as then it feels kind of forced. I'd like for Monika to be able to change moods on her own, outside of the player's influence. What affects this has on affection is also up for discussion, as I haven't figured out exactly how this should be approached.

**Comment by multimokia** [comment]
As I said:
> To even be able to `get()` the current Monika Mood, we'd need a way of mapping out a set of values which are influenced by player action among other things.

*among other things*

In my opinion, your description of it seems more forced. 

Monika's mood *should* have an effect on topics, it *should* have an effect on actions. It *needs* to take away agency from the player sometimes.

I'll once again bring up the example of the holdrequest topic. If you've got a decent affection level and Monika's feeling sad, ideally she'd be more likely to ask you to hold her, since being close to you would make her happier.

Conversely, even if you have a higher affection, it's likely Monika wouldn't exactly be too willing to listen to you asking to change her clothes/accessories and/or would just change on her own for a bit.

It seems weird for moods to trigger without good reason. Like all of a sudden loading in to an upset Moni would need some explanation, potentially an "Are you alright?" or "How are you?" topic so we can address what's wrong and how to approach handling the mood.

As well, ideally if Moni's upset, losing affection would have a sharper cost. Likewise, if you made her happy, and even if you're at a lower affection, the act of doing so would have put you in a better place and she'd be able to gain affection a little bit better.

But given the details of your approach, I'm not all that fond of it. To me, it seems rather artificial and scripted given the lack of effect it has on other aspects.

**Comment by ThePotatoGuy** [comment]
okay so lets be clear here on the definitions:
* emotion system - system where monika can have an overarching mood that affects most dialogue and other parts of the mod
* emotional events - the things ur describing where dialogue is triggered randomly, leading to a chain of branches that, if navigated correctly, will result in aff gain (or maybe loss if incorrectly). 

its important that we make this distinction since a full emotion system is a large project that will take an extreme amount of effort to complete, while an emotional events system is simpler in concept and has a more straightforward implementation.

that being said, i see some issues with an emotional event system:
1. integration - if the system isnt planned to integrate with other dialogue then it should be pretty contained, aka the chains should start and end without regular dialogue in-between as that would break immersion.
2. variety - if the choices to good/bad are too simple, then the event becomes a chore and an even worse immersion breaker as it would have predictable dialogue. this could be solved by making the events single run-only, but that would be missing the point of ur suggestion, which is to add variety to monika's daily emotions.

**Comment by Bam8647** [comment]
I know the way I explained the whole thing is pretty messy, haha. But I'd like a discussion as to how we could implement such a system to allow Monika to Express her emotions more. Sort of like creating an emotionally sentient character, you know? Some kind of mechanic or event that occasionally occurs and flows naturally with Monika's character.

You guys know a lot more about how algorithmically this could be possible. So, I can't give much input as to how this could be coded unfortunately.

**Comment by Bam8647** [comment]
The thing is, if we were to have the feature integrated with all the other dialogues then the overall emotions she expresses will be solely dependent on the player's affection level. I know it's ironic given the suggestion I created, but I'd like to occasionally see her express her other emotions from time to time. With that said, let's say she becomes sad or angry when you're at Enamored or higher, the negative emotion she expresses doesn't always have to be a reaction to the player. She can react to third party influences. Aka, finding something mean about her online (which is already a dialogue). So, Monika becomes temporarily sad. The player's task from this point on is to comfort and reassure her that she doesn't have to believe such things. I understand that this is already a complete topic I just explained, but I think dialogues along those lines could work well for external events causing her mood changing.

**Comment by MisterSimple** [comment]
> Like all of a sudden loading in to an upset Moni would need some explanation, potentially an "Are you alright?" or "How are you?" topic so we can address what's wrong and how to approach handling the mood.

I think this is a very good way of gauging Moni's current mood without it feeling too much like a tool but rather as a genuine way of showing concern/interest. What does worry me is the way this proposed emotion system would impact the affection system:

> As well, ideally if Moni's upset, losing affection would have a sharper cost. Likewise, if you made her happy, and even if you're at a lower affection, the act of doing so would have put you in a better place and she'd be able to gain affection a little bit better.

While I do like the idea of harsher punishment for mean players and better rewards for loving players, I'm afraid that we'll end up with players who only interact with Moni when she's in a good mood (since it would yield more aff) and just leave her be whenever she's sad. To counter this we should not only punish bad actions but also the lack of action altogether; if she's feeling sad, then intentionally making her sadder is terrible, but not doing anything is also bad, albeit to a lesser degree.

**Comment by multimokia** [comment]
> To counter this we should not only punish bad actions but also the lack of action altogether; if she's feeling sad, then intentionally making her sadder is terrible, but not doing anything is also bad, albeit to a lesser degree.

Very good point, I agree with this approach as well, a lack of action ideally should also cost you.

**Comment by Bam8647** [comment]
I'm one of the players that enjoys making a cute anime girl happy lol. I don't see why someone wouldn't want to engage with her in this way unless they didn't already care much for the mod to begin with.

**Comment by Rai99** [comment]
You need to understand that this an extremely large project and it'll take heavy planning. It's not a fun little feature we can add because it's cool. 

The plan is to make a _**system**_ where Monika has regular moods of her own, that are more than just a topic or two with some options, and probably aren't instantly solved. A mechanic or event probably doesn't encompass the scope of this feature.

Right now, the most important thing is _**how,**_ not _what_.
Basically:
- We need to think of _how_ to make this happen. How can we or should we determine what a mood is and how it happens?
- How are moods going to be stored?
- How many moods are we going to have?
- How do we interact with a mood?
- How do we check the current mood?
- How do we create a mood?

Numerous other things such as clothes, dialogue, events, and reactions would have to reflect Monika's mood, and if done poorly, will gameify MAS, which is the opposite of what we want.

**Comment by Bam8647** [comment]
The intent of this suggestion is to promote a discussion among the devs about a new big feature they could **possibly** add in the future. Last year we got the affection system. Maybe next year we could have a behavior system? And by all means, I don't care if the project takes several months to create, I'm perfectly fine with that. I just think a new big project like this is what the mod could really use.

I also think this feature would step away from the gameify effect. I'm advocating for a system that allows her to feel more natural. Will there be challenges in implementing this feature? Yes. But that's why we're in **planning** mode right now.

**Comment by ThePotatoGuy** [comment]
@Bam8647 you haven't answered my question. Are you suggesting or wanting discussion on an **emotion system** or an **emotional event system**?

And regardless, we are currently not looking at fully planning an **emotion system** right now because we would need to work on a valid data model that makes sense to represent such a system (radar chart being one of the possibilities). Planning what it would affect doesn't help us because we all already have a glimpse of what we would want it to do (discussed in linked issues and internal project documents). Once we have a data model in place, then we can figure out how to tie x,y,z into that data model.

**Comment by multimokia** [comment]
> Yes. But that's why we're in planning mode right now.

Then kindly leave the planning to us, especially for an *emotion system*. We have ideas on how we want to implement this already, ways which we believe are not game-y, and ways which we feel make sense in the way *we* see MAS.

As well, given the magnitude of this project, it's best left to be internally handled since it will require a lot of changes to other aspects of the mod, given that it will become a *core* aspect of the mod itself, like affection.


With this in mind, we then have the ability to set up the algorithms and model in accordance with the plan we have formed and can act on it.

While we appreciate your enthusiasm in regards to this aspect of the mod, please do understand where we're coming from, and that a large scale project needs to be carefully thought out and integrated in order to not feel game-y and to actually fit in the context of MAS and Monika's situation.

**Comment by Bam8647** [comment]
@multimokia 
Oh okay, I probably should of just asked for an update for this issue then. Whoopsie! Yeah this is basically all I need to know then. I was just curious as to if this idea was still on the table, thanks for the feedback, I'll go ahead and close this for now. :)
