### ISSUE TITLE
[Bug] Lyrics slower than music during All I Want For Christmas Is You

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5098]
As it says in the title, when Monika sings All I Want For Christmas Is You, she sings it slower than the music in the background, and it really bothers me. I hope you can fins a way to fix it. I'm not sure if it only occurs on my computer, but I'm pretty sure it's on every computer because last year when she sang this, it occurred the same way. Happy Holidays!

**Comment by multimokia** [comment]
It's more difficult than you think...

The main problem is that it's completely based on the amount of system resources being used at the time.

If your computer's not using much, it is pretty much in time, no issue. But if there's a slight lag spike at all, the lyrics go behind. It is pretty much impossible to compensate for since it's entirely unpredictable.

What we have now (tested with minimal CPU load) is as accurate as we can get it.

**Comment by PollenTheCat** [comment]
Oh, okay. Thank you.

**Comment by ThePotatoGuy** [comment]
I just want to point out that there are other potential ways to enforce a stricter timing, with caveats:

| solution | PROS | CONS | Notes |
|----------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------|
| using the timed background jump screen | * timing done via allocating seconds for each line, allowing for second-level granularity<br>* handled via screens and timer, all renpy code | * requires a label for each line of dialogue<br>* each label requires a hide/show screen statement<br>* may result in dialogue lines being cutoff if those lines are not finished showing. could be subverted via using "fast" but that might look bad | we use this for menus that time out |  |
| custom displayable (think piano) | * timing can be near perfect<br>* custom displayables offer best performance, ensuring timing is consistent on other computers<br>* potentially generalizable (think piano) | * cannot use the standard dialogue window (think how piano does lyrics)<br>* animating a line to appear left-to-right is difficult. best to not even try since this use-case is extremely limited.<br>* cannot use standard method to show monika expressions (think pianio) <br> * lots of overhead when writing custom displayables |  |  |
|  |  |  |  | 

the current implementation is simpler and works for most people

**Comment by ThePotatoGuy** [comment]
[closing as wontfix]
