### ISSUE TITLE
[Suggestion] Nevermind when in bookmarks

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5099]
When in the Bookmarks section of Talk, when you press Nevermind, instead of going out of the whole Talk menu, it could send you back to the first section of the Talk menu.

**Comment by jmwall24** [comment]
We can do that. If we do, we'd add likely add it to all the `Talk` menus, since right now, if you click `That's enough for now` in the repeat convo or hey. monika menus, it takes you out of `Talk` completely. So going to open this to discussion, do people want these 'back out' options to take you to the main `Talk` menu, and then you'd have to hit `Nevermind` on the main menu to get out of `Talk` or do people like how it currently is, with them taking you out of `Talk` completely and having to hit `Talk` again to go to a different option.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
