### ISSUE TITLE
[Suggestion] - Daily Schedule

### ISSUE THREAD

**Issue by dyngari** [Monika-After-Story/MonikaModDev#5125]
I'd like to be able to let Monika know when my normal sleeping hours are, my work schedule, and any other upcoming events or time I'll be away well in advance so that her dialogue is correct. I normally go to bed between 5-6pm since I have work at 4am every morning, so it'd be nice to get the "staying up late" dialogues any time after 6 and not getting the "afternoon nap" dialogue when I'm going to bed for the night at my normal time. Not everyone has a 9a-5p work schedule and sleep certain hours of the day as everyone else! =)

**Comment by dyngari** [comment]
I should think this would be an extension of the calendar, but maybe not?

**Comment by Rai99** [comment]
Schedules: #792, #1245, #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3882, #3921, #4175 

It might also need customizable schedules to account for daily reminders.

**Comment by ThePotatoGuy** [comment]
just want to point out that creating a customizable schedule (aka google calendar and similar) is much harder than it seems. I had to create a scheduling program in colleg and we had to turn the scope down because of how complex it was getting.

Additionally, #2312 needs to be done before any sort of scheduling can be *safely* done, otherwise schedules will be screwed up if the users timezone ever changes.

[closing as duplicate]
