### ISSUE TITLE
[Suggestion] Religion | Holidays

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5128]
For my first suggestion: Religion. I think it's somewhat important for your partner to know which religion, if any, you follow. Along with that: Holidays. Since not everyone celebrates certain holidays (for example: Christmas), they should have an option to pick which holidays you celebrate. I know this would take about three times the work you already do for holidays, but I hope it could be arranged. (I mean, think about how awkward it'd be if you were celebrating Christmas with Monika when you don't even celebrate Christmas.) Have a good day, and Happy Holidays!

**Comment by multimokia** [comment]
My only thing is, the way it's celebrated in the mod is that there's no reference to religion whatsoever.

Much like how a lot of people celebrate Christmas, it's not about the religion, but more just about the atmosphere and the people you spend it with.

**Comment by lunulae** [comment]
Rather than adjusting the holiday events through this, it might be a means for adding some topics. If you celebrate a different holiday, Monika could have a special greeting or a brief topic talking about what you'd do together on that day.
I'm not very educated on ones outside of Christmas and Hannukah but it might be a cool idea for future contributions.

**Comment by softombre** [comment]
even if it doesn't reference the christian religion, its still christmas and it still has most of the Christian traditions, which would probably be kinda awkward for a player who celebrates hannukah for example
yea, i know we can't do events for every holiday ever, but maybe we could add the most well known ones like hannukah?

**Comment by multimokia** [comment]
> but maybe we could add the most well known ones like hannukah?

Actually, there used to be Hannukah topics, but with some internal discussion we'd removed them because of what I'd mentioned earlier.
I completely see what you're saying, but I'd like to raise a counterpoint which was brought up during this discussion was that it quickly becomes a very slippery slope for other events for other religions and such.

This can very easily get out of hand with a lot of events which would need to be added to account for the inclusivity, and there will most definitely be things which we don't really have a good enough grasp to handle in order to do right, leading to a lot of potential offence taken by the community.

Given that Christmas is regarded more as a normal civic holiday and disassociated from religion in that manner, it makes more sense to stick with it that way, leaving the religion aspect out of it entirely.

**Comment by GOKOP** [comment]
> I think it's somewhat important for your partner to know which religion, if any, you follow.
There *is* a topic where Monika asks you if you're religious tho, unless it was deleted.

**Comment by ThePotatoGuy** [comment]
Picking holidays would be nice, but there's too much scope to consider. 

However, being able to opt-out of a holiday I think would be acceptable. Changes to do that might be pretty large, though.
