### ISSUE TITLE
[Suggestion] Anime Recomendations

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#5162]
I came up with the idea on making a conversation where Monika tells you she wants to watch an anime, but doesn't know wich one and asks player to recommend, then I don't know, there could be like a list with some animes and when player tells her to watch x anime, some days later she tells you she watched it and says something like: "I really like the character development" or "I cryed when..." something like that

**Comment by Rai99** [comment]
#4684 

Having a list of different anime to select wouldn't really be possible beyond a small handful, and there are definitely more than that. 

Even if it was a text entry, there wouldn't really be any way to do anything with it, especially if we want to make specific critiques about specific anime. 

A similar idea was brought up in the linked issue, and unfortunately rejected, since it would require ongoing additions to add more, especially as new media is created and released, which, based off of the cancelled movie feature, isn't likely to happen.

**Comment by FrikiHD** [comment]
But how about we put the most famus ones only?

**Comment by multimokia** [comment]
It's a slippery slope. You'll get people saying

"But x is here, why not y?"

**Comment by RavenPLAYER** [comment]
Look the https://github.com/Monika-After-Story/MonikaModDev/issues/4684.

**Comment by FrikiHD** [comment]
Then I guess F for Otaku Monika :"v
