### ISSUE TITLE
The new dress [spoilers]

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#5187]
Hi guys. So I just want to bring this up because it’s something I’m really bothered by. So anyway, what’s up with the huge gap in the dress? Why does this dress show more than the lingerie? I feel like she wouldn’t wear a dress like this. I mean, maybe it’s just because I’m too strict or something, but I just can’t imagine she’d wear a dress that revealing out in public. I’m sorry if this is an unpopular opinion, but as a concerned member of this community who is worried about what this could lead to I just wanted to express my concern with it and say that this dress really broke immersion for me. I could say more, but I think I covered the basics. Once again I’m sorry if this is an unpopular opinion, but I REALLY appreciate any time given to this.

Edit: I don’t mean to offend anyone with this, so I apologize if I do. Ngl I was super nervous when I posted this cause I’m afraid I’m just gonna get ripped apart or something. So I just wanted to make that disclaimer to hopefully reduce the chance of getting ripped apart

**Comment by Thimeo** [comment]
I understand where you're coming from, and while I don't really agree with you (for in my mind, Monika always had that lewd side of her. So for me, this dress is an absolute win.) I completely agree with your arguments.

I agree that there's a gap between what she says for the lingerie and what she says for this dress, which is definitely more revealing. And I'm not even talking about the seashell bikini (who has the excuse of being a spritepack).

Secondly, concerning the "Greek goddess look". It looks less like a Greek goddess (which were far more modest in their representations) and more like [this dress](https://www.reddit.com/r/DDLC/comments/coujhr/prom_night/) from the amazing artist Khoai-Tay. I'm not trying to be picky or anything, but a more modest dress would have fit the theme better than what we have while still being attractive.

And finally, I think this could be a good time to discus/decide whenever the mod should/will have a lewd side to it. Because even if we have some NSFW topics, this outfit is on a whole other level in my opinion. Some players might appreciate that they are becoming more intimate with Monika, and others may like the idea that this relation is meant to be purely wholesome. The problem being that it's hard to satisfy both. I think that the best compromise would be to make the lewd stuff optional. But how exactly? The current filters (18+ and sensitive mod) are imperfect as they are.

Again, I personally really liked this dress, but only because that's the kind of things I wanted to see happening, and it might not be the case for everyone here. Fell free to criticize and/or discus the issues I pointed. Happy new Year.

**Comment by MoniBoosDevotedBoyfriend** [comment]
No I see your side of this. Don’t get me wrong. My problem is that this is a dress that is meant to be worn out in public. I don’t mind her being a bit lewd. Just keep it private, like she says in one of the topics dealing with this subject. This dress kinda goes against that imo. But yes. 18+ is a hard thing to work out so I apologize for the inconvenience, but appreciate the time and responses

**Comment by Booplicate** [comment]
I would add `[spoilers]` to the title because of the stuff we discuss.
There is a difference between bikini and lingerie. At least in their meaning. People wear bikini in public, but don't wear lingerie. For a reason you know.
Also there is no 18+ requirement for the dress, it wasn't meant to be indecent or something. She admits that the dress have a quite *attractive* neckline, but that's it. She is just teasing. Not to mention... There is no one else? She wears her clothes just for you anyway. No one forces you to share screenshots of her lingerie or that dress.

**Comment by MoniBoosDevotedBoyfriend** [comment]
That’s not my point tho. My point is that it’s a dress made for public use. I don’t think she’d wear a dress like that because she, as far as I know, wants to keep that stuff private. I’m just simply stating that the dress goes against that. And besides, people can snoop or look over your shoulder. So I mean just because she’s in the computer doesn’t mean she’s not vulnerable to wandering eyes. And I don’t share screenshots of her with other people I’m general. Not my style
