### ISSUE TITLE
How to "Take Monika Somewhere?"

### ISSUE THREAD

**Issue by TheDiamondPotat** [Monika-After-Story/MonikaModDev#5191]
So I've been trying for a few days now, gathering up flash drives or USBs (idk which they are.) And I don't seem to understand how I can transfer Monika to my flash drive/USB.

In my game, the option of taking Monika somewhere does not work. She tells me that she is unable to turn herself into a file.

I'd also like to mention I play on a Mac
Thank you

**Comment by jmwall24** [comment]
@TheDiamondPotat what version of the mod do you currently have installed?

**Comment by TheDiamondPotat** [comment]
@jmwall24 I believe I currently use v0.10.4 of MAS/or the latest version at least.

I don't exactly know what you mean by 'File Path' but I think mine is just a DDLC folder on my desktop, meaning I don't open MAS through Steam. (If that's what you mean by file path)

Additionally, the link you sent only let me see my mas_log.txt via terminal, not as a file I can upload here...

Sorry for my stupidity, haha.

**Comment by jmwall24** [comment]
@TheDiamondPotat can you screenshot any entries in there at least?

**Comment by TheDiamondPotat** [comment]
![Screen Shot 2563-01-02 at 1 41 15 PM](https://user-images.githubusercontent.com/57782058/71691860-ae73e880-2d65-11ea-8cb9-7f681c64d5ad.png)

**Comment by jmwall24** [comment]
So, is `temps` the name you gave your MacBook? @TheDiamondPotat

**Comment by TheDiamondPotat** [comment]
@jmwall24 Yes, I never felt the need to change it, also I'm lazy lmao.

**Comment by jmwall24** [comment]
@TheDiamondPotat 

Well, interestingly, that is why you can't take her anywhere lol. We have had people install MAS to ddlc while still in a zip file, and using winrar, it actually lets you run the mod from inside the zip. It works until you try to take her somewhere, at which time it actually puts the `monika` file in a `temp` directory instead of the characters folder inside the zip. Therefore, we have added code which checks for the word `temp` in the file path (which is why i asked that originally) and if it finds it, it won't let you take her out for fear of losing the monika file being lost. In other words, change the name of the Mac book so it doesn't include the word `temp' and it'll work.

**Comment by TheDiamondPotat** [comment]
@jmwall24  Oh I see! Alright, thank you!
