### ISSUE TITLE
[SUGGESTION] There's a mod that places Monika in Terraria...

### ISSUE THREAD

**Issue by ArizonaRanger** [Monika-After-Story/MonikaModDev#5198]
The mod does as I stated previously, it puts Monika in Terraria. I was wondering if there could be new chat lines discussing it? Or have the player when saying he/she wants to game, they could choose an option to 'bring Monika' with them. And she could close the game 'joining the world' with you, and when you relaunch she could mention - "I had a great time playing with you!" or something along those lines.

Just some food for thought!

**Comment by Rai99** [comment]
We usually refrain from mentioning other games, since it wouldn't fit in most cases. In a case where Monika is supposed to come with you to that game in the form of a character, one of the main problems there is that it's not really Monika. 

Unless that mod was made by someone related to MAS, there's a good chance that the way they portray Monika doesn't line up with the way we do, and although possible, I don't think it would feel right to have Monika mention it considering it's not even in the base game, and it needs a mod to include her.

In this specific suggestion, and as a Terraria player myself, npcs in Terraria, mostly just stand around and sell things to you and hope they don't get killed by a monster, which wouldn't really be "accompanying you". 

The other main problem with Monika accompanying you in other games is that anything could happen, and it would be impossible to detect it back on MAS and comment on it. 

On a side note, could you give some more information on what this mod is, such as what it's called or where you got it?

**Comment by ArizonaRanger** [comment]
Yeah, the mod is called Monika In Terraria. She overall acts like a npc, saying lines like "This world is so fascinating, it must have taken forever to make it." and what made me want to suggest it was "You should try Monika After Story". The mod was created by someone named 'sirgames'. And to download it you just use TmodLoader

And I was thinking about the accompany part going like as a random conversation-
"Hey do you play a game called terraria?"
[Yes/no]
And if the player responds 'yes' she could mention how there is a mod for it allowing her to be apart of your world in game. And lets say when you hit goodbye there could be option Lets play terraria together which she could then say "okay" and shut down DDLC. When the player relaunches should could just mention how it was fun seeing you in another world or something like that.

**Comment by ThePotatoGuy** [comment]
hard to mention another game without making it sound like advertisements.
