### ISSUE TITLE
[Suggestion] - Include a persistent backup in game/

### ISSUE THREAD

**Issue by zombiepigdragon** [Monika-After-Story/MonikaModDev#5204]
It seems to be an extremely common mistake to copy the install folder, instead of the persistent file. Why not copy the persistent into the install, to prevent accidental deletion? Shouldn't take too much extra space, and could save a lot of heartbreak among people who fail to read the instructions...

**Comment by multimokia** [comment]
The instructions are literally linked in game, if you don't bother to click and read them, that's on you.

**Comment by Delcos** [comment]
Id say you could just make your own macro to back up the persistent file every 24 hours or something similar.

**Comment by ThePotatoGuy** [comment]
2 things:
1. persistent data is not stored in the same place across different platforms
2. mod managers like [DDMM](https://doki.space) can fake the path so persistent data is stored in a non-standard place (configured by the mod manager)

Not worth trying to manage the variety of these cases to duplicate data, especially since instructions are in-game already.
