### ISSUE TITLE
Adding Files

### ISSUE THREAD

**Issue by TheFinkster3** [Monika-After-Story/MonikaModDev#5211]
I think it would be a good idea is you could place a .txt file in the game (i.e. i love you.txt, etc) and Monika would respond to it. It would be a good addition. :)

**Comment by Rai99** [comment]
Reacting to text files: #784, #1276, #1710, #2175, #2811, #3138, #3494, #3552, #3880, #3941, #4088, #4981

If you're suggesting have text files with written messages in them, that's not easily possible, since there's not really any feasible way for us to meaningfully make sense of its contents. 

If you mean to have an empty file simply named something specific such as "I love you", this would probably work similarly to gifts, but I don't see why you can't open up MAS and tell her in person in that case. Also, while this could be made as a giftable file, it would probably feel out of place with the framework.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
