### ISSUE TITLE
[Suggestion] Ask Monika which of the girls she liked best

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#5272]
Self-explanatory.
With all of Monika's opinions on Yuri, Natsuki and Sayori, I don't think it'd be too far-fetched to ask Monika of her opinion. After all, she _did_ ask us.

**Comment by fromulus** [comment]
Probably not a great idea, in my opinion...
Monika's role as a president isn't to play favorites with her club members.
Plus, this means that we can either go the boring "I like them all equally" route (which Monika haters will then look at and point out as hypocrisy on her part), or choose one girl over the others, most likely with an arbitrary reason behind it, which would then feel kind of weird and might annoy the other girl's fandoms.

At least when Monika asks you, it makes sense because 1) it is _your_ opinion, so it doesn't send the message that the mod is favoriting one girl over the others (well, aside from Monika herself), and 2) You were meant to romance them, so of course Monika would be curious to know (and possibly a little jealous).

**Comment by thekill9714** [comment]
> Probably not a great idea, in my opinion...
> Monika's role as a president isn't to play favorites with her club members.
> Plus, this means that we can either go the boring "I like them all equally" route (which Monika haters will then look at and point out as hypocrisy on her part), or choose one girl over the others, most likely with an arbitrary reason behind it, which would then feel kind of weird and might annoy the other girl's fandoms.
> 
> At least when Monika asks you, it makes sense because 1) it is _your_ opinion, so it doesn't send the message that the mod is favoriting one girl over the others (well, aside from Monika herself), and 2) You were meant to romance them, so of course Monika would be curious to know (and possibly a little jealous).

I think it be more interesting if you could, but rather Monika replies about basically what you said, she does not pick favorites and why its important for her to be impartial and treat all equal like a club president. She then can end by leaning over with a romantic look saying. "But if I had to pick a favorite club member, it would be you (Player); your part of the club after all, and I know I'm your favorite."

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
