### ISSUE TITLE
[suggestion] - Can there be a Greeting option in the "Talk" menu

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5274]
The title is a giveaway but here are some examples of greetings:

Good evening (a different dialog)

Good morning (same as above)

hello (...you get the point)

nice to see you ("Nice to see you to, how is your [day, evening, morning, night])

long time no see (your being silly [But if you were gone for a long time] i agree, its been awhile)

Maybe add a few of your own?
Thank you :O)

**Comment by multimokia** [comment]
Not entirely sure how this would work, given that as soon as you load in, Monika greets you (As well, there's already a `Good morning` topic and `Good evening` topic)

**Comment by WingdingsMaster** [comment]
WHOOPS forgot to add "Suggestion" in the title

**Comment by WingdingsMaster** [comment]
I mean, could we greet her back?
" as soon as you load in, Monika greets you "

well those seem like one time buttons...
there's already a `Good morning` topic and `Good evening`

**Comment by multimokia** [comment]
> I mean, could we greet her back?

Issue with this is the open-ended nature of some of the greetings, it's difficult to think out a lot of the possible responses (and it wouldn't be in the talk menu, since at that point the moment is gone. It'd have to me directly in each greeting)

**Comment by WingdingsMaster** [comment]
ah, I see... well should my examples work?

**Comment by multimokia** [comment]
Even then, not really. It would require a rewrite of pretty much all the greetings, as some options will fit but others won't, plus certain greetings have their own rhetorical prompts in them which would now need to have an answer to them if we're going to add something like this. However it's not easy, again, to account for everything.

Honestly not sure if it's too worth doing.

**Comment by WingdingsMaster** [comment]
ah, good point, Ill cancel the idea,
... how do you do that?

**Comment by GOKOP** [comment]
> > I mean, could we greet her back?
> 
> Issue with this is the open-ended nature of some of the greetings, it's difficult to think out a lot of the possible responses (and it wouldn't be in the talk menu, since at that point the moment is gone. It'd have to me directly in each greeting)

But you already have "I love you too" option in talk menu in some cases when Monika says "I love you"; if that works then why greetings couldn't?

**Comment by multimokia** [comment]
example:
```python
label greeting_surprised:
    m 1wuo "Oh!{w=0.5} Hello, [player]!"
    m 1lksdlb "Sorry, you surprised me a little."
    m 1eua "How've you been?"
    return
```

If we were to open this up to an open ended system (as to not render the current greeting system useless), this in itself is such a vast question as there's a potentially infinite amount of answers, from the simple "I'm well thanks." to "Not too well...".

This latter option would then need to be expanded on, and the issue is that it's rather impossible to address many potential responses, since when you open the conversation like this, it implies you're going to keep on the subject and discuss what the matter may be together.

Of course, this is just one topic, but it applies to more which do similar rhetorical questions.

"I love you too" is simple, since it's the basic response to any "I love you." in a relationship. The only thing which would make it different is the slight variations, but all in the end meaning the same thing.

**Comment by GOKOP** [comment]
Oh, now I get it. For some reason I didn't think about anything else that "good morning to you too" lol

**Comment by ThePotatoGuy** [comment]
can't see too many uses of greeting someone more than once at a time. maybe as a joke but doesn't seem worth.
