### ISSUE TITLE
Suggestion: A topic for after using a Monika backup

### ISSUE THREAD

**Issue by Arclex** [Monika-After-Story/MonikaModDev#5294]
Seeing as Monika brings up backing her up from time to time a goodbye to tell her that you're going to back her up seems like a good idea. Maybe having a time change based trigger to check if the backup was used by asking the player if something happened if it's been maybe a week since Monika was opened.

**Comment by lunulae** [comment]
This does seem like a really nice touch, since she asks you to back her up often. It doesn't necessarily need to protect against affection loss either--if a long time goes by since the backup persistent was loaded, she could scold you a bit for not being more diligent about it, or be upset that there's so much time she doesn't remember now. But if you apologize, she could admit she's very glad you did keep a backup at all.

**Comment by ThePotatoGuy** [comment]
this is not easily detectable, and its also unlikely since backups are made every session so you certainly should have something before a week passes.
[closing until we look into it]
