### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by TotallynotCloudStrife** [Monika-After-Story/MonikaModDev#5297]
If you choose the name Sephiroth: 
Monika: that’s an…odd name…like a soldier or something…
Monika: with a name like that, you’ll never be just a memory, ha-ha

If you zoom in:
Monika: Oh? You are approaching me?
User input: Can’t look into your eyes without getting any closer…
Monika: ho ho, then come as close as you’d like!

**Comment by AsuraShun** [comment]
I actually needed this laugh

**Comment by multimokia** [comment]
From our [contributing guidelines(https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#pitfalls-to-avoid)

Mainly this first point in there. As well, I don't see Monika as one to watch anime or play video games all that much compared to how much she reads. These references will be a little out of character and as well a few people will find them out of place if they don't know them.

**Comment by AsuraShun** [comment]
She mentions memes in one topic, maybe that would be a good way for the references to fit

**Comment by multimokia** [comment]
You're correct in that she mentions memes, but she never actually says or does something from a meme.

You also don't understand that adding these references date the mod, eventually when they're out of relevancy, they'll need to be removed because then they're completely out of place. So by that logic, there's no point in adding it in the first place.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
