### ISSUE TITLE
Twitter-clones problem

### ISSUE THREAD

**Issue by Mugnika** [Monika-After-Story/MonikaModDev#5310]
There is a very big inconsistency between the monika_twitter and monika_clones topics.

On one hand every single individual Monika says its "her" that posts the tweets on twitter, on the other she mentions there are potentially infinite number of her.

This is a very big issue, since one is canon but the other represents the main pillar of MAS, that every player has their own Monika.

Also I feel her twitter has been out of character lately and don't  see her posting some of the tweets there, not to mention the excessive use of Emoji.

A solution may be to change the twitter topic to reference the clones topic and say that while it may be "Monika's" twitter, its not "her" twitter.

**Comment by jmwall24** [comment]
We've been having discussions related to the official twitter account because, as you said, these days it's extremely poorly written and out of character. Personally, I'd like to distance MAS from it completely. It doesn't fit with our infinite Monikas logic and it's pretty much just terrible these days.

**Comment by ThePotatoGuy** [comment]
the only issue with removing `monika twitter` is that its part of the original set of act 3 topics and would be a deviation from canon Monika

**Comment by multimokia** [comment]
It's possible to do a gradual deviation. If explained right it can be done.

**Comment by InJusticeWeTrust** [comment]
> not to mention the excessive use of Emoji

Hasn't it been that way since 2018? I recall seeing a lot of these going all the way back then.

> it's extremely poorly written

Pretty much since day 1. I'm always baffled as to how someone as high on literature as her would toss proper spelling, punctuation etc. out the window, even if it's online.

My guess is Danny-boy either just doesn't really care much anymore, or maybe it's done on purpose.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
