### ISSUE TITLE
[Suggestion] Cherry kisses and other fruits

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#5327]
So when Monika mentions Cherry kisses we should be able to gift her some cherries or another type of fruit. But with the Cherry kisses, if you have enough affection she would do a cherry kiss with you! If not she'll just eat the cherries like normal.

**Comment by lunulae** [comment]
This could be a good addition once consumables get added, it could have a random chance if she's eating cherries and you use the "kiss me" prompt.

**Comment by fromulus** [comment]
This brings up the same problem as usual-
-Who's holding the cherry/fruit ?

MC ?
Does it just float in the air, placed conveniently in a way that makes it feels like it's in our mouth from our perspective ?

Certainly not us in any case, since we're not physically present in the classroom.
Kisses and hugs kinda work because we can pretend to be doing it, but that's not really possible with cherry kisses as it really needs physical contact to work.

As cute as ideas like these are, I really don't think they should be done at the detriment of the logic and limitations imposed on us by the context we're in (a distance relationship).

**Comment by satoshi-kun** [comment]
In my opinion if we can pretend that we are hugging/kissing Monika, we can also pretend that we are cherry kissing, since hugs and regular kisses also need physical contact to work, 
I don't see why adding a cherry to the kiss would change it that much.

**Comment by Booplicate** [comment]
Nah, I don't think so. To me It **will be** different. Isn't you supposed to eat the cherry? Will you pretend that you eat it? But she still would eat it herself?😕 Not to mention that you'll need a new art for her mouth just for this kiss.
I can see her mentioning a cherry kiss if you saw the previous topic (a fun fact to be correct).

**Comment by lunulae** [comment]
This is a good point, the mod is pretty ambiguous in how much of a sense of touch we have with Monika, and sharing food would definitely be a stretch of that.
It could be done as a playful-pretend sort of way, but it would likely not be worth it to make the extra art for such a small interaction.

**Comment by Rai99** [comment]
#4453 

Actually implementing a cherry kiss would probably have some holes in it, but cherries could be their own consumable, and Monika could potentially mention a cherry kiss.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
