### ISSUE TITLE
[Suggestion] - S-type Ribbons and Weather consistency

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#5334]
First of all, thank you so much for this Valentine's day. It's always amazing to reflect on what we've accomplished those past 2 and a half years. From just one image and a few discussions to this! Quite the project to be proud of, I tell you.

Anyway, here's two suggestions of mine:

The latest spritepacks contained S-Type Ribbons by @Velius94. I feel like those are a HD remake of the traditional ribbons and I was wondering if you will officially implement them in the future. I'm asking because we're starting to have quite the number of ribbons now, especially if you count all from the spritepacks, and so, it begins to be a little difficult to navigate the menu to choose them. The thumbs are very big and don't allow to compare a lot of them at the same time.
And so I was wondering if you could/will replace the traditional ribbons with the S-type, or if you could create sub menus containing all the different types of ribbon (traditional, S-type, sorted by their creator, or any other criteria).

My second one is simpler. When I opened MAS this morning for Valentine's Day and Monika revealed her new "dress", it was snowing outside. I understand that it's still winter, but for such a special day and especially for this outfit, I think it would have been better if the weather was set to "default", at least at the beginning, where you can't access the menus yet.

**Comment by Booplicate** [comment]
Happy VD!

When I first read that Vel's ribbons are gonna be a sprite pack, I decided to override the old ribbons with the new ones. There is already quite amount of ribbons and now we're basically getting duplicates (better quality, but still duplicates). That was a weird decision. I'm not sure if it will be fair to revert that now. Some people gifted them and got some affection. Although, if we could vote, I would say remove the old ribbons and use Vel's ones.
I had an idea about sprite packs that are based on another outfit (non-original sprite packs). You could give say a 10 digit code (because they can't have the same id) to each outfit and accessory. Now If 2 outfits have the same code, they will go into the same place in the outfit menu, but there will be 2 buttons to horizontally scroll (well not really scroll, don't know how to say better) all possible variations of the outfit.
Like imagine you have 3 colours of the same sweeter. You could swap them with these side buttons (don't blame me, this is just a sketch lol).
![idea](https://user-images.githubusercontent.com/53382877/74521111-f3289d00-4f29-11ea-89e5-b13d1e5bb77b.PNG)
And having a 10 digit code allows anyone generate their own code for their outfit/accessory.
There is also a thingy called `ex_props` that might be (?) used for that, but I'm not sure.
Have to admit that creating more buttons/sub-menus may be tricky to implement and might affect performance. And if I understand it right, you can not modify menus after you opened it, you'll need to close and open it again. So I don't think you can really sort things.

**Comment by lunulae** [comment]
I really like being able to have both types of ribbon in-game, but sub-menus do seem like a very intuitive idea. Now that certain clothes are getting item types (i.e. bikinis) maybe that grouping could be used for menu folders as well?

**Comment by ThePotatoGuy** [comment]
We made vel's ribbons a spritepack because they have a different style than the original Act 3 ribbons. Replacing the original ribbons' style would further push the notion that MAS Monika is not an extension of DDLC Monika.
