### ISSUE TITLE
[Possible duplicate] Background not changing in dialogues

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#5357]
Searched around the issues, yet didn't find issues that are related. Maybe I just didn't search *good enough*... Ahem.

So, the background does not change in dialogues and while holding Monika.

**Comment by multimokia** [comment]
This is actually intentional behavior. It's somewhat impossible to do this now with the current way the spaceroom is drawn given that it's a label. Calling that label to draw everything while in another label can cause issues.

It would also mean that we'd need to run a second thread to run checks to see if we should change the room, which would degrade performance, making this not too worth implementing.

**Comment by scpketer** [comment]
*Sigh*... another intentional thing.

**Comment by scpketer** [comment]
Wait. You implemented eye blink somehow. Maybe something like that could be used to update backgrounds?

**Comment by multimokia** [comment]
Again it will require a full redesign of how the spaceroom is handled, which would also mean an overhaul of the background framework

Blinking and the spaceroom are done in two different ways.

**Comment by scpketer** [comment]
So, not planning to implement this at all?

"*It's not a bug, it's a feature*."

**Comment by multimokia** [comment]
No, it has more cost than gain to implement in terms of performance as I mentioned earlier.

I have tested doing this myself and with the current system it's a 50/50 that calling the spaceroom label to redraw everything won't crash because of starting an interaction while mid interaction, and again, performance was degraded. MAS already struggles on some lower end computers, we don't want to make it unplayable.
