### ISSUE TITLE
[suggestion] A new conversation Idea: Sleeping positions

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5359]
<Could Monika talk about the Position you sleep, any why it is healthy to lay to the left? It's A weird topic, but it might be worth putting into the game>

**Comment by Rai99** [comment]
If I recall, it's because the stomach is on the left side of your body, and sleeping on your left side makes it easier to digest food since it's less likely to leak back up, or something like that. It might also fit as a fun fact.

**Comment by lunulae** [comment]
I like the idea of a branching dialogue for this, since Monika could tell each player a fact about their individual preferred sleeping position (I know sleeping on your back is one of the most common sleeping positions, but it is also linked to lower back pain and likelihood of snoring, for example.)

Although, that comes with the obstacle of what to write if the player doesn't have a particular preferred position, so maybe it would fit better as a fun fact.

**Comment by Rai99** [comment]
A topic with a menu might not be best, since there could be any number of sleeping positions, but maybe there could be a fun fact for each known sleeping position. 

A fun sleeping position fact I like to tell people is that sleeping curled up in a ball indicates you're a tsundere. I like to call that the chestnut position; hard and spiky on the outside, soft and sweet on the inside.

**Comment by fromulus** [comment]
If it does end up being a topic with a player choice menu, I sure hope it contains an option for people who struggle every night _because they can't for the life of them find a comfortable sleeping position this is so annoying oh my god._

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
