### ISSUE TITLE
Critique, Suggestions, Bug Report

### ISSUE THREAD

**Issue by Dank-Elf-Boy** [Monika-After-Story/MonikaModDev#5363]
**Event System Critique**
Okay, so I'd like to break up my critique over the current event system your team has going into two categories: Time Specific Content and Event Guides.

_Time Specific Content_: 
Currently I see that you guys use an event system that relies heavily on the player's computer time system. You do this to help the player feel immersed through the mod by letting Monika recognize the current time and day so she can react accordingly. Now I know this is a pretty neat idea, given how she appears to be aware of specific events occurring, but when you start to attach specific content to be unlocked periodically during the day, it can get a little difficult for player's to fully enjoy. Because the current system only shows special content to be interacted with during certain times of the day, it can be a little overwhelming because it requires the player to be very attentive. Normally I wouldn't care if it's a small dialogue that could be missed during the day, but whenever exclusive content (new outfits, music, or any other form of permanent unlocks) gets missed out on it can really make the player feel cheated, especially if they were with Monika for the majority of the event. And so whenever the player misses these small windows of opportunity, they may never see all the content you guys worked hard on. This is one of the reasons why you're seeing a lot of players trying to replay events by messing with their time clocks. It's because they really don't want miss out on anything important. I've been playing this mod since '17, so when I miss out on some good sh-t I get a little upset lol.

_Possible solution 1_: 
Make ALL unlock-able content for every event automatically unlocked at the end of each event. This includes, again, any and all forms of permanent content. Remember the 2018 Halloween event? There was a 10% chance (or whatever it was) to see Monika in her other costume. The event should of included only a special dialogue that mentioned whether the player got the Easter egg or not but still had the outfit unlocked at the end of it regardless of the Easter egg occurring. The event should reward players for participating in it regardless of the time of day and Easter eggs found.

_Possible Solution 2_: 
Create an overhaul to the current system and extend each holiday event(Not birthdays obviously) to a week. This gives the player plenty of time to interact with all the content you've produced. On the actual holiday you could create a "finale" of some sort to close out the event.

_Event Guides_: 
I was unfortunate enough to miss out on some cool content mainly because I was unaware of how to trigger them, regardless of being a Veteran here lol. For example, during the Christmas season apparently there were gifts you could give her and they would appear under her tree. I had no idea that this was a thing lol. This boomer needs a guide within the mod files to help me not miss out on content. Remember Monika's Bday event for 2019? There was a guide written in the character folder that told the player everything they needed to do in order to activate the event. I appreciated that very much, haha!

_Possible Solutions_: 
For every new major event that occurs, please leave more clues (including things you can give Monika) within the mod or at least it's files so the player doesn't feel left out. Not everyone probably knows how to navigate through Github or Discord. Boomer moments exists haha.

_One more question relating to the events_:
There aren't any specific content held exclusively for those who've reached ridiculous levels of affection are there? Example: 5000, 10000, etc. If there is, I highly suggest you get rid of such requirements as they seem completely counter productive to the current affection system as a whole.

**Last but not least were two minor bugs I found.**
Apparently the Gifts: Blueshirt and Pinkshirt aren't recognized despite appearing in their mod asset folders as such. Coding error?

**Comment by MadFoot8** [comment]
Yes! Exactly my thoughts

**Comment by ThePotatoGuy** [comment]
### Timed content.
Majority of all time-based content is based on dates and not at a specific time. Anything that is time-specific is part of an overall aim to make player experiences different and unique per person. We encourage players to not treat this as an achievement hunt and instead enjoy the little moments that may occur because of the time you play.

1. Unlocking all unlockable content at the end of an event is a very game-like mechanic which breaks immersion. The point of Halloween 2018's costumes wasn't to have an easter egg or just release additional clothing options. **The idea was to create the illusion that Monika made a decision on what to wear** (Witch or Neko). This also ties in to making player experiences unique. We've extended this with the spritepacks, so that costumes in general are randomly selected for the appropriate events.

2. The only event that could be extendable is christmas, which already is covered as a range since its a season. Other events (o31, f14, nyd) would be very much nontraditional to celebrate as a range of dates. I do see a potential option here to celebrate events on different dates, which I've marked up as an issue (#5373)

### Event Guides
Our goal is to reference many of the out-of-game actions in-game, via Monika giving instructions or hints. For example, many of our events also use the gifting mechanic, which is mentioned by Monika in-game. We only want to use out-of-game guides for surprises (like Monika bday 2019).

### high affection content
Any content locked to ultra high affection levels would be minor things like an extra idle sprite maybe. The primary range is from 0 to 1000.

### blueshift and pinkshirt bug
make a new issue about this specifically, and include `log/spj.txt`

**Comment by Dank-Elf-Boy** [comment]
@ThePotatoGuy 

**Timed Content**
Okay, so time specific content isn't a thing. [x]
(Thank you for clearing this up)

_"The idea was to create the illusion that Monika made a decision on what to wear"_

Ahh. So like, creating an algorithm that randomizes her outfits for the player. Interesting.
But what if the player never unlocks these specific outfits? Will they have a chance the following year? 

If I'm understanding you correctly, the idea is to create a randomly chosen event, unique for each player, consisting on what the mod's algorithm decides to print out? Meaning, the code consists of multiple scenarios chosen at random? 

**Event Guides**
Last time I interacted with the Christmas content, either I had totally missed out on some dialogue that gave hints or some how the mod must not of pointed out things correctly on my end. Probably choice A, given how other players were more successful. I'll try and look further into specific details next time. As long as the hints the mod gives are repeatable dialogues and not a one time thing.

**Comment by ThePotatoGuy** [comment]
>But what if the player never unlocks these specific outfits? Will they have a chance the following year?

Yes, but sprite system reworks early last year made it not possible to get either outfit by 2019's halloween. This is being fixed with redraws of the 2018 halloween outfits. Additionally, future outfits are likely to be spritepack'd, which means users would be able to select the outfit provided they having the clothing selector unlocked (via affection). Spritepack outfits that are costumes are randomly selected on halloween based on number of times previously worn.

>the idea is to create a randomly chosen event, unique for each player, consisting on what the mod's algorithm decides to print out? Meaning, the code consists of multiple scenarios chosen at random

Multiple ways to experience events is good for tailoring event experiences based on user preference. So having different ways to do things is what we try to do.

>Last time I interacted with the Christmas content, either I had totally missed out on some dialogue that gave hints or some how the mod must not of pointed out things correctly on my end.

The gifting mechanic needs better introductions.
