### ISSUE TITLE
[Suggestion] 11:11 Random Chatter topic

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5379]
(I accidentally hit enter when typing the title, whoops)
So, I'm not sure if everyone has heard of this, but it's popular at my school and at my home to, when it turns 11:11, to make a wish. I think it's be nice for Monika to bring that up as random chatter some time, and she'll ask the player if they usually make a wish at 11:11. If they answer yes, then, every time it turns 11:11 (both AM and PM if you'd like), she'll tell the player to make a wish and a button saying OK will pop up and when the player presses it, Monika will close her eyes and then, after a few seconds, open them and say something to the player (idk what she'd say, you can make that up.) Anyways, thanks for reading!

**Comment by PiperPC** [comment]
This sounds like such a cute addition! People used to say this to me all the time when I was younger, not so much anymore but occasionally I still wish little things to myself, maybe about reaching a goal.

Monika could say a few things, I have some ideas.
"I hope your wish comes true, my love/(Name)"
"I finished making my wish... I hope it comes true someday." Hinting at wishing for herself and player to be in the same reality.

There are also a few random things I found on 11:11 wishing that maybe Monika might find interesting enough to comment on randomly after the first 11:11 dialogue.
"If you look at a clock at exactly 11:11, and have not checked the time since before 11:00, then you can make a wish. Once your wish is made, look away from the clock immediately."
"At 11:11 AM, you have to wish that the wish you make at 11:11 PM will come true. This is a very important step called “pre-wishing.” If you fail to pre-wish your evening wish, it either won't come true, or the exact opposite of what you wish will come true."
Not sure if these are factual? But it might be worth looking into if anyone is interested!

**Comment by multimokia** [comment]
While it's a cute idea, it's not really feasible with the current event system. Putting things to happen at *exactly* the right time is pretty much impossible as things depend on the random chatter timer. This means that it's possible to be slightly off, or not show at all if you're mid topic during the trigger time (since it'd basically be a one minute window).

As well, the event system isn't really built for events to repeat at any frequency other than yearly.

**Comment by PiperPC** [comment]
I don't really think it's worth making the 11:11 event happen every 12 hours? I just felt maybe it triggers once around 11AM or 11PM, and then some random dialogue after becomes available. I felt that would be a more lenient and doable thing but It's alright if it's something that wouldn't work at all.

The thing is, it's definitely too strict for a 1 minute trigger window, and it's even more strict to have that occur twice every single day. Which is why I think of it the way I do, that way it's way more lenient and be a singular one off event that makes some extra random chatter available. Maybe manually triggerable dialogue available in the menus, even.

**Comment by ThePotatoGuy** [comment]
As multi mentioned, triggering something to show at a specific time is not supported with the Event system. Events are designed to be async in that if a trigger condition passes, the event will run but you just don't know when exactly. This keeps the system stable as we can expect that certain code flows will not be interrupted.

However, an 11:11 specific topic with a decent amount of custom conditional resetting and start of topic guardrails could be done to avoid it from being shown at wrong times. Can't say its worth it though.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
