### ISSUE TITLE
Adding / auto-Detecting holidays

### ISSUE THREAD

**Issue by KiRyX112** [Monika-After-Story/MonikaModDev#5402]
I don't know if there was such a topic. 
But I wonder if you can add the ability to determine holidays based on the country of the player, this can be done by IP address, but it seems that not all IP displays the country, especially the city. Then you could tell Monica where you live, and she would ask about holidays from the database and suggest adding them to the calendar. Of course, this option is much more time-consuming than the first one)

**Comment by Rai99** [comment]
Custom Events: #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3832, #3921, #3933 

Telling Monika where we live: #2505, #2953, #3804, #4020, #4808, #4826 

Custom Calendar:  #1740, #1771, #2078, #2257, #2384, #2647, #2811, #4596, #5058 

Having a list of potential holidays is one thing, since there's probably a lot, but there's no way we could have content for all of them. Sure, maybe having it on the calendar and acknowledging that there's something on a particular day might be enough, but having a custom calendar system should be good enough to allow people to add in any holidays or events they want.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
