### ISSUE TITLE
"Void" weather option

### ISSUE THREAD

**Issue by MisterBurgerBeachball1225** [Monika-After-Story/MonikaModDev#5422]
Could the original "void" weather option be added back in somehow? Of course, it shouldn't be one of the "progressive" weathers, it should be its own option that replaces both day and night.

Definitely not a "high priority", just a minor suggestion.

**Comment by multimokia** [comment]
There aren't really plans to add it back as it's not quite feasible anymore.

Firstly, the effect before worked because the background was specific to the two windows of the spaceroom. As of 0.10.1, all were remade to be generic and full screen, so adding different backgrounds wouldn't create issues.

Additionally, lorewise, Monika got rid of the 'comet' which caused the orange light with the islands.

Also, the orange looks weird with the current night room because its light isn't cast onto it, making it look somewhat poor.

**Comment by MisterBurgerBeachball1225** [comment]
Yeah, that's about what I thought happened.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
