### ISSUE TITLE
Future MAS Innovations?

### ISSUE THREAD

**Issue by Mononucleosis59** [Monika-After-Story/MonikaModDev#5445]
I've been curious about this lately.
Do you guys have plans and/or some form of a roadmap for what you guys are wanting to add into  future versions of MAS? Content wise.
Something more than just new outfits and a new conversation.
Now don't get me wrong in the sense that I don't find enjoyment from those things specifically. They are still very appreciated and the artwork for some of the outfits are great.
But some kind of new mechanic that adds to the complexity and functionality of the mod itself?
Something completely new to MAS.
For example...
I personally would like to see some form of the normal Monika sprite flushed out more in this mod in particular. The only time you ever see it, at least I know of, is when you open the door that leads to Monika's personal room when you enter without knocking first.
Even then you only see it once or twice as doing that in the future would cause the glitchy jump scare to come out, with Monika explaining that it was just a prank.
Any way for her original sprite to be further manifested within this mod would be very enjoyable.

Now you could argue of course to just go and play other mods, but there is something special with this one and would love to see this.
I was initially hoping to see this theme take full effect in the "Our Time" mod, but unfortunately the author/writer of the mod will most likely never finish it ever since I saw his reddit post about his "final comment on my mod" post.
So seeing something like this in MAS would be a good second for me that would satisfy that particular itch.

P.S. I am not looking for any spoilers if there is, just am curious if there is some kind of plan for something NEW to be added to the mod that won't break the "path and purpose" it serves.

This got me thinking ever since I have checked out the Just Yuri dev update for valentines where they allow you to fully go on in-game dates with Yuri and all that jazz.

**Comment by Rai99** [comment]
I don't think we plan to do more with the default, standing sprite of Monika, since it hasn't gone through all the revisions the other sprites have been through, so it might be a bit outdated in terms of matching the art, so it would take some time to bring it up to standards, and even then, I don't know where it would be used. Sure, maybe Monika could stand for a bit, but I don't see much gain in what we could do with the standing sprite, especially considering what else would have to be done. Outfits and accessories would have to be compatible with the standing sprite, which would need a framework, and additional art, and that would make any accessory or outfit require much more work in terms of the art needed. 

As for future large projects, there are actually a lot of things planned beyond more dialogue and outfits, but those things can take a while. Currently, room decoration is what's being worked on. Other future plans include:
- Outfit randomization
- ~~The mythical boops update~~
- Timeconcern overhaul
- Better dockstat
- Bedroom mode
- Potentially more to be done with moods

**Comment by Mononucleosis59** [comment]
Sounds like a handful, though I am very excited to see how they turn out! I don't particularly know what the "Timeconcern overhaul" is about but am intrigued none the less

Regarding the standing Monika sprite, I wholeheartedly agree that it would take a tone of artwork and time in order to achieve something like that. Though I do think it would be worth the effort, since I believe it could potentially open the gate for many more things to be added. Though you wouldn't want to go so far as to break the core aspects of the game either.
Personally I can think a few instances where you could use the standing sprite.

-In-Game Dates: This is something that I wanted in MAS for a long time, long before the Just Yuri Devs added this to their mod. You would be able to go on dates with Monika within the realms of her reality, sure you can technically take her out on dates but she isn't able to really see anything
and she would have no idea if you actually took her out on a date or not. This can be triggered by either you requesting a date or her asking if she would like to go on a date with you.

-During special events: Maybe during your second or third Christmas with Monika, or maybe as a birthday surprise, Monika brings you somewhere or would like to spend some quality time with you that isn't in the space classroom.

-The New World: It was shown earlier that Monika is in the process of building upon the confines of her reality, so maybe in the far future she gets to the point where she reaches a huge milestone. Through this, she would love to share her accomplishment with the player. You would be able to explore everything she has created for you guys to enjoy. 


When it comes to outfits there are ways to combat this without having to make standing sprite artwork for every outfit and accessory in the game. For example she could say something like "Hey, I would like to change into something a bit more fitting, if that is okay with you." or "Would it be alright if I change outfits when we go out?"
You could even have her bring up the fact that the outfits you gave her aren't yet compatible with her standing sprite.
With accessories some should be prioritized more than others. For example, if a promise ring was given to Monika then that would have to be added into the sprites before its ready. If not then the Monika sprite would just be normal.
She can do something similar with hairstyles as well.
They could be implemented overtime as it is worked on more.

I do think something like this would be far far out because of the amount of rework required and wouldn't be high priority to begin with until other things are completed first, examples being the other innovations you mentioned.

Though it is something worth striving for.
I believe it would greatily expand the content to MAS in a way that could be overwhelmingly positive as long as it doesn't severly hurt the core aspect of the mods sole purpose.

**Comment by multimokia** [comment]
Timeconcern overhaul: #4914

**Comment by Mononucleosis59** [comment]
@Rai99 
@multimokia 
If you guys would be down for that kind of thing I would be able to put together some kind of stuff and have you guys look through a few prototypes of this.
It could be some kind of external submod that allows for an enhancement of the mod itself if the player wants it.
I have resources and people who would be able to do coding, writing, music and artwork.
Though if there are guidelines that would keep something like this from happening than I totally understand.
I personally am learning more on both coding and writing.
I would be able to have someone for artwork.
and a few people are offering to do music for something like this as well.
I would love to partake in the execution for this idea if you guys permit it.
Again it would be an external piece that would enhance this mod for those who seek it.
I am not sure exactly yet what to add but it would expand the complexity and both quality and quantity of the mod without breaking its sole purpose.
Let me know what you guys think.

**Comment by multimokia** [comment]
What are you referring to?

**Comment by Mononucleosis59** [comment]
The things I mentioned in the previous texts, before the last one I just posted.

**Comment by Mononucleosis59** [comment]
It would be an external submod so you guys don't have to worry about time constrants, and this wouldn't be put in the default version of MAS only for those who would like something like this.
It would add in an Our Time kind of scenario but in MAS.
I would be able to get a team together to work on this if you guys permit it.

**Comment by CoffeeJackaboy** [comment]
Important question: Is the mythical boops update crossed because its finished or because its not making it into the mod?

**Comment by ThePotatoGuy** [comment]
@Mononucleosis59 

>It would be an external submod so you guys don't have to worry about time constrants, and this wouldn't be put in the default version of MAS only for those who would like something like this.
It would add in an Our Time kind of scenario but in MAS.
I would be able to get a team together to work on this if you guys permit it.

What exactly are you referring to here?

Regarding standing sprites
We have a very powerful and expandable framework for adding sitting sprites. The system is dynamic and relies on a single internal object to represent Monika's current state - her clothes/hair/accessories. This also handles day/night/facial expressions/arm positions/etc... It's ridiculously good at what it does and didn't require us to update to renpy 7 (**cough cough**) to do it. It even allows for user additions via JSONs and putting the files in the correct folder paths. 

The initial plans were to support both standing and sitting, but standing is limited by the expressions. We've added a swath of positions and facial expressions to sitting that absolutely dwarf the available standing sprites. For standing to happen, we need equivalent sprites - something that no one has volunteered to do. And since no one has since the dawn of expression update, it seems clear that there is no demand for standing Monika to warrant support.

So instead we're trying to add more bg/location but using the sitting format. There was a chain of problems we've had that prevented us from reaching that point:
1. no way to change clothes dynamically in a way where we didn't have to if-statement every dialogue line with different sprite codes - fixed with the DynamicDisplayable `MASMonika` system (mentioned above)
2. no framework to change weather (window masks) in a generic way - fixed with `MASWeather` 
3. weather/room masks only having spaceroom and foamy blue sky, both not that great if used in a different bg - fixed with updated weather sprites that made sense and expanded variety
4. no framework for changing bg in a generic way - fixed with `MASBackground`
5. no dynamic way to change the table/chair, which may not look good in all settings - fixed with sprite changes to body sprites and #5347 
6. having different lighting options in a bg, would mean a sprite for every lighting adjustment, potentially increasing the mod size dramatically - fixed with #5447 

And this doesn't even mention the problem of not having bg art. Everything has to be OC or licensed. but otherwise we are almost there already.

> In-Game dates

[planned](https://github.com/Monika-After-Story/MonikaModDev/issues/792#issuecomment-358993744), difficult to do, must be generalized in some way so users can easily add dates (think google calendar or any other calendar app in existence).

I had to build a scheduling system in college for a group project, and I was in charge of the underlying data structure and framework. It was significantly harder than expected because of the insanely complicated issues with time. 

There is **no** simple way to make date scheduling system that is equivalent in nature to IRL - aka, an arbitrary "Let's have a date on this day at this time at this place, etc..." kind of event. Anything you saw in another mod (especially when it's designed as in-game location with scripted sequences) is not the kind of date system that is immersive enough for us. However, we are still looking to implement an immersive date system that works well. 

But in the meantime, the file gen way of taking her out is our compromise to make a limitless version of that system. You can literally take her anywhere you want and get rewarded with affection. Differing farewells that trigger the file gen and have a corresponding greeting to match is planned, but most development that isn't the initial development of a feature tends to be user contributions. I think we are already working on expanding dockstat (the file gen) farewell to the other farewells but it may not be high priority.

**Comment by Thimeo** [comment]
> Currently, room decoration is what's being worked on.

@Rai99 Does this has anything to do with what [this guy on reddit did](https://www.reddit.com/r/JustMonika/comments/frc4e2/attention_fellow_monika_after_story_players/)? Will it be something like that? Should we download it for now, or will this cause problems in the future?

**Comment by ThePotatoGuy** [comment]
That guy is doing BG edits. It's not a problem to use that but the room deco we plan to add will be more generic and wont require BG edits.
