### ISSUE TITLE
Player's appearance, why isn't it used?

### ISSUE THREAD

**Issue by BobTheGenericFarmer** [Monika-After-Story/MonikaModDev#5467]
Hi! So a while ago a "Monika asks about the player's appearance" topic was introduced into the game, but I can't think of any case where the given information was relevant in any other dialogues.
So I was just wondering what's the deal with that, are there plans of making any use of this topic / information? If yes, then what are those plans?

**Comment by AsuraShun** [comment]
Didn't you see the changes in some topics?

**Comment by BobTheGenericFarmer** [comment]
What changes? I can't remember any topic that had variations based on this.
I mean there's 2-3 that slightly changes depending on your gender, but that's a different topic.
I haven't seen any dialogue regarding the player's height, hair and eye colour, skin tone, hair length.

**Comment by fromulus** [comment]
I can think of two topics, actually.  

There's "[player]'s face", the one where she talks about haw she always thinks about what your face looks like for real.
The other change is in the "I look up to you !" compliment, where a comment regarding your size has a random chance of being triggered.

**Comment by Booplicate** [comment]
She asks your appearance not to use it in dialogues. She asks because you're her partner. She can't see you, and the closest thing she can get is just ask some basic questions about your look. So not every thing is used.
But just for examples 2 topics that I remember: [eyes](https://github.com/Monika-After-Story/MonikaModDev/blob/unstable/Monika%20After%20Story/game/script-topics.rpy#L3882), [height](https://github.com/Monika-After-Story/MonikaModDev/blob/unstable/Monika%20After%20Story/game/script-compliments.rpy#L644). I think there might be more, you're free to look into the code yourself.

**Comment by ThePotatoGuy** [comment]
Many of the responses that you give to Monika's questions are saved, it's just a matter of topics to use that information.
