### ISSUE TITLE
Suggestion:covid 19

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#5469]
Remember the ''what if I came into your world'' question you can ask monika? What if one of the possible answers was us telling her about the virus instead of it being its own topic?

**Comment by LittleSaltFish** [comment]
reference:#5430 #5456 
I don't think add these time-related event is a good idea.
Because MAS is a long term project. We need to modify the content frequently if we join these time-related events.And I think it is troublesome.
But in my opinion we can still talk about these in other forms(at least not in the form like discussing the news)(≧∇≦)/

**Comment by ThePotatoGuy** [comment]
We don't plan to do anything with coronavirus than we already have.
