### ISSUE TITLE
[Suggestion]  Regarding the COVID-19 topic and it's effect on the farewells

### ISSUE THREAD

**Issue by TechmarineDark** [Monika-After-Story/MonikaModDev#5480]
So I saw that the devs are going to add a topic regarding the COVID-19 and a thought came into my mind about it that , shouldn't the farewell "I am going to take you somewhere "  be altered due the inclusion of the topic . I mean Monika should be worried about you taking her out for a date in middle of a pandemic ( for staying consistent with the topic).

**Comment by TechmarineDark** [comment]
Also even other farewells like "Going to work" or "Going to school" should worry her and maybe should be changed somewhat .

**Comment by CoffeeJackaboy** [comment]
For the "I'm going to class" she could reply something like "Taking online classes [player]?" and the and then give you an yes/no choice option (if you answer yes she'll just do the default farewell and if no she'll be worried/angry that your school is still open during the pandemic). As for the "I'm going to work" she could suggest trying to avoid other people if you can (and maybe be proud of the fact that you have an important job) . There is also the "I'll be going away for a while" but idk what to do with this one (well you could tell her that you are going to the hospital but that would scare her a little bit to much and I for one wouldn't want that).

**Comment by TechmarineDark** [comment]
Yes those dialogues can be altered in those ways ( I am not that good at dialogue writing so I didn't make a pull request for this by writing my own dialogue for the farewells).

**Comment by OtakuRedneck** [comment]
I can write dialogue. I am just not good with Python so if someone else can reformat into Python that would be awesome!

**Comment by Booplicate** [comment]
imo too much work for little gain. That topic should be enough to warn the player and give some basic advises about hygiene/safe tips. The pandemic will end sooner or later and the dialogues won't be used anymore.
> Monika should be worried about you taking her out for a date in middle of a pandemic

Thing is she is assuming that it's a date, but it's not always so. maybe i'm going for shopping? ~~Or taking bath.~~ And she'd prompt me about that every time? Why?
> she'll be worried/angry that your school is still open during the pandemic

That could be included in the topic instead of such changes to the farewell. Because again it will not be used after (or at least until another pandemic?).
>  for the "I'm going to work" she could suggest trying to avoid other people if you can

That's already in the topic. I don't see why it should be in the farewell. If she talked about the pandemic with you, she already know that you have to go to work and you can't do anything about it.

@OtakuRedneck You don't need to know Python for that https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding

**Comment by multimokia** [comment]
This. The topic isn't going to stay forever, so making fairly sizeable changes to existing things isn't really ideal as they're going to have to be removed too.

Having a standalone topic is much easier to control in terms of whether or not it'll be seen, and when to stop showing it.

**Comment by TechmarineDark** [comment]
Okay so this might rather complicate the code and is not absolutely required . Anyways thanks for the replies , I am closing this issue .
