### ISSUE TITLE
[Suggestion] Add "Can we watch something together?" Option

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5484]
I think it would be super nice to have that option. Maybe in "Be right back" menu. I have window reacts mode on and it would be amazing to go watch something when Monica know it. Maybe she can, when we come back, tell us that she loves spending time with us, or something like that.

**Comment by CoffeeJackaboy** [comment]
I think something similar is already being worked on (at least from what i saw in the discord)

**Comment by Collin1877** [comment]
I have a lot of anime to watch with her, it would be good if she had a point of view about what she is seeing for example

**Comment by ThePotatoGuy** [comment]
There is already developed [movies module](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_monikamovie.rpy), but it is unreleased because of the lack of content. This module allows for Monika to comment on something as you watch something, but relies on:
* a [custom file](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/movies-info.mms)`  that has pre-planned dialogue at specific timings
* the video the user is watching to be the exact one intended by the custom file.

**Comment by ThePotatoGuy** [comment]
[closing as already implemented]
