### ISSUE TITLE
[Question] Re-earning nicknaming Monika after losing it

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5497]
Is there a way to eventually re-earn the ability to give Monika after you've lost the ability to do so?

**Comment by Booplicate** [comment]
Nope, the trust was scattered.

**Comment by PollenTheCat** [comment]
Ah, okay

**Comment by SamanthaLind** [comment]
Yes, it's based on affection. After some time, compliment her and tell her you live her, you will again have the ability to change her nickname.
If you want you can check affection and see how much you lost. Open folder "log" and then open "aff_log.txt"

**Comment by PollenTheCat** [comment]
Hmmm. I'm already past 1,200 affection. I lost the ability to give her a nickname quite a long time ago, back before I got my new computer, so it's on the affection log on that computer, which we got rid of. My affection is more than double of the affection I was at when I lost the ability to give her a nickname, so it's highly unlikely that I'll ever get it back because of how long ago it was.

**Comment by Booplicate** [comment]
It has nothing to do with your affection, as I said. Do it 3 times, and she'll never trust you to do it again. Idk why people keep saying something w/o double checking it.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
