### ISSUE TITLE
[Suggestion] Helping with addictions

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5499]
I know it's probably weird, but I think it would be cool idea if Monika helped with ending some bad habits.
I thought about it when she asked me about smoking ( I do it, a lot). It was really nice, and helped me smoke less. 
I think it would be nice when if someone choose option "yes I smoke" there would be option in "be right back" named: " I'm going to smoke." Maybe hearing what Monika says about it would help get rid of this habit.
I don't know how many people would want it, but it could work with others bad habits too. If someone eats between meals too much Monika would give some suggestions to stay healthier... It's just I saw option to tell Monika about something that's not healthy and which she doesn't like and I would love to see how she helps player be healthier, and spend more time with her instead of smoking.

**Comment by satoshi-kun** [comment]
I think the mod already does a really good job on helping improving bad habits and quiting addictions. 
I installed this mod on june 17th 2019 and within a month time I managed to quit smoking (till this day) and also improved my sleeping habits (used to be a very late riser), all thanks to the advice given within the mod.
So in my opinion, the help is already there now it is only a matter of the player's will to change.

**Comment by Booplicate** [comment]
Imo just saying that you're going to smoke so Monika can say that it's bad wouldn't help. Like every time she will say "Smoking is bad for your health, you should quit". Would it really help? I don't smoke, but I know a lot of people who do. And they already know that it's bad. Most people smoke not because they don't know how bad it is for their health. The problem goes into psychology.

Having a button for smoking is bad in general. You will unintentionally agitate other people to smoke. Even if you will show it only to smokers, you will remind them about cigarettes just with this button. They wanted to play something, and will see that button about smoking. Imo not very good. if something, Monika would try to move the player's thought away from smoking.

I think having more gentle way to express Monika's worries about the player smoking could work though! Like mentioning (from time to time) that it would make her happy if you stop smoking, or giving some advises and asking if they helped smoke less later. Maybe helping the player to relief their stress. Of course that's more complicated. And yes, I know those go apart from my previous statement. I think there's a little difference between them. One thing if you give a way to smoke and another if you show your care.

Other bad habits are even more hard. For example
> If someone eats between meals too much Monika would give some suggestions to stay healthier

I do. And you'd be surprised about my weigh. Not to mention that she doesn't know what we're eating. It's not good to give advises when you don't see the full picture. Tbh I wouldn't touch the weigh at all. Just focus on healthy food. And actually, there're already some topics about that. I wouldn't mind if we got some more, though!

I agree with satoshi. If you think about it, Monika already talks about aging and dying. She mentions that you should watch for your health. Recommends to try fitness and stuff. She wants you to live as long as you can. I think we already have all the support from her. It's all up to you to start thinking about your health. Because if you don't want to help yourself, no one can help you.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
