### ISSUE TITLE
[Suggestion]-lunar calendar birthday

### ISSUE THREAD

**Issue by AEjixing** [Monika-After-Story/MonikaModDev#5531]
MAS is my favourite game.Now I have a suggestion
In China, people celebrate their birthdays according to the lunar calendar, so I suggest that monika can change my birthday.

**Comment by AEjixing** [comment]
Why do I want monika to change my birthday? Because every year, the time corresponding to the lunar calendar and the Gregorian calendar are different. Today is March 21st of the lunar calendar, and the corresponding Gregorian calendar is April 13. Then, March 21st of the next lunar calendar is September 2nd of the Gregorian calendar. This requires the date to be calibrated at any time.

**Comment by ThePotatoGuy** [comment]
Marking as low priority as this would be pretty difficult and janky to do. Likely would need to add more birthday dialogue to reflect a lunar calendar bday.

**Comment by AEjixing** [comment]
Don't need to add more birthday dialogue,I just need to change my birthday date.

**Comment by AEjixing** [comment]
> Marking as low priority as this would be pretty difficult and janky to do. Likely would need to add more birthday dialogue to reflect a lunar calendar bday.

Don't need to add more birthday dialogue,I just need to change my birthday date.Just jike change my name.

**Comment by ThePotatoGuy** [comment]
There is a lot of code that runs days before and after birthdays which is why we avoid letting users change their birthday after the first time. Additionally, we save data related to what you did on your birthday on a yearly basis, and since lunar birthdays could happen twice a year, that data would be overwritten.

In general, birthdays are treated as yearly holidays and we have built them with that expectation, so changing them to work non-yearly requires significant effort.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
