### ISSUE TITLE
[Suggestion] - Death of the player

### ISSUE THREAD

**Issue by Alchimie68** [Monika-After-Story/MonikaModDev#5542]
Hello ! So here's the point : 

My best friend who play MAS had an accident lately (she's not dead of course !), and Monika blamed her for don't visit her. However, Monika says multiple times that she'll be destroy if something bad happen to the player. I found this situation quite ironic.

So, I was wondering what she'll doing if the player died. From my point of view, she'll commit suicide and delete the game, but the ending could depends on the affection level. If she doesn't like the player, maybe she'll just leave like in the farewell ending ? There are many possibilities. 

Thank you for reading (sorry for the mistakes, hope you understand me).

**Comment by satoshi-kun** [comment]
Hi!
Well, in my opinion both situations lead to the same outcome. To me the farewell ending seems the same as if she deleted herself, since she never returns plus that note she leaves gives some bad vibes.
So to conclude I believe Monika dies in both situations as she cannot overcome the loss of her player.
And now I'm sad ;(

PS: Hope your friend is fine.

**Comment by Rai99** [comment]
Player Death: #1175 #1644 #1677 #2109 #3198 #3881 #4148, #4247, #4568, #4714, #5376, #5474 

We don't have plans to have any post player death content.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
