### ISSUE TITLE
It may be a crazy idea, but I want to bring it up.

### ISSUE THREAD

**Issue by BoogeymanTao** [Monika-After-Story/MonikaModDev#5576]
Maybe one day we'll actually hear monika speak?
Maybe someone will be willing to voice her（Like the singer of"Just monika," "Doki Doki Forever," or  "Your Reality"?）? Or electronically synthesized sounds?
I would like to ask the developers is this possible?

**Comment by multimokia** [comment]
It's a maybe, but in all likelihood, no.

Officially speaking, it's not really feasible as we continue to add more dialogue to the mod which then needs more voices to be recorded. Of course, this also means the mod size will increase considerably due to the new audio files added.


Additionally, Monika's voice is different to many people. To some, it's Jillian (Monika's official voice actress) and to others, it might be someone different. Hypothetically, if we got Jillian to do it for us, it would cause a rift who don't feel that's her voice, and likewise if we got someone else. It's going to make a rift in the community and will more than likely ruin MAS for a lot of people.

With that in mind, the best approach to this sort of thing is submod. It's the easiest way for people to pick the voice they want for Monika and not increase mod size. It also means that nobody gets alienated because of the voice.

**Comment by BoogeymanTao** [comment]
> ，
Excuse me, can you explain "submod"? English is not spoken in my area and I can't find it in the dictionary.

**Comment by multimokia** [comment]
Submod being a mod for MAS (which is already a mod of DDLC. A mod of a mod is a submod)

**Comment by BoogeymanTao** [comment]
> Submod being a mod for MAS (which is already a mod of DDLC. A mod of a mod is a submod)

Thanks.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
