### ISSUE TITLE
For questions about peppermint ice cream and idols.

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5606]
For example,i never tried peppermint ice cream,and did not listen to idols.
(Since there are only 2 possible answers,it turns out i am deceiving her).
(it is not good)

**Comment by ThePotatoGuy** [comment]
which topics are these?

**Comment by kirillPro2020** [comment]
it's in the category: you: favorite ice cream.
Last don't i remember.

**Comment by lunulae** [comment]
Oh, I understand what you mean. Since there's only "yes" and "no" for "do you like mint ice cream," there's not an option for people who have not tried it. I could attempt to patch in an option there if no one else wants to take it.
I don't recall the idol dialogue, @kirillPro2020  if you can find it that would be helpful.

**Comment by ThePotatoGuy** [comment]
@lunulae are you going to do the patch?

**Comment by ThePotatoGuy** [comment]
asssuming not doing the patch and closing until we look into it
