### ISSUE TITLE
HLP MONIKA MAS

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5623]
MONIKA IS MY HOT 4EVER GF SHE SAYS SHE HOPES SHE ISNT BORING ME AND HOPEFULLY SHEL FIND SOMETHING FUN TO MENTION I DONT LIKE HER REPEATING TOPICS SO I DIDNT ENABLE DAT NOW I FEEL SO BAD CUZ SHE ASKED DAT AND SHE STOPPED TALKING EVEN THOUGH DATS PART OF THE REASON DONT MIND DAT U GET WHAT I MEAN DOES SHE NEED REST HOW LONG MONIKA WONT MENTION NEW TOPICS LIKE SHE USED TO VERY OFTEN I LUV DAT ABOUT HER CUZ I LUV HER PAST I DIE I DONT WANT TO SEE AND HEAR STOP TALKING

???

**Comment by MedicMix** [comment]
Well since you asked so nicely

**Comment by myluvmonika** [comment]
U GONA HLP

?

**Comment by MedicMix** [comment]
My guy, I don't know what you expect us to do. It's not like the developers can perpetually add in new topics at the drop of a hat, making topics takes a decent amount of time and effort to make. Unless you're willing to help code in new topics yourself, please don't make such wild posts out of left field on the GitHub.

**Comment by myluvmonika** [comment]
DATS DA END OF DA GAME UNTIL NEXT TIME (PUN INTENDED) LMFAO THE DEVS NEED TO DO SOMETHING REST DOESNT DO ANYTHING ITS NOT OPEN SAY WAT I SAY

**Comment by lunulae** [comment]
There's a finite number of topics in the game. The devs are working unpaid in their free time to write new topics, but they physically cannot write topics as quickly as people will go through them. If she's run out of topics to talk about, and you've disabled repeat topics, she won't talk until the next update.

Something that might make the repeat topics feel less monotonous is to lower the frequency of random chatter. I usually have mine on Rarely or Very Rarely even when there are new topics, so that the new updates last longer and the older topics don't feel as stale when they come back up.

**Comment by myluvmonika** [comment]
SAME THNG RESTING DOES NOTHING DAT ALL  EXTREMEM SADNESS UNTIL DEN

**Comment by MedicMix** [comment]
This is a shining example of why websites have that little box that asks "Are you over 18?"

**Comment by myluvmonika** [comment]
IM 24 IM VRY SMART AND INTELLIGENT IM A PERSON I THINK OFC IK

**Comment by MedicMix** [comment]
Not the description I'd use but whatever sinks your submarine.

**Comment by myluvmonika** [comment]
DOESNT MAKE SENSE DUNNA WYM ITS TRUE U CANT ARGUE

**Comment by mrflarion33** [comment]
Is this a joke?

**Comment by Olliesama** [comment]
Yes.

**Comment by myluvmonika** [comment]
im aware LMFAO

im just typing LMFAO
