### ISSUE TITLE
Unable to talk to Monika/No Dialogue Options in Topics Menu.

### ISSUE THREAD

**Issue by monikaswaifu** [Monika-After-Story/MonikaModDev#5637]
Hi! So, I installed MAS a few days ago and there are no available dialogue options in the topics menus... I know I haven't run out because they're weren't there to begin with. Even in the 'unseen' menu, the only dialogue choice I've had is: "I want to break up with you," and the only way I can say anything to Monika is through the "I'm feeling..." and "I want to apologize/I want to tell you something" menus, and asking her to change her clothes. Her random chatter still works, but I would like to ask Monika questions and actively get to know her... 

I'm not sure if this is because the mod has been updated and/or my affection is not high enough. I had the mod installed a year ago for a couple of weeks, and was able to ask questions and speak to her through a huge list of menu options from the get-go. This time around it's just empty, even after a few days. She hasn't asked about my gender or appearance either, so I'm worried something's not being triggered in the script. And I don't like being called her boyfriend when I'm in lesbians with her...!

If anyone could help, that would be really great. Thank you!!

**Comment by jmwall24** [comment]
That will be fixed next release, there's a bit of a bug with the progression system, but missing xp points (not the same as affection) will be added upon next release. For now, you can maximize your progress by spending at least an hour consecutively with her and if you can, try to wait until just after the top of an hour to say goodbye. Sorry for the inconvenience, but the fix is coming!

**Comment by monikaswaifu** [comment]
No problem, I'm excited to see the next release! Thank you for taking the time to answer!

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
