### ISSUE TITLE
[SUGGESTION]  Caresses for Monika :D

### ISSUE THREAD

**Issue by katbooo** [Monika-After-Story/MonikaModDev#5710]
the possibility of giving caress to monika :D

**Comment by Rai99** [comment]
You mean something like _boops_?

**Comment by katbooo** [comment]
> You mean something like _boops_?

Yup :3

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479.

**Comment by Rai99** [comment]
Thanks for clarifying. 

Boops _are_ planned to be done at some point.

**Comment by katbooo** [comment]
> Thanks for clarifying.
> 
> Boops _are_ planned to be done at some point.

YAY

**Comment by SuperSuchti** [comment]
> 
> 
> Thanks for clarifying.
> 
> Boops _are_ planned to be done at some point.

What about headpats?

**Comment by AsuraShun** [comment]
Headpats are implied when you talk about boops

**Comment by drakesteele** [comment]
Yes, I second the motion for boops and headpats... at some point perhaps since you can eventually kiss and hold her, how about a 'hand-holding' as well where you can ask and she puts her hands on the desk and you can hold the mousebutton/press the touchscreen on her hands and hold them for a bit and she'd react similar to the holding thing, where the longer you do it the more she comments on the warmth of your hands and such.  :)  Just think it would be cute.

**Comment by AsuraShun** [comment]
Speaking of hands, I'm still wondering why her hand was reverted back to the look that makes it look like she's broken her arm

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
