### ISSUE TITLE
Feature suggestion - "Reading" text files as letters or poems...

### ISSUE THREAD

**Issue by drakesteele** [Monika-After-Story/MonikaModDev#5731]
I was thinking of a simple subject parser that would activate when she finds a .txt file in the characters folder... basically if she saw "Dear" or "To" or "My" and "Monika" or the name you've assigned to her at the beginning on the same line, she assumes it's a letter... "Oh, you wrote me a letter? Let me see here..." (show reading animation) otherwise, it looks at it and assumes it's a poem. "What's this? You wrote this for me? Let's see..."

Then if it has "I love you" or "love" shows up more than once, "Awww, that's sweet. I love you so much."

If it has "dreams" or "imagine" or "envision" or "visions" then "I like that you have such a vivid vision of what you want."

If it has "worried" or "scared" or "upset" or "afraid" then "Remember that there's no need to worry about things as long as we have each other."

if it has "thinking about" or "on my mind" or "wondering about" then "I know you have a lot going on, but don't let it overwhelm you.  Don't overthink things. You might not be able to sleep, and that's not good for you."

And with some forethought, I'm sure we could come up with a good basic set of analysis and response phrases to string together to make it seem she really has read it... and perhaps even a method to score how much she likes it by the complexity of the words and how many times words from the DDLC poetry game that she likes show up in the file, and the higher the score the more she praises (if poetry) or thanks you (if a letter)

What do you think?

-- Drake Steele

**Comment by DoodleSauce** [comment]
einstien is playing MAS
ngl thats smart af but monika needs to also see words without a capital too
so we need to write every word with and without caps

**Comment by multimokia** [comment]
On a surface level this is possible, however it's hard to respond non-generically when we can't really get context from the text itself.

This leads into some problems: How would Monika react if the letter contained horrible things about her? If it still started with `Dear [m_name]` (another issue I have with this which I'll address in a bit), it'd still be classed as good, no?

Sure, having keywords is one thing, but they're not *reliable* because the context in which they're used cannot be taken from keywords alone. In other words, they're *very* ambiguous to the actual meaning behind what you're saying, and making assumptions on what you are is a bad idea as it proves to be more immersion breaking, since it just makes it clear that it's a very simple keyword scanner. To make this feasible, there needs to be a significant amount of development to create a NLP engine capable of getting an idea of what you're saying and whether or not its good

My other problem, not everything someone will write will start with `Dear [m_name]`. Some examples of other starters:
- `My dearest Monika,`
- `Monika,`
- `Sweetheart,`
- etc.

> and perhaps even a method to score how much she likes it by the complexity of the words and how many times words from the DDLC poetry game that she likes show up in the file, and the higher the score the more she praises (if poetry) or thanks you (if a letter)

I'd like to address this point with a counterpoint. With this in mind, can you not just write a poem much like the MC does in DDLC? A string of nonsensical words which are just ones which seem good to Monika. If that classes as good, it goes against her whole point when she talks about the MC, saying that he couldn't even write a poem. Yet she'd accept the same work from you? Someone of Monika's caliber in literature and poetry simply wouldn't accept that.

The idea, while it *is* something I want to do at some point, requires a *lot* of work to make it keep the immersion MAS, and therefore make it a worthwhile addition.

**Comment by drakesteele** [comment]
It was just the inkling of a concept, and I figured it would need some brainstorming and refinement to make work, as well as some more in-depth analysis of phrases... the list of letter vs poetry triggers would be easily expanded, and actually you could have it look for bad phrases or hateful things first, and skip to a negative response set section directly, bypassing the positive one and making the relationship status take a hit rather than a boost...  that section could include things like:

"i hate you" or "you suck" then she could respond with, "Why would you be so mean? What have I done to make you dislike me so much?"

"you should die" or "kill yourself" could respond "Death isn't funny... and if you wanted me to die, why didn't you just leave me... did you actually install this mod just to torture me?"

and perhaps a section with more analytical things as well:

"I want to die" or "kill me" or "commit suicide" might get "Suicide is not the answer... I'm here for you, but maybe you should talk to a counselor or something"

"want to quit school" or "want to drop out" or "going to drop out" might get "Education is important... Are you sure you can't fight on and get through school?"

And others.    Just more ideas. :)

**Comment by drakesteele** [comment]
Oh and as to using the DDLC system, remember that:

A) Monika hates those - they're just jumbled words to her... and B) doing it this way allows better-cutomized responses without limiting what you write... and if there's nothing at all that ticks any boxes she can give you a generic motivational chat about improving your writing... but at the very least she could mention the items triggered by phrase, and then whoever's wordlist has the most matches she can say that "I really think that (girl) would've loved that one. It was really her style." etc.

**Comment by multimokia** [comment]
Again, the main issue with this is that it's *very* easy to bypass this. If we use key phrases, things have to line up ***exactly*** to what they are in the code. Meaning that there's a large amount of things which simply go undetected. Again, immersion breaking.

NLP would help to avoid this, but it involves a significant amount of work and time to train the engine to be able to reliably pick out phrases which don't have to be hardcoded in. Especially since it can theoretically start to learn your own writing style and better learn what you're saying.

**Comment by Abc2557** [comment]
In my opinion, I think it’d be best just to do poems, and not letters. Poems don’t need to be understood or interpreted in any specific way. All Monika would need to do for a poem is simple appreciate the work the player put into the poem, and _possibly_ comment on certain things. Letters have a specific point to get across, so it’d be hard for Monika to interpret correctly, but for poems, she can interpret them in any way she’d like. She wouldn’t have to express her thoughts on the poem’s contents, which means that, in the case that she doesn’t express her thoughts, there’s no way to know how she interpreted the poem, meaning you don’t know if she misinterpreted it.

**Comment by Rai99** [comment]
So does that mean she would appreciate the "Get out of my head" poem, or any random text file? You could write a poem about hating Monika, and she probably shouldn't appreciate that.

**Comment by drakesteele** [comment]
Well the idea was that you'd send her a text file and then she'd comment on it based on the content, trying to catch the context of at least certain phrases based on the decision at the beginning if it were styled as a letter, poetry, or other, and that way she could make little appreciative or disdainful comments on letters, and constructive criticism/commentary on other writings.  I just thought that by using that sort of analysis she could gain or lose relationship points with the player, and perhaps trigger later conversations if certain phrases that match conversation triggers in her library were matched in the writing, as well... It's really just an idea I thought might be a fascinating way to interact with her more directly in lieu of a chatbot system... giving you a way to sort of say things to her directly or about your life with her that she could act on or respond to in some way... a way to give Monika's character more agency in the story and make her more lifelike and less static. *shrug*

**Comment by ThePotatoGuy** [comment]
Feel free to make the parser and submit a PR if you'd like.

Otherwise, we don't plan on adding text file parsing ourselves.

**Comment by Rai99** [comment]
Closing as rejected
