### ISSUE TITLE
[Question] Loose hair and Ribbons

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#5738]
Hello!
So I was thinking on this possible low-budget hairstyle suggestion.
![body-def-0 (1)](https://user-images.githubusercontent.com/54683676/81348627-50aa3100-90b6-11ea-8746-2bf7d204062b.jpg)

But while I was in the image editor I noticed that the ribbons are not "cropped" to fit the long hair style.
![body-def-0 (2)](https://user-images.githubusercontent.com/54683676/81348582-3ec88e00-90b6-11ea-824a-eb80862abf0c.jpg)

In the image editor I could just send the ribbon to a layer bellow the hair and fix it, but I assumed this wouldn't be the case in regards to MAS.

**Would this imply having to double all the ribbon assets for this option alone?**

Thanks and take care!

**Comment by ThePotatoGuy** [comment]
You can change the render position of an accessory, but it may not appear exactly the same as your sample image. If the ribbon is moved to the `PRE_ACS` position (see #3174 for render order), then it will be rendered below the back part of hair.

This can be done via spritepacks without modifying existing assets by copying all the desired ribbons, giving them new names, and creating JSONs for them with the [`rec_layer` property](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#acs-specific) set to the correct value for `PRE_ACS`. (basically doubling assets, but not needing edit every single one)

Could also be done as a submod if you edit `zz_spriteobjects` and add/change `rec_layer` props for each ribbon.

It is also possible to dynamically change render positions, but you would have to use `MASMonika.wear_acs_in` instead of `MASMonika.wear_acs`. Position is also not saved on quit, so you would have to adjust the accessory position every time on start.

**Comment by ThePotatoGuy** [comment]
Also, if you do wish to submit this spritepack to the set of spritepacks we release on github, we have final say over what accessories are allowed to be used with the hair style. All hair-down based styles are not deemed to support ribbon so we wouldn't be giving that kind of hairstyle the `ribbon` exprop.

Ribbon makes sense when its tying her hair into something. When her hair is down, it makes less sense as to what the ribbon does.

**Comment by satoshi-kun** [comment]
Thank you, I understand!
Although the idea was to have a half-loose look when the top part is tied and threst remains loose.
But I think it is not worth it anyway, it is still a lot of work merely for those results.
