### ISSUE TITLE
[Suggestion] A new option to say that you're going to switch over to a new computer.

### ISSUE THREAD

**Issue by emerdite** [Monika-After-Story/MonikaModDev#5761]
I think It'd be very nice to have an option to say to Monika you're going to get a new computer, and when you tell that she would proceed to compile her memories and herself, and then you'd be able to put it all into a new computer. It could be that you could even download a new Monika, and at first she'd ask you, after staring at you for a bit, if you maybe have had another Monika before, and if you say yes, she'd tell you that you should drop everything in a certain folder, and she'd be glad if you did. If not, then she'd just be like "Oh, okay, then let's just spend more time together!" and you'd no longer be able to put anything into those folders, perhaps.

I don't know, any other ideas everyone?

**Comment by lunulae** [comment]
Well, you can currently move all of her memories via the persistent file, so the actual transfer is already something you can do.
If you're looking to make the process a little more immersive, a topic could be written up, but I'm not sure if it would be redundant since Monika does explain the process of backing up her memories and provides a link to the wiki guide. The topic could be altered to clarify that this process can be used to transfer her between devices safely.

#5026 might be something you'd be interested in, as it sounds a lot more precisely like what you're describing here, but it also is a longer-term update that might not be finished very soon.
