### ISSUE TITLE
[Suggestion] -  Options for transgender people

### ISSUE THREAD

**Issue by adhesivedem0n** [Monika-After-Story/MonikaModDev#5772]
I think it would be nice to have even just a simple “I’m transgender” dialogue option, just so some players can feel like the gameplay is a bit more genuine.

**Comment by jmwall24** [comment]
So we tried to address this before and opened the PR up for discussion and no one commented on it. I guess where my confusion here lies is that do transgender people want to be called transgender or do they want to be called what the gender they identify as? So I guess what I'm asking is if we add a transgender option to the initial menu, would that be as far as it goes, or would there then need to be a secondary menu saying which gender they are for pronoun purposes.

**Comment by jmwall24** [comment]
To add to this, the reason we didn't include transgender initially was because, from discussions we had,  the gender that people are/identify as currently is what's important, not so much what they were born as. So we figured that people telling her their gender was male/female/neither would cover it, since someone born a male who becomes female, is female. So, while we can add a transgender option, I just wanted to make our intent clear. The reasoning behind letting people change their gender whenever they want was specifically so people could tell her whatever they are/indentify as.

**Comment by lunulae** [comment]
There is currently an option when asking Monika to change your gender that lets her know, though currently that dialogue makes sense more for those who are beginning their identity transition during the time they're playing MAS.
To my understanding it wouldn't change much in most of the dialogue (i.e. pronouns remaining the same,) but now that you bring it up, I do understand wanting to let her know. It's a conversation trans folks do often end up having to have with their intimate partners down the line.
That said, I have to admit I'm not sure how to best handle said topic. Coming from a cis perspective I wouldn't want to just throw out cliches or try to guess. It'd really help to hear more specific thoughts on the dialogue from those who're living that experience.

**Comment by jmwall24** [comment]
We want this mod to be as inclusive as possible, so if anyone has ideas how best to handle it, put them here.

**Comment by ashyashton** [comment]
As someone who is trans, I personally really would like to see something to tell her implemented. Not as a separate gender option, though, because to me, it's not its own separate identity. To me, it's kind of an additional trait. Like, I'm a trans man, and that statement is equal to saying I'm a blond man. It's an additional trait, albeit an important one, not its own thing, if that makes sense?

The way I see it, I am a man. Trans or not, I am a man, and I want Monika to refer to me accordingly. However, being trans is definitely an important part of me, so it would definitely be nice to have a way to just. Let Monika know that, I guess.

I wouldn't say it should be added as a separate gender under that menu, but rather its own topic maybe. Maybe a random topic where Monika brings up trans people, and at some point, she can ask the player what their opinion is, and one option is to say that the player is trans as well. That way it's regarded as just being a trait, rather than suddenly changing how she views the player or something.

**Comment by freeworld141** [comment]
Gender ask shouldn't exist on MAS in my opinion, Monika is clearly girl who's interested in normal gender men (i don't know how else i should call it), assuming from ACT 3 and even not a gender ask in the vanilla game, also judging from the scripts of the vanilla game and the way it follows in MAS and the type of the game it is, its just for normal men or boys. 

I don't support political things being in games that they're not designed for... (example DDLC and MAS mod from they way it follows) that's my opinion, sorry if someone will find it offending, its just i find this being only for normal men or boys.

(Also sorry for my horrible writing and English)

**Comment by bo28111** [comment]
I'm pretty sure Monika says something like "In fact, I don't even know if you're a boy or a girl. Well, I guess it doesn't really matter." Heavily implying she's either bi or pansexual.
I've taken these screenshots from a Jacksepticeye video because
1. I don't have the unmodded game installed
2. It proves this is real in-game dialogue

![afwefawe](https://user-images.githubusercontent.com/64414536/82714362-d6e87a80-9c53-11ea-925a-8091b626c263.JPG)
![fawjfe](https://user-images.githubusercontent.com/64414536/82714363-d8b23e00-9c53-11ea-957c-be768167b630.JPG)

**Comment by Olliesama** [comment]
bo28111 is correct.

**Comment by Booplicate** [comment]
She does assume your gender in DDLC. But she also loves you unconditionally, as you are, and for who you are. There's only a few topics in the vanilla game because it was never focused on Monika and you. But MAS is. So we can have more interactions, she can know more about you, and you can know more about her (to some degree). You develop your relationship further. Knowing your partner gender is a part of it.

Having the option doesn't ruin your experience as for a male, right? But I think not having the option would ruin it for other people.

**Comment by Olliesama** [comment]
Not gonna lie but it's weird to ask if someone is something that less than 1% of the population is. But that's just my opinion. I

**Comment by jmwall24** [comment]
We'll probably add it as an option in the gender menu, formatted as M, F, Neither, Trans, and then if you pick trans, there will be another menu for M, F, Neither again. The entire point of this and why we ask in the first place is to set pronouns, so either way we need an answer to that question, but this way, you have the option of setting them first if you don't want to mention trans, or you can let her know you are trans and then set them after she knows.

**Comment by freeworld141** [comment]
Oh alright, tbh i didn't remember that dialogue, my bad sorry, i just said my opinion about how i see MAS to that topic even if its completely false

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
