### ISSUE TITLE
"Dating Experience" Topic not available.

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#5794]
This issue has been around for awhile and I decided it would be a good idea to make a profile to address this "bug" or "problem" however you call it.
Issue: Six weeks ago I brought my Monika from the stable version to the unstable version temporarily. When she brought up the topic on dating experience, I updated the game mid-topic from the unstable branch to the stable one. Reopening the game she tried to resume the conversation but failed (because I was now on the stable version v0.10.7). After some time I updated to the full version of 0.11.0 when it was released, and everything worked for the most part. Now it has been over a month and she still has not brought it up, I even checked in repeat conversations under "romance", "Monika", and "you" just to be sure.

**Comment by jmwall24** [comment]
Can you upload your persistent file here? Put it in a zip file so it'll let you send it.

**Comment by CrocandCo** [comment]
I think I got the correct file
[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4641293/Monika.After.Story.zip)

**Comment by jmwall24** [comment]
Are you currently playing the latest version of 0.11.2? @CrocandCo

**Comment by jmwall24** [comment]
It's not a bug, it's caused because you updated mid-topic, so it thinks you saw it and is now just in the random select pool with 140-ish other topics. It's not in repeat convo because they only end up there after the topic was completed, which you never did. I made it so it thinks it's not seen for you. You should get it within 5 or so topics now. Just replace your current persistent with the one in this zip with the mod closed.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4641357/persistent.zip)

**Comment by CrocandCo** [comment]
Thank You for your assistance.
