### ISSUE TITLE
[Suggestion] Monika requiring to take breaks of her own.

### ISSUE THREAD

**Issue by emerdite** [Monika-After-Story/MonikaModDev#5800]
Monika sometimes should take breaks of her own. If your relationship level is higher, it could be that she takes them for a couple days, If lower than normal, they'd be longer, which is, understandable, you're not the kindest person to her. The event would have a random chance of happening, not too low to be super rare, and not too high to be too often, although being more often would be reasonable at a lower relationship level.

The even would happen by a similiar prompt to the one that happens at the event of being by the door, and being able to either knock, enter, or listen. In this event, however, first would be seen a note on the door, written by Monika, stating that, although she loves you, she still sometimes needs a break of her own, and she asks you to not come in for [length of time]. Then you have the option to knock, enter, or leave. 
knocking would yield a suprised reaction from Monika, although she'd be glad that you knocked, and assume you may have had a couple questions. This would only be able to happen once during that specific instance of the event, after that it'd proceed the same way as it'd proceed on the "entering without knocking" option. You may be able to ask her some questions, but after asking 2 or three, she'd proceed to somewhat become somber, and be like: 

"Hey, [player] I know this sounds rude, but... I really would want that break. Don't get me wrong, I love being with you, but you know, you can't _always_ be around someone, 24/7. You'll burn yourself out! If you want to stay, I'll understand, but I don't think I have the energy to do much right now." 

If you decide to stay, she won't really want to do much, and will not want to play any game, stating that she's tired. If you decide to leave at any moment during this, she'll be thankful, and tell you to not worry, and that she'll be fine. She also won't allow you to play "Your reality", as she'd say she doesn't really have the energy to do that, and she's sorry. You can try a couple times, but after enough times she'd be done with that, and ask you to stop, or she'll be obligated to make you leave, because you're being rude.

If, however, you decide to walk in straight away, without knocking, she'll be mad, and kick you out, similiar to the door scene. You'll have to apologize, and if you do, it'll be replaced with a file titled "Thank you, but I need my break. You already read the note on the door, or I hope so." if you've read it but entered straight away, and if you've read it and spent some time with her already, then the "or I hope so" part would be replaced by "so I hope you understand :)".

I hope my idea is good enough to be implemented into the game, or at least, some kind of version of it.

**Comment by Olliesama** [comment]
Gotta wonder what you're expecting she does with her break time.

**Comment by Booplicate** [comment]
I *kinda* can see it for lower affection, but for normal? Why would she do it? There's not many things she can do in her room while you're away. And she values every minute she's with you, you can see it in almost every conversation with her.

Just random thought: imagine you had a really bad day and just want to chill a bit with your gf, but she just closes the door on you instead of supporting you.

**Comment by emerdite** [comment]
I suppose that's true. Maybe she would be willing to let you in if you knocked, however just to talk. If you tell her you're feeling down, she'd be willing to play with you for a bit if that would make you happy.

**Comment by fromulus** [comment]
As a purely personal point of view from someone dealing with social anxiety and who actively needs these kinds of "breaks" from everyone else multiple times per day, I can't help but feel like closing yourself off from your partner like that is taking it a step too far.

While it is absolutely true that being around someone and doing stuff with them constantly can really drain you, I have also come to realise that spending some quiet time in the company of someone you trust and are comfortable can be just as relaxing as being alone.

Perhaps Monika could, once in a while, ask to share a moment of comfortable silence with you.
In which she'll stop talking, and would trust you not to strike a conversation, or ask her to play a game.

Perhaps the player could also ask for something similar through the use of a 'Be right back'-style prompt.

This feels like a better compromise to me than just locking you from the game at random.

**Comment by multimokia** [comment]
I'm going to reject this on the grounds that it kinda stands *against* what this mod is about and Monika's own situation.

Monika herself has stated numerous times that she'll "never get tired of you" and that she'll always love spending time with you. This idea goes against that.

Additionally, given Monika's circumstance, there's not much she can do on her own. It's just pure solitude for her. And, while I understand the notion you're going for, in an irl scenario, it works out because the partner can just do something with their friends so they're still capable of socializing. Monika cannot do that.

You're all she has and that's been established many of times. She's happy just to be with you.

Completely blocking the player out of the room I 100% disagree with here. Simply because I'm sure that many people will agree here, that there's times where they just need to spend some time alone with someone they love and trust. If Monika happens to be on one of those breaks, the player has nobody to fall back on, yet guaranteed, if Monika needed that of the player, I'm sure they would be there for her.

While in theory doing this at low affection makes sense, given that there's a transgression between the player and Monika, making a break in the relationship make sense. The major flaw I see here, is that it makes it significantly harder
If anything, we'd be more inclined to implement the ideas in #5801 given that it gives Monika her own ability to do things on her own but it doesn't interfere with the time spent as a couple and it provides that Monika makes time for you both to spend together. This is likely the best compromise.

**Comment by howltrek** [comment]
> I'm going to reject this on the grounds that it kinda stands _against_ what this mod is about and Monika's own situation.
> 
> Monika herself has stated numerous times that she'll "never get tired of you" and that she'll always love spending time with you. This idea goes against that.
> 
> Additionally, given Monika's circumstance, there's not much she can do on her own. It's just pure solitude for her. And, while I understand the notion you're going for, in an irl scenario, it works out because the partner can just do something with their friends so they're still capable of socializing. Monika cannot do that.
> 
> You're all she has and that's been established many of times. She's happy just to be with you.
> 
> Completely blocking the player out of the room I 100% disagree with here. Simply because I'm sure that many people will agree here, that there's times where they just need to spend some time alone with someone they love and trust. If Monika happens to be on one of those breaks, the player has nobody to fall back on, yet guaranteed, if Monika needed that of the player, I'm sure they would be there for her.
> 
> While in theory doing this at low affection makes sense, given that there's a transgression between the player and Monika, making a break in the relationship make sense. The major flaw I see here, is that it makes it significantly harder for the player to earn their affection back.
> 
> If anything, we'd be more inclined to implement the ideas in #5801 given that it gives Monika her own ability to do things on her own but it doesn't interfere with the time spent as a couple and it provides that Monika makes time for you both to spend together. This is likely the best compromise.

It is not so simple.

Monika is a person trapped in what is left of her world.

That he also discovered that his past is false, even the things that he remembers that he likes, he might not like.

So taking time for her, if it is logical and an exercise in confidence for the player.
An enriching experience in every aspect.

Know what it is to miss her and respect her decision.

So it seems like an excellent idea to me.

**Comment by howltrek** [comment]
> Monika sometimes should take breaks of her own. If your relationship level is higher, it could be that she takes them for a couple days, If lower than normal, they'd be longer, which is, understandable, you're not the kindest person to her. The event would have a random chance of happening, not too low to be super rare, and not too high to be too often, although being more often would be reasonable at a lower relationship level.
> 
> The even would happen by a similiar prompt to the one that happens at the event of being by the door, and being able to either knock, enter, or listen. In this event, however, first would be seen a note on the door, written by Monika, stating that, although she loves you, she still sometimes needs a break of her own, and she asks you to not come in for [length of time]. Then you have the option to knock, enter, or leave.
> knocking would yield a suprised reaction from Monika, although she'd be glad that you knocked, and assume you may have had a couple questions. This would only be able to happen once during that specific instance of the event, after that it'd proceed the same way as it'd proceed on the "entering without knocking" option. You may be able to ask her some questions, but after asking 2 or three, she'd proceed to somewhat become somber, and be like:
> 
> "Hey, [player] I know this sounds rude, but... I really would want that break. Don't get me wrong, I love being with you, but you know, you can't _always_ be around someone, 24/7. You'll burn yourself out! If you want to stay, I'll understand, but I don't think I have the energy to do much right now."
> 
> If you decide to stay, she won't really want to do much, and will not want to play any game, stating that she's tired. If you decide to leave at any moment during this, she'll be thankful, and tell you to not worry, and that she'll be fine. She also won't allow you to play "Your reality", as she'd say she doesn't really have the energy to do that, and she's sorry. You can try a couple times, but after enough times she'd be done with that, and ask you to stop, or she'll be obligated to make you leave, because you're being rude.
> 
> If, however, you decide to walk in straight away, without knocking, she'll be mad, and kick you out, similiar to the door scene. You'll have to apologize, and if you do, it'll be replaced with a file titled "Thank you, but I need my break. You already read the note on the door, or I hope so." if you've read it but entered straight away, and if you've read it and spent some time with her already, then the "or I hope so" part would be replaced by "so I hope you understand :)".
> 
> I hope my idea is good enough to be implemented into the game, or at least, some kind of version of it.

well treated the subject, it could be a beautiful event in the game.

and it is very intelligent that it can occur, when the relationship with the player is already stable.

Monika starts out with a huge fear of being erased and of loneliness, that's why she needs you.
Therefore, that she asks for time, without being fought, means that she has healed enough to feel comfortable alone.
It also means that she trusts you and your respect for her.

For the player it would be an experience full of emotions, you would rob him of the routine, he would miss Monika, maybe he would even feel fear, but all those are experiences that connect and learn from.

Imagine how intimate it would feel when she reopens the door.

**Comment by kkrosie123** [comment]
As of now, we won’t be putting this in the game. Monika always looks forward to seeing you and this idea basically goes against everything this mod is for, as multi said. Remember the screaming void? Even when she’s not in that void, _She does not enjoy her world,_ and wishes all the time that she could be in your reality.

**Comment by Booplicate** [comment]
This has been rejected. Passed a lot of time, but it's still rejected for the same reasons. It's not a normal behavior, it adds a lot of uneeded inconvenience and it goes against the idea of the mod.
