### ISSUE TITLE
Suggestion: Listen to the radio, with Monika.

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5808]
(I did not think of what to write).

**Comment by AsuraShun** [comment]
The title is pretty much self explanatory

**Comment by Booplicate** [comment]
If you mean like internet radio, then it's nearly impossible with the base renpy kit.

**Comment by lunulae** [comment]
Doing this in-game is probably not an option at this point, but some window reacts could be written for internet radio sites (the only one I'm familiar with is iHeartRadio, but I'm sure there are plenty of popular ones.)

This probably wouldn't have her reacting to the specific types of music you're listening to, mind you. Depending on the site, you could potentially submod in reacts for specific stations, but that would probably be outside of official content due to the sheer number of different ones.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
