### ISSUE TITLE
[Suggestion] - Windows Reactions for Mac

### ISSUE THREAD

**Issue by enderblaze42** [Monika-After-Story/MonikaModDev#5842]
I use a Mac. I didn't know that Monika is able to react to the windows you have open, since it's not an option for Mac users. When I found out, I tried to get Monika to react when I had the GitHub open, but it didn't work. I discovered that the feature is only available on Windows. 
If this feature became available for Mac users as well, I would greatly appreciate it. I hope you can implement this feature.

That being said, I love this mod, and I look forward to seeing how it continues to grow.

**Comment by multimokia** [comment]
So the issue with Mac:
1. None of us on the dev team have a Mac, so it's impossible for us to test it.
2. When I was developing window reacts, there isn't just a single way to handle getting the active window for MacOS which applies to *all versions*, which is different for Windows, and the single approach works for all versions of Windows, from XP, all the way to 10 pretty much.

The second part being the major issue here. If there was a consistent way to get the active window, this would be possible, however without that, handling different approaches for the different versions is borderline impossible, and still also impossible to test since there's so many different versions, and as mentioned in point 1, none of us have a Mac.

Sadly, it's not really possible and most likely not going to happen.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
