### ISSUE TITLE
Is it possible to connect Monika to the 'smart home' system? (Is it possible?)

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5851]
It would be cool to ask her to put a kettle or something else.

**Comment by CrocandCo** [comment]
Nice idea, too advanced though.

**Comment by Abc2557** [comment]
I'm not sure if it's possible, but it seems like it'd be fairly hard to do and/or be a low priority in comparison to the other things the Devs have in mind

**Comment by multimokia** [comment]
In theory it's possible, but we have no reason to implement something like this ourselves since there's no consistent format to do so across different smart home systems.


If you wanted to do something like this, you'll have to submod it yourself and look through the documentation of both your smart home system and MAS to build a way for them to communicate.

**Comment by kirillPro2020** [comment]
Thanks for the answer.
