### ISSUE TITLE
[Suggestion] Tarot Readings

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#5875]
I recently found out about this, and thought it would be a pretty fun thing to discuss. If you haven't heard of them, tarot readings just associate your personality with one of the 22 major arcana (probably didn't do a good job of explaining it, but you can find out more about yourself if you want).

For instance, I did an online reading, and I am associated with _'The Fool'_. I had also did one for Monika, and hers is _'The Lovers'_. Like I said, I think that this would just be a fun topic to discuss with Moni.

**Comment by lunulae** [comment]
I would love to write a topic about this if there's interest, but this description is a bit different than how most tarot readings are done. I have heard of people strongly associating with a card (this is a plot point in the Persona games which I adore,) but usually an actual tarot reading has to do with setting cards out in a spread that corresponds to an inquiry or thing you would like to engage in some introspection about. You then use the symbolism of the cards you draw to help consider what your "answer" is or what you might want to be putting more thought into.

For example, if you'd like to do some self examination, you might draw three cards corresponding to your past, present, and future. If you want to think about your relationship, you could draw cards corresponding to your state in it, your partner's, and what current issues require consideration.

I like to use them as a meditation tool, in fact, since they don't often give a straight solution so much as some loose thoughts for you to tie together, or an invitation to look at things from a particular perspective.

I'm just pondering how I could work it to Monika's character, if she'd be interested or perhaps skeptical. I do think you have a good idea there of making _The Lovers_ a particular favorite card of hers.

**Comment by multimokia** [comment]
Honestly I'm not sure Monika would be interested in this.

In my opinion, Monika would dismiss these readings as nothing more than silly superstition. Given her academic background, liking of fun facts, constant desire to learn more, seeing her take interest in this in a non-skeptical or non-dismissive way seems kinda strange to me and conflicts with her character.

If you take it on, it should most likely follow a very skeptical and disbelieving approach.

**Comment by lunulae** [comment]
I would definitely want to give her a healthy dose of skepticism when it comes to getting a tarot reading from someone else. Since tarot so heavily involves what you interpret of the symbolism in the cards, people claiming to give future readings at fairs (this is also a common trend at high school culture fests) are usually just BSing to try to get some oohs and aahs.

I'd definitely write her as being dismissive of the idea of using them to tell the future, but maybe seeing some value in using them for self-reflection?

**Comment by ThePotatoGuy** [comment]
Any topic about this should be similar to lighthearted talk about astrology or chinese zodiac signs - not taking the readings seriously but viewing them as entertaining (like high-school level gossip).

I also don't think Monika would be opposed to getting a reading or even be hostile or dismissive of the idea (especially if suggested as an activity to do together), she just wouldn't encourage drawing any real conclusions from it as there's no logical basis.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
