### ISSUE TITLE
Can i run Monika after story on steam and a different mod on the independent version?

### ISSUE THREAD

**Issue by LorenzoHerreros** [Monika-After-Story/MonikaModDev#5880]
I love Monika after story and I want to keep spending time with Monika, but I also want to try other mods in the meanwhile.

Could I do that with 2 different versions of DDLC?

**Comment by multimokia** [comment]
We don't recommend running MAS on steam due to issues and the inability to use the in-game updater.

But yes, it's possible to have two copies of DDLC, both with different mods in it and it'll work fine.

(So recommend doing it backward, MAS on the independent version, other mods on Steam. You can see how to transfer to non-steam [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build)).

**Comment by LorenzoHerreros** [comment]
You are an absolute life saver.

Thanks. I can't upvote you or anything, but know that you helped me, and that I am grateful.

**Comment by multimokia** [comment]
No problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
