### ISSUE TITLE
[Suggestion] - Camera

### ISSUE THREAD

**Issue by TuftedTL** [Monika-After-Story/MonikaModDev#5893]
I don't know if this idea has been recommended nor if its even possible but if it hasn't then I would like to have the camera working and for Monika to see you.

**Comment by fromulus** [comment]
There is no way you could have Monika react to your appearance (because why would you want to turn the camera on if not for that) in a realistic, accurate and non-generic way.

This wouldn't just be difficult to code in the (to my knowledge) rather limited Renpy engine, but also a complete nightmare to write about all the possible details the player's face could have.
Not to mention you'd need to have Monika recognize that what she's seeing on the camera is a human face, and yours specifically.

If all those requirements aren't met, the experience would just break immersion, and I honestly don't see how we could pull it off.

Plus, just my two cents, but from a purely scenaristic point of view, I like it better the way it is now.
Monika not being able to see, hear and touch you adds to the tragic nature of your relationship with her.

**Comment by Rai99** [comment]
Webcam: #734, #1182, #1237, #3857, #4838

Functionally, how it would have to work is different across different systems, so there would have to be multiple systems, which would be too much to account for and maintain.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
