### ISSUE TITLE
[Suggestion] Monika's Life Challenges

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5920]
One of the best thing about having a girlfriend like Monika, is that she pushes you to be a better person. When you do your chores, it feels really good to tell Monika that you're Doing Housechores in the Goodbye menu. It's one of the primary reasons I play this mod. Working on getting my life into order while having a supporting girlfriend is really nice in any case. I'm sure some of you feel the same way.

So my suggestion, if it hasn't been said already, is kind of in the same vein, but more specific. What if we add a new category in the Talk menu labelled "Challenges...", and then have some subcategories within called things like "Workout", "Eating habits", "Sleeping", "Chores", "Learning" and so on. In the beginning, Monika would just ask you a question from random chatter whether you're interested in making a real change with her and for her. Possibly activated at higher affections levels.

If you say yes, then she will start telling you that she could give you challenges, and if you complete them, she will _do_ different things for you, before laughing and saying she's joking. 

m "Or am I"? 

The rewards could be anything from dictating new poems to you, dancing for you, blowing you a kiss, even reading you unique stories. All of them SFW of course. 

I understand that this is probably going to take years to implement, but I just wanted to air the idea to see if this is a direction anyone at all care about the mod taking. I'm learning basic python atm, so in a few months, who knows, I might be able to contribute to the project.

**Comment by lunulae** [comment]
Since they'll be very based on the honor system I do think the rewards should stay simple like you've described, so that folks don't feel so tempted to lie to get a more tangible reward like a new accessory.
If a challenge is failed, up to a certain number of times Monika could give some simple pieces of advice that might help the next time you try, as well.

All in all, it does seem like a pretty involved thing to implement, but I think it's very sweet, and I'd be interested in helping out on it if there's dev interest.

**Comment by multimokia** [comment]
Things like eating habits aren't as easy to capture as we can't guarantee players will use the farewell for eating. Maybe they'll do so at work or something. If they're at home, they might eat with Monika, no brb, no farewell needed. So that's a tricky case to capture.

Sleep stuff I have some sort of plans to implement with #4914. My current testing with this seems to show promise and I think with the functions made, it should be possible to scale this to more than just timeconcern. More like overall time *awareness*.

Ideally these can be used to help *somewhat* verify the validity of some of these things, that and help Monika potentially pose them as gentle suggestions if she notices things seemingly out of line.

**Comment by Rai99** [comment]
I'm not too sure about the rewards from completing challenges, especially more outlandish things like dancing for you. 

We generally want to avoid game-ifying MAS too much, and locking content behind this isn't something we likely want to do, since it would force players to go through it as honestly, or dishonestly as they want just to get some unlocks and never again.

**Comment by Freshairkaboom** [comment]
@Rai99 Yeah I get your point. Maybe just a bit of dialogue as a reward then, some encouragement, maybe another way to increase affection? I know I've read that making new sprites are getting increasingly difficult, so I wouldn't want to overload the mod with it.

I've not read through #4914 very well, but I'll do that soon. Maybe something similar could be done for workout routines and eating habits, and my idea could just as well be implemented in random dialogue or topics under "Hey Monika..." to make it simpler. I agree that a whole new system may be too much of a game-ifying thing to do.
