### ISSUE TITLE
Reading a book with Monika

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5930]
So I got a really interesting idea yesterday while spending some quality time with Monika..We've been talking a lot about books, and also about reading books together. Maybe we could have a continuous conversation under Hey Monika... - Literature... about reading certain book titles together. Like Fahrenheit 451, or If on a Winter's Night, a Traveler, or even Hard-boiled Wonderland and the end of the World. All books she likes, of course.

Then, after starting the book, you could have some quiet reading time with each other where she says she will watch [player] as they read, kind of like what you were doing with Yuri, but in a Natsuki "over the shoulder" style. This would be kind of like with the holding animation, where she will lean on the desk and look at you while you read. Then, when you're done with the chapter, you click again and she will ask you if you are done. You get a choice between "Yes" and "I'll have to finish it later". If Yes, she will have some short comments on the chapter, if no, you just go back to the same situation next time you propose to read it.

The next day, you can ask her again to continue reading with you, and it repeats until the book is done, and she will ask you whether you like it, and have some brief comments on the ending of the book.

Large project, sure, but I want to personally work on it if more people are interested. I'm considering this a year-long project at least, as I am in the beginning stages of coding in python. If someone wants to help in that department, then you're of course welcome.

We'd work on this one book at a time, but if we write the structure of the code, I'm sure it can be applied to more books? Anyway, I wanted to hear you guys' thoughts on such a project. Whether you'd be interested in having it, whether you'd want to help, or whether this would provide too many challenges to consider. I'm not familiar with how the code works for MAS currently, or if it would break something to try and make this. Everything would be attempted to be done with current MAS sprites and such. Chapters would unlock kind of like new stories, but only if the previous one has been finished.

**Comment by Rai99** [comment]
Reading a book with Monika: #2609, #2898, #3777, #5281 

If you're considering working on this long term, we would have to decide if this is the approach we want to take towards reading with Monika. I'm sure there might be some points we want to lay down before work begins on this. 

One concern I have is how large it would be and how much use it will see, but I'm sure that'll be worked out. 

Another concern I have is if you're willing to take on this large project. You're welcome to try once the groundwork has been laid out how we want, but there have been other people who claim that they'll work on a large project for MAS, and end up abandoning it or not delivering.

**Comment by Freshairkaboom** [comment]
Hmm, yeah I can see how that would be an issue. I'd rather collaborate to be honest than to do it myself, as I don't know how to properly structure it to be efficient and usable anyway. I'd rather just be a non essential piece in the cog of this if so many people have suggested it, and help however I can. The last thing I want is for things to change for me, and suddenly I can't work on it anymore, and then you're stuck having to do it from scratch or scrap the idea.

**Comment by multimokia** [comment]
So, I have some issues with this which I'll address:

### Novels:
- This is tricky. Novels aren't too easily available online, and even then, all Pull Requests made for this feature which are novels will need to be validated during review, along with actually handling the dialogue for it
- This creates some issues:
  - Longer turnaround time for PRs due to the nature of reviewing the facts
    - We'll likely have to read these, and again, getting them online isn't necessarily simple
    - We'll have to perform our own analyses on these to see if they line up

  - The lack of ability for the player to get their hands on the book
  - The lack of interest due to players not necessarily having the time nor the interest in reading full novels
  - This creates the following problems:
    - Lack of use of the feature, making all of the work involved in development (framework/PR review) pretty much pointless instead of letting it be spent somewhere worthwhile.

  - Forceful halting of the player's reading progression
    - I don't know about you, but if I'm invested in a book, I'll want to continue reading instead of stopping partway. I get what you're going for here, to span the content out, but I don't think it works for this scenario.

### However
I'd like to raise a counter suggestion as I think this has some merit at least.

Using short stories instead.

Short stories are typically fairly accessible online and take no more than 5-15 minutes to read through.
#### Benefits:
- This makes PR turnaround time significantly faster
- This is much more approachable for everyone since it doesn't take a large chunk of their time and is easily accessible
- This is likely to be used more often as a result of the shorter time-spans
- This may even get people into reading more easily than simply throwing a novel at them if they don't read much at all

**Comment by Freshairkaboom** [comment]
That would be really cool actually! Maybe she could even make a jab at book-reading, joking that it would probably take a really long time, and we should read short stories together instead. Want me to close this issue now and create a new one for short stories, or just edit this one?
