### ISSUE TITLE
Monika sings only one song

### ISSUE THREAD

**Issue by GehorLef** [Monika-After-Story/MonikaModDev#5938]
I might just be "lucky", but for some reason the only song that Monika sings is "Shelter".
Well, maybe she likes this song very much, I dunno

**Comment by multimokia** [comment]
Songs no longer derandom automatically, and since full release hasn't come out yet, the update script to rerandom the other songs hasn't run yet, so for now you'll pretty much only get that.

That said you can ask her to stop singing songs too vids the same way you can tell her to stop bringing up a certain topic (press 'x' when she's singing it)

**Comment by GehorLef** [comment]
Oh, okay.
