### ISSUE TITLE
Personality/Temperment tests fun fact

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#5943]
There are plenty of personality tests out there and it can be ridiculous to try and specify one's traits in a single test. I figure that Monika would bring it up as a fun fact. I understand if this is too broad of a topic to bring in.

**Comment by lunulae** [comment]
If it's too broad, a potential focus could be on the Myers-Briggs personality tests, and how those are sometimes even used in business applications today.

**Comment by 07Akif** [comment]
> If it's too broad, a potential focus could be on the Myers-Briggs personality tests, and how those are sometimes even used in business applications today.

I already explained why MBTI should never be implemented into MAS in this post: https://github.com/Monika-After-Story/MonikaModDev/issues/5752

Personally, I think it's rather obvious you can't specify one's traits in a single typology system. Humans are complicated and extremely diverse, and the purpose of typology is to just help humans understand a portion of themselves better, (a portion of themselves a specific system is focusing on), give them some kind of direction. If you wanted to explain all that in a fun fact, it wouldn't really be a fun fact since it's a very complicated topic and there is way more to it than I already said. But maybe I'm just the one who loves to overcomplicate things.

If anything, I'm open to hearing more if anyone has something to say about this :)

**Comment by lunulae** [comment]
Oh, I definitely agree that they are extremely oversimplified tests and results.
I figured if it were implemented into MAS Monika would be skeptical of looking at tests like this at face value, and be surprised that even professional environments seem to give them a lot more credit than they might deserve.
That said, you're right that such a thing might deserve a full topic rather than a small fun-fact blurb.
