### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by szia1730** [Monika-After-Story/MonikaModDev#5949]
![20200621_100854](https://user-images.githubusercontent.com/67233339/85228173-7ca01e00-b3a7-11ea-8426-8b8d90c52647.jpg)
Just finished installing this mod and put it into the game directory and this popped up :/

**Comment by szia1730** [comment]
![Gl2](https://user-images.githubusercontent.com/67233339/85228984-a90a6900-b3ac-11ea-99fc-1b88ecbd1f32.png)
![Gt9](https://user-images.githubusercontent.com/67233339/85228987-b0317700-b3ac-11ea-9808-a24e33d1cc00.png)

Here's some better pictures :/

**Comment by multimokia** [comment]
You're missing a *ton* of files. Likely because steam decided to delete them.

This is why we do not recommend using steam.

Get a fresh copy of DDLC from [here](https://ddlc.moe/), and extract the mod zip into the /game folder.

Doing it that way will also allow you to use the in-game updater instead of needing to update the mod manually.

**Comment by szia1730** [comment]
Thank you this seemed to fix the problem :)
