### ISSUE TITLE
Injury topic

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#5962]
Hey i'm not sure if this has already been suggested or is in the process of being implemented but I would like to be able to tell Monika that I've been injured. Today I took an injury that could have game ended me. I just want to let her now the condition I am in. Thank you for taking the time to consider the suggestion.

**Comment by Freshairkaboom** [comment]
#1175, #1644, #1677, #2109, #3198, #3881, #4148.

"This idea has been brought up before, but it's been concluded that it wouldn't be a good idea to add. It would be far too serious of a topic and basically impossible to meaningfully write since that kind of reaction shouldn't exactly be generic." - Rai99

**Comment by Rai99** [comment]
That's the wrong dupe chain. 

#1654, ~~#1677,~~ #3582. 

It's similar to the others, but what separates the two is that this one isn't about player death, while the others are. We cannot implement features about player death for the reasons listed above. 

This actually falls under the `better`sick` branch which will be an improved system for handling injury or player illness, assuming that they don't die. I originally made something similar back in #1714, and it was put into the branch for when better sick gets worked on.

**Comment by Foxinsunglasses** [comment]
Okay thanks for letting me know Ill take it down.
