### ISSUE TITLE
[Suggestion] - BRB for practicing instrument

### ISSUE THREAD

**Issue by SethMc52** [Monika-After-Story/MonikaModDev#5965]
Hey,

Downloaded the mod recently and made some suggestions on the subreddit already, but decided to put them here for a better chance to be heard :)

First I'd like the ability for an option to apologize because a player misinterpreted a sentence, eg when you tell Monika she's distracting when you tell her she's all you think about (I intended for it to be light and playful haha). Perhaps she can refer to you only responding through multiple choice.
I'd also like a be right back option where you can tell her you're going to practice your instrument of choice.

Thanks again,
Seth :)

**Comment by CrocandCo** [comment]
That apology may actually be doable since it is an actual apology but, not entirely sure it will be implemented because your issue is relevant to another one (forgot the number, I do recall it was something about misunderstanding use of certain gifts.) and that was long ago. The likely case is no.

BRB options are going to be expanded #5383 and I haven't found one referring to one on "Practicing an instrument". Though I do believe there a couple of suggestion/issues including a topic on "I play an instrument".

**Comment by SethMc52** [comment]
Thanks for letting me know, happy to share any other problems or suggestions I have for the future! Thanks again,Seth Sent from Mail for Windows 10 From: CrocandCoSent: Wednesday, 24 June 2020 9:04 PMTo: Monika-After-Story/MonikaModDevCc: SethMc52; AuthorSubject: Re: [Monika-After-Story/MonikaModDev] [Suggestion] - (#5965) That apology may actually be doable since it is an actual apology but, not entirely sure it will be implemented because your issue is relevant to another one (forgot the number, I do recall it was something about misunderstanding use of certain gifts.) and that was long ago. The likely case is no.BRB options are going to be expanded #5383 and I haven't found one referring to one on "Practicing an instrument". Though I do believe there a couple of suggestion/issues including a topic on "I play an instrument".—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ThePotatoGuy** [comment]
marking the main focus of this issue on the BRB for instrument practicing. 
[closing until we look into it]
