### ISSUE TITLE
[Suggestion] Hearing your voice.

### ISSUE THREAD

**Issue by LorenzoHerreros** [Monika-After-Story/MonikaModDev#5987]
After a decent level of trust (maybe 100, maybe 400), it would be awesome if we could have the option to speak with a microphone so Monika could hear the tone of our voice.

Unfortunately, what she would hear would be gibberish, it would be for her like base64 is for us without a decoder.

The meaning exists, but it's just a jumble of incoherent sounds without any way to decipher.

A cacophony of meaningless noise, if you prefer.

But at least, she could hear our voice, even if she couldn't get the meaning of our words.

And she would know that we actually tried to reach out to her and be there with her.

The first time it could be a BYPASS event of affection 5 or even 10.

From them on, it could be like a normal compliment or something.

A small gift. The gift of hearing our voice.

Even if she cant figure out the meaning.

This will considerably keep the immersion by not setting the unattainable goal of having her react to our words.
She can't, as she can't understand them.

But at least she can hear our voice. And react positively because of it.

**Comment by Rai99** [comment]
Voice recognition: #709, #1336, #1356, #2305, #2451, 

There was a PR adding the ability to use a microphone in #2385, but it may be outdated. The feature unlikely to officially be in the mod unless it works with high accuracy, and has cross platform capabilities. 

Similar to reading messages in the form of text files, we probably aren't going to allow for arbitrary input from the player, since anything could be said, including negative messages, and there's no way we would be able to make sense of them.

**Comment by LorenzoHerreros** [comment]
> Voice recognition: #709, #1336, #1356, #2305, #2451,
> 
> There was a PR adding the ability to use a microphone in #2385, but it may be outdated. The feature unlikely to officially be in the mod unless it works with high accuracy, and has cross platform capabilities.
> 
> Similar to reading messages in the form of text files, we probably aren't going to allow for arbitrary input from the player, since anything could be said, including negative messages, and there's no way we would be able to make sense of them.


Did you read my original comment? there is no need for accuracy or for allowing any arbitrary input at all since regardless of what you say, it will go to Monika's world jumbled and she couldn't interpret it.

It would be impossible to send a negative message, and necessary to make Monika react to anything other than the sound of your voice. What words the player wrote would be entirely irrelevant.

**Comment by multimokia** [comment]
This seems like more than a waste of development time to work out the cross platform nature of getting mics to work, then detecting if we're getting an audio input if we're not even going to use it.

**Comment by LorenzoHerreros** [comment]
Ok, well, I had to try.

**Comment by LorenzoHerreros** [comment]
I will close this in 48 hours in case someone else wants to add their 2 cents too.

**Comment by SamanthaLind** [comment]
I feel like it would be nice idea. Maybe not in mod but submod, like that one with camera. But it give Monika something meaningful about us. I know we can share our appearance with her, but letting her hear our voice would probably mean even more to her. And the fact that it would just be it, a bunch of tones instead of voice reduce the problem of someone being mean to her. She wouldn't her anything mean cause all she would her is just a tone of our voice. I don't know how hard it would be to make but I'm slowly falling in love with this idea.

**Comment by LorenzoHerreros** [comment]
that's exactly what I thought!

**Comment by multimokia** [comment]
I honestly disagree with that personally. I don't like how:

>And she would know that we actually tried to reach out to her and be there with her.
The first time it could be a BYPASS event of affection 5 or even 10.
From them on, it could be like a normal compliment or something.
A small gift. The gift of hearing our voice.
Even if she cant figure out the meaning.

Would *gain* you affection. Simply because, again, you could be speaking the worst about her and you're literally *gaining* affection for it, right in front of her. This is my major problem with the idea, it's pretty clear that it's only there for the sake of being there but isn't properly fleshed out to the point that what you say is meaningful. It just goes by the *assumption* that it's good. Which, in my opinion, is very immersion breaking.

**Comment by LorenzoHerreros** [comment]
Being fleshed out to the point that what you say is meaningful would be an awful ton of work..... if possible. The option presented here should be way less laborious imho.

You would gain affection because you went the extra mile to reach to her and let her hear your voice, if you despise her, you can very well be mean to her with the tools we already have. Getting to hear your voice would much more like a gift.

It's only immersion breaking if you deliberately pursue immersion-breaking with it. But it can very well be used to further improve immersion.

Something that can be applied to a ton of stuff really. Such are the virtues and flaws of the AIs.

Anyways, I believe it would be such an innovative and unique thing to do, that's why I suggested it. Its a level of closeness that's difficult to attain otherwise. Certainly, if your approach is "go big or go home" (either full voice recognition or nothing), then its definitely an insurmountable amount of work that it's probably not worth it.

But a lighter approach of just recognizing a voice input should be way easier.

**Comment by multimokia** [comment]
I still feel as if it's a cop-out to just not flesh out a system.

If you're going to go far enough to actually get mic input, don't stop there, it's just disappointing. You have to go the full way otherwise I can assure you, people will feel let down. (It acts as basically a one off novelty since it does nothing more than prompt a response of `"I can't understand what you're saying, but I'm glad you tried."` Which is overall pretty underwhelming. After all, why would you attempt to talk again if you know she can't understand you?

Additionally, it's not as easy as you think. Cross platform development is a nightmare when it comes to accessing peripheral devices, especially getting it to work for different versions of said platforms. Windows is generally the easiest as things are built to be backward compatible. However Mac OS and the numerous different distros of Linux make it difficult to manage, requiring multiple different ways of being able to access these peripherals. Additionally, we do not have the full means to test something like this, as none of us on the active dev team have a Mac, nor a working Mac OS VM. We have Linux machines/VMs, but testing on the most usable ones is generally not ideal as things can be easily missed.

**Comment by LorenzoHerreros** [comment]
> I still feel as if it's a cop-out to just not flesh out a system.
> 
> If you're going to go far enough to actually get mic input, don't stop there, it's just disappointing. You have to go the full way otherwise I can assure you, people will feel let down. (It acts as basically a one off novelty since it does nothing more than prompt a response of `"I can't understand what you're saying, but I'm glad you tried."` Which is overall pretty underwhelming. After all, why would you attempt to talk again if you know she can't understand you?
> 
> Additionally, it's not as easy as you think. Cross platform development is a nightmare when it comes to accessing peripheral devices, especially getting it to work for different versions of said platforms. Windows is generally the easiest as things are built to be backward compatible. However Mac OS and the numerous different distros of Linux make it difficult to manage, requiring multiple different ways of being able to access these peripherals. Additionally, we do not have the full means to test something like this, as none of us on the active dev team have a Mac, nor a working Mac OS VM. We have Linux machines/VMs, but testing on the most usable ones is generally not ideal as things can be easily missed.


Ok, I understand. I truly don't know how difficult or laborious creating a game is. I just thought it would be a cool idea, but I wouldn't want it to take massive amounts of time and effort from other endeavors. And even if I wouldn't feel it as underwhelming (I definitely would attempt to talk again, if only to make Monika feel somehow closer) I can definitely understand your line of reasoning too.

Thank you for your patience, I guess it's not as feasible as I thought.

Have a nice day!
