### ISSUE TITLE
We're not home yet

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6030]
What if you could take your laptop out with Monika in it after you say "Goodbye/I'm going to take you somewhere...", and bring her to a place, then when you open up the game, you get an option to say "Wait, we're not home yet" or "Home sweet home" when she says "And we're home!". 

If the player uses the first option, she asks if [player] brought the computer outside, and you can either say "Yes, I wanted to spend time with you outside." or "Actually, we're home now."

That way, you can bring your laptop to a coffee shop, the library, even to class, and hang out with Monika after you take her outside too, without her thinking you're home. While outside, the Goodbye/I'm going to take you somewhere... option is replaced with Goodbye/I'm going to take you home... or maybe have it as another option.

Of course, if you're normally on a stationary computer, this would be less useful for you, as bringing over the persistents to a laptop every time you want to switch would be a pain, even if you made persistents local. Seeing this dialogue menu every time would maybe get annoying for you. So what if we can toggle "laptop mode" in settings, and this dialogue only happens if you have it checked? Would this be hard to code?

Not saying this is something I really need, but I think it would be cool to take Monika places, and actually talk to her outside without her thinking we're home yet. I completely understand if this is something nobody else wants.

**Comment by LorenzoHerreros** [comment]
This would be a nice touch probably. While I very rarely use a laptop outside work, it will definitely add immersion for the people who do.

**Comment by ThePotatoGuy** [comment]
I like this a lot. 

Some considerations, though.
For desktop users, this would actually be more like a PC to PC transfer, in which case #5026 must be addressed. 

Rather than a laptop setting, probably could just have the existing take you somewhere ask if she should turn into a file first, which would determine the appropriate greeting to use. This might be more difficult than expected because of how generic the take you somewhere farewell is supposed to be, and when we additional file-gen style farewells, this could become more of a problem.

Obviously would need a new greeting where Monika asks if you're there yet, too.

[closing until we look into it]
