### ISSUE TITLE
[Question] Where did MAS get the rain sounds from?

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#6037]
Where did MAS get the audio for the ambient rain sounds from? 
I'm asking because I'm interested in using the rain audio for my own VN, if I'd be allowed to. If I'm not allowed to, I'll just find another way to get myself some different rain audio.

**Comment by ThePotatoGuy** [comment]
Sorry for the late reply.

appears it might have been custom (#1003). I'm not 100% sure. There is also #201, but I'm 85% sure we did **not** use this.

Since the origin is not certain, I'm going to make the decision that we own the rain sounds. Therefore, you are free to use our rain, provided you give credit. Just note that if someone in the linked issues claim ownership and have a differing opinion, you might need to grab rain from elsewhere.

**Comment by Abc2557** [comment]
Alrighty! Thank you very much! I’ll close this for now since I have a response
