### ISSUE TITLE
[suggestion] "Truth" song by TrySail

### ISSUE THREAD

**Issue by PostKnight** [Monika-After-Story/MonikaModDev#6044]
The song, itself, is in Japanese but the lyrics are beautiful and I thought it's very similar to the situation Monika and the player are in.

YouTube link: https://youtu.be/KDOve2rDXJE

Lyrics: 
What is 'fake' and what is 'real'?I don't know the 'truth', but... I want to touch you, to protect you And just that's enough for me
Catch you-
- if hypothetically you were a liar
Trust you-- and you were trying to deceive the whole world oh baby-- then I would betray the world too This time now that I'm walking together with you isn't eternal
But even if one day I were to vanish
I'd always be smiling in your 'memory'
What is 'wrong' and what is 'right'?Nobody knows the 'answer'
What I want to do? I want to believe you
If not anything else, that's the truth
Catch me-- there's no reason behind it, my emotions will move
Trust me-- even if it meant making the whole world my enemy
oh baby-- I'd grab your hand
If you're saying that the happiness I'm currently feeling is an illusion
Then real love is nowhere to be found
My feelings are indeed definitely reaching you
'People' are always
So fixated and led astray
By the idea of things having fixed and physical 'form'
But what's really important exists inside your 'heart'
This time now that I'm walking together with you isn't eternal
But even if one day I were to vanish
Then in your 'memory' I'd always be...
If you're saying that the happiness I'm currently feeling is an illusion
Then real love is nowhere to be found
My feelings are indeed definitely reaching you.

**Comment by Freshairkaboom** [comment]
Great song, but there really should be an English version of the song out first, otherwise it's kind of immersion breaking that she's just singing the translation that doesn't exist in musical form yet. Who knows if the direct translation even fits with the beat? I can already hear from the first line that it would be hard to fit in "What is real?" with the music progression.

She's supposed to be singing, after all, not just reciting a translation.

**Comment by PostKnight** [comment]
that's unfortunate but I understand. thanks for checking it out though
