### ISSUE TITLE
[Suggestion] Best Girl

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#6056]
When you call Monika "best girl", you get the same response each time. I was thinking, for repeat times saying it, have her say something like,
"I'll always think you're best [gender], [player]!" 
Just to change it up so she doesn't always bring up that she figured you thought she was best girl since you installed the mod.

**Comment by scpketer** [comment]
What if player is trans/non-binary? I mean I like the idea, but you know the world we live in, we can't miss out these two.

**Comment by lunulae** [comment]
For trans, they'd have the option to specify their pronouns in the gender topic. But you have a good point about non-binary, I'm not sure if "best person" sounds awkward or not.
Maybe "best partner?" Though that's not really the same thing.

**Comment by LorenzoHerreros** [comment]
best [gender] is more than good enough.
You can never aspire to please a crowd of 10.000 people, regardless of how great you do.
An egg and bacon breakfast may result unpleasing for vegans.
A vegan breakfast may be unpleasing for people who follow "carnivore-only" diets.
And a balanced breakfast for both.

What are you going to do, have your characters to always skip breakfast? To skip al mentions to food in your game/novel?

No, have them have breakfast in a non-offensive way so people can relate, even if they dont identify 100% with the text.

Making something that pleases 99%+ of the people is good enough.

You cannot say no to a good idea because someone, somewhere, may not identify 100% with it. We wouldn't have any kind of fiction otherwise.

**Comment by scpketer** [comment]
Then yeah, 'best boy/girl/person' I guess.

**Comment by LorenzoHerreros** [comment]
Agreed.

**Comment by LooseEthics** [comment]
^this pretty much. Just my 2 cents here: I get that we want to be inclusive, and I can get behind that, for the most part. But this 'everyone gets something or noone gets anything' mindset just seems dumb to me, especially when dealing with a group this large.

**Comment by lunulae** [comment]
Oh, certainly. I do still want to see it included, I was just wondering if it was preferable to word it another way for a better sound. 
That said "you're best girl" already is a bit grammatically odd so that's probably just part of the joke. :P

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
