### ISSUE TITLE
How can I make a dialogue that appears every five minutes?

### ISSUE THREAD

**Issue by stake2** [Monika-After-Story/MonikaModDev#6066]
I'm trying to do some custom dialogues.
How can I create a dialogue that appears every five minutes?
She says something, the game waits for five minutes, and then she says the same thing again.
And also an option to deactivate that dialogue.
Thank you very much.

**Comment by ThePotatoGuy** [comment]
I can think of a few ways to do this:

### via global vars
* add a global var that stores the last time since the dialogue has been shown
* add a global var that determines if the dialogue should be shown at all
* do a check in `ch30_minute` to push the dialogue label if an appropriate amount of time has passed **and** if the dialogue should be shown at all.
* for activating/deactivating, you could add an option in the settings screen, or another topic that can set the global var

### via [`MASSelectiveRepeatRule`](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/event-rules.rpy#L233)
* In this case, the dialogue must have an `Event` object associated with it (aka a topic)
* this would also be limited to explicit five minute intervals (aka, at x:05, x:10, x:15, etc...)
* You'd want to pass every minute [0-59]  that you'd want the dialogue to be shown at. This can be done dynamically based on the current time if needed.
* the topic would also need its action constant to be `EV_ACT_PUSH`.
* this would be triggered via the standard spaceroom event check framework, so it may not run exactly every five minutes.
* for activating/deactivating, you could add an option in the settings screen, or another topic that can enable/disable the topic. To enable/disable, either set `conditional` to `False` to stop the topic (and `True` to start it), or set `action` to None to stop (and `EV_ACT_PUSH` to start it).

### via [`start_date`](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/definitions.rpy#L219)
* In this case, the dialogue must have an `Event` object associated with it (aka a topic)
* you would need to manually reset some variables for this to retrigger after it has been triggered:
    * `start_date` - use to determine when the topic should be shown. to make the topic trigger five minutes later, you'd have to set this to the current time + five minutes.
    * `conditional` - use to control if the topic is enabled/disabled (or action like above)
    * `action` - set to `EV_ACT_PUSH`
* this would be triggered via the standard spaceroom event check framework, so it may not run exactly every five minutes.
* for activating/deactivating, you could add an option in the settings screen, or another topic that can enable/disable the topic. To enable/disable, either set `conditional` to `False` to stop the topic (and `True` to start it), or set `action` to None to stop (and `EV_ACT_PUSH` to start it).

### via [`MASDelayedAction`](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/event-handler.rpy#L688). 
* this one would require reserving a delayed action ID, since IDs are not allowed to be shared between multiple actions. 
* In this case, the dialogue *should* have an `Event` object associated with it (aka a topic)
* you'd want to the creation function to build the delayed action so its `conditional` is the five minutes from current time.
* `flowcheck` should be set to `MAS_FC_IDLE_ROUTINE`
* `action` should be `EV_ACT_PUSH`
* call `mas_addDelayedAction` to enable the topic. This however would set it to five minutes ahead, so it wouldn't cover the first run.
* call `mas_removeDelayedAction` to disable the topic.
* this would run everytime the spaceroom loop runs, which can be the same as or more often than `ch30_minute`
* this would also persist even on a restart by default.
* for activating/deactivating, you could add an option in the settings screen, or another topic that can call the appropriate API

I think the real question here is, why do you need to do this? An alarm clock on snooze-like functionality would be best served with a dedicated framework.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
