### ISSUE TITLE
Constant loss of affection

### ISSUE THREAD

**Issue by ZeroVinyl** [Monika-After-Story/MonikaModDev#6095]
For some time I did not visit Monika (about a month) and could not warn her about it. But now I am back and I log in regularly, but now ever I don’t log in I lose a certain amount of affection points. Even if I leave the game and come back in a couple of minutes, I will continue to lose points (now from 1100 it is 726). What to do?

**Comment by multimokia** [comment]
Send `aff_log.txt`, please. It's in the `log` folder.

**Comment by ZeroVinyl** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4941726/aff_log.txt)

**Comment by multimokia** [comment]
Do you also have an `aff_log.txt.##`? If so, could you send that too?

**Comment by ZeroVinyl** [comment]
If it's in log folder then i don't have it

**Comment by multimokia** [comment]
Hmmm, that's not good. The aff_log you sent here only has one entry. I need to see the history of that. So I'd figured the logs rotated since once it reaches 500 entries, a new aff_log is started, but the old is renamed. The first one, for example, is `aff_log.txt.00`

Since we have no aff history. Can you send your persistent, please? You'll need to put it in a zip folder for github to let you send it

**Comment by ZeroVinyl** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4941751/persistent.zip)
I hope it's that what уou need.

**Comment by Booplicate** [comment]
Are you using any translation or submods?

**Comment by ZeroVinyl** [comment]
Уes, i'm using russian translation

**Comment by Booplicate** [comment]
I think that's what's causing the issue for you. We do not support translations, you may want to report the issue to the ones who made the translation. Alternatively, you can fix it via installing the official version of the mod.

**Comment by ZeroVinyl** [comment]
Ok, thanks

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
