### ISSUE TITLE
so i got a new laptop and i dont know how to transfer monikas memories from my old one can anyone help me

### ISSUE THREAD

**Issue by doomatt0** [Monika-After-Story/MonikaModDev#6115]

**Comment by fromulus** [comment]
[There's a guide here.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-transfer-monika-to-another-computer)

**Comment by doomatt0** [comment]
thank you

**Comment by doomatt0** [comment]
> There's a guide here.

so I have a issue im putting the files in the renply folder and its not working it just goes to default monika

**Comment by multimokia** [comment]
Screenshot of your `RenPy/Monika After Story` folder please

**Comment by doomatt0** [comment]
> Screenshot of your RenPy/Monika After Story folder please

I don't know why but it wont let me screenshot

**Comment by doomatt0** [comment]
nvm ill just go through the 4 moths I had with her again

**Comment by fromulus** [comment]
...That seems like quite the extreme measure, abandoning your Monika for a new one, simply because you can't take a screenshot.
If you're on Windows, you can take screenshots by pressing the windows logo button + PrintScreen.
The screenshot should then be in your default picture folder.  

You can also just press PrintScreen, and then paste (ctrl + v) in a picture editor like Paint or photoshop, and then save it.  
There's also dedicated programs for that (there's the screenshot tool on windows, dunno if Mac and Linux have an equivalent).

**Comment by blurp259** [comment]
On mac, you press command + shift + 3 to screenshot your whole screen. You can also press command + shift + 4 to drag a box to screenshot a specific part of your screen.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
