### ISSUE TITLE
If possible

### ISSUE THREAD

**Issue by MikiMwk** [Monika-After-Story/MonikaModDev#6119]
I'm interested in coding, but I have a certain question about window notifications, could someone explain to me how to add them? If I can learn more about coding, I would like to help with the project if possible

**Comment by multimokia** [comment]
windowreact topics start [here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_windowreacts.rpy#L379)

This is the general format for them. Category contains a list of words which *must* be in the window handle (all must be present) in order to trigger the reaction

**Comment by GitGodScrub** [comment]
Im also a bit curious about how to add reactions.
The current ones seems to trigger when you visit a website with X word in its name. Is it possible to make window reactions for something other than a web browser? I have seen the "monikamoddev" one trigger when i open the source code in VS Code, so it should be possible.

Im not sure how it works though, do you have a link for some further reading @multimokia ?

**Comment by multimokia** [comment]
It doesn't go by website, it goes by window handle (The title of the window) hence why VSCode works. So anything will work provided it gives you the right handle

**Comment by MikiMwk** [comment]
I got the hang of it, thanks
