### ISSUE TITLE
[suggestion] expand topic "I'm telling sick"

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6125]
I feel like it could use few more options. Something like:
"I catched a cold"
"I ate too much and now my stomach hurts"
"I exercised too much and now my muscles are sore"
"I'm on my period"
Like have option to tell her why exactly you're feeling sick. Cause it could mean many things and it would be great to tell her what's the reason. Also have her to tell player different options for making player feel better, or remind to take better care of himself/herself.

**Comment by fromulus** [comment]
The problem here is the same as why we aren't able to tell her what we're going to eat when leaving for lunch, or which country we're living in, or why we can't tell her in more detail what's our favorite games/musics/movies/books/etc.

There's just way too many possible options for us to realistically cover them all, and even if we did, we'd end up with a menu that has a gigantic list of options that the player would have to spend 5 minutes looking through just to find which one they want to pick.

Not an optimal scenario if the player isn't feeling well and probably plans on going to take some rest, either.

**Comment by SamanthaLind** [comment]
I'm not asking for covering every option. Just like brb menu doesn't cover every possible one. Just to expand it a little. Maybe we could have it split into two menus. Like first one is what we already have and add to that "I want to tell you why I'm feeling sick" if player wants to elaborate. Then have just few more popular reasons why player could feel bad.

**Comment by MarsisUwU** [comment]
i like the idea and if its "too much" you can just add the common ones like "i have a flu" or "i have a cold" or "i have my period" or "my stomach hurts" but I'd really be great to tell monika how you are feeling.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
