### ISSUE TITLE
The theme of the first medical aid.

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#6177]
I think it's important to know how to give first aid.
Monika could tell you about the basic knowledge.For example: how to perform artificial respiration,how to stop bleeding, and so on.(We live in a dangerous world after all.)

**Comment by Freshairkaboom** [comment]
She should talk about the importance of learning such things, but any medical advice that we can write into MAS would be dangerous to utilize in a real situation. We don't want a bunch of people going out and being overconfident in their first aid abilities because of a mod they play. I would love if Monika talked about first aid though, and how everyone should learn it.

**Comment by SamanthaLind** [comment]
I don't know about you but I learned it in school and I think it would be really nice. Of course she can't act like just small talk with her is enough, maybe she could remind player that in situations like that it's really important to stay calm. And it would be really nice if she could mention some myths about first aid, like I heard once about the way to stop bleeding in arm or leg by wrapping some material higher and my teacher warned us to never do it cause wits really dangerous. 
I feel like warning player about what not to do instead of telling player what to do is more important, that way player won't hurt anyone if they ever use that knowledge.

**Comment by Freshairkaboom** [comment]
I really don't think she should say anything about what to do or not to do specifically. I think she should encourage us to seek out first aid courses from trained professionals.

**Comment by kirillPro2020** [comment]
Then she could ask the player if he knows how to provide first aid,if not, she could advise you to sign up for a course.

**Comment by ThePotatoGuy** [comment]
She could talk about first aid and how it is important, but unless we can pull an EMT to review dialogue, we should not put actual medical advice in the mod. That's very dangerous.

[closing as rejected]
