### ISSUE TITLE
Stories and Fun facts randomised 

### ISSUE THREAD

**Issue by Mugnika** [Monika-After-Story/MonikaModDev#6178]
Fromulus and I were talking about the fact that so few people see Fun facts and stories. Therefore we propose to make fun facts random as in 1 fun fact that Moni will tell you a day. As for stories, seeing most of them are pretty long, she can ask you, again once a day, if you would like to hear a story if its day or a scary story if its night.

**Comment by Freshairkaboom** [comment]
Stories could be spread out more I feel. Maybe start a counter for 3 days after you have heard a story previously? Spreading out content sounds like a good idea regardless. Fun facts I understand having every day though, because they're so short and probably easy to make, so eventually we'll have an absolute truckload of them probably.

**Comment by Mugnika** [comment]
one story every 24 hours is optimal I think, it would also give incentives to people to start making new ones again, since people will start seeing them

**Comment by Booplicate** [comment]
I don't think that fun facts have enough value to bring them up randomly again and again. Random topics is something interesting you can talk about, while fun facts lose their value after the first view. Another reason why they exist is things that can't be in repeatable topics go in fun facts.

Not sure how much sense will make her asking `"Hey, Is it okay if I tell you a story now?"` *every day*. I can see her telling a horror story on Halloween, but that's not what you want. Also I don't think stories are worth to be repeated either (at least not so often).

That'll remove 2 interactions where *you ask Monika to do something* (there's already lack of it). And since you force those to be shown at least once per day, you don't spread out, but speed up running out of things too. It'll also mean scrapping 2 existing frameworks (?), not sure if I like the idea.

> so few people see Fun facts and stories

Is it really so? If it's not obvious for some that they can ask for more facts/stories, maybe we could adjust the dialogues?

**Comment by Mugnika** [comment]
The problem here mainly is that very few people see stories and fun facts. Songs are brought up one time too, maybe we can do something similar with fun facts. As for stories, it would make sense for Monika to tell you a story once in a while, if not every day than every so often.

**Comment by Booplicate** [comment]
> Songs are brought up one time too, maybe we can do something similar with fun facts

No, she keeps singing them (unless you asked her to stop), but that doesn't work for fun facts.
> very few people see stories and fun facts

But why?

**Comment by Mugnika** [comment]
We can make it so that she tells the fun fact once and than you have to ask for it again, the stories might be handled the way "hold me" is, if you have not heard a story for a longer time she will ask whether you want to hear one.

**Comment by multimokia** [comment]
Honestly what this tells me more is that stories and fun facts just aren't what people are looking for in MAS.


Makes me think that development time can be better spent by working on other things

**Comment by fromulus** [comment]
I personally think the problem is closer to the fact that you don't tend to ask to see topics again very often when you have seen them all.
Even I just tend to have Monika in the background with repeat topics on and low frequency, and listen to her occasional talks.
I kind of feel like there isn't necessarily a huge gain in prompting topics repeatedly, and fun facts and stories kind of suffer from it, being things that you only access by prompting yourself.

Maybe making those into a daily occurence would be a bit too frequent for that kind of content, but I still do believe that having Monika prompt them on her own every once in a while (without necesserily ditch the systems that are already in place, where a player can ask her directly for more if they're interested) would help bring more variety to the random pool.  

Plus, having them on specific intervalls could help make them feel like some kind of little tradition between Monika and the player, some kind of special thing to look forward to every once in a while, and that's an idea that I do find rather appealing, as simple and cute as it is.

**Comment by multimokia** [comment]
My thing is also for people who *do* know about them. I personally have no interest in the stories myself, and the way I see it, it's somewhat implied that because I never ask, I don't want to hear one.


I see where you're coming from but I feel like this also needs a way to just have her *not* ask because I can see that getting annoying or kinda naggy.

Fun facts don't really work in random chatter selections since as broken mentioned, they're basically meant to be one time things, since they don't really offer much for repeats.

**Comment by Mugnika** [comment]
we can disable it for people who do not want them, telling Moni you are not interested in stories would do it.

**Comment by Mugnika** [comment]
as for fun facts, making them a one time and than derandom

**Comment by fromulus** [comment]
As for stories,  an option in the stories sub-menu to tell her if you changed your mind and are okay (or not anymore) with hearing stories occasionally seems apropriate as well.

**Comment by lunulae** [comment]
I don't know if it's fitting to have stories be a random topic, since they're meant to be longer-form. But I could see facts getting an optional random topic similar to the songs format. Talking about odd things you've learned happens in many relationships, romantic or otherwise.
They do have a bit of an odd dialogue flow for it though, since she seems to look up the fun facts on the spot during the pool topic. Maybe a generic lead-in could solve that, but I'm not sure?

This might be better as a separate suggestion, but I would personally really like a random "you pick one" button for stories/scary stories. Often I just swipe my mouse and click one without looking when I want to do this, but I've noticed I often pick the same two or three.

**Comment by CrocandCo** [comment]
My viewpoint from this (at least from personal experience) is I want to savor it for special moments or when I am bored and want to learn something new. If I get a random fact nearly everyday that is going to burnout the list of fun facts very quickly for those who see Monika everyday. Stories are the same problem with the added (unfortunate) annoyance of asking if they want to hear a story. I can visualize some people may not like seeing her ask daily and just try to completely de-random the topic altogether.

As for another point to put in the spotlight not everyone is going to go through every topic or conversation. Some will just remain untouched like some of the brb's or telling Monika "You're a murderer!".  To me it's fine that you don't go through every nook and cranny of an individual within the first week. It just makes it boring real fast in (certain) cases. If however, this does go through then the same concept could be applied to seeing the victory lines when the player wins a chess match against Monika. They must be added to experience everything.

**Comment by Mugnika** [comment]
[closing until we look into it]
