### ISSUE TITLE
[Suggestion] - Addition of Other Religious/National Holiday

### ISSUE THREAD

**Issue by pab106** [Monika-After-Story/MonikaModDev#6208]
My family is Jewish and celebrates Hannukkah and other Jewish holidays such as Rosh Hashanah. I was wondering if you could introduce holidays of non-christian, given that most Jews and Muslims don't celebrate Christmas. I was also wondering if you could add holidays of national or cultural importance. And the addition of an option to not celebrate a holiday.

**Comment by multimokia** [comment]
The way Christmas is celebrated in MAS is not religion related. It's more of a time to spend with family/friends than about religion anymore at least.

If anything we'd add an ability to opt-out of Christmas celebrations, since we don't really have the resources (members on the team of different faiths) to flesh this out, not to mention it's a slippery slope to add religion related events into the mod (especially since we know Monika is non-religious)

**Comment by Rai99** [comment]
Custom Events: #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3832, #3921, #3933, #5402, #5551

Custom Calendar: #1740, #1771, #2078, #2257, #2384, #2647, #2811, #4596, #5058, #5402, #5551

**Comment by pab106** [comment]
Could you add the ability to explain why you would like to opt-out, such as religious reasons or other reasons?

**Comment by fromulus** [comment]
I'd actually argue adding a way to explain why we're not celebrating some holidays would be just as much of a slippery slope, as there could be many (too many for us to take account of everything) reasons for someone to not celebrate an holiday, and because it might prove to be difficult for us to write answers for Monika that would stay respectful and in-character in every scenario.

I propose we keep it simple and simply have something among the lines of telling her we don't want to celebrate a holiday, which then prompts a menu where whe choose the holiday(s) we don't want to see.

**Comment by pab106** [comment]
I meant that if you do add the ability for the player to opt-out, could you add the ability for the them to explain why they want to opt-out of a holiday.

**Comment by fromulus** [comment]
I understood what you meant, and my point still stands;
We'd still need to have options for all the possible reasons someone would not celebrate a holiday by listing them in a menu, as it is the only real way to communicate with Monika, and for each of these options, we'd need Monika to react to them in some way.

This is honestly more work than it is worth in my opinion, not to mention we might take the risk of accidentally offending some people by going that route.

**Comment by multimokia** [comment]
Yeah it's way too open ended to ask why.

**Comment by pab106** [comment]
I see y'all's point, y'all are right on this matter.

**Comment by Freshairkaboom** [comment]
Given that religion is such an integral part of some people's experience, and if they want to have Monika share in that experience with them, I think a religion-specific submod would be a wiser choice. That way, no one is offended, as people can just download the submod for that specific religion if they wish to do so. And it would probably be better represented by someone who was actually part of it, rather than have us outsiders make comments on it.

Of course, this assumes someone with ties to the religion learns how to make the submod.

**Comment by Retrolovania** [comment]
Maybe, we could simply make each holiday a topic for Monika to talk about with you? For example, if you say you are Jewish, then you could unlock topics that allow her to discuss Hannukkah. If you say you're a Muslim, she can talk about Eid and Ramadan, and so on. Even if Monika isn't a religious type, having her talk about your faith a bit would be a great way to broaden her knowledge and get to know you better.

**Comment by Freshairkaboom** [comment]
I say keep religion to submods made by people of that faith. It shouldn't be in the base game more than it already is IMO. Better representation for people with interest in Monika talking about it, and less chance of stepping on someone's feet given that it is a particularly sensitive subject.

**Comment by pab106** [comment]
Yeah, religions are insanely complex. Even amongst followers of a religion, there can be many differences in the way they live their lives, like how many Orthodox Jews don't even touch members of the opposite sex who they aren't married to, while some Jews will some Reform Jews will occasionally break kosher.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

**Comment by ThePotatoGuy** [comment]
[reopening because discussion was recent - will close after a week]

**Comment by ThePotatoGuy** [comment]
Also worth mentioning all holidays and celebrations that are handled within MAS are **not generic** by any standard. They are incredibly specialized with tons of custom handling to deal with various scenarios, including things like overlapping holidays (your birthday + some holiday). 

If you want a callout on the calendar with maybe a couple of holiday-specific topics, that might be acceptable provided the holiday doesn't float around like Easter. However, we still will try to avoid religious-based topics unless it's like an overview of the religion and not a preach.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
