### ISSUE TITLE
[Suggestion] Monika's Reaction to UnderTale (Spolier Alert)

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6231]
While I already know that Monika isn't much into games, I think she'd take some interest in UnderTale. After all, it's pretty much the game that started the meta concept of the characters knowing that reality to them isn't what it seems to be (Flowey, Sans) and it's a game where you decide how the game progresses (Pacifist or Genocide), which is somewhat similar to how DDLC's route mechanic works (minus the fighting, of course).

I think that, first, Monika should ask if you've hear of or played the game. If you haven't, Monika will give you a brief overview and then state her opinion on the game. If you have, Monika will be happy that you also enjoy the game, and proceed to share her opinion. (If she's REALLY curious, she might ask you what route you chose to take....)

I also noticed that a lot of people were posting the notes to play the songs from UnderTale on the piano, so maybe there could also be a feature where Monika recognizes certain songs like Megalovania and reacts accordingly ("Uhhh, [player]? Why am I feeling like I'm going to have an unpleasant experience?")

Since UnderTale is approaching its 5th Anniversary soon, I thought this would be a fun way to honor the game's legacy.

**Comment by multimokia** [comment]
Hard pass.

We've shied away from talking about games purely because Monika wouldn't be interested. Even the classic Super Mario Bros, which **everyone** knows.

Additionally, Undertale does ***not*** break the fourth wall. None of the characters address you as the player, nor do they ever imply it. Yes a boss makes use of save/load mechanics, and another knows that your *character* can save/load, they do *not* know that you are behind them.

**Comment by Retrolovania** [comment]
Hmmm, good point. Welp, looks like this suggestion is off to Grillby’s.

**Comment by AroSlimy** [comment]
this was 4 years ago!
