### ISSUE TITLE
(Question) Custom Message After Playing Piano in the JSON itself?

### ISSUE THREAD

**Issue by JmDemisana** [Monika-After-Story/MonikaModDev#6240]
Hello..

I plan to publish one note JSON a month here from now on (next month will be Adventure Time's "Island Song"), but I wonder if it's possible to change the dialogue Monika gives you after you play and make it different for every song without creating a custom rpy file (preferably in the JSON itself). 

If so, how? If not, do you plan to have custom post-piano dialogue (maybe as a seperate file for your piano notes pack)?

**Comment by ThePotatoGuy** [comment]
This is not documented in the wiki page, but it is possible to add labels to the JSON that will be called after a piano session ends:
```json
{
    "win_label": "name_of_label_to_call_when_song_is_completed",
    "fc_label": "name_of_label_to_call_when_song_is_completed_with_no_mistakes",
    "fail_label": "name_of_label_to_call_when_song_is_failed",
    "prac_label": "name_of_label_to_call_when_song_is_practiced",
    "launch_label", "name_of_label_to_call_before_piano_is_launched_after_user_picks_a_song",
}
```
These should go at the same level as the `name`, `verse_list`, `pnm_list` keys. The labels would need to be defined in an external rpy.

There are two piano endings that are not currently configurable by song:
1. user does not hit a single note (regardless of in a song or not)
2. user is in freestyle mode and does not play any song 

Let me know if you would like us to add another label option to replace scenario 1 if in a song.

We did not put this on the wiki because we never completely decided whether this was the best way to implement custom post-piano dialogue. Another way we looked at but did not implement is actually having dialogue lines + expressions be added to the JSON itself. However trying to support text+expressions in a JSON is almost like trying to reimplement renpy code parsing but in JSON form - rather pointless when you can just write renpy code. When we do allow dialogue lines in JSONs (sprite objects), we limit it to 1-liners with no configurable expression for simplicity.

**Comment by JmDemisana** [comment]
Do I create a seperate issue with the rpy that contains the dialogues and link all the piano notes it currently supports to it (like a list)?

Just in case a person decided to install the JSON but not the rpy, will it be able to use the default post-piano dialogue or should I do two versions of JSON (One that uses the default and one with the custom labels)?

**Comment by ThePotatoGuy** [comment]
Put both the rpy and JSON in the same issue. It will default to the standard dialogue if the labels dont exist.

**Comment by JmDemisana** [comment]
[Custom Postpiano Draft.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5144752/Custom.Postpiano.Draft.zip)
Is this okay?

**Comment by ThePotatoGuy** [comment]
Yes, that should work probably, but prefix your labels with your name so it doesn't conflict with `mas_piano` labels in the future.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
