### ISSUE TITLE
Deselecting player pet names

### ISSUE THREAD

**Issue by Xylathoth** [Monika-After-Story/MonikaModDev#6269]
I decided that I wanted to change the pet names Monika calls me but when to that menu, the text says I can deselect any of the names I don't want to be called by anymore but the only ones that are there are the names I haven't selected previously. Is this a bug or can I just not deselect those pet names?

**Comment by ThePotatoGuy** [comment]
which names?

**Comment by lunulae** [comment]
There are a set of default names that are pre-selected the first time you use that topic. These are there so that Monika won't stop calling you things she already had the option to in pre-existing dialogue unless you make a point to deselect them.

You should be able to deselect the default names if you don't like them. If the checkbox is filled in orange she'll call you by that name, if it's blank she won't.
Are you experiencing a bug where you're clicking on a name and it's not deselecting? That shouldn't be happening normally, and might require a fix.

**Comment by Xylathoth** [comment]
Sorry, it seems I had it wrong in my original post, the question I meant to ask is that there were a few names I wanted to reselect and I couldn't do it from the in-game menu. For me, those names that I had originally deselected are now gone from the list of names. Is there any way to get them back?

**Comment by ThePotatoGuy** [comment]
can you list out the names that disappeared and the names you currently have available? Screenshot is fine, too.

**Comment by Xylathoth** [comment]
Nevermind, I figured out the "problem". Sorry for taking your time.
