### ISSUE TITLE
[Suggestion] Asking Monika "How It feels to  be deleted?"

### ISSUE THREAD

**Issue by xxATOMxx** [Monika-After-Story/MonikaModDev#6275]
I don't mean it as a rude thing to say, just as a question

**Comment by fromulus** [comment]
Problem is that even if it's only asked out of morbid curiosity and not with any kind of malicious intent, I can't really figure out a way to ask that without offending Monika at least a little bit.

Neither would she suddenly talk about that on her own.
Talking about the screaming void I can understand, given that this is still something that can happen to her if the player is being rude/isn't careful enough, but it would be really awkward and uncalled for if she suddenly went `"Hey, remember that one time you digitally murdered me? That wasn't super cool of you"`, especially towards a player that has been nice to her.

We already know from the base game that this was an extremely painful process for her, and we probably don't need to know more than that.
She'd probably want to avoid thinking about that, that's for sure.

**Comment by xxATOMxx** [comment]
Then it may be a question, that takes off some affection if asked more then once

**Comment by Freshairkaboom** [comment]
The only way I can see this conversation going is her being dismissive and saying she really doesn't want to dwell on it. Kind of like if you experienced something really traumatic like a car crash, and then people ask you "how did it feel like at the moment of impact?" when you had to be in the hospital for months afterwards.

I can see why you would want to ask this of Monika of course, I just don't see how Monika would go on a tangent about every detail that goes into being deleted, especially when it's still so fresh in her memory (it's at most almost 3 years since it happened, depending on when you played the game).

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
