### ISSUE TITLE
This is my frist time downloading ddlc mods and im having hard times if i even installed the mods right but i dont have any idea what these mean and this just happens when i tell monika "do you want to meet my girlfriend"

### ISSUE THREAD

**Issue by Akiresuu** [Monika-After-Story/MonikaModDev#6276]
![image](https://user-images.githubusercontent.com/70768458/92261278-caa0ca00-ee9e-11ea-9c51-211765a9aa6f.png)

**Comment by lunulae** [comment]
This seems to be a current bug, I think we've had more than one person report this one.
If you can restart the mod without troubles, please avoid that topic for now, and it will likely be fixed in a future update.
If restarting is giving you trouble, try restoring an older backup persistent. (You might have to go back a few if you have been trying to restart a few times.)

**Comment by ThePotatoGuy** [comment]
assuming fixed in #6251

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
