### ISSUE TITLE
Suggestion / alternative for repeat topics

### ISSUE THREAD

**Issue by TheHeretek** [Monika-After-Story/MonikaModDev#6342]
The title might be a bit misleading, but I suppose it should say an alternative to repeat topics for after "hopefully think of something fun to talk about soon" is triggered.

While some might appreciate the silence, and others might just toggle repeat topics. It would be nice to have a toggle for "Random Chatter". What I mean by random chatter is for non conversation / non-unique repeatable dialogue to fill the void after "hopefully think of something fun to talk about soon" has been triggered, that can be toggled on or off.

Giving Monika a toggle for her own "I would like to tell you something" where she can throw simple compliments or tidbits of how she feels or thinks at the moment without having repeat topics enabled. This would be an option for simple text that is repeatable and not unique dialogue. Just something to fill the void without repeating previously had conversations.

By non-unique i'm just talking about small one or two line dialogue along the same lines of your own "I would like to tell you something" options. After all, a random compliment can go a long ways to brighten someones day.

I can add the dialogue myself, but don't have the slightest clue how to add the toggle in settings, my python knowledge is limited to making simple interactive novels and calculators.

**Comment by Freshairkaboom** [comment]
Right, so what you want is basically akin to the "My coffee is ready, be right back" type of dialogue right? Something that doesn't trigger the window notifications, and she waits a set amount of time to say before skipping the dialogue? Like passing comments that don't necessarily need to stay until you press spacebar? 

That could work IMO, and we don't necessarily need to alter the settings for it either, just make a persistent variable for wanting to spend time in silence, that if true, can prevent these small dialogues from occurring.

What I mean is that these dialogues are potentially just passing remarks or emotions that could be uttered by Monika without it needing to be a topic in and of itself. However, I would like to know if there's a way we can detect if MAS is the currently active window, so she only says these comments if the player can see here. Otherwise, there would be less of a point to it.

**Comment by fromulus** [comment]
There _is_ a way to check if MAS is the active window (`mas_isFocused()` if I'm not mistaken), the coffee dialogue uses it and changes depending on whether the MAS window is active or not.

**Comment by Freshairkaboom** [comment]
Yeah this is what you're talking about.
![Consumables](https://user-images.githubusercontent.com/45746485/93321877-fd3db180-f812-11ea-869b-5c8d7d489916.png)

**Comment by ThePotatoGuy** [comment]
there would need to be a large amount of filler dialogue or else it will have the same effect as repeat topics. Could be nice for immersion but difficult to implement.

[closing until we look into it]
