### ISSUE TITLE
(Suggestion) monika's fingernails custom colors 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6383]
For example Tan or Green ect.

**Comment by Rai99** [comment]
#4243

**Comment by StayHappy1270** [comment]
@Ant9cp oh someone named Orcaramelo made black nail polish incase you're interested. Sorry about not giving _their exact link_ (idr it). But credit goes to Orcaramelo. 

heres a zip file for it!
[Orcaramelo- Nail Polish.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5292953/Orcaramelo-.Nail.Polish.zip)

Make sure to read the instructions! If you ever want her to not have the nail polish on, you'll have to save a back-up of her original arms also be sure to hold onto this because when there's an update they'll reset to the originals.

Hope this was useful. Enjoy!
