### ISSUE TITLE
(Suggestion: Marriage).

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6441]
It would be nice if, when we reach a certain level of affection (700, for example) ask if she thinks about marriage when she moves into our reality. She could give details of how she imagines the perfect day with the player, how she would like her dress to be, where she would like to get married, where she would like to spend the honeymoon, who she would invite to that special day and other details.

**Comment by 20RaVen23** [comment]
I think 700 is pretty early tbh. It should be more like 2000 imo

**Comment by kittendetails** [comment]
> Acho que 700 é bem cedo tbh. Deve ser mais parecido com 2000 imo

But the maximum is 1000, if i remember correctly.

**Comment by lunulae** [comment]
There is a "Will you marry me" option already present, and it has some variants based on time you've been with her rather than affection level if I remember correctly. 
Although, as to specifics about what kind of wedding she'd like, that could maybe come earlier, since it's more talking about her personal preferences and fantasies than genuinely planning anything. If it were a pool topic I'd probably phrase it like "what's your dream wedding?"

**Comment by 20RaVen23** [comment]
@kittendetails the max lvl of affection is 100000 :P

**Comment by kittendetails** [comment]
> @kittendetails the max lvl of affection is 100000 :P

Oh, sorry, I didn't know that. My native language is not english, so probably haven't had a complete update on my language yet. (Sorry for any grammatical errors. :P)

**Comment by 20RaVen23** [comment]
nah it's okay, English is not my native language either lol

**Comment by Rai99** [comment]
If I recall, the max affection was actually 1,000,000 the last time I checked. You missed a digit.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
