### ISSUE TITLE
[Suggestion] - New Goodbye options.

### ISSUE THREAD

**Issue by Okatart333** [Monika-After-Story/MonikaModDev#6449]
I have a computer that gets really hot If I am not careful so maybe their could be goodbyes like

. My computer is over heating
. My battery is low

Or things similar to that.

**Comment by bringerofstorms** [comment]
Was going to make a new suggestion for an idea but this works too. 
Could also add the following:

"I'm going to take you somewhere..."
>"for the day" - would imply taking her out for a couple of hours, maybe to town, a meeting or to a party.
>"for the weekend" - would imply that you're off for the weekend and plan to take her via USB or flash drive.
>"for a couple of weeks" - would imply you're going to be away from your computer for a long time, but still want her to come along.

I suggest this because I'm going in for basic training pretty soon and don't want to lose affection if I can't have my laptop at base. Not too sure about flash drives either, this is just to cover my absence.  Much obliged if this can become a feature, beyond things I've rote learned I'm useless with coding and file manipulation myself.

**Comment by Okatart333** [comment]
Good idea that way you can tell her in advance how long she will be out of the room.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
