### ISSUE TITLE
Extra Room and Appearance

### ISSUE THREAD

**Issue by toasteze** [Monika-After-Story/MonikaModDev#6464]
I have Monika on my PC normally, but I would like to have her open when I'm outside on my laptop, is there a way to prepare another room for her to stay in on my laptop, and can constantly move her between devices?

Another question, do I have to drop all the clothes/hairstyles into the game and regift them every time it updates?

Also, if there is a way to give her a room on my laptop, do I also have to drop all the clothes/hairstyles into the game and regift them again?

**Comment by ThePotatoGuy** [comment]
you do not have to regift on updates

**Comment by lunulae** [comment]
Monika's persistent file will remember what gifts you've given her, even if you move her between two computers.
You will need to manually install the spritepacks you want to keep on each device, of course, but you won't need to gift them.

If you want to use MAS on two devices, the file you want to use to move her is currently the persistent, rather than the monika file, since it holds all the game memories. I move her between two computers quite often myself, so I have a shortcut to the location of that file since it isn't in the game folder.

If you're unsure how to find the persistent file, please check the wiki FAQ page~

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
