### ISSUE TITLE
[Suggestion] Telling Monika you are asexual/not interested in sex.

### ISSUE THREAD

**Issue by Alyssa4Life** [Monika-After-Story/MonikaModDev#6469]
I don't mean telling Monika you don't want a relationship (Because this mod is literally for people who want to date her forever), I just mean telling her you aren't interested in having sexual intercourse. It could help her understand the player better, and could also lead to some different dialogue with the more NSFW conversations (Rule 34, paraphilia). I just think it would be a more inclusive option for many players, and could help Monika understand us better.

**Comment by hlepnamingblyat** [comment]
I want to see her face when I can tell that I would love to do everything with her. 😆

**Comment by lunulae** [comment]
I've been thinking about how this might be handled, because I was thinking about providing some kind of option for players who might not want the risque-type content even if they meet the requirements for it.
Much as I like the idea of having content for telling Monika about our personal sexuality/identity, I think "I'm not interested in sex" is probably a better way to go about wording it for the function of toggling that content, because I've known asexual people who are comfortable with doing/talking about things of that nature for their partner, and I've known non-asexual people who don't want to touch on that sort of thing due to personal trauma or cultural/religious values.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
