### ISSUE TITLE
Question about easter

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6501]
Why doesn't monika celebrate easter?

**Comment by scpketer** [comment]
Well, I could only assume that's because easter, as far as I know, is religious holiday, and Monika is said to be atheist.

But that's just my quick theory. This has all chances to be not implemented yet.

**Comment by LooseEthics** [comment]
Three reasons come to mind:

- The way this holiday is celebrated differs quite a lot based on location. In some places, like some parts of the USA, it's a kids' holiday with egg hunts and whatnot. In other places it's more religious with fasting and church-going. Other places don't celebrate it at all. Where I'm from, people celebrate it by hitting each other with sticks and drinking industrial-tier alcohol.

- The date is dependent on the lunar cycle and therefore varies year to year.

- Also since it's by nature a religious holiday, there's a date split between predominantly orthodox countries, where the church uses the Julian calendar, and everyone else.
