### ISSUE TITLE
Question about chess

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6536]
Is there going to be changes to chess

**Comment by Rai99** [comment]
There are plans for a large overhaul of chess to make it more enjoyable for all players.

**Comment by multimokia** [comment]
#6163

**Comment by Ant9cp** [comment]
Is it possible for someone that is really bad like me gonna win at all?

**Comment by Ant9cp** [comment]
Rai99: (There are plans for a large overhaul of chess to make it more enjoyable for all players.)

Are you sure about that? because i think it's gonna be the same anyways

**Comment by Retrolovania** [comment]
Well, you can't make any changes to the general chess formula, since the game's been standardized to heck. However, that doesn't mean there aren't ways to mix it up a bit...

**Comment by multimokia** [comment]
Well you haven't tried it so

**Comment by Ant9cp** [comment]
I Always lose with chess

**Comment by Retrolovania** [comment]
At the moment, a loss is pretty much the norm when playing against Monika. Given her intelligence, her Elo rating (rate system used to determine a chess player's skill level) is quite high. So, naturally, you'll only beat her either through a stoke of luck, or if you somehow manage to cheat (although she'll catch on and end the game).

**Comment by Ant9cp** [comment]
How do you enjoy a game like this anyway?

**Comment by Retrolovania** [comment]
Chess isn't meant to be enjoyed by winning or loosing. It's about testing your skill and cognitive thinking; figuring out what moves to make in order to sidetrack your opponent while keeping your pieces safe. If you're really good at Chess, chances are you can think faster and more efficiently than a Harvard graduate. That's why Chess is on of the most highly regarded games in the world.

**Comment by Ant9cp** [comment]
Well then i'm very dumb person then right?

**Comment by Retrolovania** [comment]
What? No, of course not. I'm not saying intelligence is completely necessary here. It's mostly creativity in a way.

**Comment by Booplicate** [comment]
> because i think it's gonna be the same anyways

You asked if there are plans to change chess and got positive answer with linked PR. And after that without even looking at it once you say chess won't change? How does that make any sense? I tested the PR myself and can say chess does feel easier. But I guess it's easier for you to just say that you can't win and give up on it. Then the question is, why did you ask if we plan to improve chess in the first place if you don't care anyway?

How I know you haven't looked at it? Because the PR has more than 4500 changes, the game was rewritten from scratch. So you're either very disrespectful to the insane work @multimokia and @Legendkiller21 have done there, or you just ignored the answer, which leads to my first question.

**Comment by Ant9cp** [comment]
Woooooow. @Booplicate i haven't even looked at this comment of yours or the all the hard work of @multimokia @Legendkiller21  and your saying this: (So you're either very disrespectful to the insane work) I have never been disrespectful to any of them. like you can be at two places at the same time. everyone have other things to do than just looking at comments on github.
