### ISSUE TITLE
Add a visual (like an ipod) representing that music is playing when you ask to play music

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6565]
Wouldn't it be a good idea to add like a device in MAS for monika to grab and put it on the table whenever you ask to play music and then listen to the music coming from the device

(Device example) like a mp3 player or something else (et cetera)

**Comment by Retrolovania** [comment]
Make it an original iPod (rebrand it as a MoniPod), and we're talking.

**Comment by Ant9cp** [comment]
My idea's isn't good enough or something? 🤨

**Comment by Retrolovania** [comment]
...an iPod is an MP3 player? I just meant in terms of design?

**Comment by kittendetails** [comment]
I think it would be a cute idea. But it would be really difficult to have a reaction for each song, since the player can add literally any sound if it's in an MP3 format. Maybe a list of specific songs can be created, with equally specific reactions.  Also, like @Retrolovania said, there would have to be a design for an MP3 player/iPod. Maybe both are too small to put on the table. I guess a small/medium radio would be more efficient? I know it looks old, but maybe it will add a "vintage" look to the room? Idk, it was just something that I thought.

**Comment by Retrolovania** [comment]
A radio would be pretty awesome! Maybe it could be a cassette player/Walkman? That way, Monika can take it whenever you go out, sort of like the thermos.

**Comment by kittendetails** [comment]
This is a really great idea. Monika is "alone" in your pendrive when you take her out. Maybe it's a little scary to be in the dark all the time, even if she is with you in your pocket or whatever. She also say that she doesn't like being in the dark. But, listening to music, maybe she feels less apprehensive. A radio for her to listen to music while drinking coffee or hot chocolate in her thermos looks great.

**Comment by scpketer** [comment]
I don't think there is a good way to react on songs. MP3 files can lack comprehensive file name and metadata, so we can't make out what song it is without analyzing its contents, which is... Sort of hard to implement.

**Comment by Rai99** [comment]
So original suggestion was like having a music device on the desk.

**Comment by scpketer** [comment]
You're absolutely right, it was.

**Comment by ThePotatoGuy** [comment]
could be done in a janky way with an ipod ACS right now, but a full implementation otherwise would take some work.

[closing until we look into it]
