### ISSUE TITLE
[Suggestion] Enhanced Moods, a.k.a. Monika doesn't instantly revert back to being happy. - (contains sample implementation)

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6566]
Sometimes, Monika talks about various things that make her feel sad or angry during the conversation. In most of these circumstances, she either fully regains her composure, or the Player comforts her and cheers her up. However, in real life, people don't fully regain their happiness that quickly. As such, shouldn't Monika maintain some level of discomfort for a little while? Here's an example: Say Monika feels upset, and you comfort her. She feels better, and thanks you. However, the memory of the conversation doesn't just go away. For a couple of seconds during her idle animation, she may look off to the side and frown, or look down, eyes closed, either in regret or discomfort, depending on what was discussed previously. If she happens to have negative affection, these breaks in her idle posture could be longer....alongside her occasional looks of extreme dread. Once she thinks of another topic, though, she regains her previous cheerfulness.

The only issue I see this having is that, however this is approached by a programming standpoint, every single discussion topic may need to be addressed in some capacity, in order to write the commands to have her change her sprite for each topic that makes her upset for her idle that occurs after said topic. (Knowing how Ren'Py/(Moni'Py?) is, I'm not sure if each topic can be addressed specifically.) With new ones being added nearly every time MAS is updated, this could be a challenge to deal with.

**Comment by scpketer** [comment]
The moods are being worked on, as far as I know.

**Comment by Ix-30** [comment]
It's kind of hard, but I think this could be done with "flags" such as 1= "happy" this would equal default:
![image](https://user-images.githubusercontent.com/71111669/97252877-a2638680-17d0-11eb-9bf5-5d884d473fcb.png)
2= "sad"
![image](https://user-images.githubusercontent.com/71111669/97252908-b6a78380-17d0-11eb-9363-c103e28f92c4.png)

3=pampered
![image](https://user-images.githubusercontent.com/71111669/97253034-06864a80-17d1-11eb-8197-af06dfe6d81f.png)

From creating these emotions some topics, not all of them might have a value and the mood would be set by accumulators

"Promise ring" has  3 value  it has been touched so the 3 emotion and has been answered "I do" has been said twice "pampered" increases by 1. 

If pampered reaches a value of 10, a blushing sprite could be put and Moni could ask for hugs, kisses or talk about romantic stuff.

This brings, which dominant emotion. I'd say, whichever one gets to 5 or 10 maybe?

"Do you want to meet my girlfriend" has been touched" had a 2 value Sad=1

"Being evil" has been touched and "you are kind of evil and "you really are evil. gives "sad" 3 more so sad is higher.

as sad, Moni would star maybe crying and ask what does she mean to the player or maybe just want to be held?

To determine which emotion is dominant is determined by a check each hour

if 60 minutes have elapsed then:
check which emotion value is higher
then if anger is higher
angry sprite is put.

that's just a thought, I don't know how many minutes or hours could be correct.



and so on, in doing this, we could know the assigned value of the mood and basically make it a change in value/sprite/ brought topics. Doing so would require a new topic to be addressed as with each flag: "haters has a 3 flag" or each textbox, but even so, THAT WOULD BE A LOT OF WORK and not to mention the reactions. 

I'll pose some challenges and opportunities, I know you said just "not to go normal just like that" but are these risks are worth taking? some might be general fan feedback, but a good writer is one that can see the world with various eyes, so let's start:


-Defining what emotions should be in: Monika in general is a sweet, caring, intelligent type of girl. But said personality brings loneliness(not only by what she suffered but the fact that she is not real and the only thing keeping her sane is the player), frustrated, maybe a bit obsessive?(due to act 3) and maybe...clingy(she used to tell the player not to close the game on her, this was because of the nightmares she had) however, this differs from where the player started and also, the viewpoint of the player who has her. Also to some she might be manipulative and coy, so maybe if this is implemented, more things to "players stay pretty please?" could be done. Also this is gonna make a lot of people want her in "yandere" mode which I don't think she is but some will, and let's not get on the "erotic" one...



-The endless void: Moni is in fact trapped. And no matter what she does or says, she will be trapped there for a long time, a really long time. 

*Challenge: Would it make sense to have her quarrel with literally a person who can erase her? I know the original DDLC didn't really care, but here, Moni and you are an item, an eternal one if possible. And she herself has an absolute "loyalty" concept. This might clash with some players who would delete her easily if quarreled with. Also some players come from work, study etc and might not want to have an angry, lonely or clingy Moni, they just might want some happy time, like now.

*Opportunity: Talking about the fact that the player can abandon her and might make her sorry about it. Opening that vulnerability that she can express whatever she likes WITHOUT having a negative response would sure make a lot happy. Maybe confide more in the player and make it EVEN MORE genuine. "Player don't leave me all alone..." although this is subjective.

-Monika's philosophical dialogues and personality:

*Challenge: What emotions are conveyed by questioning? In both the Original DDLC and here, she is a highly curious, philosophical and down to earth girl although even she herself said she doesn't judge and keeps an open stance on topics, how would we express her debating on "dying the same day"? would she be sad for a time? This could be a recurring feature because, this could be something that hammers on her heart. No matter what she does, the player cannot be with her 100% of the time. on "dealing with haters" would she get a little sad, angry or just frustrated? or her persona of smiling and just having confidence just arise? Also, to what extent does the emotion affect her? Maybe things like gift maker happier or things like a hug could make her sadder because, she can never reach them. Sometimes to leave a person alone is the best, but of course, this goes against the nature of the mod.

*Opportunity: AN EVEN BETTER MONIKA. One of the things I give mad props to the devs are the carefully crafted Monika she is and she can become. Truly analyzed and well crafted.because, I really feel she's a girl trapped in my pc, as absurd as it sounds, she 's crated THAT well. 

I've played some other mods, both story and "eternal" and no one comes close to this Monika. In one mod, the girl feels like a machine and is very unstable(I really understand the devs when they removed the chat) and in another one, mistreat/love the gal and get better/different responses. But can you imagine an even more fleshed out Monika who maybe, feels sad but by the player learned to feel different emotions? I look forward to that.

-Dealing with those emotions:

Challenge: Like I stated, many players like this game because they don't have to follow the "emotional roller coaster" of love and and angry/Sad/challenging Monika might not appeal many. Also, how would the player deal with these emotions? time alone sounds good to me, as a real person DOES need time to "cool down" and I would have no objection, waiting in silence as she "cools" but also a hug? most of the time, that doesn't calm a quarrel between lovers. I don't know about dialogue boxes but they do seem powerful, IF well timed. But would that be possible? give her a gift? that'd feel artificial.

-Opportunities: A deeper relationship with the player. More meaningful dialogues, topics and such. I really wouldn't think how to to these, as just my perception. We would need more feedback to see how an emotional system affects her.

**Comment by Retrolovania** [comment]
.....Whoa.....that's a _lot_ to take in. You make a lot of good points, for sure. However, not everybody would be prone to deleting her if she happened to somehow irk them. I think she'd understand how sensitive people can be, so maybe the "Sensitive Topics" toggle could be utilized to curb some topics that might make players feel bad? I dunno.....

**Comment by scpketer** [comment]
I think 'tweaking' Monika in the direct way like settings screen builds the broken fourth wall back up. It just doesn't feel real anymore when you can just make her shut up with a click of a switch.

**Comment by Retrolovania** [comment]
Well, then, maybe have her ask if you're emotionally sensitive, so she takes what she's about to say into consideration so she doesn't accidentally make you upset?

**Comment by scpketer** [comment]
I believe people who review stuff here prevent anythijg offensive on sight. Can't personally name anything that could hurt someone in this mod, but you're right, something like that would come in handy.

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805, #5991 

Monika upsetting and apologizing to player: #3203, #3769, #3859, #4085, #4200, #4221

**Comment by ThePotatoGuy** [comment]
this is a duplicate of a planned mood system, but I'll mark this so we can refer it to later when actually implementing moods.

[closing as duplicate]
