### ISSUE TITLE
Question about what unstable mode does

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6569]
In settings you have a option called unstable mode what does it do when enabled?

**Comment by scpketer** [comment]
Makes the updater pull updates from unstable branch.

**Comment by Ant9cp** [comment]
Why does it say (It is HIGHLY recommended to make a backup of your persistents) what is the reason for that extacly?

**Comment by scpketer** [comment]
The reason is exact same as why you shouldn't use any other unstable software unless you are ready to experience potential instability consequences.

Imagine a bug in mod script which causes your persistent to corrupt or get removed, and while this bug gets removed in stable, it might be still unnoticed in the unstable branch, thus leaving you to it.
