### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by sassberrysnap** [Monika-After-Story/MonikaModDev#6597]
Hello! I have recently discovered Reality shifting!! It's where you can shift into your desired reality, and it seems like something Monika would talk about!

Maybe she could bring it up in a conversation of her or the player shifting to a reality just for the two of them, and in other discussions she could talk about different methods and subliminals! And of course scripting! There's a lot to research about it and I feel like that would be something nice to add to the game!

**Comment by shtrs** [comment]
Okay, so... I don't think shifting really applies to Monika's reality, since it only works with variants of our reality. Something more fitting would be a desired reality, but it's literally creating your own reality temporally.
Equal way a lot of misinformation is being spread in the witch community, so I could be wrong.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
