### ISSUE TITLE
[Suggestion] A topic on plural systems

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#6613]
So I was thinking back to the old suggestion on Monika's opinion on tulpas and tulpamancy ([#6089](https://github.com/Monika-After-Story/MonikaModDev/issues/6089)), and I think, rather than just tulpas and tulpamancy, what about just a topic on plural systems in general, regardless of origin? In general, plurality and plural systems in general are less controversial of a topic when compared to tulpamancy specifically. While plurality can be controversial to some, it's much less controversial than tulpamancy, so I feel it'd at least be a more reasonable option than a topic on tulpas and tulpamancy specifically

**Comment by lunulae** [comment]
This is a tricky one. I really like this topic but it's also really complex if we involve the player. 
DID is a rare condition but one that media simplifies and stereotypes so much. With her attitude toward those unrealistic character types, I think Monika would really sympathize toward real people who get such a bad rep and even often used as horror tropes. It's especially a kick-while-they're-down situation because it's most often a disorder born out of extreme mental trauma.

I have to be honest though, I'd have a tough time with how to write about if the player has this condition, because it's one with a lot of variability. I suppose she could assume for now that they don't, or consider it something they could work out better in the same physical space if they do?
I suppose we've taken a similar stance with depression before as well, so it wouldn't necessarily be out of place to do so. I'd like to hear what folks think before I settle on that as the best solution though.

**Comment by ashyashton** [comment]
As a person who is part of a system, I DEFINITELY think this would be really nice! In fact, it was the inspiration behind one of my suggestions (number #6588 is the one in question). I referred to them as just my friends to make it easier, but mostly I was referring to my headmates. Maybe we could combine the ideas? Like, if we implement an ability to tell Monika you do have alters/headmates, and then later add an ability for friends to talk to Monika, maybe one option during that could be that someone could say that it's one of those people. Then the two topics connect, as well, which I think we desperately need more obvious examples of. All in all, I think this is a great idea!!

**Comment by Abc2557** [comment]
Wow, it's great to know there are other systems on here! About your idea, I feel like it would be _great_, but it'd just be way too hard to implement imo. Still a good idea regardless! Unless an option for that is added, just having other system members talk as the player seems like the best option. We have our name set as our system name and change our preferred pronouns to the preferred pronouns of who's talking

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
