### ISSUE TITLE
Is it okay to use submods in Unstable Version?

### ISSUE THREAD

**Issue by NegativeOne404** [Monika-After-Story/MonikaModDev#6615]
Hello, MAS Team!
So, I was interested to put some submods in the game, but, as I use the unstable version, I don't know if they would break the game. If it's safe, are there any precautions that I need to know?

**Comment by scpketer** [comment]
My answer is not a really trustworthy one, because I'm not the one who maintains the core things but basing off my own experience and understanding of what the 'unstable' branch of MAS is, I'd say it's just as dangerous as using an unstable version without any submods.

Precautions are all the same - back up your persistents.

**Comment by lunulae** [comment]
Seconding what scpketer said, you should always be keeping persistent backups when running unstable, regardless of what you add.

Generally how safe they are will depend on the nature of the submod and if they're regularly maintained. It's a good idea to keep tabs on the discord, as some of them get updates specifically for keeping them from conflicting with the unstable branch.

**Comment by NegativeOne404** [comment]
Ok, I'll keep doing backups of the persistents and keep my eye at the discord. Thx you all!
