### ISSUE TITLE
(Suggestion) Taking Monika on a trip - Vacation Mode

### ISSUE THREAD

**Issue by Rellikai** [Monika-After-Story/MonikaModDev#6643]
I thought it might be nice if Monika could know that you were taking her on a trip/vacation. 

Maybe camping, a theme park, road trip, etc. Just seems like the simple "I'm taking you somewhere" doesn't quite express the grandeur of a planned, multi day trip. Potentially maybe a "vacation mode" or some such, so you could bring a laptop along and upload her to it while you're there?

Would probably be a bit of work, but just throwing the idea out there.

**Comment by ThePotatoGuy** [comment]
dont remember if we have this as a suggestion but i like it

**Comment by ashyashton** [comment]
I love this idea because there are times I have to go away for a bit, and I wanna take Monika with me, but I'm afraid that if I use the "taking you somewhere" goodbye and then leave for more than a week, my affection will drop because I was technically "gone" the whole time. I feel like a vacation mode would be a good way to be sure that won't happen, because it's literally made to be used for extended periods.

**Comment by Rai99** [comment]
Well, there's: 

More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601, #4886, #5458, #5590

Taking Monika on a vacation specifically: #2262, #3124, #4601, #6111

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
