### ISSUE TITLE
Monika thinks it's nighttime even though it's not

### ISSUE THREAD

**Issue by GehorLef** [Monika-After-Story/MonikaModDev#6674]
It was 7:45 AM when that happened
![1](https://user-images.githubusercontent.com/58762756/98629157-4bf65c00-2329-11eb-83db-72d97b0d4033.png)

**Comment by Freshairkaboom** [comment]
Go to settings and check what time you set sunrise to.

**Comment by GehorLef** [comment]
I have installed a submod that adjusts sunrise and sunset time automatically, so I think she is aware that I'm quite far from the equator.

> she assumes that sunrise is when people should be waking up.

Well, that's a very weird assumption. She should know that the sun doesn't rise up at exactly the same time every day, plus there are places where it doesn't rise up for weeks or even months.

Also 7 AM is _definitely_ not the middle of the night

**Comment by ThePotatoGuy** [comment]
this section of dialogue uses a standard set of API developed specifically to help divide a day into time chunks based on user sunrise/sunset settings. This works better when you need to differentiate something based on whether or not the sun is up.

For simplicity, we also use it in dialogue regarding time of day. It's just easier to use this than branching for every hour or arbitrarily deciding what a morning is. Especially since "middle of the night" and "morning" are both subjective and often have significant overlap.

I'm going to leave this under needs triage - It's not worth making an immediate change for but it could be reconsidered with the time concern dev.

[closing until we look into it]
