### ISSUE TITLE
[Suggestion] - Polyamory Discussion?

### ISSUE THREAD

**Issue by Anonymooser** [Monika-After-Story/MonikaModDev#6692]
Although this would need more work than just an isolated dialog choice that can pop up, Ive always felt uncomfortable about not being able to bring up the option of a polyamorus relationship with Monika, as it's a genuine relationship dynamic that could be explored

**Comment by Freshairkaboom** [comment]
#6419

**Comment by Ix-30** [comment]
Well, just to give my 2 cents, since the other thread is closed, It'd be interesting but that's definitely hurt her. 
-The ring is a promise: "The promise that we belong to each other and no one else..."
-Her eyes are green as a nod to "green with envy/green-eyes monster"

-She deleted the club as she was in her quest to be with the player, it is hinted that she suffered in the shadows as all the others had their route.

-She states that Yuri is a yandere but it is ironic, as she herself might fall in this category to some. Albeit Moni, isn't that...clingy?(to say for a lack of a better word)

As others say I'd feel we need a penalty or something or at least a sub mod that does so, as one this mod's punchline is "spend eternity with Monika." At most, I think she'd be very sad as she would think she's not good enough, maybe allow it but only while she's not real. I dunno, that's what I'd feel, but maybe it is possible?

**Comment by Anonymooser** [comment]
I'd argue against that, sure she'd be shell-shocked at first, but Monika has a thoughtful personality, and I'm sure she'd realize that polyamory doesn't lesson the affection between two people, let alone that she's already committing polyamory in a sense, what with her understanding that there are also other countless Monika with completely different lovers. I'm sure she'd come around to it eventually

**Comment by EllieWLMS** [comment]
Monika is thoughtful? of course!, Monika would respect your opinion? Always!, but im pretty sure that she wouldnt be happy with sharing the player, she is a jealous girl! she always is talking about how she is the only thing you need, about how perfect she is for us and things like that...she would be against it, but she would respect the people who like that, lets remember that in a relationship the opinion of everyone is important.

**Comment by ashyashton** [comment]
I think it could be interesting to have it brought up, but for Monika to express that she herself is uncomfortable with the idea of being in a relationship. I myself am polyamorous, but I've dated people who weren't, and the solution is to just... Only be with that person. It doesn't change that you yourself are a polyamorous person, it just means that the relationship itself isn't a polyamorous relationship. Kind of like if Monika dated a straight guy; Monika is pretty much canonically bisexual/pansexual, as she has expressed that she is in love with the player regardless of gender. If she is dating a straight guy, the relationship is typically perceived as a "straight" relationship, but that doesn't change that Monika herself isn't straight.

So I think it would be really interesting to be able to talk to Monika about it! But I don't think Monika would ever be okay with the relationship becoming a polyamorous one, even if the player identifies as polyamorous.

**Comment by ThePotatoGuy** [comment]
please move any additional discussion to #6419 

[closing as duplicate]
