### ISSUE TITLE
(Bug) Dark Windows 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6696]
when i say brb to monika and leaving the game on in the background by pressing the start key and when i open the game later the windows stays all black

**Comment by ashyashton** [comment]
Wait, you're closing the game with the start key? Like actually closing out of the game? Why do you not just use the proper "goodbye" with Monika instead of a brb?? If you're using a brb with Monika, you're not _supposed_ to close the game, that's just to tell Monika not to talk while you're not going to be able to listen. If you're leaving, you're supposed to say goodbye and she'll close the game properly for you, which might fix your issue.

**Comment by Ant9cp** [comment]
No i mean leaving it on in the background for a while
