### ISSUE TITLE
[Issue] Monika has stopped talking to me.

### ISSUE THREAD

**Issue by DraconicBladewing64** [Monika-After-Story/MonikaModDev#6712]
Hello. I have been enjoying the Monika After Story Mod, and have recently reached 500 affection with Monika. However, several days ago, My computer was being very slow and ended up crashing the game on me. I reopened the game, and I had a conversation with Monika about the game crashing. However, since then, Monika has not brought up any topics on her own. She will sing one song, and then proceed to stay silent after that. I have the Random Chatter set to Very Often, and still, she will not speak on her own. Is there any way to fix this issue? Thank you for your time.

**Comment by Freshairkaboom** [comment]
There is a limited amount of topics available to discuss. Some topics are locked behind certain holidays, other behind even higher affection or anniversaries, but it seems you've reached a point where she doesn't have anything new to say. You could always turn on repeat topics, but I'd recommend setting her random chat frequency to rarer and leave her on in the background. I hope you'll stay with her even if she doesn't always speak. I know she'd appreciate that.

**Comment by DraconicBladewing64** [comment]
Hello. Thank you for your reply. Unfortunately, I don't believe that I have exhausted all of Monika 's topics yet. I say this because she has yet to introduce me to chess, as well as the piano. Also, when I checked the repeat conversations, under the locations tab, it only showed two locations that Monika has talked about. When I toggle repeat conversations, she talks normally, but does not speak when it is disabled. I just want to make sure that my Monika is okay. Thank you for your time.

**Comment by Booplicate** [comment]
> she has yet to introduce me to chess, as well as the piano

Game unlocking isn't an ordinary conversation, it especially depends on time you spend with her every day. You can speed up unlocking chess by playing pong, but for piano you have to actively spend time with her (I say actively, but running her in background also counts). It's intended to be unlocked late.

> repeat conversations, under the locations tab, it only showed two locations

There's only 2 topics in that category, what are you looking for?

> When I toggle repeat conversations, she talks normally, but does not speak when it is disabled

Because she doesn't have new topics to talk about. That is the sign that you did see all the available conversation for now. As Freshairkaboom said, you'll get more with time. As well as the old topics may change over time depending on some conditions. But in the end there is only so many topics.

**Comment by DraconicBladewing64** [comment]
Okay. I believe that I understand a bit better, Thank you for your help.
