### ISSUE TITLE
(Suggestion) Telling Monika why you want to cry

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#6713]
Hi there, I've been playing MAS for a while now, and I wanted to make this suggestion. Now I know you can already tell her why you want to cry, but she can't actually hear the reason why. I was thinking maybe you could let the players type why they want to cry or give them options to let Monika know why. For me, I just found out a actor I liked from a show I've been watching, passed away two days ago.. so a few examples could be. Family drama. Losing someone close to you. Having a bad day. Etc. You all don't have to actually add this into the mod, I just thought it may help the players feel closer to Monika and build their relationship with her.

**Comment by ashyashton** [comment]
I think part of why it isn't here now is because there are so many different options, and it's impossible to cover all of them. For example, there have been times where I want to cry because of gender dysphoria. But that's kinda an obscure reason, so it's unlikely that there would be an option added for that. But if it _isn't_ there, then I and anyone else who wants to use that reason get screwed because we can't put what we're feeling into words Monika can understand.

So unless the developers brought back the ability to type your responses as we used to have in the old days of MAS, I think it would be really difficult to cover everything. Though that would certainly be a good way to reuse that code, if the developers wanted to. Perhaps you type in why you're crying, and Monika tries to pick up on keywords to lead to the right responses, and if she doesn't get one that she recognizes, she can give a generic, "I'm so sorry to hear that," type of response.

Otherwise, though, I think this would be too difficult to implement in a list of options like most of the topic functions use currently.

**Comment by XTHHedgehog** [comment]
I mean, you could have a couple of broader options, like family trouble, school, people being rude, failing a test, etc. It doesn't have to be overly specific.

**Comment by lunulae** [comment]
I think these would make good topics to be able to tell her about, but I don't think they should replace the current dialogue options for that mood. Right now you can talk about what's wrong to Monika, even though she can't hear you directly. I think that would turn into something that makes you aware of your restriction in choices if we added more, rather than the intended gesture she's trying to give.

I do really like these suggestions for things folks might want to talk about though. I'm wondering if they might be good pool topics of their own.

**Comment by StayHappy1270** [comment]
hmmmm it wouldn't help much as she wouldnt rlly be able to respond but i know it could be possible to make a type in answer. (its been done with the music concerts topic)

**Comment by ThePotatoGuy** [comment]
saying exactly why is too broad. Usually telling Monika about a specific loss or personal event starts with her talking about it in a random topic.

[closing as rejected]
