### ISSUE TITLE
[Suggestion] little suggestion - Put into characters folder Image of yourself, For Monika

### ISSUE THREAD

**Issue by polios3** [Monika-After-Story/MonikaModDev#6728]
(Sorry for my English) I have a little suggestion to add an option to put in the character folder, an image called "Player" with a .png or .jpg extension. It would only check if such a file was created, which would trigger Monica's reaction. Monika will say that she does not know how to read the given file, but hopes that after the file name and the file extension it is a Player's photo. Monika would appreciate that we would like to show her our face. you create .gift, so it can't be that hard to make something like that too. Yes, any image or text file renamed "Player .jpg/.png" will work, but to keep the design simple, you don't need to check that it is actually a photo and that there is actually a face in the photo.

**Comment by Mugnika** [comment]
the responses for that would be generic at best. As of now we dont have a way to do that effectively

**Comment by fromulus** [comment]
I'd also rather we avoid letting the player input images into the mod, and even more letting Monika hang up the image somewhere in her room (as it is a feature that has been asked before) precisely because we can't check what type of images they are.

This opens too much meme potential that we can't check, and most importantly, this would likely mean we'd start seeing images of Monika with indecent images hung around her room such as p0rn or nazi symbols.

If we decide not to allow these sorts of things with Monika's nicknames, I think we shouldn't allow them with pictures, either.

**Comment by polios3** [comment]
(Sorry for my English) Sorry, you didn't understand me. I am aware that checking the picture is impossible. That's why I wrote that my idea is based on Monika not being able to read the contents of this file. Only the name and type of the file could be read by Monika. The explanation of why she can't, I leave to someone who will have some creative idea about it. It is not reading a picture, it is reading whether a given file exists. Which also takes care of Monika's reaction, because she can't read the picture, so she'll probably say, "Thank you for wanting to show me what you look like, I wish I could see it, but I appreciate it anyway. I'm sure you're handsome" or something like that.

**Comment by Rai99** [comment]
#4408

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
