### ISSUE TITLE
[Suggestion] - Space weather option

### ISSUE THREAD

**Issue by Omegafredo** [Monika-After-Story/MonikaModDev#6739]
A option in the weather select for the classic space background from the original game.
I don't know if thats an option later unlocked but if it is im sorry.

**Comment by lunulae** [comment]
The current issue with this is that the old space background functions a little differently from how MAS weathers have been made.
The space background would, for example, not be usable with any custom backgrounds because the mask is made for the spaceroom windows rather than filling up the whole screen.

Generally, the current dev consensus seems to be that if someone could remake it so that it functioned like the other weathers, it could be added, but that seems like a difficult task.

I suppose it could also be locked to only function in the default spaceroom, but I don't think that's preferable, especially if we plan on implementing decorations later that might alter the windows of the room.

**Comment by Omegafredo** [comment]
Oh okay, i just thought the space background would really fit the 'Just Monika' music and sometimes you want the original background.

Also do i close the issue now or something? Im new to suggesting and github overall

**Comment by lunulae** [comment]
You can close it yourself if you like, helps keep things clean and organized. 
In the future, if there's ever an issue you'd like to leave open for discussion or further consideration, feel free to leave it as open though. A dev will close it if/when there's nothing more to be done with it.
