### ISSUE TITLE
A question about what happens next if your idea's or other things that gets accepted 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6750]
Can anyone maybe tell me what happens next if one of your idea's and other suggestions gets accepted?

**Comment by Rai99** [comment]
You wait.

**Comment by lunulae** [comment]
Since everyone on the dev team is doing this for free as a hobby, they're not on a strict schedule for what gets done when.

Once someone's picked up a suggestion, they will code it, write dialogue, and it gets put forward in a pull request for review, revision, and testing. If it's a larger feature or more complex dialogue this step can take quite a bit of time and go through quite a few iterations.

Rest assured, your requests aren't going to disappear. There's quite a lot of new things being worked on every day. 👍
