### ISSUE TITLE
unlocking monika's sprites

### ISSUE THREAD

**Issue by SunBlade1830** [Monika-After-Story/MonikaModDev#6776]
there are some sprites in game directory and i wonder how can i unlock them? something like santa lingerie.
what are their conditions?
player's age? specific days? specific amount of affection? levels in var_dump.log ? or just by luck?

**Comment by ashyashton** [comment]
There are multiple conditions for these. For the Santa lingerie, you have to have a certain level of affection, be old enough (over 18 I believe), and you have to spend Christmas with her for her to show it to you, and you might have to do so at night rather than during the day. I think the same is true for all lingerie, just that it's on a different specific holiday than Christmas.

**Comment by winika** [comment]
I believe (correct me if i'm wrong). The Santa Lingerie is unlocked at Christmas Eve at around 8:00... you need over 2000 affection, to be 18 or over, and need sensitive mode off. That's what I remembered anyways.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
