### ISSUE TITLE
Empty log folder

### ISSUE THREAD

**Issue by PrimusRex** [Monika-After-Story/MonikaModDev#6812]
I recently reinstalled MAS and noticed that my log folder is empty. There are no issues with running the mod, just that I can't check affection or anything. I tried deleting and reinstalling it again, but the folder is still empty.

**Comment by lunulae** [comment]
How long have you been playing since your re-install? The game writes the log files as you play, they're not generated by your save. So if you deleted the old ones, you'll have to wait for new affection data to come in before you can see where you're at.

If you've been playing for a while and there are still no logs being made, there might be something up.

**Comment by PrimusRex** [comment]
I reinstalled around three days ago and have been playing every day since then, and so far there still isn't anything in the folder.

**Comment by multimokia** [comment]
Are you on Mac?

**Comment by PrimusRex** [comment]
Yes, I am on Mac.

**Comment by multimokia** [comment]
Due to odd file permission issues on Mac, logs are exported to a hidden directory elsewhere in the system. [This entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-to-view-your-log-files) outlines how to find your logs on Mac.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
