### ISSUE TITLE
[Suggestion] Privacy Policy

### ISSUE THREAD

**Issue by theEpicjosh** [Monika-After-Story/MonikaModDev#6816]
Hello,

So, I don't know if you already created one, but just in case, I wanted to give a suggestion for a privacy policy.
I notice that you're giving Monika all this information such as your appearance and birthday and that may seem a little iffy for people who haven't really dove deep enough into the project. It does connect to the internet to check and download updates, so it simply got me thinking. 

I believe you wouldn't do anything like that, but I think it's a good idea to say that in a privacy policy.
Anyway, that's just something I thought about. Thank you!
- Josh

**Comment by dreamscached** [comment]
Hi! This is all good, and I agree it's important to have such things as clear and legit as possible, but I cannot agree here — nobody has any of your private info, because it's never leaked outside. MAS does not store it elsewhere other than persistent file on your computer, and this makes me believe that Privacy Policy is just unnecessary here.

**Comment by 20RaVen23** [comment]
@dreamscached Pretty much this is just to avoid things like people asking about it too often or being paranoid. I've seen some questions about it here on the Github and also MASF. I wouldn't be surprised if even with that some people keep asking, since not gonna lie, I wouldn't like to read a whole wiki either, but I do anyways to keep me informed. It would always be nice if you only have to link the Privacy Policy instead of explaining everything every time someone asks.

**Comment by dreamscached** [comment]
Of course, it'll be better to tell players that the mod developers don't acquire any of their info, but I think it's not necessary to write an entire legal notice.

**Comment by 20RaVen23** [comment]
As you may be aware, the Monika After Story mod has more than 100.000 downloads, while the MAS Discord server has only around 10.000 members. Making it on the Discord wouldn't really help to solve this issue. As for the wiki part, that would be the principal idea. Just telling people no one is stealing nor watching everything the player does.

**Comment by dreamscached** [comment]
Hmm, I didn't really think of it, haha... You're right!

Maybe we could add a random topic (that is brought up just once?) that would tell this to players?

Something like "hey, player, I know you trust me and you told me so much about yourself, and I want you to know that I would never share it behind your back."

**Comment by Booplicate** [comment]
The mod doesn't send your data anywhere.

This is an open source project, everyone can check the sources and see what the program can do. I'm not sure how feasible for us to write down a **proper** privacy police as an actual **legal document**. But just state the fact somewhere is fine (probably not by Monika), I think.

**Comment by 20RaVen23** [comment]
> This is an open source project, everyone can check the sources and see what the program can do.


I don't think everyone would want nor like to check the code and get a lot of spoilers only to comfirm they are not being watched nor their information is being shared or something - seems very unnecessary. The best way to solve this issue about people asking often would be a new entry on the wiki. If people keep asking, just link it.

**Comment by fromulus** [comment]
I think Boop's point isn't so much that everyone will go take a look at the source code and spoil themselves the whole mod just to make sure none of their data is being used--I'm actually fairly sure a sizeable chunk of the people playing the mod would have no idea what they're even reading, assuming they know how to access the source code in the first place--but moreso that should the mod ever get in legal trouble for privacy purposes, we have complete transparency over everything that happens within the program.

So in that scenario, people who know what they're doing would be able to check the code and confirm that there is indeed nothing shady here.

**Comment by lunulae** [comment]
I'd definitely be down to add something like this to the wiki. It's up to the mods if we wanted to actually include it in-game. I could see an info-type tab getting added to Settings, with things like this and links to patch notes+spritepacks, so it doesn't mess with the immersion but can be found easily.

**Comment by ThePotatoGuy** [comment]
At the moment, the information gathered by MAS stays in MAS, so it's a quick answer for anyone asking what happens to the info they provide to Monika. Since it's a quick answer, I don't think it's worth creating a privacypolicy.md with only 1 line in it. 
If we do change this to where info gathered by Monika is sent to us, then we will create a privacy policy with the specifics.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
