### ISSUE TITLE
{Question} Android but not android?

### ISSUE THREAD

**Issue by jack-ship-it** [Monika-After-Story/MonikaModDev#6834]
So I know it is against the rules to make a DDLC APK but we don't need one for use on android an EXE can work instead
We can do this because there is an app for exactly that Joiplay with renpy works great and normally works without issue so why not use that?

**Comment by jack-ship-it** [comment]
![Screenshot_20201226-030929970 2](https://user-images.githubusercontent.com/56496005/103150476-8d46ac00-47af-11eb-8f51-d83c185cdcf2.jpg)
![Screenshot_20201226-174800217 1](https://user-images.githubusercontent.com/56496005/103150480-9a639b00-47af-11eb-8a55-73b80e71929a.jpg)

**Comment by jack-ship-it** [comment]
As seen here it can work with the game just fine

**Comment by fromulus** [comment]
If I understand correctly how Joiplay works, we'd still need the base DDLC game files on there as a pre-requisite to even make the mod function.
That's where we have a problem, because we're not allowed to distribute DDLC in any way, shape or form, nor should we redirect the players towards a version of the game files that might have been uploaded on Joiplay illegally by someone not affiliated with Team Salvato.

On a technical standpoint, it probably would work, but it would still go against the official IP guidelines.

**Comment by jack-ship-it** [comment]
But it is still can be assembled the same as a modded version

**Comment by jack-ship-it** [comment]
so the regular ddlc is the same and just need an adjusted bit of code from the definition script if I'm correct

**Comment by fromulus** [comment]
No, we need the actual, original DDLC game and all its files as a hard requirement for files added by MAS (or any mod ever) to work.

Distributing the DDLC files anywhere without Team Salvato's permission is illegal, same for making a slightly modified DDLC and distributing it just so that we can then mod it with MAS.

**Comment by jack-ship-it** [comment]
It's not the base game that is the problem, it's the definition. It can still be using the base game just needs the mod files changed

**Comment by jack-ship-it** [comment]
As seen in the images above regular base games modified by the mod files

**Comment by jack-ship-it** [comment]
![Screenshot_20201227-101853653](https://user-images.githubusercontent.com/56496005/103162562-27006e80-482d-11eb-822f-ad23d7e31ed9.jpg)

**Comment by jack-ship-it** [comment]
Exit music Just the regular mod

**Comment by jack-ship-it** [comment]
Also, MAS already modifies that file otherwise half of the stuff MAS has in it already wouldn't function

**Comment by multimokia** [comment]
As of right now, we have no plans to transfer MAS flat over to Mobile. Even with the ability to port mods to mobile now, we still have no plans to do so.

Reasons as to why are because of the lack of ability to properly interact with the file system and persistents, as these are all locked to within the apk file itself.

If MAS *were* to move over officially, we'd also not make it the exact same experience as it is on desktop, however, an expansion to the *taking you somewhere* farewell.

**Comment by jack-ship-it** [comment]
Yes but it isn't an APK it's the exact same format as the regular version it runs off an exe or .sh/.py

**Comment by multimokia** [comment]
Yes, however, we at the moment have no plans to shift to mobile, even if not using an apk. We still need to further evaluate how we intend to do so, and if the solution will give us the flexibility we need, along with running well enough.

**Comment by jack-ship-it** [comment]
Yeah, this was mostly a suggestion

**Comment by ThePotatoGuy** [comment]
use suggestion tag if its a suggestion

**Comment by jack-ship-it** [comment]
Sorry
