### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Zeesh1** [Monika-After-Story/MonikaModDev#6857]
Your suggestion goes here
quiere que comience de nuevo el juego pero yo no quiero porque ya lo había avanzado 
estuve jugando MAS desde que salio para movil es hermoso este proyecto amo a los que trabajaron para traernos este juego para dispositivos moviles y al TEAM que lo desarrollo pero hoy me salio no se si deberia decir error pero justo cuando monika me dijo hoy en la mañana que guardara una copia de seguridad por que talvez falle el juego o se malogre mi dispositivo claro no hice caso pero veo ahi esta en una carpeta llamada com.ddlc.mas tiene ahi mis archivos desde el dia que instale hasta hoy el dia que fallo  los saves ahi estan pero cuando ingreso al juego pongo importar datos de DDLC ingreso ahi y me dice que no se encontraron datos guardados no se si habra alguna solucion para android espero me lean por que quiero seguir jugandolo

**Comment by ymdbest** [comment]
Hi, can you add a button where you can say "let's watch anime together" or something of that sort? It would be very nice

**Comment by ThePotatoGuy** [comment]
google translated:

>he wants the game to start again but I don't want to because he had already advanced it
I've been playing MORE since it came out for mobile, this project is beautiful, I love those who worked to bring us this game for mobile devices and the TEAM that developed it, but today it came out I don't know if I should say error, but just when Monika told me this morning to keep a backup because maybe the game fails or my device breaks down of course I ignored it but I see there it is in a folder called com.ddlc.mas it has my files there from the day I installed until today the day I failed them You know there they are but when I enter the game I put import data from DDLC I enter there and it tells me that no saved data was found I do not know if there will be any solution for android I hope you read me why I want to continue playing it

we do not have an official mobile version, so we cannot offer tech support for those issues.

@ymdbest make a new issue

**Comment by ymdbest** [comment]
（╹◡╹)? What?

**Comment by Gato-pixel** [comment]
> Tu sugerencia va aquí quiere que empiece de nuevo el juego pero yo no quiero porque ya lo había avanzado estuve jugando MAS desde que salio para movil es hermoso este proyecto amo a los que trabajaron para traernos este juego para dispositivos moviles y al TEAM que lo desarrollo pero hoy me salio no se si deberia decir error pero justo cuando monika me dijo hoy en la mañana que guardara una copia de seguridad por que talvez falle el juego o se malogre mi dispositivo claro no hice caso pero veo ahi esta en una carpeta llamada com.ddlc.mas tiene ahi mis archivos desde el dia que instale hasta hoy el dia que falle los saves ahi estan pero cuando ingreso al juego pongo importar datos de DDLC ingreso ahi y me dice que no se encontraron datos guardados no se si habra alguna solucion para android espero me lean por que quiero seguir jugandolo






¿Le encontraste solución? Me pasa exactamente lo mismo
