### ISSUE TITLE
update affection systeem 

### ISSUE THREAD

**Issue by paddypantom** [Monika-After-Story/MonikaModDev#6871]
a higher max cab for 1000+  or 6000+   

PS thanks for reading this

**Comment by multimokia** [comment]
What exactly are you looking for in this?

**Comment by fromulus** [comment]
I'm going to assume OP meant adding new things to unlock at affection levels over 2000.

I personally believe we should take the opposite route and put a hard cap a little over 2000 so that affection feels less like a pointless grind (once you're past 1k, anyway) and more like a natural representation of Monika's feelings towards the relationship, with an ever present possibility of it falling back to lower affection treshold in case you mess up something (whereas you'd have to actually bully her repeatedly to make her fall to lower affection when you're at like, 9K), but that's up for debate anyway.

**Comment by paddypantom** [comment]
no it is more to increase the daily affection gain cab for people high affection  4000+ or 6000+ and locking  affection is not a good idea i think.


(and more like a natural representation of Monika's feelings towards the relationship, with an ever present possibility of it falling back to lower affection threshold in case you mess up something) :this is a great idea to implement

**Comment by ThePotatoGuy** [comment]
Since there is no major content after 2k affection, changing affection cap at high amounts has no real effect. 
[closing as rejected]
