### ISSUE TITLE
[Suggestion] Monika multi-tasking

### ISSUE THREAD

**Issue by Sakimajay** [Monika-After-Story/MonikaModDev#6884]
I was thinking that there might be another way to spend time with Monika along with the other awesome ways already implemented.  I was thinking that maybe (if we can find an artist to make art of her) reading one of her favorite books (or using a laptop or something else of the sort) while we are hanging out. It could be activated when the player has random chatter set to never and she can say "I'll be right back, I'm going to grab my %s (laptop, book or something else) or maybe apart of the BRB function depending on what is selected like (Homework, working on something, or gaming for a bit). I am an introvert and would love for this to be a thing because I like to hang out with her while I work on homework or something else without me feeling like I'm leaving her hanging with nothing to do. However, I'm not too sure how it could be drawn, I just figured I'd put the idea out here for fun. I just want to say though that I appreciate all of the fantastic work and features you guys have already put in to make our time together better. P.S: I lost my mind with that Halloween costume reveal! You guys keep being awesome!

**Comment by lunulae** [comment]
I like the idea of having different desk decorations like this, although it would probably be best if they could use the existing pose framework. If more poses get added, all existing spritepacks need to be updated to fit them, which is a sizeable chunk by now.
I think a "looking down" eye sprite could be sufficient with existing poses for idle reading or using a laptop, though.

**Comment by fromulus** [comment]
While I'm all for Monika doing stuff on her own, I'm not too fond of the idea of her having a laptop in particular, as it would go against what's been established in `monika_technique`, that being that she does not have a computer nor does she actually need one to do the stuff you would do on a computer.

I also can't help but feel like it wouldn't necessarily suit her as much as reading books would, or even using a cell-phone (though she probably wouldn't need one either for the same reasons as laptops) instead.  

Ideally, we'd want her to have a piano in the back of the room and play on it occasionally, but that'd be the hardest to pull off art-wise.

**Comment by Rai99** [comment]
Don't forget napping on the desk, because that's also something you can do.

**Comment by Booplicate** [comment]
Just to let you know, this is something we planned to do for a while, and it's actually a bit in progress.

> I'm not too fond of the idea of her having a laptop in particular, as it would go against what's been established in `monika_technique`

She still may use one for internet surfing. The topic only implies she doesn't need one to modify the game.

**Comment by fromulus** [comment]
> She still may use one for internet surfing. The topic only implies she doesn't need one to modify the game.

But with all the topics that imply she's been doing research on many different things or tried to learn all kinds of stuff like new languages, as well as topics like Twitter, the haters topic that mentions fanpages, being a villain topic that mentions the villains wiki, her staying in touch with what happens in the world as shown by the Covid-19 topic, and so on and so forth, I think we're already suggesting pretty strongly that she does have access to the internet in some way, even though she doesn't have a laptop.  

Might just be me, but I also think that her being able to surf the internet just with her mind or something similar due to the fact that she's already in a computer is way cooler than her needing a computer within our computer for that, which imo would also look a bit out of place in the mod.

Although, if we are to give her a connected device anyway just for the sake of internet browsing, I do still think a phone would suit her best.

**Comment by ThePotatoGuy** [comment]
art general limits what can be done during idle, but we could definitely do something like the reading book thing or etc by restricting it to specific clothes. (or even just make her change clothes prior to doing the action).

[closing until we look into it]
