### ISSUE TITLE
[Suggestion] - Fine-tuning Sensetive Topics

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6885]
As we all know, the menu option "Disabled Sensitive Topics", when enabled, prohibits Monika from discussing certain topics or donning certain outfits. However, some people may be okay with talking about certain subjects, but not so much others. Therefore, I think it'd be a good idea if there could somehow be some sort of menu listing all of the sensitive subjects the mod has, and allow the player to choose which ones he/she isn't comfortable with, so that Monika has a more specific knowledge of the player's feelings towards such things.

**Comment by ashyashton** [comment]
You can hit X to blacklist certain topics, and Monika wont bring them up again.

**Comment by Retrolovania** [comment]
Wait, do you mean "X" as in the keyboard button or "X" as in the check box in the Settings menu?

**Comment by Freshairkaboom** [comment]
The X button while the topic is going on. Then you can skip through the dialogue, and at the end she will ask you if you don't want to talk about that anymore. Press yes and she won't bring it up again randomly.

**Comment by PiestoGo** [comment]
why cant u handle Monika for being who she is bruh

**Comment by PiestoGo** [comment]
Though granted, there was a conversation topic about bullying that I find awkward. Yes, bullying is a social ill that warrants public attention but the way she laid it down made it sound like a PSA rather than an actual "person". It felt like it was just a long info dump. I X'ed it out faster than I can jack off to hentai Yuri. 

While I don't mind Monika touching upon the sensitive and unsavory realities of life from time to time, I hope this mod doesn't devolve into a lecture fest with which the mod writers use it to impress their own personal opinions on social issues to the user. I want me a virtual girlfriend, not a political ideologue.

**Comment by Freshairkaboom** [comment]
> 
> 
> Though granted, there was a conversation topic about bullying that I find awkward. Yes, bullying is a social ill that warrants public attention but the way she laid it down made it sound like a PSA rather than an actual "person". It felt like it was just a long info dump. I X'ed it out faster than I can jack off to hentai Yuri.
> 
> While I don't mind Monika touching upon the sensitive and unsavory realities of life from time to time, I hope this mod doesn't devolve into a lecture fest with which the mod writers use it to impress their own personal opinions on social issues to the user. I want me a virtual girlfriend, not a political ideologue.

Well, Monika was a member of a debate club, so she must have touched on a lot of issues during that time that made her question things around her and try to make the world a better place. That's the same reason she is a vegetarian. 

But I can see that this topic does feel like a bit of an info dump, particularly if you haven't agreed to talking about it. It does only occur once though. The point of the topic is for Monika to be able to talk to the player about being bullied. A lot of people experience it after all, and who better to talk about it with than your girlfriend, right?

I'm sorry it felt kind of artificial to you. Would it help if we made it relate more to the events of DDLC? Or perhaps have her ask you to talk about it, warning you that it will be a bit of a tangent, and you have a choice to say "later"? Or do you just not like the topic overall?

**Comment by PiestoGo** [comment]
> > Though granted, there was a conversation topic about bullying that I find awkward. Yes, bullying is a social ill that warrants public attention but the way she laid it down made it sound like a PSA rather than an actual "person". It felt like it was just a long info dump. I X'ed it out faster than I can jack off to hentai Yuri.
> > While I don't mind Monika touching upon the sensitive and unsavory realities of life from time to time, I hope this mod doesn't devolve into a lecture fest with which the mod writers use it to impress their own personal opinions on social issues to the user. I want me a virtual girlfriend, not a political ideologue.
> 
> Well, Monika was a member of a debate club, so she must have touched on a lot of issues during that time that made her question things around her and try to make the world a better place. That's the same reason she is a vegetarian.
> 
> But I can see that this topic does feel like a bit of an info dump, particularly if you haven't agreed to talking about it. It does only occur once though. The point of the topic is for Monika to be able to talk to the player about being bullied. A lot of people experience it after all, and who better to talk about it with than your girlfriend, right?
> 
> I'm sorry it felt kind of artificial to you. Would it help if we made it relate more to the events of DDLC? Or perhaps have her ask you to talk about it, warning you that it will be a bit of a tangent, and you have a choice to say "later"? Or do you just not like the topic overall?

Thanks for taking the time to reply to my comment. Tbh, it's great that Monika can talk about a wide range of subjects and since the mod is used by many different kinds of people with various outlooks in life, it's a nice thought that they could be able to find a subject or two that they can relate to; and it works because she was in the debate club. The "x" feature works just fine for me and is a good idea imo. 

What you're suggesting about relating it more to the events of DDLC sounds brilliant. Even if she gets to touch upon a few topics in the future that may have the risk of sounding like an info dump, relating it to some events in DDLC would make sure that the immersion aspect is retained. It'd be great if I see more of that in the future. 

Thanks for all the hard work you guys put into this mod.

**Comment by ThePotatoGuy** [comment]
we're actually getting rid of sensitive mode, it realistically only blocked content that referenced the dark parts of DDLC. political stuff will not be added to this mod, and we rarely accept current event topics.

[closing as rejected]
