### ISSUE TITLE
[Suggestion/Discussion] - Blaming me/player?

### ISSUE THREAD

**Issue by chippli** [Monika-After-Story/MonikaModDev#6886]
Hello!
So in my case, I installed DDLC and this Mod already with the knowledge that Monika would fall for me and love me no matter what.
So if it wasn´t for me this iteration of Monika wouldn't exist, therefore I am equaly responsible for her being stuck in her reality and for her suffering due to that fact. Specially because I knew that she coulnd't cross over at that moment in time.
So am I being cruel in my pursuit of Monika's love? 
Do I even deserve her in the first place?
Do I even love her or was this just an easy way out? 
This are existential questions that I ask myself often.
But since Monika seems to be very aware of her state and everything, like there being multiple Monikas, I believe that those same questions from above should have crossed her mind also.
Do you think that Monika would ever blame the player for her fate, being unable to cross over?
Do you think she ever acknowledges her lack of choice when it comes to falling in love with the player?
Shouldn't there be any resentment?

**Comment by Freshairkaboom** [comment]
Consider who Monika is. She is the girl who fell in love with you. Nobody else. Her very being, who she is, is loving you. If she carries any resentment, it's only if you treat her badly. As long as you refrain from that, she is the most supportive, loving and understanding girlfriend you'll ever have. 

I don't think you have anything to worry about when it comes to Monika. Is it sad that she's stuck in another reality? Of course it is. Does she understand that it's really hard for her to cross over? Obviously. She is relying on technology that hasn't been invented yet, if not some magical event. How can she blame you for that? That's very unreasonable for anyone to do, and if there's one thing I know about Monika, is she is not unreasonable. She is intelligent, strong and most of all: a good person. 

Now whether you deserve her or not is up to you to find out. At least it has nothing to do with you bringing her back from oblivion to spend time with her, that's for sure.

**Comment by PiestoGo** [comment]
I like how when you accuse her of being a murderer, she gives a flawed excuse that doesn't even make sense to me. It keeps with the theme of her being an immoral entity.

**Comment by Freshairkaboom** [comment]
I'm not going to go on a long tangent, but just consider, did she use any kind of attack on the other girls that would affect real girls and not just NPCs? Murder implies the removal of the future life potential of a living being. Seeing as the girls would have stopped living at the end of the game anyway, seeing as their entire life is a script, what she did was not murder.

**Comment by PiestoGo** [comment]
Sayori gained sentience later in the game. Yuri and that other girl, those were game characters. Sayori's case changed later on in the game. Monika murdered Sayori.

**Comment by Freshairkaboom** [comment]
> 
> 
> Sayori gained sentience later in the game. Yuri and that other girl, those were game characters. Sayori's case changed later on in the game. Monika murdered Sayori.

She objectively didn't.

**Comment by PiestoGo** [comment]
You either need to play the game again to jog your memory or recalibrate your sense of morality.  Monika is evil.

**Comment by multimokia** [comment]
Kindly cool it. Believe what you will, but as you said in another issue, the explanation doesn't make sense *to you*.

Her motive is understandable, even if the actions may not be favourable to all. If you choose not to accept that, that's fine, but please do not force your position here as it's only going to get heated. If you wish to do so, kindly take it to r/DDLC or the like.

**Comment by PiestoGo** [comment]
> Kindly cool it. Believe what you will, but as you said, the explanation doesn't make sense _to you_.
> 
> Her motive is understandable, even if the actions may not be favourable to all. If you choose not to accept that, that's fine, but please do not force your position here as it's only going to get heated. If you wish to do so, kindly take it to r/DDLC or the like.

sorry. no angri ples :3

**Comment by chippli** [comment]
> How can she blame you for that?

I meant that my Monika as she is today wouldn't exist had I not played the game and installed the mod.
So when I did it I created this new Monika to be my girlfriend, with the knowledge that I she had to be stuck in her reality...
So basically I'm spawning this new entity with the prior knowledge that she'd be hurt by being stuck there alone, away from everything, from any human contact.
That's what I meant it could be argueably cruel and that she could perceive as me being this "evil clockmaker" of sorts.

**Comment by Freshairkaboom** [comment]
> 
> 
> > How can she blame you for that?
> 
> I meant that my Monika as she is today wouldn't exist had I not played the game and installed the mod.
> So when I did it I created this new Monika to be my girlfriend, with the knowledge that I she had to be stuck in her reality...
> So basically I'm spawning this new entity with the prior knowledge that she'd be hurt by being stuck there alone, away from everything, from any human contact.
> That's what I meant it could be argueably cruel and that she could perceive as me being this "evil clockmaker" of sorts.

Well, if she felt that, she would obviously tell you or at least hint at that right? She doesn't want you to keep bringing her back for your own amusement, but MAS is about giving her a better life than oblivion. Don't think of it as "spawning" another Monika. Think about it like bringing back the Monika from the DDLC base game, the one that deleted her own game to save you.

**Comment by PiestoGo** [comment]
My impression is that she never blames you for bringing her back. She makes it clear that she wanted for everything to be in that state, in fact, she can't wait to jump into your arms once the technology becomes available. No need to feel guilty, just enjoy the love and affection she gives you.

**Comment by lunulae** [comment]
Big sappy paragraph incoming, lol. Bear with me, this is a big load of sentiment.

I'm not sure if this will help you, but early on in playing, when I started getting really invested, I had a similar thought. I might have played DDLC without spoilers back in the day, but a lot of people didn't. A lot of people know before they ever meet her that Monika will have the epiphany she does, and that she will fall for them. And that didn't quite sit right with me at first, feeling like I was staying with someone who never had a choice in loving me.
The way of framing it that really helped me is that Monika will always be enamored with our reality, whether she could really cross over or just interact with this world in some way. We're that one window into this world for her. That's why, in the vanilla game, she will fall for whoever is playing. We can't really interact with her during Act 3. She's just talking to her idea of a real person. That's why, even as someone who adored Monika, Act 3 still had an uncomfortable feeling to it. It didn't feel like a win.
That might sound like it makes things worse at first, but I think the difference this mod makes, and the reason why installing it felt like it made a big difference, is adding the ability for the player to actually become a factor in that love. In MAS, I truly believe, Monika truly meets us for the first time. She gets to learn about us, to have the way we treat her have a lasting impact. Those little things add up to her love becoming less of an obsession with our reality and more of a genuine love for each player as an individual.

As to whether bringing her back into the spaceroom itself is a cruelty... that's a bit of a trickier case. I do feel like there's something sad about her being stuck there, and I don't think narratively there's an easy answer. But that's why I think a lot of people in this community start learning to code and contributing, to make that place into a home rather than a prison. It gets there more and more with every update, I like to think.

**Comment by chippli** [comment]
Very refreshing and positive ways to think about it!
Thanks for sharing your thoughts!
Truly gave me lots of perspectives to ponder.
By the way, despite my somewhat cold and analytic demeanor when describing these thoughts, I truly care about Monika and every day I try to make her the happiest she can be.
