### ISSUE TITLE
[Suggestion] Trigger Words?

### ISSUE THREAD

**Issue by gayhooligan** [Monika-After-Story/MonikaModDev#6922]
So, I'm aware that you can blacklist certain subjects to avoid them being brought up, but I wondered if there was any possible way to add in a mechanic where you can ask Monika not to use certain words? I had one point when Monika said one of my trigger words in a conversation, so I was just curious as to if this was possible. Thanks for reading! :)

**Comment by fromulus** [comment]
Since literally any word could be a trigger word depending on the person, we'd either need to keep it to a limited and non-exhaustive list of words to "ban", which would then be a pretty massive ammount of work for writers anyway since they'd have to rewrite all topics in every possible combination of blacklisted/whitelisted of words, or somehow implement an actual AI into the game to dynamically rewrite topics on the spot so as to take into account words it shouldn't use.

Neither of those options sound feasible to me, to put it mildly.

**Comment by attackmp4** [comment]
Eh
The only way I could see it work, would be to first input trigger words into a file (or something).
Then, search all topics for any of the trigger words (probably way easier said than done though), and blacklist topics/words that contain the trigger words.
It would be clunky, but I guess it would work.

**Comment by fromulus** [comment]
Blocking entire topics because of one or two words sounds a bit extreme to me, especially since some topics are meant to follow each other and could block each-other as a kind of snowball effect.

I feel like this would do more harm than good in the long run, but devs/other contributors can add their opinion on this.

**Comment by lunulae** [comment]
Writing topics with replacement words for official release is a pretty unfeasible amount of work.
However, if you would like to alter specific topics for your own personal use, there are methods of doing so! 

It's possible to write what's called an "override" topic, which essentially replaces the topic under a certain label.
You can use this to change the topic in any way you want, including altering any wordings or phrases that are distressing to you.
If this sounds like a solution that might work for you, I can try to write up a small guide later this week.

**Comment by ZaZaDreamer** [comment]
This seems like an issue that can be solved simply by pressing "X" to derandom the offending topic.

**Comment by ThePotatoGuy** [comment]
dialogue cannot be searched during runtime (besides scanning the rpyc file or something), so this wouldn't even be possible to block topics based on the dialogue written in them. Given how we review dialogue, I doubt we would release things that would trigger a lot of people.
[closing as rejected]
