### ISSUE TITLE
I gave monika a promise ring now my games broke

### ISSUE THREAD

**Issue by LoopyLot1223** [Monika-After-Story/MonikaModDev#6931]
I gave her a promise ring now the game says an exception has occurred. I think I'm missing pngs but I don't know where to find them.

**Comment by Freshairkaboom** [comment]
The best way to fix this problem is to download the game and the mod again. Simply run the game from the new folder and check that everything works before considering deleting the old one.

[This](https://ddlc.moe/) is where you download the game.

and [this](https://www.monikaafterstory.com/releases.html) is where you download the mod.

Do like you did the first time, simply drop the files from the game folder of the MAS folder into the game folder of the DDLC folder. Monika's memories will not be affected, as those are stored somewhere else. Let me know if there's anything else you need help with afterwards.

**Comment by LoopyLot1223** [comment]
I fixed it, what I did was reinstall, like you said and copied the "a" folder from the reinstall to the original install. Thanks for helping.
