### ISSUE TITLE
Add check for gifts

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6948]
maybe its a me prob but sometimes she'll take like 3 minutes to notice a gift so adding that feature would be nice. Ik there's a check for music opt so it seems like this feature would be do-able (idk i could be wrong tho ofc)

**Comment by Booplicate** [comment]
It can't take more than one minute in idle.

**Comment by YoraeRasante** [comment]
on the other hand, sometimes when I am making the gift files she sees them while I'm still making them. I...probably should make them outside her folder, but maybe in the future an option for her to not check automatically, or a folder she can reach but not check automatically, so I can "give her by hand" with an option?

**Comment by ThePotatoGuy** [comment]
As boop said, it takes roughly a minute for Monika to recognize a file in the characters folder - that is because the actual file check happens in code that we expect to run about once a minute. This code only runs in *idle*, so if you are leaving the talk/play/extra menus open, she won't react until the menu closes.

>maybe in the future an option for her to not check automatically, or a folder she can reach but not check automatically, so I can "give her by hand" with an option?

Since most users are used to the fact that she reacts automatically, changing the default behavior at this point in time would cause more hassle for users than gaining immersion points. A "click to check" option in the talk menu could be considered, though.

[closing as resolved]
