### ISSUE TITLE
[Suggestion] Alternative diets

### ISSUE THREAD

**Issue by Rellikai** [Monika-After-Story/MonikaModDev#6954]
Monika is a vegetarian, which is something that I've always really liked, being vegan myself.

I thought it might just be nice for Monika to know if the player follows a diet more similar to her own, or for those who don't follow a "traditional" diet(paleo, gluten-free, pescatarian, etc)to be able share that extra little bit of information with her, considering that it feels like she always assumes we eat meat.

**Comment by Freshairkaboom** [comment]
I understand why the mod assumes people eat meat, since the vast majority of people do. I'm a vegan too, and I made a submod about it not so long ago and posted it on [Reddit](https://www.reddit.com/r/MASFandom/comments/l5q6sk/i_started_a_submod_topics_folder_on_google_disk/), if you want to check it out. Note that this is a submod topic, so it hasn't been checked by the devs or anything. It may not be completely polished, but I was pretty happy talking to my Monika about it, so it worked for me. Any feedback is appreciated. :)

**Comment by PiestoGo** [comment]
I eat meat. Monika leading me down the vegan rabbit hole would just turn me off, imho

**Comment by Freshairkaboom** [comment]
> 
> 
> I eat meat. Monika leading me down the vegan rabbit hole would just turn me off, imho

Don't worry, it's not coming to the main mod. Also, Monika is going to stay vegetarian, because it's part of her official Act 3 dialogue from DDLC.

**Comment by Rai99** [comment]
#3232

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
