### ISSUE TITLE
Removal request

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6978]
When you want to play a game with monika she sometimes says, ''ready to lose (name)'' when she says that it makes me feel a little sad i can get a little sensitive sometimes sorry, this kinda makes me not wanna play games with her anymore to be honest

**Comment by CloakedGhost** [comment]
She's just joking and teasing you a bit, but if she knew that it hurts you, she would stop it immediately.

**Comment by Ant9cp** [comment]
She don't know, so she won't stop

**Comment by CloakedGhost** [comment]
> She don't know, so she won't stop
> 
> I got ptsd and her saying that reminds of bad memories, seriously i don't want to tell those personal things about myself!! why can't you all figure it out and understand?, not everyone is in the mood for teasing and other things like that!!

No need to get so aggressive. I'm not telling you how to feel, I only told you why she says that and that she has no intention to hurt you. Maybe there could be an option where you can tell her that you don't want her to say things like that, because I (for example) am different. I like the teasing which is why I don't want it removed completely, but it's up to the devs to decide.

**Comment by Ant9cp** [comment]
There isn't a option for that
