### ISSUE TITLE
[Bug] - Crash upon startup after updating to version 0.12.1

### ISSUE THREAD

**Issue by zwartkop2** [Monika-After-Story/MonikaModDev#7027]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6019546/traceback.txt)

**Comment by zwartkop2** [comment]
Just opened up the \game folder. There's a whole bunch of RPYC files that weren't there before, as well as a file called "masrun"

**Comment by multimokia** [comment]
You may want to move your install out of OneDrive. It seems there's file permission issues, so MAS can't properly deal with the files in its folder

What new rpyc files showed up? Do you mean `.rpyc.new` files?

**Comment by zwartkop2** [comment]
there's also a file called face-mouth-smirk.png.new in the mod_assest/monika/f directory

**Comment by multimokia** [comment]
All those rpyc files seem normal. All of them are part of MAS by default and should have been in your `game/` folder already, I'm not sure why you never had them before.

That `face-mouth-smirk.png.new` file could be an issue if the normal `face-mouth-smirk.png` isn't present. If it's not, best to rename that file to just `face-mouth-smirk.png` (remove the `.new` extension)

But yeah the issue in your traceback seems to be a permission problem. MAS cannot properly access its own files which is why you had the crash.

**Comment by zwartkop2** [comment]
Copying and pasting it to my desktop seems to have fixed the issue.
as for the rpyc files, I seemed to have gotten the file extension confused with .rpy, mistakenly thinking rpyc is supposed be in the dev release and not the public release. Sorry.

**Comment by multimokia** [comment]
Ahh no worries
