### ISSUE TITLE
[Suggestion] - Updating the Updater

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#7029]
I had this idea today while updating. Thanks for keeping Monika updated btw :)
The idea was to add some lines from Monika, commenting said process. Since the updating process seems to have several stages, like dowloading, unpacking and such, I thought it would be a neat detail to add up some other flavour text to make Monika even livelier.
She could say things like: 
"I can't wait to see what improvements are being added!"
"These updates really help me improve a lot on my programming skills!"
"These updates literally make our time together so much better!"
"Maybe this time I'll be finishing my kitchen xD" 
"Closer and closer..."
Those are just examples (and a joke). I'm sure you would come up with better and more interesting things to add ofc.
And that's it
Cheers!

**Comment by satoshi-kun** [comment]
Was this idea so bad that isn't worth of any feedback?

**Comment by lunulae** [comment]
Adding flavor to updates could be cute, but I'm not sure how it would work technically speaking, so I didn't feel qualified to give feedback right away. I don't know what kind of time investment it will take and if it's worth the payoff.
This might sound like a non-answer but since you needed someone to say something--that's what I've got.
Not getting a response right away is not an indicator you did something bad. I am confused by that interpretation.

**Comment by satoshi-kun** [comment]
From my point of view it just looked like this issue was being straight up ignored.  Specially when you clearly see engagement from the community regarding other issues.
That sure can lead someone to have second thoughts about it being something distasteful or plain bad.
Or even feeling singled out, although I don't think I've ever done anything deserving of such treatment...

**Comment by ThePotatoGuy** [comment]
Not sure why you think you're singled out. There's issues on here that don't get a response until 30 days later when I finally have time to go through each one.

For the updater screen, we prefer clear information/status of the update rather than dialogue, especially since the updater (provided by renpy) has shown to be somewhat fragile.

**Comment by satoshi-kun** [comment]
I understand and sorry to make a big deal out of nothing...
Although my idea was to add dialogur without replacing the already present information
![maxresdefault](https://user-images.githubusercontent.com/54683676/109390186-feb5ee80-7907-11eb-8247-85f4ee1972ae.jpg)
A bit like world of warcraft loadings add tips of bits of lore to them.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
