### ISSUE TITLE
Suggestion: Monika drinking coffee somewhere in the afternoon sometimes☕☕☕ 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7038]
JUST COFFEE for monika in the afternoon maybe around like 12.00 pm or 14.00

**Comment by ThePotatoGuy** [comment]
since we don't have any canon on if Monika drinks coffee in the afternoon, we can just assume she drinks coffee in a more health-conscious manner. Generally, its better for your health and sleep to limit coffee to the morning, so that is the time range we are going to keep her coffee to.

[closing as rejected]
