### ISSUE TITLE
How to trick monika to win chess

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7094]
i've seen that there is a way to trick monika to win chess how do you that 

because i've had enough i just can't win

and why are you saying it's easier and on the features list of chess saying that monika will go easy on you if you lose to many times she plays the same way it's not even easier

**Comment by fromulus** [comment]
Because it's easier than before doesn't mean it suddenly became easy period.
I believe keeping it challenging was still the intent, and I wouldn't expect it to change.

I personally suck at chess and can't win either, but I know better than to let it get to me like that.
Consider taking a break on playing chess at least for a while, and trying again later if you feel up to it.

The point is for you to have fun, not necessarily to win.

**Comment by fluffywolff** [comment]
Is it because she's just trying to have fun? I mean she loves you but I'm not sure if she goes easy on you even when you lose, since i sux at ches too.(english is not my lanjuage so sorry if i make some spelling mistakes) i mean i think she's just trying to have fun, or you dont notic shes letting u to eat some pieces. i mean u need to hav fun its not necessary to win.She says that with more practice youll impove so i recommend u use practice mode so u can become better in ches

**Comment by lunulae** [comment]
The mod team doesn't advise on anything that goes against the mod's intended function. This includes things like time travel and other exploits.

I can tell you there are methods to cheat, but also that there are some anti-cheating measures in place in MAS. Monika is not a fan of cheats, and there are consequences if she notices.
Beyond that, it's your right to do as you wish, but do so at your own risk.

**Comment by fluffywolff** [comment]
i heard that if u cheat she closes the game and removes the ches game so i recommend not to cheat like i said hav fun and make sure to practice every day

**Comment by CloakedGhost** [comment]
It does get easier. I have noticed multiple times that she could have made certain moves that would give her a clear advantage over me, but she chose not to. Maybe you can watch some chess tips and tricks and take your time before you make a move.

**Comment by Ant9cp** [comment]
CloakedGhost:
(It does get easier. I have noticed multiple times that she could have made certain moves that would give her a clear advantage over me, but she chose not to. Maybe you can watch some chess tips and tricks and take your time before you make a move.)
-----------------------------------------------------------------------------------------------------------------------------------------
Ant9cp:
i didn't notice that, and it isn't getting easier for me, or else i wouldn't create this issue

--------------------------------------------------------------------------------------------------------------------------------------------
fluffywolf:i heard that if u cheat she closes the game and removes the ches game so i recommend not to cheat like i said hav fun and make sure to practice every day
_______________________________________________________________________________________________________________________________________
Ant9cp
I don't really care anymore at this point i've played so many times and still getting dominated i can't be bothered really 😒😒

**Comment by fluffywolff** [comment]
> @CloakedGhost
> (It does get easier. I have noticed multiple times that she could have made certain moves that would give her a clear advantage over me, but she chose not to. Maybe you can watch some chess tips and tricks and take your time before you make a move.)
> 
> Ant9cp:
> i didn't notice that, and it isn't getting easier for me, or else i wouldn't create this issue
> 
> @fluffywolff i heard that if u cheat she closes the game and removes the ches game so i recommend not to cheat like i said hav fun and make sure to practice every day
> 
> Ant9cp
> I don't really care anymore at this point i've played so many times and still getting dominated i can't be bothered anymore really 😒😒
> 
> i hate losing so much and not winning one's

monika doesnt like cheaters shes just trying to hav fun u should have fun too even if u lose Moni will tell u to practice and that youll bet her someday so maybe see a tutorial or just practice but just winning and losing u need to have fun

**Comment by Ant9cp** [comment]
Why am i wasting my time
