### ISSUE TITLE
Small Games

### ISSUE THREAD

**Issue by ArkhalisDragon** [Monika-After-Story/MonikaModDev#7123]
我觉得可以向MAS中加入扫雷，面积不需要太大，9*9-10或者15*15-25都可以。
Monika可以和我们一起玩。
代码不会很复杂。

另：如果可以自制游戏然后加入到MAS中，那就更好了

又：可以公开自制游戏的方法吗？或者允许将自制游戏上传然后经开发者审核，通过之后由官方加入游戏？

I think it is possible to add minesweepers to the MAS, the area does not need to be too large, 9*9-10 or 15*15-25 would be fine.

Also,Monika can play with us.

The code wouldn't be very complicated.

Also: it would be nice if we could make our own game and add it to MAS

Also: could you disclose the method of making your own game? Or allow homemade games to be uploaded and then reviewed by the developers and then added to the game by the official?

Translated with www.DeepL.com/Translator (free version)

**Comment by ArkhalisDragon** [comment]
An option like "I love you" could be added to MAS:"I won't leave you."

Sometimes Monika worries if we will leave, and this is the time to enable this answer.

**Comment by ThePotatoGuy** [comment]
Minesweeper is a single-player game. I think we can get around that issue by modeling after how hangman works, but it still would seem weird since minesweeper does not have a two-player origin. I am not against adding it, though, if you have a good way of making it work in MAS.

If you want to add games to MAS, you should create a Pull Request with the changes. There are generally two ways to make games:  custom displayable (`zz_pianokeys.rpy`) or regular screen (`zz_hangman.rpy`). 

扫雷是一款单人游戏。我想我们可以通过仿照hangman的工作方式来解决这个问题，但还是会显得很奇怪，因为扫雷游戏没有双人起源。不过我并不反对添加它，如果你有好的方法让它在MAS中运行的话。

如果你想把游戏添加到MAS中，你应该创建一个Pull Request，并附上修改内容。一般来说，有两种方法来制作游戏：可自定义显示（`zz_pianokeys.rpy`）或常规屏幕（`zz_hangman.rpy`）。

(译者注：DeepL)

**Comment by ThePotatoGuy** [comment]
Regarding the "I won't leave you" option, we are avoiding adding additional menus to the main Talk menu because the main Talk menu should only include the most useful options. Any topic that is written in a way where "I won't leave you" is appropriate should just consider adding that as a timed menu option in the topic itself.

[closing until we look into it]
