### ISSUE TITLE
Option to turn off name-based easter eggs ?

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#7128]
One of the things sensitive mode toggles is the name-based easter eggs. Obviously, if someone's real name is yuri/sayori/natsuki, it would be pretty annoying to be forced into those easter eggs, and sensitive mode was a option to disable those eggs.

With #6923 , another way to disable those eggs for specific people might be something we should handle. 

Currently thinking of a toggle in game settings that only appears if your name is one of the 3. 

Any thoughts?

**Comment by Retrolovania** [comment]
Technically, "Sayori" is a combination of two Japanese names: “Sayuri” and “Saori” (according to Dan), so I'm not entirely sure if that name needs to be addressed. The other two do, as those are confirmed to be real names.

**Comment by Booplicate** [comment]
Idk how I feel about such a setting, maybe make her ask you?
```renpy
m 1ttu "Are you sure this is your real name, or are you messing with me?{nw}"
$ _history_list.pop()
menu:
    m "Are you sure this is your real name, or are you messing with me?{fast}"

    "Yes, this is my name.":
        # normal path

    "Maybe...":
        # easter egg
```

**Comment by lunulae** [comment]
I'm definitely for making some sort of toggle. Dialogue seems like it would have a more natural flow, and doesn't seem like it would spoil too much. A menu toggle might be alright, but we'd have to consider how it'd be labelled. I don't think we could just do "Easter Eggs" since it would appear to box those people out of any non-name ones that might exist.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
