### ISSUE TITLE
Dialogue Suggestion: Different Dere Types

### ISSUE THREAD

**Issue by saltedgator** [Monika-After-Story/MonikaModDev#7150]
There is already one topic about tsunderes in the media category. There aren't too many other conversation topics there-- so maybe Monika could talk about some other deres? including yandere (relate it to Yuri, joke about how maybe the player would be interested in someone totally devoted to them) kuudere (the quiet, demure type) himedere (royal and snooty) Etc. She could even ask what your preference would be (but of course, one of the options would be "you, Monika!" )

**Comment by TwistDraw** [comment]
Monika's original chapter 3 spaceroom dialogue brought up tsundere's in relation to Natsuki. I'm not sure if that particular dialogue was cut from the mod though, since I've never seen her bring it up. I have gotten the Yandere dialogue in relation to Yuri though.

One way to organically introduce other dere-type in depth (and provide more interaction) would be to place a branching choice option in the Yandere topic. At one point, Monika says something like:
m: I'm sure you've realized there is one girl in the Literature Club who fits that description perfectly.
m: And that person is...

At which point, you could have the choice to interject with different names. Say Yuri (or say nothing at all) and she continues the standard dialogue. Say Natsuki and she could go into Tsunderes. Say Satsuki and she talks about Derederes.

And of course say Monika and she either gets a bit quiet and introspective, a little hurt, but also seriously considering it if your affection is high enough, gets very upset if you already told her you thought she was evil, and laugh it off as just 'killing characters in video games' again if your affection is below a certain threshold.

Regardless, afterwards it could unlock other dere-tropes as topics to bring up.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
