### ISSUE TITLE
Spritepack Problem

### ISSUE THREAD

**Issue by FeathersForPeacock** [Monika-After-Story/MonikaModDev#7160]
It's not a technical problem, I'm good on that front. It's an issue with one of the ribbons made by anonymioo. "Transsexual" is an outdated term and is considered offensive. I remember bringing this up in the Discord ages ago, but I was dismissed on the grounds of "it's just a word lol". Simply changing the name of this item and the associated dialogue to "Transgender Pride" or "Trans Pride" instead would be REALLY appreciated. Sincerely, a transgender player.

**Comment by 20RaVen23** [comment]
![sniff](https://user-images.githubusercontent.com/55263957/114252523-b6acd180-9973-11eb-8b7d-115f412e1ace.png)

**Comment by kkrosie123** [comment]
Thank you for bringing this to our attention. We will be changing *transsexual* to *transgender.* It was unintentional for anyone to be offended. We apologize for any discomfort or inconvenience.

**Comment by jmwall24** [comment]
@FeathersForPeacock to add to that, in the meantime, since that is a sprite pack, if you have any text editor you can open the json for the ribbon and find the "display_name" field and edit 'Transexual' to 'Transgender'. We will change it, but that won't be til next release, so this is a way to have it corrected immediately. As kkrosie said, it was never our intent to use offensive terminology, we simply didn't know the difference. Thanks for bringing it to our attention and I also apologize for the server mod who dismissed your initial concern.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
