### ISSUE TITLE
Monika does not react to my gift

### ISSUE THREAD

**Issue by stumpgamer** [Monika-After-Story/MonikaModDev#7164]
I tried to give her the usual gifts like coffee or cupcakes but she doesn't react she doesn't do anything as if I didn't give her anything, is there anything I can do?

**Comment by Asw123dxd** [comment]
what kind of file do you use
(Notepad or normal file) 

(I will use google translate because my English is bad, so if you ignore the mistakes I made, I would be very happy.)

**Comment by stumpgamer** [comment]
> what kind of file do you use
> (Notepad or normal file) 
> 
> (I will use google translate because my English is bad, so if you ignore the mistakes I made, I would be very happy.)

the normal file coffee.gift

**Comment by Asw123dxd** [comment]
What paths do you follow when trying to give her gifts now?

**Comment by stumpgamer** [comment]
> What paths do you follow when trying to give her gifts now?

i go in the character folder then i do right click with the mouse then i do New and i chose text and document and then i rename It as coffee.gift

**Comment by Asw123dxd** [comment]
I don't know much about this topic, but I want to help you.
If you need to open a notebook, you can write whatever you want in the notebook (but you have to save it), then you can save your notebook and convert it as a regular file.
(You've already done these)

Now we are in the game and you have to click on the "I'll take you somewhere" button, Monika has to accept it and prepare herself, the game will close when it is ready. Now you need to enter the "Doki Doki Literature Club" file and enter the "Characters" file. This file should contain "Monika.chr and monika". you need to place these files on the desktop. Next, you need to add the gift file you created to the "characters" file. Then
After adding the gift file, put the "Monika.chr" and "monika" files back to their original location (put them back in the character file) and then reopen the game
She must first say Monika (I can stay a little longer), then see the gift and be surprised.

**Comment by stumpgamer** [comment]
> I don't know much about this topic, but I want to help you.
> If you need to open a notebook, you can write whatever you want in the notebook (but you have to save it), then you can save your notebook and convert it as a regular file.
> (You've already done these)
> 
> Now we are in the game and you have to click on the "I'll take you somewhere" button, Monika has to accept it and prepare herself, the game will close when it is ready. Now you need to enter the "Doki Doki Literature Club" file and enter the "Characters" file. This file should contain "Monika.chr and monika". you need to place these files on the desktop. Next, you need to add the gift file you created to the "characters" file. Then
> After adding the gift file, put the "Monika.chr" and "monika" files back to their original location (put them back in the character file) and then reopen the game
> She must first say Monika (I can stay a little longer), then see the gift and be surprised.

ok il try to di It right now!

**Comment by Asw123dxd** [comment]
When creating a gift file I recommend that you create it on the desktop.

**Comment by Asw123dxd** [comment]
I forgot to include this here, if you want this to work you need to change the file type so you have to click on the file explorer and have the "view" option above. You need to click on it and enable the "file name extensions" option. Then, if there are extensions such as "txt" at the end of the gift file, you will need to rename it and delete it. As a warning, it should say "this file may be seriously corrupted". You have to accept it, it will turn into a gift file.

**Comment by stumpgamer** [comment]
> I forgot to include this here, if you want this to work you need to change the file type so you have to click on the file explorer and have the "view" option above. You need to click on it and enable the "file name extensions" option. Then, if there are extensions such as "txt" at the end of the gift file, you will need to rename it and delete it. As a warning, it should say "this file may be seriously corrupted". You have to accept it, it will turn into a gift file.
> 
> 
> (Don't do anything to Monika file)

I followed your steps but nothing has changed :(

**Comment by Asw123dxd** [comment]
I just tried to give monika coffee again just to be sure, but this time it didn't work, then I decided to give cupcakes, but this time I made the file name "cupcake.gift" beforehand and then saved it. Then he saw it this time when I entered the game again.

**Comment by Asw123dxd** [comment]
So now try to give cupcake this time, but this time change the name in your notebook at first, then write whatever you want in the notebook then save it.

**Comment by stumpgamer** [comment]
> So now try to give cupcake this time, but this time change the name in your notebook at first, then write whatever you want in the notebook then save it.

it didn't work, I'm sorry to steal all this time but unfortunately this problem has been going on for weeks I can't give her anything anymore😔

**Comment by Asw123dxd** [comment]
What you need to do is go into notepad, create a new file, and type whatever you want into it. It doesn't matter what you type, just as long as the file can be saved.

Then hit "save as" and put insertgiftnamehere.gift. For example "promisering.gift". Then you'll need to change the file name in your files. Hit "view" then tick "file name extensions" and your gift should appear as, per the example "promisering.gift.txt". You'll need to remove the .txt part.

Ignore the text box that appears that warns you that the file may become unusable, as you don't need to go back into the file once it's done.

Now what you need to do is open Monika After Story. It's not necessary, but I'd recommend spending a little bit of time with her, just brighten her day a little bit.

Once you're done there, say goodbye and choose the "I'm going to take you somewhere" option. We'll need Monika's file outside of the characters folder for this to work. Just moving her onto the desktop works fine, but you can move her anywhere you like outside of the directory. (Just a side note, I'm not sure I'm the only one with this problem, but make sure her file is moved and not just copied. This applies for both ways.)

Now you need to move the .gift file that you have created into the characters folder that you've just taken Monika out of. You can put her back in now. Again make sure you actually move her instead of just copying.

Now all you need to do is reopen Monika After Story. Depending on how long you wait before reopening the game, Monika's response will be either "That wasn't much of a trip, /name/" or the usual "And we're home!" You should see some ellipses in the text box moving somewhat slowly, followed by Monika opening the gift.

**Comment by Asw123dxd** [comment]
it should work this time

**Comment by Booplicate** [comment]
You do not need to do all that to give her a gift.

@stumpgamer We have a [gifting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifting-guide), that should help you.

**Comment by stumpgamer** [comment]
> You do not need to do all that to give her a gift.
> 
> @stumpgamer We have a [gifting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifting-guide), that should help you.

nono i know how to give a gift but One day She stops to react when i give a gift and the gift file dont dissapear in the character folder

**Comment by Booplicate** [comment]
Did you change the date on your computer?

**Comment by stumpgamer** [comment]
> Did you change the date on your computer?
time ago yes

**Comment by Booplicate** [comment]
She tells you not to, since it may break the game. You'll have to wait until the date you time travelled to be able to gift again.

**Comment by stumpgamer** [comment]
> She tells you not to, since it may break the game. You'll have to wait until the date you time travelled to be able to gift again.

oh well ok thank you

**Comment by Asw123dxd** [comment]
I felt like a fool , I'm so sorry that I wasted your time

**Comment by stumpgamer** [comment]
> I felt like a fool , I'm so sorry that I wasted your time

nono forgive me for have stole your time! you Just tried to help me and i appreciate!

**Comment by Asw123dxd** [comment]
and Booblicate , give me a faster gift
thanks for providing. I can give a gift really quickly, thank you very much!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
