### ISSUE TITLE
[Suggestion] - Cheek Kiss

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7170]
While a general kiss (that is, on the lips) is considered a trademark sign of affection, a kiss on the cheek is a lighter way of letting someone know you care for them. I figured it'd make for a nice little option to be able to give Monika one once in a while just as a little reminder that you care about her. Who knows? Maybe she could give you one, too...?

**Comment by fromulus** [comment]
Problem is that kisses in MAS are very abstract, and that we acknowledge the fact that there isn't any actual kissing going on, but that you and Monika are simply silently agreeing to pretend the two of you are kissing.

Going from there, I feel like there really isn't much (if anything at all) we could do to differentiate the two kinds of kisses, nor is there really any point to it;
Since you're already meant to pretend you're kissing her, there's nothing stopping you from pretending you are giving her (or that she is giving you) a kiss on the cheek instead.

There isn't anything in the kissing animation or dialogue that suggests that it _has_ to be a mouth to mouth kiss, either.

**Comment by Retrolovania** [comment]
That's a good point, actually....
Ah, well. It is what it is.
