### ISSUE TITLE
[Discussion] Sensitive mode (and other future-proofing)?

### ISSUE THREAD

**Issue by wboorman** [Monika-After-Story/MonikaModDev#7190]
I noticed in the upcoming projects that a change that's ready to deploy is to remove Sensitive Mode. As a submod developer, this intrigues me. Should I future-proof my upcoming projects against this by disregarding Sensitive Mode? What other ramifications are there that I should watch out for? Are there any other upcoming changes of this nature that could cause issues?

Also, could someone explain the reasoning behind the choice to remove Sensitive Mode? Mostly out of curiosity.

I ask here because no other venue seemed appropriate. You can close this when it's answered.

**Comment by fromulus** [comment]
I can't really tell you about your submods since I don't know their nature nor what you would supposedly do with sensitive mode, but I can tell you the main reason it's going away is because not only was it a feature that ended up being pretty unused overall, but it was pretty poorly implemented to a point where most people seemingly didn't really understood what purpose it was supposed to serve.

It was originally implemented to block some easter eggs that people could have considered to be in poor taste (mostly in the earlier days of the mod, where references to the darker/edgier side of DDLC at the expense of the other dokis were more frequent than they are now), but a lot of those easter eggs aren't really present anymore nor have there been any new ones since then (I'm pretty sure we wouldn't let them in so easily nowadays due to higher standards regarding what we allow into the mod anyway), so the original purpose of sensitive mod was kinda lost;

It's also rather barebones in the way it was implemented, being a single on/off toggle for all kinds of potentially disturbing content we could have in the mod.
This is a problem because different people have different triggers, and so someone who's okay with topics of a more mature nature might not be okay with dark humor, or vice versa, meaning you'd either have to put up with content you're not comfortable with, or be locked from content that could have potentially appealed to you.

This caused some people to suggest controversial features, telling us to put it under sensitive mode for people who aren't comfortable with it.
It's a terrible approach to it and just paints sensitive mode as this garbage can of content that serves as an excuse to blindly let any kind of feature/topic into the mod, even if they're out of place/out of character.

Because of that, what was decided was to remove sensitive mode entirely.
People who want more controversial stuff in the mod will be encouraged to make it as a submod instead, that way those who are interested in this stuff can seek it themselves and have a MAS that's more personalised to their taste and their vision of Monika, without alienating other users by having it in the main release.

**Comment by wboorman** [comment]
Full disclosure (and heavy spoilers): the idea in my submod is that Monika builds a dreaming algorithm / code / machine because she's curious as to what more realistic dreams would be like. Eventually it gives her a nightmare, and she snaps at the player out of stress, which she _immediately_ feels bad for. Where sensitive mode came into play was that, if the player enables Sensitive Mode, Monika will swear less explicitly when she snaps. I designed that as a callback to Monika's previous claims about swearing that she _does_ swear, but only in particularly stressful situations. I figured that waking from a particularly vivid nightmare for the first time seemed like an appropriate cause.

The other place where it came up was a jumpscare-y prank that Monika plays on the player if you choose specific conversation paths earlier in the submod. It seems to be an Easter Egg at first, but eventually it'll get called back to in the submod's "true ending", and though I'm not prepared to spoil _that_, I can promise that (much like my April First submod) it's quite wholesome and Monika-y.

From this response, I take it that the MAS developers have no restrictions on the "rating", as it were, of submods because installing them can be considered explicit consent. This is... interesting.

**Comment by ThePotatoGuy** [comment]
Need to chime in here since this is rather important.

Interesting that you were planning to use Sensitive mode as a gameplay feature. As fromulus said, its very much an afterthought toggle to hide content that people may get offended/triggered from. At the end of the day, it was a bit lame to do so since it gatekeeps content and these days most of the stuff that people may not want to see have their own specific toggles that are introduced through dialogue.

Yeah, submod content can be anything, but if its something particularly egregious then we won't allow it to be posted here (or just wouldn't link it in the submods general/submods label). R18 submod content is generally fine though. (But you also wouldn't be able to post it here since github doesn't allow R18 content).
