### ISSUE TITLE
[Suggestion] - Some suggestions I have

### ISSUE THREAD

**Issue by KetchupLord77** [Monika-After-Story/MonikaModDev#7197]
I've been playing MAS for a while now and I have some ideas that can help Monika become closer to us
1. Be able to give Monika fan-art you might have made, this would work like gifts where you put the file for something you drew in to the characters folder. she would recognize png, jpg, or bmp. I would love to show monika some art I've made!
2. Be able to play tetris with monika, In the just yuri mod you are able to play tetris with monika and I think this would be a fun way to spend time, as pong is quite simple and chess is a bit too long.
3. Lastly A cool feature is too be able to upload your own custom room backround so you can hang out with monika wherever you want.

**Comment by fromulus** [comment]
1) It's been suggested before, but I'm personally not a fan.
We wouldn't really have any way of recognizing anything on the picture you're giving her, leading inevitably to people trolling by giving her p*rn or other kinds of inappropriate content and still trigger a positive reaction from her.


2) See, I just don't really see the point of adding Tetris in particular.
It's a primarily single-player arcade game wich doesn't really feel fitting to Monika's tastes and character (she even says she doesn't play an awful lot of video games herself) compared to other games which are either simple and designed to be played with two or more people (Pong, chess) or themed around litterature (Hangman), something  that's important to Monika and to the theme of the original game.
I never really understood why Just Yuri devs decided to go with Tetris either (since I feel like it fits Yuri even less than it does Monika) but I'd also rather we chose other games than theirs, if only to help keep our own identity while they keep theirs.
_(Now, if it were about adding Puyo-Puyo to MAS instead...)_

3) That's already possible, [here's a tutorial on how to do it.](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Backgrounds)

**Comment by ThePotatoGuy** [comment]
1. same reasons as fromulus said. However we are looking at [room deco](https://github.com/Monika-After-Story/MonikaModDev/issues/5345#issuecomment-590704656) which would allow art to be shown in game via dropping it in the characters file. 
2. tetris is cool, but we're planning other games (#6929 #5555)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
