### ISSUE TITLE
 I deleted Monika file and she is not in game and I delete game and then I redownload but she still not there. What to do? 

### ISSUE THREAD

**Issue by fixmeppl** [Monika-After-Story/MonikaModDev#7204]
I deleted Monika file and she is not in game and I delete game and then I redownload but she still not there. What to do?

**Comment by H2-san** [comment]
You're going to have to restore an earlier persistent.

1. Go to where your `AppData` folder is located. (If you have the persistent saved locally, ignore this step and go to those persistent files.)
2. You'll see files like the following: 
`persistent` - that is your main persistent data file. Delete it.
`persistent##.bak` - the higher the number, the more recent that persistent is.* (If you can't see the .bak extension, click 'View' > 'Options' > 'View' tab in the dialog box, and then uncheck "Hide extensions for known file types.")
3. Rename the most recent `persistent##.bak` to `persistent`, then say yes to the warning pop up, and boom.

*NOTE: If there is a `persistent99.bak`, check for `persistent00.bak`. If `persistent00.bak` does not exist, then you're all clear to use `persistent99.bak` - otherwise, if `persistent00.bak` is present, see if `persistent01.bak` exists and so on, using the most recent `persistent##.bak`.

Congrats, persistent restored. You will lose some progress, though, so be sure to make up for it. :)

**Comment by fixmeppl** [comment]
I'm confused. I went to the AppsData folder and all I se is Local LocalLow and Roaming. I went into those folder and found no persistent.

**Comment by zwartkop2** [comment]
Under Roaming there should be a folder labeled RenPy. Look there

**Comment by fixmeppl** [comment]
Thanks it worked!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
