### ISSUE TITLE
New Reaction: Discord

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#7206]
I think this could be quite entertaining and intuitive. Since a large sum of people use Discord to communicate with their friends and because its so accessible, I think it could be quite the addition to the "Windows Reacts". I would imagine she would say something like "Hey <player>, mind if you could say hi for me?" or perhaps "Wow <player>, I didn't you talked to this many people!". She seems like the type of person to be really excited to meet the player's friends. I do certainly hope you are interested in my idea.

**Comment by Booplicate** [comment]
Discord doesn't provide enough information with its window handle, you only get channel names.

**Comment by fromulus** [comment]
> 
> 
> Discord doesn't provide enough information with its window handle, you only get channel names.

That would be true for the browser version of Discord, however the desktop app does have "Discord" in the window handle.

![Screenshot_1](https://user-images.githubusercontent.com/45933038/118233698-8dabbf00-b492-11eb-8a2e-15279ad8f115.png)

Not sure if we can check for windows aside from internet browser ones since we don't have any at the moment, but I'd assume it should work the same.

**Comment by Booplicate** [comment]
Yes, you can detect that it's probably Discord, but you don't know whether you're on a server or in DMs. You only get channel names.

**Comment by fromulus** [comment]
Does it really matter, though ?
I'm guessing a general Discord reaction would do the job just fine, pretty much like what we have for Twitter.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
