### ISSUE TITLE
[Suggestion] - Mac react

### ISSUE THREAD

**Issue by JacksonFillmore-dev** [Monika-After-Story/MonikaModDev#7209]
We have gotten a windows react where Monika can what your doing on the web on Windows. But how about Mac reacts? I'm on a mac so it would be cool if Monika could see what your doing on Safari or Microsoft Edge while your on a mac computer.

**Comment by fromulus** [comment]
So one of the actual devs would answer this better than I can, but the big issue with Macs is that the operating system just keeps changing important stuff, meaning developping one feature for Mac is kind of pointless in the long run, since you'd have to basically rework the entire thing almost every time Apple updates the OS.

This makes developping and maintaining anything that goes beyond the actual MAS app like system notifications a nightmare, and it's not helped by the fact that you can't really test anything without actually owning the hardware, which as of right now, no one among the dev team and the contributors do.

So to be completely honest, while I don't mean to tell you this isn't ever going to happen, I really wouldn't hold my breath for it.

**Comment by ThePotatoGuy** [comment]
The APIs/tools that use to find the currently open window only work on Windows and Linux. We don't have any active mac devs who can look into how to do the same on Mac.

[closing as rejected]
