### ISSUE TITLE
[Suggestion] allow to play pong with the arrow key

### ISSUE THREAD

**Issue by antoineok** [Monika-After-Story/MonikaModDev#7211]
the title say everything, i think this should be a great idea, being able to play the pong minigame with the keyboard

**Comment by lunulae** [comment]
It might be possible, but there is one very tricky question. How fast should the cursor move when you hit the arrow key? It needs to be fast enough to work at higher, super-fast levels of gameplay, but not so fast that the player has no control.
The one advantage I don't think we'll be able to perfectly convert from mouse is that balance of control.

**Comment by fromulus** [comment]
Being able to move the paddle by scrolling with the middle button might be an interesting middle ground though, and it would theorethically give a similar feel than of the original Magnavox Odyssey controller.

**Comment by antoineok** [comment]
i asked that because my mouse don't work correctly, so i asked that to finally beat her in the pong minigame

**Comment by ThePotatoGuy** [comment]
For best results, there would have to be an acceleration based on how long the key was held down, otherwise the bar would move too slow for a lot of cases. Anyone with physics experience is welcome to make a pr, but for now we're not going to prioritize this as the mouse is a more flexible and accurate tool for bar control.
