### ISSUE TITLE
MAS notifications arent working properly. it only shows this icon(bottom right) and doesnt pop up on my screen. 

### ISSUE THREAD

**Issue by AkoSiAdam** [Monika-After-Story/MonikaModDev#7289]
![w1zyrkzkw0371](https://user-images.githubusercontent.com/85292510/120642584-aadb1880-c4a7-11eb-95be-09fc90f87695.png)

**Comment by Wingdinggaster656** [comment]
This is... A hard one to solve.
The reasons are really various, so I can't really help you... But I'd like to try at least.

First of all, this problem doesn't come up 100%, right?
If not, the reason is usually this: when the game starts and loads the icon, you don't have enough video memory, and even if your video memory is fine later on, it won't try to reload. Therefore, a solution that is not 100% effective is to keep the computer as idle as possible when starting the game.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
