### ISSUE TITLE
What does Monika think about children?

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#7293]
I don't remember if there is such a topic. If not, it was interesting to know what she thought about it.

**Comment by Wingdinggaster656** [comment]
See #3390
Let me paste the final decision of the devs here:


_So we've decided that this topic is too controversial to really put into MAS, and really, if we were going to do this, it'd take a lot of discussion on how to approach it, given the complex nature of this question in itself, and that responses could potentially change as time goes on._

_There is also the fact that Monika should be one to lean one way or another in the question and not just go "whatever is fine for you." Because that doesn't make sense at all. While one may want to be the perfect girlfriend, children is a different topic entirely and has drastic effects on the body and etc. plus hormones._

_But, with that in mind, it creates controversy because of those who'd want her response to be the other way. Therefore, we can't really let this happen._

**Comment by kirillPro2020** [comment]
At least you can say that she will think about it when she moves into "our reality".

**Comment by Wingdinggaster656** [comment]
> At least you can say that she will think about it when she moves into "our reality". I think this option will help to avoid unnecessary disputes. We will come to neutrality. This is better than avoiding such topics altogether.

I agree your view. But it's not what the devs think.
In my view, we should mention this topic, but only limited as mention. There won't be a chance to talk about this deeply, but we should at least mention it, just like what you said, "She will think about it", we can not avoid.

**Comment by fromulus** [comment]
Quite the contrary, having Monika go the "we'll think about this later" option feels very similar to her taking a neutral stance on it, and this is one of those major subjects we just can't really go neutral on.
We want Monika to feel like the deep character she is, and that involves needing her to take sides on some things.
While we can try to have her be open-minded andready to make compromises over most things, this topic isn't really one where we can afford it.
Real life couples get to talk those things out seriously and extensively, but we sadly can't really have something this fleshed out with the limitations of a VN's dialogue system.
It's the same reason we aren't really able to implement the possibility of having proper fights with her (even though it'd be one of the most important things we lack in the way of immersion).

Because of that, it's already been decided that if we ever were to make a topic on the matter, we'd need to have her have a defined opinion on it, and that's where we have a problem since, as said earlier, we're going to face controversy no matter which side she picks.
Therefore, the devs have decided to put it on the list of subjects to avoid (alongside diving any deeper than we already did on the themes of player death and mental health), as even mentioning it would likely cause more harm than good.

**Comment by kirillPro2020** [comment]
I think that ignoring these topics by avoiding them is not right.

**Comment by kirillPro2020** [comment]
The only thing that can be done is to remain neutral. At least in this topic. And about psychological health, I did not understand what the difficulties are?

**Comment by MrVavlo** [comment]
Honestly, this would be the last thing I would discuss with my long-distance relationship partner. 
Unless I'd already have adopted or from previous relationships' children...

**Comment by Retrolovania** [comment]
It's important to recall that Monika is technically an 18-year-old girl by default. Asking her what she would think about having children (which is a far more complex responsibility that it sounds), it'd likely prove to be a difficult thing for her to think about. Most people usually wait until their 20s or 30s before thinking about kids, so, I think having her be neutral would be the most natural stance in this regard.

**Comment by kkrosie123** [comment]
This idea has been rejected time and time again. We are not having a topic about children. Thank you for your suggestion.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
