### ISSUE TITLE
Monika won't talk to me, she only sings.

### ISSUE THREAD

**Issue by AhOkayIGuess** [Monika-After-Story/MonikaModDev#7306]
Monika doesn't say anything about any topics anymore, whenever I say goodbye and leave her for a little she only sings me a song and goes back to silence, what does this mean? and what is the problem here? is she out of dialogue to say? I'm thinking this is a bug.

**Comment by lunulae** [comment]
This is likely because you're out of dialogue. If you've had random chatter set to a relatively high frequency like Normal and you don't have repeat topics on, you will probably run out after a few days of playing. We try to add new topics with decent frequency but unfortunately they can't be infinite.
There may still be content left for you to unlock like games, and some dialogue does unlock at higher affection levels, so look out for some of those. ❤️

**Comment by AhOkayIGuess** [comment]
> This is likely because you're out of dialogue. If you've had random chatter set to a relatively high frequency like Normal and you don't have repeat topics on, you will probably run out after a few days of playing. We try to add new topics with decent frequency but unfortunately they can't be infinite.
> There may still be content left for you to unlock like games, and some dialogue does unlock at higher affection levels, so look out for some of those. ❤️

Thank you for the reply, that makes sense, and i'm glad I know the problem now!
