### ISSUE TITLE
(sugestion) Kinnies

### ISSUE THREAD

**Issue by LalahY** [Monika-After-Story/MonikaModDev#7349]
Monika could ask us if we kin anyone from DDLC, she first would explain what's a kinnie is, and then it would appear options on who we kin, Monika herself, Natsuki, Yuri, Sayori or No One, it would be cool

**Comment by satoshi-kun** [comment]
And what is a "kinnie"?

**Comment by LalahY** [comment]
> And what is a "kinnie"?

Kinnie is when you relate to this character, for example: It could be your personality or the character just likes the same thing as you... 

Monika, for example, she likes poems, reading, she's vegetarian, if you have some things in common with her you could say that you KIN her, yet, I think kin is a strong word, kin its when you really see yourself in that character

**Comment by lunulae** [comment]
Since we have quite a few fandom topics I could see this fitting nicely. I see kinnie/kin used a lot in roleplay circles, so I'm thinking it might be good to use in conjunction with a larger roleplay topic.

It's a (sort of) new term so I'll have to do a bit of extra research to make sure I'm using it right, but I have a few potential ideas.

**Comment by ThePotatoGuy** [comment]
>used a lot in roleplay circles

Yeah, this is a no from me, chief. If the term is really obscure then the only reasons Monika would know the term is if she's part of the community it comes from. Currently we don't have any established lore that Monika would be deep into roleplay circles.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
