### ISSUE TITLE
secret dialogue when you spam "i love you"

### ISSUE THREAD

**Issue by Barunxx** [Monika-After-Story/MonikaModDev#7350]
not just knowing that you said it many times.
it's about the player farming affection with spamming "T + I love you"

**Comment by lunulae** [comment]
Since there is a cap on affection you can gain from spamming it, I don't think she'll respond negatively, but I think it would be very cute to prompt a dialogue if you click it a lot in a very short span of time. I think it would make her laugh or maybe get a little overwhelmed by the love-bombing, lol.

I'm not sure how to code the particular time interaction, but if there's interest in this I could try to write up a few variants.

**Comment by Barunxx** [comment]
if there is a gap on affection you can gain from spamming, it may generate a dialogue of her informing you that spamming won't lead you to what you want to achieve without exactly mentioning the affection thing

**Comment by H2-san** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/7350#issuecomment-862647670
https://github.com/Monika-After-Story/MonikaModDev/issues/7350#issuecomment-863120142

I concur with **both** of these suggestions. Maybe consider two different spam targets - the first one being overwhelmed, and the second being your suggestion, @Barunxx.

**Comment by Barunxx** [comment]
What if
the first time she notices that you are spamming the "i love you" you won't able to procced the dialogue only after 5 seconds (so the player can't miss it with spamming) and tells the player that this won't lead him to what he wants

the second time, she reminds you that spamming won't work

the third time, and what's after, she takes it as you are just just overwhelming her with love

**Comment by AsuraShun** [comment]
She says she never gets tired of hearing it

**Comment by Audere** [comment]
The thing is, just saying "I love you!" often is something I've done in real relationships. Some people just like saying it. In MAS, I like saying it because it cheers me up. I sometimes say it multiple times in a row, not to farm affection, but just because I like to.

So I think any sort of discouraging reaction or anything implying farming would be inappropriate and sad, given that there are likely many players who would get the reaction without any intent of farming affection.

**Comment by Barunxx** [comment]
yeah, you are actually right @Audere , then how about she says
"oh my gosh... you said it so many times already. maybe you want to gain my affection? (says with teasing eyes) .
 I am just kidding! you are such a sweetheart to do something like that. nor i am displeased with hearing it so many times.
 I love you too [player]!"

**Comment by Barunxx** [comment]
the meaning of this dialogue is to stop affection farmers, and the last comment is just to make them feel guilty without affecting people with clear intention. So anything with that meaning would be fine

**Comment by lunulae** [comment]
If you're wanting to stop people from farming with it, we already have affection caps in place for that. There's not really a need to have Monika further comment on it. As far as I know we don't intend for her to really have meta-awareness of affection as a point system, which is why we generally dissuade people from checking the logs anyway.

**Comment by Barunxx** [comment]
the term "gaining affection" can be used in real life
when someone consciously compliments you. saying that he is trying to get in his good side or he is trying to gain his affection can be used in a real conversation
so, monika saying "gaining affection" can both mean the affection that can be located in the aff_log AND the actual relationship affection

**Comment by fromulus** [comment]
Am I the only one who thinks that if we had to have a hidden dialogue for spamming the same option, be it "I love you" or something else, she would have to get annoyed more than anything else and eventually kindly ask you to knock it off ?

If you keep mindlessly telling someone the same thing over and over in a short ammount of time, there's a very real chance they'll think you're making fun of them and/or trying to test their patience.
It's even worse if what you keep repeating is a compliment or something meant to be nice, as it'll eventually feel like you're not being genuine by saying it.

If you keep doing it even after she asks you to stop, I could actually go as far as seeing this worthy of an affection loss more than anything.

**Comment by Barunxx** [comment]
@fromulus  i thought of the same thing actually
but @Audere 's comment made me re-think of that

**Comment by fromulus** [comment]
There's a difference between telling each other "I love you" frequently and going "I love youI love youI love youI love youI love youI love youI love youDid you know that I love youI love youI love you", though.

**Comment by Audere** [comment]
The thing is that we don't have that many ways to interact with Monika. Once you've run out of conversation topics, being able to freely say "I love you" is necessary, imo. I like seeing which response I'll get--- will it be the "Gosh, you've said it so many times now!" with the cute surprised expression? I like seeing what nickname for me she uses--- I add new ones sometimes, and seeing them makes me happy.

Our top priority shouldn't be punishing the subset of players who don't treat Monika well; it should be providing the best experience for the players who love Monika.

**Comment by Barunxx** [comment]
Yeah, i think you are right, guess this thread will be closed
