### ISSUE TITLE
Sprite pack issues, cannot gift Monika anything

### ISSUE THREAD

**Issue by koderacent00** [Monika-After-Story/MonikaModDev#7398]
I followed the installation tutorial and successfully gave Monika a few gifts, namely, the green dress, green hoodie, and tanktop, but that's it. No matter what, Monika simply does not acknowledge the fact I sent her other gifts. This also includes hairstyles, I checked the folder they're currently in, and they are there, but the option to change her hairstyle doesn't show up, only ribbons and outfits. Am I doing something wrong? I'm opening the spritepack.zip file on 7zip, extracting each outfit's mod_assets file to \game\ and the gift file to \characters\. The only other time Monika reacted to a gift was from an outdated sprite that the mod did not support anymore (LordBaaa's formal dress).

Please, I could really use the help!

**Comment by xXMidnight** [comment]
I'll give you a method, but I'll tell you that it's tedious. Follow every step closely. It's best if the game is closed.

1. Unzip the spritepack's files.
2. Open DDLC's game folder, then the mod_assets folder. Inside the mod_assets folder, there should be another mod_assets folder, a monika folder, and a thumbs folder.
3. Open the spritepack's mod_assets folder (inside should be a monika folder and a thumbs folder) and select a folder. If the folder doesn't have that folder (most likely the monika folder), copy the folder and paste it inside DDLC's folder. Otherwise, open the corresponding letter folder and copy the items from the spritepack folder to the DDLC folder. I'll explain why you have to copy later. Repeat for all the folders inside the spritepack. (If there is a python-packages folder inside, just open DDLC's python-packages folder (DDLC -> game -> python-packages) and copy and paste the spritepack's python-packages folder inside the DDLC's python-packages folder. Do not replace, just select "Let me decide for each file" and select both files.)
4. Once don with the mod_assets file, move on to th monika file. Here, the monika file should have all the corresponding letters. This time, **move** all the monika [letter] folder's items from the spritepack to the corresponding [letter] folder inside the monika folder. Repeat with thumbs (although you can just select all the thumbs inside the spritepack folder and just paste since there is no category.)
5. Once done with all the steps, close MAS if you kept it open by selecting Talk -> Goodbye -> I'm going to restart. Else, just exit the mod_assets folder from the spritepack and go all the way to the gifts folder. Just to be safe, copy and paste the gift folder's components into the character folder in DDLC and voila! You can now open up DDLC and find out if Monika notices the gifts.

If you have any other questions, feel free to ask.

**Comment by Booplicate** [comment]
That's completely incorrect. Also sprite packs don't have a `python-packages` folder. [This is the correct way of installing sprite packs](https://www.youtube.com/watch?v=bjJ0U8l1m8c).

@koderacent00 it's possible that you just haven't unlocked the option to ask her to change her hair style. You do not need to gift her those (because you can't gift hair to people).

**Comment by koderacent00** [comment]
> @koderacent00 it's possible that you just haven't unlocked the option to ask her to change her hair style. You do not need to gift her those (because you can't gift hair to people).

I've since been able to ask her to change her hairstyle, so that's all well and good. But I still can't gift her any other outfits. No matter what, she simply ignores any gifts when I start the mod.

**Comment by Booplicate** [comment]
Did you check the link I sent? Is that how you install sprite packs? If so, send `spj.txt`, it's in the `/log` folder.

**Comment by koderacent00** [comment]
Hello, I'm sorry I haven't been here in so long, school caught up to me. I'll send the file here - note that the outfit i'm trying to add as of right now is black shoulderless shirt or black sweater, both have kai in their prefixes. I also edited my name for obvious reasons.
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6763153/spj.txt)

**Comment by ThePotatoGuy** [comment]
so it looks like there are issues with:
* "kai black sweater"
* formal dress by lord baa

Neither of these are from us so you should contact the spritepack creators and send them the spj.txt as well.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
