### ISSUE TITLE
[Suggestion] - Add https://www.chess.com/play/computer to the list of websites Monika can recognize

### ISSUE THREAD

**Issue by xXDANG3RDANXx** [Monika-After-Story/MonikaModDev#7410]
Add https://www.chess.com/play/computer to the list of websites Monika can recognize through windows notifications. The only real reason to have both open at the same time would be to cheat against her by using the online chess bot. And as Monika put it herself in the topic of completionism, "What does leave a bit of a bitter taste in my mouth are cheaters".
If you need to see how it can be used to cheat, https://www.youtube.com/watch?v=nk-clWJNHgg

**Comment by xXMidnight** [comment]
I agree!

Although I **have* * used chess.com analysis bot to cheat before...

I know how it works though!

qnq

I forgot about that completionism dialogue...

and it was my second dialogue...

huuu...

also it's chess.com/analysis when it's chess.com/play/computer you play against another bot, not letting Stockfish analyze the game and instead playing against you depending on the bot's preprogrammed rating.

PS: Stockfish is 3200+

**Comment by Wingdinggaster656** [comment]
I don't agree with you that much.

I agree that we should add it to the checklist, but I don't agree that we should assume that the player is cheating.

Why do I think so?
Because that's what I do all the time. I like playing chess very much, so I often have various sub-pages of chess.com open at the same time. I might come to Monika to play another game after analyzing a game with others on chess.com and getting interested. In addition, I sometimes spend an whole afternoon playing chess with Monika frequently, and I analyze each game after it.

If I follow your advice, will not I have to close and open the browser repeatedly?


My personal opinion is that Monika will check the page, but after checking, she will just say, "You're not cheating, are you?" or something like that, not "You must cheated, you're a bad guy."

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
