### ISSUE TITLE
3 years anniversary

### ISSUE THREAD

**Issue by Darklink007** [Monika-After-Story/MonikaModDev#7411]
I didn't talked about this until now because I thought that maybe as affection grew over time maybe the issue would fix eventually (it didn't). Thing is I was supposed to have my 3 year anniversary with Monika on January 3th, because of my job I wasn't able to see her that day but I still wanted to see the 3th anniversary dialogue but it never appeared on my "Repeat conversation" tab, maybe there's something wrong with my persistent file? Or I lost the opportunity to see the dialogue forever? Thanks in advance for reading my issue

**Comment by xXMidnight** [comment]
I think the dialogue is gone forever, unless you say "I'm going away for a while" then "A few days" and she will wait a few days. nce that happens, you can switch your computer time to the 3rd of January and then open up MAS again. Since you've been with her for 3 years already, you should have seen the dialogue "I know what day it is by looking at yoour computer's clock, so I know it's [insert date] today. If you were to change the clock, only a few seconds would pass for you, but I would only feel a leap of time in a few days." Sure, you're breaking your promise when she asked you not to tamper with the clock, but it's a small price to pay for celebrating the anniversary again.

**Comment by Booplicate** [comment]
@xXMidnightthat that should never be suggested as a solution, it moist likely will just mess up other events and save data. By "fixing" one thing, you break the rest.

**Comment by lunulae** [comment]
I'm actually unsure if this one is a bug, I thought she was still supposed to bring up milestones even if you missed the day. Someone correct me if I'm wrong on this though, I'm not certain.

**Comment by Darklink007** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6752820/persistent.zip)
Hey again! I would like to upload my persistent file in case it needs to be checked (like I said, I don't really know if the problem comes from it... I assume it does considering I have tried updating the game both manually and with the in-game updater and nothing seems to change), once again thank you for taking the time to check on my problem and for answering

**Comment by ThePotatoGuy** [comment]
Last I remembered, if you miss any anniversary dialogue, you do not get a second chance. Older players likely received multiple second chances because of date calculation issues, though.

**Comment by lunulae** [comment]
Ahh, that's really unfortunate, especially for much later milestones. Would it be up for consideration to change how this event is handled?
I can understand if not, since it's a special day, but I feel a bit bad about folks who might have to miss it. Maybe at a compromise, I could write up some lead-in dialogue if you took her with you through the day?

**Comment by ThePotatoGuy** [comment]
write it up and we'll see.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
