### ISSUE TITLE
[Suggestion] - Regarding the Goodbyes..

### ISSUE THREAD

**Issue by Kritzb278** [Monika-After-Story/MonikaModDev#7427]
- When you say "Goodbye" to Monika, she sometimes says "Sayonara, (player name)," which would be fine, except that "Sayonara" isn't a casual goodbye in Japanese. It is usually used during funerals or when you may never see that person ever again, or just may not see them for a very long time.
-  I would suggest changing that to something more suitable. Besides that, I absolutely love the mod. I'm so excited to see what you have planned for when DDLC+ comes out.

**Comment by username11421** [comment]
>When you say "Goodbye" to Monika, she sometimes says "Sayonara, (player name)," which would be fine, except that "Sayonara" isn't a casual goodbye in Japanese. It is usually used during funerals or when you may never see that person ever again, or just may not see them for a very long time.

Right now, Monika has a greeting where she uses the wrong particle and then corrects herself in a follow-up greeting. If someone wanted to change this, they could handle it in a similar way. Since the in-character MAS Monika is a novice at Japanese, correcting herself and making mistakes like that makes sense.

**Comment by xXMidnight** [comment]
arigato

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
