### ISSUE TITLE
How can I safely move my Monika memories to another drive?

### ISSUE THREAD

**Issue by Danielshmaniel** [Monika-After-Story/MonikaModDev#7436]
I once lost my Monika memory files when I formatted my C drive and forgot to back up the App data stuff (where I have the RenPy folder).

So, I'd like to know if there is a safe way to move the "persistent" to my disposable drive (that I don't format).

Disclaimer: I am still new to MAS files, so please pardon me if I don't know which do what. I was told that the "persistent" file was the most important file to back up.
Regarding the rest of the RenPy folder, I don't know if I should just move the RenPy folder OR the "persistent" alone in the DDLC directory.

**Comment by username11421** [comment]
All you need to do is copy the persistent onto your disposable drive as per [the wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). It's also worth having a backup on the cloud somewhere (e.g. your Google drive or Dropbox) so that you can access it regardless of the hardware you're using.

**Comment by Danielshmaniel** [comment]
@username11421 Thank you for your reply. Backing up is indeed important, but since I don't want to back up my disposable drive since I never format it, I'm asking you if MAS would still work if I was to move the entire RenPy folder from C:\Users\myuser\Appdata to D:\Software\DDLC . I said in the disclaimer that I am new to MAS files, so I want to know if moving RenPy wouldn't affect anything.

**Comment by username11421** [comment]
I see. If you edit the top level file "DDLC.py", there's these lines:
```
    if save_directory is None:
       save_directory = renpy.config.save_directory
       save_directory = renpy.exports.fsencode(save_directory)
```

Normally, these lines help it find your %appdata% RenPy folder. If you wanted the saves to all become local, within the MAS files, you'd change this to:
```
    if save_directory is None:
        return gamedir + "/saves"
```

If you do this, you should be able to run the entire MAS from the disposable drive and it would also contain your saves right there in the MAS/saves folder, and it wouldn't even matter where your RenPy folder was. But if you don't change these lines, I _think_ it would still look for your appdata on your default (C:) drive and you'd be missing the persistent.

Rather than changing the lines to return the `gamedir + "/saves"`, in order to do **exactly** what you've laid out, you'll have to have that line of code return the actual new path where you'll put the RenPy folder. I'm not 100% sure if just replacing `gamedir + "/saves"` with the absolute path would work, though. You have to be careful when doing this since Monika's memories are being retrieved from wherever this location points to.

**Comment by xXMidnight** [comment]
oh.
no...
poor guy.
idk how to help.

**Comment by Danielshmaniel** [comment]
@username11421 thank you for helping out with the technical bits. Though I'm too scared to mess with technical stuff since it sounds confusing and might even be dangerous, I'd really appreciate if someone could test this out before I try. No offence

**Comment by ThePotatoGuy** [comment]
You could just copy them out like a backup, then put them back in later.

**Comment by Danielshmaniel** [comment]
> 
> 
> You could just copy them out like a backup, then put them back in later.

I will, thanks!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Danielshmaniel** [comment]
> 
> 
> [closing as resolved]

I'm still a bit doubtful if it will work (I haven't moved it yet)
