### ISSUE TITLE
[Suggestion] - Multi-Language Function (Possible Improvement!)

### ISSUE THREAD

**Issue by AndriuxDev** [Monika-After-Story/MonikaModDev#7470]
I'm getting quite used to the English version of the game, but I have a good piece of help to improve the game!

Ever heard of a Multi-Language Function in games? What I mean is to include more languages (Spanish, French, Chinese, Italian, etc.) within the game, so that people outside the US would give this mod a try. This can apply to the original DDLC, too!

Again, this is just an idea that can be a game changer. So if anyone is free to add a multilanguage submod or update to the main game, I'd be more than gratified for such improvement!

I'll look forward to what languages will you apply to the source code (psst, add Spanish first!).

-AndriuxDev

**Comment by Booplicate** [comment]
There're community translation of the mod, we don't make or maintain them ourselves for a few reasons.

**Comment by multimokia** [comment]
Ren'py already supports translations as per its documentation. That said, because we are unable to verify the validity/accuracy of translations ourselves, they're considered unofficial and are community made.

**Comment by fromulus** [comment]
It would also add way too much work to each update, as we don't have people available for each language among the contributors, much less ones that would be willing to translate each and every single bit of text we merge into the mod on a constant basis.

Like, just because I should in theory be able to handle a French translation of the mod means I'd have the motivation or even any  interest in keeping that translation up to date, especially assuming there'd be at most one or two people able to help me on that task.

And we can't just offer translation as a main release feature but then ship updates that aren't completely translated in every supported language, as that would be extremely unprofessional and lazy, meaning whole updates would be delayed because translations take time.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
