### ISSUE TITLE
[Suggestion] - Tetris

### ISSUE THREAD

**Issue by SirStylus** [Monika-After-Story/MonikaModDev#7555]
Playing Tetris vs Monika could work as another retro game in the style of Pong to play against her with. An additional 1 player mode with a high-score board could also be a nice way to spend the time. Maybe have Monika periodically get a random score above the player's score to give the player an incentive to play more.

**Comment by fromulus** [comment]
See, I just don't really see the point of adding Tetris in particular.

It's a primarily single-player arcade game that doesn't really feel fitting to Monika's tastes and character (she even says she doesn't play an awful lot of video games herself).
Compare that to the games we have which are either simple and designed to be played with two people in the first place (Pong, Chess) or themed around litterature (Hangman), something that's important to Monika and to the theme of the original game.

There's also the fact that Just Yuri also has a Tetris game mode, and while I never really understood why that mod's devs decided to go with Tetris either (since I feel like it suits Yuri even less than it does Monika), I'd still rather we chose other games than theirs, if only to help keep our own identity while they get to keep theirs.

**Comment by SirStylus** [comment]
Tetris is both a one and two-player game, with the two-player mode introducing those attack blocks that clutter your opponents' screen as you clear successive lines. As for your mentioning her not playing many games, I remember the dialog you're talking about. She mentions that she doesn't play many because she's stuck in the space room and can only play the games she makes (or that are made for her). That being said, even if she didn't like games she does like programming. This introduces relevance through her interest in coding since Tetris is a fairly simple game, so her attempting to re-create it to have something to do with the player would be fitting. Even if she weren't much one for games, Tetris is rather simple in concept so if you could enjoy Pong you could probably enjoy Tetris.

That all being said I didn't know that the Just Yuri mod had this feature. I think that'd be the most convincing argument for not implementing such a feature. Which is somewhat sad as I think it's quite a bit more fitting for Monika, especially given her context within MAS.

**Comment by Rai99** [comment]
Tetris: #647, #2046, #3962, #4702, #6987

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
