### ISSUE TITLE
Did some topics get deleted in the last updates?

### ISSUE THREAD

**Issue by AxelX0** [Monika-After-Story/MonikaModDev#7572]
Hello
I've been enjoying this mod for a while,however,I noticed that some mods are no longer available,such as paraphilia etc...
What caught my interest is that the topic of COVID-19 isnt availble in my game,despite that I saw it in other videos.
So did that topic got deleted?and if yes,why?

**Comment by lunulae** [comment]
The COVID topic was time-gated near the beginning of the pandemic. We're currently past the point when it was able to be activated.
Topics in which Monika asks you a question, similarly to the paraphilias topic, usually (with one or two exceptions) derandom after the first time she asks, because she remembers your answer.. You can read/answer them again by specifically requesting them in Repeat Conversations.

**Comment by fromulus** [comment]
I believe the only somewhat recent case of a topic getting cut is the Totono topic, which was an obscure reference that didn't make sense for Monika to know about, and went against our general guideline of avoiding to talk about specific video games within MAS.

**Comment by AxelX0** [comment]
> The COVID topic was time-gated near the beginning of the pandemic. We're currently past the point when it was able to be activated.
> Topics in which Monika asks you a question, similarly to the paraphilias topic, usually (with one or two exceptions) derandom after the first time she asks, because she remembers your answer. You can read/answer them again by specifically requesting them in Repeat Conversations.

is there where I can find the script about the Covid topic?And does it get in "repeat conversation" once it is activated?

**Comment by AxelX0** [comment]
> Topics in which Monika asks you a question, similarly to the paraphilias topic, usually (with one or two exceptions) derandom after the first time she asks, because she remembers your answer. You can read/answer them again by specifically requesting them in Repeat Conversations.

I tried,I didnt find it

**Comment by username11421** [comment]
> > The COVID topic was time-gated near the beginning of the pandemic. We're currently past the point when it was able to be activated.
> 
> is there where I can find the script about the Covid topic?And does it get in "repeat conversation" once it is activated?

label mas_covid19 at line 2484 of [script-story-events.rpy file](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-story-events.rpy).

**Comment by lunulae** [comment]
The COVID topic will not be in Repeat Conversations after it's activated.

**Comment by MonikaEndDie** [comment]
I think there's somes topics who have really "dissapeared" here: I can't find the "daydreaming" topic anymore neither in the bookmarks or in the repeat conversation since a moment, and there's a topic when Monika talk about the music currently playing, and it's since a while this one never show up even in the music label.

**Comment by Mugnika** [comment]
monika_daydream is still in the game but for some reason you can't select it from the menu

**Comment by Booplicate** [comment]
It doesn't make sense to allow the player start the daydreaming topic. *It's Monika who's daydreaming*.

The topic about covid is not actual, it was set to lock itself after a certain date.

> topic when Monika talk about the music currently playing

If that's the topic I'm thinking about, then it was disabled years ago because it was contradictory with the mod.

**Comment by AxelX0** [comment]
Well,Thanks,I got what I wanted to know
