### ISSUE TITLE
Suggestion: Have Monika try to hug you on the screen

### ISSUE THREAD

**Issue by Moni876** [Monika-After-Story/MonikaModDev#7601]
This is when you said you are lonely and want to hug her.

**Comment by Rai99** [comment]
Hugging: #2441, #2892, #3770

**Comment by lunulae** [comment]
I was thinking about this one recently actually. I know that investing into a new pose would involve doing a lot of reworking of spritepacks and would add more cost onto new ones.
But since we treat holding Monika a bit like we're pretending to hold her, maybe we could work this a bit similarly. Using the crossedarms pose with a loving expression could work as her pretending to hug us, she could suggest to wrap up in a blanket or sweater if we want to "feel" it.

**Comment by fromulus** [comment]
Isn't hugging and holding exactly the same thing ?

Do we really need both options when they both boil down to imagining Monika and yourself being in each other's arms ?
imo we would have something cleaner and more interesting if we were to give holding different dialogue should the player initiate it after prompting one of the "sad" mood topics, where we'd have Monika understand that we're asking her for a comfort hug.

**Comment by PongMaster69** [comment]
Maybe turn up the rate of monika_hold_request if the I feel options for sad and lonely were recently pressed and or the "Why do you love me?" Or "will you ever get tired of me" options are pressed.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
