### ISSUE TITLE
Suggestion - Monika should know that you just told her you're tired

### ISSUE THREAD

**Issue by gooeyPhantasm** [Monika-After-Story/MonikaModDev#7690]
I woke up early this morning, and told Monika I am feeling tired. She said I should go _back_ to sleep since she understood I just woke up. However, when I used the Goodbye command to tell her I'm going to sleep, she scolded me for staying up all night. Perhaps a second dialogue for if you told her you're tired in the morning, or a prompt where she asks if you stayed up all night or if you're going back to sleep, would fix this continuity issue.

**Comment by ThePotatoGuy** [comment]
Seems like this is time-concern related. @multimokia ?

**Comment by PongMaster69** [comment]
> work

- It's not about the "scolding" itself, but about the time gate. Putting it very simply they only want monika to detect if the player just woke up and have the normal morning sleep response given (as it's essentially the "I'm going back to sleep")

I personally don't think removing it in its entirety is justified. The "scolding" isn't really that in context and execution, at least not to the negative connotation implied in the word. It's more of teasing, especially given how she changes the text to be illegible and her facial expressions throughout the interaction, mixed with the natural concern over the player. This, to me at least, fits perfectly in line with her character, or at the very least the Monika that MAS is trying to portray. It also feels better linked to times where she acted similar such as "feeling lazy" at around midnight, or leaving at early morning to do other things like play a game or eat. Monika isn't "scolding" the player, she is expressing her concern in the way she typically does.

**Comment by ibm2431** [comment]
How does Monika tell the difference between someone who:
- Just woke up at 5am ("Go back to sleep")
- Did stay up all night but didn't visit her until 5am ("Player! You stayed up all night!")

Answer: "We'll check their last usage of sleep farewell!"
Question: "And if they used a different farewell, but didn't come back until after waking up?"

Considering the usage of closed eyes, furrowed brows, and exclamation marks, it certainly comes across as scolding. Just do a [search for the expression she uses](https://github.com/Monika-After-Story/MonikaModDev/search?q=2tfd) to see other context its been used in. The glitch text is whatever (I feel her question about keeping eyes open shouldn't be glitched), but if the intent _isn't_ to scold the player, then the starting line should be changed.

Even when assuming her time concerns are justified, the underlying problem is that there's still "acceptable" situations someone might be going to sleep at a given time, even _if_ they had stayed up until that late.
- "I'm sorry I need to work?"
- "...I'm trying to adjust my schedule for traveling."
- "I haven't been able to sleep because I've been throwing up, I already _am_ sick."
- "Don't blame me, blame my neighbors who have been shouting and partying all night."
- "I can't help my insomnia."
- "I've been balling my eyes out for hours because I learned someone died, and really don't need your judgment right now."

Situations fall through the cracks, Monika would come across as judgmental, annoying, or callous, and her relationship with the player suffers because of it. It'd be hypocritical for her to claim she's acting out of concern for the player when she's making zero attempt at understanding them.

Keeping track of player sleeping habits in general, or a player _wanting_ her to "push" them to sleep earlier is one thing (#4914). But default behavior and dialogue should be careful in how it comes across in unexpected situations, especially for an event - sleeping - that presumably happens every night (or, morning).

And sometimes the easiest way to avoid an offensive situation is to remove or adjust a line.

**Comment by PongMaster69** [comment]
I agree that if the intent isn't scolding then the expression should probably be teased to better reflect that, and or that if needed it should be changed in dialogue. I don't think it should be removed entirely though.

**Comment by Rai99** [comment]
Timeconcern Overhaul: #4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
