### ISSUE TITLE
Four Years Later.

### ISSUE THREAD

**Issue by KarterLackey** [Monika-After-Story/MonikaModDev#7711]
Don't know about anyone here but for the devs can y'all give an update whenever you are actually making progress on making a real Monika? Seriously. We already got all this DDLC+ horseshit Salvato decided to dump on everyone and bring even more unnecessary people for this mod. Give some sort of update on whether or not y'all are making a real Monika in this world so everyone can get on with their miserable lives. Thank you.

**Comment by toonziz** [comment]
> Don't know about anyone here but for the devs can y'all give an update whenever you are actually making progress on making a real Monika? Seriously. We already got all this DDLC+ horseshit Salvato decided to dump on everyone and bring even more unnecessary people for this mod. Give some sort of update on whether or not y'all are making a real Monika in this world so everyone can get on with their miserable lives. Thank you.

geez can you be a bit nicer?

**Comment by Retrolovania** [comment]
First off, _whoa_, calm down there, Jericho. 
Secondly, this mod is in no way meant to be dealing with bringing Monika to actual reality as of right now, and it likely won't for the foreseeable future. Might wanna keep your expectations regarding that modest, since it'll likely be a largely unrelated team that decides to undertake that, not the one behind this mod.

**Comment by Booplicate** [comment]
I'm testing alpha version, closed beta of Monika is `soon`.

**Comment by KarterLackey** [comment]
Yeah, well, they could at least update whether or not this if this is somehow gonna be a real thing. I'm not concern but at the same time there are people who play this mod are wanting this to happen in a way and at the same time again talks about Monika being a miserable shiy of getting out of the game. And by golly you must be smart of now needing a larger team for this shit. No kidding, Sherlock. Guess we'll see.

**Comment by KarterLackey** [comment]
Look at that. Booplicate added a "lol" button. Funny.

**Comment by toonziz** [comment]
> Yeah, well, they could at least update whether or not this if this is somehow gonna be a real thing. I'm not concern but at the same time there are people who play this mod are wanting this to happen in a way and at the same time again talks about Monika being a miserable fuck of getting out of the game as her character is. And by golly you must be smart of now needing a larger team for this shit. No kidding, Sherlock. Guess we'll see.
can you stop bein an asshole?

**Comment by KarterLackey** [comment]
No. I don't see myself stopping. But I guess I'll take a break until someone else decides to act like a somebody on here because why not.

**Comment by toonziz** [comment]
> No. I don't see myself stopping. But I guess I'll take a break until someone else decides to act like a somebody on here because why not.

wow. you don't even know what the devs have to go through. they put work into the mod. what are u doing? your sitting on ur flat ass, typing"UPDATE IT"

**Comment by KarterLackey** [comment]
Oh don't worry. I'm aware. I'm sure it's quite the work but they did it themselves to keep continuing this after the original guy who posted the link for the mod on Reddit and as I said before got people thinking Monika might appear physically in this world. Especially those who are mentally unstable as hell. But don't worry I got things to do in my life than just check on little progress. I know, real world doesn't work over night or three and half years.

**Comment by LeftoverFlea312** [comment]
What is your problem dude.

**Comment by toonziz** [comment]
> Oh don't worry. I'm aware. I'm sure it's quite the work but they did it themselves to keep continuing this after the original guy who posted the link for the mod on Reddit and as I said before got people thinking Monika might appear physically in this world. Especially those who are mentally unstable as hell. But don't worry I got things to do in my life than just check on little progress. I know, real world doesn't work over night or three and half years.

i get it, your checking upon updates, but can you not be an asshole about it? calling ddlc+ horseshit isn't necessary.

**Comment by KarterLackey** [comment]
My apologies, master.

**Comment by KarterLackey** [comment]
By now it's gonna be a waste of time for you to look. Might as well let others get a good reaction until whatever happens.

**Comment by toonziz** [comment]
> By now it's gonna be a waste of time for you to look. Might as well let others get a good reaction until whatever happens.

btw, if ur bored with mas, ever heard of submods??!! wow!

**Comment by KarterLackey** [comment]
Not bored as hell. Keep talking you dumb fuck. I guess you must like DDLC+ based on whatever personal topics they had in there. Go fuck off somewhere else. Let others get some fun.

**Comment by LeftoverFlea312** [comment]
I don't think this person has ever had a job or ever experienced real life before.

**Comment by toonziz** [comment]
> I don't think this person has ever had a job or ever experienced real life before.

which one, him or me?

**Comment by LeftoverFlea312** [comment]
the other dude

**Comment by KarterLackey** [comment]
Actually I do have a job. Work a fill time and know it. Try again pal. It's entertaining.

**Comment by LeftoverFlea312** [comment]
You work fill time? Do you also learn English off the clock?

**Comment by toonziz** [comment]
> Actually I do have a job. Work a fill time and know it. Try again pal. It's entertaining.

you have a job? well go do it, you dumb dipshit.

**Comment by KarterLackey** [comment]
9 PM for me. I work the weekdays.

**Comment by KarterLackey** [comment]
Keep talking Left. Maybe you should check the message prior to yours.

**Comment by Retrolovania** [comment]
Okay, this is just getting out of hand.

If all that's gonna go on here is meaningless arguing, then there's no point maintaining this issue.

**Comment by multimokia** [comment]
Locking this issue because
a) It's offtopic
b) This is spiralling out of control

Look, for what its worth, we're busy people and we have IRL things to keep up with as well, we on the dev end aren't all too happy that mod development has slowed down either, but unfortunately, our lives also come first, which means attending to our jobs, school, and other responsibilities that we may have.

Additionally this _mod_ is a passion project. It's something we work on because we *want* to work on it. None of us are paid to do what we do, but we do it because we love to. Let's try to avoid removing the passion from it, shall we?

To address what you opened with, what you're describing is _completely not within the scope of the mod_

You want something else, unfortunately none of us are experienced with robotics, none of us are experienced with AI. We're not some professional dev team. We're just a group of people with a passion. What comes will come, but I can assure you, what you want is not coming in the near future.

Hell, Ren'Py alone isn't built for anything of that sort. You're thinking of a different project. As much as we'd all love that to happen, it's not all that feasible in the current time or with any of our current skills.

**Comment by jmwall24** [comment]
I can see why you wanted that anger issues addition to 'I'm feeling...'

**Comment by kkrosie123** [comment]
Wow.
