### ISSUE TITLE
Spritepacks layers and new groups of accesories 

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7718]
I think it would be better for the layer system, or rather the hair, to be redone. The problem is that when creating spritepacks, in some cases the hair overlaps the spritepacks you are doing. In my situation, when creating the headphones, the hair that is on the back of the head interfered and they overlap the wires, thereby spoiling the spritepack. It would be better if the hair was separate, that is, there were front hair and back hair, changing the layers does not help in any way and in some cases, because of this, you cannot create accessories for the head.It Is strange that the hair on the back of the head overlaps the things that are in front of them.
Now about new types of accessorie.
As the community grows, new people appear with different ideas and desires for spritepacks. Therefore, it would be nice to add new types of accessories (since now there are not very few of them, and if you want something unique or new, you will have to replace any item, for example, you cannot combine your item with a choker because it replaces it)For example, add categories like: Bracelets, glasses, hats, makeup, nails, earrings, and so on. So things will not interfere and you can create unique outfits.

**Comment by Booplicate** [comment]
> It would be better if the hair was separate, that is, there were front hair and back hair

There's already front and back layers for hair, even more we added a mid layer for hair as well (but I think it's not ready yet, we might need split sprites), see #7148.

> changing the layers does not help in any way

Chance are you're doing smth wrong or maybe you need to split your accessory into multiple layers.

> it would be nice to add new types of accessories (since now there are not very few of them, and if you want something unique or new, you will have to replace any item

You don't have to replace acs, it's just people use incorrect acs types to reuse existing selectors. We only add new selectors when we get a new acs of that type. Community can add new selectors themselves, and if anyone wants to contribute those officially, they are more than just welcome!

> add categories like: Bracelets, glasses, hats, makeup, nails, earrings

- bracelets are quite problematic, we're currently thinking of how to handle them
- hats are available since #5330
- makeups are also problematic with the current system, I believe
- earrings are available since #6682
