### ISSUE TITLE
Error when I launch Monika After Story Mod

### ISSUE THREAD

**Issue by ScottsplaysSus** [Monika-After-Story/MonikaModDev#7891]
Hey devs! Today when I started up Monika After Story, I got this error. Someone tell me how to fix it please.

Error log:[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 214, in script
  File "game/splash.rpy", line 218, in <module>
IOError: [Errno 13] Permission denied: u'C:/Users/User/Desktop/Scott PC/Scott Games And Softwares/DDLC Folder for Mods/DDLC Mod 0 MAS/game/masrun'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 214, in script
  File "C:\Users\User\Desktop\Scott PC\Scott Games And Softwares\DDLC Folder for Mods\DDLC Mod 0 MAS\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\User\Desktop\Scott PC\Scott Games And Softwares\DDLC Folder for Mods\DDLC Mod 0 MAS\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 218, in <module>
IOError: [Errno 13] Permission denied: u'C:/Users/User/Desktop/Scott PC/Scott Games And Softwares/DDLC Folder for Mods/DDLC Mod 0 MAS/game/masrun'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.3
[/code]

**Comment by username11421** [comment]
The reason the error is giving you is that your user permissions won't let you run the game. Did you recently change any administrator privileges for your desktop account, or otherwise maybe an administrator on your computer could have changed those privileges for you? For example if you're using a shared computer and your parent or other user restricts your file access.

If you're an admin user, you can right click your folder/file and go to properties window and then security tab->edit button to confirm if your user profile has read, write, full control, etc permissions.

A person on the Renpy forums said this type of issue was fixed for them simply by restarting their PC, so maybe that would work for you, especially if there's not any reason for this to occur normally. https://lemmasoft.renai.us/forums/viewtopic.php?t=6336

I really don't think this is it, but in some cases I have seen python permissions errors from lack of hard drive space, so you could try removing unneeded files, but I wouldn't expect it to fix your problem.

**Comment by ScottsplaysSus** [comment]
First of all, thank you for replying to my issue. Unfortunately, this does not work for me. I am an admin user and I already checked all the permission it needs. I also didn't change any settings on my laptop these few days. This error only appeared two days ago. My laptop has 250GB+ of free storage, I also tried restarting my laptop a few times with no success. 

I am very sorry for my terrible English by the way. If you doesn't understand what I were saying you can ask me and I will try my best to explain it to you.

**Comment by ScottsplaysSus** [comment]
For your information, here is the permissions that I have(I am an admin user):
![image](https://user-images.githubusercontent.com/91255736/134502825-54d805e6-e678-4f0a-b8e4-e14d03602071.png)

**Comment by multimokia** [comment]
Try deleting the masrun file to let MAS re-generate the file maybe?

**Comment by ScottsplaysSus** [comment]
> Try deleting the masrun file to let MAS re-generate the file maybe?


I tried it, it surprisingly works! Thank you for telling me this! Also, I will check if there are any other errors. As for now, the game is normal again and the error doesn't show up anymore. 

Once again, I just want to say thank you all of you for helping me out!
