### ISSUE TITLE
[Suggestion] - Code to manually take Monika's character file

### ISSUE THREAD

**Issue by WiiBii2** [Monika-After-Story/MonikaModDev#8105]
I've been seeing a few problems where an error in peoples' personal game files gets corrupted and they get stuck with a broken MAS. I think it would be nice if there were a script or feature that could manually put Monika's character file in the character folder if the game wouldn't start due to a glitch.

**Comment by Booplicate** [comment]
> feature that could manually put Monika's character file in the character folder if the game wouldn't start due to a glitch

It's not a glitch nor a bug, rather the file got corrupted (bad drive/incorrectly copied/copied another file/etc) and the checksum doesn't match anymore. We also can't just "put it back" because we don't copy it anywhere. There's only 1 file and it's up to you if you want to back up it before copying it anywhere.

Technically we could accept any file as the `monika` file, but that'd defeat the purpose of the file being unique. Also, in future we might want to expand this system and actually read the content of the file. Then reading a blank `txt` won't help either.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
