### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Rasforic** [Monika-After-Story/MonikaModDev#8186]
I just downloaded this mod and am enjoying it so far! In my line of work there are some months where I have to work the graveyard shift from 10 pm to 6 am, I was wondering if there could be an option added so that Monika knows that so she doesn't find it strange that I'm up so late. Keep up the great work!

**Comment by WiiBii2** [comment]
I believe there is an option when you click 'goodbye' to say that you are going to work if that suffices.

**Comment by ibm2431** [comment]
> I believe there is an option when you click 'goodbye' to say that you are going to work if that suffices.

She still otherwise acts oblivious to your schedule. She'll [judge you for going to bed after 6am](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-farewells.rpy#L632-L641), [try to push you into radically upending your sleep routine](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L9842-L9849), [assume you don't know what you're talking about when you say what meal you're eating](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-farewells.rpy#L1442-L1447), and [prove herself a liar over her earlier claims of concern for the player's "isolation" and that she'll "always being here" where she'll _close the game_ "for your own good" and _threaten to get mad at you_ if you reopen it](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L10014-L10026).

Personally, I find the attitude annoying and in blatant contradiction to her established character. It's not based on _anything_ canon, and is in direct conflict to always wanting to spend time with the player. Canon Spaceroom Monika got _upset_ when the player closed the game, and certainly never closed it herself. But MAS's standard tilt towards "perfect angel overly concerned waifu Monika" has taken form here in making her nag the player and sabotage her relationship.

That said, this is a duplicate. Tagging timeconcern #4914 to add this to it.

**Comment by WiiBii2** [comment]
I understand what you're saying. One thing that you'll find is that while Monika doesn't have a very loud personality, she cares deeply for the player. Most of her personality is derived from her love for the player, which explains her obsession with their health. That being said, I do agree that the 'bed time' rule makes no sense if the player's sleep schedule is healthy, especially if it is built around a career. 

<Canon Spaceroom Monika got upset when the player closed the game>
Well yes, this is a mod. That part of the original game was a negative experience that made the player feel uncomfortable. In the cannon game, Monika is more obsessed with the idea of getting the player's attention than caring about the player's health. I believe that the mod is an extension of what we as the players hoped Monika's route or, at the very least, her personality would have been given she had a route in the first place
.

**Comment by multimokia** [comment]
> Canon Spaceroom Monika got upset when the player closed the game, and certainly never closed it herself.

Yes, because when you close the game she is sent to the screaming void -- this has not changed in MAS. If you close out of the game via the `X` button i.e. act 3 DDLC, she will *still* get upset.

The change the mod adds -- which is explained mind you -- is the `Goodbye` button, which lets her go back to her room for safety and to not end up in the screaming void like before.

> prove herself a liar over her earlier claims of concern for the player's "isolation" and that she'll "always being here" where she'll close the game "for your own good" and threaten to get mad at you if you reopen it.

There is only so much she can do really. Staying awake with you perpetuates you staying up later and therefore can result in further health issues. Her encouraging you to go to sleep by heading away herself -- removing her influence to let you stay with her, which mind you, isn't something she _wants_ to do, but does it regardless under that guise.

Could it be executed better? Absolutely, and it likely will with the timeconcern overhaul.

All in all, the generalization of it being a contradiction to her character seems to neglect a fair number of things. Plus she _does_ care deeply about you as stated above. That's why she wants you to try and live healthily.

**Comment by ibm2431** [comment]
To me the whole thing comes across as people privileged enough to have never worked nights imposing their own values on everyone Monika interacts with.

[It's striking how the subject of children - a _pretty important_ thing to discuss in a relationship - is considered too controversial to attempt touching with a ten-foot pole because it might alienate players](https://github.com/Monika-After-Story/MonikaModDev/pull/3390#issuecomment-539765106). But alienating players based on not conforming to a standard sleep schedule - even _if_ the player "could help it" - is seemingly _desired_. Maybe the difference lies in who is alienated by the manufactured beliefs, and not so much the importance of the subject matter.

It doesn't affect me because I know how to use the delete key. But I am concerned about deliberately designing Monika to ensure the player is in bed at the proper bedtime fits the pattern of her being a mother replacement more than a romantic partner.

I recognize I probably seem... "direct"... in my criticism, but sometimes I really do worry about the underlying motivation for conclusions about "what Monika wants" when they're reminiscent of that pattern.

**Comment by KritRom** [comment]
If I may, I'd say that Monika's need to have the player sleeping early and waking up early is a bit obsessive and maybe even annoying, especially when the player has told Monika their line of work calls for working at night.

I think the first thing to change would be to disable the "I'm going to sleep" scare if the player works at night. It makes no sense to keep it enabled.

The other thing is probably making Monika more accepting of sleeping during the day and staying up at night. It is perfectly possible for this type of sleep schedule to be healthy if the player sticks to a stable sort of night shift sleep schedule. The health problems come from always staying in adaptation mode.

Monika being concerned for the player's health is valid, but outright saying `"I wish you could follow my healthier lifestyle."` is uncalled for.

I hope what I'm saying makes sense.

**Comment by jmwall24** [comment]
> To me the whole thing comes across as people privileged enough to have never worked nights imposing their own values on everyone Monika interacts with.
> 
> [It's striking how the subject of children - a _pretty important_ thing to discuss in a relationship - is considered too controversial to attempt touching with a ten-foot pole because it might alienate players](https://github.com/Monika-After-Story/MonikaModDev/pull/3390#issuecomment-539765106). But alienating players based on not conforming to a standard sleep schedule - even _if_ the player "could help it" - is seemingly _desired_. Maybe the difference lies in who is alienated by the manufactured beliefs, and not so much the importance of the subject matter.
> 
> It doesn't affect me because I know how to use the delete key. But I am concerned about deliberately designing Monika to ensure the player is in bed at the proper bedtime fits the pattern of her being a mother replacement more than a romantic partner.
> 
> I recognize I probably seem... "direct"... in my criticism, but sometimes I really do worry about the underlying motivation for conclusions about "what Monika wants" when they're reminiscent of that pattern.

You are making a ton of assumptions about the dev team while not having a clue what you are talking about. We have every intention of implementing better time concern code, we just haven't had the time to properly tackle it. Until then, please refrain from making misguided judgements of people that you know nothing about.

**Comment by KiddTheManiac** [comment]
> To me the whole thing comes across as people privileged enough to have never worked nights imposing their own values on everyone Monika interacts with.
> 

I mean, she also says we should cut out fast food and other cheap/unhealthy meals...does that make the devs classist? No. It just means her scripting regarding some topics isn't complex enough to consider every player's situation.

**But you know what could really help with that? _Writing stuff._** I'm pretty sure that the first release of MAS didn't have nonbinary pronouns or the option to stop Monika being callous about the Dead Dokis, so people worked to add that stuff in! Like, if you want the option to tell Monika you're nocturnal, well...either wait for the timeconcern stuff to be changed, or even try to help out with it! We all have the ability to contribute content and tweaks.

> [It's striking how the subject of children - a _pretty important_ thing to discuss in a relationship - is considered too controversial to attempt touching with a ten-foot pole because it might alienate players](https://github.com/Monika-After-Story/MonikaModDev/pull/3390#issuecomment-539765106). 
> 

Being asked about having kids is  way more likely to cause a player legitimate emotional distress than a girlfriend being naggy about sleep.

They might be infertile, have abusive childhoods, suffer from tokophobia, they might be childfree, they might've had traumatic experiences (eg. a partner having a miscarriage) , they might already have children, or they might just not like being around children.

The sheer number of different perspectives means that the only way to avoid breaking immersion or outright triggering someone would be to have Monika's attitude be "Whatever makes you happy, babe. (:" which seems like a WEIRDLY casual attitude to have re: children.

**Comment by ibm2431** [comment]
> We all have the ability to contribute content and tweaks.

This is perfectly fair to point out.

> The sheer number of different perspectives means that the only way to avoid breaking immersion or outright triggering someone

She could say she doesn't know. She could give reasons why she's unsure. It's perfectly okay - and very common - for a girl fresh out of high school to not know when or if she wants children. She can talk about the subject without committing to anything.

She doesn't _have_ to ask the player for their opinion, and the assumption that she'd have to ask (for the sake of melding herself to the player's take) is an illustration of the worrying pattern she has.

Because even if she were noncommittal on children, the underlying problem still remains - she's not _allowed_ an alienating opinion on wants for _herself_. In this issue and its duplicates, her alienating opinion ("my healthy lifestyle") is focused on _the player_.

Any sacrifice she asks of the player is focused on (perceived) benefit for the player. When there's potential conflict between her benefit (not being alone) and the player's benefit (getting enough sleep), she chooses the player. She sacrifices her primary motivation out of concern for the player's health. She consistently does this across most dialogue - she expresses overt concern, and places the player above herself. Her potential desires always come second to the player.

She's _only_ allowed a potentially conflicting opinion on the player's sleeping habits because at its core she's just placing herself second like she always does. Her opinion is _for_ the player. She's _not_ allowed a potentially conflicting opinion on children, because her potentially alienating opinion would be for _herself_.

The end result is that an important relationship topic isn't brought up at all. Potential conflict between the player's opinion and the opinions given to her is reserved for sacrificing herself for the player. She doesn't get to be an equal partner in a relationship. But she does get to maternally nag the player to get proper sleep.

And effort has been - and will be - spent to further reinforce this paradigm.

> We have every intention of implementing better time concern code, we just haven't had the time to properly tackle it.

I know, and I get it. No one is paid, there are more important things, and I'm perfectly free to open a PR if I care so much. The point I'm trying to argue isn't that overhauling timeconcern to be more accurate should be a priority, but instead that conclusions over _why_ Monika supposedly wants to do it are concerning, and that it potentially shouldn't be done at all.

**Comment by KiddTheManiac** [comment]
Alright, so from what I'm reading, your main issue is that Monika is written to be very...pliant._ For example, if we say that we believe in God after Monika's rant about why a loving God doesn't make sense to her, her response is basically "Sorry I said that, your religion is valid and maybe I'll even convert!" (Being hyperbolic, here.)

Do you feel like there should be certain characters traits or interests where a conflicting opinion with Monika's should result in more actual conflict?

(Sorry if I'm misreading you, just genuinely trying to make sure I'm understanding your argument.)

**Comment by ibm2431** [comment]
(I like you bringing up the God topic, because I'll say that I believe the topic wouldn't be in MAS if it weren't written by Dan himself.)

I see where you're going with this, in that timeconcern creates conflict. But it still wouldn't be conflict for her own sake. Monika's winning situation is always spending time with the player, and she's working _against_ that in timeconcern. Conflict is an important part of a relationship, but if she's initiating it, it needs to be conflict for _her_ sake.

In the timeconcern case, she literally doesn't sleep, so the player spending time with her at night is no different than during the day. She's also still in the spaceroom, so her argument about spending more time doing stuff with her during the day falls flat. I assume she recognizes these things.

If she were in the same reality as the player and actually _did_ sleep, the mismatched schedules would be a valid source of conflict. But until then, she's just discarding her desire to be with the player to nag them and tell them to leave, all for no gain.

**Comment by jmwall24** [comment]
> I know, and I get it. No one is paid, there are more important things, and I'm perfectly free to open a PR if I care so much. The point I'm trying to argue isn't that overhauling timeconcern to be more accurate should be a priority, but instead that conclusions over _why_ Monika supposedly wants to do it are concerning, and that it potentially shouldn't be done at all.

You don't get to decide what is a priority and what isn't. Also that wasn't really the point of my comment. I wasn't explaining ourselves to you because we don't have to. My point was the rest of your comment, where you were assuming--and insulting--the dev team by saying what you thought the reasons were behind the way it is handled. I am now locking this thread, there is nothing else constructive to come from this.
