### ISSUE TITLE
Handholdings [suggestion] 

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8210]
Quite an interesting idea. You can ask Monika to touch the screen so you can touch the screen too, and it will feel like you are holding each other's hands! It just requires you to draw a hand sprite. It will be somewhat similar to the function that is now in the game, only more realistic.It may look a little strange, but the idea is very cool for me.

**Comment by fromulus** [comment]
Sounds cute, but it wouldn't _just_ require to draw a hand sprite, we'd have to redraw Monika's pose and arms for it to even look natural.
This, in turns, means we'd need to draw new poses for all the outfits, and would make old spritepacks incompatible with the feature, as they would need to be updated to the new pose(s).

**Comment by Nikv2005** [comment]
> Sounds cute, but it wouldn't _just_ require to draw a hand sprite, we'd have to redraw Monika's pose and arms for it to even look natural.
> This, in turns, means we'd need to draw new poses for all the outfits, and would make old spritepacks incompatible with the feature, as they would need to be updated to the new pose(s).

I don't think it will take a lot of new positions, two or three will be enough. The mod is evolving and unfortunately all things ever become old, and because of spritepacks alone, the development of the mod cannot be slowed down. After all, sooner or later these spritepacks will become old and unsuitable for the game.

**Comment by Booplicate** [comment]
I like the idea of you both touching the screen, but...

Spritepacks are a huge part of the mod, we can't just throw them away. So far there's no reason for them to become old or unsuitable. Adding one new pose would require a lot of efforts, even if you only consider official outfits.

**Comment by Nikv2005** [comment]
Well, I did not say to throw them away, but you can update it, even though it is expensive. But okay, I'll have to wait, and hope that this will be added, because this is a very cool function.

**Comment by KiddTheManiac** [comment]
It's not necessarily a "cost" thing, but...there are hundreds of different outfits that people on the Reddit have made, some of whom haven't talked about MAS or even been online in years. 

It'd be a massive effort to contact all those artists / etc and be like "Hey, remember when you drew that skimpy dress two years ago? Well now we need you to find that file and make some new variations on it!" 

The alternative would be to do what some hair/outfit combos do "I don't think these two go together", but it'd be pretty immersion-breaking to have Monika say that she can't hold your hand because her t-shirt is just...too tight to move her arm in that specific direction or something. Especially with just how many outfits it'd apply to.

**Comment by ThePotatoGuy** [comment]
We can programmatically disable/enable things based on the clothing, so we could still use non-updated spritepacks alongside updated ones. However, as mentioned, it would be odd if the clothing is the only reason she can't move her hand, and there's no good way to explain the discrepancy to the player.

**Comment by Nikv2005** [comment]
As far as I understand, this cannot be done yet. If you think so, then in the future there will definitely be new poses, and this cannot be avoided. I'll have to wait for better times for this idea.After all, I did not want that because of the spritepacks the game could not develop in this direction.

**Comment by fromulus** [comment]
You seem to believe new poses are inevitable, but I wouldn't as sure on the matter.
As we've already explained here, adding/modifying poses is a big and difficult ordeal due to all the art it requires both from contributors and from the sprite pack making community.

We've already had to go through that about two years ago when changing the leaning poses, and that alone was already a mess the people who worked on it do not want to go through again, even though we had nowhere near as many sprite packs as we do today.

I understand the frustration, but it's ultimately like using Monika's standing sprites;

It sounds nice on paper, but we don't really need it, they don't bring _that_ much more to the mod, and yet they represent a massive amount of work that could be spent on actual features instead.

It's just not worth the trouble.

**Comment by Nikv2005** [comment]
Okay, but still ideas like this will be very interesting, although I will require a total redrawing of the spritepacks. And yet I think that in the future there will definitely be changes in poses or something like that. While this does not really develop the mod, but if you take the example of Monika standing, it will add some interactivity, and it will look good. But okay, this is impossible to implement at present, perhaps in the future there will be something similar. I will sit and wait

**Comment by fromulus** [comment]
Problem is that the more we wait to do something like that, the more outfits will be added over time and therefore the more work there will be to do.
Not only is it unlikely we'll tackle something like this today, but it's only going to get more and more unrealistic of a task to complete over time.

**Comment by Nikv2005** [comment]
What about official outfits? , you can update only them . It's a good that you thinking about community too. But if you update only official spritepacks , that's be easier . And people from the community will update their spritepacks themselves if they really want it.

**Comment by kkrosie123** [comment]
It's... Not as easy as it sounds. Chances are we won't be adding more poses. Cool idea, but as of now, not feasible. Too much work for one small feature.

**Comment by Nikv2005** [comment]
Now it may not be possible to do this, but why not in the future? Since mod can be developed, in the future it is necessary to somehow add new poses so as not to be limited to the old ones.

**Comment by Booplicate** [comment]
> What about official outfits? , you can update only them

As I said, even updating only official outfits would take a lot. But also we do not want to break spritepacks. It's not an option.

> And people from the community will update their spritepacks themselves if they really want it.

We can't expect a thousand of people to update their spritepacks, just not feasible at this point.

> in the future it is necessary to somehow add new poses

We actually don't plan to add new poses. Because again, that'd break outfits/accessories. We did it before and it'd be the last thing we'd do again.

**Comment by Nikv2005** [comment]
Maybe new poses are not needed, but I think it will be easier to change old ones. for example, to make a pose where, for example, the hand is standing somehow differently, it only requires an additional hand sprite. This is exactly what you can do for handholdings, you just need a new hand sprite and that's it. And this does not require redrawing the spritepack, but only adding a sprite for the hand.

**Comment by ThePotatoGuy** [comment]
>As I said, even updating only official outfits would take a lot. But also we do not want to break spritepacks. It's not an option.

Just want to clarify, an additional pose would not break spritepacks. The only time a spritepack-breaking change would occur is if the sprite-json format changed, which at this point in time will be extremely rare.

>then in the future there will definitely be new poses

I'm not going to say that *new poses won't be added in the future. But I will say that its very unlikely, because I have a strict requirement that all official outfits and official spritepacks support all features of the mod. This means that if a new pose is added, all of these need to support the new pose. (This is what happened with the hair color change, where **every** hair that we ship with was changed). So in short, if you want to see a handholding pose, you (or someone else) will have to create the sprite for every outfit and official spritepack we have.

*new pose meaning new art - adding new poses that use the existing arms is supported and easy to do.

**Comment by Booplicate** [comment]
> an additional pose would not break spritepacks

Bad wording, what I meant is even with a fallback it would look bad. Not really *break*, but basically make unusable. So people would have to update their spritepacks, but there's *a lot* of them. I think it'd be very unprofessional of us to give the feature for creating custom outfits, but require people to redraw their assets every year. I'm not considering programmatically toggling a feature because we can't clearly explain why it works with one dress, but not with another. I think a new pose should be considered only if it'd really add a lot to the mod, not just 1 or 2 places where it'd be used. All in all, I think it's not worth as of now. Unless we do just a wrist motion, which would allow us to save on outfits/spritepacks update.

**Comment by ibm2431** [comment]
Leaning body pose comes pretty close and might be workable. A modified version of `body-leaning-def` keeping the head upright, and a modified `arms-leaning-def-left-def` editing the hand at the wrist to face a palm towards the player can result in a "new" pose that doesn't affect official or most community clothing packs.

An artist I am not, so I apologize for this composite image monstrosity, but here's a mockup of what it might look like:
![handhold](https://user-images.githubusercontent.com/13112942/141520165-46efacea-b02d-43d6-b832-953767185823.png)
(I have no doubt I have some misaligned sprites; pretend it all lines up.)

I needed to flip the [original hand image](https://en.wikipedia.org/wiki/File:Human-Hands-Front-Back.jpg), so the wrong-side shading makes it look disconnected, but I think an actual drawn asset might look believable with the existing "leaning" arm pose.

It'd need two new body sprites (matching the "alignment" of existing leaning pose), but existing clothing assets wouldn't be changed.

There would be an issue with community outfits that have baked-in _gloves_. First solution I've got to handle those (other than ignoring) might be adding a new exprop for "gloveless". When absent, results in some line from Monika saying, "hold on, let me change clothes - holding your hand just isn't the same when I can't feel the warmth".

Alternatively: Monika is self-aware that she needs art assets to represent her. It wouldn't be out-of-character for her to just _say_ that she can't do something if the outfit's art isn't compatible. This could even lead to her wistfully saying how nice it'd be to be free from the game and be able to do whatever she wants without pre-drawn art - "A girl can dream, right?"

**Comment by ibm2431** [comment]
It might help to clarify the "screen distance" that's being imagined:
![screen-distance](https://user-images.githubusercontent.com/13112942/141538527-3d3ee311-07e7-4a5f-8525-08345413e1df.png)
The above mockup envisions a close screen distance (A), which is the only way the existing leaning pose might come close with just edits to the hand. But if the screen distance people are imagining is farther out (B), then it would definitely require clothes to have a new outstretched arm sprite.

**Comment by Nikv2005** [comment]
I like this idea . You can imagine that the elbow is on the table and the arm is slightly bent, no one has canceled the fact that Monika can still tilt one side. Although there are problems with the position of the hand, ideally the hand should be at the edge of the monitor so as not to cover the face. Most of all, to make everything look aesthetically pleasing and beautiful, you need to draw a separate hand sprite. But I do not think that it will already require a lot of effort in a small change in the Json file and drawing a hand. You can try to improve that idea in which you do not need to draw a hand sprite, but there it will need to develop so that everything looks normal

**Comment by shinolife63** [comment]
> Leaning body pose comes pretty close and might be workable. A modified version of `body-leaning-def` keeping the head upright, and a modified `arms-leaning-def-left-def` editing the hand at the wrist to face a palm towards the player can result in a "new" pose that doesn't affect official or most community clothing packs.
> 
> An artist I am not, so I apologize for this composite image monstrosity, but here's a mockup of what it might look like: ![handhold](https://user-images.githubusercontent.com/13112942/141520165-46efacea-b02d-43d6-b832-953767185823.png) (I have no doubt I have some misaligned sprites; pretend it all lines up.)
> 
> I needed to flip the [original hand image](https://en.wikipedia.org/wiki/File:Human-Hands-Front-Back.jpg), so the wrong-side shading makes it look disconnected, but I think an actual drawn asset might look believable with the existing "leaning" arm pose.
> 
> It'd need two new body sprites (matching the "alignment" of existing leaning pose), but existing clothing assets wouldn't be changed.
> 
> There would be an issue with community outfits that have baked-in _gloves_. First solution I've got to handle those (other than ignoring) might be adding a new exprop for "gloveless". When absent, results in some line from Monika saying, "hold on, let me change clothes - holding your hand just isn't the same when I can't feel the warmth".
> 
> Alternatively: Monika is self-aware that she needs art assets to represent her. It wouldn't be out-of-character for her to just _say_ that she can't do something if the outfit's art isn't compatible. This could even lead to her wistfully saying how nice it'd be to be free from the game and be able to do whatever she wants without pre-drawn art - "A girl can dream, right?"
> 
> **edit:** A mockup attempt with some clipart from getty instead of wikipedia photo: ![handhold2](https://user-images.githubusercontent.com/13112942/141529430-bf2c2c03-fb5f-4915-9285-4fb01de127cd.png)


I kinda like this approach, feels like its worth fleshing out as a submod or something and testing from there.

**Comment by ThePotatoGuy** [comment]
closing as rejected. no plans to add additional arm poses at this time.
