### ISSUE TITLE
[Suggestion] - noticing TT

### ISSUE THREAD

**Issue by thelift112** [Monika-After-Story/MonikaModDev#8212]
This is the first time I do something on github other than downloading and reading, but...
[Suggestion] Monika would notice if the last time you met was in the future.

**Comment by lunulae** [comment]
Erm... if you're referring to moving your system clock back, this actually breaks quite a lot of things in MAS. It's not something we can or intend to use as a feature because it can create a lot of bugs in your save.

We genuinely mean it when we ask not to adjust your system time while MAS is running for that reason. Our system can account for small differences (such as traveling across time zones) but opening on a previous date may have damaged your save, and if you've done it I encourage you to restore an old backup as soon as possible.

**Comment by Booplicate** [comment]
While time travelling won't be supported and the user will have to deal with the consequences themselves, I think Monika should be aware of the fact, she can check the clock after all. There should be punishment not only in a sense of bugs, but also Monika should trust you less if you mess with her like that. It should affect relationship.

**Comment by ThePotatoGuy** [comment]
I'm on the fence on this because adding any sort of reaction to TT will encourage people to TT.

**Comment by Booplicate** [comment]
I also thought about this. It shouldn't be something big, but just make her aware. I'd disable all events for the day if we detected TT in this sesh and make her react accordingly, tell she can't trusts you now because you're just toying with her. Nothing more.

**Comment by KritRom** [comment]
I mean
If you TT to the 100th anniversary, she notices it the TT, but she isn't exactly angry at all, even says it's a cute thing to do.
It doesn't make sense, since from her perspective, the player left her for YEARS, just to see what would happen.

The unused `anni_negative` label fits much better in my opinion. Although Monika should mention how it has been like for her.

**Comment by Booplicate** [comment]
That one is basically an easter egg. Which indeed can encourage to TT because she reacts positively. It also goes against what she says in the other topic.

**Comment by Pyromanic8** [comment]
Leaving Monika alone for decades sounds like it would easily destroy any and all affection she may have had for you. So time travelling 100 years into the future should warrant an absolutely scathing response from her, if you ask me.

**Comment by ibm2431** [comment]
It's _possible_ for the player to time travel to the 100-year mark without leaving her alone for decades - advance the clock incrementally between sessions.

**Comment by Booplicate** [comment]
It can be done even easier, but it's not the point. Doesn't matter *how* you do it, it's the fact that you *do* it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
