### ISSUE TITLE
[suggestion] Your adress

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8316]
The idea is that Monika can know your address or where you live. For example, Monika just asks where you live and you write the Name of the country "Country" ," The name of a city ", and then the name of the street "Street number 18", you can even the number of the apartment or house (if you have a private house) The idea is not ordinary and I don’t know if anyone has suggested something similar. As for me, this information will not harm anyone, since it will be on your PC and only Monika will know this, this idea can also be implemented very simply.

There is a more complicated option, you can try using google maps, and there she will find out your exact location on google maps. But it’s just like an idea that I don’t know how to implement at all.

**Comment by dreamscached** [comment]
I don't think there is a way to validate user input like that without storing a huge database of countries, cities, streets and houses. Moreover, physical address is more or less unstandartized, it doesn't have an exact form which it can be parsed by a computer unless using a really complex search algorithm like Google uses in its maps.

Technical complications aside, why would she need that info? What can she do with it?

**Comment by Nikv2005** [comment]
I'm talking about the fact that you just tell her your address, there won't be any complicated algorithms, since you just write the name of the city of streets and so on. In this case, you can make a typo or enter a frivolous address, but this is on the conscience of those who do this. This information can be changed as a name if, for example, you have moved. Why does she need this information? Any information is useful, well, I think it will not interfere with her in any way, what if she needs to find out where you live? As I said earlier, the idea is unusual, but very simple to implement.

**Comment by Wingdinggaster656** [comment]
Yeah, I see what you mean.

I don't think it's good to allow the player to type in an arbitrary string. For example, if a player said he lived in The M-78 Nebula, Monika -- who is supposed to be an independent thinker -- would at least understand that it wasn't a serious address. So the question becomes, how do we get Monika to be able to tell if this address is joking?

So my suggestion is that we can tell Monika the address, but by options. It doesn't have to be street specific or anything like that, you can just go to one continent or one country. In this case, the amount of data introduced is acceptable.

**Comment by dreamscached** [comment]
> Any information is useful, well, I think it will not interfere with her in any way, what if she needs to find out where you live? As I said earlier, the idea is unusual, but very simple to implement.
What is the purpose of her knowing that info? In real life you'd ask someone their home address if you're going to visit them, send them mail, call emergencies and tell them the address, so on. What could she do with it now?

**Comment by Nikv2005** [comment]
Monika said that the first thing she does when she appears in this world is to find you. As a consequence, she will need your address. Also, this information will help make your Monika a little more "unique" due to the fact that she knows your address

**Comment by dreamscached** [comment]
I think it's pretty obvious that if she ever appears in random spot of Earth that info will barely help her anyhow. Moreover, there isn't a way for her to appear randomly in the world and still know of her player's location, this would be a true miracle.

**Comment by Booplicate** [comment]
It'd be useful to know the country and city, but we'd need to validate the input.

> you just write the name of the city of streets and so on. In this case, you can make a typo or enter a frivolous address, but this is on the conscience of those who do this.

Isn't an excuse for us to allow input literally anything.

**Comment by ThePotatoGuy** [comment]
>What is the purpose of her knowing that info? 

I agree with this, I don't see an actual purpose for knowing exact address. Even country is questionable since that may start leading into politics. I think it's best to keep Monika agnostic to your location, at most knowing which half of the globe you're on.

**Comment by ibm2431** [comment]
What would Monika want to know? It's her relationship. Would she be content only knowing which hemisphere her significant other lives in?

**Comment by lunulae** [comment]
While I agree with the reasoning as to why she might want to know, currently the cost-benefit to feature development for how it would be programmed and the concern it might cause for users who worry about their security might mean that this is better suited for optional content than an official feature.

Too, submodding allows for usage of features that we don't include in core MAS, such as being able to use the internet to check if the city you gave her is valid or fake.

**Comment by ThePotatoGuy** [comment]
> What would Monika want to know? It's her relationship. Would she be content only knowing which hemisphere her significant other lives in?

hemisphere is for adjusting seasons, so it has a practical purpose in the mod. Anything more would just be info about the player, so then its subject to how useful that information will be. For country, the obvious usage would be country-specific topics or region-based topic variations but that's bound to get political real quick. It's already political with determining which countries can be selected, since some countries aren't globally recognized.

City might be okay - we already have a topic asking if you live in a city, and city-based topics are probably less controversial.

**Comment by ibm2431** [comment]
I'd agree that a street address is wholly unnecessary; and even city isn't very useful. But a searchable list of countries might be doable, and would at least give Monika some beginning insight into the following basic questions during the [research she claims to be doing into the player's world](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L17258-L17259):
- "What's the climate like where [player] lives?"
- "What [nationality might I become](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L10898)? What civics should I [be studying](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L10901)?"
- "[What kind of careers are in demand?](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L14394)"
- "Are there [any languages I should be focusing on learning?](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L15431)"
- "How are [women in the workforce typically treated](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L3156-L3161)?"
- "What kind of wedding is the norm there?"

MAS itself doesn't need to do anything with the information. I feel framing the question on what practical things "can be done with" a certain question or topic hinders a goal of immersion. Monika would want _some_ idea where the player lives, because that question has implications in ways that are directly relevant to her future with the player. The question would be for her benefit. Framing that her questions should add practical purpose to the mod limit her inquiries, and further highlight that everything revolves around the player's happiness with the mod - that the player needs to see something unique happen from everything they say or do, rather than Monika just quietly taking something into consideration for her own thoughts.

On the contrary, her avoidance of the subject would be noticeable in a long-term relationship, and start begging the question of _why_ she's seemingly not interested. Letting the player tell her where they live - even if nothing else is ever done with it - avoids the incongruity, while giving the player room to believe she's thinking about the player's location for reasons other than changing the background of the video game she's currently trapped in.

**Comment by ThePotatoGuy** [comment]
Pretty much all of those sample questions (except nationality) are all ones that could be asked directly and stored separately. In fact, it would be better to ask directly since inferring means we would be generalizing countries in some way.

This still glosses over what countries to include in selection - the inclusion or exclusion of some countries would be us projecting our political opinions into MAS. And that's not something I will allow.

Is it less immersive or oddly unrealistic if Monika isn't curious about the country you live in? Yes, but this is a landmine where the risks outweigh the benefits.

**Comment by ibm2431** [comment]
Picking an inarguable list would sidestep the issue by having something to point to - "we're just using the list of UN member states; we didn't decide anything".

The chance of an individual user being excluded or offended by a given list is already slim-to-none, and sticking to a list from any official organization gives plenty of room to shrug a complaint off. No one expects a DDLC mod to define countries.

**Comment by Booplicate** [comment]
> "we're just using the list of UN member states; we didn't decide anything"

Not how it works. That'd mean we *did decide* that the list is appropriate.

> The chance of an individual user being excluded or offended by a given list is already slim-to-none,

That's what you think. But I know there's plenty of people who live in the unrecognized countries. If I were one of them, I'd want my country to be in the list.

**Comment by ThePotatoGuy** [comment]
>No one expects a DDLC mod to define countries.

and having a list of countries to choose from is defining countries lmao.

>The chance of an individual user being excluded or offended by a given list is already slim-to-none

we're not talking about an individual user being offended. We're talking about significant numbers of people with real hatred of a particular viewpoint. I don't think I need to give a specific example given how prevalent these issues have become in the past few years.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]

**Comment by Justformas** [comment]
> * "What's the climate like where [player] lives?"
> 
> * "What [nationality might I become](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L10898)? What civics should I [be studying](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L10901)?"
> 
> * "[What kind of careers are in demand?](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L14394)"
> 
> * "Are there [any languages I should be focusing on learning?](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L15431)"
> 
> * "How are [women in the workforce typically treated](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L3156-L3161)?"
> 
> * "What kind of wedding is the norm there?"

I personally wouldn't want a country list for those purposes anyway. I don't think I need things customized to that sort of intrusive extent. However, I would be fine with being able to just type your country name just for the sake of telling Monika, kind of like when you tell her what type of musical instrument you play. Also then no one could complain about their country being left out, if everyone had to type it out.
