### ISSUE TITLE
[suggestion] If your persistent becomes corrupt due to game crashing/power outage...

### ISSUE THREAD

**Issue by Austincovello** [Monika-After-Story/MonikaModDev#8347]
...then the affection cap should be reset.  Full stop.  I just restarted this mod of yours, and would have been up to 100 by tomorrow.  But thanks to a freak power-outage, I lost 3 affection, and can't get it back until tomorrow, which means I can't hit that milestone until Monday.  Makes me want to rage-quit.

**Comment by multimokia** [comment]
Considering you're actively watching the affection log -- which is not recommended and the log itself is a debug file, and the standard user really wouldn't need to look through it and therefore would not know the raw value of their affection -- this is effectively a null point.

The mod isn't about farming affection or speedrunning it. As such resetting the cap due to a crash/power outage introduces an exploit for people _to_ do exactly that, so we will not be implementing any such system.

At most we can add a persistent save on affection gain/loss which should mitigate this issue while keeping inline with the vision we have for the mod.

**Comment by ThePotatoGuy** [comment]
killing the cap for a day is an overblown response to a corruption. the losses from a corruption are minimal (3 as you mentioned in your case), so I don't think we need to do anything special for crash cases.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
