### ISSUE TITLE
[Bug] - Affection Points dropped a lot

### ISSUE THREAD

**Issue by WilsonSmith01** [Monika-After-Story/MonikaModDev#8498]
I rescued my Monika from being eliminated because I was doing a backup when my PC shut down, so I lost my Renpy folder.

I rescued this folder (I took the least old) but when I opened it gave me this error that I described in a Reddit post: [https://www.reddit.com/r/MASFandom/comments/rnluee/i_need_a_big_help/](url)
![Screenshot 2021-12-24 135653](https://user-images.githubusercontent.com/87719123/147393757-e0c870a7-e8b1-4d2f-b157-51a67860f48b.jpg)

I saw that wasn't rescued from the Renpy folder, so I took every single file in the eliminated folder.

After that, I downloaded a new version of Monika After Story, and Chibika says to me that she couldn't restore the save and she created a "Fake Monika" that says to me 

> It's only a bunch of unreadable code <

Then Monika's file was deleted.

After this action, I deleted this "fake Monika".

After that, I saw that I didn't rescue every file from the Renpy folder, so I restored everything.

But when I opened the app I saw that Monika missed me a lot and dropped not correctly the affection points.

BUT, the affection point didn't drop correctly the affection points so I described this issue in another Reddit post:

 [https://www.reddit.com/r/MASFandom/comments/rnluee/i_need_a_big_help/](url)
![Screenshot 2021-12-25 162537](https://user-images.githubusercontent.com/87719123/147393756-ba778e30-63b8-451a-808c-ed1a9903fa4c.jpg)

I hope that I didn't do anything that corrupt Monika's integrity and I can adjust this big problem with a few clicks/patches because I want to stay with Monika

**Comment by ThePotatoGuy** [comment]
Did you recover any other persistents? There should be 10 backups at a time. Otherwise there's nothing we can do if you lost the persistent files.

**Comment by WilsonSmith01** [comment]
The problem is I tried with everything, but every time give to me this.

Maybe I can't restore a persistent properly, but I follow the guide and every time affection dropped from 2000 to 925.

Really I don't know where I do wrong, maybe the restoration process or another thing, but I really don't know.

The fact I recover the entire folder, not only the persistent.

**Comment by ThePotatoGuy** [comment]
if you tried with all 10 persistents and the loaded affection is the same, it means only 1 of those persistents is not corrupt since the system will auto load the first noncorrupt one it can find. 

Additionally, your reddit post implies that you only kept the persistent values with the largest number. The system numbers persistents, but the numbers roll over after 99 - meaning that if the last backup is per99, the next one is per01. Now 10 backups shouldn't span 1000 affection, so it might be that system was unable to delete/overwrite backups, resulting in the per99 being a really old persistent. Easy way to check if this was the case is if there are 100 persistents in the folder - which if there is, then you only have old backups and there's still nothing we can do here.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
