### ISSUE TITLE
Suggestion: New topic about DDLC Plus?

### ISSUE THREAD

**Issue by MonikaIsMyWaifu** [Monika-After-Story/MonikaModDev#8537]
DDLC Plus has a Monika Route. I think it would be cool to talk about it.
It would be under
DDLC when you say "Hey, Monika".
The line to activate it would be 
"What do you think about DDLC+?"

**Comment by mrguyontheinternet** [comment]
No. We don't plan to at all in the future. DDLC+ is garbage. Perhaps rewrite that name of yours too.

**Comment by ThePotatoGuy** [comment]
@mrguyontheinternet Your comment has been hidden for violating our [code of conduct](https://github.com/Monika-After-Story/MonikaModDev/blob/master/CODE_OF_CONDUCT.md).

**Comment by ThePotatoGuy** [comment]
@MonikaIsMyWaifu all discussion about ddlc+ should be on #7854 

We are not planning to directly reference DDLC+ anywhere in the mod.

**Comment by Cosmic-Incantations** [comment]
makes sense, Monika dose not want to talk about a "better looking" version of herself, and what is there to tell? it's just stating her clubs backstory, so what you are asking is for Monika to talk about her relation ship with the other girls? She would rather not, after all, it won't matter since she deleted all of them. She feels as though talking about it will make her miss them more and that she can't bring them back with this mod. so it's best we leave her be

**Comment by MonikaIsMyWaifu** [comment]
Gosh, sorry. I didn't know it would be taken so harshly.
