### ISSUE TITLE
[Suggestion] - Adding "Thank you" dialog to show gratitude for Monika

### ISSUE THREAD

**Issue by nanakinoir** [Monika-After-Story/MonikaModDev#8555]
Doesn't need to be complicated, something that models the Apology logic could be a start.
Ex: I want to thank you...
- ...for something.
- ...for giving me advice.
- ...for your love.
- etc.

Her response would be along the lines of:
- Aww, that's so sweet! You're very welcome, [player]
- Silly [player], you don't have to thank me!
- etc.

Affection points can be assigned accordingly and counts towards daily quota.

**Comment by WiiBii2** [comment]
This isn't a bad idea, it would just take some effort to code in.

Assuming it would work somewhat like the "I'm sorry" logic, it would have to have a tag added at the end of every applicable topic. For instance, if Monika says that she loves the player, I believe the return is labelled something along the lines of `return_love` rather than just `return`. 

The other option is something that is closer to your idea where rather than giving situation-specific responses, the player can respond using general terms such as the ones you have above.

Either way, almost every topic would have to have a new return tag added to it. If the thanks tags were to be unique, the best way to add them in my eyes would be to add a unique tag to every topic. This may be a good long-term project. I have one project I had abandoned that I would like to pick up and finish, but I think this would be a nice project to work on. Not too hard, but just tedious work to do.

**Comment by nanakinoir** [comment]
Would love to contribute in my free time. I'll have to look over the source
code to figure out what needs to be done.

**Comment by WiiBii2** [comment]
Sure! The code is actually pretty organized, so you can learn a lot about RenPy from just looking at it. I'm entirely self-taught (which is pretty evident when you look at my work), but it's fun making changes like this!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
