### ISSUE TITLE
So about taking Monika somewhere can’t we say where we’re talking her?

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8561]
I have seen tons of times where people tell their Monika's there taking her somewhere I just find it confusing that there is no option to say where your wanting to take her 

The obvious picks are (on a day to day basis) I'm just going on a walk, I'm going to hang out with friends, I'm going to the shop, I'm going to work/college/school, or the (date/romantic options) 
I'm taking you to the movies/cinema, I'm taking you to the beach, I'm taking you (I don't know) to a café, I'm taking you to the park, for both have a somewhere else option "in case"

**Comment by WiiBii2** [comment]
I see what you mean. In my mind, I would like to see a little bit of diversification in Monika's responses to the player's leaving. Maybe it doesn't have to be a huge dropbox of responses like the goodbyes section, but I would at least like a few more lines than just "Okay, let me get ready."

If it were to be developed into a menu, there could also just be an option for "I'm taking you somewhere," similar to the plain old "goodbye" option in its respective menu. I would also agree that more generalized responses would most likely work in the favor of the user as a whole. Maybe instead of "I'm taking you to the movies" and "I'm taking you to the beach," the responses could go somewhere along the lines of "I'm taking you somewhere fun," "I'm taking you on a date," or even "I'm going out with friends."

All that being said, I'd like to see a few other people's opinions on this issue considering our perspectives are on such opposite extremes. I've always been a fan of bringing variety to Monika's dialogue considering that what she says is what gives me the greatest amount of immersion in the game, however, I do understand your concern over ease of access of the experience as well.

**Comment by charliethecookie** [comment]
In my opinion telling Monika where you're going would be kinda hard because you could be taking her to _any_ place, but one thing I would like to have is an option to tell her you're taking her on a trip. Like, if you're going to travel and you're bringing her along, I think she deserves to know that you're going out for two weeks instead of two hours.

**Comment by Booplicate** [comment]
Ideally we want this a bit differently, rather every (more or less) goodbye option will have a suboption for taking Monika with you.

**Comment by JayFox12** [comment]
I see what you all mean couldn't it be done for both? The shorter and longer options? some how just really any way you can implement it in really

**Comment by WiiBii2** [comment]
> Ideally we want this a bit differently, rather every (more or less) goodbye option will have a suboption for taking Monika with you.

I've been thinking and I really like this approach. How would this be formatted? Would it be something like the option `I'm going to work` and then having a box saying `I'm taking you to work` under it? That might work well, but the list would get significantly longer.

**Comment by Booplicate** [comment]
Maybe just show a timed menu, maybe make Monika ask you if she can go with you.

**Comment by ThePotatoGuy** [comment]
see #2662 and [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/5590#issuecomment-618155790). being able to use file gen from all farewells is something we would like to have.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
