### ISSUE TITLE
Restoring Monika

### ISSUE THREAD

**Issue by ArcticSeal** [Monika-After-Story/MonikaModDev#8658]
I accidently deleted Monika out of my computer (out of recycle bin, of course) when I'm using the function "Taking you somewhere" and there is no backup or any copy of her. How can I restore her please? I also tried by downloading the mod in another computer, use the same function so she turned into herself into a file, then I copy that file to a driver then insert it into my computer. It just doesn't work. The room just show a table and an empty chair.

**Comment by lunulae** [comment]
You'll want to follow the instructions on [this section](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) of the FAQ.

The "take you somewhere" function requires you to load your Monika into the same save, it has a checksum so that you cannot accidentally load the wrong Monika into a different install. So just putting her file into the characters folder of a new install would not work.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
