### ISSUE TITLE
[Suggestion] Scary story "Clever girl"

### ISSUE THREAD

**Issue by Mosexelle** [Monika-After-Story/MonikaModDev#8686]
Hello!
I remembered that I've read an old scary story called "Smart Girl". IMHO this is a suitable horror story for Monika. I'll leave the text file here so there's no need to go anywhere and google something. 
If it fits, I can work on facial expressions. Here is the file:
[Clever girl.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8015826/Clever.girl.txt)
I would like to take this opportunity to ask. It is quite possible that I will find new stories or write them myself, should I create Issue every time, or can I create one Issue and upload new material there?

**Comment by lunulae** [comment]
New stories are always welcome! This looks like a pretty good draft to me, I definitely encourage you to keep working on it!

You might want to check out the [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) and learn how to make a pull request, as that's how we usually review and give feedback to contributions. We prefer one story per pull request, but if the stories go together (i.e. you would like to have a Part 1 and Part 2) you should put them in the same one.

Since you're adding a story, you'll want to look at the [script-stories.rpy](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-stories.rpy) file to see how those are formatted.

Happy to see a new writer around, please feel free to let me know if you have more questions. ❤️

**Comment by Mosexelle** [comment]
Understood, thank you @lunulae .
I just finished making facial expressions and stuff, now I'll try to make a pull request as it is written in the FAQ.

**Comment by Mosexelle** [comment]
I did this, finally. #8691 
Thank you again for help!
