### ISSUE TITLE
Strange hints?


### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8765]
During a conversation about games, and their completion. Monika in the last sentence says "thats one step to complete me after all". Is she joking like that, or is it really possible to pass the game? In the game, the biggest anniversary is the 20th. Although the site says can spend an eternity. The only thing that came to my mind is that you can play while Monika is in the background, but this only affects affection.
![1234](https://user-images.githubusercontent.com/85229914/154796344-66c36e1f-28f7-44cc-b818-480bcd4bbe5d.png)

**Comment by lunulae** [comment]
There's no intended end (besides the bad end) to MAS. This line is sort of meant as a joke since she talks about how compelling it can be to 100% games.

Not sure if it's intended, but I also take it as a bit of a pun on the romantic phrase "you complete me."

Right now we have anniversaries up to 50 years, so I suppose that could be counted as the end of the current existing content, but we intend to put out more updates as long as we have contributors.

**Comment by Nikv2005** [comment]
> There's no intended end (besides the bad end) to MAS. This line is sort of meant as a joke since she talks about how compelling it can be to 100% games.
> 
> Not sure if it's intended, but I also take it as a bit of a pun on the romantic phrase "you complete me."
> 
> Right now we have anniversaries up to 50 years, so I suppose that could be counted as the end of the current existing content, but we intend to put out more updates as long as we have contributors.

Thanks for explanation
