### ISSUE TITLE
[Suggestion] - Dialogue - Asking Moni for a Shopping List

### ISSUE THREAD

**Issue by WishStone-Dragon** [Monika-After-Story/MonikaModDev#9013]
I saw something for this in the code already - Moni leaving us a list of requests in the Character folder.
A chat section in "Monika..." might be nice to ask Monika if she'd like us to get her more of anything. (If we need a writer, I will chain myself to that task. I mean, I suggested it x3)

I noticed that Moni isn't having hot chocolate in the evenings anymore, but if she mentioned wanting more, I must have missed it.

**Comment by Justformas** [comment]
I agree and I also think this list should include things that we haven't given to her yet, so that there's an in-game way to figure out what gifts you can give her without having to look them up. I'm not saying that this list should include all possible gifts (or at least, not right away), but gradually over time it should mention more types of gifts.

Monika could also say something like she doesn't want you to feel "obligated" to get these things, but that it would make her happy if you did.

**Comment by lunulae** [comment]
In regards to the hot chocolate, she only has it on winter nights. Since the northern hemisphere's ticked over to spring, she won't be having it for a while.

I'd definitely be interested in being able to ask her ourselves, especially for those who use Auto dialogue and might have missed what she asked for.

**Comment by Booplicate** [comment]
Wanted this for a while, might get in in next release.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
