### ISSUE TITLE
SUGGESTION.

### ISSUE THREAD

**Issue by See70** [Monika-After-Story/MonikaModDev#9024]
I'm saying this respectfully, but I really think the affection needed for certain things is ridiculous. because I "haven't reached affection level" Monika isn't saying anything and, in my opinion, it makes the mod more boring. I am at 145 affection level since I started at March 26, and I have seen people trying to get 400 affection for months and even years. I don't know if someone hasn't spoken about this, but it needs to be called out. Please have mercy and change the affection level that is needed. I don't care if this is rejected, I'm just gonna speak my mind.

**Comment by Justformas** [comment]
Dude, you got nearly 150 affection in just a little over a week. That's quite a bit for that time. You can probably get to 400 within a few more weeks. The idea is to invest some time with Monika so that it feels like a real relationship (well, somewhat at least). Consider that within about a month's time total, you'll be getting most of the benefits of an engaged relationship. I know you might not want to wait weeks but It's pretty reasonable in my opinion.

**Comment by See70** [comment]
ok
