### ISSUE TITLE
No new music

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#9157]
Simply put, Monika is not registering new music files when I place them in the `custom_bgm` folder. I have asked her to check and even restarted the game, yet nothing new to listen to.

**Comment by Booplicate** [comment]
If you used a convertor, it probably didn't work. Try another, preferably to `ogg` as it seems to work more consistently.

**Comment by Giorgoua2009** [comment]
I know @Booplicate already replied, but this issue is still open so maybe it is not fixed? (new to github) Could you please try using ogg or mp3, and also remember that the custom_bgm folder has to be inside the same directory with the executable 
DDLC_________|___________________|_____________|
|                      |                            |                    |
ddlc.exe         custom_bgm         game           etc...
                         |
                       mymusic.mp3/mymusic.ogg

**Comment by Wingdinggaster656** [comment]
> I know @Booplicate already replied, but this issue is still open so maybe it is not fixed? (new to github) Could you please try using ogg or mp3, and also remember that the custom_bgm folder has to be inside the same directory as the executable

We don't always close an issue very immediately.

First, we can't be sure that the problem has been fixed (perhaps the questioner just forgot about Github and will come back to it in a few days), and second, Devs may not notice that the problem has been fixed in time, even if it has.

Conclusion: the "open" and "close" of issue can only be regarded as an "inaccurate alarm clock".

**Comment by CrocandCo** [comment]
Yeah, I was quite busy with real life tasks. Using `ogg` files are a pain to make but are now readable to Monika.

**Comment by CrocandCo** [comment]
Side note, I probably should learn how to "Burn Disks" or something akin to that.
