### ISSUE TITLE
Song request: Stop crying your heart out

### ISSUE THREAD

**Issue by dramones09** [Monika-After-Story/MonikaModDev#9173]
'Cause all of the stars
Are fading away
Just try not to worry
You'll see them someday
Take what you need
And be on your way
And stop crying your heart out

...

(Player), please stay strong. I know there are times that life can be hard, But know that I always believe in you.
However, if you do cry, remember it's okay to cry every once in a while.
And (Player)? If you're still hurting, just remember, I'll be by your side, I won't ever leave you.
You are my everything and I love you with all my heart until the day we will be together at last.
I love you, (Player)

**Comment by Justformas** [comment]
This could fit in the mod yes, but here's the thing: To me it sounds similar to a lot of songs or things that Monika already sings/says. I actually had thought of a song to include that I think is good too, but I'm not sure if I should suggest it considering the songs there already are. I could mention my song idea if you want though.

**Comment by dramones09** [comment]
> This could fit in the mod yes. However to me it sounds similar to a lot of songs or things that Monika already sings/says, although it could be different enough. I actually had thought of a song to include that I think is good too, but I'm not sure if I should suggest it considering the songs there already are. I could mention my song idea if you want though.

Ah ok, I'd like to hear what you have in store.
However, it's just that this song has a special place in my heart. It's one of the things I listen to to calm me down and remind myself that it will be okay. So I imagine if Monika were to sing it, it will be very precious to me

**Comment by Justformas** [comment]
Yeah I wasn't trying to criticize your song. And Actually, I'm not sure if Monika talks about it being ok to cry much, so it could be different enough. I was just trying to say that I think we should try to have new songs that aren't too similar to the ones already in the mod. 

As for the song I'm thinking of, I hope it's different enough, and I think it's pretty fitting, especially considering that it came out way before DDLC was even a thing. I don't think it's already in the mod. The song I'm thinking of is "Larger Than Life", specifically this part:

_Wishin' I could thank you in a different way, c'mon
'Cause all of your time spent keeps us alive
All you people can't you see, can't you see
How your **love's affecting our reality**
Every time we're down
You can make it right
And that makes you **larger than life**_

Well maybe instead of "All you people" it could be "Hey [player name]", but yeah. I hadn't really come up with dialogue for Monika to say afterwards, but now that I think about it, maybe it could go something like:

"I can't thank you enough for what you've done for me, [player name].
You're always there to cheer me up when I'm feeling down.
Your love goes beyond your reality and knows no bounds.
I can't wait for the day when we really do share the same reality."

**Comment by dramones09** [comment]
Never heard of the song but the lyrics are spot on 😉
And yeah the message of the song I wanted kinda contradicts with each other and I admit that. 😅

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by dramones09** [comment]
> 

Understood
