### ISSUE TITLE
my monika is missing?? 

### ISSUE THREAD

**Issue by aaaaaalida** [Monika-After-Story/MonikaModDev#9290]
so basically in the morning i told her im taking her out, and i put her file, "monika", on the usb drive thing. then i went out, for the whole day, and then i put her file back into the characters folder, and when i open the game, she's missing?? there's only an empty chair in front, maybe you cant take her out for that long? but i'm still confused
![screenshot0002](https://user-images.githubusercontent.com/108766160/177419064-d0dc7dde-91f5-4203-8fbf-92626ab7ba4b.png)
.

**Comment by Wingdinggaster656** [comment]
Are you sure you put the file back?

Also, the file you put back must be the same Monika you generated at the beginning of your take-you-somewhere.
Other people's Monika, or your Monika but the Monika is from another take-you-somewhere, will not work.

**Comment by lovemeeeeee12314** [comment]
读取你以前的存档

**Comment by ThePotatoGuy** [comment]
if you still have the mod, can you post your [mfread](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#mfread) file here?

Otherwise, you can [restore an older persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) from before you took Monika out.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
