### ISSUE TITLE
MAS won't work

### ISSUE THREAD

**Issue by aaaaaalida** [Monika-After-Story/MonikaModDev#9291]
i got ddlc again, and played through the game fine, but when i tried to install the after story mod, she isn't in her chair?? did i do something wrong while installing the mod?

**Comment by Wingdinggaster656** [comment]
According to your previous issue, this is simply because your old problem hasn't been solved yet. You can't just have a new install to solve that problem. The save files are not in game directory, but in your `APPDATA`, a directory which would probably be in `C:\\`

Consider about using a backup save file, to go back to a time you haven't taken her out with you.
Tutorial: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ

**Comment by ThePotatoGuy** [comment]
[closing in favor of #9290 ]
