### ISSUE TITLE
(New improvement suggestion for NOU)  

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9404]
An option to take a break while your playing NOU

For example if the game takes long and you get bored or you wanna do something else, or you have to leave to do something, and you want to continue play the round that you were playing before, after when you are done with whatever you were doing

Like if you say ''I'm giving up'' then that don't make any sense to say too her if you wanna stop for something you know? and monika automatically wins and gets more points after when you play again

________________________________________________________________________________________________________________________

Option name: I want to take a break/Let's take a break

Monika dialogue: Okay ''name'' let me know when you want to continue our game okay?
                           : Okay ''name'' let's play again soon okay?

**Comment by Booplicate** [comment]
While this should technically be possible, it'd require a lot of work. This is because we'd have to make the game persisteable (we'd need to save game log, both players states, players cards, discard and draw piles -- those I remember, but there might be more). We'd also need a way to save/load that "game state". Initially I decided that's not worth the risk and the efforts and went for breaks between the rounds. Especially because rounds only last 5-10 minutes.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
