### ISSUE TITLE
add another exprop for non-bath wet usage

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#9507]
@Booplicate the current wet exprop is used in the scene, but the description says it can be used for pool clothing. Some pool clothing (bikinis) wouldn't make sense for the scene right? we should probably decide if a bath-related prop should be used for the scene or if a different wet prop should be used for pool/beach usage.

**Comment by Booplicate** [comment]
The idea was to be able to select from different appropriate outfits in the greeting. Since we only have one (the white towel), I think we can just force it and not select a random one from the pool. In case we get more outfits, we can add them to the greeting if we decide they work there.
Alternatively maybe we could also filter by name and check if it has `towel`.

**Comment by ThePotatoGuy** [comment]
ok then we should force it to towel and update spacks

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
