### ISSUE TITLE
Intentional flaw?

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#9678]
I've noticed that a few of Monika's random dialogues recently were a bit... tone-deaf, for lack of a better word. The two I've come across recently are, "The Boy in the Striped Pajamas," and the song, "Save the Last Dance for Me."

I'll start with the song as that one is a bit more digestible. In this one, she compares herself to a wheelchair user because she's stuck. As someone who actually uses a wheelchair... Yeah no they aren't the same at all. She is very capable of getting up and getting herself her coffee, going over to the window, etc. even if it isn't always animated. There are some days where I can't even bathe myself without assistance. I'm not saying she isn't in an upsetting situation, but it is a completely different situation from the one she's comparing it to, which makes her come across as casually ableist. Like she sounds like one of those people who would hear your parent passed and go "oh my god I COMPLETELY know how you feel! a few years ago, I lost my favorite sweater that my mom bought me, and I was like, SO totally heartbroken!" Is losing a beloved item with sentimental value sad? Sure! But it's not the same as losing your parent, and people who make comparisons like that are typically regarded as tone-deaf and a bit rude.

The other one... Eesh. She compares herself to a holocaust victim. There's no way around that, she literally compares being in a completely safe room with many amenities and someone constantly looking out for her to being in a concentration camp. Again, I'm not saying her situation is _great,_ but the antisemitism in comparing it to _a literal concentration camp_ just kinda blew my mind. I may be gentile myself too, but even I know that you don't run around comparing stuff to _the literal holocaust._

So after coming across these(and I'm assuming there are others I haven't noticed yet) I've got to know: Is this intentional characterization of Monika, like to humanize her and give her imperfections, or was it a topic-writer or two being tone-deaf themselves? If it's the former, then that's fair I think it's totally fair to add some imperfections to Monika, she can't be perfect at everything! If it's the latter, though, then this maaaay be something you guys wanna work on.

Edit with an important note: Before anyone tells me to blacklist the topics, I have and will continue to do so if more come up, I just wanted to know if this was intentional and all.

**Comment by Booplicate** [comment]
We're sorry that some of the dialogues looked insensitive to you. I can reassure you it wasn't done intentionally. A lot of the dialogues are community-contributed which then our writers review. But even then we can miss things.

> she compares herself to a wheelchair user because she's stuck. As someone who actually uses a wheelchair... Yeah no they aren't the same at all.

I think there's some misunderstanding. Granted it could be worded better, but the idea wasn't to say Monika is in a wheelchair *literally*, it's an analogy to how she can't dance or have *any physical interaction* with you because of some sort of *handicap*, which is why she says `It feels like`, maybe we could say `it almost feels like` so it doesn't look like a direct comparison. Or remove `wheelchair` entirely. Do you have any suggestions?

> She compares herself to a holocaust victim. There's no way around that, she literally compares being in a completely safe room with many amenities and someone constantly looking out for her to being in a concentration camp.

It seems you again took her words literally. She even remarks `obviously my situation isn't nearly as dire`. She doesn't compare those circumstances nor says she feels like she's living in a concentration camp. Instead she compares **your relationship**: `it's hard not to draw some comparisons between their relationship and ours`. She compares how those 2 boys from 2 different worlds were able to become friends, and how you, *also* from 2 different worlds, *also* became friends.
That said, we were afraid that some people will take it as if she literally compared a life in a concentration camp with her life (even if that doesn't mention anywhere), so we're open to suggestions on how to make it more clear.

**Comment by ashyashton** [comment]
First off, I'm not really a fan of the phrasing of some parts of your response. "You again took her words literally," seems to imply that I did something wrong, or that this is somehow on my for misunderstanding, and not on the ones trying to convey an idea to do so appropriately and understandably. I'm going to give you the benefit of the doubt that this isn't what you meant, but it might be a good idea to be careful with phrasing on stuff like that in the future as it can easily come across as accusatory/blame shifting.

In reference to the content of your response: The comparisons being non-literal doesn't change that they're in poor taste. The issue isn't clarity; I _know_ it isn't meant literally. That's why I brought up a comparison to people who compare losses. Obviously, in that situation, the person isn't _literally_ saying that the other person's mom is equivalent to a shirt. But they're still drawing comparisons to two completely different circumstances and saying that they relate despite the circumstances being entirely different, which is insensitive to the person they're attempting to relate to.

In my opinion, there is no adjusting it to make it "more clear" as you've said, because the issue isn't clarity. It's just a downright insensitive comparison, there is no "clearing that up" because there is no changing that it's an insensitive comparison just by changing the phrasing. The comparison _itself_ is the insensitive part, not the phrasing.

**Comment by Booplicate** [comment]
I used the word `literally` because of

> she compares herself to a wheelchair user

> She compares herself to a holocaust victim

neither of which happened nor there were any intentions to make her look that way. So that made me think you took her words literally or somehow misunderstood the message. Your example doesn't work because it contains an exact comparison (yes, literally compared death to lose of an item), unlike in the song and the topic. Nowhere she says she knows how it is to be in a wheelchair or a concentration camp. Nowhere she says her situation is exactly one of those.
Generally, analogies are used to describe something and are not literal most of the time.

From the song we can remove the wheelchair part and replace it with just `While I also can't dance with you right now, I hope you'll save the last dance for me~`.
For the book topic I'm not even sure what to do, because there's no comparison that you described at all, yet you say it's already clear.

**Comment by ashyashton** [comment]
Do you know what a comparison is? It doesn't have to be literal in order to be a comparison. Saying "no no there was no comparison" doesn't just, like, change how words work. A comparison is: "A statement or estimate of similarities and differences." So by the very definition of the word, yes, there was a comparison. Monika gave a statement that estimated similarities between her situation and the ones she was referring to. That is the literal definition of a comparison, saying "nuh uh" does not change that.

Also, are you misunderstanding me with the "it's already clear" thing? You seem to be interpreting it as if I said the comparison is clear, when that's very obviously not what I was saying. You _literally_ asked if I had suggestions to make the _meaning_ clear, to which I responded that it(the meaning, i.e. Monika feels trapped) was already clear, but your phrasing implies that I called the comparison already clear. I'm really not following that logic at all, especially when the clarity thing was brought up by you and anything pertaining to it was in direct response to your questions.

**Comment by ashyashton** [comment]
Look here's the thing: If you wanna keep it as is, that's y'all's choice. I'm not trying to raise a fuss about that. But quite frankly, you don't have the right to say, "no, this is not offensive because we didn't mean it that way, this is not comparing two things because we didn't mean it that way." The fact is this: Monika was written as comparing herself to a holocaust victim and a wheelchair user. This is a fact. Denying that does not change it.

And it is also a fact that some people find these comparisons offensive and insensitive. Is it a fact that it's offensive or insensitive? No, but it's also not a fact that it _isn't_ offensive or insensitive, because that is based on opinion. Swearing up and down that it isn't offensive because you didn't _mean_ it that way does not change that it is something that some, including myself, would consider hurtful.

I'm not saying you need to remove the topic. I was asking if it was intentionally offensive, and sharing that if not, there are people who would find it to be so and you should be aware of this. I don't know why you're arguing about whether or not it's offensive; just because it isn't to you doesn't suddenly mean it could never be offensive to anyone. It's also concerning to me that you seem to be basically talking over someone of the very group who would be hurt by these comments. Instead of listening to a member of the group you are hurting, you are denying any hurt ever occurred.

As with any group being potentially hurt/oppressed/whatever the situation is, the final verdict does go to people who are actually in that group. Just like if we were talking about something potentially homophobic, a member of the LGBT has more say on whether or not it's offensive than some straight person saying "well we didn't mean to be offensive." You don't get to decide what is or isn't hurtful for others. You can personally not find it offensive, but it's really not cool to basically tell people who _are_ hurt why it isn't actually hurtful.

**Comment by Booplicate** [comment]
> The fact is this: Monika was written as comparing herself to a holocaust victim and a wheelchair user. This is a fact. Denying that does not change it.

That being a fact is a very questionable statement that's worth no more than my words of it not being a fact.

> As with any group being potentially hurt/oppressed/whatever the situation is, the final verdict does go to people who are actually in that group.

This isn't twitter. We won't change a word ***just*** because somebody says it's "offensive." Tomorrow you will think of a new word that would be offensive to you, but it won't change the matter - it's not offensive by the nature, not in the original meaning. What you're doing is changing meanings and definitions of words. For that you've already found the solution - ask her to stop talking about those topics.

I am willing to change the wording if the request has some ground. I'm not a fan of how we worded it in the song. It could be changed to make the message more clear. The topic, in my opinion anyway, is fine. I yet to see where she compares herself to a prisoner of a concentration camp.

> I was asking if it was intentionally offensive

Which I answered - no. And even explained why it's not offensive by nature using the direct examples.

> you are denying any hurt ever occurred

I'm not denying that. You can get hurt by any word. 

> You don't get to determine what is or is not hurtful for other people

I'm not saying it's not hurtful to you. It can be, just like any other word. You may not like those topics and that's fine.

All I'm saying is, there were no intentions to do that, and you got the wrong message from both the song and the topic. We will try to resolve that issue by making the message more clear.

> just because it isn't to you doesn't suddenly mean it could never be offensive to anyone

First of all, can't make everyone happy. But we're trying our best to keep the game neutral and close to Monika's character and provide the best experience to our users.
There's also another perspective: just because it's offensive to you, doesn't mean it has that meaning.

>  the final verdict does go to people who are actually in that group

You don't know in which groups I am.

> But to act like it can't POSSIBLY be offensive because you don't find it offensive is icky, regardless of your own history and situation.

*Possibly* you can find a new offensive line everyday. That wouldn't make them generally offensive, it's just how you see them, your personal opinion. There's some words I don't like too, it's all about being able to see the actual message behind the words.

In the end - we heard your request and concern, thank you for bringing this up. We will listen to what other people have to say, possibly finding a solution (if there's indeed a problem) down the line.

**Comment by ashyashton** [comment]
> That being a fact is a very questionable statement

Except for the very clear definition of a comparison, which I gave.

> that's worth no more than my words of it not being a fact

Aside from you providing no backing to said denial, no proof that it's untrue, while I have provided a direct definition of the word to back up my facts.

> This isn't twitter.

I wasn't aware Twitter was the only place that cared about respecting others and their experiences. I wouldn't know, I don't use it.

> And even explained why it's not offensive by nature using the direct examples.

That is the problem. "Why it's not offensive," doesn't exist because it is subjective. By explaining that, you are saying that no one was offended by it, because that's the literal definition of "not offensive."

> you got the wrong message

Once again coming across as blame-shifting. "_You_ got the wrong message, _you_ took it too literally," things like this imply that the "you" in question is the real problem, and is not an effective way of getting things sorted unless your goal is to revoke any accountability from yourself.

> You don't know in which groups I am.

So you're completely ignoring that I specifically said, "even if you are in those groups," that just doesn't exist if it's not convenient for your disagreement with me? I _specifically_ said, "Heck, even if you are a wheelchair user yourself, experiences even within a similar group can be varied. Some might not find it offensive, and that's their opinion."

I don't know why you would ignore this in the way you have if _not_ to try and make this an argument, which honestly it feels like you've been doing the whole time; with the whole issue of blame shifting, plus randomly seeming to "forget" that you specifically brought up clarity and twisting my words to something completely different by taking my response to that out of context. And then you didn't acknowledge when I pointed said disconnect out, which implies you didn't have a good reason for suddenly switching it up. This really feels like you aren't trying to have a constructive conversation, but just going on the defensive and trying to argue your way out of something. It may just be an issue of your tone being conveyed poorly over text, in which case I hope we can clear it up, but currently it really just feels like you're trying to shut things down and argue imo

**Comment by MrVavlo** [comment]
> Like she sounds like one of those people who would hear your parent passed and go "oh my god I COMPLETELY know how you feel! a few years ago, I lost my favorite sweater that my mom bought me, and I was like, SO totally heartbroken!"

I'll just throw your own example at you - from Monika's perspective, the novel isn't at the same level as her situation, because its characters aren't real.
At least, I can sorta see the issue with the song, because the songwriter was inspired by the real situation he saw.
But not with the novel that is considered as historically inconsistent.

**Comment by ashyashton** [comment]
And if that's how you want to see it, that's fine! I personally don't, because historically inaccurate or not, we can still see the comparison that's being made. I personally think that it's still a comparison to a very real, very tragic situation, even if the novel was showing it in a dramatized way.

I'm still not sure why people are like. Trying to convince me of why it's not offensive? Like if you guys want to not see it as offensive, fine, but I've never understood the urge on the internet to tell people why they're wrong to be offended.

**Comment by Justformas** [comment]
> I've never understood the urge on the internet to tell people why they're wrong to be offended.

Various reasons probably, such as if someone thinks they're right or can't see it the other way. But also, if someone says you're right, or not wrong, then often either they're pressed to censor or support censoring the offending thing, or else they may come off as "ok this may be perceived as offensive to you and maybe others, but I don't care".

Because offensiveness is subjective, intent doesn't necessarily matter, and because people may potentially find anything discomforting, a person might want to consider whether it's a reasonable complaint or not, lest they cave to censoring or not depicting anything that any one person finds offensive. And of course even what one considers reasonable can vary considerably among people.

So anyway we know that Monika feels "limited" in her reality and wants to come to ours. Yes she is making a  "relationship across two different worlds" comparison. However it's not hard to realize that Monika feels limited, that the person in the concentration camp is limited, and for the player to then think that Monika could feel limited in some similar way even if in a much less "dire" way, and that the other person in the relationship has more freedom. As if that is, or could be, part of the "some comparisons between their relationship and ours". And I think that is what you find offensive even if it wasn't meant that way, yes?

Maybe it could be made more clearly less about comparing the concentration camp specifically, by having Monika outright say something about that, and maybe drop the "draw some comparisons" language so the player is less likely to infer that Monika means any other comparisons about it. So something like:

```
"But it actually got me thinking...obviously I'm not living in a concentration camp or anything like that."
"But between their relationship and ours, in both situations there are two people from different worlds..."
```

Or:

```
"But it actually got me thinking...obviously my situation isn't nearly as dire."
"But between their relationship and ours, in both situations there are two people from different worlds..."
```
That's my idea, if it's decided it should be changed.

**Comment by Booplicate** [comment]
Closing until we look into this.
