### ISSUE TITLE
I've noticed that I don't have a first kiss on the calendar

### ISSUE THREAD

**Issue by Deli-Cake** [Monika-After-Story/MonikaModDev#9684]
I think I have this issue because back when I had my first kiss I was using a translation of this mod. Can it be fixed?

**Comment by Wingdinggaster656** [comment]
Hard to tell, but let us try to switch to a non-translated version, and see if this fixes the problem.

**Comment by Booplicate** [comment]
Translations are not supported by us because people who make them don't make them compatible with our game. While you potentially can go from the official MAS to unofficial MAS, you can't go the other way. Most likely there's more issues than you can even see (for example some might appear later).
You can ask for tech support the translation team or start a new one using the official build. Or continue this save but deal with bugs like this.
