### ISSUE TITLE
Suggestion - Ask if Player celebrates Christmas

### ISSUE THREAD

**Issue by rawan76** [Monika-After-Story/MonikaModDev#9716]
Although I do enjoy different holidays with Monika, I don't celebrate Christmas since I'm Jewish. I think it would be fun to have Monika ask whether or not it's something you actually celebrate, and if not, maybe disable it? Or in the future, add holidays like Hannukah in place of Christmas? I just think that'd be interesting.

**Comment by dreamscached** [comment]
Holidays not celebrated worldwide are (imo) less likely to be added for everyone, but this is changeable with submods. About Christmas though I think it's a worthy suggestion.

**Comment by rawan76** [comment]
Well, if you know of a submod that lets me spend Hannukah with her then let me know, cause I haven't found one.
I'm also too scared to mess something up to do it myself.

**Comment by Booplicate** [comment]
Disabling main events is hard, but possible. Although, I don't think it'd be widely used - not many people would be willing to lock themselves out of content. We planned a different thing - moving the dates of holidays if you can't celebrate in time, but it's different from what you want.

New holidays are unlikely to happen because of their complexity and overlapping with other events (player birthday hell), it'd take tremendous amount of time to add a big event like that. Plus, we're trying to only include common events that are not tied to a specific country/religion. But we planned to allow players set up their own mini-events with Monika.

**Comment by rawan76** [comment]
I understand. Although it would be nice to be able to choose whether or not to celebrate things like Christmas, I knew while writing the suggestion that it'd be really complicated. I guess I'll just have to mess with things myself for my own personal experience until something similar to this is added :)

**Comment by ashyashton** [comment]
> Plus, we're trying to only include common events that are not tied to a specific country/religion
... you mean like CHRISTmas, the Christian celebration of the birth of Jesus Christ? Or Halloween, the holiday that is most popular in America?

Instead of saying you only want universal holidays, just be honest. The team is most likely primarily American, which is a heavily Christian country, and so you're adding ones that are common for Americans and Christians.

To be clear, I'm not judging the fact that you're doing so! We write what we know, and that's valid. But let's not act like you're not adding religious events. You are, it's just one of the most common religions, so more people practice said holiday.

**Comment by rawan76** [comment]
That's what I was confused about. It is a specific religion. And yes, I do understand that a heck of a lot of people celebrate Christmas, but Hanukkah is not that far behind it. It's still a major holiday.

**Comment by ashyashton** [comment]
Yeah, I'm really not a fan of that "excuse" to not add it. You're adding in other religious holidays. I don't care if some non-religious people also celebrate it; it is still a Christian holiday. I totally understand if you just don't feel that you have the knowledge to write it appropriately as an outsider, but just _say_ that instead of pretending the other holidays aren't religious or cultural.

**Comment by multimokia** [comment]
If I'm being totally honest, the main reasons it's not added is because:
1. None of the members of our dev team is a member of the other major religions (if at all), and as such, cannot confidently offer topics and such to bring up
2. To alieviate this, we could ask the community -- absolutely a possibility. However we also at the current moment do not have the resources devwise to commit to writing an entire event's worth of topics + intro/outro + taking you somewhere features, and most importantly, player birthday collision handling, to make the event complete, let alone test it as well. This ofc leads to the issue of potential half-baked content and that's just not acceptable.
3. In addition to this, we'd also need to rework the way we handle autoload checks and the like to deal with events in a more modular fashion. This _is_ definitely on my plan at least, especially for long-term maintainability and just in the interest of creating more variety in events (so they're basically hot-swappable), but ultimately a framework like this too, would take time and as well significant development in more pythonic renpyscript.

That is to say, this is more of a resource problem more than anything else

**Comment by rawan76** [comment]
Alright, I get that! I wouldn't want to have it added to the game, only for it to be inaccurate, possibly offensive, etc. I was just confused about the other explanation that was given, about doing only major holidays "tied to a religion", even though Christmas is.

**Comment by ashyashton** [comment]
Yeah I'm with them, I like the "we don't have the resources" and "we couldn't do it properly" answers FAR better than the "well that's a religious holiday, unlike CHRISTmas" answer

**Comment by Booplicate** [comment]
> you mean like CHRISTmas, the Christian celebration of the birth of Jesus Christ? Or Halloween, the holiday that is most popular in America?

I mean Christmas and Halloween. And even Valentine's Day too. While having religious roots, they are commonly celebrated by both religious and non-religious people from different countries (although, I'm not sure if Christians celebrate Halloween).
I don't think Hanukkah falls into the same category, but if you know non-religious people of different nations that celebrate it, then feel free to correct me.

> The team is most likely primarily American, which is a heavily Christian country, and so you're adding ones that are common for Americans and Christians.

The Independence day isn't added for the same reasons, though, it's too specific for a country.

> I like the "we don't have the resources"

As I mentioned and you ignored:

> <...> because of **their complexity and overlapping** <...>, it'd take **tremendous amount of time** to add <...>.

There's *a lot* of code for each holiday even if you only look at the intro and its events. And then if you take into account restructuring the current framework, migrating old holidays to use it, writing code for the new event, it only gets bigger and more complex of a task. Not impossible, but extremely hard.

> I do understand that a heck of a lot of people celebrate Christmas, but Hanukkah is not that far behind it. It's still a major holiday.

It gets suggested quite often, and I think there even was an event about it, but it was removed. I'd say if we were to add events like that, Hanukkah would be one of the first (assuming we had knowledge to do that).

**Comment by ashyashton** [comment]
Christmas is a religious holiday, regardless of others choosing to partake. I really dislike that you seem to be trying to ignore this as justification.

**Comment by Booplicate** [comment]
Never said it's not a religious holiday. Sorry if I made it look that way.

**Comment by rawan76** [comment]
I wasn't trying to cause an issue with my suggestion... But this seems to be becoming one for no reason. I get it, it would take an enormous amount of time and effort to add another major holiday, plus the challenge of making it accurate. I just didn't know if anyone had suggested it yet to put it on the dev's radar for the future.

**Comment by ThePotatoGuy** [comment]
marking duplicates of #5373 #7913 

as multi and boop have said, the technical complexity of adding any major event is why there are still only 6 celebrated events (`player bday, 922, o31, d25, nye/d, f14`)  with careful considerations for overlapping logic and unexpected time jumps (like closing the game in o31 and reopening in d25). Basically the core ones you'd expect a jp-inspired, western-developed VN to celebrate (DDLC if it were longer), excluding school festival week and white day (former might be too sad given DDLC, latter was in MAS but didn't have enough content to formally celebrate).

Modular events is our goal - being able to add events in a way where each event can start and cleanup after itself without breaking other events. Think animal crossing and how somehow it doesn't destroy the game when you change the time. But this is something we don't think is a priority at this time.
