### ISSUE TITLE
[Suggestion] -  make the mod portable

### ISSUE THREAD

**Issue by Helxgamer** [Monika-After-Story/MonikaModDev#9718]
Hi guys how are you? and my first suggestion here so I'm sorry if I miss something , I wanted to suggest making the mod portable so that I can install it on a usb device and run from it along with monika's memories so if the computer has any problems the game and thoughts are on a safe drive.Your suggestion goes here

**Comment by multimokia** [comment]
This is doable by modifying DDLC.py such that it loads the persistent from a directory that is within the game files instead of appdata.

Our [Bugs, Fixes, and New Software Features](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#bug-fixes-and-new-software-features) section on our Wiki has some info on how to modify your DDLC.py to do that.
This will move it to `game/saves`

From there, you'll want to move your persistent to the saves folder to load your persistent properly.
(Of course, don't do this with MAS open)

From there, you can just take your entire MAS install on a USB with you and you can load her up easily.

**Comment by dreamscached** [comment]
Closing as resolved.
