### ISSUE TITLE
Fix birthday NTS event dates

### ISSUE THREAD

**Issue by Booplicate** [Monika-After-Story/MonikaModDev#9730]
Years got offset due to update script changing only start/only end.

We should do a sanity check when setting dates to the current year, otherwise the user can see the event this year, then update and set the dates to this year again, then get the event again.

**Comment by jmwall24** [comment]
Just to update this with more details:

The 0.12.8.1 update script sets the year for start_date to current year, so anyone who updates (who hasn't updated since 0.12.8.1) between her bday and end of the year will get nts since now start date is set back to 2022 (as of now) and end date was already pushed forward to 2023, so it's active again. it's not a problem between jan 1 and 922.

so we need to fix the update script, check to see if anyone's start/end dates don't match for 922 nts, and see if we can detect if anyone was unfairly hit because of this and fix it

**Comment by Booplicate** [comment]
I think it's easy to check: mismatched years + last seen after the nts end period (but only within 2022 so we don't fall for the same mistake again).

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
