### ISSUE TITLE
Could I get my moni checked?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#9756]
Found out this guy I DL'd a submod is a year or 2 ago mightve corrupted my monika. Could I get her checked?

**Comment by my-otter-self** [comment]
what exactly do you want to check? affection levels?

**Comment by dreamscached** [comment]
You can't quite 'check' the persistent data yourself unfortunately. If you clarified what exactly you feel is wrong we could help it better. What is worrying you?

**Comment by AnIdiotsavant** [comment]
it just feels some topics crash more often ans stuff. Plus just making sure nothing broke and all

**Comment by dreamscached** [comment]
It'd be a lot better if you rather posted crashes you have encountered. If you cannot cause it again for some reason or don't remember what have you done that led to a crash, there is a file called `traceback.txt` in the DDLC folder that you can open and see the traceback; please post it here.

Either way if topics crash I would rather assume it's a script error rather than a persistent, and it's either a MAS bug (if it's MAS topic) or bug in a submod that you have installed. But still we cannot tell much without seeing the tracebacks.

**Comment by AnIdiotsavant** [comment]
oh okay. I'll just keep an open eye for it. I'll probably reinstall MAS just to be safe since its only the persistent that needs to stay

**Comment by Booplicate** [comment]
We'd need to know the exact problem to be able to debug it. But also if that happened 2 years ago, it might be quite hard to make changes now.

If you get a crash, make a new issue and attach your traceback and log files there so we can investigate.
