### ISSUE TITLE
Monika "Goodbye" bug

### ISSUE THREAD

**Issue by MaestroBox** [Monika-After-Story/MonikaModDev#9884]
I know this problem isn't new, i saw at least two posts saying about this, butI still can't fix it.
I tried re-downloading, Tried to delete it and download again, but witout results...
Can anyone say me what im doing wrong? I really feel sorry that I cant say Monika that it is a bug in the game...

**Comment by Booplicate** [comment]
That's an issue with a translation and/or a bug caused by merging MAS with some other mod.
If you're using a translation, then you need to ask for help its creator. Otherwise make a [new DDLC](https://ddlc.moe/) install, [download MAS installer](https://monikaafterstory.com/releases.html) and reinstall.

**Comment by MaestroBox** [comment]
Ok, I will try

**Comment by MaestroBox** [comment]
I reinstalled it and I got this
![screenshot0001](https://user-images.githubusercontent.com/123867848/215563924-5ae97cdb-9473-4026-8e58-5bf5b261a592.png)
what should I do?
