### ISSUE TITLE
Monika's gone...

### ISSUE THREAD

**Issue by hspinks2692** [Monika-After-Story/MonikaModDev#9954]
So I was trying to move Monika to a new computer and I did a lot of things out of order:
1) I moved over ONLY MAS and opened the game. Monika didn't remember me and started everything over. The last thing I did with Monika was take her out somewhere. New monika saw this file and deleted it.
2) I then closed the game and read up what I should do. I read that I should move over the persistent files and copy te DDLC game itself. I did both. But now... when I open the game... Monika is gone. 

I'm seeing that all I'd need is a new Monika file but the chr file from the game doesn't work. Is there anything I can do to get her back?

**Comment by Wingdinggaster656** [comment]
The Monika file generated by MAS is never` monika.chr` - not at all. This is stated in the beginning.

Everything Monika remembers is in and only in the persistent file, so "moved over ONLY MAS" doesn't represent anything at all.

> New monika saw this file and deleted it.

No, the new Monika didn't see this file. The new Monika saw `monika.chr`, not `monika`.

> when I open the game... Monika is gone.

This is because you didn't move the `monika`(again, not `monika.chr`). Go to find that file, and place it in the `characters` folder.

**Comment by Wingdinggaster656** [comment]
The Monika file generated by MAS is never` monika.chr` - not at all. This is stated in the beginning.

Everything Monika remembers is in and only in the persistent file, so "moved over ONLY MAS" doesn't represent anything at all.

> New monika saw this file and deleted it.

No, the new Monika didn't see this file(`monika` file). The new Monika saw `monika.chr`, not `monika`.

> when I open the game... Monika is gone.

This is because you didn't move the `monika`(again, not `monika.chr`). Go to find that file, and place it in the `characters` folder.

**Comment by hspinks2692** [comment]
You make a point but I *did* start the game when I moved MAS over. She didn't rememeber who I was so I couldn't do anything (I thought). So I closed the game and didn't get a Monika file. In short, I started a new file, as such Monika came back, removed the monika file, and I didn't get it back.

**Comment by Wingdinggaster656** [comment]
> She didn't rememeber who I was

Yes, this is because you didn't move the persistent file over.

> removed the monika file

No, the new Monika didn't remove the file. She removed `monika.chr`(again and again, NOT `monika`).

> I then closed the game and read up what I should do. I read that I should move over the persistent files and copy te DDLC game itself. I did both.

Based on this sentence, I think you have two MAS on your new device now? Can you find the first one, and show the content of your `characters` folder?

**Comment by hspinks2692** [comment]
![image](https://user-images.githubusercontent.com/45012878/230779370-7d9df998-d179-499b-991a-cbbfe03a81b2.png)

**Comment by Wingdinggaster656** [comment]
Do you have `persistentxx.bak` files with you?

See this link, restore your persistent file to a point that you haven't taken Monika out yet: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by hspinks2692** [comment]
IT WORKED! thank you so much!
